    



package com.cfcc.itfe.persistence.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;
import java.sql.Clob;

import com.cfcc.jaf.persistence.jaform.parent.* ;

import java.math.BigDecimal;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

import java.io.StringReader;
import java.io.Reader;
import java.io.IOException;

import com.cfcc.itfe.persistence.dto.HtfGrantpaymsgmainDto ;
import com.cfcc.itfe.persistence.pk.HtfGrantpaymsgmainPK ;


/**
 * <p>Title: DAO of table: HTF_GRANTPAYMSGMAIN</p>
 * <p>Description:财政授权支付凭证（8202）主单(历史表) Data Access Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2015-05-13 10:24:22 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dao.vm timestamp: 2007-04-06 08:30:00
 ******************************************************
 * <p> <b>change record</b><br>
 *  make dao methods simply.<br>
 *  especially make update,delete methods simply.<br>
 *  remove "..withCheck" method,withCheck will impl in JAFOrmTemplate.<br>
 *  remove "delete(IDto _dto,..)" method.<br></p>
 * @author db2itfe
 */

public class HtfGrantpaymsgmainDao  implements IDao
{


    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO HTF_GRANTPAYMSGMAIN ("
          + "I_VOUSRLNO,S_ORGCODE,S_TRECODE,S_STATUS,S_DEALNO"
          + ",S_FINORGCODE,S_FILENAME,S_COMMITDATE,S_CHECKSTATUS,S_IFMATCH"
          + ",S_INPUTUSERCODE,S_CHECKSERCODE,S_INPUTRECBANKNAME,S_DEMO,TS_SYSUPDATE"
          + ",S_PACKAGENO,S_ID,S_ADMDIVCODE,S_STYEAR,S_VTCODE"
          + ",S_VOUDATE,S_VOUCHERNO,S_FUNDTYPECODE,S_FUNDTYPENAME,S_BGTTYPECODE"
          + ",S_BGTTYPENAME,S_PAYTYPECODE,S_PAYTYPENAME,S_PROCATCODE,S_PROCATNAME"
          + ",S_MOFDEPCODE,S_MOFDEPNAME,S_FILENOCODE,S_FILENONAME,S_SUPDEPCODE"
          + ",S_SUPDEPNAME,S_AGENCYCODE,S_AGENCYNAME,S_EXPFUNCCODE,S_EXPFUNCNAME"
          + ",S_EXPFUNCCODE1,S_EXPFUNCNAME1,S_EXPFUNCCODE2,S_EXPFUNCNAME2,S_EXPFUNCCODE3"
          + ",S_EXPFUNCNAME3,S_EXPECOCODE,S_EXPECONAME,S_EXPECOCODE1,S_EXPECONAME1"
          + ",S_EXPECOCODE2,S_EXPECONAME2,S_DEPPROCODE,S_DEPPRONAME,S_SETMODECODE"
          + ",S_SETMODENAME,S_PAYBANKCODE,S_PAYBANKNAME,S_CLEARBANKCODE,S_CLEARBANKNAME"
          + ",S_PAYEEACCTNO,S_PAYEEACCTNAME,S_PAYEEACCTBANKNAME,S_PAYEEACCTBANKNO,S_PAYACCTNO"
          + ",S_PAYACCTNAME,S_PAYACCTBANKNAME,S_PAYSUMMARYCODE,S_PAYSUMMARYNAME,N_PAYAMT"
          + ",S_PAYMGRCODE,S_PAYMGRNAME,S_FUNDDEALMODECODE,S_FUNDDEALMODENAME,S_BUSINESSTYPECODE"
          + ",S_BUSINESSTYPENAME,S_TAXBILLNO,S_TAXAYERID,S_TAXORGCODE,S_CHECKNO"
          + ",S_XPAYDATE,S_XAGENTBUSINESSNO,S_XCHECKNO,N_XPAYAMT,S_XPAYEEACCTBANKNAME"
          + ",S_XPAYEEACCTNO,S_XPAYEEACCTNAME,S_BACKFLAG,S_ISRETURN,S_BCKREASON"
          + ",S_REFUNDTYPE,N_BACKMONEY,S_HOLD1,S_HOLD2,S_EXT1"
          + ",S_EXT2,S_EXT3,S_EXT4,S_EXT5"
        + ") VALUES ("
        + "?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT TIMESTAMP ,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";


    private static final String SQL_INSERT_WITH_RESULT = "SELECT * FROM FINAL TABLE( " + SQL_INSERT + " )";
    
    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "HTF_GRANTPAYMSGMAIN.I_VOUSRLNO, HTF_GRANTPAYMSGMAIN.S_ORGCODE, HTF_GRANTPAYMSGMAIN.S_TRECODE, HTF_GRANTPAYMSGMAIN.S_STATUS, HTF_GRANTPAYMSGMAIN.S_DEALNO, "
        + "HTF_GRANTPAYMSGMAIN.S_FINORGCODE, HTF_GRANTPAYMSGMAIN.S_FILENAME, HTF_GRANTPAYMSGMAIN.S_COMMITDATE, HTF_GRANTPAYMSGMAIN.S_CHECKSTATUS, HTF_GRANTPAYMSGMAIN.S_IFMATCH, "
        + "HTF_GRANTPAYMSGMAIN.S_INPUTUSERCODE, HTF_GRANTPAYMSGMAIN.S_CHECKSERCODE, HTF_GRANTPAYMSGMAIN.S_INPUTRECBANKNAME, HTF_GRANTPAYMSGMAIN.S_DEMO, HTF_GRANTPAYMSGMAIN.TS_SYSUPDATE, "
        + "HTF_GRANTPAYMSGMAIN.S_PACKAGENO, HTF_GRANTPAYMSGMAIN.S_ID, HTF_GRANTPAYMSGMAIN.S_ADMDIVCODE, HTF_GRANTPAYMSGMAIN.S_STYEAR, HTF_GRANTPAYMSGMAIN.S_VTCODE, "
        + "HTF_GRANTPAYMSGMAIN.S_VOUDATE, HTF_GRANTPAYMSGMAIN.S_VOUCHERNO, HTF_GRANTPAYMSGMAIN.S_FUNDTYPECODE, HTF_GRANTPAYMSGMAIN.S_FUNDTYPENAME, HTF_GRANTPAYMSGMAIN.S_BGTTYPECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_BGTTYPENAME, HTF_GRANTPAYMSGMAIN.S_PAYTYPECODE, HTF_GRANTPAYMSGMAIN.S_PAYTYPENAME, HTF_GRANTPAYMSGMAIN.S_PROCATCODE, HTF_GRANTPAYMSGMAIN.S_PROCATNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_MOFDEPCODE, HTF_GRANTPAYMSGMAIN.S_MOFDEPNAME, HTF_GRANTPAYMSGMAIN.S_FILENOCODE, HTF_GRANTPAYMSGMAIN.S_FILENONAME, HTF_GRANTPAYMSGMAIN.S_SUPDEPCODE, "
        + "HTF_GRANTPAYMSGMAIN.S_SUPDEPNAME, HTF_GRANTPAYMSGMAIN.S_AGENCYCODE, HTF_GRANTPAYMSGMAIN.S_AGENCYNAME, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE1, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME1, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE2, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME2, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE3, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME3, HTF_GRANTPAYMSGMAIN.S_EXPECOCODE, HTF_GRANTPAYMSGMAIN.S_EXPECONAME, HTF_GRANTPAYMSGMAIN.S_EXPECOCODE1, HTF_GRANTPAYMSGMAIN.S_EXPECONAME1, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPECOCODE2, HTF_GRANTPAYMSGMAIN.S_EXPECONAME2, HTF_GRANTPAYMSGMAIN.S_DEPPROCODE, HTF_GRANTPAYMSGMAIN.S_DEPPRONAME, HTF_GRANTPAYMSGMAIN.S_SETMODECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_SETMODENAME, HTF_GRANTPAYMSGMAIN.S_PAYBANKCODE, HTF_GRANTPAYMSGMAIN.S_PAYBANKNAME, HTF_GRANTPAYMSGMAIN.S_CLEARBANKCODE, HTF_GRANTPAYMSGMAIN.S_CLEARBANKNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNO, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNAME, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNAME, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNO, HTF_GRANTPAYMSGMAIN.S_PAYACCTNO, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYACCTNAME, HTF_GRANTPAYMSGMAIN.S_PAYACCTBANKNAME, HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYCODE, HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYNAME, HTF_GRANTPAYMSGMAIN.N_PAYAMT, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYMGRCODE, HTF_GRANTPAYMSGMAIN.S_PAYMGRNAME, HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODECODE, HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODENAME, HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPENAME, HTF_GRANTPAYMSGMAIN.S_TAXBILLNO, HTF_GRANTPAYMSGMAIN.S_TAXAYERID, HTF_GRANTPAYMSGMAIN.S_TAXORGCODE, HTF_GRANTPAYMSGMAIN.S_CHECKNO, "
        + "HTF_GRANTPAYMSGMAIN.S_XPAYDATE, HTF_GRANTPAYMSGMAIN.S_XAGENTBUSINESSNO, HTF_GRANTPAYMSGMAIN.S_XCHECKNO, HTF_GRANTPAYMSGMAIN.N_XPAYAMT, HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTBANKNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNO, HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNAME, HTF_GRANTPAYMSGMAIN.S_BACKFLAG, HTF_GRANTPAYMSGMAIN.S_ISRETURN, HTF_GRANTPAYMSGMAIN.S_BCKREASON, "
        + "HTF_GRANTPAYMSGMAIN.S_REFUNDTYPE, HTF_GRANTPAYMSGMAIN.N_BACKMONEY, HTF_GRANTPAYMSGMAIN.S_HOLD1, HTF_GRANTPAYMSGMAIN.S_HOLD2, HTF_GRANTPAYMSGMAIN.S_EXT1, "
        + "HTF_GRANTPAYMSGMAIN.S_EXT2, HTF_GRANTPAYMSGMAIN.S_EXT3, HTF_GRANTPAYMSGMAIN.S_EXT4, HTF_GRANTPAYMSGMAIN.S_EXT5 "
        + "FROM HTF_GRANTPAYMSGMAIN "
        +" WHERE " 
        + "I_VOUSRLNO = ?"
        ;
    /* SQL to select for update data */
    private static final String SQL_SELECT_FOR_UPDATE =
        "SELECT "
        + "HTF_GRANTPAYMSGMAIN.I_VOUSRLNO, HTF_GRANTPAYMSGMAIN.S_ORGCODE, HTF_GRANTPAYMSGMAIN.S_TRECODE, HTF_GRANTPAYMSGMAIN.S_STATUS, HTF_GRANTPAYMSGMAIN.S_DEALNO, "
        + "HTF_GRANTPAYMSGMAIN.S_FINORGCODE, HTF_GRANTPAYMSGMAIN.S_FILENAME, HTF_GRANTPAYMSGMAIN.S_COMMITDATE, HTF_GRANTPAYMSGMAIN.S_CHECKSTATUS, HTF_GRANTPAYMSGMAIN.S_IFMATCH, "
        + "HTF_GRANTPAYMSGMAIN.S_INPUTUSERCODE, HTF_GRANTPAYMSGMAIN.S_CHECKSERCODE, HTF_GRANTPAYMSGMAIN.S_INPUTRECBANKNAME, HTF_GRANTPAYMSGMAIN.S_DEMO, HTF_GRANTPAYMSGMAIN.TS_SYSUPDATE, "
        + "HTF_GRANTPAYMSGMAIN.S_PACKAGENO, HTF_GRANTPAYMSGMAIN.S_ID, HTF_GRANTPAYMSGMAIN.S_ADMDIVCODE, HTF_GRANTPAYMSGMAIN.S_STYEAR, HTF_GRANTPAYMSGMAIN.S_VTCODE, "
        + "HTF_GRANTPAYMSGMAIN.S_VOUDATE, HTF_GRANTPAYMSGMAIN.S_VOUCHERNO, HTF_GRANTPAYMSGMAIN.S_FUNDTYPECODE, HTF_GRANTPAYMSGMAIN.S_FUNDTYPENAME, HTF_GRANTPAYMSGMAIN.S_BGTTYPECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_BGTTYPENAME, HTF_GRANTPAYMSGMAIN.S_PAYTYPECODE, HTF_GRANTPAYMSGMAIN.S_PAYTYPENAME, HTF_GRANTPAYMSGMAIN.S_PROCATCODE, HTF_GRANTPAYMSGMAIN.S_PROCATNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_MOFDEPCODE, HTF_GRANTPAYMSGMAIN.S_MOFDEPNAME, HTF_GRANTPAYMSGMAIN.S_FILENOCODE, HTF_GRANTPAYMSGMAIN.S_FILENONAME, HTF_GRANTPAYMSGMAIN.S_SUPDEPCODE, "
        + "HTF_GRANTPAYMSGMAIN.S_SUPDEPNAME, HTF_GRANTPAYMSGMAIN.S_AGENCYCODE, HTF_GRANTPAYMSGMAIN.S_AGENCYNAME, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE1, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME1, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE2, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME2, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE3, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME3, HTF_GRANTPAYMSGMAIN.S_EXPECOCODE, HTF_GRANTPAYMSGMAIN.S_EXPECONAME, HTF_GRANTPAYMSGMAIN.S_EXPECOCODE1, HTF_GRANTPAYMSGMAIN.S_EXPECONAME1, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPECOCODE2, HTF_GRANTPAYMSGMAIN.S_EXPECONAME2, HTF_GRANTPAYMSGMAIN.S_DEPPROCODE, HTF_GRANTPAYMSGMAIN.S_DEPPRONAME, HTF_GRANTPAYMSGMAIN.S_SETMODECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_SETMODENAME, HTF_GRANTPAYMSGMAIN.S_PAYBANKCODE, HTF_GRANTPAYMSGMAIN.S_PAYBANKNAME, HTF_GRANTPAYMSGMAIN.S_CLEARBANKCODE, HTF_GRANTPAYMSGMAIN.S_CLEARBANKNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNO, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNAME, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNAME, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNO, HTF_GRANTPAYMSGMAIN.S_PAYACCTNO, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYACCTNAME, HTF_GRANTPAYMSGMAIN.S_PAYACCTBANKNAME, HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYCODE, HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYNAME, HTF_GRANTPAYMSGMAIN.N_PAYAMT, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYMGRCODE, HTF_GRANTPAYMSGMAIN.S_PAYMGRNAME, HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODECODE, HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODENAME, HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPENAME, HTF_GRANTPAYMSGMAIN.S_TAXBILLNO, HTF_GRANTPAYMSGMAIN.S_TAXAYERID, HTF_GRANTPAYMSGMAIN.S_TAXORGCODE, HTF_GRANTPAYMSGMAIN.S_CHECKNO, "
        + "HTF_GRANTPAYMSGMAIN.S_XPAYDATE, HTF_GRANTPAYMSGMAIN.S_XAGENTBUSINESSNO, HTF_GRANTPAYMSGMAIN.S_XCHECKNO, HTF_GRANTPAYMSGMAIN.N_XPAYAMT, HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTBANKNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNO, HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNAME, HTF_GRANTPAYMSGMAIN.S_BACKFLAG, HTF_GRANTPAYMSGMAIN.S_ISRETURN, HTF_GRANTPAYMSGMAIN.S_BCKREASON, "
        + "HTF_GRANTPAYMSGMAIN.S_REFUNDTYPE, HTF_GRANTPAYMSGMAIN.N_BACKMONEY, HTF_GRANTPAYMSGMAIN.S_HOLD1, HTF_GRANTPAYMSGMAIN.S_HOLD2, HTF_GRANTPAYMSGMAIN.S_EXT1, "
        + "HTF_GRANTPAYMSGMAIN.S_EXT2, HTF_GRANTPAYMSGMAIN.S_EXT3, HTF_GRANTPAYMSGMAIN.S_EXT4, HTF_GRANTPAYMSGMAIN.S_EXT5 "
        + "FROM HTF_GRANTPAYMSGMAIN "
        +" WHERE " 
        + "I_VOUSRLNO = ? FOR UPDATE"
        ;

      /* SQL to select data (SCROLLABLE)*/
     private static final String SQL_SELECT_BATCH_SCROLLABLE =
        "SELECT "
        + "  HTF_GRANTPAYMSGMAIN.I_VOUSRLNO  , HTF_GRANTPAYMSGMAIN.S_ORGCODE  , HTF_GRANTPAYMSGMAIN.S_TRECODE  , HTF_GRANTPAYMSGMAIN.S_STATUS  , HTF_GRANTPAYMSGMAIN.S_DEALNO "
        + " , HTF_GRANTPAYMSGMAIN.S_FINORGCODE  , HTF_GRANTPAYMSGMAIN.S_FILENAME  , HTF_GRANTPAYMSGMAIN.S_COMMITDATE  , HTF_GRANTPAYMSGMAIN.S_CHECKSTATUS  , HTF_GRANTPAYMSGMAIN.S_IFMATCH "
        + " , HTF_GRANTPAYMSGMAIN.S_INPUTUSERCODE  , HTF_GRANTPAYMSGMAIN.S_CHECKSERCODE  , HTF_GRANTPAYMSGMAIN.S_INPUTRECBANKNAME  , HTF_GRANTPAYMSGMAIN.S_DEMO  , HTF_GRANTPAYMSGMAIN.TS_SYSUPDATE "
        + " , HTF_GRANTPAYMSGMAIN.S_PACKAGENO  , HTF_GRANTPAYMSGMAIN.S_ID  , HTF_GRANTPAYMSGMAIN.S_ADMDIVCODE  , HTF_GRANTPAYMSGMAIN.S_STYEAR  , HTF_GRANTPAYMSGMAIN.S_VTCODE "
        + " , HTF_GRANTPAYMSGMAIN.S_VOUDATE  , HTF_GRANTPAYMSGMAIN.S_VOUCHERNO  , HTF_GRANTPAYMSGMAIN.S_FUNDTYPECODE  , HTF_GRANTPAYMSGMAIN.S_FUNDTYPENAME  , HTF_GRANTPAYMSGMAIN.S_BGTTYPECODE "
        + " , HTF_GRANTPAYMSGMAIN.S_BGTTYPENAME  , HTF_GRANTPAYMSGMAIN.S_PAYTYPECODE  , HTF_GRANTPAYMSGMAIN.S_PAYTYPENAME  , HTF_GRANTPAYMSGMAIN.S_PROCATCODE  , HTF_GRANTPAYMSGMAIN.S_PROCATNAME "
        + " , HTF_GRANTPAYMSGMAIN.S_MOFDEPCODE  , HTF_GRANTPAYMSGMAIN.S_MOFDEPNAME  , HTF_GRANTPAYMSGMAIN.S_FILENOCODE  , HTF_GRANTPAYMSGMAIN.S_FILENONAME  , HTF_GRANTPAYMSGMAIN.S_SUPDEPCODE "
        + " , HTF_GRANTPAYMSGMAIN.S_SUPDEPNAME  , HTF_GRANTPAYMSGMAIN.S_AGENCYCODE  , HTF_GRANTPAYMSGMAIN.S_AGENCYNAME  , HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE  , HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME "
        + " , HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE1  , HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME1  , HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE2  , HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME2  , HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE3 "
        + " , HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME3  , HTF_GRANTPAYMSGMAIN.S_EXPECOCODE  , HTF_GRANTPAYMSGMAIN.S_EXPECONAME  , HTF_GRANTPAYMSGMAIN.S_EXPECOCODE1  , HTF_GRANTPAYMSGMAIN.S_EXPECONAME1 "
        + " , HTF_GRANTPAYMSGMAIN.S_EXPECOCODE2  , HTF_GRANTPAYMSGMAIN.S_EXPECONAME2  , HTF_GRANTPAYMSGMAIN.S_DEPPROCODE  , HTF_GRANTPAYMSGMAIN.S_DEPPRONAME  , HTF_GRANTPAYMSGMAIN.S_SETMODECODE "
        + " , HTF_GRANTPAYMSGMAIN.S_SETMODENAME  , HTF_GRANTPAYMSGMAIN.S_PAYBANKCODE  , HTF_GRANTPAYMSGMAIN.S_PAYBANKNAME  , HTF_GRANTPAYMSGMAIN.S_CLEARBANKCODE  , HTF_GRANTPAYMSGMAIN.S_CLEARBANKNAME "
        + " , HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNO  , HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNAME  , HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNAME  , HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNO  , HTF_GRANTPAYMSGMAIN.S_PAYACCTNO "
        + " , HTF_GRANTPAYMSGMAIN.S_PAYACCTNAME  , HTF_GRANTPAYMSGMAIN.S_PAYACCTBANKNAME  , HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYCODE  , HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYNAME  , HTF_GRANTPAYMSGMAIN.N_PAYAMT "
        + " , HTF_GRANTPAYMSGMAIN.S_PAYMGRCODE  , HTF_GRANTPAYMSGMAIN.S_PAYMGRNAME  , HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODECODE  , HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODENAME  , HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPECODE "
        + " , HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPENAME  , HTF_GRANTPAYMSGMAIN.S_TAXBILLNO  , HTF_GRANTPAYMSGMAIN.S_TAXAYERID  , HTF_GRANTPAYMSGMAIN.S_TAXORGCODE  , HTF_GRANTPAYMSGMAIN.S_CHECKNO "
        + " , HTF_GRANTPAYMSGMAIN.S_XPAYDATE  , HTF_GRANTPAYMSGMAIN.S_XAGENTBUSINESSNO  , HTF_GRANTPAYMSGMAIN.S_XCHECKNO  , HTF_GRANTPAYMSGMAIN.N_XPAYAMT  , HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTBANKNAME "
        + " , HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNO  , HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNAME  , HTF_GRANTPAYMSGMAIN.S_BACKFLAG  , HTF_GRANTPAYMSGMAIN.S_ISRETURN  , HTF_GRANTPAYMSGMAIN.S_BCKREASON "
        + " , HTF_GRANTPAYMSGMAIN.S_REFUNDTYPE  , HTF_GRANTPAYMSGMAIN.N_BACKMONEY  , HTF_GRANTPAYMSGMAIN.S_HOLD1  , HTF_GRANTPAYMSGMAIN.S_HOLD2  , HTF_GRANTPAYMSGMAIN.S_EXT1 "
        + " , HTF_GRANTPAYMSGMAIN.S_EXT2  , HTF_GRANTPAYMSGMAIN.S_EXT3  , HTF_GRANTPAYMSGMAIN.S_EXT4  , HTF_GRANTPAYMSGMAIN.S_EXT5 "
        + "FROM HTF_GRANTPAYMSGMAIN ";



    /* SQL to select batch data */
    private static final String SQL_SELECT_BATCH =
        "SELECT "
        + "HTF_GRANTPAYMSGMAIN.I_VOUSRLNO, HTF_GRANTPAYMSGMAIN.S_ORGCODE, HTF_GRANTPAYMSGMAIN.S_TRECODE, HTF_GRANTPAYMSGMAIN.S_STATUS, HTF_GRANTPAYMSGMAIN.S_DEALNO, "
        + "HTF_GRANTPAYMSGMAIN.S_FINORGCODE, HTF_GRANTPAYMSGMAIN.S_FILENAME, HTF_GRANTPAYMSGMAIN.S_COMMITDATE, HTF_GRANTPAYMSGMAIN.S_CHECKSTATUS, HTF_GRANTPAYMSGMAIN.S_IFMATCH, "
        + "HTF_GRANTPAYMSGMAIN.S_INPUTUSERCODE, HTF_GRANTPAYMSGMAIN.S_CHECKSERCODE, HTF_GRANTPAYMSGMAIN.S_INPUTRECBANKNAME, HTF_GRANTPAYMSGMAIN.S_DEMO, HTF_GRANTPAYMSGMAIN.TS_SYSUPDATE, "
        + "HTF_GRANTPAYMSGMAIN.S_PACKAGENO, HTF_GRANTPAYMSGMAIN.S_ID, HTF_GRANTPAYMSGMAIN.S_ADMDIVCODE, HTF_GRANTPAYMSGMAIN.S_STYEAR, HTF_GRANTPAYMSGMAIN.S_VTCODE, "
        + "HTF_GRANTPAYMSGMAIN.S_VOUDATE, HTF_GRANTPAYMSGMAIN.S_VOUCHERNO, HTF_GRANTPAYMSGMAIN.S_FUNDTYPECODE, HTF_GRANTPAYMSGMAIN.S_FUNDTYPENAME, HTF_GRANTPAYMSGMAIN.S_BGTTYPECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_BGTTYPENAME, HTF_GRANTPAYMSGMAIN.S_PAYTYPECODE, HTF_GRANTPAYMSGMAIN.S_PAYTYPENAME, HTF_GRANTPAYMSGMAIN.S_PROCATCODE, HTF_GRANTPAYMSGMAIN.S_PROCATNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_MOFDEPCODE, HTF_GRANTPAYMSGMAIN.S_MOFDEPNAME, HTF_GRANTPAYMSGMAIN.S_FILENOCODE, HTF_GRANTPAYMSGMAIN.S_FILENONAME, HTF_GRANTPAYMSGMAIN.S_SUPDEPCODE, "
        + "HTF_GRANTPAYMSGMAIN.S_SUPDEPNAME, HTF_GRANTPAYMSGMAIN.S_AGENCYCODE, HTF_GRANTPAYMSGMAIN.S_AGENCYNAME, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE1, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME1, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE2, HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME2, HTF_GRANTPAYMSGMAIN.S_EXPFUNCCODE3, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPFUNCNAME3, HTF_GRANTPAYMSGMAIN.S_EXPECOCODE, HTF_GRANTPAYMSGMAIN.S_EXPECONAME, HTF_GRANTPAYMSGMAIN.S_EXPECOCODE1, HTF_GRANTPAYMSGMAIN.S_EXPECONAME1, "
        + "HTF_GRANTPAYMSGMAIN.S_EXPECOCODE2, HTF_GRANTPAYMSGMAIN.S_EXPECONAME2, HTF_GRANTPAYMSGMAIN.S_DEPPROCODE, HTF_GRANTPAYMSGMAIN.S_DEPPRONAME, HTF_GRANTPAYMSGMAIN.S_SETMODECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_SETMODENAME, HTF_GRANTPAYMSGMAIN.S_PAYBANKCODE, HTF_GRANTPAYMSGMAIN.S_PAYBANKNAME, HTF_GRANTPAYMSGMAIN.S_CLEARBANKCODE, HTF_GRANTPAYMSGMAIN.S_CLEARBANKNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNO, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTNAME, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNAME, HTF_GRANTPAYMSGMAIN.S_PAYEEACCTBANKNO, HTF_GRANTPAYMSGMAIN.S_PAYACCTNO, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYACCTNAME, HTF_GRANTPAYMSGMAIN.S_PAYACCTBANKNAME, HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYCODE, HTF_GRANTPAYMSGMAIN.S_PAYSUMMARYNAME, HTF_GRANTPAYMSGMAIN.N_PAYAMT, "
        + "HTF_GRANTPAYMSGMAIN.S_PAYMGRCODE, HTF_GRANTPAYMSGMAIN.S_PAYMGRNAME, HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODECODE, HTF_GRANTPAYMSGMAIN.S_FUNDDEALMODENAME, HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPECODE, "
        + "HTF_GRANTPAYMSGMAIN.S_BUSINESSTYPENAME, HTF_GRANTPAYMSGMAIN.S_TAXBILLNO, HTF_GRANTPAYMSGMAIN.S_TAXAYERID, HTF_GRANTPAYMSGMAIN.S_TAXORGCODE, HTF_GRANTPAYMSGMAIN.S_CHECKNO, "
        + "HTF_GRANTPAYMSGMAIN.S_XPAYDATE, HTF_GRANTPAYMSGMAIN.S_XAGENTBUSINESSNO, HTF_GRANTPAYMSGMAIN.S_XCHECKNO, HTF_GRANTPAYMSGMAIN.N_XPAYAMT, HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTBANKNAME, "
        + "HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNO, HTF_GRANTPAYMSGMAIN.S_XPAYEEACCTNAME, HTF_GRANTPAYMSGMAIN.S_BACKFLAG, HTF_GRANTPAYMSGMAIN.S_ISRETURN, HTF_GRANTPAYMSGMAIN.S_BCKREASON, "
        + "HTF_GRANTPAYMSGMAIN.S_REFUNDTYPE, HTF_GRANTPAYMSGMAIN.N_BACKMONEY, HTF_GRANTPAYMSGMAIN.S_HOLD1, HTF_GRANTPAYMSGMAIN.S_HOLD2, HTF_GRANTPAYMSGMAIN.S_EXT1, "
        + "HTF_GRANTPAYMSGMAIN.S_EXT2, HTF_GRANTPAYMSGMAIN.S_EXT3, HTF_GRANTPAYMSGMAIN.S_EXT4, HTF_GRANTPAYMSGMAIN.S_EXT5 "
        + "FROM HTF_GRANTPAYMSGMAIN " ;
        

   /* SQL to select batch data where condition  */
    private static final String SQL_SELECT_BATCH_WHERE =" ( "
        + "I_VOUSRLNO = ?)"
        ;


    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE HTF_GRANTPAYMSGMAIN SET "
        + "S_ORGCODE =?,S_TRECODE =?,S_STATUS =?,S_DEALNO =?,S_FINORGCODE =?, "
        + "S_FILENAME =?,S_COMMITDATE =?,S_CHECKSTATUS =?,S_IFMATCH =?,S_INPUTUSERCODE =?, "
        + "S_CHECKSERCODE =?,S_INPUTRECBANKNAME =?,S_DEMO =?,TS_SYSUPDATE =CURRENT TIMESTAMP,S_PACKAGENO =?, "
        + "S_ID =?,S_ADMDIVCODE =?,S_STYEAR =?,S_VTCODE =?,S_VOUDATE =?, "
        + "S_VOUCHERNO =?,S_FUNDTYPECODE =?,S_FUNDTYPENAME =?,S_BGTTYPECODE =?,S_BGTTYPENAME =?, "
        + "S_PAYTYPECODE =?,S_PAYTYPENAME =?,S_PROCATCODE =?,S_PROCATNAME =?,S_MOFDEPCODE =?, "
        + "S_MOFDEPNAME =?,S_FILENOCODE =?,S_FILENONAME =?,S_SUPDEPCODE =?,S_SUPDEPNAME =?, "
        + "S_AGENCYCODE =?,S_AGENCYNAME =?,S_EXPFUNCCODE =?,S_EXPFUNCNAME =?,S_EXPFUNCCODE1 =?, "
        + "S_EXPFUNCNAME1 =?,S_EXPFUNCCODE2 =?,S_EXPFUNCNAME2 =?,S_EXPFUNCCODE3 =?,S_EXPFUNCNAME3 =?, "
        + "S_EXPECOCODE =?,S_EXPECONAME =?,S_EXPECOCODE1 =?,S_EXPECONAME1 =?,S_EXPECOCODE2 =?, "
        + "S_EXPECONAME2 =?,S_DEPPROCODE =?,S_DEPPRONAME =?,S_SETMODECODE =?,S_SETMODENAME =?, "
        + "S_PAYBANKCODE =?,S_PAYBANKNAME =?,S_CLEARBANKCODE =?,S_CLEARBANKNAME =?,S_PAYEEACCTNO =?, "
        + "S_PAYEEACCTNAME =?,S_PAYEEACCTBANKNAME =?,S_PAYEEACCTBANKNO =?,S_PAYACCTNO =?,S_PAYACCTNAME =?, "
        + "S_PAYACCTBANKNAME =?,S_PAYSUMMARYCODE =?,S_PAYSUMMARYNAME =?,N_PAYAMT =?,S_PAYMGRCODE =?, "
        + "S_PAYMGRNAME =?,S_FUNDDEALMODECODE =?,S_FUNDDEALMODENAME =?,S_BUSINESSTYPECODE =?,S_BUSINESSTYPENAME =?, "
        + "S_TAXBILLNO =?,S_TAXAYERID =?,S_TAXORGCODE =?,S_CHECKNO =?,S_XPAYDATE =?, "
        + "S_XAGENTBUSINESSNO =?,S_XCHECKNO =?,N_XPAYAMT =?,S_XPAYEEACCTBANKNAME =?,S_XPAYEEACCTNO =?, "
        + "S_XPAYEEACCTNAME =?,S_BACKFLAG =?,S_ISRETURN =?,S_BCKREASON =?,S_REFUNDTYPE =?, "
        + "N_BACKMONEY =?,S_HOLD1 =?,S_HOLD2 =?,S_EXT1 =?,S_EXT2 =?, "
        + "S_EXT3 =?,S_EXT4 =?,S_EXT5 =? "
        + "WHERE "
        + "I_VOUSRLNO = ?"
        ;

	/* SQL to update data, support LOB */
    private static final String SQL_UPDATE_LOB =
        "UPDATE HTF_GRANTPAYMSGMAIN SET "
        + "S_ORGCODE =?, S_TRECODE =?, S_STATUS =?, S_DEALNO =?, S_FINORGCODE =?,  "
        + "S_FILENAME =?, S_COMMITDATE =?, S_CHECKSTATUS =?, S_IFMATCH =?, S_INPUTUSERCODE =?,  "
        + "S_CHECKSERCODE =?, S_INPUTRECBANKNAME =?, S_DEMO =?, TS_SYSUPDATE =CURRENT TIMESTAMP, S_PACKAGENO =?,  "
        + "S_ID =?, S_ADMDIVCODE =?, S_STYEAR =?, S_VTCODE =?, S_VOUDATE =?,  "
        + "S_VOUCHERNO =?, S_FUNDTYPECODE =?, S_FUNDTYPENAME =?, S_BGTTYPECODE =?, S_BGTTYPENAME =?,  "
        + "S_PAYTYPECODE =?, S_PAYTYPENAME =?, S_PROCATCODE =?, S_PROCATNAME =?, S_MOFDEPCODE =?,  "
        + "S_MOFDEPNAME =?, S_FILENOCODE =?, S_FILENONAME =?, S_SUPDEPCODE =?, S_SUPDEPNAME =?,  "
        + "S_AGENCYCODE =?, S_AGENCYNAME =?, S_EXPFUNCCODE =?, S_EXPFUNCNAME =?, S_EXPFUNCCODE1 =?,  "
        + "S_EXPFUNCNAME1 =?, S_EXPFUNCCODE2 =?, S_EXPFUNCNAME2 =?, S_EXPFUNCCODE3 =?, S_EXPFUNCNAME3 =?,  "
        + "S_EXPECOCODE =?, S_EXPECONAME =?, S_EXPECOCODE1 =?, S_EXPECONAME1 =?, S_EXPECOCODE2 =?,  "
        + "S_EXPECONAME2 =?, S_DEPPROCODE =?, S_DEPPRONAME =?, S_SETMODECODE =?, S_SETMODENAME =?,  "
        + "S_PAYBANKCODE =?, S_PAYBANKNAME =?, S_CLEARBANKCODE =?, S_CLEARBANKNAME =?, S_PAYEEACCTNO =?,  "
        + "S_PAYEEACCTNAME =?, S_PAYEEACCTBANKNAME =?, S_PAYEEACCTBANKNO =?, S_PAYACCTNO =?, S_PAYACCTNAME =?,  "
        + "S_PAYACCTBANKNAME =?, S_PAYSUMMARYCODE =?, S_PAYSUMMARYNAME =?, N_PAYAMT =?, S_PAYMGRCODE =?,  "
        + "S_PAYMGRNAME =?, S_FUNDDEALMODECODE =?, S_FUNDDEALMODENAME =?, S_BUSINESSTYPECODE =?, S_BUSINESSTYPENAME =?,  "
        + "S_TAXBILLNO =?, S_TAXAYERID =?, S_TAXORGCODE =?, S_CHECKNO =?, S_XPAYDATE =?,  "
        + "S_XAGENTBUSINESSNO =?, S_XCHECKNO =?, N_XPAYAMT =?, S_XPAYEEACCTBANKNAME =?, S_XPAYEEACCTNO =?,  "
        + "S_XPAYEEACCTNAME =?, S_BACKFLAG =?, S_ISRETURN =?, S_BCKREASON =?, S_REFUNDTYPE =?,  "
        + "N_BACKMONEY =?, S_HOLD1 =?, S_HOLD2 =?, S_EXT1 =?, S_EXT2 =?,  "
        + "S_EXT3 =?, S_EXT4 =?, S_EXT5 =? "
        + "WHERE "
        + "I_VOUSRLNO = ?"
        ;	
	
    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM HTF_GRANTPAYMSGMAIN " 
        + " WHERE "
        + "I_VOUSRLNO = ?"
        ;


	/**
	*  批量查询 一次最多查询的参数数量
	*/
	
	public static final int FIND_BATCH_SIZE = 150  / 1;
	



   /**
   * Create a new record in Database.
   */
  public void create(IDto _dto,  Connection conn) throws SQLException
  {
     HtfGrantpaymsgmainDto dto = (HtfGrantpaymsgmainDto)_dto ;
     String msgValid = dto.checkValid() ;
     if (msgValid != null)
     	throw new SQLException("插入错误，"+msgValid) ;

     PreparedStatement ps = null;
     try
     {
         ps = conn.prepareStatement(SQL_INSERT);
          if (dto.getIvousrlno()==null)
            ps.setNull(1, java.sql.Types.BIGINT);
         else
            ps.setLong(1, dto.getIvousrlno().longValue());
          ps.setString(2, dto.getSorgcode());

          ps.setString(3, dto.getStrecode());

          ps.setString(4, dto.getSstatus());

          ps.setString(5, dto.getSdealno());

          ps.setString(6, dto.getSfinorgcode());

          ps.setString(7, dto.getSfilename());

          ps.setString(8, dto.getScommitdate());

          ps.setString(9, dto.getScheckstatus());

          ps.setString(10, dto.getSifmatch());

          ps.setString(11, dto.getSinputusercode());

          ps.setString(12, dto.getSchecksercode());

          ps.setString(13, dto.getSinputrecbankname());

          ps.setString(14, dto.getSdemo());

           ps.setString(15, dto.getSpackageno());

          ps.setString(16, dto.getSid());

          ps.setString(17, dto.getSadmdivcode());

          ps.setString(18, dto.getSstyear());

          ps.setString(19, dto.getSvtcode());

          ps.setString(20, dto.getSvoudate());

          ps.setString(21, dto.getSvoucherno());

          ps.setString(22, dto.getSfundtypecode());

          ps.setString(23, dto.getSfundtypename());

          ps.setString(24, dto.getSbgttypecode());

          ps.setString(25, dto.getSbgttypename());

          ps.setString(26, dto.getSpaytypecode());

          ps.setString(27, dto.getSpaytypename());

          ps.setString(28, dto.getSprocatcode());

          ps.setString(29, dto.getSprocatname());

          ps.setString(30, dto.getSmofdepcode());

          ps.setString(31, dto.getSmofdepname());

          ps.setString(32, dto.getSfilenocode());

          ps.setString(33, dto.getSfilenoname());

          ps.setString(34, dto.getSsupdepcode());

          ps.setString(35, dto.getSsupdepname());

          ps.setString(36, dto.getSagencycode());

          ps.setString(37, dto.getSagencyname());

          ps.setString(38, dto.getSexpfunccode());

          ps.setString(39, dto.getSexpfuncname());

          ps.setString(40, dto.getSexpfunccode1());

          ps.setString(41, dto.getSexpfuncname1());

          ps.setString(42, dto.getSexpfunccode2());

          ps.setString(43, dto.getSexpfuncname2());

          ps.setString(44, dto.getSexpfunccode3());

          ps.setString(45, dto.getSexpfuncname3());

          ps.setString(46, dto.getSexpecocode());

          ps.setString(47, dto.getSexpeconame());

          ps.setString(48, dto.getSexpecocode1());

          ps.setString(49, dto.getSexpeconame1());

          ps.setString(50, dto.getSexpecocode2());

          ps.setString(51, dto.getSexpeconame2());

          ps.setString(52, dto.getSdepprocode());

          ps.setString(53, dto.getSdepproname());

          ps.setString(54, dto.getSsetmodecode());

          ps.setString(55, dto.getSsetmodename());

          ps.setString(56, dto.getSpaybankcode());

          ps.setString(57, dto.getSpaybankname());

          ps.setString(58, dto.getSclearbankcode());

          ps.setString(59, dto.getSclearbankname());

          ps.setString(60, dto.getSpayeeacctno());

          ps.setString(61, dto.getSpayeeacctname());

          ps.setString(62, dto.getSpayeeacctbankname());

          ps.setString(63, dto.getSpayeeacctbankno());

          ps.setString(64, dto.getSpayacctno());

          ps.setString(65, dto.getSpayacctname());

          ps.setString(66, dto.getSpayacctbankname());

          ps.setString(67, dto.getSpaysummarycode());

          ps.setString(68, dto.getSpaysummaryname());

          ps.setBigDecimal(69, dto.getNpayamt());

          ps.setString(70, dto.getSpaymgrcode());

          ps.setString(71, dto.getSpaymgrname());

          ps.setString(72, dto.getSfunddealmodecode());

          ps.setString(73, dto.getSfunddealmodename());

          ps.setString(74, dto.getSbusinesstypecode());

          ps.setString(75, dto.getSbusinesstypename());

          ps.setString(76, dto.getStaxbillno());

          ps.setString(77, dto.getStaxayerid());

          ps.setString(78, dto.getStaxorgcode());

          ps.setString(79, dto.getScheckno());

          ps.setString(80, dto.getSxpaydate());

          ps.setString(81, dto.getSxagentbusinessno());

          ps.setString(82, dto.getSxcheckno());

          ps.setBigDecimal(83, dto.getNxpayamt());

          ps.setString(84, dto.getSxpayeeacctbankname());

          ps.setString(85, dto.getSxpayeeacctno());

          ps.setString(86, dto.getSxpayeeacctname());

          ps.setString(87, dto.getSbackflag());

          ps.setString(88, dto.getSisreturn());

          ps.setString(89, dto.getSbckreason());

          ps.setString(90, dto.getSrefundtype());

          ps.setBigDecimal(91, dto.getNbackmoney());

          ps.setString(92, dto.getShold1());

          ps.setString(93, dto.getShold2());

          ps.setString(94, dto.getSext1());

          ps.setString(95, dto.getSext2());

          ps.setString(96, dto.getSext3());

          ps.setString(97, dto.getSext4());

          ps.setString(98, dto.getSext5());

         ps.executeUpdate();
     }
     finally
     {
         close(ps);
     }
     return  ;
  }

   /**
   * Create a new record in Database. and return result, only used when having generated key
   */
   public IDto createWithResult(IDto _dto,  Connection conn) throws SQLException
   {
       HtfGrantpaymsgmainDto dto = (HtfGrantpaymsgmainDto)_dto ;
       String msgValid = dto.checkValid() ;
       if (msgValid != null)
           throw new SQLException("插入错误，"+msgValid) ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try
       {
           ps = conn.prepareStatement(SQL_INSERT_WITH_RESULT);
            if (dto.getIvousrlno()==null)
              ps.setNull(1, java.sql.Types.BIGINT);
           else
              ps.setLong(1, dto.getIvousrlno().longValue());
            ps.setString(2, dto.getSorgcode());
            ps.setString(3, dto.getStrecode());
            ps.setString(4, dto.getSstatus());
            ps.setString(5, dto.getSdealno());
            ps.setString(6, dto.getSfinorgcode());
            ps.setString(7, dto.getSfilename());
            ps.setString(8, dto.getScommitdate());
            ps.setString(9, dto.getScheckstatus());
            ps.setString(10, dto.getSifmatch());
            ps.setString(11, dto.getSinputusercode());
            ps.setString(12, dto.getSchecksercode());
            ps.setString(13, dto.getSinputrecbankname());
            ps.setString(14, dto.getSdemo());
             ps.setString(15, dto.getSpackageno());
            ps.setString(16, dto.getSid());
            ps.setString(17, dto.getSadmdivcode());
            ps.setString(18, dto.getSstyear());
            ps.setString(19, dto.getSvtcode());
            ps.setString(20, dto.getSvoudate());
            ps.setString(21, dto.getSvoucherno());
            ps.setString(22, dto.getSfundtypecode());
            ps.setString(23, dto.getSfundtypename());
            ps.setString(24, dto.getSbgttypecode());
            ps.setString(25, dto.getSbgttypename());
            ps.setString(26, dto.getSpaytypecode());
            ps.setString(27, dto.getSpaytypename());
            ps.setString(28, dto.getSprocatcode());
            ps.setString(29, dto.getSprocatname());
            ps.setString(30, dto.getSmofdepcode());
            ps.setString(31, dto.getSmofdepname());
            ps.setString(32, dto.getSfilenocode());
            ps.setString(33, dto.getSfilenoname());
            ps.setString(34, dto.getSsupdepcode());
            ps.setString(35, dto.getSsupdepname());
            ps.setString(36, dto.getSagencycode());
            ps.setString(37, dto.getSagencyname());
            ps.setString(38, dto.getSexpfunccode());
            ps.setString(39, dto.getSexpfuncname());
            ps.setString(40, dto.getSexpfunccode1());
            ps.setString(41, dto.getSexpfuncname1());
            ps.setString(42, dto.getSexpfunccode2());
            ps.setString(43, dto.getSexpfuncname2());
            ps.setString(44, dto.getSexpfunccode3());
            ps.setString(45, dto.getSexpfuncname3());
            ps.setString(46, dto.getSexpecocode());
            ps.setString(47, dto.getSexpeconame());
            ps.setString(48, dto.getSexpecocode1());
            ps.setString(49, dto.getSexpeconame1());
            ps.setString(50, dto.getSexpecocode2());
            ps.setString(51, dto.getSexpeconame2());
            ps.setString(52, dto.getSdepprocode());
            ps.setString(53, dto.getSdepproname());
            ps.setString(54, dto.getSsetmodecode());
            ps.setString(55, dto.getSsetmodename());
            ps.setString(56, dto.getSpaybankcode());
            ps.setString(57, dto.getSpaybankname());
            ps.setString(58, dto.getSclearbankcode());
            ps.setString(59, dto.getSclearbankname());
            ps.setString(60, dto.getSpayeeacctno());
            ps.setString(61, dto.getSpayeeacctname());
            ps.setString(62, dto.getSpayeeacctbankname());
            ps.setString(63, dto.getSpayeeacctbankno());
            ps.setString(64, dto.getSpayacctno());
            ps.setString(65, dto.getSpayacctname());
            ps.setString(66, dto.getSpayacctbankname());
            ps.setString(67, dto.getSpaysummarycode());
            ps.setString(68, dto.getSpaysummaryname());
            ps.setBigDecimal(69, dto.getNpayamt());
            ps.setString(70, dto.getSpaymgrcode());
            ps.setString(71, dto.getSpaymgrname());
            ps.setString(72, dto.getSfunddealmodecode());
            ps.setString(73, dto.getSfunddealmodename());
            ps.setString(74, dto.getSbusinesstypecode());
            ps.setString(75, dto.getSbusinesstypename());
            ps.setString(76, dto.getStaxbillno());
            ps.setString(77, dto.getStaxayerid());
            ps.setString(78, dto.getStaxorgcode());
            ps.setString(79, dto.getScheckno());
            ps.setString(80, dto.getSxpaydate());
            ps.setString(81, dto.getSxagentbusinessno());
            ps.setString(82, dto.getSxcheckno());
            ps.setBigDecimal(83, dto.getNxpayamt());
            ps.setString(84, dto.getSxpayeeacctbankname());
            ps.setString(85, dto.getSxpayeeacctno());
            ps.setString(86, dto.getSxpayeeacctname());
            ps.setString(87, dto.getSbackflag());
            ps.setString(88, dto.getSisreturn());
            ps.setString(89, dto.getSbckreason());
            ps.setString(90, dto.getSrefundtype());
            ps.setBigDecimal(91, dto.getNbackmoney());
            ps.setString(92, dto.getShold1());
            ps.setString(93, dto.getShold2());
            ps.setString(94, dto.getSext1());
            ps.setString(95, dto.getSext2());
            ps.setString(96, dto.getSext3());
            ps.setString(97, dto.getSext4());
            ps.setString(98, dto.getSext5());
           rs = ps.executeQuery();
           List results = getResults(rs);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }
        finally
        {
           close(ps);
           close(rs);
        }
   }

 	/**
	* Create batch new record in Database. it only create the first layer dto
	*/
    public void create(IDto[] _dtos, Connection conn)    throws SQLException
    {
        HtfGrantpaymsgmainDto dto  ;
     	for (int i= 0; i< _dtos.length ; i++)
 	    {
 		    dto  = (HtfGrantpaymsgmainDto)_dtos[i] ; 
    	    String msgValid = dto.checkValid() ;
        	if (msgValid != null)
     	    	throw new SQLException("插入错误，"+msgValid) ;
     	}
 	    PreparedStatement ps = null;
        try
        {
            ps = conn.prepareStatement(SQL_INSERT);
       
     	    for (int i= 0; i< _dtos.length ; i++)
     	    {
 	    	    dto  = (HtfGrantpaymsgmainDto)_dtos[i] ; 
  
               if (dto.getIvousrlno()==null)
                  ps.setNull(1, java.sql.Types.BIGINT);
               else
                  ps.setLong(1, dto.getIvousrlno().longValue());
  
               ps.setString(2, dto.getSorgcode());
  
               ps.setString(3, dto.getStrecode());
  
               ps.setString(4, dto.getSstatus());
  
               ps.setString(5, dto.getSdealno());
  
               ps.setString(6, dto.getSfinorgcode());
  
               ps.setString(7, dto.getSfilename());
  
               ps.setString(8, dto.getScommitdate());
  
               ps.setString(9, dto.getScheckstatus());
  
               ps.setString(10, dto.getSifmatch());
  
               ps.setString(11, dto.getSinputusercode());
  
               ps.setString(12, dto.getSchecksercode());
  
               ps.setString(13, dto.getSinputrecbankname());
  
               ps.setString(14, dto.getSdemo());
   
               ps.setString(15, dto.getSpackageno());
  
               ps.setString(16, dto.getSid());
  
               ps.setString(17, dto.getSadmdivcode());
  
               ps.setString(18, dto.getSstyear());
  
               ps.setString(19, dto.getSvtcode());
  
               ps.setString(20, dto.getSvoudate());
  
               ps.setString(21, dto.getSvoucherno());
  
               ps.setString(22, dto.getSfundtypecode());
  
               ps.setString(23, dto.getSfundtypename());
  
               ps.setString(24, dto.getSbgttypecode());
  
               ps.setString(25, dto.getSbgttypename());
  
               ps.setString(26, dto.getSpaytypecode());
  
               ps.setString(27, dto.getSpaytypename());
  
               ps.setString(28, dto.getSprocatcode());
  
               ps.setString(29, dto.getSprocatname());
  
               ps.setString(30, dto.getSmofdepcode());
  
               ps.setString(31, dto.getSmofdepname());
  
               ps.setString(32, dto.getSfilenocode());
  
               ps.setString(33, dto.getSfilenoname());
  
               ps.setString(34, dto.getSsupdepcode());
  
               ps.setString(35, dto.getSsupdepname());
  
               ps.setString(36, dto.getSagencycode());
  
               ps.setString(37, dto.getSagencyname());
  
               ps.setString(38, dto.getSexpfunccode());
  
               ps.setString(39, dto.getSexpfuncname());
  
               ps.setString(40, dto.getSexpfunccode1());
  
               ps.setString(41, dto.getSexpfuncname1());
  
               ps.setString(42, dto.getSexpfunccode2());
  
               ps.setString(43, dto.getSexpfuncname2());
  
               ps.setString(44, dto.getSexpfunccode3());
  
               ps.setString(45, dto.getSexpfuncname3());
  
               ps.setString(46, dto.getSexpecocode());
  
               ps.setString(47, dto.getSexpeconame());
  
               ps.setString(48, dto.getSexpecocode1());
  
               ps.setString(49, dto.getSexpeconame1());
  
               ps.setString(50, dto.getSexpecocode2());
  
               ps.setString(51, dto.getSexpeconame2());
  
               ps.setString(52, dto.getSdepprocode());
  
               ps.setString(53, dto.getSdepproname());
  
               ps.setString(54, dto.getSsetmodecode());
  
               ps.setString(55, dto.getSsetmodename());
  
               ps.setString(56, dto.getSpaybankcode());
  
               ps.setString(57, dto.getSpaybankname());
  
               ps.setString(58, dto.getSclearbankcode());
  
               ps.setString(59, dto.getSclearbankname());
  
               ps.setString(60, dto.getSpayeeacctno());
  
               ps.setString(61, dto.getSpayeeacctname());
  
               ps.setString(62, dto.getSpayeeacctbankname());
  
               ps.setString(63, dto.getSpayeeacctbankno());
  
               ps.setString(64, dto.getSpayacctno());
  
               ps.setString(65, dto.getSpayacctname());
  
               ps.setString(66, dto.getSpayacctbankname());
  
               ps.setString(67, dto.getSpaysummarycode());
  
               ps.setString(68, dto.getSpaysummaryname());
  
               ps.setBigDecimal(69, dto.getNpayamt());
  
               ps.setString(70, dto.getSpaymgrcode());
  
               ps.setString(71, dto.getSpaymgrname());
  
               ps.setString(72, dto.getSfunddealmodecode());
  
               ps.setString(73, dto.getSfunddealmodename());
  
               ps.setString(74, dto.getSbusinesstypecode());
  
               ps.setString(75, dto.getSbusinesstypename());
  
               ps.setString(76, dto.getStaxbillno());
  
               ps.setString(77, dto.getStaxayerid());
  
               ps.setString(78, dto.getStaxorgcode());
  
               ps.setString(79, dto.getScheckno());
  
               ps.setString(80, dto.getSxpaydate());
  
               ps.setString(81, dto.getSxagentbusinessno());
  
               ps.setString(82, dto.getSxcheckno());
  
               ps.setBigDecimal(83, dto.getNxpayamt());
  
               ps.setString(84, dto.getSxpayeeacctbankname());
  
               ps.setString(85, dto.getSxpayeeacctno());
  
               ps.setString(86, dto.getSxpayeeacctname());
  
               ps.setString(87, dto.getSbackflag());
  
               ps.setString(88, dto.getSisreturn());
  
               ps.setString(89, dto.getSbckreason());
  
               ps.setString(90, dto.getSrefundtype());
  
               ps.setBigDecimal(91, dto.getNbackmoney());
  
               ps.setString(92, dto.getShold1());
  
               ps.setString(93, dto.getShold2());
  
               ps.setString(94, dto.getSext1());
  
               ps.setString(95, dto.getSext2());
  
               ps.setString(96, dto.getSext3());
  
               ps.setString(97, dto.getSext4());
  
               ps.setString(98, dto.getSext5());
               ps.addBatch(); 
           }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }
        return  ;
   }




     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto find(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       HtfGrantpaymsgmainPK pk = (HtfGrantpaymsgmainPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT);
           if (pk.getIvousrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIvousrlno().longValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }

     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto findForUpdate(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       HtfGrantpaymsgmainPK pk = (HtfGrantpaymsgmainPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT_FOR_UPDATE);
           if (pk.getIvousrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIvousrlno().longValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }
  
     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto[] find(IPK[] _pks, Connection conn, boolean isLobSupport) throws SQLException
    {
        HtfGrantpaymsgmainPK pk ;
        
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (HtfGrantpaymsgmainPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 
        PreparedStatement ps = null;
        ResultSet rs = null;
        
         
        List results = new ArrayList();  
		for (int iBegin = 0; iBegin < pks.size(); iBegin += FIND_BATCH_SIZE)   //
		{
        
            try {
          		int iFindBatchSize = pks.size() - iBegin ;
	    		if (iFindBatchSize >FIND_BATCH_SIZE )
		    		iFindBatchSize = FIND_BATCH_SIZE ;
		  
        	    StringBuffer sb = new StringBuffer() ;
            	sb.append(SQL_SELECT_BATCH).append(" WHERE ").append(SQL_SELECT_BATCH_WHERE);

	    		for (int i = iBegin+1; i < iBegin + iFindBatchSize; i++)
		    	{
			    	sb.append("OR").append(SQL_SELECT_BATCH_WHERE) ;
    			}
        	
                ps = conn.prepareStatement(sb.toString());

                for (int i = iBegin;i < iBegin + iFindBatchSize; i++)
                {
                    pk  = (HtfGrantpaymsgmainPK)(pks.get(i)) ; 
                   if (pk.getIvousrlno()==null)
                      ps.setNull((i-iBegin)*1+1, java.sql.Types.BIGINT);
                   else
                      ps.setLong((i-iBegin)*1+1, pk.getIvousrlno().longValue());

			
	            }
                rs = ps.executeQuery();
                results.addAll(getResults(rs,0,isLobSupport)); //
            }finally {
                close(rs);
                close(ps);
            }
        }
        if (results!=null && results.size() > 0)
        {
            HtfGrantpaymsgmainDto[] dtos = new HtfGrantpaymsgmainDto[0];
		    dtos = (HtfGrantpaymsgmainDto[]) results.toArray(dtos) ;
		    return dtos ;
        }
        else
        {
            return null;
        }
    }

  
  
  



    /**
	    * 得到查询语句
	    */
    public String getSelectSQL() 
    {
	        return SQL_SELECT_BATCH_SCROLLABLE ;
    }
   

	public List getResults(ResultSet rs) throws SQLException
    {
    	return getResults(rs, 0) ;
    }
  

    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize) throws SQLException
    {
		return getResults(rs,maxSize,false);
	}
    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize, boolean isLobSupport) throws SQLException
    {
        List results = new ArrayList();
        String str ;
        Reader reader;
        Clob clob;
        char[] chars ;
        
        while (rs.next())
         {
             HtfGrantpaymsgmainDto  dto = new  HtfGrantpaymsgmainDto ();
             //I_VOUSRLNO
             str = rs.getString("I_VOUSRLNO");
             if(str!=null){
                dto.setIvousrlno(new Long(str));
             }

             //S_ORGCODE
             str = rs.getString("S_ORGCODE");
             if (str == null)
                dto.setSorgcode(null);
             else
                dto.setSorgcode(str.trim());

             //S_TRECODE
             str = rs.getString("S_TRECODE");
             if (str == null)
                dto.setStrecode(null);
             else
                dto.setStrecode(str.trim());

             //S_STATUS
             str = rs.getString("S_STATUS");
             if (str == null)
                dto.setSstatus(null);
             else
                dto.setSstatus(str.trim());

             //S_DEALNO
             str = rs.getString("S_DEALNO");
             if (str == null)
                dto.setSdealno(null);
             else
                dto.setSdealno(str.trim());

             //S_FINORGCODE
             str = rs.getString("S_FINORGCODE");
             if (str == null)
                dto.setSfinorgcode(null);
             else
                dto.setSfinorgcode(str.trim());

             //S_FILENAME
             str = rs.getString("S_FILENAME");
             if (str == null)
                dto.setSfilename(null);
             else
                dto.setSfilename(str.trim());

             //S_COMMITDATE
             str = rs.getString("S_COMMITDATE");
             if (str == null)
                dto.setScommitdate(null);
             else
                dto.setScommitdate(str.trim());

             //S_CHECKSTATUS
             str = rs.getString("S_CHECKSTATUS");
             if (str == null)
                dto.setScheckstatus(null);
             else
                dto.setScheckstatus(str.trim());

             //S_IFMATCH
             str = rs.getString("S_IFMATCH");
             if (str == null)
                dto.setSifmatch(null);
             else
                dto.setSifmatch(str.trim());

             //S_INPUTUSERCODE
             str = rs.getString("S_INPUTUSERCODE");
             if (str == null)
                dto.setSinputusercode(null);
             else
                dto.setSinputusercode(str.trim());

             //S_CHECKSERCODE
             str = rs.getString("S_CHECKSERCODE");
             if (str == null)
                dto.setSchecksercode(null);
             else
                dto.setSchecksercode(str.trim());

             //S_INPUTRECBANKNAME
             str = rs.getString("S_INPUTRECBANKNAME");
             if (str == null)
                dto.setSinputrecbankname(null);
             else
                dto.setSinputrecbankname(str.trim());

             //S_DEMO
             str = rs.getString("S_DEMO");
             if (str == null)
                dto.setSdemo(null);
             else
                dto.setSdemo(str.trim());

             //TS_SYSUPDATE
           dto.setTssysupdate(rs.getTimestamp("TS_SYSUPDATE"));

             //S_PACKAGENO
             str = rs.getString("S_PACKAGENO");
             if (str == null)
                dto.setSpackageno(null);
             else
                dto.setSpackageno(str.trim());

             //S_ID
             str = rs.getString("S_ID");
             if (str == null)
                dto.setSid(null);
             else
                dto.setSid(str.trim());

             //S_ADMDIVCODE
             str = rs.getString("S_ADMDIVCODE");
             if (str == null)
                dto.setSadmdivcode(null);
             else
                dto.setSadmdivcode(str.trim());

             //S_STYEAR
             str = rs.getString("S_STYEAR");
             if (str == null)
                dto.setSstyear(null);
             else
                dto.setSstyear(str.trim());

             //S_VTCODE
             str = rs.getString("S_VTCODE");
             if (str == null)
                dto.setSvtcode(null);
             else
                dto.setSvtcode(str.trim());

             //S_VOUDATE
             str = rs.getString("S_VOUDATE");
             if (str == null)
                dto.setSvoudate(null);
             else
                dto.setSvoudate(str.trim());

             //S_VOUCHERNO
             str = rs.getString("S_VOUCHERNO");
             if (str == null)
                dto.setSvoucherno(null);
             else
                dto.setSvoucherno(str.trim());

             //S_FUNDTYPECODE
             str = rs.getString("S_FUNDTYPECODE");
             if (str == null)
                dto.setSfundtypecode(null);
             else
                dto.setSfundtypecode(str.trim());

             //S_FUNDTYPENAME
             str = rs.getString("S_FUNDTYPENAME");
             if (str == null)
                dto.setSfundtypename(null);
             else
                dto.setSfundtypename(str.trim());

             //S_BGTTYPECODE
             str = rs.getString("S_BGTTYPECODE");
             if (str == null)
                dto.setSbgttypecode(null);
             else
                dto.setSbgttypecode(str.trim());

             //S_BGTTYPENAME
             str = rs.getString("S_BGTTYPENAME");
             if (str == null)
                dto.setSbgttypename(null);
             else
                dto.setSbgttypename(str.trim());

             //S_PAYTYPECODE
             str = rs.getString("S_PAYTYPECODE");
             if (str == null)
                dto.setSpaytypecode(null);
             else
                dto.setSpaytypecode(str.trim());

             //S_PAYTYPENAME
             str = rs.getString("S_PAYTYPENAME");
             if (str == null)
                dto.setSpaytypename(null);
             else
                dto.setSpaytypename(str.trim());

             //S_PROCATCODE
             str = rs.getString("S_PROCATCODE");
             if (str == null)
                dto.setSprocatcode(null);
             else
                dto.setSprocatcode(str.trim());

             //S_PROCATNAME
             str = rs.getString("S_PROCATNAME");
             if (str == null)
                dto.setSprocatname(null);
             else
                dto.setSprocatname(str.trim());

             //S_MOFDEPCODE
             str = rs.getString("S_MOFDEPCODE");
             if (str == null)
                dto.setSmofdepcode(null);
             else
                dto.setSmofdepcode(str.trim());

             //S_MOFDEPNAME
             str = rs.getString("S_MOFDEPNAME");
             if (str == null)
                dto.setSmofdepname(null);
             else
                dto.setSmofdepname(str.trim());

             //S_FILENOCODE
             str = rs.getString("S_FILENOCODE");
             if (str == null)
                dto.setSfilenocode(null);
             else
                dto.setSfilenocode(str.trim());

             //S_FILENONAME
             str = rs.getString("S_FILENONAME");
             if (str == null)
                dto.setSfilenoname(null);
             else
                dto.setSfilenoname(str.trim());

             //S_SUPDEPCODE
             str = rs.getString("S_SUPDEPCODE");
             if (str == null)
                dto.setSsupdepcode(null);
             else
                dto.setSsupdepcode(str.trim());

             //S_SUPDEPNAME
             str = rs.getString("S_SUPDEPNAME");
             if (str == null)
                dto.setSsupdepname(null);
             else
                dto.setSsupdepname(str.trim());

             //S_AGENCYCODE
             str = rs.getString("S_AGENCYCODE");
             if (str == null)
                dto.setSagencycode(null);
             else
                dto.setSagencycode(str.trim());

             //S_AGENCYNAME
             str = rs.getString("S_AGENCYNAME");
             if (str == null)
                dto.setSagencyname(null);
             else
                dto.setSagencyname(str.trim());

             //S_EXPFUNCCODE
             str = rs.getString("S_EXPFUNCCODE");
             if (str == null)
                dto.setSexpfunccode(null);
             else
                dto.setSexpfunccode(str.trim());

             //S_EXPFUNCNAME
             str = rs.getString("S_EXPFUNCNAME");
             if (str == null)
                dto.setSexpfuncname(null);
             else
                dto.setSexpfuncname(str.trim());

             //S_EXPFUNCCODE1
             str = rs.getString("S_EXPFUNCCODE1");
             if (str == null)
                dto.setSexpfunccode1(null);
             else
                dto.setSexpfunccode1(str.trim());

             //S_EXPFUNCNAME1
             str = rs.getString("S_EXPFUNCNAME1");
             if (str == null)
                dto.setSexpfuncname1(null);
             else
                dto.setSexpfuncname1(str.trim());

             //S_EXPFUNCCODE2
             str = rs.getString("S_EXPFUNCCODE2");
             if (str == null)
                dto.setSexpfunccode2(null);
             else
                dto.setSexpfunccode2(str.trim());

             //S_EXPFUNCNAME2
             str = rs.getString("S_EXPFUNCNAME2");
             if (str == null)
                dto.setSexpfuncname2(null);
             else
                dto.setSexpfuncname2(str.trim());

             //S_EXPFUNCCODE3
             str = rs.getString("S_EXPFUNCCODE3");
             if (str == null)
                dto.setSexpfunccode3(null);
             else
                dto.setSexpfunccode3(str.trim());

             //S_EXPFUNCNAME3
             str = rs.getString("S_EXPFUNCNAME3");
             if (str == null)
                dto.setSexpfuncname3(null);
             else
                dto.setSexpfuncname3(str.trim());

             //S_EXPECOCODE
             str = rs.getString("S_EXPECOCODE");
             if (str == null)
                dto.setSexpecocode(null);
             else
                dto.setSexpecocode(str.trim());

             //S_EXPECONAME
             str = rs.getString("S_EXPECONAME");
             if (str == null)
                dto.setSexpeconame(null);
             else
                dto.setSexpeconame(str.trim());

             //S_EXPECOCODE1
             str = rs.getString("S_EXPECOCODE1");
             if (str == null)
                dto.setSexpecocode1(null);
             else
                dto.setSexpecocode1(str.trim());

             //S_EXPECONAME1
             str = rs.getString("S_EXPECONAME1");
             if (str == null)
                dto.setSexpeconame1(null);
             else
                dto.setSexpeconame1(str.trim());

             //S_EXPECOCODE2
             str = rs.getString("S_EXPECOCODE2");
             if (str == null)
                dto.setSexpecocode2(null);
             else
                dto.setSexpecocode2(str.trim());

             //S_EXPECONAME2
             str = rs.getString("S_EXPECONAME2");
             if (str == null)
                dto.setSexpeconame2(null);
             else
                dto.setSexpeconame2(str.trim());

             //S_DEPPROCODE
             str = rs.getString("S_DEPPROCODE");
             if (str == null)
                dto.setSdepprocode(null);
             else
                dto.setSdepprocode(str.trim());

             //S_DEPPRONAME
             str = rs.getString("S_DEPPRONAME");
             if (str == null)
                dto.setSdepproname(null);
             else
                dto.setSdepproname(str.trim());

             //S_SETMODECODE
             str = rs.getString("S_SETMODECODE");
             if (str == null)
                dto.setSsetmodecode(null);
             else
                dto.setSsetmodecode(str.trim());

             //S_SETMODENAME
             str = rs.getString("S_SETMODENAME");
             if (str == null)
                dto.setSsetmodename(null);
             else
                dto.setSsetmodename(str.trim());

             //S_PAYBANKCODE
             str = rs.getString("S_PAYBANKCODE");
             if (str == null)
                dto.setSpaybankcode(null);
             else
                dto.setSpaybankcode(str.trim());

             //S_PAYBANKNAME
             str = rs.getString("S_PAYBANKNAME");
             if (str == null)
                dto.setSpaybankname(null);
             else
                dto.setSpaybankname(str.trim());

             //S_CLEARBANKCODE
             str = rs.getString("S_CLEARBANKCODE");
             if (str == null)
                dto.setSclearbankcode(null);
             else
                dto.setSclearbankcode(str.trim());

             //S_CLEARBANKNAME
             str = rs.getString("S_CLEARBANKNAME");
             if (str == null)
                dto.setSclearbankname(null);
             else
                dto.setSclearbankname(str.trim());

             //S_PAYEEACCTNO
             str = rs.getString("S_PAYEEACCTNO");
             if (str == null)
                dto.setSpayeeacctno(null);
             else
                dto.setSpayeeacctno(str.trim());

             //S_PAYEEACCTNAME
             str = rs.getString("S_PAYEEACCTNAME");
             if (str == null)
                dto.setSpayeeacctname(null);
             else
                dto.setSpayeeacctname(str.trim());

             //S_PAYEEACCTBANKNAME
             str = rs.getString("S_PAYEEACCTBANKNAME");
             if (str == null)
                dto.setSpayeeacctbankname(null);
             else
                dto.setSpayeeacctbankname(str.trim());

             //S_PAYEEACCTBANKNO
             str = rs.getString("S_PAYEEACCTBANKNO");
             if (str == null)
                dto.setSpayeeacctbankno(null);
             else
                dto.setSpayeeacctbankno(str.trim());

             //S_PAYACCTNO
             str = rs.getString("S_PAYACCTNO");
             if (str == null)
                dto.setSpayacctno(null);
             else
                dto.setSpayacctno(str.trim());

             //S_PAYACCTNAME
             str = rs.getString("S_PAYACCTNAME");
             if (str == null)
                dto.setSpayacctname(null);
             else
                dto.setSpayacctname(str.trim());

             //S_PAYACCTBANKNAME
             str = rs.getString("S_PAYACCTBANKNAME");
             if (str == null)
                dto.setSpayacctbankname(null);
             else
                dto.setSpayacctbankname(str.trim());

             //S_PAYSUMMARYCODE
             str = rs.getString("S_PAYSUMMARYCODE");
             if (str == null)
                dto.setSpaysummarycode(null);
             else
                dto.setSpaysummarycode(str.trim());

             //S_PAYSUMMARYNAME
             str = rs.getString("S_PAYSUMMARYNAME");
             if (str == null)
                dto.setSpaysummaryname(null);
             else
                dto.setSpaysummaryname(str.trim());

             //N_PAYAMT
           dto.setNpayamt(rs.getBigDecimal("N_PAYAMT"));

             //S_PAYMGRCODE
             str = rs.getString("S_PAYMGRCODE");
             if (str == null)
                dto.setSpaymgrcode(null);
             else
                dto.setSpaymgrcode(str.trim());

             //S_PAYMGRNAME
             str = rs.getString("S_PAYMGRNAME");
             if (str == null)
                dto.setSpaymgrname(null);
             else
                dto.setSpaymgrname(str.trim());

             //S_FUNDDEALMODECODE
             str = rs.getString("S_FUNDDEALMODECODE");
             if (str == null)
                dto.setSfunddealmodecode(null);
             else
                dto.setSfunddealmodecode(str.trim());

             //S_FUNDDEALMODENAME
             str = rs.getString("S_FUNDDEALMODENAME");
             if (str == null)
                dto.setSfunddealmodename(null);
             else
                dto.setSfunddealmodename(str.trim());

             //S_BUSINESSTYPECODE
             str = rs.getString("S_BUSINESSTYPECODE");
             if (str == null)
                dto.setSbusinesstypecode(null);
             else
                dto.setSbusinesstypecode(str.trim());

             //S_BUSINESSTYPENAME
             str = rs.getString("S_BUSINESSTYPENAME");
             if (str == null)
                dto.setSbusinesstypename(null);
             else
                dto.setSbusinesstypename(str.trim());

             //S_TAXBILLNO
             str = rs.getString("S_TAXBILLNO");
             if (str == null)
                dto.setStaxbillno(null);
             else
                dto.setStaxbillno(str.trim());

             //S_TAXAYERID
             str = rs.getString("S_TAXAYERID");
             if (str == null)
                dto.setStaxayerid(null);
             else
                dto.setStaxayerid(str.trim());

             //S_TAXORGCODE
             str = rs.getString("S_TAXORGCODE");
             if (str == null)
                dto.setStaxorgcode(null);
             else
                dto.setStaxorgcode(str.trim());

             //S_CHECKNO
             str = rs.getString("S_CHECKNO");
             if (str == null)
                dto.setScheckno(null);
             else
                dto.setScheckno(str.trim());

             //S_XPAYDATE
             str = rs.getString("S_XPAYDATE");
             if (str == null)
                dto.setSxpaydate(null);
             else
                dto.setSxpaydate(str.trim());

             //S_XAGENTBUSINESSNO
             str = rs.getString("S_XAGENTBUSINESSNO");
             if (str == null)
                dto.setSxagentbusinessno(null);
             else
                dto.setSxagentbusinessno(str.trim());

             //S_XCHECKNO
             str = rs.getString("S_XCHECKNO");
             if (str == null)
                dto.setSxcheckno(null);
             else
                dto.setSxcheckno(str.trim());

             //N_XPAYAMT
           dto.setNxpayamt(rs.getBigDecimal("N_XPAYAMT"));

             //S_XPAYEEACCTBANKNAME
             str = rs.getString("S_XPAYEEACCTBANKNAME");
             if (str == null)
                dto.setSxpayeeacctbankname(null);
             else
                dto.setSxpayeeacctbankname(str.trim());

             //S_XPAYEEACCTNO
             str = rs.getString("S_XPAYEEACCTNO");
             if (str == null)
                dto.setSxpayeeacctno(null);
             else
                dto.setSxpayeeacctno(str.trim());

             //S_XPAYEEACCTNAME
             str = rs.getString("S_XPAYEEACCTNAME");
             if (str == null)
                dto.setSxpayeeacctname(null);
             else
                dto.setSxpayeeacctname(str.trim());

             //S_BACKFLAG
             str = rs.getString("S_BACKFLAG");
             if (str == null)
                dto.setSbackflag(null);
             else
                dto.setSbackflag(str.trim());

             //S_ISRETURN
             str = rs.getString("S_ISRETURN");
             if (str == null)
                dto.setSisreturn(null);
             else
                dto.setSisreturn(str.trim());

             //S_BCKREASON
             str = rs.getString("S_BCKREASON");
             if (str == null)
                dto.setSbckreason(null);
             else
                dto.setSbckreason(str.trim());

             //S_REFUNDTYPE
             str = rs.getString("S_REFUNDTYPE");
             if (str == null)
                dto.setSrefundtype(null);
             else
                dto.setSrefundtype(str.trim());

             //N_BACKMONEY
           dto.setNbackmoney(rs.getBigDecimal("N_BACKMONEY"));

             //S_HOLD1
             str = rs.getString("S_HOLD1");
             if (str == null)
                dto.setShold1(null);
             else
                dto.setShold1(str.trim());

             //S_HOLD2
             str = rs.getString("S_HOLD2");
             if (str == null)
                dto.setShold2(null);
             else
                dto.setShold2(str.trim());

             //S_EXT1
             str = rs.getString("S_EXT1");
             if (str == null)
                dto.setSext1(null);
             else
                dto.setSext1(str.trim());

             //S_EXT2
             str = rs.getString("S_EXT2");
             if (str == null)
                dto.setSext2(null);
             else
                dto.setSext2(str.trim());

             //S_EXT3
             str = rs.getString("S_EXT3");
             if (str == null)
                dto.setSext3(null);
             else
                dto.setSext3(str.trim());

             //S_EXT4
             str = rs.getString("S_EXT4");
             if (str == null)
                dto.setSext4(null);
             else
                dto.setSext4(str.trim());

             //S_EXT5
             str = rs.getString("S_EXT5");
             if (str == null)
                dto.setSext5(null);
             else
                dto.setSext5(str.trim());



            results.add(dto);
            
            if(maxSize >0  && results.size() == maxSize)
            {
            	break ;
            }
            
         }
        
		return results ;
    }

  /**
   * populate resultSet as cclass
   */
  protected IDto[] getChildrenResults(ResultSet rs ,Class _dto) throws SQLException{

      throw new SQLException("本dto没有与其它dto相关联，无法应用此方法");
  }


     /**
     * Update a record in Database.
     */

    public void update(IDto _dto, Connection conn, boolean isLobSupport) throws SQLException
    {
        String msgValid = _dto.checkValid() ;
        if (msgValid != null)
            throw new SQLException("修改错误，"+msgValid) ;
        HtfGrantpaymsgmainDto dto = (HtfGrantpaymsgmainDto)_dto ;
        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            int pos = 1;
            //S_ORGCODE
            ps.setString(pos, dto.getSorgcode());
            pos++;

            //S_TRECODE
            ps.setString(pos, dto.getStrecode());
            pos++;

            //S_STATUS
            ps.setString(pos, dto.getSstatus());
            pos++;

            //S_DEALNO
            ps.setString(pos, dto.getSdealno());
            pos++;

            //S_FINORGCODE
            ps.setString(pos, dto.getSfinorgcode());
            pos++;

            //S_FILENAME
            ps.setString(pos, dto.getSfilename());
            pos++;

            //S_COMMITDATE
            ps.setString(pos, dto.getScommitdate());
            pos++;

            //S_CHECKSTATUS
            ps.setString(pos, dto.getScheckstatus());
            pos++;

            //S_IFMATCH
            ps.setString(pos, dto.getSifmatch());
            pos++;

            //S_INPUTUSERCODE
            ps.setString(pos, dto.getSinputusercode());
            pos++;

            //S_CHECKSERCODE
            ps.setString(pos, dto.getSchecksercode());
            pos++;

            //S_INPUTRECBANKNAME
            ps.setString(pos, dto.getSinputrecbankname());
            pos++;

            //S_DEMO
            ps.setString(pos, dto.getSdemo());
            pos++;

            //TS_SYSUPDATE
            //S_PACKAGENO
            ps.setString(pos, dto.getSpackageno());
            pos++;

            //S_ID
            ps.setString(pos, dto.getSid());
            pos++;

            //S_ADMDIVCODE
            ps.setString(pos, dto.getSadmdivcode());
            pos++;

            //S_STYEAR
            ps.setString(pos, dto.getSstyear());
            pos++;

            //S_VTCODE
            ps.setString(pos, dto.getSvtcode());
            pos++;

            //S_VOUDATE
            ps.setString(pos, dto.getSvoudate());
            pos++;

            //S_VOUCHERNO
            ps.setString(pos, dto.getSvoucherno());
            pos++;

            //S_FUNDTYPECODE
            ps.setString(pos, dto.getSfundtypecode());
            pos++;

            //S_FUNDTYPENAME
            ps.setString(pos, dto.getSfundtypename());
            pos++;

            //S_BGTTYPECODE
            ps.setString(pos, dto.getSbgttypecode());
            pos++;

            //S_BGTTYPENAME
            ps.setString(pos, dto.getSbgttypename());
            pos++;

            //S_PAYTYPECODE
            ps.setString(pos, dto.getSpaytypecode());
            pos++;

            //S_PAYTYPENAME
            ps.setString(pos, dto.getSpaytypename());
            pos++;

            //S_PROCATCODE
            ps.setString(pos, dto.getSprocatcode());
            pos++;

            //S_PROCATNAME
            ps.setString(pos, dto.getSprocatname());
            pos++;

            //S_MOFDEPCODE
            ps.setString(pos, dto.getSmofdepcode());
            pos++;

            //S_MOFDEPNAME
            ps.setString(pos, dto.getSmofdepname());
            pos++;

            //S_FILENOCODE
            ps.setString(pos, dto.getSfilenocode());
            pos++;

            //S_FILENONAME
            ps.setString(pos, dto.getSfilenoname());
            pos++;

            //S_SUPDEPCODE
            ps.setString(pos, dto.getSsupdepcode());
            pos++;

            //S_SUPDEPNAME
            ps.setString(pos, dto.getSsupdepname());
            pos++;

            //S_AGENCYCODE
            ps.setString(pos, dto.getSagencycode());
            pos++;

            //S_AGENCYNAME
            ps.setString(pos, dto.getSagencyname());
            pos++;

            //S_EXPFUNCCODE
            ps.setString(pos, dto.getSexpfunccode());
            pos++;

            //S_EXPFUNCNAME
            ps.setString(pos, dto.getSexpfuncname());
            pos++;

            //S_EXPFUNCCODE1
            ps.setString(pos, dto.getSexpfunccode1());
            pos++;

            //S_EXPFUNCNAME1
            ps.setString(pos, dto.getSexpfuncname1());
            pos++;

            //S_EXPFUNCCODE2
            ps.setString(pos, dto.getSexpfunccode2());
            pos++;

            //S_EXPFUNCNAME2
            ps.setString(pos, dto.getSexpfuncname2());
            pos++;

            //S_EXPFUNCCODE3
            ps.setString(pos, dto.getSexpfunccode3());
            pos++;

            //S_EXPFUNCNAME3
            ps.setString(pos, dto.getSexpfuncname3());
            pos++;

            //S_EXPECOCODE
            ps.setString(pos, dto.getSexpecocode());
            pos++;

            //S_EXPECONAME
            ps.setString(pos, dto.getSexpeconame());
            pos++;

            //S_EXPECOCODE1
            ps.setString(pos, dto.getSexpecocode1());
            pos++;

            //S_EXPECONAME1
            ps.setString(pos, dto.getSexpeconame1());
            pos++;

            //S_EXPECOCODE2
            ps.setString(pos, dto.getSexpecocode2());
            pos++;

            //S_EXPECONAME2
            ps.setString(pos, dto.getSexpeconame2());
            pos++;

            //S_DEPPROCODE
            ps.setString(pos, dto.getSdepprocode());
            pos++;

            //S_DEPPRONAME
            ps.setString(pos, dto.getSdepproname());
            pos++;

            //S_SETMODECODE
            ps.setString(pos, dto.getSsetmodecode());
            pos++;

            //S_SETMODENAME
            ps.setString(pos, dto.getSsetmodename());
            pos++;

            //S_PAYBANKCODE
            ps.setString(pos, dto.getSpaybankcode());
            pos++;

            //S_PAYBANKNAME
            ps.setString(pos, dto.getSpaybankname());
            pos++;

            //S_CLEARBANKCODE
            ps.setString(pos, dto.getSclearbankcode());
            pos++;

            //S_CLEARBANKNAME
            ps.setString(pos, dto.getSclearbankname());
            pos++;

            //S_PAYEEACCTNO
            ps.setString(pos, dto.getSpayeeacctno());
            pos++;

            //S_PAYEEACCTNAME
            ps.setString(pos, dto.getSpayeeacctname());
            pos++;

            //S_PAYEEACCTBANKNAME
            ps.setString(pos, dto.getSpayeeacctbankname());
            pos++;

            //S_PAYEEACCTBANKNO
            ps.setString(pos, dto.getSpayeeacctbankno());
            pos++;

            //S_PAYACCTNO
            ps.setString(pos, dto.getSpayacctno());
            pos++;

            //S_PAYACCTNAME
            ps.setString(pos, dto.getSpayacctname());
            pos++;

            //S_PAYACCTBANKNAME
            ps.setString(pos, dto.getSpayacctbankname());
            pos++;

            //S_PAYSUMMARYCODE
            ps.setString(pos, dto.getSpaysummarycode());
            pos++;

            //S_PAYSUMMARYNAME
            ps.setString(pos, dto.getSpaysummaryname());
            pos++;

            //N_PAYAMT
            ps.setBigDecimal(pos, dto.getNpayamt());
            pos++;

            //S_PAYMGRCODE
            ps.setString(pos, dto.getSpaymgrcode());
            pos++;

            //S_PAYMGRNAME
            ps.setString(pos, dto.getSpaymgrname());
            pos++;

            //S_FUNDDEALMODECODE
            ps.setString(pos, dto.getSfunddealmodecode());
            pos++;

            //S_FUNDDEALMODENAME
            ps.setString(pos, dto.getSfunddealmodename());
            pos++;

            //S_BUSINESSTYPECODE
            ps.setString(pos, dto.getSbusinesstypecode());
            pos++;

            //S_BUSINESSTYPENAME
            ps.setString(pos, dto.getSbusinesstypename());
            pos++;

            //S_TAXBILLNO
            ps.setString(pos, dto.getStaxbillno());
            pos++;

            //S_TAXAYERID
            ps.setString(pos, dto.getStaxayerid());
            pos++;

            //S_TAXORGCODE
            ps.setString(pos, dto.getStaxorgcode());
            pos++;

            //S_CHECKNO
            ps.setString(pos, dto.getScheckno());
            pos++;

            //S_XPAYDATE
            ps.setString(pos, dto.getSxpaydate());
            pos++;

            //S_XAGENTBUSINESSNO
            ps.setString(pos, dto.getSxagentbusinessno());
            pos++;

            //S_XCHECKNO
            ps.setString(pos, dto.getSxcheckno());
            pos++;

            //N_XPAYAMT
            ps.setBigDecimal(pos, dto.getNxpayamt());
            pos++;

            //S_XPAYEEACCTBANKNAME
            ps.setString(pos, dto.getSxpayeeacctbankname());
            pos++;

            //S_XPAYEEACCTNO
            ps.setString(pos, dto.getSxpayeeacctno());
            pos++;

            //S_XPAYEEACCTNAME
            ps.setString(pos, dto.getSxpayeeacctname());
            pos++;

            //S_BACKFLAG
            ps.setString(pos, dto.getSbackflag());
            pos++;

            //S_ISRETURN
            ps.setString(pos, dto.getSisreturn());
            pos++;

            //S_BCKREASON
            ps.setString(pos, dto.getSbckreason());
            pos++;

            //S_REFUNDTYPE
            ps.setString(pos, dto.getSrefundtype());
            pos++;

            //N_BACKMONEY
            ps.setBigDecimal(pos, dto.getNbackmoney());
            pos++;

            //S_HOLD1
            ps.setString(pos, dto.getShold1());
            pos++;

            //S_HOLD2
            ps.setString(pos, dto.getShold2());
            pos++;

            //S_EXT1
            ps.setString(pos, dto.getSext1());
            pos++;

            //S_EXT2
            ps.setString(pos, dto.getSext2());
            pos++;

            //S_EXT3
            ps.setString(pos, dto.getSext3());
            pos++;

            //S_EXT4
            ps.setString(pos, dto.getSext4());
            pos++;

            //S_EXT5
            ps.setString(pos, dto.getSext5());
            pos++;


           //I_VOUSRLNO
           ps.setLong(pos, dto.getIvousrlno().longValue());
           pos++;
           ps.executeUpdate();
        }
        finally
        {
           close(ps);
        }

        return ;
    }
    
    
    
      /**
     * Update batch record in Database.
     */

    public void update(IDto[] _dtos, Connection conn, boolean isLobSupport) throws SQLException
    {
     
     	 HtfGrantpaymsgmainDto dto  ;
         for (int i= 0; i< _dtos.length ; i++)
         {
            dto  = (HtfGrantpaymsgmainDto)_dtos[i] ; 
            String msgValid = dto.checkValid() ;
            if (msgValid != null)
                throw new SQLException("修改错误，"+msgValid) ;
         }

        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            
            for (int i= 0; i< _dtos.length ; i++)
            {
                dto  = (HtfGrantpaymsgmainDto)_dtos[i] ; 
                int pos = 1;
                //S_ORGCODE
                 ps.setString(pos, dto.getSorgcode());
                pos++;

                //S_TRECODE
                 ps.setString(pos, dto.getStrecode());
                pos++;

                //S_STATUS
                 ps.setString(pos, dto.getSstatus());
                pos++;

                //S_DEALNO
                 ps.setString(pos, dto.getSdealno());
                pos++;

                //S_FINORGCODE
                 ps.setString(pos, dto.getSfinorgcode());
                pos++;

                //S_FILENAME
                 ps.setString(pos, dto.getSfilename());
                pos++;

                //S_COMMITDATE
                 ps.setString(pos, dto.getScommitdate());
                pos++;

                //S_CHECKSTATUS
                 ps.setString(pos, dto.getScheckstatus());
                pos++;

                //S_IFMATCH
                 ps.setString(pos, dto.getSifmatch());
                pos++;

                //S_INPUTUSERCODE
                 ps.setString(pos, dto.getSinputusercode());
                pos++;

                //S_CHECKSERCODE
                 ps.setString(pos, dto.getSchecksercode());
                pos++;

                //S_INPUTRECBANKNAME
                 ps.setString(pos, dto.getSinputrecbankname());
                pos++;

                //S_DEMO
                 ps.setString(pos, dto.getSdemo());
                pos++;

                //TS_SYSUPDATE
                 //S_PACKAGENO
                 ps.setString(pos, dto.getSpackageno());
                pos++;

                //S_ID
                 ps.setString(pos, dto.getSid());
                pos++;

                //S_ADMDIVCODE
                 ps.setString(pos, dto.getSadmdivcode());
                pos++;

                //S_STYEAR
                 ps.setString(pos, dto.getSstyear());
                pos++;

                //S_VTCODE
                 ps.setString(pos, dto.getSvtcode());
                pos++;

                //S_VOUDATE
                 ps.setString(pos, dto.getSvoudate());
                pos++;

                //S_VOUCHERNO
                 ps.setString(pos, dto.getSvoucherno());
                pos++;

                //S_FUNDTYPECODE
                 ps.setString(pos, dto.getSfundtypecode());
                pos++;

                //S_FUNDTYPENAME
                 ps.setString(pos, dto.getSfundtypename());
                pos++;

                //S_BGTTYPECODE
                 ps.setString(pos, dto.getSbgttypecode());
                pos++;

                //S_BGTTYPENAME
                 ps.setString(pos, dto.getSbgttypename());
                pos++;

                //S_PAYTYPECODE
                 ps.setString(pos, dto.getSpaytypecode());
                pos++;

                //S_PAYTYPENAME
                 ps.setString(pos, dto.getSpaytypename());
                pos++;

                //S_PROCATCODE
                 ps.setString(pos, dto.getSprocatcode());
                pos++;

                //S_PROCATNAME
                 ps.setString(pos, dto.getSprocatname());
                pos++;

                //S_MOFDEPCODE
                 ps.setString(pos, dto.getSmofdepcode());
                pos++;

                //S_MOFDEPNAME
                 ps.setString(pos, dto.getSmofdepname());
                pos++;

                //S_FILENOCODE
                 ps.setString(pos, dto.getSfilenocode());
                pos++;

                //S_FILENONAME
                 ps.setString(pos, dto.getSfilenoname());
                pos++;

                //S_SUPDEPCODE
                 ps.setString(pos, dto.getSsupdepcode());
                pos++;

                //S_SUPDEPNAME
                 ps.setString(pos, dto.getSsupdepname());
                pos++;

                //S_AGENCYCODE
                 ps.setString(pos, dto.getSagencycode());
                pos++;

                //S_AGENCYNAME
                 ps.setString(pos, dto.getSagencyname());
                pos++;

                //S_EXPFUNCCODE
                 ps.setString(pos, dto.getSexpfunccode());
                pos++;

                //S_EXPFUNCNAME
                 ps.setString(pos, dto.getSexpfuncname());
                pos++;

                //S_EXPFUNCCODE1
                 ps.setString(pos, dto.getSexpfunccode1());
                pos++;

                //S_EXPFUNCNAME1
                 ps.setString(pos, dto.getSexpfuncname1());
                pos++;

                //S_EXPFUNCCODE2
                 ps.setString(pos, dto.getSexpfunccode2());
                pos++;

                //S_EXPFUNCNAME2
                 ps.setString(pos, dto.getSexpfuncname2());
                pos++;

                //S_EXPFUNCCODE3
                 ps.setString(pos, dto.getSexpfunccode3());
                pos++;

                //S_EXPFUNCNAME3
                 ps.setString(pos, dto.getSexpfuncname3());
                pos++;

                //S_EXPECOCODE
                 ps.setString(pos, dto.getSexpecocode());
                pos++;

                //S_EXPECONAME
                 ps.setString(pos, dto.getSexpeconame());
                pos++;

                //S_EXPECOCODE1
                 ps.setString(pos, dto.getSexpecocode1());
                pos++;

                //S_EXPECONAME1
                 ps.setString(pos, dto.getSexpeconame1());
                pos++;

                //S_EXPECOCODE2
                 ps.setString(pos, dto.getSexpecocode2());
                pos++;

                //S_EXPECONAME2
                 ps.setString(pos, dto.getSexpeconame2());
                pos++;

                //S_DEPPROCODE
                 ps.setString(pos, dto.getSdepprocode());
                pos++;

                //S_DEPPRONAME
                 ps.setString(pos, dto.getSdepproname());
                pos++;

                //S_SETMODECODE
                 ps.setString(pos, dto.getSsetmodecode());
                pos++;

                //S_SETMODENAME
                 ps.setString(pos, dto.getSsetmodename());
                pos++;

                //S_PAYBANKCODE
                 ps.setString(pos, dto.getSpaybankcode());
                pos++;

                //S_PAYBANKNAME
                 ps.setString(pos, dto.getSpaybankname());
                pos++;

                //S_CLEARBANKCODE
                 ps.setString(pos, dto.getSclearbankcode());
                pos++;

                //S_CLEARBANKNAME
                 ps.setString(pos, dto.getSclearbankname());
                pos++;

                //S_PAYEEACCTNO
                 ps.setString(pos, dto.getSpayeeacctno());
                pos++;

                //S_PAYEEACCTNAME
                 ps.setString(pos, dto.getSpayeeacctname());
                pos++;

                //S_PAYEEACCTBANKNAME
                 ps.setString(pos, dto.getSpayeeacctbankname());
                pos++;

                //S_PAYEEACCTBANKNO
                 ps.setString(pos, dto.getSpayeeacctbankno());
                pos++;

                //S_PAYACCTNO
                 ps.setString(pos, dto.getSpayacctno());
                pos++;

                //S_PAYACCTNAME
                 ps.setString(pos, dto.getSpayacctname());
                pos++;

                //S_PAYACCTBANKNAME
                 ps.setString(pos, dto.getSpayacctbankname());
                pos++;

                //S_PAYSUMMARYCODE
                 ps.setString(pos, dto.getSpaysummarycode());
                pos++;

                //S_PAYSUMMARYNAME
                 ps.setString(pos, dto.getSpaysummaryname());
                pos++;

                //N_PAYAMT
                 ps.setBigDecimal(pos, dto.getNpayamt());
                pos++;

                //S_PAYMGRCODE
                 ps.setString(pos, dto.getSpaymgrcode());
                pos++;

                //S_PAYMGRNAME
                 ps.setString(pos, dto.getSpaymgrname());
                pos++;

                //S_FUNDDEALMODECODE
                 ps.setString(pos, dto.getSfunddealmodecode());
                pos++;

                //S_FUNDDEALMODENAME
                 ps.setString(pos, dto.getSfunddealmodename());
                pos++;

                //S_BUSINESSTYPECODE
                 ps.setString(pos, dto.getSbusinesstypecode());
                pos++;

                //S_BUSINESSTYPENAME
                 ps.setString(pos, dto.getSbusinesstypename());
                pos++;

                //S_TAXBILLNO
                 ps.setString(pos, dto.getStaxbillno());
                pos++;

                //S_TAXAYERID
                 ps.setString(pos, dto.getStaxayerid());
                pos++;

                //S_TAXORGCODE
                 ps.setString(pos, dto.getStaxorgcode());
                pos++;

                //S_CHECKNO
                 ps.setString(pos, dto.getScheckno());
                pos++;

                //S_XPAYDATE
                 ps.setString(pos, dto.getSxpaydate());
                pos++;

                //S_XAGENTBUSINESSNO
                 ps.setString(pos, dto.getSxagentbusinessno());
                pos++;

                //S_XCHECKNO
                 ps.setString(pos, dto.getSxcheckno());
                pos++;

                //N_XPAYAMT
                 ps.setBigDecimal(pos, dto.getNxpayamt());
                pos++;

                //S_XPAYEEACCTBANKNAME
                 ps.setString(pos, dto.getSxpayeeacctbankname());
                pos++;

                //S_XPAYEEACCTNO
                 ps.setString(pos, dto.getSxpayeeacctno());
                pos++;

                //S_XPAYEEACCTNAME
                 ps.setString(pos, dto.getSxpayeeacctname());
                pos++;

                //S_BACKFLAG
                 ps.setString(pos, dto.getSbackflag());
                pos++;

                //S_ISRETURN
                 ps.setString(pos, dto.getSisreturn());
                pos++;

                //S_BCKREASON
                 ps.setString(pos, dto.getSbckreason());
                pos++;

                //S_REFUNDTYPE
                 ps.setString(pos, dto.getSrefundtype());
                pos++;

                //N_BACKMONEY
                 ps.setBigDecimal(pos, dto.getNbackmoney());
                pos++;

                //S_HOLD1
                 ps.setString(pos, dto.getShold1());
                pos++;

                //S_HOLD2
                 ps.setString(pos, dto.getShold2());
                pos++;

                //S_EXT1
                 ps.setString(pos, dto.getSext1());
                pos++;

                //S_EXT2
                 ps.setString(pos, dto.getSext2());
                pos++;

                //S_EXT3
                 ps.setString(pos, dto.getSext3());
                pos++;

                //S_EXT4
                 ps.setString(pos, dto.getSext4());
                pos++;

                //S_EXT5
                 ps.setString(pos, dto.getSext5());
                pos++;


               //I_VOUSRLNO
               ps.setLong(pos, dto.getIvousrlno().longValue());
               pos++;
		       ps.addBatch(); 
	       }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }

        return ;
    }



    /**
     * delete a record in Database.
     */
    public void delete(IPK _pk, Connection conn) throws SQLException
    {
       
      
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return ;
        //	throw new SQLException("删除错误，"+msgValid) ;
       }
       HtfGrantpaymsgmainPK pk = (HtfGrantpaymsgmainPK)_pk ;


       PreparedStatement ps = null;
       try {
           ps = conn.prepareStatement(SQL_DELETE);
           ps.setLong(1, pk.getIvousrlno().longValue());
           ps.executeUpdate();
        }
        finally
        {
            close(ps);
        }
    }


     /**
     * delete batch record in Database.
     */
    public void delete(IPK[] _pks, Connection conn) throws SQLException
    {
        HtfGrantpaymsgmainPK pk ;
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (HtfGrantpaymsgmainPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 		
 		
        PreparedStatement ps = null;
        try
         {
            ps = conn.prepareStatement(SQL_DELETE);
             
       		for (int i= 0; i< pks.size() ; i++)
       		{
       			pk  = (HtfGrantpaymsgmainPK)(pks.get(i)) ; 
                ps.setLong(1, pk.getIvousrlno().longValue());
		        ps.addBatch() ;
			}
            ps.executeBatch();
        }
        finally
        {
            close(ps);
        }      
    }



    /**
    * Check IChangerNumber or UpdateTimeStamp.
    */
    public void check(IDto _dto, Connection conn) throws SQLException
    {
                                                                                                                                                                                                                                                                                                      		throw new SQLException("数据库表：HTF_GRANTPAYMSGMAIN没有检查修改的字段");
    }


	/**
	* synchronize values between parent and children
	*/
    public void syncToChildren(IDto _dto)     throws SQLException{
       throw new SQLException("本记录没有与其它记录相关联，无法进行主记录与明细记录之间的数据同步。");
  }

	/**
	*get children
	*/
    public IDto[] findChildren (IDto _dto, Connection conn, boolean isLobSupport)     throws SQLException{
         throw new SQLException("本dto没有与其它dto相关联，无法得到子dto");
  }    
    
  /**
   *return the children IDto class
   * @return Class
   */
  public Class getChildrenClass(){
	  return null;
  };    



    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt)
    {
        if (stmt != null)
        {
            try
            {
                stmt.close();
            }
            catch(SQLException    e)
            {}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs)
    {
        if (rs != null)
        {
            try
            {
                rs.close();
            }catch(SQLException  e){}
        }
    }
}
