    



package com.cfcc.itfe.persistence.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;
import java.sql.Clob;

import com.cfcc.jaf.persistence.jaform.parent.* ;

import java.math.BigDecimal;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

import java.io.StringReader;
import java.io.Reader;
import java.io.IOException;

import com.cfcc.itfe.persistence.dto.HtrTaxorgDebtReportDto ;
import com.cfcc.itfe.persistence.pk.HtrTaxorgDebtReportPK ;


/**
 * <p>Title: DAO of table: HTR_TAXORG_DEBT_REPORT</p>
 * <p>Description: Data Access Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:55 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dao.vm timestamp: 2007-04-06 08:30:00
 ******************************************************
 * <p> <b>change record</b><br>
 *  make dao methods simply.<br>
 *  especially make update,delete methods simply.<br>
 *  remove "..withCheck" method,withCheck will impl in JAFOrmTemplate.<br>
 *  remove "delete(IDto _dto,..)" method.<br></p>
 * @author win7
 */

public class HtrTaxorgDebtReportDao  implements IDao
{


    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO HTR_TAXORG_DEBT_REPORT ("
          + "S_TAXORGCODE,S_TRECODE,S_RPTDATE,S_CASHBANK,S_KINDSIGN"
          + ",S_CORPUSSUBJECT,N_CORDAYAMT,N_CORTENDAYAMT,N_CORMONTHAMT,N_CORQUARTERAMT"
          + ",N_CORYEARAMT,S_ACCRUALSUBJECT,N_ACCDAYAMT,N_ACCTENDAYAMT,N_ACCMONTHAMT"
          + ",N_ACCQUARTERAMT,N_ACCYEARAMT"
        + ") VALUES ("
        + "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";


    private static final String SQL_INSERT_WITH_RESULT = "SELECT * FROM FINAL TABLE( " + SQL_INSERT + " )";
    
    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "HTR_TAXORG_DEBT_REPORT.S_TAXORGCODE, HTR_TAXORG_DEBT_REPORT.S_TRECODE, HTR_TAXORG_DEBT_REPORT.S_RPTDATE, HTR_TAXORG_DEBT_REPORT.S_CASHBANK, HTR_TAXORG_DEBT_REPORT.S_KINDSIGN, "
        + "HTR_TAXORG_DEBT_REPORT.S_CORPUSSUBJECT, HTR_TAXORG_DEBT_REPORT.N_CORDAYAMT, HTR_TAXORG_DEBT_REPORT.N_CORTENDAYAMT, HTR_TAXORG_DEBT_REPORT.N_CORMONTHAMT, HTR_TAXORG_DEBT_REPORT.N_CORQUARTERAMT, "
        + "HTR_TAXORG_DEBT_REPORT.N_CORYEARAMT, HTR_TAXORG_DEBT_REPORT.S_ACCRUALSUBJECT, HTR_TAXORG_DEBT_REPORT.N_ACCDAYAMT, HTR_TAXORG_DEBT_REPORT.N_ACCTENDAYAMT, HTR_TAXORG_DEBT_REPORT.N_ACCMONTHAMT, "
        + "HTR_TAXORG_DEBT_REPORT.N_ACCQUARTERAMT, HTR_TAXORG_DEBT_REPORT.N_ACCYEARAMT "
        + "FROM HTR_TAXORG_DEBT_REPORT "
        +" WHERE " 
        + "S_TAXORGCODE = ? AND S_TRECODE = ? AND S_RPTDATE = ? AND S_CASHBANK = ? AND S_CORPUSSUBJECT = ? AND "
        + "S_ACCRUALSUBJECT = ?"
        ;
    /* SQL to select for update data */
    private static final String SQL_SELECT_FOR_UPDATE =
        "SELECT "
        + "HTR_TAXORG_DEBT_REPORT.S_TAXORGCODE, HTR_TAXORG_DEBT_REPORT.S_TRECODE, HTR_TAXORG_DEBT_REPORT.S_RPTDATE, HTR_TAXORG_DEBT_REPORT.S_CASHBANK, HTR_TAXORG_DEBT_REPORT.S_KINDSIGN, "
        + "HTR_TAXORG_DEBT_REPORT.S_CORPUSSUBJECT, HTR_TAXORG_DEBT_REPORT.N_CORDAYAMT, HTR_TAXORG_DEBT_REPORT.N_CORTENDAYAMT, HTR_TAXORG_DEBT_REPORT.N_CORMONTHAMT, HTR_TAXORG_DEBT_REPORT.N_CORQUARTERAMT, "
        + "HTR_TAXORG_DEBT_REPORT.N_CORYEARAMT, HTR_TAXORG_DEBT_REPORT.S_ACCRUALSUBJECT, HTR_TAXORG_DEBT_REPORT.N_ACCDAYAMT, HTR_TAXORG_DEBT_REPORT.N_ACCTENDAYAMT, HTR_TAXORG_DEBT_REPORT.N_ACCMONTHAMT, "
        + "HTR_TAXORG_DEBT_REPORT.N_ACCQUARTERAMT, HTR_TAXORG_DEBT_REPORT.N_ACCYEARAMT "
        + "FROM HTR_TAXORG_DEBT_REPORT "
        +" WHERE " 
        + "S_TAXORGCODE = ? AND S_TRECODE = ? AND S_RPTDATE = ? AND S_CASHBANK = ? AND S_CORPUSSUBJECT = ? AND  FOR UPDATE"
        + "S_ACCRUALSUBJECT = ? FOR UPDATE"
        ;

      /* SQL to select data (SCROLLABLE)*/
     private static final String SQL_SELECT_BATCH_SCROLLABLE =
        "SELECT "
        + "  HTR_TAXORG_DEBT_REPORT.S_TAXORGCODE  , HTR_TAXORG_DEBT_REPORT.S_TRECODE  , HTR_TAXORG_DEBT_REPORT.S_RPTDATE  , HTR_TAXORG_DEBT_REPORT.S_CASHBANK  , HTR_TAXORG_DEBT_REPORT.S_KINDSIGN "
        + " , HTR_TAXORG_DEBT_REPORT.S_CORPUSSUBJECT  , HTR_TAXORG_DEBT_REPORT.N_CORDAYAMT  , HTR_TAXORG_DEBT_REPORT.N_CORTENDAYAMT  , HTR_TAXORG_DEBT_REPORT.N_CORMONTHAMT  , HTR_TAXORG_DEBT_REPORT.N_CORQUARTERAMT "
        + " , HTR_TAXORG_DEBT_REPORT.N_CORYEARAMT  , HTR_TAXORG_DEBT_REPORT.S_ACCRUALSUBJECT  , HTR_TAXORG_DEBT_REPORT.N_ACCDAYAMT  , HTR_TAXORG_DEBT_REPORT.N_ACCTENDAYAMT  , HTR_TAXORG_DEBT_REPORT.N_ACCMONTHAMT "
        + " , HTR_TAXORG_DEBT_REPORT.N_ACCQUARTERAMT  , HTR_TAXORG_DEBT_REPORT.N_ACCYEARAMT "
        + "FROM HTR_TAXORG_DEBT_REPORT ";



    /* SQL to select batch data */
    private static final String SQL_SELECT_BATCH =
        "SELECT "
        + "HTR_TAXORG_DEBT_REPORT.S_TAXORGCODE, HTR_TAXORG_DEBT_REPORT.S_TRECODE, HTR_TAXORG_DEBT_REPORT.S_RPTDATE, HTR_TAXORG_DEBT_REPORT.S_CASHBANK, HTR_TAXORG_DEBT_REPORT.S_KINDSIGN, "
        + "HTR_TAXORG_DEBT_REPORT.S_CORPUSSUBJECT, HTR_TAXORG_DEBT_REPORT.N_CORDAYAMT, HTR_TAXORG_DEBT_REPORT.N_CORTENDAYAMT, HTR_TAXORG_DEBT_REPORT.N_CORMONTHAMT, HTR_TAXORG_DEBT_REPORT.N_CORQUARTERAMT, "
        + "HTR_TAXORG_DEBT_REPORT.N_CORYEARAMT, HTR_TAXORG_DEBT_REPORT.S_ACCRUALSUBJECT, HTR_TAXORG_DEBT_REPORT.N_ACCDAYAMT, HTR_TAXORG_DEBT_REPORT.N_ACCTENDAYAMT, HTR_TAXORG_DEBT_REPORT.N_ACCMONTHAMT, "
        + "HTR_TAXORG_DEBT_REPORT.N_ACCQUARTERAMT, HTR_TAXORG_DEBT_REPORT.N_ACCYEARAMT "
        + "FROM HTR_TAXORG_DEBT_REPORT " ;
        

   /* SQL to select batch data where condition  */
    private static final String SQL_SELECT_BATCH_WHERE =" ( "
        + "S_TAXORGCODE = ? AND S_TRECODE = ? AND S_RPTDATE = ? AND S_CASHBANK = ? AND S_CORPUSSUBJECT = ? AND )"
        + "S_ACCRUALSUBJECT = ?)"
        ;


    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE HTR_TAXORG_DEBT_REPORT SET "
        + "S_KINDSIGN =?,N_CORDAYAMT =?,N_CORTENDAYAMT =?,N_CORMONTHAMT =?,N_CORQUARTERAMT =?, "
        + "N_CORYEARAMT =?,N_ACCDAYAMT =?,N_ACCTENDAYAMT =?,N_ACCMONTHAMT =?,N_ACCQUARTERAMT =?, "
        + "N_ACCYEARAMT =? "
        + "WHERE "
        + "S_TAXORGCODE = ? AND S_TRECODE = ? AND S_RPTDATE = ? AND S_CASHBANK = ? AND S_CORPUSSUBJECT = ? AND "
        + "S_ACCRUALSUBJECT = ?"
        ;

	/* SQL to update data, support LOB */
    private static final String SQL_UPDATE_LOB =
        "UPDATE HTR_TAXORG_DEBT_REPORT SET "
        + "S_KINDSIGN =?, N_CORDAYAMT =?, N_CORTENDAYAMT =?, N_CORMONTHAMT =?, N_CORQUARTERAMT =?,  "
        + "N_CORYEARAMT =?, N_ACCDAYAMT =?, N_ACCTENDAYAMT =?, N_ACCMONTHAMT =?, N_ACCQUARTERAMT =?,  "
        + "N_ACCYEARAMT =? "
        + "WHERE "
        + "S_TAXORGCODE = ? AND S_TRECODE = ? AND S_RPTDATE = ? AND S_CASHBANK = ? AND S_CORPUSSUBJECT = ? AND "
        + "S_ACCRUALSUBJECT = ?"
        ;	
	
    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM HTR_TAXORG_DEBT_REPORT " 
        + " WHERE "
        + "S_TAXORGCODE = ? AND S_TRECODE = ? AND S_RPTDATE = ? AND S_CASHBANK = ? AND S_CORPUSSUBJECT = ? AND "
        + "S_ACCRUALSUBJECT = ?"
        ;


	/**
	*  批量查询 一次最多查询的参数数量
	*/
	
	public static final int FIND_BATCH_SIZE = 150  / 6;
	



   /**
   * Create a new record in Database.
   */
  public void create(IDto _dto,  Connection conn) throws SQLException
  {
     HtrTaxorgDebtReportDto dto = (HtrTaxorgDebtReportDto)_dto ;
     String msgValid = dto.checkValid() ;
     if (msgValid != null)
     	throw new SQLException("插入错误，"+msgValid) ;

     PreparedStatement ps = null;
     try
     {
         ps = conn.prepareStatement(SQL_INSERT);
          ps.setString(1, dto.getStaxorgcode());

          ps.setString(2, dto.getStrecode());

          ps.setString(3, dto.getSrptdate());

          ps.setString(4, dto.getScashbank());

          ps.setString(5, dto.getSkindsign());

          ps.setString(6, dto.getScorpussubject());

          ps.setBigDecimal(7, dto.getNcordayamt());

          ps.setBigDecimal(8, dto.getNcortendayamt());

          ps.setBigDecimal(9, dto.getNcormonthamt());

          ps.setBigDecimal(10, dto.getNcorquarteramt());

          ps.setBigDecimal(11, dto.getNcoryearamt());

          ps.setString(12, dto.getSaccrualsubject());

          ps.setBigDecimal(13, dto.getNaccdayamt());

          ps.setBigDecimal(14, dto.getNacctendayamt());

          ps.setBigDecimal(15, dto.getNaccmonthamt());

          ps.setBigDecimal(16, dto.getNaccquarteramt());

          ps.setBigDecimal(17, dto.getNaccyearamt());

         ps.executeUpdate();
     }
     finally
     {
         close(ps);
     }
     return  ;
  }

   /**
   * Create a new record in Database. and return result, only used when having generated key
   */
   public IDto createWithResult(IDto _dto,  Connection conn) throws SQLException
   {
       HtrTaxorgDebtReportDto dto = (HtrTaxorgDebtReportDto)_dto ;
       String msgValid = dto.checkValid() ;
       if (msgValid != null)
           throw new SQLException("插入错误，"+msgValid) ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try
       {
           ps = conn.prepareStatement(SQL_INSERT_WITH_RESULT);
            ps.setString(1, dto.getStaxorgcode());
            ps.setString(2, dto.getStrecode());
            ps.setString(3, dto.getSrptdate());
            ps.setString(4, dto.getScashbank());
            ps.setString(5, dto.getSkindsign());
            ps.setString(6, dto.getScorpussubject());
            ps.setBigDecimal(7, dto.getNcordayamt());
            ps.setBigDecimal(8, dto.getNcortendayamt());
            ps.setBigDecimal(9, dto.getNcormonthamt());
            ps.setBigDecimal(10, dto.getNcorquarteramt());
            ps.setBigDecimal(11, dto.getNcoryearamt());
            ps.setString(12, dto.getSaccrualsubject());
            ps.setBigDecimal(13, dto.getNaccdayamt());
            ps.setBigDecimal(14, dto.getNacctendayamt());
            ps.setBigDecimal(15, dto.getNaccmonthamt());
            ps.setBigDecimal(16, dto.getNaccquarteramt());
            ps.setBigDecimal(17, dto.getNaccyearamt());
           rs = ps.executeQuery();
           List results = getResults(rs);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }
        finally
        {
           close(ps);
           close(rs);
        }
   }

 	/**
	* Create batch new record in Database. it only create the first layer dto
	*/
    public void create(IDto[] _dtos, Connection conn)    throws SQLException
    {
        HtrTaxorgDebtReportDto dto  ;
     	for (int i= 0; i< _dtos.length ; i++)
 	    {
 		    dto  = (HtrTaxorgDebtReportDto)_dtos[i] ; 
    	    String msgValid = dto.checkValid() ;
        	if (msgValid != null)
     	    	throw new SQLException("插入错误，"+msgValid) ;
     	}
 	    PreparedStatement ps = null;
        try
        {
            ps = conn.prepareStatement(SQL_INSERT);
       
     	    for (int i= 0; i< _dtos.length ; i++)
     	    {
 	    	    dto  = (HtrTaxorgDebtReportDto)_dtos[i] ; 
  
               ps.setString(1, dto.getStaxorgcode());
  
               ps.setString(2, dto.getStrecode());
  
               ps.setString(3, dto.getSrptdate());
  
               ps.setString(4, dto.getScashbank());
  
               ps.setString(5, dto.getSkindsign());
  
               ps.setString(6, dto.getScorpussubject());
  
               ps.setBigDecimal(7, dto.getNcordayamt());
  
               ps.setBigDecimal(8, dto.getNcortendayamt());
  
               ps.setBigDecimal(9, dto.getNcormonthamt());
  
               ps.setBigDecimal(10, dto.getNcorquarteramt());
  
               ps.setBigDecimal(11, dto.getNcoryearamt());
  
               ps.setString(12, dto.getSaccrualsubject());
  
               ps.setBigDecimal(13, dto.getNaccdayamt());
  
               ps.setBigDecimal(14, dto.getNacctendayamt());
  
               ps.setBigDecimal(15, dto.getNaccmonthamt());
  
               ps.setBigDecimal(16, dto.getNaccquarteramt());
  
               ps.setBigDecimal(17, dto.getNaccyearamt());
               ps.addBatch(); 
           }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }
        return  ;
   }




     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto find(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       HtrTaxorgDebtReportPK pk = (HtrTaxorgDebtReportPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT);
           ps.setString(1, pk.getStaxorgcode());

           ps.setString(2, pk.getStrecode());

           ps.setString(3, pk.getSrptdate());

           ps.setString(4, pk.getScashbank());

           ps.setString(5, pk.getScorpussubject());

           ps.setString(6, pk.getSaccrualsubject());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }

     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto findForUpdate(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       HtrTaxorgDebtReportPK pk = (HtrTaxorgDebtReportPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT_FOR_UPDATE);
           ps.setString(1, pk.getStaxorgcode());

           ps.setString(2, pk.getStrecode());

           ps.setString(3, pk.getSrptdate());

           ps.setString(4, pk.getScashbank());

           ps.setString(5, pk.getScorpussubject());

           ps.setString(6, pk.getSaccrualsubject());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }
  
     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto[] find(IPK[] _pks, Connection conn, boolean isLobSupport) throws SQLException
    {
        HtrTaxorgDebtReportPK pk ;
        
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (HtrTaxorgDebtReportPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 
        PreparedStatement ps = null;
        ResultSet rs = null;
        
         
        List results = new ArrayList();  
		for (int iBegin = 0; iBegin < pks.size(); iBegin += FIND_BATCH_SIZE)   //
		{
        
            try {
          		int iFindBatchSize = pks.size() - iBegin ;
	    		if (iFindBatchSize >FIND_BATCH_SIZE )
		    		iFindBatchSize = FIND_BATCH_SIZE ;
		  
        	    StringBuffer sb = new StringBuffer() ;
            	sb.append(SQL_SELECT_BATCH).append(" WHERE ").append(SQL_SELECT_BATCH_WHERE);

	    		for (int i = iBegin+1; i < iBegin + iFindBatchSize; i++)
		    	{
			    	sb.append("OR").append(SQL_SELECT_BATCH_WHERE) ;
    			}
        	
                ps = conn.prepareStatement(sb.toString());

                for (int i = iBegin;i < iBegin + iFindBatchSize; i++)
                {
                    pk  = (HtrTaxorgDebtReportPK)(pks.get(i)) ; 
                   ps.setString((i-iBegin)*6+1, pk.getStaxorgcode());

                   ps.setString((i-iBegin)*6+2, pk.getStrecode());

                   ps.setString((i-iBegin)*6+3, pk.getSrptdate());

                   ps.setString((i-iBegin)*6+4, pk.getScashbank());

                   ps.setString((i-iBegin)*6+5, pk.getScorpussubject());

                   ps.setString((i-iBegin)*6+6, pk.getSaccrualsubject());

			
	            }
                rs = ps.executeQuery();
                results.addAll(getResults(rs,0,isLobSupport)); //
            }finally {
                close(rs);
                close(ps);
            }
        }
        if (results!=null && results.size() > 0)
        {
            HtrTaxorgDebtReportDto[] dtos = new HtrTaxorgDebtReportDto[0];
		    dtos = (HtrTaxorgDebtReportDto[]) results.toArray(dtos) ;
		    return dtos ;
        }
        else
        {
            return null;
        }
    }

  
  
  



    /**
	    * 得到查询语句
	    */
    public String getSelectSQL() 
    {
	        return SQL_SELECT_BATCH_SCROLLABLE ;
    }
   

	public List getResults(ResultSet rs) throws SQLException
    {
    	return getResults(rs, 0) ;
    }
  

    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize) throws SQLException
    {
		return getResults(rs,maxSize,false);
	}
    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize, boolean isLobSupport) throws SQLException
    {
        List results = new ArrayList();
        String str ;
        Reader reader;
        Clob clob;
        char[] chars ;
        
        while (rs.next())
         {
             HtrTaxorgDebtReportDto  dto = new  HtrTaxorgDebtReportDto ();
             //S_TAXORGCODE
             str = rs.getString("S_TAXORGCODE");
             if (str == null)
                dto.setStaxorgcode(null);
             else
                dto.setStaxorgcode(str.trim());

             //S_TRECODE
             str = rs.getString("S_TRECODE");
             if (str == null)
                dto.setStrecode(null);
             else
                dto.setStrecode(str.trim());

             //S_RPTDATE
             str = rs.getString("S_RPTDATE");
             if (str == null)
                dto.setSrptdate(null);
             else
                dto.setSrptdate(str.trim());

             //S_CASHBANK
             str = rs.getString("S_CASHBANK");
             if (str == null)
                dto.setScashbank(null);
             else
                dto.setScashbank(str.trim());

             //S_KINDSIGN
             str = rs.getString("S_KINDSIGN");
             if (str == null)
                dto.setSkindsign(null);
             else
                dto.setSkindsign(str.trim());

             //S_CORPUSSUBJECT
             str = rs.getString("S_CORPUSSUBJECT");
             if (str == null)
                dto.setScorpussubject(null);
             else
                dto.setScorpussubject(str.trim());

             //N_CORDAYAMT
           dto.setNcordayamt(rs.getBigDecimal("N_CORDAYAMT"));

             //N_CORTENDAYAMT
           dto.setNcortendayamt(rs.getBigDecimal("N_CORTENDAYAMT"));

             //N_CORMONTHAMT
           dto.setNcormonthamt(rs.getBigDecimal("N_CORMONTHAMT"));

             //N_CORQUARTERAMT
           dto.setNcorquarteramt(rs.getBigDecimal("N_CORQUARTERAMT"));

             //N_CORYEARAMT
           dto.setNcoryearamt(rs.getBigDecimal("N_CORYEARAMT"));

             //S_ACCRUALSUBJECT
             str = rs.getString("S_ACCRUALSUBJECT");
             if (str == null)
                dto.setSaccrualsubject(null);
             else
                dto.setSaccrualsubject(str.trim());

             //N_ACCDAYAMT
           dto.setNaccdayamt(rs.getBigDecimal("N_ACCDAYAMT"));

             //N_ACCTENDAYAMT
           dto.setNacctendayamt(rs.getBigDecimal("N_ACCTENDAYAMT"));

             //N_ACCMONTHAMT
           dto.setNaccmonthamt(rs.getBigDecimal("N_ACCMONTHAMT"));

             //N_ACCQUARTERAMT
           dto.setNaccquarteramt(rs.getBigDecimal("N_ACCQUARTERAMT"));

             //N_ACCYEARAMT
           dto.setNaccyearamt(rs.getBigDecimal("N_ACCYEARAMT"));



            results.add(dto);
            
            if(maxSize >0  && results.size() == maxSize)
            {
            	break ;
            }
            
         }
        
		return results ;
    }

  /**
   * populate resultSet as cclass
   */
  protected IDto[] getChildrenResults(ResultSet rs ,Class _dto) throws SQLException{

      throw new SQLException("本dto没有与其它dto相关联，无法应用此方法");
  }


     /**
     * Update a record in Database.
     */

    public void update(IDto _dto, Connection conn, boolean isLobSupport) throws SQLException
    {
        String msgValid = _dto.checkValid() ;
        if (msgValid != null)
            throw new SQLException("修改错误，"+msgValid) ;
        HtrTaxorgDebtReportDto dto = (HtrTaxorgDebtReportDto)_dto ;
        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            int pos = 1;
            //S_KINDSIGN
            ps.setString(pos, dto.getSkindsign());
            pos++;

            //N_CORDAYAMT
            ps.setBigDecimal(pos, dto.getNcordayamt());
            pos++;

            //N_CORTENDAYAMT
            ps.setBigDecimal(pos, dto.getNcortendayamt());
            pos++;

            //N_CORMONTHAMT
            ps.setBigDecimal(pos, dto.getNcormonthamt());
            pos++;

            //N_CORQUARTERAMT
            ps.setBigDecimal(pos, dto.getNcorquarteramt());
            pos++;

            //N_CORYEARAMT
            ps.setBigDecimal(pos, dto.getNcoryearamt());
            pos++;

            //N_ACCDAYAMT
            ps.setBigDecimal(pos, dto.getNaccdayamt());
            pos++;

            //N_ACCTENDAYAMT
            ps.setBigDecimal(pos, dto.getNacctendayamt());
            pos++;

            //N_ACCMONTHAMT
            ps.setBigDecimal(pos, dto.getNaccmonthamt());
            pos++;

            //N_ACCQUARTERAMT
            ps.setBigDecimal(pos, dto.getNaccquarteramt());
            pos++;

            //N_ACCYEARAMT
            ps.setBigDecimal(pos, dto.getNaccyearamt());
            pos++;


           //S_TAXORGCODE
           ps.setString(pos, dto.getStaxorgcode());
           pos++;
           //S_TRECODE
           ps.setString(pos, dto.getStrecode());
           pos++;
           //S_RPTDATE
           ps.setString(pos, dto.getSrptdate());
           pos++;
           //S_CASHBANK
           ps.setString(pos, dto.getScashbank());
           pos++;
           //S_CORPUSSUBJECT
           ps.setString(pos, dto.getScorpussubject());
           pos++;
           //S_ACCRUALSUBJECT
           ps.setString(pos, dto.getSaccrualsubject());
           pos++;
           ps.executeUpdate();
        }
        finally
        {
           close(ps);
        }

        return ;
    }
    
    
    
      /**
     * Update batch record in Database.
     */

    public void update(IDto[] _dtos, Connection conn, boolean isLobSupport) throws SQLException
    {
     
     	 HtrTaxorgDebtReportDto dto  ;
         for (int i= 0; i< _dtos.length ; i++)
         {
            dto  = (HtrTaxorgDebtReportDto)_dtos[i] ; 
            String msgValid = dto.checkValid() ;
            if (msgValid != null)
                throw new SQLException("修改错误，"+msgValid) ;
         }

        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            
            for (int i= 0; i< _dtos.length ; i++)
            {
                dto  = (HtrTaxorgDebtReportDto)_dtos[i] ; 
                int pos = 1;
                //S_KINDSIGN
                 ps.setString(pos, dto.getSkindsign());
                pos++;

                //N_CORDAYAMT
                 ps.setBigDecimal(pos, dto.getNcordayamt());
                pos++;

                //N_CORTENDAYAMT
                 ps.setBigDecimal(pos, dto.getNcortendayamt());
                pos++;

                //N_CORMONTHAMT
                 ps.setBigDecimal(pos, dto.getNcormonthamt());
                pos++;

                //N_CORQUARTERAMT
                 ps.setBigDecimal(pos, dto.getNcorquarteramt());
                pos++;

                //N_CORYEARAMT
                 ps.setBigDecimal(pos, dto.getNcoryearamt());
                pos++;

                //N_ACCDAYAMT
                 ps.setBigDecimal(pos, dto.getNaccdayamt());
                pos++;

                //N_ACCTENDAYAMT
                 ps.setBigDecimal(pos, dto.getNacctendayamt());
                pos++;

                //N_ACCMONTHAMT
                 ps.setBigDecimal(pos, dto.getNaccmonthamt());
                pos++;

                //N_ACCQUARTERAMT
                 ps.setBigDecimal(pos, dto.getNaccquarteramt());
                pos++;

                //N_ACCYEARAMT
                 ps.setBigDecimal(pos, dto.getNaccyearamt());
                pos++;


               //S_TAXORGCODE
               ps.setString(pos, dto.getStaxorgcode());
               pos++;
               //S_TRECODE
               ps.setString(pos, dto.getStrecode());
               pos++;
               //S_RPTDATE
               ps.setString(pos, dto.getSrptdate());
               pos++;
               //S_CASHBANK
               ps.setString(pos, dto.getScashbank());
               pos++;
               //S_CORPUSSUBJECT
               ps.setString(pos, dto.getScorpussubject());
               pos++;
               //S_ACCRUALSUBJECT
               ps.setString(pos, dto.getSaccrualsubject());
               pos++;
		       ps.addBatch(); 
	       }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }

        return ;
    }



    /**
     * delete a record in Database.
     */
    public void delete(IPK _pk, Connection conn) throws SQLException
    {
       
      
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return ;
        //	throw new SQLException("删除错误，"+msgValid) ;
       }
       HtrTaxorgDebtReportPK pk = (HtrTaxorgDebtReportPK)_pk ;


       PreparedStatement ps = null;
       try {
           ps = conn.prepareStatement(SQL_DELETE);
           ps.setString(1, pk.getStaxorgcode());
           ps.setString(2, pk.getStrecode());
           ps.setString(3, pk.getSrptdate());
           ps.setString(4, pk.getScashbank());
           ps.setString(5, pk.getScorpussubject());
           ps.setString(6, pk.getSaccrualsubject());
           ps.executeUpdate();
        }
        finally
        {
            close(ps);
        }
    }


     /**
     * delete batch record in Database.
     */
    public void delete(IPK[] _pks, Connection conn) throws SQLException
    {
        HtrTaxorgDebtReportPK pk ;
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (HtrTaxorgDebtReportPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 		
 		
        PreparedStatement ps = null;
        try
         {
            ps = conn.prepareStatement(SQL_DELETE);
             
       		for (int i= 0; i< pks.size() ; i++)
       		{
       			pk  = (HtrTaxorgDebtReportPK)(pks.get(i)) ; 
                ps.setString(1, pk.getStaxorgcode());
                ps.setString(2, pk.getStrecode());
                ps.setString(3, pk.getSrptdate());
                ps.setString(4, pk.getScashbank());
                ps.setString(5, pk.getScorpussubject());
                ps.setString(6, pk.getSaccrualsubject());
		        ps.addBatch() ;
			}
            ps.executeBatch();
        }
        finally
        {
            close(ps);
        }      
    }



    /**
    * Check IChangerNumber or UpdateTimeStamp.
    */
    public void check(IDto _dto, Connection conn) throws SQLException
    {
                                 		throw new SQLException("数据库表：HTR_TAXORG_DEBT_REPORT没有检查修改的字段");
    }


	/**
	* synchronize values between parent and children
	*/
    public void syncToChildren(IDto _dto)     throws SQLException{
       throw new SQLException("本记录没有与其它记录相关联，无法进行主记录与明细记录之间的数据同步。");
  }

	/**
	*get children
	*/
    public IDto[] findChildren (IDto _dto, Connection conn, boolean isLobSupport)     throws SQLException{
         throw new SQLException("本dto没有与其它dto相关联，无法得到子dto");
  }    
    
  /**
   *return the children IDto class
   * @return Class
   */
  public Class getChildrenClass(){
	  return null;
  };    



    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt)
    {
        if (stmt != null)
        {
            try
            {
                stmt.close();
            }
            catch(SQLException    e)
            {}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs)
    {
        if (rs != null)
        {
            try
            {
                rs.close();
            }catch(SQLException  e){}
        }
    }
}
