    



package com.cfcc.itfe.persistence.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;
import java.sql.Clob;

import com.cfcc.jaf.persistence.jaform.parent.* ;

import java.math.BigDecimal;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

import java.io.StringReader;
import java.io.Reader;
import java.io.IOException;

import com.cfcc.itfe.persistence.dto.HtvInCorrhandbookDto ;
import com.cfcc.itfe.persistence.pk.HtvInCorrhandbookPK ;


/**
 * <p>Title: DAO of table: HTV_IN_CORRHANDBOOK</p>
 * <p>Description: Data Access Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:56 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dao.vm timestamp: 2007-04-06 08:30:00
 ******************************************************
 * <p> <b>change record</b><br>
 *  make dao methods simply.<br>
 *  especially make update,delete methods simply.<br>
 *  remove "..withCheck" method,withCheck will impl in JAFOrmTemplate.<br>
 *  remove "delete(IDto _dto,..)" method.<br></p>
 * @author win7
 */

public class HtvInCorrhandbookDao  implements IDao
{


    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO HTV_IN_CORRHANDBOOK ("
          + "I_VOUSRLNO,S_ELECVOUNO,S_CORRVOUNO,D_ACCEPT,D_ACCT"
          + ",D_VOUCHER,S_ORIPAYEETRECODE,S_ORIAIMTRECODE,S_ORITAXORGCODE,S_ORIBDGSBTCODE"
          + ",C_ORIBDGLEVEL,C_ORIBDGKIND,S_ORIASTFLAG,F_ORICORRAMT,S_CURPAYEETRECODE"
          + ",S_CURAIMTRECODE,S_CURTAXORGCODE,S_CURBDGSBTCODE,C_CURBDGLEVEL,C_CURBDGKIND"
          + ",S_CURASTFLAG,F_CURCORRAMT,S_REASONCODE,C_TRIMFLAG,S_PACKAGENO"
          + ",S_STATUS,S_FILENAME,S_BOOKORGCODE,TS_SYSUPDATE,S_TBSORIASTFLAG"
          + ",S_TBSCURASTFLAG,S_DEALNO,S_DEMO"
        + ") VALUES ("
        + "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT TIMESTAMP ,?,?,?,?)";


    private static final String SQL_INSERT_WITH_RESULT = "SELECT * FROM FINAL TABLE( " + SQL_INSERT + " )";
    
    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "HTV_IN_CORRHANDBOOK.I_VOUSRLNO, HTV_IN_CORRHANDBOOK.S_ELECVOUNO, HTV_IN_CORRHANDBOOK.S_CORRVOUNO, HTV_IN_CORRHANDBOOK.D_ACCEPT, HTV_IN_CORRHANDBOOK.D_ACCT, "
        + "HTV_IN_CORRHANDBOOK.D_VOUCHER, HTV_IN_CORRHANDBOOK.S_ORIPAYEETRECODE, HTV_IN_CORRHANDBOOK.S_ORIAIMTRECODE, HTV_IN_CORRHANDBOOK.S_ORITAXORGCODE, HTV_IN_CORRHANDBOOK.S_ORIBDGSBTCODE, "
        + "HTV_IN_CORRHANDBOOK.C_ORIBDGLEVEL, HTV_IN_CORRHANDBOOK.C_ORIBDGKIND, HTV_IN_CORRHANDBOOK.S_ORIASTFLAG, HTV_IN_CORRHANDBOOK.F_ORICORRAMT, HTV_IN_CORRHANDBOOK.S_CURPAYEETRECODE, "
        + "HTV_IN_CORRHANDBOOK.S_CURAIMTRECODE, HTV_IN_CORRHANDBOOK.S_CURTAXORGCODE, HTV_IN_CORRHANDBOOK.S_CURBDGSBTCODE, HTV_IN_CORRHANDBOOK.C_CURBDGLEVEL, HTV_IN_CORRHANDBOOK.C_CURBDGKIND, "
        + "HTV_IN_CORRHANDBOOK.S_CURASTFLAG, HTV_IN_CORRHANDBOOK.F_CURCORRAMT, HTV_IN_CORRHANDBOOK.S_REASONCODE, HTV_IN_CORRHANDBOOK.C_TRIMFLAG, HTV_IN_CORRHANDBOOK.S_PACKAGENO, "
        + "HTV_IN_CORRHANDBOOK.S_STATUS, HTV_IN_CORRHANDBOOK.S_FILENAME, HTV_IN_CORRHANDBOOK.S_BOOKORGCODE, HTV_IN_CORRHANDBOOK.TS_SYSUPDATE, HTV_IN_CORRHANDBOOK.S_TBSORIASTFLAG, "
        + "HTV_IN_CORRHANDBOOK.S_TBSCURASTFLAG, HTV_IN_CORRHANDBOOK.S_DEALNO, HTV_IN_CORRHANDBOOK.S_DEMO "
        + "FROM HTV_IN_CORRHANDBOOK "
        +" WHERE " 
        + "I_VOUSRLNO = ?"
        ;
    /* SQL to select for update data */
    private static final String SQL_SELECT_FOR_UPDATE =
        "SELECT "
        + "HTV_IN_CORRHANDBOOK.I_VOUSRLNO, HTV_IN_CORRHANDBOOK.S_ELECVOUNO, HTV_IN_CORRHANDBOOK.S_CORRVOUNO, HTV_IN_CORRHANDBOOK.D_ACCEPT, HTV_IN_CORRHANDBOOK.D_ACCT, "
        + "HTV_IN_CORRHANDBOOK.D_VOUCHER, HTV_IN_CORRHANDBOOK.S_ORIPAYEETRECODE, HTV_IN_CORRHANDBOOK.S_ORIAIMTRECODE, HTV_IN_CORRHANDBOOK.S_ORITAXORGCODE, HTV_IN_CORRHANDBOOK.S_ORIBDGSBTCODE, "
        + "HTV_IN_CORRHANDBOOK.C_ORIBDGLEVEL, HTV_IN_CORRHANDBOOK.C_ORIBDGKIND, HTV_IN_CORRHANDBOOK.S_ORIASTFLAG, HTV_IN_CORRHANDBOOK.F_ORICORRAMT, HTV_IN_CORRHANDBOOK.S_CURPAYEETRECODE, "
        + "HTV_IN_CORRHANDBOOK.S_CURAIMTRECODE, HTV_IN_CORRHANDBOOK.S_CURTAXORGCODE, HTV_IN_CORRHANDBOOK.S_CURBDGSBTCODE, HTV_IN_CORRHANDBOOK.C_CURBDGLEVEL, HTV_IN_CORRHANDBOOK.C_CURBDGKIND, "
        + "HTV_IN_CORRHANDBOOK.S_CURASTFLAG, HTV_IN_CORRHANDBOOK.F_CURCORRAMT, HTV_IN_CORRHANDBOOK.S_REASONCODE, HTV_IN_CORRHANDBOOK.C_TRIMFLAG, HTV_IN_CORRHANDBOOK.S_PACKAGENO, "
        + "HTV_IN_CORRHANDBOOK.S_STATUS, HTV_IN_CORRHANDBOOK.S_FILENAME, HTV_IN_CORRHANDBOOK.S_BOOKORGCODE, HTV_IN_CORRHANDBOOK.TS_SYSUPDATE, HTV_IN_CORRHANDBOOK.S_TBSORIASTFLAG, "
        + "HTV_IN_CORRHANDBOOK.S_TBSCURASTFLAG, HTV_IN_CORRHANDBOOK.S_DEALNO, HTV_IN_CORRHANDBOOK.S_DEMO "
        + "FROM HTV_IN_CORRHANDBOOK "
        +" WHERE " 
        + "I_VOUSRLNO = ? FOR UPDATE"
        ;

      /* SQL to select data (SCROLLABLE)*/
     private static final String SQL_SELECT_BATCH_SCROLLABLE =
        "SELECT "
        + "  HTV_IN_CORRHANDBOOK.I_VOUSRLNO  , HTV_IN_CORRHANDBOOK.S_ELECVOUNO  , HTV_IN_CORRHANDBOOK.S_CORRVOUNO  , HTV_IN_CORRHANDBOOK.D_ACCEPT  , HTV_IN_CORRHANDBOOK.D_ACCT "
        + " , HTV_IN_CORRHANDBOOK.D_VOUCHER  , HTV_IN_CORRHANDBOOK.S_ORIPAYEETRECODE  , HTV_IN_CORRHANDBOOK.S_ORIAIMTRECODE  , HTV_IN_CORRHANDBOOK.S_ORITAXORGCODE  , HTV_IN_CORRHANDBOOK.S_ORIBDGSBTCODE "
        + " , HTV_IN_CORRHANDBOOK.C_ORIBDGLEVEL  , HTV_IN_CORRHANDBOOK.C_ORIBDGKIND  , HTV_IN_CORRHANDBOOK.S_ORIASTFLAG  , HTV_IN_CORRHANDBOOK.F_ORICORRAMT  , HTV_IN_CORRHANDBOOK.S_CURPAYEETRECODE "
        + " , HTV_IN_CORRHANDBOOK.S_CURAIMTRECODE  , HTV_IN_CORRHANDBOOK.S_CURTAXORGCODE  , HTV_IN_CORRHANDBOOK.S_CURBDGSBTCODE  , HTV_IN_CORRHANDBOOK.C_CURBDGLEVEL  , HTV_IN_CORRHANDBOOK.C_CURBDGKIND "
        + " , HTV_IN_CORRHANDBOOK.S_CURASTFLAG  , HTV_IN_CORRHANDBOOK.F_CURCORRAMT  , HTV_IN_CORRHANDBOOK.S_REASONCODE  , HTV_IN_CORRHANDBOOK.C_TRIMFLAG  , HTV_IN_CORRHANDBOOK.S_PACKAGENO "
        + " , HTV_IN_CORRHANDBOOK.S_STATUS  , HTV_IN_CORRHANDBOOK.S_FILENAME  , HTV_IN_CORRHANDBOOK.S_BOOKORGCODE  , HTV_IN_CORRHANDBOOK.TS_SYSUPDATE  , HTV_IN_CORRHANDBOOK.S_TBSORIASTFLAG "
        + " , HTV_IN_CORRHANDBOOK.S_TBSCURASTFLAG  , HTV_IN_CORRHANDBOOK.S_DEALNO  , HTV_IN_CORRHANDBOOK.S_DEMO "
        + "FROM HTV_IN_CORRHANDBOOK ";



    /* SQL to select batch data */
    private static final String SQL_SELECT_BATCH =
        "SELECT "
        + "HTV_IN_CORRHANDBOOK.I_VOUSRLNO, HTV_IN_CORRHANDBOOK.S_ELECVOUNO, HTV_IN_CORRHANDBOOK.S_CORRVOUNO, HTV_IN_CORRHANDBOOK.D_ACCEPT, HTV_IN_CORRHANDBOOK.D_ACCT, "
        + "HTV_IN_CORRHANDBOOK.D_VOUCHER, HTV_IN_CORRHANDBOOK.S_ORIPAYEETRECODE, HTV_IN_CORRHANDBOOK.S_ORIAIMTRECODE, HTV_IN_CORRHANDBOOK.S_ORITAXORGCODE, HTV_IN_CORRHANDBOOK.S_ORIBDGSBTCODE, "
        + "HTV_IN_CORRHANDBOOK.C_ORIBDGLEVEL, HTV_IN_CORRHANDBOOK.C_ORIBDGKIND, HTV_IN_CORRHANDBOOK.S_ORIASTFLAG, HTV_IN_CORRHANDBOOK.F_ORICORRAMT, HTV_IN_CORRHANDBOOK.S_CURPAYEETRECODE, "
        + "HTV_IN_CORRHANDBOOK.S_CURAIMTRECODE, HTV_IN_CORRHANDBOOK.S_CURTAXORGCODE, HTV_IN_CORRHANDBOOK.S_CURBDGSBTCODE, HTV_IN_CORRHANDBOOK.C_CURBDGLEVEL, HTV_IN_CORRHANDBOOK.C_CURBDGKIND, "
        + "HTV_IN_CORRHANDBOOK.S_CURASTFLAG, HTV_IN_CORRHANDBOOK.F_CURCORRAMT, HTV_IN_CORRHANDBOOK.S_REASONCODE, HTV_IN_CORRHANDBOOK.C_TRIMFLAG, HTV_IN_CORRHANDBOOK.S_PACKAGENO, "
        + "HTV_IN_CORRHANDBOOK.S_STATUS, HTV_IN_CORRHANDBOOK.S_FILENAME, HTV_IN_CORRHANDBOOK.S_BOOKORGCODE, HTV_IN_CORRHANDBOOK.TS_SYSUPDATE, HTV_IN_CORRHANDBOOK.S_TBSORIASTFLAG, "
        + "HTV_IN_CORRHANDBOOK.S_TBSCURASTFLAG, HTV_IN_CORRHANDBOOK.S_DEALNO, HTV_IN_CORRHANDBOOK.S_DEMO "
        + "FROM HTV_IN_CORRHANDBOOK " ;
        

   /* SQL to select batch data where condition  */
    private static final String SQL_SELECT_BATCH_WHERE =" ( "
        + "I_VOUSRLNO = ?)"
        ;


    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE HTV_IN_CORRHANDBOOK SET "
        + "S_ELECVOUNO =?,S_CORRVOUNO =?,D_ACCEPT =?,D_ACCT =?,D_VOUCHER =?, "
        + "S_ORIPAYEETRECODE =?,S_ORIAIMTRECODE =?,S_ORITAXORGCODE =?,S_ORIBDGSBTCODE =?,C_ORIBDGLEVEL =?, "
        + "C_ORIBDGKIND =?,S_ORIASTFLAG =?,F_ORICORRAMT =?,S_CURPAYEETRECODE =?,S_CURAIMTRECODE =?, "
        + "S_CURTAXORGCODE =?,S_CURBDGSBTCODE =?,C_CURBDGLEVEL =?,C_CURBDGKIND =?,S_CURASTFLAG =?, "
        + "F_CURCORRAMT =?,S_REASONCODE =?,C_TRIMFLAG =?,S_PACKAGENO =?,S_STATUS =?, "
        + "S_FILENAME =?,S_BOOKORGCODE =?,TS_SYSUPDATE =CURRENT TIMESTAMP,S_TBSORIASTFLAG =?,S_TBSCURASTFLAG =?, "
        + "S_DEALNO =?,S_DEMO =? "
        + "WHERE "
        + "I_VOUSRLNO = ?"
        ;

	/* SQL to update data, support LOB */
    private static final String SQL_UPDATE_LOB =
        "UPDATE HTV_IN_CORRHANDBOOK SET "
        + "S_ELECVOUNO =?, S_CORRVOUNO =?, D_ACCEPT =?, D_ACCT =?, D_VOUCHER =?,  "
        + "S_ORIPAYEETRECODE =?, S_ORIAIMTRECODE =?, S_ORITAXORGCODE =?, S_ORIBDGSBTCODE =?, C_ORIBDGLEVEL =?,  "
        + "C_ORIBDGKIND =?, S_ORIASTFLAG =?, F_ORICORRAMT =?, S_CURPAYEETRECODE =?, S_CURAIMTRECODE =?,  "
        + "S_CURTAXORGCODE =?, S_CURBDGSBTCODE =?, C_CURBDGLEVEL =?, C_CURBDGKIND =?, S_CURASTFLAG =?,  "
        + "F_CURCORRAMT =?, S_REASONCODE =?, C_TRIMFLAG =?, S_PACKAGENO =?, S_STATUS =?,  "
        + "S_FILENAME =?, S_BOOKORGCODE =?, TS_SYSUPDATE =CURRENT TIMESTAMP, S_TBSORIASTFLAG =?, S_TBSCURASTFLAG =?,  "
        + "S_DEALNO =?, S_DEMO =? "
        + "WHERE "
        + "I_VOUSRLNO = ?"
        ;	
	
    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM HTV_IN_CORRHANDBOOK " 
        + " WHERE "
        + "I_VOUSRLNO = ?"
        ;


	/**
	*  批量查询 一次最多查询的参数数量
	*/
	
	public static final int FIND_BATCH_SIZE = 150  / 1;
	



   /**
   * Create a new record in Database.
   */
  public void create(IDto _dto,  Connection conn) throws SQLException
  {
     HtvInCorrhandbookDto dto = (HtvInCorrhandbookDto)_dto ;
     String msgValid = dto.checkValid() ;
     if (msgValid != null)
     	throw new SQLException("插入错误，"+msgValid) ;

     PreparedStatement ps = null;
     try
     {
         ps = conn.prepareStatement(SQL_INSERT);
          if (dto.getIvousrlno()==null)
            ps.setNull(1, java.sql.Types.BIGINT);
         else
            ps.setLong(1, dto.getIvousrlno().longValue());
          ps.setString(2, dto.getSelecvouno());

          ps.setString(3, dto.getScorrvouno());

          ps.setDate(4, dto.getDaccept());

          ps.setDate(5, dto.getDacct());

          ps.setDate(6, dto.getDvoucher());

          ps.setString(7, dto.getSoripayeetrecode());

          ps.setString(8, dto.getSoriaimtrecode());

          ps.setString(9, dto.getSoritaxorgcode());

          ps.setString(10, dto.getSoribdgsbtcode());

          ps.setString(11, dto.getCoribdglevel());

          ps.setString(12, dto.getCoribdgkind());

          ps.setString(13, dto.getSoriastflag());

          ps.setBigDecimal(14, dto.getForicorramt());

          ps.setString(15, dto.getScurpayeetrecode());

          ps.setString(16, dto.getScuraimtrecode());

          ps.setString(17, dto.getScurtaxorgcode());

          ps.setString(18, dto.getScurbdgsbtcode());

          ps.setString(19, dto.getCcurbdglevel());

          ps.setString(20, dto.getCcurbdgkind());

          ps.setString(21, dto.getScurastflag());

          ps.setBigDecimal(22, dto.getFcurcorramt());

          ps.setString(23, dto.getSreasoncode());

          ps.setString(24, dto.getCtrimflag());

          ps.setString(25, dto.getSpackageno());

          ps.setString(26, dto.getSstatus());

          ps.setString(27, dto.getSfilename());

          ps.setString(28, dto.getSbookorgcode());

           ps.setString(29, dto.getStbsoriastflag());

          ps.setString(30, dto.getStbscurastflag());

          ps.setString(31, dto.getSdealno());

          ps.setString(32, dto.getSdemo());

         ps.executeUpdate();
     }
     finally
     {
         close(ps);
     }
     return  ;
  }

   /**
   * Create a new record in Database. and return result, only used when having generated key
   */
   public IDto createWithResult(IDto _dto,  Connection conn) throws SQLException
   {
       HtvInCorrhandbookDto dto = (HtvInCorrhandbookDto)_dto ;
       String msgValid = dto.checkValid() ;
       if (msgValid != null)
           throw new SQLException("插入错误，"+msgValid) ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try
       {
           ps = conn.prepareStatement(SQL_INSERT_WITH_RESULT);
            if (dto.getIvousrlno()==null)
              ps.setNull(1, java.sql.Types.BIGINT);
           else
              ps.setLong(1, dto.getIvousrlno().longValue());
            ps.setString(2, dto.getSelecvouno());
            ps.setString(3, dto.getScorrvouno());
            ps.setDate(4, dto.getDaccept());
            ps.setDate(5, dto.getDacct());
            ps.setDate(6, dto.getDvoucher());
            ps.setString(7, dto.getSoripayeetrecode());
            ps.setString(8, dto.getSoriaimtrecode());
            ps.setString(9, dto.getSoritaxorgcode());
            ps.setString(10, dto.getSoribdgsbtcode());
            ps.setString(11, dto.getCoribdglevel());
            ps.setString(12, dto.getCoribdgkind());
            ps.setString(13, dto.getSoriastflag());
            ps.setBigDecimal(14, dto.getForicorramt());
            ps.setString(15, dto.getScurpayeetrecode());
            ps.setString(16, dto.getScuraimtrecode());
            ps.setString(17, dto.getScurtaxorgcode());
            ps.setString(18, dto.getScurbdgsbtcode());
            ps.setString(19, dto.getCcurbdglevel());
            ps.setString(20, dto.getCcurbdgkind());
            ps.setString(21, dto.getScurastflag());
            ps.setBigDecimal(22, dto.getFcurcorramt());
            ps.setString(23, dto.getSreasoncode());
            ps.setString(24, dto.getCtrimflag());
            ps.setString(25, dto.getSpackageno());
            ps.setString(26, dto.getSstatus());
            ps.setString(27, dto.getSfilename());
            ps.setString(28, dto.getSbookorgcode());
             ps.setString(29, dto.getStbsoriastflag());
            ps.setString(30, dto.getStbscurastflag());
            ps.setString(31, dto.getSdealno());
            ps.setString(32, dto.getSdemo());
           rs = ps.executeQuery();
           List results = getResults(rs);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }
        finally
        {
           close(ps);
           close(rs);
        }
   }

 	/**
	* Create batch new record in Database. it only create the first layer dto
	*/
    public void create(IDto[] _dtos, Connection conn)    throws SQLException
    {
        HtvInCorrhandbookDto dto  ;
     	for (int i= 0; i< _dtos.length ; i++)
 	    {
 		    dto  = (HtvInCorrhandbookDto)_dtos[i] ; 
    	    String msgValid = dto.checkValid() ;
        	if (msgValid != null)
     	    	throw new SQLException("插入错误，"+msgValid) ;
     	}
 	    PreparedStatement ps = null;
        try
        {
            ps = conn.prepareStatement(SQL_INSERT);
       
     	    for (int i= 0; i< _dtos.length ; i++)
     	    {
 	    	    dto  = (HtvInCorrhandbookDto)_dtos[i] ; 
  
               if (dto.getIvousrlno()==null)
                  ps.setNull(1, java.sql.Types.BIGINT);
               else
                  ps.setLong(1, dto.getIvousrlno().longValue());
  
               ps.setString(2, dto.getSelecvouno());
  
               ps.setString(3, dto.getScorrvouno());
  
               ps.setDate(4, dto.getDaccept());
  
               ps.setDate(5, dto.getDacct());
  
               ps.setDate(6, dto.getDvoucher());
  
               ps.setString(7, dto.getSoripayeetrecode());
  
               ps.setString(8, dto.getSoriaimtrecode());
  
               ps.setString(9, dto.getSoritaxorgcode());
  
               ps.setString(10, dto.getSoribdgsbtcode());
  
               ps.setString(11, dto.getCoribdglevel());
  
               ps.setString(12, dto.getCoribdgkind());
  
               ps.setString(13, dto.getSoriastflag());
  
               ps.setBigDecimal(14, dto.getForicorramt());
  
               ps.setString(15, dto.getScurpayeetrecode());
  
               ps.setString(16, dto.getScuraimtrecode());
  
               ps.setString(17, dto.getScurtaxorgcode());
  
               ps.setString(18, dto.getScurbdgsbtcode());
  
               ps.setString(19, dto.getCcurbdglevel());
  
               ps.setString(20, dto.getCcurbdgkind());
  
               ps.setString(21, dto.getScurastflag());
  
               ps.setBigDecimal(22, dto.getFcurcorramt());
  
               ps.setString(23, dto.getSreasoncode());
  
               ps.setString(24, dto.getCtrimflag());
  
               ps.setString(25, dto.getSpackageno());
  
               ps.setString(26, dto.getSstatus());
  
               ps.setString(27, dto.getSfilename());
  
               ps.setString(28, dto.getSbookorgcode());
   
               ps.setString(29, dto.getStbsoriastflag());
  
               ps.setString(30, dto.getStbscurastflag());
  
               ps.setString(31, dto.getSdealno());
  
               ps.setString(32, dto.getSdemo());
               ps.addBatch(); 
           }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }
        return  ;
   }




     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto find(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       HtvInCorrhandbookPK pk = (HtvInCorrhandbookPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT);
           if (pk.getIvousrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIvousrlno().longValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }

     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto findForUpdate(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       HtvInCorrhandbookPK pk = (HtvInCorrhandbookPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT_FOR_UPDATE);
           if (pk.getIvousrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIvousrlno().longValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }
  
     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto[] find(IPK[] _pks, Connection conn, boolean isLobSupport) throws SQLException
    {
        HtvInCorrhandbookPK pk ;
        
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (HtvInCorrhandbookPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 
        PreparedStatement ps = null;
        ResultSet rs = null;
        
         
        List results = new ArrayList();  
		for (int iBegin = 0; iBegin < pks.size(); iBegin += FIND_BATCH_SIZE)   //
		{
        
            try {
          		int iFindBatchSize = pks.size() - iBegin ;
	    		if (iFindBatchSize >FIND_BATCH_SIZE )
		    		iFindBatchSize = FIND_BATCH_SIZE ;
		  
        	    StringBuffer sb = new StringBuffer() ;
            	sb.append(SQL_SELECT_BATCH).append(" WHERE ").append(SQL_SELECT_BATCH_WHERE);

	    		for (int i = iBegin+1; i < iBegin + iFindBatchSize; i++)
		    	{
			    	sb.append("OR").append(SQL_SELECT_BATCH_WHERE) ;
    			}
        	
                ps = conn.prepareStatement(sb.toString());

                for (int i = iBegin;i < iBegin + iFindBatchSize; i++)
                {
                    pk  = (HtvInCorrhandbookPK)(pks.get(i)) ; 
                   if (pk.getIvousrlno()==null)
                      ps.setNull((i-iBegin)*1+1, java.sql.Types.BIGINT);
                   else
                      ps.setLong((i-iBegin)*1+1, pk.getIvousrlno().longValue());

			
	            }
                rs = ps.executeQuery();
                results.addAll(getResults(rs,0,isLobSupport)); //
            }finally {
                close(rs);
                close(ps);
            }
        }
        if (results!=null && results.size() > 0)
        {
            HtvInCorrhandbookDto[] dtos = new HtvInCorrhandbookDto[0];
		    dtos = (HtvInCorrhandbookDto[]) results.toArray(dtos) ;
		    return dtos ;
        }
        else
        {
            return null;
        }
    }

  
  
  



    /**
	    * 得到查询语句
	    */
    public String getSelectSQL() 
    {
	        return SQL_SELECT_BATCH_SCROLLABLE ;
    }
   

	public List getResults(ResultSet rs) throws SQLException
    {
    	return getResults(rs, 0) ;
    }
  

    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize) throws SQLException
    {
		return getResults(rs,maxSize,false);
	}
    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize, boolean isLobSupport) throws SQLException
    {
        List results = new ArrayList();
        String str ;
        Reader reader;
        Clob clob;
        char[] chars ;
        
        while (rs.next())
         {
             HtvInCorrhandbookDto  dto = new  HtvInCorrhandbookDto ();
             //I_VOUSRLNO
             str = rs.getString("I_VOUSRLNO");
             if(str!=null){
                dto.setIvousrlno(new Long(str));
             }

             //S_ELECVOUNO
             str = rs.getString("S_ELECVOUNO");
             if (str == null)
                dto.setSelecvouno(null);
             else
                dto.setSelecvouno(str.trim());

             //S_CORRVOUNO
             str = rs.getString("S_CORRVOUNO");
             if (str == null)
                dto.setScorrvouno(null);
             else
                dto.setScorrvouno(str.trim());

             //D_ACCEPT
           dto.setDaccept(rs.getDate("D_ACCEPT"));

             //D_ACCT
           dto.setDacct(rs.getDate("D_ACCT"));

             //D_VOUCHER
           dto.setDvoucher(rs.getDate("D_VOUCHER"));

             //S_ORIPAYEETRECODE
             str = rs.getString("S_ORIPAYEETRECODE");
             if (str == null)
                dto.setSoripayeetrecode(null);
             else
                dto.setSoripayeetrecode(str.trim());

             //S_ORIAIMTRECODE
             str = rs.getString("S_ORIAIMTRECODE");
             if (str == null)
                dto.setSoriaimtrecode(null);
             else
                dto.setSoriaimtrecode(str.trim());

             //S_ORITAXORGCODE
             str = rs.getString("S_ORITAXORGCODE");
             if (str == null)
                dto.setSoritaxorgcode(null);
             else
                dto.setSoritaxorgcode(str.trim());

             //S_ORIBDGSBTCODE
             str = rs.getString("S_ORIBDGSBTCODE");
             if (str == null)
                dto.setSoribdgsbtcode(null);
             else
                dto.setSoribdgsbtcode(str.trim());

             //C_ORIBDGLEVEL
             str = rs.getString("C_ORIBDGLEVEL");
             if (str == null)
                dto.setCoribdglevel(null);
             else
                dto.setCoribdglevel(str.trim());

             //C_ORIBDGKIND
             str = rs.getString("C_ORIBDGKIND");
             if (str == null)
                dto.setCoribdgkind(null);
             else
                dto.setCoribdgkind(str.trim());

             //S_ORIASTFLAG
             str = rs.getString("S_ORIASTFLAG");
             if (str == null)
                dto.setSoriastflag(null);
             else
                dto.setSoriastflag(str.trim());

             //F_ORICORRAMT
           dto.setForicorramt(rs.getBigDecimal("F_ORICORRAMT"));

             //S_CURPAYEETRECODE
             str = rs.getString("S_CURPAYEETRECODE");
             if (str == null)
                dto.setScurpayeetrecode(null);
             else
                dto.setScurpayeetrecode(str.trim());

             //S_CURAIMTRECODE
             str = rs.getString("S_CURAIMTRECODE");
             if (str == null)
                dto.setScuraimtrecode(null);
             else
                dto.setScuraimtrecode(str.trim());

             //S_CURTAXORGCODE
             str = rs.getString("S_CURTAXORGCODE");
             if (str == null)
                dto.setScurtaxorgcode(null);
             else
                dto.setScurtaxorgcode(str.trim());

             //S_CURBDGSBTCODE
             str = rs.getString("S_CURBDGSBTCODE");
             if (str == null)
                dto.setScurbdgsbtcode(null);
             else
                dto.setScurbdgsbtcode(str.trim());

             //C_CURBDGLEVEL
             str = rs.getString("C_CURBDGLEVEL");
             if (str == null)
                dto.setCcurbdglevel(null);
             else
                dto.setCcurbdglevel(str.trim());

             //C_CURBDGKIND
             str = rs.getString("C_CURBDGKIND");
             if (str == null)
                dto.setCcurbdgkind(null);
             else
                dto.setCcurbdgkind(str.trim());

             //S_CURASTFLAG
             str = rs.getString("S_CURASTFLAG");
             if (str == null)
                dto.setScurastflag(null);
             else
                dto.setScurastflag(str.trim());

             //F_CURCORRAMT
           dto.setFcurcorramt(rs.getBigDecimal("F_CURCORRAMT"));

             //S_REASONCODE
             str = rs.getString("S_REASONCODE");
             if (str == null)
                dto.setSreasoncode(null);
             else
                dto.setSreasoncode(str.trim());

             //C_TRIMFLAG
             str = rs.getString("C_TRIMFLAG");
             if (str == null)
                dto.setCtrimflag(null);
             else
                dto.setCtrimflag(str.trim());

             //S_PACKAGENO
             str = rs.getString("S_PACKAGENO");
             if (str == null)
                dto.setSpackageno(null);
             else
                dto.setSpackageno(str.trim());

             //S_STATUS
             str = rs.getString("S_STATUS");
             if (str == null)
                dto.setSstatus(null);
             else
                dto.setSstatus(str.trim());

             //S_FILENAME
             str = rs.getString("S_FILENAME");
             if (str == null)
                dto.setSfilename(null);
             else
                dto.setSfilename(str.trim());

             //S_BOOKORGCODE
             str = rs.getString("S_BOOKORGCODE");
             if (str == null)
                dto.setSbookorgcode(null);
             else
                dto.setSbookorgcode(str.trim());

             //TS_SYSUPDATE
           dto.setTssysupdate(rs.getTimestamp("TS_SYSUPDATE"));

             //S_TBSORIASTFLAG
             str = rs.getString("S_TBSORIASTFLAG");
             if (str == null)
                dto.setStbsoriastflag(null);
             else
                dto.setStbsoriastflag(str.trim());

             //S_TBSCURASTFLAG
             str = rs.getString("S_TBSCURASTFLAG");
             if (str == null)
                dto.setStbscurastflag(null);
             else
                dto.setStbscurastflag(str.trim());

             //S_DEALNO
             str = rs.getString("S_DEALNO");
             if (str == null)
                dto.setSdealno(null);
             else
                dto.setSdealno(str.trim());

             //S_DEMO
             str = rs.getString("S_DEMO");
             if (str == null)
                dto.setSdemo(null);
             else
                dto.setSdemo(str.trim());



            results.add(dto);
            
            if(maxSize >0  && results.size() == maxSize)
            {
            	break ;
            }
            
         }
        
		return results ;
    }

  /**
   * populate resultSet as cclass
   */
  protected IDto[] getChildrenResults(ResultSet rs ,Class _dto) throws SQLException{

      throw new SQLException("本dto没有与其它dto相关联，无法应用此方法");
  }


     /**
     * Update a record in Database.
     */

    public void update(IDto _dto, Connection conn, boolean isLobSupport) throws SQLException
    {
        String msgValid = _dto.checkValid() ;
        if (msgValid != null)
            throw new SQLException("修改错误，"+msgValid) ;
        HtvInCorrhandbookDto dto = (HtvInCorrhandbookDto)_dto ;
        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            int pos = 1;
            //S_ELECVOUNO
            ps.setString(pos, dto.getSelecvouno());
            pos++;

            //S_CORRVOUNO
            ps.setString(pos, dto.getScorrvouno());
            pos++;

            //D_ACCEPT
            ps.setDate(pos, dto.getDaccept());
            pos++;

            //D_ACCT
            ps.setDate(pos, dto.getDacct());
            pos++;

            //D_VOUCHER
            ps.setDate(pos, dto.getDvoucher());
            pos++;

            //S_ORIPAYEETRECODE
            ps.setString(pos, dto.getSoripayeetrecode());
            pos++;

            //S_ORIAIMTRECODE
            ps.setString(pos, dto.getSoriaimtrecode());
            pos++;

            //S_ORITAXORGCODE
            ps.setString(pos, dto.getSoritaxorgcode());
            pos++;

            //S_ORIBDGSBTCODE
            ps.setString(pos, dto.getSoribdgsbtcode());
            pos++;

            //C_ORIBDGLEVEL
            ps.setString(pos, dto.getCoribdglevel());
            pos++;

            //C_ORIBDGKIND
            ps.setString(pos, dto.getCoribdgkind());
            pos++;

            //S_ORIASTFLAG
            ps.setString(pos, dto.getSoriastflag());
            pos++;

            //F_ORICORRAMT
            ps.setBigDecimal(pos, dto.getForicorramt());
            pos++;

            //S_CURPAYEETRECODE
            ps.setString(pos, dto.getScurpayeetrecode());
            pos++;

            //S_CURAIMTRECODE
            ps.setString(pos, dto.getScuraimtrecode());
            pos++;

            //S_CURTAXORGCODE
            ps.setString(pos, dto.getScurtaxorgcode());
            pos++;

            //S_CURBDGSBTCODE
            ps.setString(pos, dto.getScurbdgsbtcode());
            pos++;

            //C_CURBDGLEVEL
            ps.setString(pos, dto.getCcurbdglevel());
            pos++;

            //C_CURBDGKIND
            ps.setString(pos, dto.getCcurbdgkind());
            pos++;

            //S_CURASTFLAG
            ps.setString(pos, dto.getScurastflag());
            pos++;

            //F_CURCORRAMT
            ps.setBigDecimal(pos, dto.getFcurcorramt());
            pos++;

            //S_REASONCODE
            ps.setString(pos, dto.getSreasoncode());
            pos++;

            //C_TRIMFLAG
            ps.setString(pos, dto.getCtrimflag());
            pos++;

            //S_PACKAGENO
            ps.setString(pos, dto.getSpackageno());
            pos++;

            //S_STATUS
            ps.setString(pos, dto.getSstatus());
            pos++;

            //S_FILENAME
            ps.setString(pos, dto.getSfilename());
            pos++;

            //S_BOOKORGCODE
            ps.setString(pos, dto.getSbookorgcode());
            pos++;

            //TS_SYSUPDATE
            //S_TBSORIASTFLAG
            ps.setString(pos, dto.getStbsoriastflag());
            pos++;

            //S_TBSCURASTFLAG
            ps.setString(pos, dto.getStbscurastflag());
            pos++;

            //S_DEALNO
            ps.setString(pos, dto.getSdealno());
            pos++;

            //S_DEMO
            ps.setString(pos, dto.getSdemo());
            pos++;


           //I_VOUSRLNO
           ps.setLong(pos, dto.getIvousrlno().longValue());
           pos++;
           ps.executeUpdate();
        }
        finally
        {
           close(ps);
        }

        return ;
    }
    
    
    
      /**
     * Update batch record in Database.
     */

    public void update(IDto[] _dtos, Connection conn, boolean isLobSupport) throws SQLException
    {
     
     	 HtvInCorrhandbookDto dto  ;
         for (int i= 0; i< _dtos.length ; i++)
         {
            dto  = (HtvInCorrhandbookDto)_dtos[i] ; 
            String msgValid = dto.checkValid() ;
            if (msgValid != null)
                throw new SQLException("修改错误，"+msgValid) ;
         }

        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            
            for (int i= 0; i< _dtos.length ; i++)
            {
                dto  = (HtvInCorrhandbookDto)_dtos[i] ; 
                int pos = 1;
                //S_ELECVOUNO
                 ps.setString(pos, dto.getSelecvouno());
                pos++;

                //S_CORRVOUNO
                 ps.setString(pos, dto.getScorrvouno());
                pos++;

                //D_ACCEPT
                 ps.setDate(pos, dto.getDaccept());
                pos++;

                //D_ACCT
                 ps.setDate(pos, dto.getDacct());
                pos++;

                //D_VOUCHER
                 ps.setDate(pos, dto.getDvoucher());
                pos++;

                //S_ORIPAYEETRECODE
                 ps.setString(pos, dto.getSoripayeetrecode());
                pos++;

                //S_ORIAIMTRECODE
                 ps.setString(pos, dto.getSoriaimtrecode());
                pos++;

                //S_ORITAXORGCODE
                 ps.setString(pos, dto.getSoritaxorgcode());
                pos++;

                //S_ORIBDGSBTCODE
                 ps.setString(pos, dto.getSoribdgsbtcode());
                pos++;

                //C_ORIBDGLEVEL
                 ps.setString(pos, dto.getCoribdglevel());
                pos++;

                //C_ORIBDGKIND
                 ps.setString(pos, dto.getCoribdgkind());
                pos++;

                //S_ORIASTFLAG
                 ps.setString(pos, dto.getSoriastflag());
                pos++;

                //F_ORICORRAMT
                 ps.setBigDecimal(pos, dto.getForicorramt());
                pos++;

                //S_CURPAYEETRECODE
                 ps.setString(pos, dto.getScurpayeetrecode());
                pos++;

                //S_CURAIMTRECODE
                 ps.setString(pos, dto.getScuraimtrecode());
                pos++;

                //S_CURTAXORGCODE
                 ps.setString(pos, dto.getScurtaxorgcode());
                pos++;

                //S_CURBDGSBTCODE
                 ps.setString(pos, dto.getScurbdgsbtcode());
                pos++;

                //C_CURBDGLEVEL
                 ps.setString(pos, dto.getCcurbdglevel());
                pos++;

                //C_CURBDGKIND
                 ps.setString(pos, dto.getCcurbdgkind());
                pos++;

                //S_CURASTFLAG
                 ps.setString(pos, dto.getScurastflag());
                pos++;

                //F_CURCORRAMT
                 ps.setBigDecimal(pos, dto.getFcurcorramt());
                pos++;

                //S_REASONCODE
                 ps.setString(pos, dto.getSreasoncode());
                pos++;

                //C_TRIMFLAG
                 ps.setString(pos, dto.getCtrimflag());
                pos++;

                //S_PACKAGENO
                 ps.setString(pos, dto.getSpackageno());
                pos++;

                //S_STATUS
                 ps.setString(pos, dto.getSstatus());
                pos++;

                //S_FILENAME
                 ps.setString(pos, dto.getSfilename());
                pos++;

                //S_BOOKORGCODE
                 ps.setString(pos, dto.getSbookorgcode());
                pos++;

                //TS_SYSUPDATE
                 //S_TBSORIASTFLAG
                 ps.setString(pos, dto.getStbsoriastflag());
                pos++;

                //S_TBSCURASTFLAG
                 ps.setString(pos, dto.getStbscurastflag());
                pos++;

                //S_DEALNO
                 ps.setString(pos, dto.getSdealno());
                pos++;

                //S_DEMO
                 ps.setString(pos, dto.getSdemo());
                pos++;


               //I_VOUSRLNO
               ps.setLong(pos, dto.getIvousrlno().longValue());
               pos++;
		       ps.addBatch(); 
	       }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }

        return ;
    }



    /**
     * delete a record in Database.
     */
    public void delete(IPK _pk, Connection conn) throws SQLException
    {
       
      
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return ;
        //	throw new SQLException("删除错误，"+msgValid) ;
       }
       HtvInCorrhandbookPK pk = (HtvInCorrhandbookPK)_pk ;


       PreparedStatement ps = null;
       try {
           ps = conn.prepareStatement(SQL_DELETE);
           ps.setLong(1, pk.getIvousrlno().longValue());
           ps.executeUpdate();
        }
        finally
        {
            close(ps);
        }
    }


     /**
     * delete batch record in Database.
     */
    public void delete(IPK[] _pks, Connection conn) throws SQLException
    {
        HtvInCorrhandbookPK pk ;
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (HtvInCorrhandbookPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 		
 		
        PreparedStatement ps = null;
        try
         {
            ps = conn.prepareStatement(SQL_DELETE);
             
       		for (int i= 0; i< pks.size() ; i++)
       		{
       			pk  = (HtvInCorrhandbookPK)(pks.get(i)) ; 
                ps.setLong(1, pk.getIvousrlno().longValue());
		        ps.addBatch() ;
			}
            ps.executeBatch();
        }
        finally
        {
            close(ps);
        }      
    }



    /**
    * Check IChangerNumber or UpdateTimeStamp.
    */
    public void check(IDto _dto, Connection conn) throws SQLException
    {
                                                                                                		throw new SQLException("数据库表：HTV_IN_CORRHANDBOOK没有检查修改的字段");
    }


	/**
	* synchronize values between parent and children
	*/
    public void syncToChildren(IDto _dto)     throws SQLException{
       throw new SQLException("本记录没有与其它记录相关联，无法进行主记录与明细记录之间的数据同步。");
  }

	/**
	*get children
	*/
    public IDto[] findChildren (IDto _dto, Connection conn, boolean isLobSupport)     throws SQLException{
         throw new SQLException("本dto没有与其它dto相关联，无法得到子dto");
  }    
    
  /**
   *return the children IDto class
   * @return Class
   */
  public Class getChildrenClass(){
	  return null;
  };    



    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt)
    {
        if (stmt != null)
        {
            try
            {
                stmt.close();
            }
            catch(SQLException    e)
            {}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs)
    {
        if (rs != null)
        {
            try
            {
                rs.close();
            }catch(SQLException  e){}
        }
    }
}
