    



package com.cfcc.itfe.persistence.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;
import java.sql.Clob;

import com.cfcc.jaf.persistence.jaform.parent.* ;

import java.math.BigDecimal;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

import java.io.StringReader;
import java.io.Reader;
import java.io.IOException;

import com.cfcc.itfe.persistence.dto.TnConpaycheckbillDto ;
import com.cfcc.itfe.persistence.pk.TnConpaycheckbillPK ;


/**
 * <p>Title: DAO of table: TN_CONPAYCHECKBILL</p>
 * <p>Description: Data Access Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:59 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dao.vm timestamp: 2007-04-06 08:30:00
 ******************************************************
 * <p> <b>change record</b><br>
 *  make dao methods simply.<br>
 *  especially make update,delete methods simply.<br>
 *  remove "..withCheck" method,withCheck will impl in JAFOrmTemplate.<br>
 *  remove "delete(IDto _dto,..)" method.<br></p>
 * @author win7
 */

public class TnConpaycheckbillDao  implements IDao
{


    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO TN_CONPAYCHECKBILL ("
          + "I_ENROLSRLNO,D_ENDDATE,D_STARTDATE,S_BOOKORGCODE,S_TRECODE"
          + ",S_BDGORGCODE,S_BDGORGNAME,S_BNKNO,S_FUNCSBTCODE,S_ECOSBTCODE"
          + ",C_AMTKIND,F_LASTMONTHZEROAMT,F_CURZEROAMT,F_CURRECKZEROAMT,F_LASTMONTHSMALLAMT"
          + ",F_CURSMALLAMT,F_CURRECKSMALLAMT,TS_SYSUPDATE"
        + ") VALUES ("
        + "DEFAULT ,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT TIMESTAMP )";


    private static final String SQL_INSERT_WITH_RESULT = "SELECT * FROM FINAL TABLE( " + SQL_INSERT + " )";
    
    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "TN_CONPAYCHECKBILL.I_ENROLSRLNO, TN_CONPAYCHECKBILL.D_ENDDATE, TN_CONPAYCHECKBILL.D_STARTDATE, TN_CONPAYCHECKBILL.S_BOOKORGCODE, TN_CONPAYCHECKBILL.S_TRECODE, "
        + "TN_CONPAYCHECKBILL.S_BDGORGCODE, TN_CONPAYCHECKBILL.S_BDGORGNAME, TN_CONPAYCHECKBILL.S_BNKNO, TN_CONPAYCHECKBILL.S_FUNCSBTCODE, TN_CONPAYCHECKBILL.S_ECOSBTCODE, "
        + "TN_CONPAYCHECKBILL.C_AMTKIND, TN_CONPAYCHECKBILL.F_LASTMONTHZEROAMT, TN_CONPAYCHECKBILL.F_CURZEROAMT, TN_CONPAYCHECKBILL.F_CURRECKZEROAMT, TN_CONPAYCHECKBILL.F_LASTMONTHSMALLAMT, "
        + "TN_CONPAYCHECKBILL.F_CURSMALLAMT, TN_CONPAYCHECKBILL.F_CURRECKSMALLAMT, TN_CONPAYCHECKBILL.TS_SYSUPDATE "
        + "FROM TN_CONPAYCHECKBILL "
        +" WHERE " 
        + "I_ENROLSRLNO = ?"
        ;
    /* SQL to select for update data */
    private static final String SQL_SELECT_FOR_UPDATE =
        "SELECT "
        + "TN_CONPAYCHECKBILL.I_ENROLSRLNO, TN_CONPAYCHECKBILL.D_ENDDATE, TN_CONPAYCHECKBILL.D_STARTDATE, TN_CONPAYCHECKBILL.S_BOOKORGCODE, TN_CONPAYCHECKBILL.S_TRECODE, "
        + "TN_CONPAYCHECKBILL.S_BDGORGCODE, TN_CONPAYCHECKBILL.S_BDGORGNAME, TN_CONPAYCHECKBILL.S_BNKNO, TN_CONPAYCHECKBILL.S_FUNCSBTCODE, TN_CONPAYCHECKBILL.S_ECOSBTCODE, "
        + "TN_CONPAYCHECKBILL.C_AMTKIND, TN_CONPAYCHECKBILL.F_LASTMONTHZEROAMT, TN_CONPAYCHECKBILL.F_CURZEROAMT, TN_CONPAYCHECKBILL.F_CURRECKZEROAMT, TN_CONPAYCHECKBILL.F_LASTMONTHSMALLAMT, "
        + "TN_CONPAYCHECKBILL.F_CURSMALLAMT, TN_CONPAYCHECKBILL.F_CURRECKSMALLAMT, TN_CONPAYCHECKBILL.TS_SYSUPDATE "
        + "FROM TN_CONPAYCHECKBILL "
        +" WHERE " 
        + "I_ENROLSRLNO = ? FOR UPDATE"
        ;

      /* SQL to select data (SCROLLABLE)*/
     private static final String SQL_SELECT_BATCH_SCROLLABLE =
        "SELECT "
        + "  TN_CONPAYCHECKBILL.I_ENROLSRLNO  , TN_CONPAYCHECKBILL.D_ENDDATE  , TN_CONPAYCHECKBILL.D_STARTDATE  , TN_CONPAYCHECKBILL.S_BOOKORGCODE  , TN_CONPAYCHECKBILL.S_TRECODE "
        + " , TN_CONPAYCHECKBILL.S_BDGORGCODE  , TN_CONPAYCHECKBILL.S_BDGORGNAME  , TN_CONPAYCHECKBILL.S_BNKNO  , TN_CONPAYCHECKBILL.S_FUNCSBTCODE  , TN_CONPAYCHECKBILL.S_ECOSBTCODE "
        + " , TN_CONPAYCHECKBILL.C_AMTKIND  , TN_CONPAYCHECKBILL.F_LASTMONTHZEROAMT  , TN_CONPAYCHECKBILL.F_CURZEROAMT  , TN_CONPAYCHECKBILL.F_CURRECKZEROAMT  , TN_CONPAYCHECKBILL.F_LASTMONTHSMALLAMT "
        + " , TN_CONPAYCHECKBILL.F_CURSMALLAMT  , TN_CONPAYCHECKBILL.F_CURRECKSMALLAMT  , TN_CONPAYCHECKBILL.TS_SYSUPDATE "
        + "FROM TN_CONPAYCHECKBILL ";



    /* SQL to select batch data */
    private static final String SQL_SELECT_BATCH =
        "SELECT "
        + "TN_CONPAYCHECKBILL.I_ENROLSRLNO, TN_CONPAYCHECKBILL.D_ENDDATE, TN_CONPAYCHECKBILL.D_STARTDATE, TN_CONPAYCHECKBILL.S_BOOKORGCODE, TN_CONPAYCHECKBILL.S_TRECODE, "
        + "TN_CONPAYCHECKBILL.S_BDGORGCODE, TN_CONPAYCHECKBILL.S_BDGORGNAME, TN_CONPAYCHECKBILL.S_BNKNO, TN_CONPAYCHECKBILL.S_FUNCSBTCODE, TN_CONPAYCHECKBILL.S_ECOSBTCODE, "
        + "TN_CONPAYCHECKBILL.C_AMTKIND, TN_CONPAYCHECKBILL.F_LASTMONTHZEROAMT, TN_CONPAYCHECKBILL.F_CURZEROAMT, TN_CONPAYCHECKBILL.F_CURRECKZEROAMT, TN_CONPAYCHECKBILL.F_LASTMONTHSMALLAMT, "
        + "TN_CONPAYCHECKBILL.F_CURSMALLAMT, TN_CONPAYCHECKBILL.F_CURRECKSMALLAMT, TN_CONPAYCHECKBILL.TS_SYSUPDATE "
        + "FROM TN_CONPAYCHECKBILL " ;
        

   /* SQL to select batch data where condition  */
    private static final String SQL_SELECT_BATCH_WHERE =" ( "
        + "I_ENROLSRLNO = ?)"
        ;


    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE TN_CONPAYCHECKBILL SET "
        + "D_ENDDATE =?,D_STARTDATE =?,S_BOOKORGCODE =?,S_TRECODE =?,S_BDGORGCODE =?, "
        + "S_BDGORGNAME =?,S_BNKNO =?,S_FUNCSBTCODE =?,S_ECOSBTCODE =?,C_AMTKIND =?, "
        + "F_LASTMONTHZEROAMT =?,F_CURZEROAMT =?,F_CURRECKZEROAMT =?,F_LASTMONTHSMALLAMT =?,F_CURSMALLAMT =?, "
        + "F_CURRECKSMALLAMT =?,TS_SYSUPDATE =CURRENT TIMESTAMP "
        + "WHERE "
        + "I_ENROLSRLNO = ?"
        ;

	/* SQL to update data, support LOB */
    private static final String SQL_UPDATE_LOB =
        "UPDATE TN_CONPAYCHECKBILL SET "
        + "D_ENDDATE =?, D_STARTDATE =?, S_BOOKORGCODE =?, S_TRECODE =?, S_BDGORGCODE =?,  "
        + "S_BDGORGNAME =?, S_BNKNO =?, S_FUNCSBTCODE =?, S_ECOSBTCODE =?, C_AMTKIND =?,  "
        + "F_LASTMONTHZEROAMT =?, F_CURZEROAMT =?, F_CURRECKZEROAMT =?, F_LASTMONTHSMALLAMT =?, F_CURSMALLAMT =?,  "
        + "F_CURRECKSMALLAMT =?, TS_SYSUPDATE =CURRENT TIMESTAMP "
        + "WHERE "
        + "I_ENROLSRLNO = ?"
        ;	
	
    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM TN_CONPAYCHECKBILL " 
        + " WHERE "
        + "I_ENROLSRLNO = ?"
        ;


	/**
	*  批量查询 一次最多查询的参数数量
	*/
	
	public static final int FIND_BATCH_SIZE = 150  / 1;
	



   /**
   * Create a new record in Database.
   */
  public void create(IDto _dto,  Connection conn) throws SQLException
  {
     TnConpaycheckbillDto dto = (TnConpaycheckbillDto)_dto ;
     String msgValid = dto.checkValid() ;
     if (msgValid != null)
     	throw new SQLException("插入错误，"+msgValid) ;

     PreparedStatement ps = null;
     try
     {
         ps = conn.prepareStatement(SQL_INSERT);
           ps.setDate(1, dto.getDenddate());

          ps.setDate(2, dto.getDstartdate());

          ps.setString(3, dto.getSbookorgcode());

          ps.setString(4, dto.getStrecode());

          ps.setString(5, dto.getSbdgorgcode());

          ps.setString(6, dto.getSbdgorgname());

          ps.setString(7, dto.getSbnkno());

          ps.setString(8, dto.getSfuncsbtcode());

          ps.setString(9, dto.getSecosbtcode());

          ps.setString(10, dto.getCamtkind());

          ps.setBigDecimal(11, dto.getFlastmonthzeroamt());

          ps.setBigDecimal(12, dto.getFcurzeroamt());

          ps.setBigDecimal(13, dto.getFcurreckzeroamt());

          ps.setBigDecimal(14, dto.getFlastmonthsmallamt());

          ps.setBigDecimal(15, dto.getFcursmallamt());

          ps.setBigDecimal(16, dto.getFcurrecksmallamt());

          ps.executeUpdate();
     }
     finally
     {
         close(ps);
     }
     return  ;
  }

   /**
   * Create a new record in Database. and return result, only used when having generated key
   */
   public IDto createWithResult(IDto _dto,  Connection conn) throws SQLException
   {
       TnConpaycheckbillDto dto = (TnConpaycheckbillDto)_dto ;
       String msgValid = dto.checkValid() ;
       if (msgValid != null)
           throw new SQLException("插入错误，"+msgValid) ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try
       {
           ps = conn.prepareStatement(SQL_INSERT_WITH_RESULT);
             ps.setDate(1, dto.getDenddate());
            ps.setDate(2, dto.getDstartdate());
            ps.setString(3, dto.getSbookorgcode());
            ps.setString(4, dto.getStrecode());
            ps.setString(5, dto.getSbdgorgcode());
            ps.setString(6, dto.getSbdgorgname());
            ps.setString(7, dto.getSbnkno());
            ps.setString(8, dto.getSfuncsbtcode());
            ps.setString(9, dto.getSecosbtcode());
            ps.setString(10, dto.getCamtkind());
            ps.setBigDecimal(11, dto.getFlastmonthzeroamt());
            ps.setBigDecimal(12, dto.getFcurzeroamt());
            ps.setBigDecimal(13, dto.getFcurreckzeroamt());
            ps.setBigDecimal(14, dto.getFlastmonthsmallamt());
            ps.setBigDecimal(15, dto.getFcursmallamt());
            ps.setBigDecimal(16, dto.getFcurrecksmallamt());
            rs = ps.executeQuery();
           List results = getResults(rs);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }
        finally
        {
           close(ps);
           close(rs);
        }
   }

 	/**
	* Create batch new record in Database. it only create the first layer dto
	*/
    public void create(IDto[] _dtos, Connection conn)    throws SQLException
    {
        TnConpaycheckbillDto dto  ;
     	for (int i= 0; i< _dtos.length ; i++)
 	    {
 		    dto  = (TnConpaycheckbillDto)_dtos[i] ; 
    	    String msgValid = dto.checkValid() ;
        	if (msgValid != null)
     	    	throw new SQLException("插入错误，"+msgValid) ;
     	}
 	    PreparedStatement ps = null;
        try
        {
            ps = conn.prepareStatement(SQL_INSERT);
       
     	    for (int i= 0; i< _dtos.length ; i++)
     	    {
 	    	    dto  = (TnConpaycheckbillDto)_dtos[i] ; 
   
               ps.setDate(1, dto.getDenddate());
  
               ps.setDate(2, dto.getDstartdate());
  
               ps.setString(3, dto.getSbookorgcode());
  
               ps.setString(4, dto.getStrecode());
  
               ps.setString(5, dto.getSbdgorgcode());
  
               ps.setString(6, dto.getSbdgorgname());
  
               ps.setString(7, dto.getSbnkno());
  
               ps.setString(8, dto.getSfuncsbtcode());
  
               ps.setString(9, dto.getSecosbtcode());
  
               ps.setString(10, dto.getCamtkind());
  
               ps.setBigDecimal(11, dto.getFlastmonthzeroamt());
  
               ps.setBigDecimal(12, dto.getFcurzeroamt());
  
               ps.setBigDecimal(13, dto.getFcurreckzeroamt());
  
               ps.setBigDecimal(14, dto.getFlastmonthsmallamt());
  
               ps.setBigDecimal(15, dto.getFcursmallamt());
  
               ps.setBigDecimal(16, dto.getFcurrecksmallamt());
                ps.addBatch(); 
           }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }
        return  ;
   }




     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto find(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TnConpaycheckbillPK pk = (TnConpaycheckbillPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT);
           if (pk.getIenrolsrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIenrolsrlno().longValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }

     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto findForUpdate(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TnConpaycheckbillPK pk = (TnConpaycheckbillPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT_FOR_UPDATE);
           if (pk.getIenrolsrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIenrolsrlno().longValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }
  
     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto[] find(IPK[] _pks, Connection conn, boolean isLobSupport) throws SQLException
    {
        TnConpaycheckbillPK pk ;
        
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TnConpaycheckbillPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 
        PreparedStatement ps = null;
        ResultSet rs = null;
        
         
        List results = new ArrayList();  
		for (int iBegin = 0; iBegin < pks.size(); iBegin += FIND_BATCH_SIZE)   //
		{
        
            try {
          		int iFindBatchSize = pks.size() - iBegin ;
	    		if (iFindBatchSize >FIND_BATCH_SIZE )
		    		iFindBatchSize = FIND_BATCH_SIZE ;
		  
        	    StringBuffer sb = new StringBuffer() ;
            	sb.append(SQL_SELECT_BATCH).append(" WHERE ").append(SQL_SELECT_BATCH_WHERE);

	    		for (int i = iBegin+1; i < iBegin + iFindBatchSize; i++)
		    	{
			    	sb.append("OR").append(SQL_SELECT_BATCH_WHERE) ;
    			}
        	
                ps = conn.prepareStatement(sb.toString());

                for (int i = iBegin;i < iBegin + iFindBatchSize; i++)
                {
                    pk  = (TnConpaycheckbillPK)(pks.get(i)) ; 
                   if (pk.getIenrolsrlno()==null)
                      ps.setNull((i-iBegin)*1+1, java.sql.Types.BIGINT);
                   else
                      ps.setLong((i-iBegin)*1+1, pk.getIenrolsrlno().longValue());

			
	            }
                rs = ps.executeQuery();
                results.addAll(getResults(rs,0,isLobSupport)); //
            }finally {
                close(rs);
                close(ps);
            }
        }
        if (results!=null && results.size() > 0)
        {
            TnConpaycheckbillDto[] dtos = new TnConpaycheckbillDto[0];
		    dtos = (TnConpaycheckbillDto[]) results.toArray(dtos) ;
		    return dtos ;
        }
        else
        {
            return null;
        }
    }

  
  
  



    /**
	    * 得到查询语句
	    */
    public String getSelectSQL() 
    {
	        return SQL_SELECT_BATCH_SCROLLABLE ;
    }
   

	public List getResults(ResultSet rs) throws SQLException
    {
    	return getResults(rs, 0) ;
    }
  

    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize) throws SQLException
    {
		return getResults(rs,maxSize,false);
	}
    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize, boolean isLobSupport) throws SQLException
    {
        List results = new ArrayList();
        String str ;
        Reader reader;
        Clob clob;
        char[] chars ;
        
        while (rs.next())
         {
             TnConpaycheckbillDto  dto = new  TnConpaycheckbillDto ();
             //I_ENROLSRLNO
             str = rs.getString("I_ENROLSRLNO");
             if(str!=null){
                dto.setIenrolsrlno(new Long(str));
             }

             //D_ENDDATE
           dto.setDenddate(rs.getDate("D_ENDDATE"));

             //D_STARTDATE
           dto.setDstartdate(rs.getDate("D_STARTDATE"));

             //S_BOOKORGCODE
             str = rs.getString("S_BOOKORGCODE");
             if (str == null)
                dto.setSbookorgcode(null);
             else
                dto.setSbookorgcode(str.trim());

             //S_TRECODE
             str = rs.getString("S_TRECODE");
             if (str == null)
                dto.setStrecode(null);
             else
                dto.setStrecode(str.trim());

             //S_BDGORGCODE
             str = rs.getString("S_BDGORGCODE");
             if (str == null)
                dto.setSbdgorgcode(null);
             else
                dto.setSbdgorgcode(str.trim());

             //S_BDGORGNAME
             str = rs.getString("S_BDGORGNAME");
             if (str == null)
                dto.setSbdgorgname(null);
             else
                dto.setSbdgorgname(str.trim());

             //S_BNKNO
             str = rs.getString("S_BNKNO");
             if (str == null)
                dto.setSbnkno(null);
             else
                dto.setSbnkno(str.trim());

             //S_FUNCSBTCODE
             str = rs.getString("S_FUNCSBTCODE");
             if (str == null)
                dto.setSfuncsbtcode(null);
             else
                dto.setSfuncsbtcode(str.trim());

             //S_ECOSBTCODE
             str = rs.getString("S_ECOSBTCODE");
             if (str == null)
                dto.setSecosbtcode(null);
             else
                dto.setSecosbtcode(str.trim());

             //C_AMTKIND
             str = rs.getString("C_AMTKIND");
             if (str == null)
                dto.setCamtkind(null);
             else
                dto.setCamtkind(str.trim());

             //F_LASTMONTHZEROAMT
           dto.setFlastmonthzeroamt(rs.getBigDecimal("F_LASTMONTHZEROAMT"));

             //F_CURZEROAMT
           dto.setFcurzeroamt(rs.getBigDecimal("F_CURZEROAMT"));

             //F_CURRECKZEROAMT
           dto.setFcurreckzeroamt(rs.getBigDecimal("F_CURRECKZEROAMT"));

             //F_LASTMONTHSMALLAMT
           dto.setFlastmonthsmallamt(rs.getBigDecimal("F_LASTMONTHSMALLAMT"));

             //F_CURSMALLAMT
           dto.setFcursmallamt(rs.getBigDecimal("F_CURSMALLAMT"));

             //F_CURRECKSMALLAMT
           dto.setFcurrecksmallamt(rs.getBigDecimal("F_CURRECKSMALLAMT"));

             //TS_SYSUPDATE
           dto.setTssysupdate(rs.getTimestamp("TS_SYSUPDATE"));



            results.add(dto);
            
            if(maxSize >0  && results.size() == maxSize)
            {
            	break ;
            }
            
         }
        
		return results ;
    }

  /**
   * populate resultSet as cclass
   */
  protected IDto[] getChildrenResults(ResultSet rs ,Class _dto) throws SQLException{

      throw new SQLException("本dto没有与其它dto相关联，无法应用此方法");
  }


     /**
     * Update a record in Database.
     */

    public void update(IDto _dto, Connection conn, boolean isLobSupport) throws SQLException
    {
        String msgValid = _dto.checkValid() ;
        if (msgValid != null)
            throw new SQLException("修改错误，"+msgValid) ;
        TnConpaycheckbillDto dto = (TnConpaycheckbillDto)_dto ;
        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            int pos = 1;
            //D_ENDDATE
            ps.setDate(pos, dto.getDenddate());
            pos++;

            //D_STARTDATE
            ps.setDate(pos, dto.getDstartdate());
            pos++;

            //S_BOOKORGCODE
            ps.setString(pos, dto.getSbookorgcode());
            pos++;

            //S_TRECODE
            ps.setString(pos, dto.getStrecode());
            pos++;

            //S_BDGORGCODE
            ps.setString(pos, dto.getSbdgorgcode());
            pos++;

            //S_BDGORGNAME
            ps.setString(pos, dto.getSbdgorgname());
            pos++;

            //S_BNKNO
            ps.setString(pos, dto.getSbnkno());
            pos++;

            //S_FUNCSBTCODE
            ps.setString(pos, dto.getSfuncsbtcode());
            pos++;

            //S_ECOSBTCODE
            ps.setString(pos, dto.getSecosbtcode());
            pos++;

            //C_AMTKIND
            ps.setString(pos, dto.getCamtkind());
            pos++;

            //F_LASTMONTHZEROAMT
            ps.setBigDecimal(pos, dto.getFlastmonthzeroamt());
            pos++;

            //F_CURZEROAMT
            ps.setBigDecimal(pos, dto.getFcurzeroamt());
            pos++;

            //F_CURRECKZEROAMT
            ps.setBigDecimal(pos, dto.getFcurreckzeroamt());
            pos++;

            //F_LASTMONTHSMALLAMT
            ps.setBigDecimal(pos, dto.getFlastmonthsmallamt());
            pos++;

            //F_CURSMALLAMT
            ps.setBigDecimal(pos, dto.getFcursmallamt());
            pos++;

            //F_CURRECKSMALLAMT
            ps.setBigDecimal(pos, dto.getFcurrecksmallamt());
            pos++;

            //TS_SYSUPDATE

           //I_ENROLSRLNO
           ps.setLong(pos, dto.getIenrolsrlno().longValue());
           pos++;
           ps.executeUpdate();
        }
        finally
        {
           close(ps);
        }

        return ;
    }
    
    
    
      /**
     * Update batch record in Database.
     */

    public void update(IDto[] _dtos, Connection conn, boolean isLobSupport) throws SQLException
    {
     
     	 TnConpaycheckbillDto dto  ;
         for (int i= 0; i< _dtos.length ; i++)
         {
            dto  = (TnConpaycheckbillDto)_dtos[i] ; 
            String msgValid = dto.checkValid() ;
            if (msgValid != null)
                throw new SQLException("修改错误，"+msgValid) ;
         }

        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            
            for (int i= 0; i< _dtos.length ; i++)
            {
                dto  = (TnConpaycheckbillDto)_dtos[i] ; 
                int pos = 1;
                //D_ENDDATE
                 ps.setDate(pos, dto.getDenddate());
                pos++;

                //D_STARTDATE
                 ps.setDate(pos, dto.getDstartdate());
                pos++;

                //S_BOOKORGCODE
                 ps.setString(pos, dto.getSbookorgcode());
                pos++;

                //S_TRECODE
                 ps.setString(pos, dto.getStrecode());
                pos++;

                //S_BDGORGCODE
                 ps.setString(pos, dto.getSbdgorgcode());
                pos++;

                //S_BDGORGNAME
                 ps.setString(pos, dto.getSbdgorgname());
                pos++;

                //S_BNKNO
                 ps.setString(pos, dto.getSbnkno());
                pos++;

                //S_FUNCSBTCODE
                 ps.setString(pos, dto.getSfuncsbtcode());
                pos++;

                //S_ECOSBTCODE
                 ps.setString(pos, dto.getSecosbtcode());
                pos++;

                //C_AMTKIND
                 ps.setString(pos, dto.getCamtkind());
                pos++;

                //F_LASTMONTHZEROAMT
                 ps.setBigDecimal(pos, dto.getFlastmonthzeroamt());
                pos++;

                //F_CURZEROAMT
                 ps.setBigDecimal(pos, dto.getFcurzeroamt());
                pos++;

                //F_CURRECKZEROAMT
                 ps.setBigDecimal(pos, dto.getFcurreckzeroamt());
                pos++;

                //F_LASTMONTHSMALLAMT
                 ps.setBigDecimal(pos, dto.getFlastmonthsmallamt());
                pos++;

                //F_CURSMALLAMT
                 ps.setBigDecimal(pos, dto.getFcursmallamt());
                pos++;

                //F_CURRECKSMALLAMT
                 ps.setBigDecimal(pos, dto.getFcurrecksmallamt());
                pos++;

                //TS_SYSUPDATE
 
               //I_ENROLSRLNO
               ps.setLong(pos, dto.getIenrolsrlno().longValue());
               pos++;
		       ps.addBatch(); 
	       }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }

        return ;
    }



    /**
     * delete a record in Database.
     */
    public void delete(IPK _pk, Connection conn) throws SQLException
    {
       
      
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return ;
        //	throw new SQLException("删除错误，"+msgValid) ;
       }
       TnConpaycheckbillPK pk = (TnConpaycheckbillPK)_pk ;


       PreparedStatement ps = null;
       try {
           ps = conn.prepareStatement(SQL_DELETE);
           ps.setLong(1, pk.getIenrolsrlno().longValue());
           ps.executeUpdate();
        }
        finally
        {
            close(ps);
        }
    }


     /**
     * delete batch record in Database.
     */
    public void delete(IPK[] _pks, Connection conn) throws SQLException
    {
        TnConpaycheckbillPK pk ;
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TnConpaycheckbillPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 		
 		
        PreparedStatement ps = null;
        try
         {
            ps = conn.prepareStatement(SQL_DELETE);
             
       		for (int i= 0; i< pks.size() ; i++)
       		{
       			pk  = (TnConpaycheckbillPK)(pks.get(i)) ; 
                ps.setLong(1, pk.getIenrolsrlno().longValue());
		        ps.addBatch() ;
			}
            ps.executeBatch();
        }
        finally
        {
            close(ps);
        }      
    }



    /**
    * Check IChangerNumber or UpdateTimeStamp.
    */
    public void check(IDto _dto, Connection conn) throws SQLException
    {
                                                   		throw new SQLException("数据库表：TN_CONPAYCHECKBILL没有检查修改的字段");
    }


	/**
	* synchronize values between parent and children
	*/
    public void syncToChildren(IDto _dto)     throws SQLException{
       throw new SQLException("本记录没有与其它记录相关联，无法进行主记录与明细记录之间的数据同步。");
  }

	/**
	*get children
	*/
    public IDto[] findChildren (IDto _dto, Connection conn, boolean isLobSupport)     throws SQLException{
         throw new SQLException("本dto没有与其它dto相关联，无法得到子dto");
  }    
    
  /**
   *return the children IDto class
   * @return Class
   */
  public Class getChildrenClass(){
	  return null;
  };    



    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt)
    {
        if (stmt != null)
        {
            try
            {
                stmt.close();
            }
            catch(SQLException    e)
            {}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs)
    {
        if (rs != null)
        {
            try
            {
                rs.close();
            }catch(SQLException  e){}
        }
    }
}
