    



package com.cfcc.itfe.persistence.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;
import java.sql.Clob;

import com.cfcc.jaf.persistence.jaform.parent.* ;

import java.math.BigDecimal;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

import java.io.StringReader;
import java.io.Reader;
import java.io.IOException;

import com.cfcc.itfe.persistence.dto.TvPayreckbankSxDto ;
import com.cfcc.itfe.persistence.pk.TvPayreckbankSxPK ;


/**
 * <p>Title: DAO of table: TV_PAYRECKBANK_SX</p>
 * <p>Description: Data Access Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:03 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dao.vm timestamp: 2007-04-06 08:30:00
 ******************************************************
 * <p> <b>change record</b><br>
 *  make dao methods simply.<br>
 *  especially make update,delete methods simply.<br>
 *  remove "..withCheck" method,withCheck will impl in JAFOrmTemplate.<br>
 *  remove "delete(IDto _dto,..)" method.<br></p>
 * @author win7
 */

public class TvPayreckbankSxDao  implements IDao
{


    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO TV_PAYRECKBANK_SX ("
          + "S_BOOKORGCODE,D_ENTRUSTDATE,S_PACKNO,S_AGENTBNKCODE,S_TRANO"
          + ",I_VOUSRLNO,S_FINORGCODE,S_TRECODE,S_VOUNO,D_VOUDATE"
          + ",S_PAYERACCT,S_PAYERNAME,S_PAYERADDR,S_PAYEEACCT,S_PAYEENAME"
          + ",S_PAYEEADDR,S_PAYEEOPBKNO,S_ADDWORD,S_BUDGETTYPE,S_TRIMSIGN"
          + ",S_OFYEAR,F_AMT,I_STATINFNUM,D_ACCTDATE,S_RESULT"
          + ",S_DESCRIPTION,S_PROCSTAT,D_ACCEPTDATE,TS_UPDATE,S_PAYMODE"
          + ",S_FILENAME,S_ID,S_BGTTYPECODE,S_BGTTYPENAME,S_FUNDTYPECODE"
          + ",S_FUNDTYPENAME,S_PAYTYPECODE,S_PAYTYPENAME,S_PAYBANKNAME,S_XPAYSNDBNKNO"
          + ",S_XPAYAMT,S_HOLD1,S_HOLD2,S_XCLEARDATE,S_AGENTACCTBANKNAME"
          + ",S_CLEARACCTBANKNAME,S_MONEYCORPCODE,S_ADMDIVCODE,S_VTCODE"
        + ") VALUES ("
        + "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";


    private static final String SQL_INSERT_WITH_RESULT = "SELECT * FROM FINAL TABLE( " + SQL_INSERT + " )";
    
    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "TV_PAYRECKBANK_SX.S_BOOKORGCODE, TV_PAYRECKBANK_SX.D_ENTRUSTDATE, TV_PAYRECKBANK_SX.S_PACKNO, TV_PAYRECKBANK_SX.S_AGENTBNKCODE, TV_PAYRECKBANK_SX.S_TRANO, "
        + "TV_PAYRECKBANK_SX.I_VOUSRLNO, TV_PAYRECKBANK_SX.S_FINORGCODE, TV_PAYRECKBANK_SX.S_TRECODE, TV_PAYRECKBANK_SX.S_VOUNO, TV_PAYRECKBANK_SX.D_VOUDATE, "
        + "TV_PAYRECKBANK_SX.S_PAYERACCT, TV_PAYRECKBANK_SX.S_PAYERNAME, TV_PAYRECKBANK_SX.S_PAYERADDR, TV_PAYRECKBANK_SX.S_PAYEEACCT, TV_PAYRECKBANK_SX.S_PAYEENAME, "
        + "TV_PAYRECKBANK_SX.S_PAYEEADDR, TV_PAYRECKBANK_SX.S_PAYEEOPBKNO, TV_PAYRECKBANK_SX.S_ADDWORD, TV_PAYRECKBANK_SX.S_BUDGETTYPE, TV_PAYRECKBANK_SX.S_TRIMSIGN, "
        + "TV_PAYRECKBANK_SX.S_OFYEAR, TV_PAYRECKBANK_SX.F_AMT, TV_PAYRECKBANK_SX.I_STATINFNUM, TV_PAYRECKBANK_SX.D_ACCTDATE, TV_PAYRECKBANK_SX.S_RESULT, "
        + "TV_PAYRECKBANK_SX.S_DESCRIPTION, TV_PAYRECKBANK_SX.S_PROCSTAT, TV_PAYRECKBANK_SX.D_ACCEPTDATE, TV_PAYRECKBANK_SX.TS_UPDATE, TV_PAYRECKBANK_SX.S_PAYMODE, "
        + "TV_PAYRECKBANK_SX.S_FILENAME, TV_PAYRECKBANK_SX.S_ID, TV_PAYRECKBANK_SX.S_BGTTYPECODE, TV_PAYRECKBANK_SX.S_BGTTYPENAME, TV_PAYRECKBANK_SX.S_FUNDTYPECODE, "
        + "TV_PAYRECKBANK_SX.S_FUNDTYPENAME, TV_PAYRECKBANK_SX.S_PAYTYPECODE, TV_PAYRECKBANK_SX.S_PAYTYPENAME, TV_PAYRECKBANK_SX.S_PAYBANKNAME, TV_PAYRECKBANK_SX.S_XPAYSNDBNKNO, "
        + "TV_PAYRECKBANK_SX.S_XPAYAMT, TV_PAYRECKBANK_SX.S_HOLD1, TV_PAYRECKBANK_SX.S_HOLD2, TV_PAYRECKBANK_SX.S_XCLEARDATE, TV_PAYRECKBANK_SX.S_AGENTACCTBANKNAME, "
        + "TV_PAYRECKBANK_SX.S_CLEARACCTBANKNAME, TV_PAYRECKBANK_SX.S_MONEYCORPCODE, TV_PAYRECKBANK_SX.S_ADMDIVCODE, TV_PAYRECKBANK_SX.S_VTCODE "
        + "FROM TV_PAYRECKBANK_SX "
        +" WHERE " 
        + "S_BOOKORGCODE = ? AND D_ENTRUSTDATE = ? AND S_PACKNO = ? AND S_AGENTBNKCODE = ? AND S_TRANO = ?"
        ;
    /* SQL to select for update data */
    private static final String SQL_SELECT_FOR_UPDATE =
        "SELECT "
        + "TV_PAYRECKBANK_SX.S_BOOKORGCODE, TV_PAYRECKBANK_SX.D_ENTRUSTDATE, TV_PAYRECKBANK_SX.S_PACKNO, TV_PAYRECKBANK_SX.S_AGENTBNKCODE, TV_PAYRECKBANK_SX.S_TRANO, "
        + "TV_PAYRECKBANK_SX.I_VOUSRLNO, TV_PAYRECKBANK_SX.S_FINORGCODE, TV_PAYRECKBANK_SX.S_TRECODE, TV_PAYRECKBANK_SX.S_VOUNO, TV_PAYRECKBANK_SX.D_VOUDATE, "
        + "TV_PAYRECKBANK_SX.S_PAYERACCT, TV_PAYRECKBANK_SX.S_PAYERNAME, TV_PAYRECKBANK_SX.S_PAYERADDR, TV_PAYRECKBANK_SX.S_PAYEEACCT, TV_PAYRECKBANK_SX.S_PAYEENAME, "
        + "TV_PAYRECKBANK_SX.S_PAYEEADDR, TV_PAYRECKBANK_SX.S_PAYEEOPBKNO, TV_PAYRECKBANK_SX.S_ADDWORD, TV_PAYRECKBANK_SX.S_BUDGETTYPE, TV_PAYRECKBANK_SX.S_TRIMSIGN, "
        + "TV_PAYRECKBANK_SX.S_OFYEAR, TV_PAYRECKBANK_SX.F_AMT, TV_PAYRECKBANK_SX.I_STATINFNUM, TV_PAYRECKBANK_SX.D_ACCTDATE, TV_PAYRECKBANK_SX.S_RESULT, "
        + "TV_PAYRECKBANK_SX.S_DESCRIPTION, TV_PAYRECKBANK_SX.S_PROCSTAT, TV_PAYRECKBANK_SX.D_ACCEPTDATE, TV_PAYRECKBANK_SX.TS_UPDATE, TV_PAYRECKBANK_SX.S_PAYMODE, "
        + "TV_PAYRECKBANK_SX.S_FILENAME, TV_PAYRECKBANK_SX.S_ID, TV_PAYRECKBANK_SX.S_BGTTYPECODE, TV_PAYRECKBANK_SX.S_BGTTYPENAME, TV_PAYRECKBANK_SX.S_FUNDTYPECODE, "
        + "TV_PAYRECKBANK_SX.S_FUNDTYPENAME, TV_PAYRECKBANK_SX.S_PAYTYPECODE, TV_PAYRECKBANK_SX.S_PAYTYPENAME, TV_PAYRECKBANK_SX.S_PAYBANKNAME, TV_PAYRECKBANK_SX.S_XPAYSNDBNKNO, "
        + "TV_PAYRECKBANK_SX.S_XPAYAMT, TV_PAYRECKBANK_SX.S_HOLD1, TV_PAYRECKBANK_SX.S_HOLD2, TV_PAYRECKBANK_SX.S_XCLEARDATE, TV_PAYRECKBANK_SX.S_AGENTACCTBANKNAME, "
        + "TV_PAYRECKBANK_SX.S_CLEARACCTBANKNAME, TV_PAYRECKBANK_SX.S_MONEYCORPCODE, TV_PAYRECKBANK_SX.S_ADMDIVCODE, TV_PAYRECKBANK_SX.S_VTCODE "
        + "FROM TV_PAYRECKBANK_SX "
        +" WHERE " 
        + "S_BOOKORGCODE = ? AND D_ENTRUSTDATE = ? AND S_PACKNO = ? AND S_AGENTBNKCODE = ? AND S_TRANO = ? FOR UPDATE"
        ;

      /* SQL to select data (SCROLLABLE)*/
     private static final String SQL_SELECT_BATCH_SCROLLABLE =
        "SELECT "
        + "  TV_PAYRECKBANK_SX.S_BOOKORGCODE  , TV_PAYRECKBANK_SX.D_ENTRUSTDATE  , TV_PAYRECKBANK_SX.S_PACKNO  , TV_PAYRECKBANK_SX.S_AGENTBNKCODE  , TV_PAYRECKBANK_SX.S_TRANO "
        + " , TV_PAYRECKBANK_SX.I_VOUSRLNO  , TV_PAYRECKBANK_SX.S_FINORGCODE  , TV_PAYRECKBANK_SX.S_TRECODE  , TV_PAYRECKBANK_SX.S_VOUNO  , TV_PAYRECKBANK_SX.D_VOUDATE "
        + " , TV_PAYRECKBANK_SX.S_PAYERACCT  , TV_PAYRECKBANK_SX.S_PAYERNAME  , TV_PAYRECKBANK_SX.S_PAYERADDR  , TV_PAYRECKBANK_SX.S_PAYEEACCT  , TV_PAYRECKBANK_SX.S_PAYEENAME "
        + " , TV_PAYRECKBANK_SX.S_PAYEEADDR  , TV_PAYRECKBANK_SX.S_PAYEEOPBKNO  , TV_PAYRECKBANK_SX.S_ADDWORD  , TV_PAYRECKBANK_SX.S_BUDGETTYPE  , TV_PAYRECKBANK_SX.S_TRIMSIGN "
        + " , TV_PAYRECKBANK_SX.S_OFYEAR  , TV_PAYRECKBANK_SX.F_AMT  , TV_PAYRECKBANK_SX.I_STATINFNUM  , TV_PAYRECKBANK_SX.D_ACCTDATE  , TV_PAYRECKBANK_SX.S_RESULT "
        + " , TV_PAYRECKBANK_SX.S_DESCRIPTION  , TV_PAYRECKBANK_SX.S_PROCSTAT  , TV_PAYRECKBANK_SX.D_ACCEPTDATE  , TV_PAYRECKBANK_SX.TS_UPDATE  , TV_PAYRECKBANK_SX.S_PAYMODE "
        + " , TV_PAYRECKBANK_SX.S_FILENAME  , TV_PAYRECKBANK_SX.S_ID  , TV_PAYRECKBANK_SX.S_BGTTYPECODE  , TV_PAYRECKBANK_SX.S_BGTTYPENAME  , TV_PAYRECKBANK_SX.S_FUNDTYPECODE "
        + " , TV_PAYRECKBANK_SX.S_FUNDTYPENAME  , TV_PAYRECKBANK_SX.S_PAYTYPECODE  , TV_PAYRECKBANK_SX.S_PAYTYPENAME  , TV_PAYRECKBANK_SX.S_PAYBANKNAME  , TV_PAYRECKBANK_SX.S_XPAYSNDBNKNO "
        + " , TV_PAYRECKBANK_SX.S_XPAYAMT  , TV_PAYRECKBANK_SX.S_HOLD1  , TV_PAYRECKBANK_SX.S_HOLD2  , TV_PAYRECKBANK_SX.S_XCLEARDATE  , TV_PAYRECKBANK_SX.S_AGENTACCTBANKNAME "
        + " , TV_PAYRECKBANK_SX.S_CLEARACCTBANKNAME  , TV_PAYRECKBANK_SX.S_MONEYCORPCODE  , TV_PAYRECKBANK_SX.S_ADMDIVCODE  , TV_PAYRECKBANK_SX.S_VTCODE "
        + "FROM TV_PAYRECKBANK_SX ";



    /* SQL to select batch data */
    private static final String SQL_SELECT_BATCH =
        "SELECT "
        + "TV_PAYRECKBANK_SX.S_BOOKORGCODE, TV_PAYRECKBANK_SX.D_ENTRUSTDATE, TV_PAYRECKBANK_SX.S_PACKNO, TV_PAYRECKBANK_SX.S_AGENTBNKCODE, TV_PAYRECKBANK_SX.S_TRANO, "
        + "TV_PAYRECKBANK_SX.I_VOUSRLNO, TV_PAYRECKBANK_SX.S_FINORGCODE, TV_PAYRECKBANK_SX.S_TRECODE, TV_PAYRECKBANK_SX.S_VOUNO, TV_PAYRECKBANK_SX.D_VOUDATE, "
        + "TV_PAYRECKBANK_SX.S_PAYERACCT, TV_PAYRECKBANK_SX.S_PAYERNAME, TV_PAYRECKBANK_SX.S_PAYERADDR, TV_PAYRECKBANK_SX.S_PAYEEACCT, TV_PAYRECKBANK_SX.S_PAYEENAME, "
        + "TV_PAYRECKBANK_SX.S_PAYEEADDR, TV_PAYRECKBANK_SX.S_PAYEEOPBKNO, TV_PAYRECKBANK_SX.S_ADDWORD, TV_PAYRECKBANK_SX.S_BUDGETTYPE, TV_PAYRECKBANK_SX.S_TRIMSIGN, "
        + "TV_PAYRECKBANK_SX.S_OFYEAR, TV_PAYRECKBANK_SX.F_AMT, TV_PAYRECKBANK_SX.I_STATINFNUM, TV_PAYRECKBANK_SX.D_ACCTDATE, TV_PAYRECKBANK_SX.S_RESULT, "
        + "TV_PAYRECKBANK_SX.S_DESCRIPTION, TV_PAYRECKBANK_SX.S_PROCSTAT, TV_PAYRECKBANK_SX.D_ACCEPTDATE, TV_PAYRECKBANK_SX.TS_UPDATE, TV_PAYRECKBANK_SX.S_PAYMODE, "
        + "TV_PAYRECKBANK_SX.S_FILENAME, TV_PAYRECKBANK_SX.S_ID, TV_PAYRECKBANK_SX.S_BGTTYPECODE, TV_PAYRECKBANK_SX.S_BGTTYPENAME, TV_PAYRECKBANK_SX.S_FUNDTYPECODE, "
        + "TV_PAYRECKBANK_SX.S_FUNDTYPENAME, TV_PAYRECKBANK_SX.S_PAYTYPECODE, TV_PAYRECKBANK_SX.S_PAYTYPENAME, TV_PAYRECKBANK_SX.S_PAYBANKNAME, TV_PAYRECKBANK_SX.S_XPAYSNDBNKNO, "
        + "TV_PAYRECKBANK_SX.S_XPAYAMT, TV_PAYRECKBANK_SX.S_HOLD1, TV_PAYRECKBANK_SX.S_HOLD2, TV_PAYRECKBANK_SX.S_XCLEARDATE, TV_PAYRECKBANK_SX.S_AGENTACCTBANKNAME, "
        + "TV_PAYRECKBANK_SX.S_CLEARACCTBANKNAME, TV_PAYRECKBANK_SX.S_MONEYCORPCODE, TV_PAYRECKBANK_SX.S_ADMDIVCODE, TV_PAYRECKBANK_SX.S_VTCODE "
        + "FROM TV_PAYRECKBANK_SX " ;
        

   /* SQL to select batch data where condition  */
    private static final String SQL_SELECT_BATCH_WHERE =" ( "
        + "S_BOOKORGCODE = ? AND D_ENTRUSTDATE = ? AND S_PACKNO = ? AND S_AGENTBNKCODE = ? AND S_TRANO = ?)"
        ;


    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE TV_PAYRECKBANK_SX SET "
        + "I_VOUSRLNO =?,S_FINORGCODE =?,S_TRECODE =?,S_VOUNO =?,D_VOUDATE =?, "
        + "S_PAYERACCT =?,S_PAYERNAME =?,S_PAYERADDR =?,S_PAYEEACCT =?,S_PAYEENAME =?, "
        + "S_PAYEEADDR =?,S_PAYEEOPBKNO =?,S_ADDWORD =?,S_BUDGETTYPE =?,S_TRIMSIGN =?, "
        + "S_OFYEAR =?,F_AMT =?,I_STATINFNUM =?,D_ACCTDATE =?,S_RESULT =?, "
        + "S_DESCRIPTION =?,S_PROCSTAT =?,D_ACCEPTDATE =?,TS_UPDATE =?,S_PAYMODE =?, "
        + "S_FILENAME =?,S_ID =?,S_BGTTYPECODE =?,S_BGTTYPENAME =?,S_FUNDTYPECODE =?, "
        + "S_FUNDTYPENAME =?,S_PAYTYPECODE =?,S_PAYTYPENAME =?,S_PAYBANKNAME =?,S_XPAYSNDBNKNO =?, "
        + "S_XPAYAMT =?,S_HOLD1 =?,S_HOLD2 =?,S_XCLEARDATE =?,S_AGENTACCTBANKNAME =?, "
        + "S_CLEARACCTBANKNAME =?,S_MONEYCORPCODE =?,S_ADMDIVCODE =?,S_VTCODE =? "
        + "WHERE "
        + "S_BOOKORGCODE = ? AND D_ENTRUSTDATE = ? AND S_PACKNO = ? AND S_AGENTBNKCODE = ? AND S_TRANO = ?"
        ;

	/* SQL to update data, support LOB */
    private static final String SQL_UPDATE_LOB =
        "UPDATE TV_PAYRECKBANK_SX SET "
        + "I_VOUSRLNO =?, S_FINORGCODE =?, S_TRECODE =?, S_VOUNO =?, D_VOUDATE =?,  "
        + "S_PAYERACCT =?, S_PAYERNAME =?, S_PAYERADDR =?, S_PAYEEACCT =?, S_PAYEENAME =?,  "
        + "S_PAYEEADDR =?, S_PAYEEOPBKNO =?, S_ADDWORD =?, S_BUDGETTYPE =?, S_TRIMSIGN =?,  "
        + "S_OFYEAR =?, F_AMT =?, I_STATINFNUM =?, D_ACCTDATE =?, S_RESULT =?,  "
        + "S_DESCRIPTION =?, S_PROCSTAT =?, D_ACCEPTDATE =?, TS_UPDATE =?, S_PAYMODE =?,  "
        + "S_FILENAME =?, S_ID =?, S_BGTTYPECODE =?, S_BGTTYPENAME =?, S_FUNDTYPECODE =?,  "
        + "S_FUNDTYPENAME =?, S_PAYTYPECODE =?, S_PAYTYPENAME =?, S_PAYBANKNAME =?, S_XPAYSNDBNKNO =?,  "
        + "S_XPAYAMT =?, S_HOLD1 =?, S_HOLD2 =?, S_XCLEARDATE =?, S_AGENTACCTBANKNAME =?,  "
        + "S_CLEARACCTBANKNAME =?, S_MONEYCORPCODE =?, S_ADMDIVCODE =?, S_VTCODE =? "
        + "WHERE "
        + "S_BOOKORGCODE = ? AND D_ENTRUSTDATE = ? AND S_PACKNO = ? AND S_AGENTBNKCODE = ? AND S_TRANO = ?"
        ;	
	
    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM TV_PAYRECKBANK_SX " 
        + " WHERE "
        + "S_BOOKORGCODE = ? AND D_ENTRUSTDATE = ? AND S_PACKNO = ? AND S_AGENTBNKCODE = ? AND S_TRANO = ?"
        ;


	/**
	*  批量查询 一次最多查询的参数数量
	*/
	
	public static final int FIND_BATCH_SIZE = 150  / 5;
	



   /**
   * Create a new record in Database.
   */
  public void create(IDto _dto,  Connection conn) throws SQLException
  {
     TvPayreckbankSxDto dto = (TvPayreckbankSxDto)_dto ;
     String msgValid = dto.checkValid() ;
     if (msgValid != null)
     	throw new SQLException("插入错误，"+msgValid) ;

     PreparedStatement ps = null;
     try
     {
         ps = conn.prepareStatement(SQL_INSERT);
          ps.setString(1, dto.getSbookorgcode());

          ps.setDate(2, dto.getDentrustdate());

          ps.setString(3, dto.getSpackno());

          ps.setString(4, dto.getSagentbnkcode());

          ps.setString(5, dto.getStrano());

          if (dto.getIvousrlno()==null)
            ps.setNull(6, java.sql.Types.BIGINT);
         else
            ps.setLong(6, dto.getIvousrlno().longValue());
          ps.setString(7, dto.getSfinorgcode());

          ps.setString(8, dto.getStrecode());

          ps.setString(9, dto.getSvouno());

          ps.setDate(10, dto.getDvoudate());

          ps.setString(11, dto.getSpayeracct());

          ps.setString(12, dto.getSpayername());

          ps.setString(13, dto.getSpayeraddr());

          ps.setString(14, dto.getSpayeeacct());

          ps.setString(15, dto.getSpayeename());

          ps.setString(16, dto.getSpayeeaddr());

          ps.setString(17, dto.getSpayeeopbkno());

          ps.setString(18, dto.getSaddword());

          ps.setString(19, dto.getSbudgettype());

          ps.setString(20, dto.getStrimsign());

          ps.setString(21, dto.getSofyear());

          ps.setBigDecimal(22, dto.getFamt());

          if (dto.getIstatinfnum()==null)
            ps.setNull(23, java.sql.Types.INTEGER);
         else
            ps.setInt(23, dto.getIstatinfnum().intValue());
          ps.setDate(24, dto.getDacctdate());

          ps.setString(25, dto.getSresult());

          ps.setString(26, dto.getSdescription());

          ps.setString(27, dto.getSprocstat());

          ps.setDate(28, dto.getDacceptdate());

          ps.setTimestamp(29, dto.getTsupdate());

          ps.setString(30, dto.getSpaymode());

          ps.setString(31, dto.getSfilename());

          ps.setString(32, dto.getSid());

          ps.setString(33, dto.getSbgttypecode());

          ps.setString(34, dto.getSbgttypename());

          ps.setString(35, dto.getSfundtypecode());

          ps.setString(36, dto.getSfundtypename());

          ps.setString(37, dto.getSpaytypecode());

          ps.setString(38, dto.getSpaytypename());

          ps.setString(39, dto.getSpaybankname());

          ps.setString(40, dto.getSxpaysndbnkno());

          ps.setBigDecimal(41, dto.getSxpayamt());

          ps.setString(42, dto.getShold1());

          ps.setString(43, dto.getShold2());

          ps.setDate(44, dto.getSxcleardate());

          ps.setString(45, dto.getSagentacctbankname());

          ps.setString(46, dto.getSclearacctbankname());

          ps.setString(47, dto.getSmoneycorpcode());

          ps.setString(48, dto.getSadmdivcode());

          ps.setString(49, dto.getSvtcode());

         ps.executeUpdate();
     }
     finally
     {
         close(ps);
     }
     return  ;
  }

   /**
   * Create a new record in Database. and return result, only used when having generated key
   */
   public IDto createWithResult(IDto _dto,  Connection conn) throws SQLException
   {
       TvPayreckbankSxDto dto = (TvPayreckbankSxDto)_dto ;
       String msgValid = dto.checkValid() ;
       if (msgValid != null)
           throw new SQLException("插入错误，"+msgValid) ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try
       {
           ps = conn.prepareStatement(SQL_INSERT_WITH_RESULT);
            ps.setString(1, dto.getSbookorgcode());
            ps.setDate(2, dto.getDentrustdate());
            ps.setString(3, dto.getSpackno());
            ps.setString(4, dto.getSagentbnkcode());
            ps.setString(5, dto.getStrano());
            if (dto.getIvousrlno()==null)
              ps.setNull(6, java.sql.Types.BIGINT);
           else
              ps.setLong(6, dto.getIvousrlno().longValue());
            ps.setString(7, dto.getSfinorgcode());
            ps.setString(8, dto.getStrecode());
            ps.setString(9, dto.getSvouno());
            ps.setDate(10, dto.getDvoudate());
            ps.setString(11, dto.getSpayeracct());
            ps.setString(12, dto.getSpayername());
            ps.setString(13, dto.getSpayeraddr());
            ps.setString(14, dto.getSpayeeacct());
            ps.setString(15, dto.getSpayeename());
            ps.setString(16, dto.getSpayeeaddr());
            ps.setString(17, dto.getSpayeeopbkno());
            ps.setString(18, dto.getSaddword());
            ps.setString(19, dto.getSbudgettype());
            ps.setString(20, dto.getStrimsign());
            ps.setString(21, dto.getSofyear());
            ps.setBigDecimal(22, dto.getFamt());
            if (dto.getIstatinfnum()==null)
              ps.setNull(23, java.sql.Types.INTEGER);
           else
              ps.setInt(23, dto.getIstatinfnum().intValue());
            ps.setDate(24, dto.getDacctdate());
            ps.setString(25, dto.getSresult());
            ps.setString(26, dto.getSdescription());
            ps.setString(27, dto.getSprocstat());
            ps.setDate(28, dto.getDacceptdate());
            ps.setTimestamp(29, dto.getTsupdate());
            ps.setString(30, dto.getSpaymode());
            ps.setString(31, dto.getSfilename());
            ps.setString(32, dto.getSid());
            ps.setString(33, dto.getSbgttypecode());
            ps.setString(34, dto.getSbgttypename());
            ps.setString(35, dto.getSfundtypecode());
            ps.setString(36, dto.getSfundtypename());
            ps.setString(37, dto.getSpaytypecode());
            ps.setString(38, dto.getSpaytypename());
            ps.setString(39, dto.getSpaybankname());
            ps.setString(40, dto.getSxpaysndbnkno());
            ps.setBigDecimal(41, dto.getSxpayamt());
            ps.setString(42, dto.getShold1());
            ps.setString(43, dto.getShold2());
            ps.setDate(44, dto.getSxcleardate());
            ps.setString(45, dto.getSagentacctbankname());
            ps.setString(46, dto.getSclearacctbankname());
            ps.setString(47, dto.getSmoneycorpcode());
            ps.setString(48, dto.getSadmdivcode());
            ps.setString(49, dto.getSvtcode());
           rs = ps.executeQuery();
           List results = getResults(rs);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }
        finally
        {
           close(ps);
           close(rs);
        }
   }

 	/**
	* Create batch new record in Database. it only create the first layer dto
	*/
    public void create(IDto[] _dtos, Connection conn)    throws SQLException
    {
        TvPayreckbankSxDto dto  ;
     	for (int i= 0; i< _dtos.length ; i++)
 	    {
 		    dto  = (TvPayreckbankSxDto)_dtos[i] ; 
    	    String msgValid = dto.checkValid() ;
        	if (msgValid != null)
     	    	throw new SQLException("插入错误，"+msgValid) ;
     	}
 	    PreparedStatement ps = null;
        try
        {
            ps = conn.prepareStatement(SQL_INSERT);
       
     	    for (int i= 0; i< _dtos.length ; i++)
     	    {
 	    	    dto  = (TvPayreckbankSxDto)_dtos[i] ; 
  
               ps.setString(1, dto.getSbookorgcode());
  
               ps.setDate(2, dto.getDentrustdate());
  
               ps.setString(3, dto.getSpackno());
  
               ps.setString(4, dto.getSagentbnkcode());
  
               ps.setString(5, dto.getStrano());
  
               if (dto.getIvousrlno()==null)
                  ps.setNull(6, java.sql.Types.BIGINT);
               else
                  ps.setLong(6, dto.getIvousrlno().longValue());
  
               ps.setString(7, dto.getSfinorgcode());
  
               ps.setString(8, dto.getStrecode());
  
               ps.setString(9, dto.getSvouno());
  
               ps.setDate(10, dto.getDvoudate());
  
               ps.setString(11, dto.getSpayeracct());
  
               ps.setString(12, dto.getSpayername());
  
               ps.setString(13, dto.getSpayeraddr());
  
               ps.setString(14, dto.getSpayeeacct());
  
               ps.setString(15, dto.getSpayeename());
  
               ps.setString(16, dto.getSpayeeaddr());
  
               ps.setString(17, dto.getSpayeeopbkno());
  
               ps.setString(18, dto.getSaddword());
  
               ps.setString(19, dto.getSbudgettype());
  
               ps.setString(20, dto.getStrimsign());
  
               ps.setString(21, dto.getSofyear());
  
               ps.setBigDecimal(22, dto.getFamt());
  
               if (dto.getIstatinfnum()==null)
                  ps.setNull(23, java.sql.Types.INTEGER);
               else
                  ps.setInt(23, dto.getIstatinfnum().intValue());
  
               ps.setDate(24, dto.getDacctdate());
  
               ps.setString(25, dto.getSresult());
  
               ps.setString(26, dto.getSdescription());
  
               ps.setString(27, dto.getSprocstat());
  
               ps.setDate(28, dto.getDacceptdate());
  
               ps.setTimestamp(29, dto.getTsupdate());
  
               ps.setString(30, dto.getSpaymode());
  
               ps.setString(31, dto.getSfilename());
  
               ps.setString(32, dto.getSid());
  
               ps.setString(33, dto.getSbgttypecode());
  
               ps.setString(34, dto.getSbgttypename());
  
               ps.setString(35, dto.getSfundtypecode());
  
               ps.setString(36, dto.getSfundtypename());
  
               ps.setString(37, dto.getSpaytypecode());
  
               ps.setString(38, dto.getSpaytypename());
  
               ps.setString(39, dto.getSpaybankname());
  
               ps.setString(40, dto.getSxpaysndbnkno());
  
               ps.setBigDecimal(41, dto.getSxpayamt());
  
               ps.setString(42, dto.getShold1());
  
               ps.setString(43, dto.getShold2());
  
               ps.setDate(44, dto.getSxcleardate());
  
               ps.setString(45, dto.getSagentacctbankname());
  
               ps.setString(46, dto.getSclearacctbankname());
  
               ps.setString(47, dto.getSmoneycorpcode());
  
               ps.setString(48, dto.getSadmdivcode());
  
               ps.setString(49, dto.getSvtcode());
               ps.addBatch(); 
           }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }
        return  ;
   }




     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto find(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TvPayreckbankSxPK pk = (TvPayreckbankSxPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT);
           ps.setString(1, pk.getSbookorgcode());

           ps.setDate(2, pk.getDentrustdate());

           ps.setString(3, pk.getSpackno());

           ps.setString(4, pk.getSagentbnkcode());

           ps.setString(5, pk.getStrano());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }

     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto findForUpdate(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TvPayreckbankSxPK pk = (TvPayreckbankSxPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT_FOR_UPDATE);
           ps.setString(1, pk.getSbookorgcode());

           ps.setDate(2, pk.getDentrustdate());

           ps.setString(3, pk.getSpackno());

           ps.setString(4, pk.getSagentbnkcode());

           ps.setString(5, pk.getStrano());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }
  
     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto[] find(IPK[] _pks, Connection conn, boolean isLobSupport) throws SQLException
    {
        TvPayreckbankSxPK pk ;
        
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TvPayreckbankSxPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 
        PreparedStatement ps = null;
        ResultSet rs = null;
        
         
        List results = new ArrayList();  
		for (int iBegin = 0; iBegin < pks.size(); iBegin += FIND_BATCH_SIZE)   //
		{
        
            try {
          		int iFindBatchSize = pks.size() - iBegin ;
	    		if (iFindBatchSize >FIND_BATCH_SIZE )
		    		iFindBatchSize = FIND_BATCH_SIZE ;
		  
        	    StringBuffer sb = new StringBuffer() ;
            	sb.append(SQL_SELECT_BATCH).append(" WHERE ").append(SQL_SELECT_BATCH_WHERE);

	    		for (int i = iBegin+1; i < iBegin + iFindBatchSize; i++)
		    	{
			    	sb.append("OR").append(SQL_SELECT_BATCH_WHERE) ;
    			}
        	
                ps = conn.prepareStatement(sb.toString());

                for (int i = iBegin;i < iBegin + iFindBatchSize; i++)
                {
                    pk  = (TvPayreckbankSxPK)(pks.get(i)) ; 
                   ps.setString((i-iBegin)*5+1, pk.getSbookorgcode());

                   ps.setDate((i-iBegin)*5+2, pk.getDentrustdate());

                   ps.setString((i-iBegin)*5+3, pk.getSpackno());

                   ps.setString((i-iBegin)*5+4, pk.getSagentbnkcode());

                   ps.setString((i-iBegin)*5+5, pk.getStrano());

			
	            }
                rs = ps.executeQuery();
                results.addAll(getResults(rs,0,isLobSupport)); //
            }finally {
                close(rs);
                close(ps);
            }
        }
        if (results!=null && results.size() > 0)
        {
            TvPayreckbankSxDto[] dtos = new TvPayreckbankSxDto[0];
		    dtos = (TvPayreckbankSxDto[]) results.toArray(dtos) ;
		    return dtos ;
        }
        else
        {
            return null;
        }
    }

  
  
  



    /**
	    * 得到查询语句
	    */
    public String getSelectSQL() 
    {
	        return SQL_SELECT_BATCH_SCROLLABLE ;
    }
   

	public List getResults(ResultSet rs) throws SQLException
    {
    	return getResults(rs, 0) ;
    }
  

    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize) throws SQLException
    {
		return getResults(rs,maxSize,false);
	}
    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize, boolean isLobSupport) throws SQLException
    {
        List results = new ArrayList();
        String str ;
        Reader reader;
        Clob clob;
        char[] chars ;
        
        while (rs.next())
         {
             TvPayreckbankSxDto  dto = new  TvPayreckbankSxDto ();
             //S_BOOKORGCODE
             str = rs.getString("S_BOOKORGCODE");
             if (str == null)
                dto.setSbookorgcode(null);
             else
                dto.setSbookorgcode(str.trim());

             //D_ENTRUSTDATE
           dto.setDentrustdate(rs.getDate("D_ENTRUSTDATE"));

             //S_PACKNO
             str = rs.getString("S_PACKNO");
             if (str == null)
                dto.setSpackno(null);
             else
                dto.setSpackno(str.trim());

             //S_AGENTBNKCODE
             str = rs.getString("S_AGENTBNKCODE");
             if (str == null)
                dto.setSagentbnkcode(null);
             else
                dto.setSagentbnkcode(str.trim());

             //S_TRANO
             str = rs.getString("S_TRANO");
             if (str == null)
                dto.setStrano(null);
             else
                dto.setStrano(str.trim());

             //I_VOUSRLNO
             str = rs.getString("I_VOUSRLNO");
             if(str!=null){
                dto.setIvousrlno(new Long(str));
             }

             //S_FINORGCODE
             str = rs.getString("S_FINORGCODE");
             if (str == null)
                dto.setSfinorgcode(null);
             else
                dto.setSfinorgcode(str.trim());

             //S_TRECODE
             str = rs.getString("S_TRECODE");
             if (str == null)
                dto.setStrecode(null);
             else
                dto.setStrecode(str.trim());

             //S_VOUNO
             str = rs.getString("S_VOUNO");
             if (str == null)
                dto.setSvouno(null);
             else
                dto.setSvouno(str.trim());

             //D_VOUDATE
           dto.setDvoudate(rs.getDate("D_VOUDATE"));

             //S_PAYERACCT
             str = rs.getString("S_PAYERACCT");
             if (str == null)
                dto.setSpayeracct(null);
             else
                dto.setSpayeracct(str.trim());

             //S_PAYERNAME
             str = rs.getString("S_PAYERNAME");
             if (str == null)
                dto.setSpayername(null);
             else
                dto.setSpayername(str.trim());

             //S_PAYERADDR
             str = rs.getString("S_PAYERADDR");
             if (str == null)
                dto.setSpayeraddr(null);
             else
                dto.setSpayeraddr(str.trim());

             //S_PAYEEACCT
             str = rs.getString("S_PAYEEACCT");
             if (str == null)
                dto.setSpayeeacct(null);
             else
                dto.setSpayeeacct(str.trim());

             //S_PAYEENAME
             str = rs.getString("S_PAYEENAME");
             if (str == null)
                dto.setSpayeename(null);
             else
                dto.setSpayeename(str.trim());

             //S_PAYEEADDR
             str = rs.getString("S_PAYEEADDR");
             if (str == null)
                dto.setSpayeeaddr(null);
             else
                dto.setSpayeeaddr(str.trim());

             //S_PAYEEOPBKNO
             str = rs.getString("S_PAYEEOPBKNO");
             if (str == null)
                dto.setSpayeeopbkno(null);
             else
                dto.setSpayeeopbkno(str.trim());

             //S_ADDWORD
             str = rs.getString("S_ADDWORD");
             if (str == null)
                dto.setSaddword(null);
             else
                dto.setSaddword(str.trim());

             //S_BUDGETTYPE
             str = rs.getString("S_BUDGETTYPE");
             if (str == null)
                dto.setSbudgettype(null);
             else
                dto.setSbudgettype(str.trim());

             //S_TRIMSIGN
             str = rs.getString("S_TRIMSIGN");
             if (str == null)
                dto.setStrimsign(null);
             else
                dto.setStrimsign(str.trim());

             //S_OFYEAR
             str = rs.getString("S_OFYEAR");
             if (str == null)
                dto.setSofyear(null);
             else
                dto.setSofyear(str.trim());

             //F_AMT
           dto.setFamt(rs.getBigDecimal("F_AMT"));

             //I_STATINFNUM
             str = rs.getString("I_STATINFNUM");
             if(str!=null){
                dto.setIstatinfnum(new Integer(str));
             }

             //D_ACCTDATE
           dto.setDacctdate(rs.getDate("D_ACCTDATE"));

             //S_RESULT
             str = rs.getString("S_RESULT");
             if (str == null)
                dto.setSresult(null);
             else
                dto.setSresult(str.trim());

             //S_DESCRIPTION
             str = rs.getString("S_DESCRIPTION");
             if (str == null)
                dto.setSdescription(null);
             else
                dto.setSdescription(str.trim());

             //S_PROCSTAT
             str = rs.getString("S_PROCSTAT");
             if (str == null)
                dto.setSprocstat(null);
             else
                dto.setSprocstat(str.trim());

             //D_ACCEPTDATE
           dto.setDacceptdate(rs.getDate("D_ACCEPTDATE"));

             //TS_UPDATE
           dto.setTsupdate(rs.getTimestamp("TS_UPDATE"));

             //S_PAYMODE
             str = rs.getString("S_PAYMODE");
             if (str == null)
                dto.setSpaymode(null);
             else
                dto.setSpaymode(str.trim());

             //S_FILENAME
             str = rs.getString("S_FILENAME");
             if (str == null)
                dto.setSfilename(null);
             else
                dto.setSfilename(str.trim());

             //S_ID
             str = rs.getString("S_ID");
             if (str == null)
                dto.setSid(null);
             else
                dto.setSid(str.trim());

             //S_BGTTYPECODE
             str = rs.getString("S_BGTTYPECODE");
             if (str == null)
                dto.setSbgttypecode(null);
             else
                dto.setSbgttypecode(str.trim());

             //S_BGTTYPENAME
             str = rs.getString("S_BGTTYPENAME");
             if (str == null)
                dto.setSbgttypename(null);
             else
                dto.setSbgttypename(str.trim());

             //S_FUNDTYPECODE
             str = rs.getString("S_FUNDTYPECODE");
             if (str == null)
                dto.setSfundtypecode(null);
             else
                dto.setSfundtypecode(str.trim());

             //S_FUNDTYPENAME
             str = rs.getString("S_FUNDTYPENAME");
             if (str == null)
                dto.setSfundtypename(null);
             else
                dto.setSfundtypename(str.trim());

             //S_PAYTYPECODE
             str = rs.getString("S_PAYTYPECODE");
             if (str == null)
                dto.setSpaytypecode(null);
             else
                dto.setSpaytypecode(str.trim());

             //S_PAYTYPENAME
             str = rs.getString("S_PAYTYPENAME");
             if (str == null)
                dto.setSpaytypename(null);
             else
                dto.setSpaytypename(str.trim());

             //S_PAYBANKNAME
             str = rs.getString("S_PAYBANKNAME");
             if (str == null)
                dto.setSpaybankname(null);
             else
                dto.setSpaybankname(str.trim());

             //S_XPAYSNDBNKNO
             str = rs.getString("S_XPAYSNDBNKNO");
             if (str == null)
                dto.setSxpaysndbnkno(null);
             else
                dto.setSxpaysndbnkno(str.trim());

             //S_XPAYAMT
           dto.setSxpayamt(rs.getBigDecimal("S_XPAYAMT"));

             //S_HOLD1
             str = rs.getString("S_HOLD1");
             if (str == null)
                dto.setShold1(null);
             else
                dto.setShold1(str.trim());

             //S_HOLD2
             str = rs.getString("S_HOLD2");
             if (str == null)
                dto.setShold2(null);
             else
                dto.setShold2(str.trim());

             //S_XCLEARDATE
           dto.setSxcleardate(rs.getDate("S_XCLEARDATE"));

             //S_AGENTACCTBANKNAME
             str = rs.getString("S_AGENTACCTBANKNAME");
             if (str == null)
                dto.setSagentacctbankname(null);
             else
                dto.setSagentacctbankname(str.trim());

             //S_CLEARACCTBANKNAME
             str = rs.getString("S_CLEARACCTBANKNAME");
             if (str == null)
                dto.setSclearacctbankname(null);
             else
                dto.setSclearacctbankname(str.trim());

             //S_MONEYCORPCODE
             str = rs.getString("S_MONEYCORPCODE");
             if (str == null)
                dto.setSmoneycorpcode(null);
             else
                dto.setSmoneycorpcode(str.trim());

             //S_ADMDIVCODE
             str = rs.getString("S_ADMDIVCODE");
             if (str == null)
                dto.setSadmdivcode(null);
             else
                dto.setSadmdivcode(str.trim());

             //S_VTCODE
             str = rs.getString("S_VTCODE");
             if (str == null)
                dto.setSvtcode(null);
             else
                dto.setSvtcode(str.trim());



            results.add(dto);
            
            if(maxSize >0  && results.size() == maxSize)
            {
            	break ;
            }
            
         }
        
		return results ;
    }

  /**
   * populate resultSet as cclass
   */
  protected IDto[] getChildrenResults(ResultSet rs ,Class _dto) throws SQLException{

      throw new SQLException("本dto没有与其它dto相关联，无法应用此方法");
  }


     /**
     * Update a record in Database.
     */

    public void update(IDto _dto, Connection conn, boolean isLobSupport) throws SQLException
    {
        String msgValid = _dto.checkValid() ;
        if (msgValid != null)
            throw new SQLException("修改错误，"+msgValid) ;
        TvPayreckbankSxDto dto = (TvPayreckbankSxDto)_dto ;
        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            int pos = 1;
            //I_VOUSRLNO
            if (dto.getIvousrlno()==null)
               ps.setNull(pos, java.sql.Types.BIGINT);
            else
               ps.setLong(pos, dto.getIvousrlno().longValue());
            pos++;

            //S_FINORGCODE
            ps.setString(pos, dto.getSfinorgcode());
            pos++;

            //S_TRECODE
            ps.setString(pos, dto.getStrecode());
            pos++;

            //S_VOUNO
            ps.setString(pos, dto.getSvouno());
            pos++;

            //D_VOUDATE
            ps.setDate(pos, dto.getDvoudate());
            pos++;

            //S_PAYERACCT
            ps.setString(pos, dto.getSpayeracct());
            pos++;

            //S_PAYERNAME
            ps.setString(pos, dto.getSpayername());
            pos++;

            //S_PAYERADDR
            ps.setString(pos, dto.getSpayeraddr());
            pos++;

            //S_PAYEEACCT
            ps.setString(pos, dto.getSpayeeacct());
            pos++;

            //S_PAYEENAME
            ps.setString(pos, dto.getSpayeename());
            pos++;

            //S_PAYEEADDR
            ps.setString(pos, dto.getSpayeeaddr());
            pos++;

            //S_PAYEEOPBKNO
            ps.setString(pos, dto.getSpayeeopbkno());
            pos++;

            //S_ADDWORD
            ps.setString(pos, dto.getSaddword());
            pos++;

            //S_BUDGETTYPE
            ps.setString(pos, dto.getSbudgettype());
            pos++;

            //S_TRIMSIGN
            ps.setString(pos, dto.getStrimsign());
            pos++;

            //S_OFYEAR
            ps.setString(pos, dto.getSofyear());
            pos++;

            //F_AMT
            ps.setBigDecimal(pos, dto.getFamt());
            pos++;

            //I_STATINFNUM
            if (dto.getIstatinfnum()==null)
                ps.setNull(pos, java.sql.Types.INTEGER);
            else
                ps.setInt(pos, dto.getIstatinfnum().intValue());
            pos++;

            //D_ACCTDATE
            ps.setDate(pos, dto.getDacctdate());
            pos++;

            //S_RESULT
            ps.setString(pos, dto.getSresult());
            pos++;

            //S_DESCRIPTION
            ps.setString(pos, dto.getSdescription());
            pos++;

            //S_PROCSTAT
            ps.setString(pos, dto.getSprocstat());
            pos++;

            //D_ACCEPTDATE
            ps.setDate(pos, dto.getDacceptdate());
            pos++;

            //TS_UPDATE
            ps.setTimestamp(pos, dto.getTsupdate());
            pos++;

            //S_PAYMODE
            ps.setString(pos, dto.getSpaymode());
            pos++;

            //S_FILENAME
            ps.setString(pos, dto.getSfilename());
            pos++;

            //S_ID
            ps.setString(pos, dto.getSid());
            pos++;

            //S_BGTTYPECODE
            ps.setString(pos, dto.getSbgttypecode());
            pos++;

            //S_BGTTYPENAME
            ps.setString(pos, dto.getSbgttypename());
            pos++;

            //S_FUNDTYPECODE
            ps.setString(pos, dto.getSfundtypecode());
            pos++;

            //S_FUNDTYPENAME
            ps.setString(pos, dto.getSfundtypename());
            pos++;

            //S_PAYTYPECODE
            ps.setString(pos, dto.getSpaytypecode());
            pos++;

            //S_PAYTYPENAME
            ps.setString(pos, dto.getSpaytypename());
            pos++;

            //S_PAYBANKNAME
            ps.setString(pos, dto.getSpaybankname());
            pos++;

            //S_XPAYSNDBNKNO
            ps.setString(pos, dto.getSxpaysndbnkno());
            pos++;

            //S_XPAYAMT
            ps.setBigDecimal(pos, dto.getSxpayamt());
            pos++;

            //S_HOLD1
            ps.setString(pos, dto.getShold1());
            pos++;

            //S_HOLD2
            ps.setString(pos, dto.getShold2());
            pos++;

            //S_XCLEARDATE
            ps.setDate(pos, dto.getSxcleardate());
            pos++;

            //S_AGENTACCTBANKNAME
            ps.setString(pos, dto.getSagentacctbankname());
            pos++;

            //S_CLEARACCTBANKNAME
            ps.setString(pos, dto.getSclearacctbankname());
            pos++;

            //S_MONEYCORPCODE
            ps.setString(pos, dto.getSmoneycorpcode());
            pos++;

            //S_ADMDIVCODE
            ps.setString(pos, dto.getSadmdivcode());
            pos++;

            //S_VTCODE
            ps.setString(pos, dto.getSvtcode());
            pos++;


           //S_BOOKORGCODE
           ps.setString(pos, dto.getSbookorgcode());
           pos++;
           //D_ENTRUSTDATE
           ps.setDate(pos, dto.getDentrustdate());
           pos++;
           //S_PACKNO
           ps.setString(pos, dto.getSpackno());
           pos++;
           //S_AGENTBNKCODE
           ps.setString(pos, dto.getSagentbnkcode());
           pos++;
           //S_TRANO
           ps.setString(pos, dto.getStrano());
           pos++;
           ps.executeUpdate();
        }
        finally
        {
           close(ps);
        }

        return ;
    }
    
    
    
      /**
     * Update batch record in Database.
     */

    public void update(IDto[] _dtos, Connection conn, boolean isLobSupport) throws SQLException
    {
     
     	 TvPayreckbankSxDto dto  ;
         for (int i= 0; i< _dtos.length ; i++)
         {
            dto  = (TvPayreckbankSxDto)_dtos[i] ; 
            String msgValid = dto.checkValid() ;
            if (msgValid != null)
                throw new SQLException("修改错误，"+msgValid) ;
         }

        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            
            for (int i= 0; i< _dtos.length ; i++)
            {
                dto  = (TvPayreckbankSxDto)_dtos[i] ; 
                int pos = 1;
                //I_VOUSRLNO
                 if (dto.getIvousrlno()==null)
                   ps.setNull(pos, java.sql.Types.BIGINT);
                else
                   ps.setLong(pos, dto.getIvousrlno().longValue());
                pos++;

                //S_FINORGCODE
                 ps.setString(pos, dto.getSfinorgcode());
                pos++;

                //S_TRECODE
                 ps.setString(pos, dto.getStrecode());
                pos++;

                //S_VOUNO
                 ps.setString(pos, dto.getSvouno());
                pos++;

                //D_VOUDATE
                 ps.setDate(pos, dto.getDvoudate());
                pos++;

                //S_PAYERACCT
                 ps.setString(pos, dto.getSpayeracct());
                pos++;

                //S_PAYERNAME
                 ps.setString(pos, dto.getSpayername());
                pos++;

                //S_PAYERADDR
                 ps.setString(pos, dto.getSpayeraddr());
                pos++;

                //S_PAYEEACCT
                 ps.setString(pos, dto.getSpayeeacct());
                pos++;

                //S_PAYEENAME
                 ps.setString(pos, dto.getSpayeename());
                pos++;

                //S_PAYEEADDR
                 ps.setString(pos, dto.getSpayeeaddr());
                pos++;

                //S_PAYEEOPBKNO
                 ps.setString(pos, dto.getSpayeeopbkno());
                pos++;

                //S_ADDWORD
                 ps.setString(pos, dto.getSaddword());
                pos++;

                //S_BUDGETTYPE
                 ps.setString(pos, dto.getSbudgettype());
                pos++;

                //S_TRIMSIGN
                 ps.setString(pos, dto.getStrimsign());
                pos++;

                //S_OFYEAR
                 ps.setString(pos, dto.getSofyear());
                pos++;

                //F_AMT
                 ps.setBigDecimal(pos, dto.getFamt());
                pos++;

                //I_STATINFNUM
                 if (dto.getIstatinfnum()==null)
                   ps.setNull(pos, java.sql.Types.INTEGER);
                else
                   ps.setInt(pos, dto.getIstatinfnum().intValue());
                pos++ ;

                //D_ACCTDATE
                 ps.setDate(pos, dto.getDacctdate());
                pos++;

                //S_RESULT
                 ps.setString(pos, dto.getSresult());
                pos++;

                //S_DESCRIPTION
                 ps.setString(pos, dto.getSdescription());
                pos++;

                //S_PROCSTAT
                 ps.setString(pos, dto.getSprocstat());
                pos++;

                //D_ACCEPTDATE
                 ps.setDate(pos, dto.getDacceptdate());
                pos++;

                //TS_UPDATE
                 ps.setTimestamp(pos, dto.getTsupdate());
                pos++;

                //S_PAYMODE
                 ps.setString(pos, dto.getSpaymode());
                pos++;

                //S_FILENAME
                 ps.setString(pos, dto.getSfilename());
                pos++;

                //S_ID
                 ps.setString(pos, dto.getSid());
                pos++;

                //S_BGTTYPECODE
                 ps.setString(pos, dto.getSbgttypecode());
                pos++;

                //S_BGTTYPENAME
                 ps.setString(pos, dto.getSbgttypename());
                pos++;

                //S_FUNDTYPECODE
                 ps.setString(pos, dto.getSfundtypecode());
                pos++;

                //S_FUNDTYPENAME
                 ps.setString(pos, dto.getSfundtypename());
                pos++;

                //S_PAYTYPECODE
                 ps.setString(pos, dto.getSpaytypecode());
                pos++;

                //S_PAYTYPENAME
                 ps.setString(pos, dto.getSpaytypename());
                pos++;

                //S_PAYBANKNAME
                 ps.setString(pos, dto.getSpaybankname());
                pos++;

                //S_XPAYSNDBNKNO
                 ps.setString(pos, dto.getSxpaysndbnkno());
                pos++;

                //S_XPAYAMT
                 ps.setBigDecimal(pos, dto.getSxpayamt());
                pos++;

                //S_HOLD1
                 ps.setString(pos, dto.getShold1());
                pos++;

                //S_HOLD2
                 ps.setString(pos, dto.getShold2());
                pos++;

                //S_XCLEARDATE
                 ps.setDate(pos, dto.getSxcleardate());
                pos++;

                //S_AGENTACCTBANKNAME
                 ps.setString(pos, dto.getSagentacctbankname());
                pos++;

                //S_CLEARACCTBANKNAME
                 ps.setString(pos, dto.getSclearacctbankname());
                pos++;

                //S_MONEYCORPCODE
                 ps.setString(pos, dto.getSmoneycorpcode());
                pos++;

                //S_ADMDIVCODE
                 ps.setString(pos, dto.getSadmdivcode());
                pos++;

                //S_VTCODE
                 ps.setString(pos, dto.getSvtcode());
                pos++;


               //S_BOOKORGCODE
               ps.setString(pos, dto.getSbookorgcode());
               pos++;
               //D_ENTRUSTDATE
               ps.setDate(pos, dto.getDentrustdate());
               pos++;
               //S_PACKNO
               ps.setString(pos, dto.getSpackno());
               pos++;
               //S_AGENTBNKCODE
               ps.setString(pos, dto.getSagentbnkcode());
               pos++;
               //S_TRANO
               ps.setString(pos, dto.getStrano());
               pos++;
		       ps.addBatch(); 
	       }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }

        return ;
    }



    /**
     * delete a record in Database.
     */
    public void delete(IPK _pk, Connection conn) throws SQLException
    {
       
      
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return ;
        //	throw new SQLException("删除错误，"+msgValid) ;
       }
       TvPayreckbankSxPK pk = (TvPayreckbankSxPK)_pk ;


       PreparedStatement ps = null;
       try {
           ps = conn.prepareStatement(SQL_DELETE);
           ps.setString(1, pk.getSbookorgcode());
           ps.setDate(2, pk.getDentrustdate());
           ps.setString(3, pk.getSpackno());
           ps.setString(4, pk.getSagentbnkcode());
           ps.setString(5, pk.getStrano());
           ps.executeUpdate();
        }
        finally
        {
            close(ps);
        }
    }


     /**
     * delete batch record in Database.
     */
    public void delete(IPK[] _pks, Connection conn) throws SQLException
    {
        TvPayreckbankSxPK pk ;
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TvPayreckbankSxPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 		
 		
        PreparedStatement ps = null;
        try
         {
            ps = conn.prepareStatement(SQL_DELETE);
             
       		for (int i= 0; i< pks.size() ; i++)
       		{
       			pk  = (TvPayreckbankSxPK)(pks.get(i)) ; 
                ps.setString(1, pk.getSbookorgcode());
                ps.setDate(2, pk.getDentrustdate());
                ps.setString(3, pk.getSpackno());
                ps.setString(4, pk.getSagentbnkcode());
                ps.setString(5, pk.getStrano());
		        ps.addBatch() ;
			}
            ps.executeBatch();
        }
        finally
        {
            close(ps);
        }      
    }



    /**
    * Check IChangerNumber or UpdateTimeStamp.
    */
    public void check(IDto _dto, Connection conn) throws SQLException
    {
                                                                                                                                    		throw new SQLException("数据库表：TV_PAYRECKBANK_SX没有检查修改的字段");
    }


	/**
	* synchronize values between parent and children
	*/
    public void syncToChildren(IDto _dto)     throws SQLException{
       throw new SQLException("本记录没有与其它记录相关联，无法进行主记录与明细记录之间的数据同步。");
  }

	/**
	*get children
	*/
    public IDto[] findChildren (IDto _dto, Connection conn, boolean isLobSupport)     throws SQLException{
         throw new SQLException("本dto没有与其它dto相关联，无法得到子dto");
  }    
    
  /**
   *return the children IDto class
   * @return Class
   */
  public Class getChildrenClass(){
	  return null;
  };    



    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt)
    {
        if (stmt != null)
        {
            try
            {
                stmt.close();
            }
            catch(SQLException    e)
            {}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs)
    {
        if (rs != null)
        {
            try
            {
                rs.close();
            }catch(SQLException  e){}
        }
    }
}
