    



package com.cfcc.itfe.persistence.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;
import java.sql.Clob;

import com.cfcc.jaf.persistence.jaform.parent.* ;

import java.math.BigDecimal;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

import java.io.StringReader;
import java.io.Reader;
import java.io.IOException;

import com.cfcc.itfe.persistence.dto.TvPbcpaySubDto ;
import com.cfcc.itfe.persistence.pk.TvPbcpaySubPK ;


/**
 * <p>Title: DAO of table: TV_PBCPAY_SUB</p>
 * <p>Description: Data Access Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:04 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dao.vm timestamp: 2007-04-06 08:30:00
 ******************************************************
 * <p> <b>change record</b><br>
 *  make dao methods simply.<br>
 *  especially make update,delete methods simply.<br>
 *  remove "..withCheck" method,withCheck will impl in JAFOrmTemplate.<br>
 *  remove "delete(IDto _dto,..)" method.<br></p>
 * @author win7
 */

public class TvPbcpaySubDao  implements IDao
{


    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO TV_PBCPAY_SUB ("
          + "I_VOUSRLNO,I_SEQNO,S_BDGORGCODE,S_FUNCSBTCODE,S_ECOSBTCODE"
          + ",C_ACCTPROP,F_AMT,TS_SYSUPDATE"
        + ") VALUES ("
        + "DEFAULT ,?,?,?,?,?,?,CURRENT TIMESTAMP )";


    private static final String SQL_INSERT_WITH_RESULT = "SELECT * FROM FINAL TABLE( " + SQL_INSERT + " )";
    
    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "TV_PBCPAY_SUB.I_VOUSRLNO, TV_PBCPAY_SUB.I_SEQNO, TV_PBCPAY_SUB.S_BDGORGCODE, TV_PBCPAY_SUB.S_FUNCSBTCODE, TV_PBCPAY_SUB.S_ECOSBTCODE, "
        + "TV_PBCPAY_SUB.C_ACCTPROP, TV_PBCPAY_SUB.F_AMT, TV_PBCPAY_SUB.TS_SYSUPDATE "
        + "FROM TV_PBCPAY_SUB "
        +" WHERE " 
        + "I_VOUSRLNO = ? AND I_SEQNO = ?"
        ;
    /* SQL to select for update data */
    private static final String SQL_SELECT_FOR_UPDATE =
        "SELECT "
        + "TV_PBCPAY_SUB.I_VOUSRLNO, TV_PBCPAY_SUB.I_SEQNO, TV_PBCPAY_SUB.S_BDGORGCODE, TV_PBCPAY_SUB.S_FUNCSBTCODE, TV_PBCPAY_SUB.S_ECOSBTCODE, "
        + "TV_PBCPAY_SUB.C_ACCTPROP, TV_PBCPAY_SUB.F_AMT, TV_PBCPAY_SUB.TS_SYSUPDATE "
        + "FROM TV_PBCPAY_SUB "
        +" WHERE " 
        + "I_VOUSRLNO = ? AND I_SEQNO = ? FOR UPDATE"
        ;

      /* SQL to select data (SCROLLABLE)*/
     private static final String SQL_SELECT_BATCH_SCROLLABLE =
        "SELECT "
        + "  TV_PBCPAY_SUB.I_VOUSRLNO  , TV_PBCPAY_SUB.I_SEQNO  , TV_PBCPAY_SUB.S_BDGORGCODE  , TV_PBCPAY_SUB.S_FUNCSBTCODE  , TV_PBCPAY_SUB.S_ECOSBTCODE "
        + " , TV_PBCPAY_SUB.C_ACCTPROP  , TV_PBCPAY_SUB.F_AMT  , TV_PBCPAY_SUB.TS_SYSUPDATE "
        + "FROM TV_PBCPAY_SUB ";



    /* SQL to select batch data */
    private static final String SQL_SELECT_BATCH =
        "SELECT "
        + "TV_PBCPAY_SUB.I_VOUSRLNO, TV_PBCPAY_SUB.I_SEQNO, TV_PBCPAY_SUB.S_BDGORGCODE, TV_PBCPAY_SUB.S_FUNCSBTCODE, TV_PBCPAY_SUB.S_ECOSBTCODE, "
        + "TV_PBCPAY_SUB.C_ACCTPROP, TV_PBCPAY_SUB.F_AMT, TV_PBCPAY_SUB.TS_SYSUPDATE "
        + "FROM TV_PBCPAY_SUB " ;
        

   /* SQL to select batch data where condition  */
    private static final String SQL_SELECT_BATCH_WHERE =" ( "
        + "I_VOUSRLNO = ? AND I_SEQNO = ?)"
        ;


    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE TV_PBCPAY_SUB SET "
        + "S_BDGORGCODE =?,S_FUNCSBTCODE =?,S_ECOSBTCODE =?,C_ACCTPROP =?,F_AMT =?, "
        + "TS_SYSUPDATE =CURRENT TIMESTAMP "
        + "WHERE "
        + "I_VOUSRLNO = ? AND I_SEQNO = ?"
        ;

	/* SQL to update data, support LOB */
    private static final String SQL_UPDATE_LOB =
        "UPDATE TV_PBCPAY_SUB SET "
        + "S_BDGORGCODE =?, S_FUNCSBTCODE =?, S_ECOSBTCODE =?, C_ACCTPROP =?, F_AMT =?,  "
        + "TS_SYSUPDATE =CURRENT TIMESTAMP "
        + "WHERE "
        + "I_VOUSRLNO = ? AND I_SEQNO = ?"
        ;	
	
    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM TV_PBCPAY_SUB " 
        + " WHERE "
        + "I_VOUSRLNO = ? AND I_SEQNO = ?"
        ;


	/**
	*  批量查询 一次最多查询的参数数量
	*/
	
	public static final int FIND_BATCH_SIZE = 150  / 2;
	



   /**
   * Create a new record in Database.
   */
  public void create(IDto _dto,  Connection conn) throws SQLException
  {
     TvPbcpaySubDto dto = (TvPbcpaySubDto)_dto ;
     String msgValid = dto.checkValid() ;
     if (msgValid != null)
     	throw new SQLException("插入错误，"+msgValid) ;

     PreparedStatement ps = null;
     try
     {
         ps = conn.prepareStatement(SQL_INSERT);
           if (dto.getIseqno()==null)
            ps.setNull(1, java.sql.Types.INTEGER);
         else
            ps.setInt(1, dto.getIseqno().intValue());
          ps.setString(2, dto.getSbdgorgcode());

          ps.setString(3, dto.getSfuncsbtcode());

          ps.setString(4, dto.getSecosbtcode());

          ps.setString(5, dto.getCacctprop());

          ps.setBigDecimal(6, dto.getFamt());

          ps.executeUpdate();
     }
     finally
     {
         close(ps);
     }
     return  ;
  }

   /**
   * Create a new record in Database. and return result, only used when having generated key
   */
   public IDto createWithResult(IDto _dto,  Connection conn) throws SQLException
   {
       TvPbcpaySubDto dto = (TvPbcpaySubDto)_dto ;
       String msgValid = dto.checkValid() ;
       if (msgValid != null)
           throw new SQLException("插入错误，"+msgValid) ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try
       {
           ps = conn.prepareStatement(SQL_INSERT_WITH_RESULT);
             if (dto.getIseqno()==null)
              ps.setNull(1, java.sql.Types.INTEGER);
           else
              ps.setInt(1, dto.getIseqno().intValue());
            ps.setString(2, dto.getSbdgorgcode());
            ps.setString(3, dto.getSfuncsbtcode());
            ps.setString(4, dto.getSecosbtcode());
            ps.setString(5, dto.getCacctprop());
            ps.setBigDecimal(6, dto.getFamt());
            rs = ps.executeQuery();
           List results = getResults(rs);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }
        finally
        {
           close(ps);
           close(rs);
        }
   }

 	/**
	* Create batch new record in Database. it only create the first layer dto
	*/
    public void create(IDto[] _dtos, Connection conn)    throws SQLException
    {
        TvPbcpaySubDto dto  ;
     	for (int i= 0; i< _dtos.length ; i++)
 	    {
 		    dto  = (TvPbcpaySubDto)_dtos[i] ; 
    	    String msgValid = dto.checkValid() ;
        	if (msgValid != null)
     	    	throw new SQLException("插入错误，"+msgValid) ;
     	}
 	    PreparedStatement ps = null;
        try
        {
            ps = conn.prepareStatement(SQL_INSERT);
       
     	    for (int i= 0; i< _dtos.length ; i++)
     	    {
 	    	    dto  = (TvPbcpaySubDto)_dtos[i] ; 
   
               if (dto.getIseqno()==null)
                  ps.setNull(1, java.sql.Types.INTEGER);
               else
                  ps.setInt(1, dto.getIseqno().intValue());
  
               ps.setString(2, dto.getSbdgorgcode());
  
               ps.setString(3, dto.getSfuncsbtcode());
  
               ps.setString(4, dto.getSecosbtcode());
  
               ps.setString(5, dto.getCacctprop());
  
               ps.setBigDecimal(6, dto.getFamt());
                ps.addBatch(); 
           }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }
        return  ;
   }




     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto find(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TvPbcpaySubPK pk = (TvPbcpaySubPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT);
           if (pk.getIvousrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIvousrlno().longValue());


           if (pk.getIseqno()==null)
               ps.setNull(2, java.sql.Types.INTEGER);
           else
               ps.setInt(2, pk.getIseqno().intValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }

     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto findForUpdate(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TvPbcpaySubPK pk = (TvPbcpaySubPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT_FOR_UPDATE);
           if (pk.getIvousrlno()==null)
               ps.setNull(1, java.sql.Types.BIGINT);
           else
               ps.setLong(1, pk.getIvousrlno().longValue());


           if (pk.getIseqno()==null)
               ps.setNull(2, java.sql.Types.INTEGER);
           else
               ps.setInt(2, pk.getIseqno().intValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }
  
     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto[] find(IPK[] _pks, Connection conn, boolean isLobSupport) throws SQLException
    {
        TvPbcpaySubPK pk ;
        
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TvPbcpaySubPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 
        PreparedStatement ps = null;
        ResultSet rs = null;
        
         
        List results = new ArrayList();  
		for (int iBegin = 0; iBegin < pks.size(); iBegin += FIND_BATCH_SIZE)   //
		{
        
            try {
          		int iFindBatchSize = pks.size() - iBegin ;
	    		if (iFindBatchSize >FIND_BATCH_SIZE )
		    		iFindBatchSize = FIND_BATCH_SIZE ;
		  
        	    StringBuffer sb = new StringBuffer() ;
            	sb.append(SQL_SELECT_BATCH).append(" WHERE ").append(SQL_SELECT_BATCH_WHERE);

	    		for (int i = iBegin+1; i < iBegin + iFindBatchSize; i++)
		    	{
			    	sb.append("OR").append(SQL_SELECT_BATCH_WHERE) ;
    			}
        	
                ps = conn.prepareStatement(sb.toString());

                for (int i = iBegin;i < iBegin + iFindBatchSize; i++)
                {
                    pk  = (TvPbcpaySubPK)(pks.get(i)) ; 
                   if (pk.getIvousrlno()==null)
                      ps.setNull((i-iBegin)*2+1, java.sql.Types.BIGINT);
                   else
                      ps.setLong((i-iBegin)*2+1, pk.getIvousrlno().longValue());

                   if (pk.getIseqno()==null)
                      ps.setNull((i-iBegin)*2+ 2 , java.sql.Types.INTEGER);
                   else
                     ps.setInt((i-iBegin)*2+2, pk.getIseqno().intValue());

			
	            }
                rs = ps.executeQuery();
                results.addAll(getResults(rs,0,isLobSupport)); //
            }finally {
                close(rs);
                close(ps);
            }
        }
        if (results!=null && results.size() > 0)
        {
            TvPbcpaySubDto[] dtos = new TvPbcpaySubDto[0];
		    dtos = (TvPbcpaySubDto[]) results.toArray(dtos) ;
		    return dtos ;
        }
        else
        {
            return null;
        }
    }

  
  
  



    /**
	    * 得到查询语句
	    */
    public String getSelectSQL() 
    {
	        return SQL_SELECT_BATCH_SCROLLABLE ;
    }
   

	public List getResults(ResultSet rs) throws SQLException
    {
    	return getResults(rs, 0) ;
    }
  

    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize) throws SQLException
    {
		return getResults(rs,maxSize,false);
	}
    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize, boolean isLobSupport) throws SQLException
    {
        List results = new ArrayList();
        String str ;
        Reader reader;
        Clob clob;
        char[] chars ;
        
        while (rs.next())
         {
             TvPbcpaySubDto  dto = new  TvPbcpaySubDto ();
             //I_VOUSRLNO
             str = rs.getString("I_VOUSRLNO");
             if(str!=null){
                dto.setIvousrlno(new Long(str));
             }

             //I_SEQNO
             str = rs.getString("I_SEQNO");
             if(str!=null){
                dto.setIseqno(new Integer(str));
             }

             //S_BDGORGCODE
             str = rs.getString("S_BDGORGCODE");
             if (str == null)
                dto.setSbdgorgcode(null);
             else
                dto.setSbdgorgcode(str.trim());

             //S_FUNCSBTCODE
             str = rs.getString("S_FUNCSBTCODE");
             if (str == null)
                dto.setSfuncsbtcode(null);
             else
                dto.setSfuncsbtcode(str.trim());

             //S_ECOSBTCODE
             str = rs.getString("S_ECOSBTCODE");
             if (str == null)
                dto.setSecosbtcode(null);
             else
                dto.setSecosbtcode(str.trim());

             //C_ACCTPROP
             str = rs.getString("C_ACCTPROP");
             if (str == null)
                dto.setCacctprop(null);
             else
                dto.setCacctprop(str.trim());

             //F_AMT
           dto.setFamt(rs.getBigDecimal("F_AMT"));

             //TS_SYSUPDATE
           dto.setTssysupdate(rs.getTimestamp("TS_SYSUPDATE"));



            results.add(dto);
            
            if(maxSize >0  && results.size() == maxSize)
            {
            	break ;
            }
            
         }
        
		return results ;
    }

  /**
   * populate resultSet as cclass
   */
  protected IDto[] getChildrenResults(ResultSet rs ,Class _dto) throws SQLException{

      throw new SQLException("本dto没有与其它dto相关联，无法应用此方法");
  }


     /**
     * Update a record in Database.
     */

    public void update(IDto _dto, Connection conn, boolean isLobSupport) throws SQLException
    {
        String msgValid = _dto.checkValid() ;
        if (msgValid != null)
            throw new SQLException("修改错误，"+msgValid) ;
        TvPbcpaySubDto dto = (TvPbcpaySubDto)_dto ;
        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            int pos = 1;
            //S_BDGORGCODE
            ps.setString(pos, dto.getSbdgorgcode());
            pos++;

            //S_FUNCSBTCODE
            ps.setString(pos, dto.getSfuncsbtcode());
            pos++;

            //S_ECOSBTCODE
            ps.setString(pos, dto.getSecosbtcode());
            pos++;

            //C_ACCTPROP
            ps.setString(pos, dto.getCacctprop());
            pos++;

            //F_AMT
            ps.setBigDecimal(pos, dto.getFamt());
            pos++;

            //TS_SYSUPDATE

           //I_VOUSRLNO
           ps.setLong(pos, dto.getIvousrlno().longValue());
           pos++;
           //I_SEQNO
           ps.setInt(pos, dto.getIseqno().intValue());
           pos++;
           ps.executeUpdate();
        }
        finally
        {
           close(ps);
        }

        return ;
    }
    
    
    
      /**
     * Update batch record in Database.
     */

    public void update(IDto[] _dtos, Connection conn, boolean isLobSupport) throws SQLException
    {
     
     	 TvPbcpaySubDto dto  ;
         for (int i= 0; i< _dtos.length ; i++)
         {
            dto  = (TvPbcpaySubDto)_dtos[i] ; 
            String msgValid = dto.checkValid() ;
            if (msgValid != null)
                throw new SQLException("修改错误，"+msgValid) ;
         }

        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            
            for (int i= 0; i< _dtos.length ; i++)
            {
                dto  = (TvPbcpaySubDto)_dtos[i] ; 
                int pos = 1;
                //S_BDGORGCODE
                 ps.setString(pos, dto.getSbdgorgcode());
                pos++;

                //S_FUNCSBTCODE
                 ps.setString(pos, dto.getSfuncsbtcode());
                pos++;

                //S_ECOSBTCODE
                 ps.setString(pos, dto.getSecosbtcode());
                pos++;

                //C_ACCTPROP
                 ps.setString(pos, dto.getCacctprop());
                pos++;

                //F_AMT
                 ps.setBigDecimal(pos, dto.getFamt());
                pos++;

                //TS_SYSUPDATE
 
               //I_VOUSRLNO
               ps.setLong(pos, dto.getIvousrlno().longValue());
               pos++;
               //I_SEQNO
               ps.setInt(pos, dto.getIseqno().intValue());
               pos++;
		       ps.addBatch(); 
	       }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }

        return ;
    }



    /**
     * delete a record in Database.
     */
    public void delete(IPK _pk, Connection conn) throws SQLException
    {
       
      
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return ;
        //	throw new SQLException("删除错误，"+msgValid) ;
       }
       TvPbcpaySubPK pk = (TvPbcpaySubPK)_pk ;


       PreparedStatement ps = null;
       try {
           ps = conn.prepareStatement(SQL_DELETE);
           ps.setLong(1, pk.getIvousrlno().longValue());
           ps.setInt(2, pk.getIseqno().intValue());
           ps.executeUpdate();
        }
        finally
        {
            close(ps);
        }
    }


     /**
     * delete batch record in Database.
     */
    public void delete(IPK[] _pks, Connection conn) throws SQLException
    {
        TvPbcpaySubPK pk ;
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TvPbcpaySubPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 		
 		
        PreparedStatement ps = null;
        try
         {
            ps = conn.prepareStatement(SQL_DELETE);
             
       		for (int i= 0; i< pks.size() ; i++)
       		{
       			pk  = (TvPbcpaySubPK)(pks.get(i)) ; 
                ps.setLong(1, pk.getIvousrlno().longValue());
                ps.setInt(2, pk.getIseqno().intValue());
		        ps.addBatch() ;
			}
            ps.executeBatch();
        }
        finally
        {
            close(ps);
        }      
    }



    /**
    * Check IChangerNumber or UpdateTimeStamp.
    */
    public void check(IDto _dto, Connection conn) throws SQLException
    {
                  		throw new SQLException("数据库表：TV_PBCPAY_SUB没有检查修改的字段");
    }


	/**
	* synchronize values between parent and children
	*/
    public void syncToChildren(IDto _dto)     throws SQLException{
       throw new SQLException("本记录没有与其它记录相关联，无法进行主记录与明细记录之间的数据同步。");
  }

	/**
	*get children
	*/
    public IDto[] findChildren (IDto _dto, Connection conn, boolean isLobSupport)     throws SQLException{
         throw new SQLException("本dto没有与其它dto相关联，无法得到子dto");
  }    
    
  /**
   *return the children IDto class
   * @return Class
   */
  public Class getChildrenClass(){
	  return null;
  };    



    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt)
    {
        if (stmt != null)
        {
            try
            {
                stmt.close();
            }
            catch(SQLException    e)
            {}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs)
    {
        if (rs != null)
        {
            try
            {
                rs.close();
            }catch(SQLException  e){}
        }
    }
}
