    



package com.cfcc.itfe.persistence.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;
import java.sql.Clob;

import com.cfcc.jaf.persistence.jaform.parent.* ;

import java.math.BigDecimal;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

import java.io.StringReader;
import java.io.Reader;
import java.io.IOException;

import com.cfcc.itfe.persistence.dto.TvTaxItemDto ;
import com.cfcc.itfe.persistence.pk.TvTaxItemPK ;


/**
 * <p>Title: DAO of table: TV_TAX_ITEM</p>
 * <p>Description: Data Access Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:04 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dao.vm timestamp: 2007-04-06 08:30:00
 ******************************************************
 * <p> <b>change record</b><br>
 *  make dao methods simply.<br>
 *  especially make update,delete methods simply.<br>
 *  remove "..withCheck" method,withCheck will impl in JAFOrmTemplate.<br>
 *  remove "delete(IDto _dto,..)" method.<br></p>
 * @author win7
 */

public class TvTaxItemDao  implements IDao
{


    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO TV_TAX_ITEM ("
          + "S_SEQ,I_PROJECTID,I_DETAILNO,S_TAXSUBJECTCODE,S_TAXSUBJECTNAME"
          + ",I_TAXNUMBER,F_TAXAMT,F_TAXRATE,F_EXPTAXAMT,F_DISCOUNTTAXAMT"
          + ",F_REALAMT,TS_UPDATE"
        + ") VALUES ("
        + "?,?,?,?,?,?,?,?,?,?,?,?)";


    private static final String SQL_INSERT_WITH_RESULT = "SELECT * FROM FINAL TABLE( " + SQL_INSERT + " )";
    
    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "TV_TAX_ITEM.S_SEQ, TV_TAX_ITEM.I_PROJECTID, TV_TAX_ITEM.I_DETAILNO, TV_TAX_ITEM.S_TAXSUBJECTCODE, TV_TAX_ITEM.S_TAXSUBJECTNAME, "
        + "TV_TAX_ITEM.I_TAXNUMBER, TV_TAX_ITEM.F_TAXAMT, TV_TAX_ITEM.F_TAXRATE, TV_TAX_ITEM.F_EXPTAXAMT, TV_TAX_ITEM.F_DISCOUNTTAXAMT, "
        + "TV_TAX_ITEM.F_REALAMT, TV_TAX_ITEM.TS_UPDATE "
        + "FROM TV_TAX_ITEM "
        +" WHERE " 
        + "S_SEQ = ? AND I_PROJECTID = ? AND I_DETAILNO = ?"
        ;
    /* SQL to select for update data */
    private static final String SQL_SELECT_FOR_UPDATE =
        "SELECT "
        + "TV_TAX_ITEM.S_SEQ, TV_TAX_ITEM.I_PROJECTID, TV_TAX_ITEM.I_DETAILNO, TV_TAX_ITEM.S_TAXSUBJECTCODE, TV_TAX_ITEM.S_TAXSUBJECTNAME, "
        + "TV_TAX_ITEM.I_TAXNUMBER, TV_TAX_ITEM.F_TAXAMT, TV_TAX_ITEM.F_TAXRATE, TV_TAX_ITEM.F_EXPTAXAMT, TV_TAX_ITEM.F_DISCOUNTTAXAMT, "
        + "TV_TAX_ITEM.F_REALAMT, TV_TAX_ITEM.TS_UPDATE "
        + "FROM TV_TAX_ITEM "
        +" WHERE " 
        + "S_SEQ = ? AND I_PROJECTID = ? AND I_DETAILNO = ? FOR UPDATE"
        ;

      /* SQL to select data (SCROLLABLE)*/
     private static final String SQL_SELECT_BATCH_SCROLLABLE =
        "SELECT "
        + "  TV_TAX_ITEM.S_SEQ  , TV_TAX_ITEM.I_PROJECTID  , TV_TAX_ITEM.I_DETAILNO  , TV_TAX_ITEM.S_TAXSUBJECTCODE  , TV_TAX_ITEM.S_TAXSUBJECTNAME "
        + " , TV_TAX_ITEM.I_TAXNUMBER  , TV_TAX_ITEM.F_TAXAMT  , TV_TAX_ITEM.F_TAXRATE  , TV_TAX_ITEM.F_EXPTAXAMT  , TV_TAX_ITEM.F_DISCOUNTTAXAMT "
        + " , TV_TAX_ITEM.F_REALAMT  , TV_TAX_ITEM.TS_UPDATE "
        + "FROM TV_TAX_ITEM ";



    /* SQL to select batch data */
    private static final String SQL_SELECT_BATCH =
        "SELECT "
        + "TV_TAX_ITEM.S_SEQ, TV_TAX_ITEM.I_PROJECTID, TV_TAX_ITEM.I_DETAILNO, TV_TAX_ITEM.S_TAXSUBJECTCODE, TV_TAX_ITEM.S_TAXSUBJECTNAME, "
        + "TV_TAX_ITEM.I_TAXNUMBER, TV_TAX_ITEM.F_TAXAMT, TV_TAX_ITEM.F_TAXRATE, TV_TAX_ITEM.F_EXPTAXAMT, TV_TAX_ITEM.F_DISCOUNTTAXAMT, "
        + "TV_TAX_ITEM.F_REALAMT, TV_TAX_ITEM.TS_UPDATE "
        + "FROM TV_TAX_ITEM " ;
        

   /* SQL to select batch data where condition  */
    private static final String SQL_SELECT_BATCH_WHERE =" ( "
        + "S_SEQ = ? AND I_PROJECTID = ? AND I_DETAILNO = ?)"
        ;


    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE TV_TAX_ITEM SET "
        + "S_TAXSUBJECTCODE =?,S_TAXSUBJECTNAME =?,I_TAXNUMBER =?,F_TAXAMT =?,F_TAXRATE =?, "
        + "F_EXPTAXAMT =?,F_DISCOUNTTAXAMT =?,F_REALAMT =?,TS_UPDATE =? "
        + "WHERE "
        + "S_SEQ = ? AND I_PROJECTID = ? AND I_DETAILNO = ?"
        ;

	/* SQL to update data, support LOB */
    private static final String SQL_UPDATE_LOB =
        "UPDATE TV_TAX_ITEM SET "
        + "S_TAXSUBJECTCODE =?, S_TAXSUBJECTNAME =?, I_TAXNUMBER =?, F_TAXAMT =?, F_TAXRATE =?,  "
        + "F_EXPTAXAMT =?, F_DISCOUNTTAXAMT =?, F_REALAMT =?, TS_UPDATE =? "
        + "WHERE "
        + "S_SEQ = ? AND I_PROJECTID = ? AND I_DETAILNO = ?"
        ;	
	
    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM TV_TAX_ITEM " 
        + " WHERE "
        + "S_SEQ = ? AND I_PROJECTID = ? AND I_DETAILNO = ?"
        ;


	/**
	*  批量查询 一次最多查询的参数数量
	*/
	
	public static final int FIND_BATCH_SIZE = 150  / 3;
	



   /**
   * Create a new record in Database.
   */
  public void create(IDto _dto,  Connection conn) throws SQLException
  {
     TvTaxItemDto dto = (TvTaxItemDto)_dto ;
     String msgValid = dto.checkValid() ;
     if (msgValid != null)
     	throw new SQLException("插入错误，"+msgValid) ;

     PreparedStatement ps = null;
     try
     {
         ps = conn.prepareStatement(SQL_INSERT);
          ps.setString(1, dto.getSseq());

          if (dto.getIprojectid()==null)
            ps.setNull(2, java.sql.Types.INTEGER);
         else
            ps.setInt(2, dto.getIprojectid().intValue());
          if (dto.getIdetailno()==null)
            ps.setNull(3, java.sql.Types.INTEGER);
         else
            ps.setInt(3, dto.getIdetailno().intValue());
          ps.setString(4, dto.getStaxsubjectcode());

          ps.setString(5, dto.getStaxsubjectname());

          if (dto.getItaxnumber()==null)
            ps.setNull(6, java.sql.Types.INTEGER);
         else
            ps.setInt(6, dto.getItaxnumber().intValue());
          ps.setBigDecimal(7, dto.getFtaxamt());

          ps.setBigDecimal(8, dto.getFtaxrate());

          ps.setBigDecimal(9, dto.getFexptaxamt());

          ps.setBigDecimal(10, dto.getFdiscounttaxamt());

          ps.setBigDecimal(11, dto.getFrealamt());

          ps.setTimestamp(12, dto.getTsupdate());

         ps.executeUpdate();
     }
     finally
     {
         close(ps);
     }
     return  ;
  }

   /**
   * Create a new record in Database. and return result, only used when having generated key
   */
   public IDto createWithResult(IDto _dto,  Connection conn) throws SQLException
   {
       TvTaxItemDto dto = (TvTaxItemDto)_dto ;
       String msgValid = dto.checkValid() ;
       if (msgValid != null)
           throw new SQLException("插入错误，"+msgValid) ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try
       {
           ps = conn.prepareStatement(SQL_INSERT_WITH_RESULT);
            ps.setString(1, dto.getSseq());
            if (dto.getIprojectid()==null)
              ps.setNull(2, java.sql.Types.INTEGER);
           else
              ps.setInt(2, dto.getIprojectid().intValue());
            if (dto.getIdetailno()==null)
              ps.setNull(3, java.sql.Types.INTEGER);
           else
              ps.setInt(3, dto.getIdetailno().intValue());
            ps.setString(4, dto.getStaxsubjectcode());
            ps.setString(5, dto.getStaxsubjectname());
            if (dto.getItaxnumber()==null)
              ps.setNull(6, java.sql.Types.INTEGER);
           else
              ps.setInt(6, dto.getItaxnumber().intValue());
            ps.setBigDecimal(7, dto.getFtaxamt());
            ps.setBigDecimal(8, dto.getFtaxrate());
            ps.setBigDecimal(9, dto.getFexptaxamt());
            ps.setBigDecimal(10, dto.getFdiscounttaxamt());
            ps.setBigDecimal(11, dto.getFrealamt());
            ps.setTimestamp(12, dto.getTsupdate());
           rs = ps.executeQuery();
           List results = getResults(rs);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }
        finally
        {
           close(ps);
           close(rs);
        }
   }

 	/**
	* Create batch new record in Database. it only create the first layer dto
	*/
    public void create(IDto[] _dtos, Connection conn)    throws SQLException
    {
        TvTaxItemDto dto  ;
     	for (int i= 0; i< _dtos.length ; i++)
 	    {
 		    dto  = (TvTaxItemDto)_dtos[i] ; 
    	    String msgValid = dto.checkValid() ;
        	if (msgValid != null)
     	    	throw new SQLException("插入错误，"+msgValid) ;
     	}
 	    PreparedStatement ps = null;
        try
        {
            ps = conn.prepareStatement(SQL_INSERT);
       
     	    for (int i= 0; i< _dtos.length ; i++)
     	    {
 	    	    dto  = (TvTaxItemDto)_dtos[i] ; 
  
               ps.setString(1, dto.getSseq());
  
               if (dto.getIprojectid()==null)
                  ps.setNull(2, java.sql.Types.INTEGER);
               else
                  ps.setInt(2, dto.getIprojectid().intValue());
  
               if (dto.getIdetailno()==null)
                  ps.setNull(3, java.sql.Types.INTEGER);
               else
                  ps.setInt(3, dto.getIdetailno().intValue());
  
               ps.setString(4, dto.getStaxsubjectcode());
  
               ps.setString(5, dto.getStaxsubjectname());
  
               if (dto.getItaxnumber()==null)
                  ps.setNull(6, java.sql.Types.INTEGER);
               else
                  ps.setInt(6, dto.getItaxnumber().intValue());
  
               ps.setBigDecimal(7, dto.getFtaxamt());
  
               ps.setBigDecimal(8, dto.getFtaxrate());
  
               ps.setBigDecimal(9, dto.getFexptaxamt());
  
               ps.setBigDecimal(10, dto.getFdiscounttaxamt());
  
               ps.setBigDecimal(11, dto.getFrealamt());
  
               ps.setTimestamp(12, dto.getTsupdate());
               ps.addBatch(); 
           }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }
        return  ;
   }




     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto find(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TvTaxItemPK pk = (TvTaxItemPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT);
           ps.setString(1, pk.getSseq());


           if (pk.getIprojectid()==null)
               ps.setNull(2, java.sql.Types.INTEGER);
           else
               ps.setInt(2, pk.getIprojectid().intValue());


           if (pk.getIdetailno()==null)
               ps.setNull(3, java.sql.Types.INTEGER);
           else
               ps.setInt(3, pk.getIdetailno().intValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }

     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto findForUpdate(IPK _pk, Connection conn, boolean isLobSupport) throws SQLException
    {
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return null ;
        //	throw new SQLException("查找错误，"+msgValid) ;
       }
        	
       TvTaxItemPK pk = (TvTaxItemPK)_pk ;

       PreparedStatement ps = null;
       ResultSet rs = null;
       try {
           ps = conn.prepareStatement(SQL_SELECT_FOR_UPDATE);
           ps.setString(1, pk.getSseq());


           if (pk.getIprojectid()==null)
               ps.setNull(2, java.sql.Types.INTEGER);
           else
               ps.setInt(2, pk.getIprojectid().intValue());


           if (pk.getIdetailno()==null)
               ps.setNull(3, java.sql.Types.INTEGER);
           else
               ps.setInt(3, pk.getIdetailno().intValue());

           rs = ps.executeQuery();
           List results = getResults(rs,0,isLobSupport);
           if (results!=null && results.size() > 0)
               return (IDto)results.get(0);
           else
               return null;
        }finally {
           close(rs);
           close(ps);
        }
    }
  
     /**
     * Retrive a record from Database.
     * (the statement below is somewhat redundant, but doesnot matter)
     */
    public IDto[] find(IPK[] _pks, Connection conn, boolean isLobSupport) throws SQLException
    {
        TvTaxItemPK pk ;
        
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TvTaxItemPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 
        PreparedStatement ps = null;
        ResultSet rs = null;
        
         
        List results = new ArrayList();  
		for (int iBegin = 0; iBegin < pks.size(); iBegin += FIND_BATCH_SIZE)   //
		{
        
            try {
          		int iFindBatchSize = pks.size() - iBegin ;
	    		if (iFindBatchSize >FIND_BATCH_SIZE )
		    		iFindBatchSize = FIND_BATCH_SIZE ;
		  
        	    StringBuffer sb = new StringBuffer() ;
            	sb.append(SQL_SELECT_BATCH).append(" WHERE ").append(SQL_SELECT_BATCH_WHERE);

	    		for (int i = iBegin+1; i < iBegin + iFindBatchSize; i++)
		    	{
			    	sb.append("OR").append(SQL_SELECT_BATCH_WHERE) ;
    			}
        	
                ps = conn.prepareStatement(sb.toString());

                for (int i = iBegin;i < iBegin + iFindBatchSize; i++)
                {
                    pk  = (TvTaxItemPK)(pks.get(i)) ; 
                   ps.setString((i-iBegin)*3+1, pk.getSseq());

                   if (pk.getIprojectid()==null)
                      ps.setNull((i-iBegin)*3+ 2 , java.sql.Types.INTEGER);
                   else
                     ps.setInt((i-iBegin)*3+2, pk.getIprojectid().intValue());

                   if (pk.getIdetailno()==null)
                      ps.setNull((i-iBegin)*3+ 3 , java.sql.Types.INTEGER);
                   else
                     ps.setInt((i-iBegin)*3+3, pk.getIdetailno().intValue());

			
	            }
                rs = ps.executeQuery();
                results.addAll(getResults(rs,0,isLobSupport)); //
            }finally {
                close(rs);
                close(ps);
            }
        }
        if (results!=null && results.size() > 0)
        {
            TvTaxItemDto[] dtos = new TvTaxItemDto[0];
		    dtos = (TvTaxItemDto[]) results.toArray(dtos) ;
		    return dtos ;
        }
        else
        {
            return null;
        }
    }

  
  
  



    /**
	    * 得到查询语句
	    */
    public String getSelectSQL() 
    {
	        return SQL_SELECT_BATCH_SCROLLABLE ;
    }
   

	public List getResults(ResultSet rs) throws SQLException
    {
    	return getResults(rs, 0) ;
    }
  

    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize) throws SQLException
    {
		return getResults(rs,maxSize,false);
	}
    /**
     * Populate the ResultSet.
     */
    public List getResults(ResultSet rs, int maxSize, boolean isLobSupport) throws SQLException
    {
        List results = new ArrayList();
        String str ;
        Reader reader;
        Clob clob;
        char[] chars ;
        
        while (rs.next())
         {
             TvTaxItemDto  dto = new  TvTaxItemDto ();
             //S_SEQ
             str = rs.getString("S_SEQ");
             if (str == null)
                dto.setSseq(null);
             else
                dto.setSseq(str.trim());

             //I_PROJECTID
             str = rs.getString("I_PROJECTID");
             if(str!=null){
                dto.setIprojectid(new Integer(str));
             }

             //I_DETAILNO
             str = rs.getString("I_DETAILNO");
             if(str!=null){
                dto.setIdetailno(new Integer(str));
             }

             //S_TAXSUBJECTCODE
             str = rs.getString("S_TAXSUBJECTCODE");
             if (str == null)
                dto.setStaxsubjectcode(null);
             else
                dto.setStaxsubjectcode(str.trim());

             //S_TAXSUBJECTNAME
             str = rs.getString("S_TAXSUBJECTNAME");
             if (str == null)
                dto.setStaxsubjectname(null);
             else
                dto.setStaxsubjectname(str.trim());

             //I_TAXNUMBER
             str = rs.getString("I_TAXNUMBER");
             if(str!=null){
                dto.setItaxnumber(new Integer(str));
             }

             //F_TAXAMT
           dto.setFtaxamt(rs.getBigDecimal("F_TAXAMT"));

             //F_TAXRATE
           dto.setFtaxrate(rs.getBigDecimal("F_TAXRATE"));

             //F_EXPTAXAMT
           dto.setFexptaxamt(rs.getBigDecimal("F_EXPTAXAMT"));

             //F_DISCOUNTTAXAMT
           dto.setFdiscounttaxamt(rs.getBigDecimal("F_DISCOUNTTAXAMT"));

             //F_REALAMT
           dto.setFrealamt(rs.getBigDecimal("F_REALAMT"));

             //TS_UPDATE
           dto.setTsupdate(rs.getTimestamp("TS_UPDATE"));



            results.add(dto);
            
            if(maxSize >0  && results.size() == maxSize)
            {
            	break ;
            }
            
         }
        
		return results ;
    }

  /**
   * populate resultSet as cclass
   */
  protected IDto[] getChildrenResults(ResultSet rs ,Class _dto) throws SQLException{

      throw new SQLException("本dto没有与其它dto相关联，无法应用此方法");
  }


     /**
     * Update a record in Database.
     */

    public void update(IDto _dto, Connection conn, boolean isLobSupport) throws SQLException
    {
        String msgValid = _dto.checkValid() ;
        if (msgValid != null)
            throw new SQLException("修改错误，"+msgValid) ;
        TvTaxItemDto dto = (TvTaxItemDto)_dto ;
        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            int pos = 1;
            //S_TAXSUBJECTCODE
            ps.setString(pos, dto.getStaxsubjectcode());
            pos++;

            //S_TAXSUBJECTNAME
            ps.setString(pos, dto.getStaxsubjectname());
            pos++;

            //I_TAXNUMBER
            if (dto.getItaxnumber()==null)
                ps.setNull(pos, java.sql.Types.INTEGER);
            else
                ps.setInt(pos, dto.getItaxnumber().intValue());
            pos++;

            //F_TAXAMT
            ps.setBigDecimal(pos, dto.getFtaxamt());
            pos++;

            //F_TAXRATE
            ps.setBigDecimal(pos, dto.getFtaxrate());
            pos++;

            //F_EXPTAXAMT
            ps.setBigDecimal(pos, dto.getFexptaxamt());
            pos++;

            //F_DISCOUNTTAXAMT
            ps.setBigDecimal(pos, dto.getFdiscounttaxamt());
            pos++;

            //F_REALAMT
            ps.setBigDecimal(pos, dto.getFrealamt());
            pos++;

            //TS_UPDATE
            ps.setTimestamp(pos, dto.getTsupdate());
            pos++;


           //S_SEQ
           ps.setString(pos, dto.getSseq());
           pos++;
           //I_PROJECTID
           ps.setInt(pos, dto.getIprojectid().intValue());
           pos++;
           //I_DETAILNO
           ps.setInt(pos, dto.getIdetailno().intValue());
           pos++;
           ps.executeUpdate();
        }
        finally
        {
           close(ps);
        }

        return ;
    }
    
    
    
      /**
     * Update batch record in Database.
     */

    public void update(IDto[] _dtos, Connection conn, boolean isLobSupport) throws SQLException
    {
     
     	 TvTaxItemDto dto  ;
         for (int i= 0; i< _dtos.length ; i++)
         {
            dto  = (TvTaxItemDto)_dtos[i] ; 
            String msgValid = dto.checkValid() ;
            if (msgValid != null)
                throw new SQLException("修改错误，"+msgValid) ;
         }

        PreparedStatement ps = null;
        try {
            if(isLobSupport){
                ps = conn.prepareStatement(SQL_UPDATE_LOB);
            }
            else{
                ps = conn.prepareStatement(SQL_UPDATE);
            }
            
            for (int i= 0; i< _dtos.length ; i++)
            {
                dto  = (TvTaxItemDto)_dtos[i] ; 
                int pos = 1;
                //S_TAXSUBJECTCODE
                 ps.setString(pos, dto.getStaxsubjectcode());
                pos++;

                //S_TAXSUBJECTNAME
                 ps.setString(pos, dto.getStaxsubjectname());
                pos++;

                //I_TAXNUMBER
                 if (dto.getItaxnumber()==null)
                   ps.setNull(pos, java.sql.Types.INTEGER);
                else
                   ps.setInt(pos, dto.getItaxnumber().intValue());
                pos++ ;

                //F_TAXAMT
                 ps.setBigDecimal(pos, dto.getFtaxamt());
                pos++;

                //F_TAXRATE
                 ps.setBigDecimal(pos, dto.getFtaxrate());
                pos++;

                //F_EXPTAXAMT
                 ps.setBigDecimal(pos, dto.getFexptaxamt());
                pos++;

                //F_DISCOUNTTAXAMT
                 ps.setBigDecimal(pos, dto.getFdiscounttaxamt());
                pos++;

                //F_REALAMT
                 ps.setBigDecimal(pos, dto.getFrealamt());
                pos++;

                //TS_UPDATE
                 ps.setTimestamp(pos, dto.getTsupdate());
                pos++;


               //S_SEQ
               ps.setString(pos, dto.getSseq());
               pos++;
               //I_PROJECTID
               ps.setInt(pos, dto.getIprojectid().intValue());
               pos++;
               //I_DETAILNO
               ps.setInt(pos, dto.getIdetailno().intValue());
               pos++;
		       ps.addBatch(); 
	       }
	
           ps.executeBatch();
        }
        finally
        {
           close(ps);
        }

        return ;
    }



    /**
     * delete a record in Database.
     */
    public void delete(IPK _pk, Connection conn) throws SQLException
    {
       
      
       String msgValid = _pk.checkValid() ;
       if (msgValid != null)
       {
       		return ;
        //	throw new SQLException("删除错误，"+msgValid) ;
       }
       TvTaxItemPK pk = (TvTaxItemPK)_pk ;


       PreparedStatement ps = null;
       try {
           ps = conn.prepareStatement(SQL_DELETE);
           ps.setString(1, pk.getSseq());
           ps.setInt(2, pk.getIprojectid().intValue());
           ps.setInt(3, pk.getIdetailno().intValue());
           ps.executeUpdate();
        }
        finally
        {
            close(ps);
        }
    }


     /**
     * delete batch record in Database.
     */
    public void delete(IPK[] _pks, Connection conn) throws SQLException
    {
        TvTaxItemPK pk ;
        List pks = new ArrayList();  
	  
		for (int i= 0; i< _pks.length ; i++)
 		{
 			pk  = (TvTaxItemPK)_pks[i] ; 
	    	String msgValid = pk.checkValid() ;
    		if (msgValid == null)
    		{
	    		pks.add(pk) ;
     		}
 		}
 		
 		
        PreparedStatement ps = null;
        try
         {
            ps = conn.prepareStatement(SQL_DELETE);
             
       		for (int i= 0; i< pks.size() ; i++)
       		{
       			pk  = (TvTaxItemPK)(pks.get(i)) ; 
                ps.setString(1, pk.getSseq());
                ps.setInt(2, pk.getIprojectid().intValue());
                ps.setInt(3, pk.getIdetailno().intValue());
		        ps.addBatch() ;
			}
            ps.executeBatch();
        }
        finally
        {
            close(ps);
        }      
    }



    /**
    * Check IChangerNumber or UpdateTimeStamp.
    */
    public void check(IDto _dto, Connection conn) throws SQLException
    {
                           		throw new SQLException("数据库表：TV_TAX_ITEM没有检查修改的字段");
    }


	/**
	* synchronize values between parent and children
	*/
    public void syncToChildren(IDto _dto)     throws SQLException{
       throw new SQLException("本记录没有与其它记录相关联，无法进行主记录与明细记录之间的数据同步。");
  }

	/**
	*get children
	*/
    public IDto[] findChildren (IDto _dto, Connection conn, boolean isLobSupport)     throws SQLException{
         throw new SQLException("本dto没有与其它dto相关联，无法得到子dto");
  }    
    
  /**
   *return the children IDto class
   * @return Class
   */
  public Class getChildrenClass(){
	  return null;
  };    



    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    private void close(Statement stmt)
    {
        if (stmt != null)
        {
            try
            {
                stmt.close();
            }
            catch(SQLException    e)
            {}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    private void close(ResultSet rs)
    {
        if (rs != null)
        {
            try
            {
                rs.close();
            }catch(SQLException  e){}
        }
    }
}
