    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.HtvFreePK;
/**
 * <p>Title: DTO of table: HTV_FREE</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:56 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class HtvFreeDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  I_VOUSRLNO BIGINT , PK   , NOT NULL  , Identity  , Generated     */
    protected Long ivousrlno;
    /**
    *  S_TAXORGCODE VARCHAR   , NOT NULL       */
    protected String staxorgcode;
    /**
    *  S_PACKNO CHARACTER   , NOT NULL       */
    protected String spackno;
    /**
    *  S_TRANO CHARACTER         */
    protected String strano;
    /**
    *  D_BILLDATE DATE   , NOT NULL       */
    protected Date dbilldate;
    /**
    *  S_ELECTROTAXVOUNO VARCHAR         */
    protected String selectrotaxvouno;
    /**
    *  S_FREEVOUNO CHARACTER   , NOT NULL       */
    protected String sfreevouno;
    /**
    *  C_FREEPLUTYPE CHARACTER   , NOT NULL       */
    protected String cfreeplutype;
    /**
    *  S_FREEPLUSUBJECTCODE VARCHAR   , NOT NULL       */
    protected String sfreeplusubjectcode;
    /**
    *  C_FREEPLULEVEL CHARACTER   , NOT NULL       */
    protected String cfreeplulevel;
    /**
    *  S_FREEPLUSIGN CHARACTER         */
    protected String sfreeplusign;
    /**
    *  S_FREEPLUPTRECODE CHARACTER   , NOT NULL       */
    protected String sfreepluptrecode;
    /**
    *  F_FREEPLUAMT DECIMAL   , NOT NULL       */
    protected BigDecimal ffreepluamt;
    /**
    *  C_FREEMIKIND CHARACTER   , NOT NULL       */
    protected String cfreemikind;
    /**
    *  S_FREEMISUBJECT VARCHAR   , NOT NULL       */
    protected String sfreemisubject;
    /**
    *  C_FREEMILEVEL CHARACTER   , NOT NULL       */
    protected String cfreemilevel;
    /**
    *  S_FREEMISIGN CHARACTER         */
    protected String sfreemisign;
    /**
    *  S_FREEMIPTRE CHARACTER   , NOT NULL       */
    protected String sfreemiptre;
    /**
    *  F_FREEMIAMT DECIMAL   , NOT NULL       */
    protected BigDecimal ffreemiamt;
    /**
    *  S_CORPCODE CHARACTER         */
    protected String scorpcode;
    /**
    *  C_TRIMSIGN CHARACTER   , NOT NULL       */
    protected String ctrimsign;
    /**
    *  S_STATUS CHARACTER         */
    protected String sstatus;
    /**
    *  S_FILENAME VARCHAR   , NOT NULL       */
    protected String sfilename;
    /**
    *  S_BOOKORGCODE CHARACTER   , NOT NULL       */
    protected String sbookorgcode;
    /**
    *  TS_SYSUPDATE TIMESTAMP         */
    protected Timestamp tssysupdate;
    /**
    *  D_ACCEPTDATE DATE   , NOT NULL       */
    protected Date dacceptdate;
    /**
    *  D_AUDITDATE DATE         */
    protected Date dauditdate;
    /**
    *  S_CHANNELCODE VARCHAR         */
    protected String schannelcode;
    /**
    *  S_ADDWORD VARCHAR         */
    protected String saddword;
    /**
    *  TS_UPDATE TIMESTAMP   , NOT NULL       */
    protected Timestamp tsupdate;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public Long getIvousrlno()
    {
        return ivousrlno;
    }
     /**
     *   Setter I_VOUSRLNO, PK , NOT NULL  , Identity  , Generated      * */
    public void setIvousrlno(Long _ivousrlno) {
        this.ivousrlno = _ivousrlno;
    }


    public String getStaxorgcode()
    {
        return staxorgcode;
    }
     /**
     *   Setter S_TAXORGCODE , NOT NULL        * */
    public void setStaxorgcode(String _staxorgcode) {
        this.staxorgcode = _staxorgcode;
    }


    public String getSpackno()
    {
        return spackno;
    }
     /**
     *   Setter S_PACKNO , NOT NULL        * */
    public void setSpackno(String _spackno) {
        this.spackno = _spackno;
    }


    public String getStrano()
    {
        return strano;
    }
     /**
     *   Setter S_TRANO        * */
    public void setStrano(String _strano) {
        this.strano = _strano;
    }


    public Date getDbilldate()
    {
        return dbilldate;
    }
     /**
     *   Setter D_BILLDATE , NOT NULL        * */
    public void setDbilldate(Date _dbilldate) {
        this.dbilldate = _dbilldate;
    }


    public String getSelectrotaxvouno()
    {
        return selectrotaxvouno;
    }
     /**
     *   Setter S_ELECTROTAXVOUNO        * */
    public void setSelectrotaxvouno(String _selectrotaxvouno) {
        this.selectrotaxvouno = _selectrotaxvouno;
    }


    public String getSfreevouno()
    {
        return sfreevouno;
    }
     /**
     *   Setter S_FREEVOUNO , NOT NULL        * */
    public void setSfreevouno(String _sfreevouno) {
        this.sfreevouno = _sfreevouno;
    }


    public String getCfreeplutype()
    {
        return cfreeplutype;
    }
     /**
     *   Setter C_FREEPLUTYPE , NOT NULL        * */
    public void setCfreeplutype(String _cfreeplutype) {
        this.cfreeplutype = _cfreeplutype;
    }


    public String getSfreeplusubjectcode()
    {
        return sfreeplusubjectcode;
    }
     /**
     *   Setter S_FREEPLUSUBJECTCODE , NOT NULL        * */
    public void setSfreeplusubjectcode(String _sfreeplusubjectcode) {
        this.sfreeplusubjectcode = _sfreeplusubjectcode;
    }


    public String getCfreeplulevel()
    {
        return cfreeplulevel;
    }
     /**
     *   Setter C_FREEPLULEVEL , NOT NULL        * */
    public void setCfreeplulevel(String _cfreeplulevel) {
        this.cfreeplulevel = _cfreeplulevel;
    }


    public String getSfreeplusign()
    {
        return sfreeplusign;
    }
     /**
     *   Setter S_FREEPLUSIGN        * */
    public void setSfreeplusign(String _sfreeplusign) {
        this.sfreeplusign = _sfreeplusign;
    }


    public String getSfreepluptrecode()
    {
        return sfreepluptrecode;
    }
     /**
     *   Setter S_FREEPLUPTRECODE , NOT NULL        * */
    public void setSfreepluptrecode(String _sfreepluptrecode) {
        this.sfreepluptrecode = _sfreepluptrecode;
    }


    public BigDecimal getFfreepluamt()
    {
        return ffreepluamt;
    }
     /**
     *   Setter F_FREEPLUAMT , NOT NULL        * */
    public void setFfreepluamt(BigDecimal _ffreepluamt) {
        this.ffreepluamt = _ffreepluamt;
    }


    public String getCfreemikind()
    {
        return cfreemikind;
    }
     /**
     *   Setter C_FREEMIKIND , NOT NULL        * */
    public void setCfreemikind(String _cfreemikind) {
        this.cfreemikind = _cfreemikind;
    }


    public String getSfreemisubject()
    {
        return sfreemisubject;
    }
     /**
     *   Setter S_FREEMISUBJECT , NOT NULL        * */
    public void setSfreemisubject(String _sfreemisubject) {
        this.sfreemisubject = _sfreemisubject;
    }


    public String getCfreemilevel()
    {
        return cfreemilevel;
    }
     /**
     *   Setter C_FREEMILEVEL , NOT NULL        * */
    public void setCfreemilevel(String _cfreemilevel) {
        this.cfreemilevel = _cfreemilevel;
    }


    public String getSfreemisign()
    {
        return sfreemisign;
    }
     /**
     *   Setter S_FREEMISIGN        * */
    public void setSfreemisign(String _sfreemisign) {
        this.sfreemisign = _sfreemisign;
    }


    public String getSfreemiptre()
    {
        return sfreemiptre;
    }
     /**
     *   Setter S_FREEMIPTRE , NOT NULL        * */
    public void setSfreemiptre(String _sfreemiptre) {
        this.sfreemiptre = _sfreemiptre;
    }


    public BigDecimal getFfreemiamt()
    {
        return ffreemiamt;
    }
     /**
     *   Setter F_FREEMIAMT , NOT NULL        * */
    public void setFfreemiamt(BigDecimal _ffreemiamt) {
        this.ffreemiamt = _ffreemiamt;
    }


    public String getScorpcode()
    {
        return scorpcode;
    }
     /**
     *   Setter S_CORPCODE        * */
    public void setScorpcode(String _scorpcode) {
        this.scorpcode = _scorpcode;
    }


    public String getCtrimsign()
    {
        return ctrimsign;
    }
     /**
     *   Setter C_TRIMSIGN , NOT NULL        * */
    public void setCtrimsign(String _ctrimsign) {
        this.ctrimsign = _ctrimsign;
    }


    public String getSstatus()
    {
        return sstatus;
    }
     /**
     *   Setter S_STATUS        * */
    public void setSstatus(String _sstatus) {
        this.sstatus = _sstatus;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME , NOT NULL        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getSbookorgcode()
    {
        return sbookorgcode;
    }
     /**
     *   Setter S_BOOKORGCODE , NOT NULL        * */
    public void setSbookorgcode(String _sbookorgcode) {
        this.sbookorgcode = _sbookorgcode;
    }


    public Timestamp getTssysupdate()
    {
        return tssysupdate;
    }
     /**
     *   Setter TS_SYSUPDATE        * */
    public void setTssysupdate(Timestamp _tssysupdate) {
        this.tssysupdate = _tssysupdate;
    }


    public Date getDacceptdate()
    {
        return dacceptdate;
    }
     /**
     *   Setter D_ACCEPTDATE , NOT NULL        * */
    public void setDacceptdate(Date _dacceptdate) {
        this.dacceptdate = _dacceptdate;
    }


    public Date getDauditdate()
    {
        return dauditdate;
    }
     /**
     *   Setter D_AUDITDATE        * */
    public void setDauditdate(Date _dauditdate) {
        this.dauditdate = _dauditdate;
    }


    public String getSchannelcode()
    {
        return schannelcode;
    }
     /**
     *   Setter S_CHANNELCODE        * */
    public void setSchannelcode(String _schannelcode) {
        this.schannelcode = _schannelcode;
    }


    public String getSaddword()
    {
        return saddword;
    }
     /**
     *   Setter S_ADDWORD        * */
    public void setSaddword(String _saddword) {
        this.saddword = _saddword;
    }


    public Timestamp getTsupdate()
    {
        return tsupdate;
    }
     /**
     *   Setter TS_UPDATE , NOT NULL        * */
    public void setTsupdate(Timestamp _tsupdate) {
        this.tsupdate = _tsupdate;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter I_VOUSRLNO, PK , NOT NULL  , Identity  , Generated     * */
    public static String  columnIvousrlno()
    {
        return "I_VOUSRLNO";
    }
   
    /**
    *   Getter S_TAXORGCODE , NOT NULL       * */
    public static String  columnStaxorgcode()
    {
        return "S_TAXORGCODE";
    }
   
    /**
    *   Getter S_PACKNO , NOT NULL       * */
    public static String  columnSpackno()
    {
        return "S_PACKNO";
    }
   
    /**
    *   Getter S_TRANO       * */
    public static String  columnStrano()
    {
        return "S_TRANO";
    }
   
    /**
    *   Getter D_BILLDATE , NOT NULL       * */
    public static String  columnDbilldate()
    {
        return "D_BILLDATE";
    }
   
    /**
    *   Getter S_ELECTROTAXVOUNO       * */
    public static String  columnSelectrotaxvouno()
    {
        return "S_ELECTROTAXVOUNO";
    }
   
    /**
    *   Getter S_FREEVOUNO , NOT NULL       * */
    public static String  columnSfreevouno()
    {
        return "S_FREEVOUNO";
    }
   
    /**
    *   Getter C_FREEPLUTYPE , NOT NULL       * */
    public static String  columnCfreeplutype()
    {
        return "C_FREEPLUTYPE";
    }
   
    /**
    *   Getter S_FREEPLUSUBJECTCODE , NOT NULL       * */
    public static String  columnSfreeplusubjectcode()
    {
        return "S_FREEPLUSUBJECTCODE";
    }
   
    /**
    *   Getter C_FREEPLULEVEL , NOT NULL       * */
    public static String  columnCfreeplulevel()
    {
        return "C_FREEPLULEVEL";
    }
   
    /**
    *   Getter S_FREEPLUSIGN       * */
    public static String  columnSfreeplusign()
    {
        return "S_FREEPLUSIGN";
    }
   
    /**
    *   Getter S_FREEPLUPTRECODE , NOT NULL       * */
    public static String  columnSfreepluptrecode()
    {
        return "S_FREEPLUPTRECODE";
    }
   
    /**
    *   Getter F_FREEPLUAMT , NOT NULL       * */
    public static String  columnFfreepluamt()
    {
        return "F_FREEPLUAMT";
    }
   
    /**
    *   Getter C_FREEMIKIND , NOT NULL       * */
    public static String  columnCfreemikind()
    {
        return "C_FREEMIKIND";
    }
   
    /**
    *   Getter S_FREEMISUBJECT , NOT NULL       * */
    public static String  columnSfreemisubject()
    {
        return "S_FREEMISUBJECT";
    }
   
    /**
    *   Getter C_FREEMILEVEL , NOT NULL       * */
    public static String  columnCfreemilevel()
    {
        return "C_FREEMILEVEL";
    }
   
    /**
    *   Getter S_FREEMISIGN       * */
    public static String  columnSfreemisign()
    {
        return "S_FREEMISIGN";
    }
   
    /**
    *   Getter S_FREEMIPTRE , NOT NULL       * */
    public static String  columnSfreemiptre()
    {
        return "S_FREEMIPTRE";
    }
   
    /**
    *   Getter F_FREEMIAMT , NOT NULL       * */
    public static String  columnFfreemiamt()
    {
        return "F_FREEMIAMT";
    }
   
    /**
    *   Getter S_CORPCODE       * */
    public static String  columnScorpcode()
    {
        return "S_CORPCODE";
    }
   
    /**
    *   Getter C_TRIMSIGN , NOT NULL       * */
    public static String  columnCtrimsign()
    {
        return "C_TRIMSIGN";
    }
   
    /**
    *   Getter S_STATUS       * */
    public static String  columnSstatus()
    {
        return "S_STATUS";
    }
   
    /**
    *   Getter S_FILENAME , NOT NULL       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_BOOKORGCODE , NOT NULL       * */
    public static String  columnSbookorgcode()
    {
        return "S_BOOKORGCODE";
    }
   
    /**
    *   Getter TS_SYSUPDATE       * */
    public static String  columnTssysupdate()
    {
        return "TS_SYSUPDATE";
    }
   
    /**
    *   Getter D_ACCEPTDATE , NOT NULL       * */
    public static String  columnDacceptdate()
    {
        return "D_ACCEPTDATE";
    }
   
    /**
    *   Getter D_AUDITDATE       * */
    public static String  columnDauditdate()
    {
        return "D_AUDITDATE";
    }
   
    /**
    *   Getter S_CHANNELCODE       * */
    public static String  columnSchannelcode()
    {
        return "S_CHANNELCODE";
    }
   
    /**
    *   Getter S_ADDWORD       * */
    public static String  columnSaddword()
    {
        return "S_ADDWORD";
    }
   
    /**
    *   Getter TS_UPDATE , NOT NULL       * */
    public static String  columnTsupdate()
    {
        return "TS_UPDATE";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "HTV_FREE";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[30];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="S_TAXORGCODE";
        columnNames[2]="S_PACKNO";
        columnNames[3]="S_TRANO";
        columnNames[4]="D_BILLDATE";
        columnNames[5]="S_ELECTROTAXVOUNO";
        columnNames[6]="S_FREEVOUNO";
        columnNames[7]="C_FREEPLUTYPE";
        columnNames[8]="S_FREEPLUSUBJECTCODE";
        columnNames[9]="C_FREEPLULEVEL";
        columnNames[10]="S_FREEPLUSIGN";
        columnNames[11]="S_FREEPLUPTRECODE";
        columnNames[12]="F_FREEPLUAMT";
        columnNames[13]="C_FREEMIKIND";
        columnNames[14]="S_FREEMISUBJECT";
        columnNames[15]="C_FREEMILEVEL";
        columnNames[16]="S_FREEMISIGN";
        columnNames[17]="S_FREEMIPTRE";
        columnNames[18]="F_FREEMIAMT";
        columnNames[19]="S_CORPCODE";
        columnNames[20]="C_TRIMSIGN";
        columnNames[21]="S_STATUS";
        columnNames[22]="S_FILENAME";
        columnNames[23]="S_BOOKORGCODE";
        columnNames[24]="TS_SYSUPDATE";
        columnNames[25]="D_ACCEPTDATE";
        columnNames[26]="D_AUDITDATE";
        columnNames[27]="S_CHANNELCODE";
        columnNames[28]="S_ADDWORD";
        columnNames[29]="TS_UPDATE";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof HtvFreeDto))
            return false;

        HtvFreeDto bean = (HtvFreeDto) obj;


      //compare field ivousrlno
      if((this.ivousrlno==null && bean.ivousrlno!=null) || (this.ivousrlno!=null && bean.ivousrlno==null))
          return false;
        else if(this.ivousrlno==null && bean.ivousrlno==null){
        }
        else{
          if(!bean.ivousrlno.equals(this.ivousrlno))
               return false;
     }
      //compare field staxorgcode
      if((this.staxorgcode==null && bean.staxorgcode!=null) || (this.staxorgcode!=null && bean.staxorgcode==null))
          return false;
        else if(this.staxorgcode==null && bean.staxorgcode==null){
        }
        else{
          if(!bean.staxorgcode.equals(this.staxorgcode))
               return false;
     }
      //compare field spackno
      if((this.spackno==null && bean.spackno!=null) || (this.spackno!=null && bean.spackno==null))
          return false;
        else if(this.spackno==null && bean.spackno==null){
        }
        else{
          if(!bean.spackno.equals(this.spackno))
               return false;
     }
      //compare field strano
      if((this.strano==null && bean.strano!=null) || (this.strano!=null && bean.strano==null))
          return false;
        else if(this.strano==null && bean.strano==null){
        }
        else{
          if(!bean.strano.equals(this.strano))
               return false;
     }
      //compare field dbilldate
      if((this.dbilldate==null && bean.dbilldate!=null) || (this.dbilldate!=null && bean.dbilldate==null))
          return false;
        else if(this.dbilldate==null && bean.dbilldate==null){
        }
        else{
          if(!bean.dbilldate.equals(this.dbilldate))
               return false;
     }
      //compare field selectrotaxvouno
      if((this.selectrotaxvouno==null && bean.selectrotaxvouno!=null) || (this.selectrotaxvouno!=null && bean.selectrotaxvouno==null))
          return false;
        else if(this.selectrotaxvouno==null && bean.selectrotaxvouno==null){
        }
        else{
          if(!bean.selectrotaxvouno.equals(this.selectrotaxvouno))
               return false;
     }
      //compare field sfreevouno
      if((this.sfreevouno==null && bean.sfreevouno!=null) || (this.sfreevouno!=null && bean.sfreevouno==null))
          return false;
        else if(this.sfreevouno==null && bean.sfreevouno==null){
        }
        else{
          if(!bean.sfreevouno.equals(this.sfreevouno))
               return false;
     }
      //compare field cfreeplutype
      if((this.cfreeplutype==null && bean.cfreeplutype!=null) || (this.cfreeplutype!=null && bean.cfreeplutype==null))
          return false;
        else if(this.cfreeplutype==null && bean.cfreeplutype==null){
        }
        else{
          if(!bean.cfreeplutype.equals(this.cfreeplutype))
               return false;
     }
      //compare field sfreeplusubjectcode
      if((this.sfreeplusubjectcode==null && bean.sfreeplusubjectcode!=null) || (this.sfreeplusubjectcode!=null && bean.sfreeplusubjectcode==null))
          return false;
        else if(this.sfreeplusubjectcode==null && bean.sfreeplusubjectcode==null){
        }
        else{
          if(!bean.sfreeplusubjectcode.equals(this.sfreeplusubjectcode))
               return false;
     }
      //compare field cfreeplulevel
      if((this.cfreeplulevel==null && bean.cfreeplulevel!=null) || (this.cfreeplulevel!=null && bean.cfreeplulevel==null))
          return false;
        else if(this.cfreeplulevel==null && bean.cfreeplulevel==null){
        }
        else{
          if(!bean.cfreeplulevel.equals(this.cfreeplulevel))
               return false;
     }
      //compare field sfreeplusign
      if((this.sfreeplusign==null && bean.sfreeplusign!=null) || (this.sfreeplusign!=null && bean.sfreeplusign==null))
          return false;
        else if(this.sfreeplusign==null && bean.sfreeplusign==null){
        }
        else{
          if(!bean.sfreeplusign.equals(this.sfreeplusign))
               return false;
     }
      //compare field sfreepluptrecode
      if((this.sfreepluptrecode==null && bean.sfreepluptrecode!=null) || (this.sfreepluptrecode!=null && bean.sfreepluptrecode==null))
          return false;
        else if(this.sfreepluptrecode==null && bean.sfreepluptrecode==null){
        }
        else{
          if(!bean.sfreepluptrecode.equals(this.sfreepluptrecode))
               return false;
     }
      //compare field ffreepluamt
      if((this.ffreepluamt==null && bean.ffreepluamt!=null) || (this.ffreepluamt!=null && bean.ffreepluamt==null))
          return false;
        else if(this.ffreepluamt==null && bean.ffreepluamt==null){
        }
        else{
          if(!bean.ffreepluamt.equals(this.ffreepluamt))
               return false;
     }
      //compare field cfreemikind
      if((this.cfreemikind==null && bean.cfreemikind!=null) || (this.cfreemikind!=null && bean.cfreemikind==null))
          return false;
        else if(this.cfreemikind==null && bean.cfreemikind==null){
        }
        else{
          if(!bean.cfreemikind.equals(this.cfreemikind))
               return false;
     }
      //compare field sfreemisubject
      if((this.sfreemisubject==null && bean.sfreemisubject!=null) || (this.sfreemisubject!=null && bean.sfreemisubject==null))
          return false;
        else if(this.sfreemisubject==null && bean.sfreemisubject==null){
        }
        else{
          if(!bean.sfreemisubject.equals(this.sfreemisubject))
               return false;
     }
      //compare field cfreemilevel
      if((this.cfreemilevel==null && bean.cfreemilevel!=null) || (this.cfreemilevel!=null && bean.cfreemilevel==null))
          return false;
        else if(this.cfreemilevel==null && bean.cfreemilevel==null){
        }
        else{
          if(!bean.cfreemilevel.equals(this.cfreemilevel))
               return false;
     }
      //compare field sfreemisign
      if((this.sfreemisign==null && bean.sfreemisign!=null) || (this.sfreemisign!=null && bean.sfreemisign==null))
          return false;
        else if(this.sfreemisign==null && bean.sfreemisign==null){
        }
        else{
          if(!bean.sfreemisign.equals(this.sfreemisign))
               return false;
     }
      //compare field sfreemiptre
      if((this.sfreemiptre==null && bean.sfreemiptre!=null) || (this.sfreemiptre!=null && bean.sfreemiptre==null))
          return false;
        else if(this.sfreemiptre==null && bean.sfreemiptre==null){
        }
        else{
          if(!bean.sfreemiptre.equals(this.sfreemiptre))
               return false;
     }
      //compare field ffreemiamt
      if((this.ffreemiamt==null && bean.ffreemiamt!=null) || (this.ffreemiamt!=null && bean.ffreemiamt==null))
          return false;
        else if(this.ffreemiamt==null && bean.ffreemiamt==null){
        }
        else{
          if(!bean.ffreemiamt.equals(this.ffreemiamt))
               return false;
     }
      //compare field scorpcode
      if((this.scorpcode==null && bean.scorpcode!=null) || (this.scorpcode!=null && bean.scorpcode==null))
          return false;
        else if(this.scorpcode==null && bean.scorpcode==null){
        }
        else{
          if(!bean.scorpcode.equals(this.scorpcode))
               return false;
     }
      //compare field ctrimsign
      if((this.ctrimsign==null && bean.ctrimsign!=null) || (this.ctrimsign!=null && bean.ctrimsign==null))
          return false;
        else if(this.ctrimsign==null && bean.ctrimsign==null){
        }
        else{
          if(!bean.ctrimsign.equals(this.ctrimsign))
               return false;
     }
      //compare field sstatus
      if((this.sstatus==null && bean.sstatus!=null) || (this.sstatus!=null && bean.sstatus==null))
          return false;
        else if(this.sstatus==null && bean.sstatus==null){
        }
        else{
          if(!bean.sstatus.equals(this.sstatus))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field sbookorgcode
      if((this.sbookorgcode==null && bean.sbookorgcode!=null) || (this.sbookorgcode!=null && bean.sbookorgcode==null))
          return false;
        else if(this.sbookorgcode==null && bean.sbookorgcode==null){
        }
        else{
          if(!bean.sbookorgcode.equals(this.sbookorgcode))
               return false;
     }
      //compare field tssysupdate
      if((this.tssysupdate==null && bean.tssysupdate!=null) || (this.tssysupdate!=null && bean.tssysupdate==null))
          return false;
        else if(this.tssysupdate==null && bean.tssysupdate==null){
        }
        else{
          if(!bean.tssysupdate.equals(this.tssysupdate))
               return false;
     }
      //compare field dacceptdate
      if((this.dacceptdate==null && bean.dacceptdate!=null) || (this.dacceptdate!=null && bean.dacceptdate==null))
          return false;
        else if(this.dacceptdate==null && bean.dacceptdate==null){
        }
        else{
          if(!bean.dacceptdate.equals(this.dacceptdate))
               return false;
     }
      //compare field dauditdate
      if((this.dauditdate==null && bean.dauditdate!=null) || (this.dauditdate!=null && bean.dauditdate==null))
          return false;
        else if(this.dauditdate==null && bean.dauditdate==null){
        }
        else{
          if(!bean.dauditdate.equals(this.dauditdate))
               return false;
     }
      //compare field schannelcode
      if((this.schannelcode==null && bean.schannelcode!=null) || (this.schannelcode!=null && bean.schannelcode==null))
          return false;
        else if(this.schannelcode==null && bean.schannelcode==null){
        }
        else{
          if(!bean.schannelcode.equals(this.schannelcode))
               return false;
     }
      //compare field saddword
      if((this.saddword==null && bean.saddword!=null) || (this.saddword!=null && bean.saddword==null))
          return false;
        else if(this.saddword==null && bean.saddword==null){
        }
        else{
          if(!bean.saddword.equals(this.saddword))
               return false;
     }
      //compare field tsupdate
      if((this.tsupdate==null && bean.tsupdate!=null) || (this.tsupdate!=null && bean.tsupdate==null))
          return false;
        else if(this.tsupdate==null && bean.tsupdate==null){
        }
        else{
          if(!bean.tsupdate.equals(this.tsupdate))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.ivousrlno!=null)
          _hash_ = _hash_ * 31+ this.ivousrlno.hashCode() ;
        if(this.staxorgcode!=null)
          _hash_ = _hash_ * 31+ this.staxorgcode.hashCode() ;
        if(this.spackno!=null)
          _hash_ = _hash_ * 31+ this.spackno.hashCode() ;
        if(this.strano!=null)
          _hash_ = _hash_ * 31+ this.strano.hashCode() ;
        if(this.dbilldate!=null)
          _hash_ = _hash_ * 31+ this.dbilldate.hashCode() ;
        if(this.selectrotaxvouno!=null)
          _hash_ = _hash_ * 31+ this.selectrotaxvouno.hashCode() ;
        if(this.sfreevouno!=null)
          _hash_ = _hash_ * 31+ this.sfreevouno.hashCode() ;
        if(this.cfreeplutype!=null)
          _hash_ = _hash_ * 31+ this.cfreeplutype.hashCode() ;
        if(this.sfreeplusubjectcode!=null)
          _hash_ = _hash_ * 31+ this.sfreeplusubjectcode.hashCode() ;
        if(this.cfreeplulevel!=null)
          _hash_ = _hash_ * 31+ this.cfreeplulevel.hashCode() ;
        if(this.sfreeplusign!=null)
          _hash_ = _hash_ * 31+ this.sfreeplusign.hashCode() ;
        if(this.sfreepluptrecode!=null)
          _hash_ = _hash_ * 31+ this.sfreepluptrecode.hashCode() ;
        if(this.ffreepluamt!=null)
          _hash_ = _hash_ * 31+ this.ffreepluamt.hashCode() ;
        if(this.cfreemikind!=null)
          _hash_ = _hash_ * 31+ this.cfreemikind.hashCode() ;
        if(this.sfreemisubject!=null)
          _hash_ = _hash_ * 31+ this.sfreemisubject.hashCode() ;
        if(this.cfreemilevel!=null)
          _hash_ = _hash_ * 31+ this.cfreemilevel.hashCode() ;
        if(this.sfreemisign!=null)
          _hash_ = _hash_ * 31+ this.sfreemisign.hashCode() ;
        if(this.sfreemiptre!=null)
          _hash_ = _hash_ * 31+ this.sfreemiptre.hashCode() ;
        if(this.ffreemiamt!=null)
          _hash_ = _hash_ * 31+ this.ffreemiamt.hashCode() ;
        if(this.scorpcode!=null)
          _hash_ = _hash_ * 31+ this.scorpcode.hashCode() ;
        if(this.ctrimsign!=null)
          _hash_ = _hash_ * 31+ this.ctrimsign.hashCode() ;
        if(this.sstatus!=null)
          _hash_ = _hash_ * 31+ this.sstatus.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.sbookorgcode!=null)
          _hash_ = _hash_ * 31+ this.sbookorgcode.hashCode() ;
        if(this.tssysupdate!=null)
          _hash_ = _hash_ * 31+ this.tssysupdate.hashCode() ;
        if(this.dacceptdate!=null)
          _hash_ = _hash_ * 31+ this.dacceptdate.hashCode() ;
        if(this.dauditdate!=null)
          _hash_ = _hash_ * 31+ this.dauditdate.hashCode() ;
        if(this.schannelcode!=null)
          _hash_ = _hash_ * 31+ this.schannelcode.hashCode() ;
        if(this.saddword!=null)
          _hash_ = _hash_ * 31+ this.saddword.hashCode() ;
        if(this.tsupdate!=null)
          _hash_ = _hash_ * 31+ this.tsupdate.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        HtvFreeDto bean = new HtvFreeDto();

          bean.ivousrlno = this.ivousrlno;

          if (this.staxorgcode != null)
            bean.staxorgcode = new String(this.staxorgcode);
          if (this.spackno != null)
            bean.spackno = new String(this.spackno);
          if (this.strano != null)
            bean.strano = new String(this.strano);
          if (this.dbilldate != null)
            bean.dbilldate = (Date) this.dbilldate.clone();
          if (this.selectrotaxvouno != null)
            bean.selectrotaxvouno = new String(this.selectrotaxvouno);
          if (this.sfreevouno != null)
            bean.sfreevouno = new String(this.sfreevouno);
          if (this.cfreeplutype != null)
            bean.cfreeplutype = new String(this.cfreeplutype);
          if (this.sfreeplusubjectcode != null)
            bean.sfreeplusubjectcode = new String(this.sfreeplusubjectcode);
          if (this.cfreeplulevel != null)
            bean.cfreeplulevel = new String(this.cfreeplulevel);
          if (this.sfreeplusign != null)
            bean.sfreeplusign = new String(this.sfreeplusign);
          if (this.sfreepluptrecode != null)
            bean.sfreepluptrecode = new String(this.sfreepluptrecode);
          if (this.ffreepluamt != null)
            bean.ffreepluamt = new BigDecimal(this.ffreepluamt.toString());
          if (this.cfreemikind != null)
            bean.cfreemikind = new String(this.cfreemikind);
          if (this.sfreemisubject != null)
            bean.sfreemisubject = new String(this.sfreemisubject);
          if (this.cfreemilevel != null)
            bean.cfreemilevel = new String(this.cfreemilevel);
          if (this.sfreemisign != null)
            bean.sfreemisign = new String(this.sfreemisign);
          if (this.sfreemiptre != null)
            bean.sfreemiptre = new String(this.sfreemiptre);
          if (this.ffreemiamt != null)
            bean.ffreemiamt = new BigDecimal(this.ffreemiamt.toString());
          if (this.scorpcode != null)
            bean.scorpcode = new String(this.scorpcode);
          if (this.ctrimsign != null)
            bean.ctrimsign = new String(this.ctrimsign);
          if (this.sstatus != null)
            bean.sstatus = new String(this.sstatus);
          if (this.sfilename != null)
            bean.sfilename = new String(this.sfilename);
          if (this.sbookorgcode != null)
            bean.sbookorgcode = new String(this.sbookorgcode);
          if (this.tssysupdate != null)
            bean.tssysupdate = (Timestamp) this.tssysupdate.clone();
          if (this.dacceptdate != null)
            bean.dacceptdate = (Date) this.dacceptdate.clone();
          if (this.dauditdate != null)
            bean.dauditdate = (Date) this.dauditdate.clone();
          if (this.schannelcode != null)
            bean.schannelcode = new String(this.schannelcode);
          if (this.saddword != null)
            bean.saddword = new String(this.saddword);
          if (this.tsupdate != null)
            bean.tsupdate = (Timestamp) this.tsupdate.clone();
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("HtvFreeDto").append(sep);
        sb.append("[ivousrlno]").append(" = ").append(ivousrlno).append(sep);
        sb.append("[staxorgcode]").append(" = ").append(staxorgcode).append(sep);
        sb.append("[spackno]").append(" = ").append(spackno).append(sep);
        sb.append("[strano]").append(" = ").append(strano).append(sep);
        sb.append("[dbilldate]").append(" = ").append(dbilldate).append(sep);
        sb.append("[selectrotaxvouno]").append(" = ").append(selectrotaxvouno).append(sep);
        sb.append("[sfreevouno]").append(" = ").append(sfreevouno).append(sep);
        sb.append("[cfreeplutype]").append(" = ").append(cfreeplutype).append(sep);
        sb.append("[sfreeplusubjectcode]").append(" = ").append(sfreeplusubjectcode).append(sep);
        sb.append("[cfreeplulevel]").append(" = ").append(cfreeplulevel).append(sep);
        sb.append("[sfreeplusign]").append(" = ").append(sfreeplusign).append(sep);
        sb.append("[sfreepluptrecode]").append(" = ").append(sfreepluptrecode).append(sep);
        sb.append("[ffreepluamt]").append(" = ").append(ffreepluamt).append(sep);
        sb.append("[cfreemikind]").append(" = ").append(cfreemikind).append(sep);
        sb.append("[sfreemisubject]").append(" = ").append(sfreemisubject).append(sep);
        sb.append("[cfreemilevel]").append(" = ").append(cfreemilevel).append(sep);
        sb.append("[sfreemisign]").append(" = ").append(sfreemisign).append(sep);
        sb.append("[sfreemiptre]").append(" = ").append(sfreemiptre).append(sep);
        sb.append("[ffreemiamt]").append(" = ").append(ffreemiamt).append(sep);
        sb.append("[scorpcode]").append(" = ").append(scorpcode).append(sep);
        sb.append("[ctrimsign]").append(" = ").append(ctrimsign).append(sep);
        sb.append("[sstatus]").append(" = ").append(sstatus).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[sbookorgcode]").append(" = ").append(sbookorgcode).append(sep);
        sb.append("[tssysupdate]").append(" = ").append(tssysupdate).append(sep);
        sb.append("[dacceptdate]").append(" = ").append(dacceptdate).append(sep);
        sb.append("[dauditdate]").append(" = ").append(dauditdate).append(sep);
        sb.append("[schannelcode]").append(" = ").append(schannelcode).append(sep);
        sb.append("[saddword]").append(" = ").append(saddword).append(sep);
        sb.append("[tsupdate]").append(" = ").append(tsupdate).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //don't need check field I_VOUSRLNO,it is generated column
  
    //check field S_TAXORGCODE
      if (this.getStaxorgcode()==null)
             sb.append("S_TAXORGCODE不能为空; ");
      if (this.getStaxorgcode()!=null)
             if (this.getStaxorgcode().getBytes().length > 12)
                sb.append("S_TAXORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_PACKNO
      if (this.getSpackno()==null)
             sb.append("S_PACKNO不能为空; ");
      if (this.getSpackno()!=null)
             if (this.getSpackno().getBytes().length > 8)
                sb.append("S_PACKNO宽度不能超过 "+8+"个字符; ");
    
    //check field S_TRANO
      if (this.getStrano()!=null)
             if (this.getStrano().getBytes().length > 8)
                sb.append("S_TRANO宽度不能超过 "+8+"个字符; ");
    
    //check field D_BILLDATE
      if (this.getDbilldate()==null)
             sb.append("D_BILLDATE不能为空; ");
      
    //check field S_ELECTROTAXVOUNO
      if (this.getSelectrotaxvouno()!=null)
             if (this.getSelectrotaxvouno().getBytes().length > 20)
                sb.append("S_ELECTROTAXVOUNO宽度不能超过 "+20+"个字符; ");
    
    //check field S_FREEVOUNO
      if (this.getSfreevouno()==null)
             sb.append("S_FREEVOUNO不能为空; ");
      if (this.getSfreevouno()!=null)
             if (this.getSfreevouno().getBytes().length > 8)
                sb.append("S_FREEVOUNO宽度不能超过 "+8+"个字符; ");
    
    //check field C_FREEPLUTYPE
      if (this.getCfreeplutype()==null)
             sb.append("C_FREEPLUTYPE不能为空; ");
      if (this.getCfreeplutype()!=null)
             if (this.getCfreeplutype().getBytes().length > 1)
                sb.append("C_FREEPLUTYPE宽度不能超过 "+1+"个字符; ");
    
    //check field S_FREEPLUSUBJECTCODE
      if (this.getSfreeplusubjectcode()==null)
             sb.append("S_FREEPLUSUBJECTCODE不能为空; ");
      if (this.getSfreeplusubjectcode()!=null)
             if (this.getSfreeplusubjectcode().getBytes().length > 30)
                sb.append("S_FREEPLUSUBJECTCODE宽度不能超过 "+30+"个字符; ");
    
    //check field C_FREEPLULEVEL
      if (this.getCfreeplulevel()==null)
             sb.append("C_FREEPLULEVEL不能为空; ");
      if (this.getCfreeplulevel()!=null)
             if (this.getCfreeplulevel().getBytes().length > 1)
                sb.append("C_FREEPLULEVEL宽度不能超过 "+1+"个字符; ");
    
    //check field S_FREEPLUSIGN
      if (this.getSfreeplusign()!=null)
             if (this.getSfreeplusign().getBytes().length > 35)
                sb.append("S_FREEPLUSIGN宽度不能超过 "+35+"个字符; ");
    
    //check field S_FREEPLUPTRECODE
      if (this.getSfreepluptrecode()==null)
             sb.append("S_FREEPLUPTRECODE不能为空; ");
      if (this.getSfreepluptrecode()!=null)
             if (this.getSfreepluptrecode().getBytes().length > 10)
                sb.append("S_FREEPLUPTRECODE宽度不能超过 "+10+"个字符; ");
    
    //check field F_FREEPLUAMT
      if (this.getFfreepluamt()==null)
             sb.append("F_FREEPLUAMT不能为空; ");
      
    //check field C_FREEMIKIND
      if (this.getCfreemikind()==null)
             sb.append("C_FREEMIKIND不能为空; ");
      if (this.getCfreemikind()!=null)
             if (this.getCfreemikind().getBytes().length > 1)
                sb.append("C_FREEMIKIND宽度不能超过 "+1+"个字符; ");
    
    //check field S_FREEMISUBJECT
      if (this.getSfreemisubject()==null)
             sb.append("S_FREEMISUBJECT不能为空; ");
      if (this.getSfreemisubject()!=null)
             if (this.getSfreemisubject().getBytes().length > 30)
                sb.append("S_FREEMISUBJECT宽度不能超过 "+30+"个字符; ");
    
    //check field C_FREEMILEVEL
      if (this.getCfreemilevel()==null)
             sb.append("C_FREEMILEVEL不能为空; ");
      if (this.getCfreemilevel()!=null)
             if (this.getCfreemilevel().getBytes().length > 1)
                sb.append("C_FREEMILEVEL宽度不能超过 "+1+"个字符; ");
    
    //check field S_FREEMISIGN
      if (this.getSfreemisign()!=null)
             if (this.getSfreemisign().getBytes().length > 35)
                sb.append("S_FREEMISIGN宽度不能超过 "+35+"个字符; ");
    
    //check field S_FREEMIPTRE
      if (this.getSfreemiptre()==null)
             sb.append("S_FREEMIPTRE不能为空; ");
      if (this.getSfreemiptre()!=null)
             if (this.getSfreemiptre().getBytes().length > 10)
                sb.append("S_FREEMIPTRE宽度不能超过 "+10+"个字符; ");
    
    //check field F_FREEMIAMT
      if (this.getFfreemiamt()==null)
             sb.append("F_FREEMIAMT不能为空; ");
      
    //check field S_CORPCODE
      if (this.getScorpcode()!=null)
             if (this.getScorpcode().getBytes().length > 20)
                sb.append("S_CORPCODE宽度不能超过 "+20+"个字符; ");
    
    //check field C_TRIMSIGN
      if (this.getCtrimsign()==null)
             sb.append("C_TRIMSIGN不能为空; ");
      if (this.getCtrimsign()!=null)
             if (this.getCtrimsign().getBytes().length > 1)
                sb.append("C_TRIMSIGN宽度不能超过 "+1+"个字符; ");
    
    //check field S_STATUS
      if (this.getSstatus()!=null)
             if (this.getSstatus().getBytes().length > 5)
                sb.append("S_STATUS宽度不能超过 "+5+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()==null)
             sb.append("S_FILENAME不能为空; ");
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_BOOKORGCODE
      if (this.getSbookorgcode()==null)
             sb.append("S_BOOKORGCODE不能为空; ");
      if (this.getSbookorgcode()!=null)
             if (this.getSbookorgcode().getBytes().length > 12)
                sb.append("S_BOOKORGCODE宽度不能超过 "+12+"个字符; ");
    
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  
    //check field D_ACCEPTDATE
      if (this.getDacceptdate()==null)
             sb.append("D_ACCEPTDATE不能为空; ");
      
    //check field D_AUDITDATE
      
    //check field S_CHANNELCODE
      if (this.getSchannelcode()!=null)
             if (this.getSchannelcode().getBytes().length > 15)
                sb.append("S_CHANNELCODE宽度不能超过 "+15+"个字符; ");
    
    //check field S_ADDWORD
      if (this.getSaddword()!=null)
             if (this.getSaddword().getBytes().length > 120)
                sb.append("S_ADDWORD宽度不能超过 "+120+"个字符; ");
    
    //check field TS_UPDATE
      if (this.getTsupdate()==null)
             sb.append("TS_UPDATE不能为空; ");
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //don't need check field I_VOUSRLNO,it is generated column
  
    //check field S_TAXORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXORGCODE")) {
               if (this.getStaxorgcode()==null)
                    sb.append("S_TAXORGCODE 不能为空; ");
               if (this.getStaxorgcode()!=null)
                    if (this.getStaxorgcode().getBytes().length > 12)
                        sb.append("S_TAXORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_PACKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PACKNO")) {
               if (this.getSpackno()==null)
                    sb.append("S_PACKNO 不能为空; ");
               if (this.getSpackno()!=null)
                    if (this.getSpackno().getBytes().length > 8)
                        sb.append("S_PACKNO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TRANO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRANO")) {
                 if (this.getStrano()!=null)
                    if (this.getStrano().getBytes().length > 8)
                        sb.append("S_TRANO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field D_BILLDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("D_BILLDATE")) {
               if (this.getDbilldate()==null)
                    sb.append("D_BILLDATE 不能为空; ");
               break;
         }
  }
    
    //check field S_ELECTROTAXVOUNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ELECTROTAXVOUNO")) {
                 if (this.getSelectrotaxvouno()!=null)
                    if (this.getSelectrotaxvouno().getBytes().length > 20)
                        sb.append("S_ELECTROTAXVOUNO 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_FREEVOUNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FREEVOUNO")) {
               if (this.getSfreevouno()==null)
                    sb.append("S_FREEVOUNO 不能为空; ");
               if (this.getSfreevouno()!=null)
                    if (this.getSfreevouno().getBytes().length > 8)
                        sb.append("S_FREEVOUNO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field C_FREEPLUTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_FREEPLUTYPE")) {
               if (this.getCfreeplutype()==null)
                    sb.append("C_FREEPLUTYPE 不能为空; ");
               if (this.getCfreeplutype()!=null)
                    if (this.getCfreeplutype().getBytes().length > 1)
                        sb.append("C_FREEPLUTYPE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_FREEPLUSUBJECTCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FREEPLUSUBJECTCODE")) {
               if (this.getSfreeplusubjectcode()==null)
                    sb.append("S_FREEPLUSUBJECTCODE 不能为空; ");
               if (this.getSfreeplusubjectcode()!=null)
                    if (this.getSfreeplusubjectcode().getBytes().length > 30)
                        sb.append("S_FREEPLUSUBJECTCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field C_FREEPLULEVEL
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_FREEPLULEVEL")) {
               if (this.getCfreeplulevel()==null)
                    sb.append("C_FREEPLULEVEL 不能为空; ");
               if (this.getCfreeplulevel()!=null)
                    if (this.getCfreeplulevel().getBytes().length > 1)
                        sb.append("C_FREEPLULEVEL 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_FREEPLUSIGN
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FREEPLUSIGN")) {
                 if (this.getSfreeplusign()!=null)
                    if (this.getSfreeplusign().getBytes().length > 35)
                        sb.append("S_FREEPLUSIGN 宽度不能超过 "+35+"个字符");
             break;
         }
  }
    
    //check field S_FREEPLUPTRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FREEPLUPTRECODE")) {
               if (this.getSfreepluptrecode()==null)
                    sb.append("S_FREEPLUPTRECODE 不能为空; ");
               if (this.getSfreepluptrecode()!=null)
                    if (this.getSfreepluptrecode().getBytes().length > 10)
                        sb.append("S_FREEPLUPTRECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field F_FREEPLUAMT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("F_FREEPLUAMT")) {
               if (this.getFfreepluamt()==null)
                    sb.append("F_FREEPLUAMT 不能为空; ");
               break;
         }
  }
    
    //check field C_FREEMIKIND
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_FREEMIKIND")) {
               if (this.getCfreemikind()==null)
                    sb.append("C_FREEMIKIND 不能为空; ");
               if (this.getCfreemikind()!=null)
                    if (this.getCfreemikind().getBytes().length > 1)
                        sb.append("C_FREEMIKIND 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_FREEMISUBJECT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FREEMISUBJECT")) {
               if (this.getSfreemisubject()==null)
                    sb.append("S_FREEMISUBJECT 不能为空; ");
               if (this.getSfreemisubject()!=null)
                    if (this.getSfreemisubject().getBytes().length > 30)
                        sb.append("S_FREEMISUBJECT 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field C_FREEMILEVEL
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_FREEMILEVEL")) {
               if (this.getCfreemilevel()==null)
                    sb.append("C_FREEMILEVEL 不能为空; ");
               if (this.getCfreemilevel()!=null)
                    if (this.getCfreemilevel().getBytes().length > 1)
                        sb.append("C_FREEMILEVEL 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_FREEMISIGN
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FREEMISIGN")) {
                 if (this.getSfreemisign()!=null)
                    if (this.getSfreemisign().getBytes().length > 35)
                        sb.append("S_FREEMISIGN 宽度不能超过 "+35+"个字符");
             break;
         }
  }
    
    //check field S_FREEMIPTRE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FREEMIPTRE")) {
               if (this.getSfreemiptre()==null)
                    sb.append("S_FREEMIPTRE 不能为空; ");
               if (this.getSfreemiptre()!=null)
                    if (this.getSfreemiptre().getBytes().length > 10)
                        sb.append("S_FREEMIPTRE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field F_FREEMIAMT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("F_FREEMIAMT")) {
               if (this.getFfreemiamt()==null)
                    sb.append("F_FREEMIAMT 不能为空; ");
               break;
         }
  }
    
    //check field S_CORPCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CORPCODE")) {
                 if (this.getScorpcode()!=null)
                    if (this.getScorpcode().getBytes().length > 20)
                        sb.append("S_CORPCODE 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field C_TRIMSIGN
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_TRIMSIGN")) {
               if (this.getCtrimsign()==null)
                    sb.append("C_TRIMSIGN 不能为空; ");
               if (this.getCtrimsign()!=null)
                    if (this.getCtrimsign().getBytes().length > 1)
                        sb.append("C_TRIMSIGN 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_STATUS
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_STATUS")) {
                 if (this.getSstatus()!=null)
                    if (this.getSstatus().getBytes().length > 5)
                        sb.append("S_STATUS 宽度不能超过 "+5+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
               if (this.getSfilename()==null)
                    sb.append("S_FILENAME 不能为空; ");
               if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_BOOKORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BOOKORGCODE")) {
               if (this.getSbookorgcode()==null)
                    sb.append("S_BOOKORGCODE 不能为空; ");
               if (this.getSbookorgcode()!=null)
                    if (this.getSbookorgcode().getBytes().length > 12)
                        sb.append("S_BOOKORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  
    //check field D_ACCEPTDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("D_ACCEPTDATE")) {
               if (this.getDacceptdate()==null)
                    sb.append("D_ACCEPTDATE 不能为空; ");
               break;
         }
  }
    
    //check field D_AUDITDATE
          
    //check field S_CHANNELCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CHANNELCODE")) {
                 if (this.getSchannelcode()!=null)
                    if (this.getSchannelcode().getBytes().length > 15)
                        sb.append("S_CHANNELCODE 宽度不能超过 "+15+"个字符");
             break;
         }
  }
    
    //check field S_ADDWORD
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ADDWORD")) {
                 if (this.getSaddword()!=null)
                    if (this.getSaddword().getBytes().length > 120)
                        sb.append("S_ADDWORD 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field TS_UPDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("TS_UPDATE")) {
               if (this.getTsupdate()==null)
                    sb.append("TS_UPDATE 不能为空; ");
               break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      HtvFreePK pk = new HtvFreePK();
      pk.setIvousrlno(getIvousrlno());
      return pk;
    };
}
