    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.HtvPayoutfinanceSubPK;
/**
 * <p>Title: DTO of table: HTV_PAYOUTFINANCE_SUB</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:56 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class HtvPayoutfinanceSubDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  I_VOUSRLNO BIGINT , PK   , NOT NULL       */
    protected Long ivousrlno;
    /**
    *  S_SEQNO INTEGER , PK   , NOT NULL       */
    protected Integer sseqno;
    /**
    *  S_TRANO VARCHAR   , NOT NULL       */
    protected String strano;
    /**
    *  S_PAYEEACCT VARCHAR   , NOT NULL       */
    protected String spayeeacct;
    /**
    *  S_PAYEENAME VARCHAR   , NOT NULL       */
    protected String spayeename;
    /**
    *  S_PAYEEADDR VARCHAR         */
    protected String spayeeaddr;
    /**
    *  S_PAYEEOPNBNKNO VARCHAR   , NOT NULL       */
    protected String spayeeopnbnkno;
    /**
    *  N_SUBAMT DECIMAL   , NOT NULL       */
    protected BigDecimal nsubamt;
    /**
    *  TS_SYSUPDATE TIMESTAMP   , NOT NULL       */
    protected Timestamp tssysupdate;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public Long getIvousrlno()
    {
        return ivousrlno;
    }
     /**
     *   Setter I_VOUSRLNO, PK , NOT NULL        * */
    public void setIvousrlno(Long _ivousrlno) {
        this.ivousrlno = _ivousrlno;
    }


    public Integer getSseqno()
    {
        return sseqno;
    }
     /**
     *   Setter S_SEQNO, PK , NOT NULL        * */
    public void setSseqno(Integer _sseqno) {
        this.sseqno = _sseqno;
    }


    public String getStrano()
    {
        return strano;
    }
     /**
     *   Setter S_TRANO , NOT NULL        * */
    public void setStrano(String _strano) {
        this.strano = _strano;
    }


    public String getSpayeeacct()
    {
        return spayeeacct;
    }
     /**
     *   Setter S_PAYEEACCT , NOT NULL        * */
    public void setSpayeeacct(String _spayeeacct) {
        this.spayeeacct = _spayeeacct;
    }


    public String getSpayeename()
    {
        return spayeename;
    }
     /**
     *   Setter S_PAYEENAME , NOT NULL        * */
    public void setSpayeename(String _spayeename) {
        this.spayeename = _spayeename;
    }


    public String getSpayeeaddr()
    {
        return spayeeaddr;
    }
     /**
     *   Setter S_PAYEEADDR        * */
    public void setSpayeeaddr(String _spayeeaddr) {
        this.spayeeaddr = _spayeeaddr;
    }


    public String getSpayeeopnbnkno()
    {
        return spayeeopnbnkno;
    }
     /**
     *   Setter S_PAYEEOPNBNKNO , NOT NULL        * */
    public void setSpayeeopnbnkno(String _spayeeopnbnkno) {
        this.spayeeopnbnkno = _spayeeopnbnkno;
    }


    public BigDecimal getNsubamt()
    {
        return nsubamt;
    }
     /**
     *   Setter N_SUBAMT , NOT NULL        * */
    public void setNsubamt(BigDecimal _nsubamt) {
        this.nsubamt = _nsubamt;
    }


    public Timestamp getTssysupdate()
    {
        return tssysupdate;
    }
     /**
     *   Setter TS_SYSUPDATE , NOT NULL        * */
    public void setTssysupdate(Timestamp _tssysupdate) {
        this.tssysupdate = _tssysupdate;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter I_VOUSRLNO, PK , NOT NULL       * */
    public static String  columnIvousrlno()
    {
        return "I_VOUSRLNO";
    }
   
    /**
    *   Getter S_SEQNO, PK , NOT NULL       * */
    public static String  columnSseqno()
    {
        return "S_SEQNO";
    }
   
    /**
    *   Getter S_TRANO , NOT NULL       * */
    public static String  columnStrano()
    {
        return "S_TRANO";
    }
   
    /**
    *   Getter S_PAYEEACCT , NOT NULL       * */
    public static String  columnSpayeeacct()
    {
        return "S_PAYEEACCT";
    }
   
    /**
    *   Getter S_PAYEENAME , NOT NULL       * */
    public static String  columnSpayeename()
    {
        return "S_PAYEENAME";
    }
   
    /**
    *   Getter S_PAYEEADDR       * */
    public static String  columnSpayeeaddr()
    {
        return "S_PAYEEADDR";
    }
   
    /**
    *   Getter S_PAYEEOPNBNKNO , NOT NULL       * */
    public static String  columnSpayeeopnbnkno()
    {
        return "S_PAYEEOPNBNKNO";
    }
   
    /**
    *   Getter N_SUBAMT , NOT NULL       * */
    public static String  columnNsubamt()
    {
        return "N_SUBAMT";
    }
   
    /**
    *   Getter TS_SYSUPDATE , NOT NULL       * */
    public static String  columnTssysupdate()
    {
        return "TS_SYSUPDATE";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "HTV_PAYOUTFINANCE_SUB";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[9];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="S_SEQNO";
        columnNames[2]="S_TRANO";
        columnNames[3]="S_PAYEEACCT";
        columnNames[4]="S_PAYEENAME";
        columnNames[5]="S_PAYEEADDR";
        columnNames[6]="S_PAYEEOPNBNKNO";
        columnNames[7]="N_SUBAMT";
        columnNames[8]="TS_SYSUPDATE";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof HtvPayoutfinanceSubDto))
            return false;

        HtvPayoutfinanceSubDto bean = (HtvPayoutfinanceSubDto) obj;


      //compare field ivousrlno
      if((this.ivousrlno==null && bean.ivousrlno!=null) || (this.ivousrlno!=null && bean.ivousrlno==null))
          return false;
        else if(this.ivousrlno==null && bean.ivousrlno==null){
        }
        else{
          if(!bean.ivousrlno.equals(this.ivousrlno))
               return false;
     }
      //compare field sseqno
      if((this.sseqno==null && bean.sseqno!=null) || (this.sseqno!=null && bean.sseqno==null))
          return false;
        else if(this.sseqno==null && bean.sseqno==null){
        }
        else{
          if(!bean.sseqno.equals(this.sseqno))
               return false;
     }
      //compare field strano
      if((this.strano==null && bean.strano!=null) || (this.strano!=null && bean.strano==null))
          return false;
        else if(this.strano==null && bean.strano==null){
        }
        else{
          if(!bean.strano.equals(this.strano))
               return false;
     }
      //compare field spayeeacct
      if((this.spayeeacct==null && bean.spayeeacct!=null) || (this.spayeeacct!=null && bean.spayeeacct==null))
          return false;
        else if(this.spayeeacct==null && bean.spayeeacct==null){
        }
        else{
          if(!bean.spayeeacct.equals(this.spayeeacct))
               return false;
     }
      //compare field spayeename
      if((this.spayeename==null && bean.spayeename!=null) || (this.spayeename!=null && bean.spayeename==null))
          return false;
        else if(this.spayeename==null && bean.spayeename==null){
        }
        else{
          if(!bean.spayeename.equals(this.spayeename))
               return false;
     }
      //compare field spayeeaddr
      if((this.spayeeaddr==null && bean.spayeeaddr!=null) || (this.spayeeaddr!=null && bean.spayeeaddr==null))
          return false;
        else if(this.spayeeaddr==null && bean.spayeeaddr==null){
        }
        else{
          if(!bean.spayeeaddr.equals(this.spayeeaddr))
               return false;
     }
      //compare field spayeeopnbnkno
      if((this.spayeeopnbnkno==null && bean.spayeeopnbnkno!=null) || (this.spayeeopnbnkno!=null && bean.spayeeopnbnkno==null))
          return false;
        else if(this.spayeeopnbnkno==null && bean.spayeeopnbnkno==null){
        }
        else{
          if(!bean.spayeeopnbnkno.equals(this.spayeeopnbnkno))
               return false;
     }
      //compare field nsubamt
      if((this.nsubamt==null && bean.nsubamt!=null) || (this.nsubamt!=null && bean.nsubamt==null))
          return false;
        else if(this.nsubamt==null && bean.nsubamt==null){
        }
        else{
          if(!bean.nsubamt.equals(this.nsubamt))
               return false;
     }
      //compare field tssysupdate
      if((this.tssysupdate==null && bean.tssysupdate!=null) || (this.tssysupdate!=null && bean.tssysupdate==null))
          return false;
        else if(this.tssysupdate==null && bean.tssysupdate==null){
        }
        else{
          if(!bean.tssysupdate.equals(this.tssysupdate))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.ivousrlno!=null)
          _hash_ = _hash_ * 31+ this.ivousrlno.hashCode() ;
        if(this.sseqno!=null)
          _hash_ = _hash_ * 31+ this.sseqno.hashCode() ;
        if(this.strano!=null)
          _hash_ = _hash_ * 31+ this.strano.hashCode() ;
        if(this.spayeeacct!=null)
          _hash_ = _hash_ * 31+ this.spayeeacct.hashCode() ;
        if(this.spayeename!=null)
          _hash_ = _hash_ * 31+ this.spayeename.hashCode() ;
        if(this.spayeeaddr!=null)
          _hash_ = _hash_ * 31+ this.spayeeaddr.hashCode() ;
        if(this.spayeeopnbnkno!=null)
          _hash_ = _hash_ * 31+ this.spayeeopnbnkno.hashCode() ;
        if(this.nsubamt!=null)
          _hash_ = _hash_ * 31+ this.nsubamt.hashCode() ;
        if(this.tssysupdate!=null)
          _hash_ = _hash_ * 31+ this.tssysupdate.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        HtvPayoutfinanceSubDto bean = new HtvPayoutfinanceSubDto();

          bean.ivousrlno = this.ivousrlno;

          bean.sseqno = this.sseqno;

          if (this.strano != null)
            bean.strano = new String(this.strano);
          if (this.spayeeacct != null)
            bean.spayeeacct = new String(this.spayeeacct);
          if (this.spayeename != null)
            bean.spayeename = new String(this.spayeename);
          if (this.spayeeaddr != null)
            bean.spayeeaddr = new String(this.spayeeaddr);
          if (this.spayeeopnbnkno != null)
            bean.spayeeopnbnkno = new String(this.spayeeopnbnkno);
          if (this.nsubamt != null)
            bean.nsubamt = new BigDecimal(this.nsubamt.toString());
          if (this.tssysupdate != null)
            bean.tssysupdate = (Timestamp) this.tssysupdate.clone();
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("HtvPayoutfinanceSubDto").append(sep);
        sb.append("[ivousrlno]").append(" = ").append(ivousrlno).append(sep);
        sb.append("[sseqno]").append(" = ").append(sseqno).append(sep);
        sb.append("[strano]").append(" = ").append(strano).append(sep);
        sb.append("[spayeeacct]").append(" = ").append(spayeeacct).append(sep);
        sb.append("[spayeename]").append(" = ").append(spayeename).append(sep);
        sb.append("[spayeeaddr]").append(" = ").append(spayeeaddr).append(sep);
        sb.append("[spayeeopnbnkno]").append(" = ").append(spayeeopnbnkno).append(sep);
        sb.append("[nsubamt]").append(" = ").append(nsubamt).append(sep);
        sb.append("[tssysupdate]").append(" = ").append(tssysupdate).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field I_VOUSRLNO
      if (this.getIvousrlno()==null)
             sb.append("I_VOUSRLNO不能为空; ");
      
    //check field S_SEQNO
      if (this.getSseqno()==null)
             sb.append("S_SEQNO不能为空; ");
      
    //check field S_TRANO
      if (this.getStrano()==null)
             sb.append("S_TRANO不能为空; ");
      if (this.getStrano()!=null)
             if (this.getStrano().getBytes().length > 8)
                sb.append("S_TRANO宽度不能超过 "+8+"个字符; ");
    
    //check field S_PAYEEACCT
      if (this.getSpayeeacct()==null)
             sb.append("S_PAYEEACCT不能为空; ");
      if (this.getSpayeeacct()!=null)
             if (this.getSpayeeacct().getBytes().length > 32)
                sb.append("S_PAYEEACCT宽度不能超过 "+32+"个字符; ");
    
    //check field S_PAYEENAME
      if (this.getSpayeename()==null)
             sb.append("S_PAYEENAME不能为空; ");
      if (this.getSpayeename()!=null)
             if (this.getSpayeename().getBytes().length > 120)
                sb.append("S_PAYEENAME宽度不能超过 "+120+"个字符; ");
    
    //check field S_PAYEEADDR
      if (this.getSpayeeaddr()!=null)
             if (this.getSpayeeaddr().getBytes().length > 120)
                sb.append("S_PAYEEADDR宽度不能超过 "+120+"个字符; ");
    
    //check field S_PAYEEOPNBNKNO
      if (this.getSpayeeopnbnkno()==null)
             sb.append("S_PAYEEOPNBNKNO不能为空; ");
      if (this.getSpayeeopnbnkno()!=null)
             if (this.getSpayeeopnbnkno().getBytes().length > 12)
                sb.append("S_PAYEEOPNBNKNO宽度不能超过 "+12+"个字符; ");
    
    //check field N_SUBAMT
      if (this.getNsubamt()==null)
             sb.append("N_SUBAMT不能为空; ");
      
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field I_VOUSRLNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("I_VOUSRLNO")) {
               if (this.getIvousrlno()==null)
                    sb.append("I_VOUSRLNO 不能为空; ");
               break;
         }
  }
    
    //check field S_SEQNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SEQNO")) {
               if (this.getSseqno()==null)
                    sb.append("S_SEQNO 不能为空; ");
               break;
         }
  }
    
    //check field S_TRANO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRANO")) {
               if (this.getStrano()==null)
                    sb.append("S_TRANO 不能为空; ");
               if (this.getStrano()!=null)
                    if (this.getStrano().getBytes().length > 8)
                        sb.append("S_TRANO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCT")) {
               if (this.getSpayeeacct()==null)
                    sb.append("S_PAYEEACCT 不能为空; ");
               if (this.getSpayeeacct()!=null)
                    if (this.getSpayeeacct().getBytes().length > 32)
                        sb.append("S_PAYEEACCT 宽度不能超过 "+32+"个字符");
             break;
         }
  }
    
    //check field S_PAYEENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEENAME")) {
               if (this.getSpayeename()==null)
                    sb.append("S_PAYEENAME 不能为空; ");
               if (this.getSpayeename()!=null)
                    if (this.getSpayeename().getBytes().length > 120)
                        sb.append("S_PAYEENAME 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEADDR
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEADDR")) {
                 if (this.getSpayeeaddr()!=null)
                    if (this.getSpayeeaddr().getBytes().length > 120)
                        sb.append("S_PAYEEADDR 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEOPNBNKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEOPNBNKNO")) {
               if (this.getSpayeeopnbnkno()==null)
                    sb.append("S_PAYEEOPNBNKNO 不能为空; ");
               if (this.getSpayeeopnbnkno()!=null)
                    if (this.getSpayeeopnbnkno().getBytes().length > 12)
                        sb.append("S_PAYEEOPNBNKNO 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field N_SUBAMT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_SUBAMT")) {
               if (this.getNsubamt()==null)
                    sb.append("N_SUBAMT 不能为空; ");
               break;
         }
  }
    
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      HtvPayoutfinanceSubPK pk = new HtvPayoutfinanceSubPK();
      pk.setIvousrlno(getIvousrlno());
      pk.setSseqno(getSseqno());
      return pk;
    };
}
