    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TfGrantpaymsgsubPK;
/**
 * <p>Title: DTO of table: TF_GRANTPAYMSGSUB</p>
 * <p>Description: 财政授权支付凭证明细信息（8202）明细 Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2015-05-13 10:24:26 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author db2itfe
 */

public class TfGrantpaymsgsubDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    * 主键流水号 I_VOUSRLNO BIGINT , PK   , NOT NULL       */
    protected Long ivousrlno;
    /**
    * 主键流水号 I_SEQNO BIGINT , PK   , NOT NULL       */
    protected Long iseqno;
    /**
    * 支付明细Id S_ID VARCHAR   , NOT NULL       */
    protected String sid;
    /**
    * 财政授权支付凭证Id S_VOUCHERBILLID VARCHAR   , NOT NULL       */
    protected String svoucherbillid;
    /**
    * 财政授权支付凭证单号 S_VOUCHERBILLNO VARCHAR   , NOT NULL       */
    protected String svoucherbillno;
    /**
    * 支付申请序号 S_VOUCHERNO VARCHAR   , NOT NULL       */
    protected String svoucherno;
    /**
    * 资金性质编码 S_FUNDTYPECODE VARCHAR   , NOT NULL       */
    protected String sfundtypecode;
    /**
    * 资金性质名称 S_FUNDTYPENAME VARCHAR   , NOT NULL       */
    protected String sfundtypename;
    /**
    * 预算类型编码 S_BGTTYPECODE VARCHAR         */
    protected String sbgttypecode;
    /**
    * 预算类型名称 S_BGTTYPENAME VARCHAR         */
    protected String sbgttypename;
    /**
    * 收支管理编码 S_PROCATCODE VARCHAR         */
    protected String sprocatcode;
    /**
    * 收支管理名称 S_PROCATNAME VARCHAR         */
    protected String sprocatname;
    /**
    * 支出类型编码 S_PAYKINDCODE VARCHAR         */
    protected String spaykindcode;
    /**
    * 支出类型名称 S_PAYKINDNAME VARCHAR         */
    protected String spaykindname;
    /**
    * 指标文号编码 S_FILENOCODE VARCHAR         */
    protected String sfilenocode;
    /**
    * 指标文号名称 S_FILENONAME VARCHAR         */
    protected String sfilenoname;
    /**
    * 一级预算单位编码 S_SUPDEPCODE VARCHAR         */
    protected String ssupdepcode;
    /**
    * 一级预算单位名称 S_SUPDEPNAME VARCHAR         */
    protected String ssupdepname;
    /**
    * 基层预算单位编码 S_AGENCYCODE VARCHAR   , NOT NULL       */
    protected String sagencycode;
    /**
    * 基层预算单位名称 S_AGENCYNAME VARCHAR   , NOT NULL       */
    protected String sagencyname;
    /**
    * 功能分类科目编码 S_EXPFUNCCODE VARCHAR   , NOT NULL       */
    protected String sexpfunccode;
    /**
    * 功能分类科目名称 S_EXPFUNCNAME VARCHAR   , NOT NULL       */
    protected String sexpfuncname;
    /**
    * 经济分类科目编码 S_EXPECOCODE VARCHAR         */
    protected String sexpecocode;
    /**
    * 经济分类科目名称 S_EXPECONAME VARCHAR         */
    protected String sexpeconame;
    /**
    * 预算项目编码 S_DEPPROCODE VARCHAR         */
    protected String sdepprocode;
    /**
    * 预算项目名称 S_DEPPRONAME VARCHAR         */
    protected String sdepproname;
    /**
    * 收款人账号 S_PAYEEACCTNO VARCHAR   , NOT NULL       */
    protected String spayeeacctno;
    /**
    * 收款人名称 S_PAYEEACCTNAME VARCHAR   , NOT NULL       */
    protected String spayeeacctname;
    /**
    * 收款人银行 S_PAYEEACCTBANKNAME VARCHAR   , NOT NULL       */
    protected String spayeeacctbankname;
    /**
    * 收款人银行行号 S_PAYEEACCTBANKNO VARCHAR         */
    protected String spayeeacctbankno;
    /**
    * 支付金额 N_PAYAMT DECIMAL   , NOT NULL       */
    protected BigDecimal npayamt;
    /**
    * 实际支付日期 S_XPAYDATE VARCHAR         */
    protected String sxpaydate;
    /**
    * 银行交易流水号 S_XAGENTBUSINESSNO VARCHAR         */
    protected String sxagentbusinessno;
    /**
    * 支票号(结算号) S_XCHECKNO VARCHAR         */
    protected String sxcheckno;
    /**
    * 实际支付金额 N_XPAYAMT DECIMAL         */
    protected BigDecimal nxpayamt;
    /**
    * 收款人银行 S_XPAYEEACCTBANKNAME VARCHAR         */
    protected String sxpayeeacctbankname;
    /**
    * 收款人账号 S_XPAYEEACCTNO VARCHAR         */
    protected String sxpayeeacctno;
    /**
    * 收款人全称 S_XPAYEEACCTNAME VARCHAR         */
    protected String sxpayeeacctname;
    /**
    * 备注 S_REMARK VARCHAR         */
    protected String sremark;
    /**
    * 预留字段1 S_HOLD1 VARCHAR         */
    protected String shold1;
    /**
    * 预留字段2 S_HOLD2 VARCHAR         */
    protected String shold2;
    /**
    * 预留字段3 S_HOLD3 VARCHAR         */
    protected String shold3;
    /**
    * 预留字段4 S_HOLD4 VARCHAR         */
    protected String shold4;
    /**
    * 扩展1 S_EXT1 VARCHAR         */
    protected String sext1;
    /**
    * 扩展2 S_EXT2 VARCHAR         */
    protected String sext2;
    /**
    * 扩展3 S_EXT3 VARCHAR         */
    protected String sext3;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public Long getIvousrlno()
    {
        return ivousrlno;
    }
     /**
     *  主键流水号 Setter I_VOUSRLNO, PK , NOT NULL        * */
    public void setIvousrlno(Long _ivousrlno) {
        this.ivousrlno = _ivousrlno;
    }


    public Long getIseqno()
    {
        return iseqno;
    }
     /**
     *  主键流水号 Setter I_SEQNO, PK , NOT NULL        * */
    public void setIseqno(Long _iseqno) {
        this.iseqno = _iseqno;
    }


    public String getSid()
    {
        return sid;
    }
     /**
     *  支付明细Id Setter S_ID , NOT NULL        * */
    public void setSid(String _sid) {
        this.sid = _sid;
    }


    public String getSvoucherbillid()
    {
        return svoucherbillid;
    }
     /**
     *  财政授权支付凭证Id Setter S_VOUCHERBILLID , NOT NULL        * */
    public void setSvoucherbillid(String _svoucherbillid) {
        this.svoucherbillid = _svoucherbillid;
    }


    public String getSvoucherbillno()
    {
        return svoucherbillno;
    }
     /**
     *  财政授权支付凭证单号 Setter S_VOUCHERBILLNO , NOT NULL        * */
    public void setSvoucherbillno(String _svoucherbillno) {
        this.svoucherbillno = _svoucherbillno;
    }


    public String getSvoucherno()
    {
        return svoucherno;
    }
     /**
     *  支付申请序号 Setter S_VOUCHERNO , NOT NULL        * */
    public void setSvoucherno(String _svoucherno) {
        this.svoucherno = _svoucherno;
    }


    public String getSfundtypecode()
    {
        return sfundtypecode;
    }
     /**
     *  资金性质编码 Setter S_FUNDTYPECODE , NOT NULL        * */
    public void setSfundtypecode(String _sfundtypecode) {
        this.sfundtypecode = _sfundtypecode;
    }


    public String getSfundtypename()
    {
        return sfundtypename;
    }
     /**
     *  资金性质名称 Setter S_FUNDTYPENAME , NOT NULL        * */
    public void setSfundtypename(String _sfundtypename) {
        this.sfundtypename = _sfundtypename;
    }


    public String getSbgttypecode()
    {
        return sbgttypecode;
    }
     /**
     *  预算类型编码 Setter S_BGTTYPECODE        * */
    public void setSbgttypecode(String _sbgttypecode) {
        this.sbgttypecode = _sbgttypecode;
    }


    public String getSbgttypename()
    {
        return sbgttypename;
    }
     /**
     *  预算类型名称 Setter S_BGTTYPENAME        * */
    public void setSbgttypename(String _sbgttypename) {
        this.sbgttypename = _sbgttypename;
    }


    public String getSprocatcode()
    {
        return sprocatcode;
    }
     /**
     *  收支管理编码 Setter S_PROCATCODE        * */
    public void setSprocatcode(String _sprocatcode) {
        this.sprocatcode = _sprocatcode;
    }


    public String getSprocatname()
    {
        return sprocatname;
    }
     /**
     *  收支管理名称 Setter S_PROCATNAME        * */
    public void setSprocatname(String _sprocatname) {
        this.sprocatname = _sprocatname;
    }


    public String getSpaykindcode()
    {
        return spaykindcode;
    }
     /**
     *  支出类型编码 Setter S_PAYKINDCODE        * */
    public void setSpaykindcode(String _spaykindcode) {
        this.spaykindcode = _spaykindcode;
    }


    public String getSpaykindname()
    {
        return spaykindname;
    }
     /**
     *  支出类型名称 Setter S_PAYKINDNAME        * */
    public void setSpaykindname(String _spaykindname) {
        this.spaykindname = _spaykindname;
    }


    public String getSfilenocode()
    {
        return sfilenocode;
    }
     /**
     *  指标文号编码 Setter S_FILENOCODE        * */
    public void setSfilenocode(String _sfilenocode) {
        this.sfilenocode = _sfilenocode;
    }


    public String getSfilenoname()
    {
        return sfilenoname;
    }
     /**
     *  指标文号名称 Setter S_FILENONAME        * */
    public void setSfilenoname(String _sfilenoname) {
        this.sfilenoname = _sfilenoname;
    }


    public String getSsupdepcode()
    {
        return ssupdepcode;
    }
     /**
     *  一级预算单位编码 Setter S_SUPDEPCODE        * */
    public void setSsupdepcode(String _ssupdepcode) {
        this.ssupdepcode = _ssupdepcode;
    }


    public String getSsupdepname()
    {
        return ssupdepname;
    }
     /**
     *  一级预算单位名称 Setter S_SUPDEPNAME        * */
    public void setSsupdepname(String _ssupdepname) {
        this.ssupdepname = _ssupdepname;
    }


    public String getSagencycode()
    {
        return sagencycode;
    }
     /**
     *  基层预算单位编码 Setter S_AGENCYCODE , NOT NULL        * */
    public void setSagencycode(String _sagencycode) {
        this.sagencycode = _sagencycode;
    }


    public String getSagencyname()
    {
        return sagencyname;
    }
     /**
     *  基层预算单位名称 Setter S_AGENCYNAME , NOT NULL        * */
    public void setSagencyname(String _sagencyname) {
        this.sagencyname = _sagencyname;
    }


    public String getSexpfunccode()
    {
        return sexpfunccode;
    }
     /**
     *  功能分类科目编码 Setter S_EXPFUNCCODE , NOT NULL        * */
    public void setSexpfunccode(String _sexpfunccode) {
        this.sexpfunccode = _sexpfunccode;
    }


    public String getSexpfuncname()
    {
        return sexpfuncname;
    }
     /**
     *  功能分类科目名称 Setter S_EXPFUNCNAME , NOT NULL        * */
    public void setSexpfuncname(String _sexpfuncname) {
        this.sexpfuncname = _sexpfuncname;
    }


    public String getSexpecocode()
    {
        return sexpecocode;
    }
     /**
     *  经济分类科目编码 Setter S_EXPECOCODE        * */
    public void setSexpecocode(String _sexpecocode) {
        this.sexpecocode = _sexpecocode;
    }


    public String getSexpeconame()
    {
        return sexpeconame;
    }
     /**
     *  经济分类科目名称 Setter S_EXPECONAME        * */
    public void setSexpeconame(String _sexpeconame) {
        this.sexpeconame = _sexpeconame;
    }


    public String getSdepprocode()
    {
        return sdepprocode;
    }
     /**
     *  预算项目编码 Setter S_DEPPROCODE        * */
    public void setSdepprocode(String _sdepprocode) {
        this.sdepprocode = _sdepprocode;
    }


    public String getSdepproname()
    {
        return sdepproname;
    }
     /**
     *  预算项目名称 Setter S_DEPPRONAME        * */
    public void setSdepproname(String _sdepproname) {
        this.sdepproname = _sdepproname;
    }


    public String getSpayeeacctno()
    {
        return spayeeacctno;
    }
     /**
     *  收款人账号 Setter S_PAYEEACCTNO , NOT NULL        * */
    public void setSpayeeacctno(String _spayeeacctno) {
        this.spayeeacctno = _spayeeacctno;
    }


    public String getSpayeeacctname()
    {
        return spayeeacctname;
    }
     /**
     *  收款人名称 Setter S_PAYEEACCTNAME , NOT NULL        * */
    public void setSpayeeacctname(String _spayeeacctname) {
        this.spayeeacctname = _spayeeacctname;
    }


    public String getSpayeeacctbankname()
    {
        return spayeeacctbankname;
    }
     /**
     *  收款人银行 Setter S_PAYEEACCTBANKNAME , NOT NULL        * */
    public void setSpayeeacctbankname(String _spayeeacctbankname) {
        this.spayeeacctbankname = _spayeeacctbankname;
    }


    public String getSpayeeacctbankno()
    {
        return spayeeacctbankno;
    }
     /**
     *  收款人银行行号 Setter S_PAYEEACCTBANKNO        * */
    public void setSpayeeacctbankno(String _spayeeacctbankno) {
        this.spayeeacctbankno = _spayeeacctbankno;
    }


    public BigDecimal getNpayamt()
    {
        return npayamt;
    }
     /**
     *  支付金额 Setter N_PAYAMT , NOT NULL        * */
    public void setNpayamt(BigDecimal _npayamt) {
        this.npayamt = _npayamt;
    }


    public String getSxpaydate()
    {
        return sxpaydate;
    }
     /**
     *  实际支付日期 Setter S_XPAYDATE        * */
    public void setSxpaydate(String _sxpaydate) {
        this.sxpaydate = _sxpaydate;
    }


    public String getSxagentbusinessno()
    {
        return sxagentbusinessno;
    }
     /**
     *  银行交易流水号 Setter S_XAGENTBUSINESSNO        * */
    public void setSxagentbusinessno(String _sxagentbusinessno) {
        this.sxagentbusinessno = _sxagentbusinessno;
    }


    public String getSxcheckno()
    {
        return sxcheckno;
    }
     /**
     *  支票号(结算号) Setter S_XCHECKNO        * */
    public void setSxcheckno(String _sxcheckno) {
        this.sxcheckno = _sxcheckno;
    }


    public BigDecimal getNxpayamt()
    {
        return nxpayamt;
    }
     /**
     *  实际支付金额 Setter N_XPAYAMT        * */
    public void setNxpayamt(BigDecimal _nxpayamt) {
        this.nxpayamt = _nxpayamt;
    }


    public String getSxpayeeacctbankname()
    {
        return sxpayeeacctbankname;
    }
     /**
     *  收款人银行 Setter S_XPAYEEACCTBANKNAME        * */
    public void setSxpayeeacctbankname(String _sxpayeeacctbankname) {
        this.sxpayeeacctbankname = _sxpayeeacctbankname;
    }


    public String getSxpayeeacctno()
    {
        return sxpayeeacctno;
    }
     /**
     *  收款人账号 Setter S_XPAYEEACCTNO        * */
    public void setSxpayeeacctno(String _sxpayeeacctno) {
        this.sxpayeeacctno = _sxpayeeacctno;
    }


    public String getSxpayeeacctname()
    {
        return sxpayeeacctname;
    }
     /**
     *  收款人全称 Setter S_XPAYEEACCTNAME        * */
    public void setSxpayeeacctname(String _sxpayeeacctname) {
        this.sxpayeeacctname = _sxpayeeacctname;
    }


    public String getSremark()
    {
        return sremark;
    }
     /**
     *  备注 Setter S_REMARK        * */
    public void setSremark(String _sremark) {
        this.sremark = _sremark;
    }


    public String getShold1()
    {
        return shold1;
    }
     /**
     *  预留字段1 Setter S_HOLD1        * */
    public void setShold1(String _shold1) {
        this.shold1 = _shold1;
    }


    public String getShold2()
    {
        return shold2;
    }
     /**
     *  预留字段2 Setter S_HOLD2        * */
    public void setShold2(String _shold2) {
        this.shold2 = _shold2;
    }


    public String getShold3()
    {
        return shold3;
    }
     /**
     *  预留字段3 Setter S_HOLD3        * */
    public void setShold3(String _shold3) {
        this.shold3 = _shold3;
    }


    public String getShold4()
    {
        return shold4;
    }
     /**
     *  预留字段4 Setter S_HOLD4        * */
    public void setShold4(String _shold4) {
        this.shold4 = _shold4;
    }


    public String getSext1()
    {
        return sext1;
    }
     /**
     *  扩展1 Setter S_EXT1        * */
    public void setSext1(String _sext1) {
        this.sext1 = _sext1;
    }


    public String getSext2()
    {
        return sext2;
    }
     /**
     *  扩展2 Setter S_EXT2        * */
    public void setSext2(String _sext2) {
        this.sext2 = _sext2;
    }


    public String getSext3()
    {
        return sext3;
    }
     /**
     *  扩展3 Setter S_EXT3        * */
    public void setSext3(String _sext3) {
        this.sext3 = _sext3;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *  主键流水号 Getter I_VOUSRLNO, PK , NOT NULL       * */
    public static String  columnIvousrlno()
    {
        return "I_VOUSRLNO";
    }
   
    /**
    *  主键流水号 Getter I_SEQNO, PK , NOT NULL       * */
    public static String  columnIseqno()
    {
        return "I_SEQNO";
    }
   
    /**
    *  支付明细Id Getter S_ID , NOT NULL       * */
    public static String  columnSid()
    {
        return "S_ID";
    }
   
    /**
    *  财政授权支付凭证Id Getter S_VOUCHERBILLID , NOT NULL       * */
    public static String  columnSvoucherbillid()
    {
        return "S_VOUCHERBILLID";
    }
   
    /**
    *  财政授权支付凭证单号 Getter S_VOUCHERBILLNO , NOT NULL       * */
    public static String  columnSvoucherbillno()
    {
        return "S_VOUCHERBILLNO";
    }
   
    /**
    *  支付申请序号 Getter S_VOUCHERNO , NOT NULL       * */
    public static String  columnSvoucherno()
    {
        return "S_VOUCHERNO";
    }
   
    /**
    *  资金性质编码 Getter S_FUNDTYPECODE , NOT NULL       * */
    public static String  columnSfundtypecode()
    {
        return "S_FUNDTYPECODE";
    }
   
    /**
    *  资金性质名称 Getter S_FUNDTYPENAME , NOT NULL       * */
    public static String  columnSfundtypename()
    {
        return "S_FUNDTYPENAME";
    }
   
    /**
    *  预算类型编码 Getter S_BGTTYPECODE       * */
    public static String  columnSbgttypecode()
    {
        return "S_BGTTYPECODE";
    }
   
    /**
    *  预算类型名称 Getter S_BGTTYPENAME       * */
    public static String  columnSbgttypename()
    {
        return "S_BGTTYPENAME";
    }
   
    /**
    *  收支管理编码 Getter S_PROCATCODE       * */
    public static String  columnSprocatcode()
    {
        return "S_PROCATCODE";
    }
   
    /**
    *  收支管理名称 Getter S_PROCATNAME       * */
    public static String  columnSprocatname()
    {
        return "S_PROCATNAME";
    }
   
    /**
    *  支出类型编码 Getter S_PAYKINDCODE       * */
    public static String  columnSpaykindcode()
    {
        return "S_PAYKINDCODE";
    }
   
    /**
    *  支出类型名称 Getter S_PAYKINDNAME       * */
    public static String  columnSpaykindname()
    {
        return "S_PAYKINDNAME";
    }
   
    /**
    *  指标文号编码 Getter S_FILENOCODE       * */
    public static String  columnSfilenocode()
    {
        return "S_FILENOCODE";
    }
   
    /**
    *  指标文号名称 Getter S_FILENONAME       * */
    public static String  columnSfilenoname()
    {
        return "S_FILENONAME";
    }
   
    /**
    *  一级预算单位编码 Getter S_SUPDEPCODE       * */
    public static String  columnSsupdepcode()
    {
        return "S_SUPDEPCODE";
    }
   
    /**
    *  一级预算单位名称 Getter S_SUPDEPNAME       * */
    public static String  columnSsupdepname()
    {
        return "S_SUPDEPNAME";
    }
   
    /**
    *  基层预算单位编码 Getter S_AGENCYCODE , NOT NULL       * */
    public static String  columnSagencycode()
    {
        return "S_AGENCYCODE";
    }
   
    /**
    *  基层预算单位名称 Getter S_AGENCYNAME , NOT NULL       * */
    public static String  columnSagencyname()
    {
        return "S_AGENCYNAME";
    }
   
    /**
    *  功能分类科目编码 Getter S_EXPFUNCCODE , NOT NULL       * */
    public static String  columnSexpfunccode()
    {
        return "S_EXPFUNCCODE";
    }
   
    /**
    *  功能分类科目名称 Getter S_EXPFUNCNAME , NOT NULL       * */
    public static String  columnSexpfuncname()
    {
        return "S_EXPFUNCNAME";
    }
   
    /**
    *  经济分类科目编码 Getter S_EXPECOCODE       * */
    public static String  columnSexpecocode()
    {
        return "S_EXPECOCODE";
    }
   
    /**
    *  经济分类科目名称 Getter S_EXPECONAME       * */
    public static String  columnSexpeconame()
    {
        return "S_EXPECONAME";
    }
   
    /**
    *  预算项目编码 Getter S_DEPPROCODE       * */
    public static String  columnSdepprocode()
    {
        return "S_DEPPROCODE";
    }
   
    /**
    *  预算项目名称 Getter S_DEPPRONAME       * */
    public static String  columnSdepproname()
    {
        return "S_DEPPRONAME";
    }
   
    /**
    *  收款人账号 Getter S_PAYEEACCTNO , NOT NULL       * */
    public static String  columnSpayeeacctno()
    {
        return "S_PAYEEACCTNO";
    }
   
    /**
    *  收款人名称 Getter S_PAYEEACCTNAME , NOT NULL       * */
    public static String  columnSpayeeacctname()
    {
        return "S_PAYEEACCTNAME";
    }
   
    /**
    *  收款人银行 Getter S_PAYEEACCTBANKNAME , NOT NULL       * */
    public static String  columnSpayeeacctbankname()
    {
        return "S_PAYEEACCTBANKNAME";
    }
   
    /**
    *  收款人银行行号 Getter S_PAYEEACCTBANKNO       * */
    public static String  columnSpayeeacctbankno()
    {
        return "S_PAYEEACCTBANKNO";
    }
   
    /**
    *  支付金额 Getter N_PAYAMT , NOT NULL       * */
    public static String  columnNpayamt()
    {
        return "N_PAYAMT";
    }
   
    /**
    *  实际支付日期 Getter S_XPAYDATE       * */
    public static String  columnSxpaydate()
    {
        return "S_XPAYDATE";
    }
   
    /**
    *  银行交易流水号 Getter S_XAGENTBUSINESSNO       * */
    public static String  columnSxagentbusinessno()
    {
        return "S_XAGENTBUSINESSNO";
    }
   
    /**
    *  支票号(结算号) Getter S_XCHECKNO       * */
    public static String  columnSxcheckno()
    {
        return "S_XCHECKNO";
    }
   
    /**
    *  实际支付金额 Getter N_XPAYAMT       * */
    public static String  columnNxpayamt()
    {
        return "N_XPAYAMT";
    }
   
    /**
    *  收款人银行 Getter S_XPAYEEACCTBANKNAME       * */
    public static String  columnSxpayeeacctbankname()
    {
        return "S_XPAYEEACCTBANKNAME";
    }
   
    /**
    *  收款人账号 Getter S_XPAYEEACCTNO       * */
    public static String  columnSxpayeeacctno()
    {
        return "S_XPAYEEACCTNO";
    }
   
    /**
    *  收款人全称 Getter S_XPAYEEACCTNAME       * */
    public static String  columnSxpayeeacctname()
    {
        return "S_XPAYEEACCTNAME";
    }
   
    /**
    *  备注 Getter S_REMARK       * */
    public static String  columnSremark()
    {
        return "S_REMARK";
    }
   
    /**
    *  预留字段1 Getter S_HOLD1       * */
    public static String  columnShold1()
    {
        return "S_HOLD1";
    }
   
    /**
    *  预留字段2 Getter S_HOLD2       * */
    public static String  columnShold2()
    {
        return "S_HOLD2";
    }
   
    /**
    *  预留字段3 Getter S_HOLD3       * */
    public static String  columnShold3()
    {
        return "S_HOLD3";
    }
   
    /**
    *  预留字段4 Getter S_HOLD4       * */
    public static String  columnShold4()
    {
        return "S_HOLD4";
    }
   
    /**
    *  扩展1 Getter S_EXT1       * */
    public static String  columnSext1()
    {
        return "S_EXT1";
    }
   
    /**
    *  扩展2 Getter S_EXT2       * */
    public static String  columnSext2()
    {
        return "S_EXT2";
    }
   
    /**
    *  扩展3 Getter S_EXT3       * */
    public static String  columnSext3()
    {
        return "S_EXT3";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TF_GRANTPAYMSGSUB";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[46];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="I_SEQNO";
        columnNames[2]="S_ID";
        columnNames[3]="S_VOUCHERBILLID";
        columnNames[4]="S_VOUCHERBILLNO";
        columnNames[5]="S_VOUCHERNO";
        columnNames[6]="S_FUNDTYPECODE";
        columnNames[7]="S_FUNDTYPENAME";
        columnNames[8]="S_BGTTYPECODE";
        columnNames[9]="S_BGTTYPENAME";
        columnNames[10]="S_PROCATCODE";
        columnNames[11]="S_PROCATNAME";
        columnNames[12]="S_PAYKINDCODE";
        columnNames[13]="S_PAYKINDNAME";
        columnNames[14]="S_FILENOCODE";
        columnNames[15]="S_FILENONAME";
        columnNames[16]="S_SUPDEPCODE";
        columnNames[17]="S_SUPDEPNAME";
        columnNames[18]="S_AGENCYCODE";
        columnNames[19]="S_AGENCYNAME";
        columnNames[20]="S_EXPFUNCCODE";
        columnNames[21]="S_EXPFUNCNAME";
        columnNames[22]="S_EXPECOCODE";
        columnNames[23]="S_EXPECONAME";
        columnNames[24]="S_DEPPROCODE";
        columnNames[25]="S_DEPPRONAME";
        columnNames[26]="S_PAYEEACCTNO";
        columnNames[27]="S_PAYEEACCTNAME";
        columnNames[28]="S_PAYEEACCTBANKNAME";
        columnNames[29]="S_PAYEEACCTBANKNO";
        columnNames[30]="N_PAYAMT";
        columnNames[31]="S_XPAYDATE";
        columnNames[32]="S_XAGENTBUSINESSNO";
        columnNames[33]="S_XCHECKNO";
        columnNames[34]="N_XPAYAMT";
        columnNames[35]="S_XPAYEEACCTBANKNAME";
        columnNames[36]="S_XPAYEEACCTNO";
        columnNames[37]="S_XPAYEEACCTNAME";
        columnNames[38]="S_REMARK";
        columnNames[39]="S_HOLD1";
        columnNames[40]="S_HOLD2";
        columnNames[41]="S_HOLD3";
        columnNames[42]="S_HOLD4";
        columnNames[43]="S_EXT1";
        columnNames[44]="S_EXT2";
        columnNames[45]="S_EXT3";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TfGrantpaymsgsubDto))
            return false;

        TfGrantpaymsgsubDto bean = (TfGrantpaymsgsubDto) obj;


      //compare field ivousrlno
      if((this.ivousrlno==null && bean.ivousrlno!=null) || (this.ivousrlno!=null && bean.ivousrlno==null))
          return false;
        else if(this.ivousrlno==null && bean.ivousrlno==null){
        }
        else{
          if(!bean.ivousrlno.equals(this.ivousrlno))
               return false;
     }
      //compare field iseqno
      if((this.iseqno==null && bean.iseqno!=null) || (this.iseqno!=null && bean.iseqno==null))
          return false;
        else if(this.iseqno==null && bean.iseqno==null){
        }
        else{
          if(!bean.iseqno.equals(this.iseqno))
               return false;
     }
      //compare field sid
      if((this.sid==null && bean.sid!=null) || (this.sid!=null && bean.sid==null))
          return false;
        else if(this.sid==null && bean.sid==null){
        }
        else{
          if(!bean.sid.equals(this.sid))
               return false;
     }
      //compare field svoucherbillid
      if((this.svoucherbillid==null && bean.svoucherbillid!=null) || (this.svoucherbillid!=null && bean.svoucherbillid==null))
          return false;
        else if(this.svoucherbillid==null && bean.svoucherbillid==null){
        }
        else{
          if(!bean.svoucherbillid.equals(this.svoucherbillid))
               return false;
     }
      //compare field svoucherbillno
      if((this.svoucherbillno==null && bean.svoucherbillno!=null) || (this.svoucherbillno!=null && bean.svoucherbillno==null))
          return false;
        else if(this.svoucherbillno==null && bean.svoucherbillno==null){
        }
        else{
          if(!bean.svoucherbillno.equals(this.svoucherbillno))
               return false;
     }
      //compare field svoucherno
      if((this.svoucherno==null && bean.svoucherno!=null) || (this.svoucherno!=null && bean.svoucherno==null))
          return false;
        else if(this.svoucherno==null && bean.svoucherno==null){
        }
        else{
          if(!bean.svoucherno.equals(this.svoucherno))
               return false;
     }
      //compare field sfundtypecode
      if((this.sfundtypecode==null && bean.sfundtypecode!=null) || (this.sfundtypecode!=null && bean.sfundtypecode==null))
          return false;
        else if(this.sfundtypecode==null && bean.sfundtypecode==null){
        }
        else{
          if(!bean.sfundtypecode.equals(this.sfundtypecode))
               return false;
     }
      //compare field sfundtypename
      if((this.sfundtypename==null && bean.sfundtypename!=null) || (this.sfundtypename!=null && bean.sfundtypename==null))
          return false;
        else if(this.sfundtypename==null && bean.sfundtypename==null){
        }
        else{
          if(!bean.sfundtypename.equals(this.sfundtypename))
               return false;
     }
      //compare field sbgttypecode
      if((this.sbgttypecode==null && bean.sbgttypecode!=null) || (this.sbgttypecode!=null && bean.sbgttypecode==null))
          return false;
        else if(this.sbgttypecode==null && bean.sbgttypecode==null){
        }
        else{
          if(!bean.sbgttypecode.equals(this.sbgttypecode))
               return false;
     }
      //compare field sbgttypename
      if((this.sbgttypename==null && bean.sbgttypename!=null) || (this.sbgttypename!=null && bean.sbgttypename==null))
          return false;
        else if(this.sbgttypename==null && bean.sbgttypename==null){
        }
        else{
          if(!bean.sbgttypename.equals(this.sbgttypename))
               return false;
     }
      //compare field sprocatcode
      if((this.sprocatcode==null && bean.sprocatcode!=null) || (this.sprocatcode!=null && bean.sprocatcode==null))
          return false;
        else if(this.sprocatcode==null && bean.sprocatcode==null){
        }
        else{
          if(!bean.sprocatcode.equals(this.sprocatcode))
               return false;
     }
      //compare field sprocatname
      if((this.sprocatname==null && bean.sprocatname!=null) || (this.sprocatname!=null && bean.sprocatname==null))
          return false;
        else if(this.sprocatname==null && bean.sprocatname==null){
        }
        else{
          if(!bean.sprocatname.equals(this.sprocatname))
               return false;
     }
      //compare field spaykindcode
      if((this.spaykindcode==null && bean.spaykindcode!=null) || (this.spaykindcode!=null && bean.spaykindcode==null))
          return false;
        else if(this.spaykindcode==null && bean.spaykindcode==null){
        }
        else{
          if(!bean.spaykindcode.equals(this.spaykindcode))
               return false;
     }
      //compare field spaykindname
      if((this.spaykindname==null && bean.spaykindname!=null) || (this.spaykindname!=null && bean.spaykindname==null))
          return false;
        else if(this.spaykindname==null && bean.spaykindname==null){
        }
        else{
          if(!bean.spaykindname.equals(this.spaykindname))
               return false;
     }
      //compare field sfilenocode
      if((this.sfilenocode==null && bean.sfilenocode!=null) || (this.sfilenocode!=null && bean.sfilenocode==null))
          return false;
        else if(this.sfilenocode==null && bean.sfilenocode==null){
        }
        else{
          if(!bean.sfilenocode.equals(this.sfilenocode))
               return false;
     }
      //compare field sfilenoname
      if((this.sfilenoname==null && bean.sfilenoname!=null) || (this.sfilenoname!=null && bean.sfilenoname==null))
          return false;
        else if(this.sfilenoname==null && bean.sfilenoname==null){
        }
        else{
          if(!bean.sfilenoname.equals(this.sfilenoname))
               return false;
     }
      //compare field ssupdepcode
      if((this.ssupdepcode==null && bean.ssupdepcode!=null) || (this.ssupdepcode!=null && bean.ssupdepcode==null))
          return false;
        else if(this.ssupdepcode==null && bean.ssupdepcode==null){
        }
        else{
          if(!bean.ssupdepcode.equals(this.ssupdepcode))
               return false;
     }
      //compare field ssupdepname
      if((this.ssupdepname==null && bean.ssupdepname!=null) || (this.ssupdepname!=null && bean.ssupdepname==null))
          return false;
        else if(this.ssupdepname==null && bean.ssupdepname==null){
        }
        else{
          if(!bean.ssupdepname.equals(this.ssupdepname))
               return false;
     }
      //compare field sagencycode
      if((this.sagencycode==null && bean.sagencycode!=null) || (this.sagencycode!=null && bean.sagencycode==null))
          return false;
        else if(this.sagencycode==null && bean.sagencycode==null){
        }
        else{
          if(!bean.sagencycode.equals(this.sagencycode))
               return false;
     }
      //compare field sagencyname
      if((this.sagencyname==null && bean.sagencyname!=null) || (this.sagencyname!=null && bean.sagencyname==null))
          return false;
        else if(this.sagencyname==null && bean.sagencyname==null){
        }
        else{
          if(!bean.sagencyname.equals(this.sagencyname))
               return false;
     }
      //compare field sexpfunccode
      if((this.sexpfunccode==null && bean.sexpfunccode!=null) || (this.sexpfunccode!=null && bean.sexpfunccode==null))
          return false;
        else if(this.sexpfunccode==null && bean.sexpfunccode==null){
        }
        else{
          if(!bean.sexpfunccode.equals(this.sexpfunccode))
               return false;
     }
      //compare field sexpfuncname
      if((this.sexpfuncname==null && bean.sexpfuncname!=null) || (this.sexpfuncname!=null && bean.sexpfuncname==null))
          return false;
        else if(this.sexpfuncname==null && bean.sexpfuncname==null){
        }
        else{
          if(!bean.sexpfuncname.equals(this.sexpfuncname))
               return false;
     }
      //compare field sexpecocode
      if((this.sexpecocode==null && bean.sexpecocode!=null) || (this.sexpecocode!=null && bean.sexpecocode==null))
          return false;
        else if(this.sexpecocode==null && bean.sexpecocode==null){
        }
        else{
          if(!bean.sexpecocode.equals(this.sexpecocode))
               return false;
     }
      //compare field sexpeconame
      if((this.sexpeconame==null && bean.sexpeconame!=null) || (this.sexpeconame!=null && bean.sexpeconame==null))
          return false;
        else if(this.sexpeconame==null && bean.sexpeconame==null){
        }
        else{
          if(!bean.sexpeconame.equals(this.sexpeconame))
               return false;
     }
      //compare field sdepprocode
      if((this.sdepprocode==null && bean.sdepprocode!=null) || (this.sdepprocode!=null && bean.sdepprocode==null))
          return false;
        else if(this.sdepprocode==null && bean.sdepprocode==null){
        }
        else{
          if(!bean.sdepprocode.equals(this.sdepprocode))
               return false;
     }
      //compare field sdepproname
      if((this.sdepproname==null && bean.sdepproname!=null) || (this.sdepproname!=null && bean.sdepproname==null))
          return false;
        else if(this.sdepproname==null && bean.sdepproname==null){
        }
        else{
          if(!bean.sdepproname.equals(this.sdepproname))
               return false;
     }
      //compare field spayeeacctno
      if((this.spayeeacctno==null && bean.spayeeacctno!=null) || (this.spayeeacctno!=null && bean.spayeeacctno==null))
          return false;
        else if(this.spayeeacctno==null && bean.spayeeacctno==null){
        }
        else{
          if(!bean.spayeeacctno.equals(this.spayeeacctno))
               return false;
     }
      //compare field spayeeacctname
      if((this.spayeeacctname==null && bean.spayeeacctname!=null) || (this.spayeeacctname!=null && bean.spayeeacctname==null))
          return false;
        else if(this.spayeeacctname==null && bean.spayeeacctname==null){
        }
        else{
          if(!bean.spayeeacctname.equals(this.spayeeacctname))
               return false;
     }
      //compare field spayeeacctbankname
      if((this.spayeeacctbankname==null && bean.spayeeacctbankname!=null) || (this.spayeeacctbankname!=null && bean.spayeeacctbankname==null))
          return false;
        else if(this.spayeeacctbankname==null && bean.spayeeacctbankname==null){
        }
        else{
          if(!bean.spayeeacctbankname.equals(this.spayeeacctbankname))
               return false;
     }
      //compare field spayeeacctbankno
      if((this.spayeeacctbankno==null && bean.spayeeacctbankno!=null) || (this.spayeeacctbankno!=null && bean.spayeeacctbankno==null))
          return false;
        else if(this.spayeeacctbankno==null && bean.spayeeacctbankno==null){
        }
        else{
          if(!bean.spayeeacctbankno.equals(this.spayeeacctbankno))
               return false;
     }
      //compare field npayamt
      if((this.npayamt==null && bean.npayamt!=null) || (this.npayamt!=null && bean.npayamt==null))
          return false;
        else if(this.npayamt==null && bean.npayamt==null){
        }
        else{
          if(!bean.npayamt.equals(this.npayamt))
               return false;
     }
      //compare field sxpaydate
      if((this.sxpaydate==null && bean.sxpaydate!=null) || (this.sxpaydate!=null && bean.sxpaydate==null))
          return false;
        else if(this.sxpaydate==null && bean.sxpaydate==null){
        }
        else{
          if(!bean.sxpaydate.equals(this.sxpaydate))
               return false;
     }
      //compare field sxagentbusinessno
      if((this.sxagentbusinessno==null && bean.sxagentbusinessno!=null) || (this.sxagentbusinessno!=null && bean.sxagentbusinessno==null))
          return false;
        else if(this.sxagentbusinessno==null && bean.sxagentbusinessno==null){
        }
        else{
          if(!bean.sxagentbusinessno.equals(this.sxagentbusinessno))
               return false;
     }
      //compare field sxcheckno
      if((this.sxcheckno==null && bean.sxcheckno!=null) || (this.sxcheckno!=null && bean.sxcheckno==null))
          return false;
        else if(this.sxcheckno==null && bean.sxcheckno==null){
        }
        else{
          if(!bean.sxcheckno.equals(this.sxcheckno))
               return false;
     }
      //compare field nxpayamt
      if((this.nxpayamt==null && bean.nxpayamt!=null) || (this.nxpayamt!=null && bean.nxpayamt==null))
          return false;
        else if(this.nxpayamt==null && bean.nxpayamt==null){
        }
        else{
          if(!bean.nxpayamt.equals(this.nxpayamt))
               return false;
     }
      //compare field sxpayeeacctbankname
      if((this.sxpayeeacctbankname==null && bean.sxpayeeacctbankname!=null) || (this.sxpayeeacctbankname!=null && bean.sxpayeeacctbankname==null))
          return false;
        else if(this.sxpayeeacctbankname==null && bean.sxpayeeacctbankname==null){
        }
        else{
          if(!bean.sxpayeeacctbankname.equals(this.sxpayeeacctbankname))
               return false;
     }
      //compare field sxpayeeacctno
      if((this.sxpayeeacctno==null && bean.sxpayeeacctno!=null) || (this.sxpayeeacctno!=null && bean.sxpayeeacctno==null))
          return false;
        else if(this.sxpayeeacctno==null && bean.sxpayeeacctno==null){
        }
        else{
          if(!bean.sxpayeeacctno.equals(this.sxpayeeacctno))
               return false;
     }
      //compare field sxpayeeacctname
      if((this.sxpayeeacctname==null && bean.sxpayeeacctname!=null) || (this.sxpayeeacctname!=null && bean.sxpayeeacctname==null))
          return false;
        else if(this.sxpayeeacctname==null && bean.sxpayeeacctname==null){
        }
        else{
          if(!bean.sxpayeeacctname.equals(this.sxpayeeacctname))
               return false;
     }
      //compare field sremark
      if((this.sremark==null && bean.sremark!=null) || (this.sremark!=null && bean.sremark==null))
          return false;
        else if(this.sremark==null && bean.sremark==null){
        }
        else{
          if(!bean.sremark.equals(this.sremark))
               return false;
     }
      //compare field shold1
      if((this.shold1==null && bean.shold1!=null) || (this.shold1!=null && bean.shold1==null))
          return false;
        else if(this.shold1==null && bean.shold1==null){
        }
        else{
          if(!bean.shold1.equals(this.shold1))
               return false;
     }
      //compare field shold2
      if((this.shold2==null && bean.shold2!=null) || (this.shold2!=null && bean.shold2==null))
          return false;
        else if(this.shold2==null && bean.shold2==null){
        }
        else{
          if(!bean.shold2.equals(this.shold2))
               return false;
     }
      //compare field shold3
      if((this.shold3==null && bean.shold3!=null) || (this.shold3!=null && bean.shold3==null))
          return false;
        else if(this.shold3==null && bean.shold3==null){
        }
        else{
          if(!bean.shold3.equals(this.shold3))
               return false;
     }
      //compare field shold4
      if((this.shold4==null && bean.shold4!=null) || (this.shold4!=null && bean.shold4==null))
          return false;
        else if(this.shold4==null && bean.shold4==null){
        }
        else{
          if(!bean.shold4.equals(this.shold4))
               return false;
     }
      //compare field sext1
      if((this.sext1==null && bean.sext1!=null) || (this.sext1!=null && bean.sext1==null))
          return false;
        else if(this.sext1==null && bean.sext1==null){
        }
        else{
          if(!bean.sext1.equals(this.sext1))
               return false;
     }
      //compare field sext2
      if((this.sext2==null && bean.sext2!=null) || (this.sext2!=null && bean.sext2==null))
          return false;
        else if(this.sext2==null && bean.sext2==null){
        }
        else{
          if(!bean.sext2.equals(this.sext2))
               return false;
     }
      //compare field sext3
      if((this.sext3==null && bean.sext3!=null) || (this.sext3!=null && bean.sext3==null))
          return false;
        else if(this.sext3==null && bean.sext3==null){
        }
        else{
          if(!bean.sext3.equals(this.sext3))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.ivousrlno!=null)
          _hash_ = _hash_ * 31+ this.ivousrlno.hashCode() ;
        if(this.iseqno!=null)
          _hash_ = _hash_ * 31+ this.iseqno.hashCode() ;
        if(this.sid!=null)
          _hash_ = _hash_ * 31+ this.sid.hashCode() ;
        if(this.svoucherbillid!=null)
          _hash_ = _hash_ * 31+ this.svoucherbillid.hashCode() ;
        if(this.svoucherbillno!=null)
          _hash_ = _hash_ * 31+ this.svoucherbillno.hashCode() ;
        if(this.svoucherno!=null)
          _hash_ = _hash_ * 31+ this.svoucherno.hashCode() ;
        if(this.sfundtypecode!=null)
          _hash_ = _hash_ * 31+ this.sfundtypecode.hashCode() ;
        if(this.sfundtypename!=null)
          _hash_ = _hash_ * 31+ this.sfundtypename.hashCode() ;
        if(this.sbgttypecode!=null)
          _hash_ = _hash_ * 31+ this.sbgttypecode.hashCode() ;
        if(this.sbgttypename!=null)
          _hash_ = _hash_ * 31+ this.sbgttypename.hashCode() ;
        if(this.sprocatcode!=null)
          _hash_ = _hash_ * 31+ this.sprocatcode.hashCode() ;
        if(this.sprocatname!=null)
          _hash_ = _hash_ * 31+ this.sprocatname.hashCode() ;
        if(this.spaykindcode!=null)
          _hash_ = _hash_ * 31+ this.spaykindcode.hashCode() ;
        if(this.spaykindname!=null)
          _hash_ = _hash_ * 31+ this.spaykindname.hashCode() ;
        if(this.sfilenocode!=null)
          _hash_ = _hash_ * 31+ this.sfilenocode.hashCode() ;
        if(this.sfilenoname!=null)
          _hash_ = _hash_ * 31+ this.sfilenoname.hashCode() ;
        if(this.ssupdepcode!=null)
          _hash_ = _hash_ * 31+ this.ssupdepcode.hashCode() ;
        if(this.ssupdepname!=null)
          _hash_ = _hash_ * 31+ this.ssupdepname.hashCode() ;
        if(this.sagencycode!=null)
          _hash_ = _hash_ * 31+ this.sagencycode.hashCode() ;
        if(this.sagencyname!=null)
          _hash_ = _hash_ * 31+ this.sagencyname.hashCode() ;
        if(this.sexpfunccode!=null)
          _hash_ = _hash_ * 31+ this.sexpfunccode.hashCode() ;
        if(this.sexpfuncname!=null)
          _hash_ = _hash_ * 31+ this.sexpfuncname.hashCode() ;
        if(this.sexpecocode!=null)
          _hash_ = _hash_ * 31+ this.sexpecocode.hashCode() ;
        if(this.sexpeconame!=null)
          _hash_ = _hash_ * 31+ this.sexpeconame.hashCode() ;
        if(this.sdepprocode!=null)
          _hash_ = _hash_ * 31+ this.sdepprocode.hashCode() ;
        if(this.sdepproname!=null)
          _hash_ = _hash_ * 31+ this.sdepproname.hashCode() ;
        if(this.spayeeacctno!=null)
          _hash_ = _hash_ * 31+ this.spayeeacctno.hashCode() ;
        if(this.spayeeacctname!=null)
          _hash_ = _hash_ * 31+ this.spayeeacctname.hashCode() ;
        if(this.spayeeacctbankname!=null)
          _hash_ = _hash_ * 31+ this.spayeeacctbankname.hashCode() ;
        if(this.spayeeacctbankno!=null)
          _hash_ = _hash_ * 31+ this.spayeeacctbankno.hashCode() ;
        if(this.npayamt!=null)
          _hash_ = _hash_ * 31+ this.npayamt.hashCode() ;
        if(this.sxpaydate!=null)
          _hash_ = _hash_ * 31+ this.sxpaydate.hashCode() ;
        if(this.sxagentbusinessno!=null)
          _hash_ = _hash_ * 31+ this.sxagentbusinessno.hashCode() ;
        if(this.sxcheckno!=null)
          _hash_ = _hash_ * 31+ this.sxcheckno.hashCode() ;
        if(this.nxpayamt!=null)
          _hash_ = _hash_ * 31+ this.nxpayamt.hashCode() ;
        if(this.sxpayeeacctbankname!=null)
          _hash_ = _hash_ * 31+ this.sxpayeeacctbankname.hashCode() ;
        if(this.sxpayeeacctno!=null)
          _hash_ = _hash_ * 31+ this.sxpayeeacctno.hashCode() ;
        if(this.sxpayeeacctname!=null)
          _hash_ = _hash_ * 31+ this.sxpayeeacctname.hashCode() ;
        if(this.sremark!=null)
          _hash_ = _hash_ * 31+ this.sremark.hashCode() ;
        if(this.shold1!=null)
          _hash_ = _hash_ * 31+ this.shold1.hashCode() ;
        if(this.shold2!=null)
          _hash_ = _hash_ * 31+ this.shold2.hashCode() ;
        if(this.shold3!=null)
          _hash_ = _hash_ * 31+ this.shold3.hashCode() ;
        if(this.shold4!=null)
          _hash_ = _hash_ * 31+ this.shold4.hashCode() ;
        if(this.sext1!=null)
          _hash_ = _hash_ * 31+ this.sext1.hashCode() ;
        if(this.sext2!=null)
          _hash_ = _hash_ * 31+ this.sext2.hashCode() ;
        if(this.sext3!=null)
          _hash_ = _hash_ * 31+ this.sext3.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TfGrantpaymsgsubDto bean = new TfGrantpaymsgsubDto();

          bean.ivousrlno = this.ivousrlno;

          bean.iseqno = this.iseqno;

          if (this.sid != null)
            bean.sid = new String(this.sid);
          if (this.svoucherbillid != null)
            bean.svoucherbillid = new String(this.svoucherbillid);
          if (this.svoucherbillno != null)
            bean.svoucherbillno = new String(this.svoucherbillno);
          if (this.svoucherno != null)
            bean.svoucherno = new String(this.svoucherno);
          if (this.sfundtypecode != null)
            bean.sfundtypecode = new String(this.sfundtypecode);
          if (this.sfundtypename != null)
            bean.sfundtypename = new String(this.sfundtypename);
          if (this.sbgttypecode != null)
            bean.sbgttypecode = new String(this.sbgttypecode);
          if (this.sbgttypename != null)
            bean.sbgttypename = new String(this.sbgttypename);
          if (this.sprocatcode != null)
            bean.sprocatcode = new String(this.sprocatcode);
          if (this.sprocatname != null)
            bean.sprocatname = new String(this.sprocatname);
          if (this.spaykindcode != null)
            bean.spaykindcode = new String(this.spaykindcode);
          if (this.spaykindname != null)
            bean.spaykindname = new String(this.spaykindname);
          if (this.sfilenocode != null)
            bean.sfilenocode = new String(this.sfilenocode);
          if (this.sfilenoname != null)
            bean.sfilenoname = new String(this.sfilenoname);
          if (this.ssupdepcode != null)
            bean.ssupdepcode = new String(this.ssupdepcode);
          if (this.ssupdepname != null)
            bean.ssupdepname = new String(this.ssupdepname);
          if (this.sagencycode != null)
            bean.sagencycode = new String(this.sagencycode);
          if (this.sagencyname != null)
            bean.sagencyname = new String(this.sagencyname);
          if (this.sexpfunccode != null)
            bean.sexpfunccode = new String(this.sexpfunccode);
          if (this.sexpfuncname != null)
            bean.sexpfuncname = new String(this.sexpfuncname);
          if (this.sexpecocode != null)
            bean.sexpecocode = new String(this.sexpecocode);
          if (this.sexpeconame != null)
            bean.sexpeconame = new String(this.sexpeconame);
          if (this.sdepprocode != null)
            bean.sdepprocode = new String(this.sdepprocode);
          if (this.sdepproname != null)
            bean.sdepproname = new String(this.sdepproname);
          if (this.spayeeacctno != null)
            bean.spayeeacctno = new String(this.spayeeacctno);
          if (this.spayeeacctname != null)
            bean.spayeeacctname = new String(this.spayeeacctname);
          if (this.spayeeacctbankname != null)
            bean.spayeeacctbankname = new String(this.spayeeacctbankname);
          if (this.spayeeacctbankno != null)
            bean.spayeeacctbankno = new String(this.spayeeacctbankno);
          if (this.npayamt != null)
            bean.npayamt = new BigDecimal(this.npayamt.toString());
          if (this.sxpaydate != null)
            bean.sxpaydate = new String(this.sxpaydate);
          if (this.sxagentbusinessno != null)
            bean.sxagentbusinessno = new String(this.sxagentbusinessno);
          if (this.sxcheckno != null)
            bean.sxcheckno = new String(this.sxcheckno);
          if (this.nxpayamt != null)
            bean.nxpayamt = new BigDecimal(this.nxpayamt.toString());
          if (this.sxpayeeacctbankname != null)
            bean.sxpayeeacctbankname = new String(this.sxpayeeacctbankname);
          if (this.sxpayeeacctno != null)
            bean.sxpayeeacctno = new String(this.sxpayeeacctno);
          if (this.sxpayeeacctname != null)
            bean.sxpayeeacctname = new String(this.sxpayeeacctname);
          if (this.sremark != null)
            bean.sremark = new String(this.sremark);
          if (this.shold1 != null)
            bean.shold1 = new String(this.shold1);
          if (this.shold2 != null)
            bean.shold2 = new String(this.shold2);
          if (this.shold3 != null)
            bean.shold3 = new String(this.shold3);
          if (this.shold4 != null)
            bean.shold4 = new String(this.shold4);
          if (this.sext1 != null)
            bean.sext1 = new String(this.sext1);
          if (this.sext2 != null)
            bean.sext2 = new String(this.sext2);
          if (this.sext3 != null)
            bean.sext3 = new String(this.sext3);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TfGrantpaymsgsubDto").append(sep);
        sb.append("[ivousrlno]").append(" = ").append(ivousrlno).append(sep);
        sb.append("[iseqno]").append(" = ").append(iseqno).append(sep);
        sb.append("[sid]").append(" = ").append(sid).append(sep);
        sb.append("[svoucherbillid]").append(" = ").append(svoucherbillid).append(sep);
        sb.append("[svoucherbillno]").append(" = ").append(svoucherbillno).append(sep);
        sb.append("[svoucherno]").append(" = ").append(svoucherno).append(sep);
        sb.append("[sfundtypecode]").append(" = ").append(sfundtypecode).append(sep);
        sb.append("[sfundtypename]").append(" = ").append(sfundtypename).append(sep);
        sb.append("[sbgttypecode]").append(" = ").append(sbgttypecode).append(sep);
        sb.append("[sbgttypename]").append(" = ").append(sbgttypename).append(sep);
        sb.append("[sprocatcode]").append(" = ").append(sprocatcode).append(sep);
        sb.append("[sprocatname]").append(" = ").append(sprocatname).append(sep);
        sb.append("[spaykindcode]").append(" = ").append(spaykindcode).append(sep);
        sb.append("[spaykindname]").append(" = ").append(spaykindname).append(sep);
        sb.append("[sfilenocode]").append(" = ").append(sfilenocode).append(sep);
        sb.append("[sfilenoname]").append(" = ").append(sfilenoname).append(sep);
        sb.append("[ssupdepcode]").append(" = ").append(ssupdepcode).append(sep);
        sb.append("[ssupdepname]").append(" = ").append(ssupdepname).append(sep);
        sb.append("[sagencycode]").append(" = ").append(sagencycode).append(sep);
        sb.append("[sagencyname]").append(" = ").append(sagencyname).append(sep);
        sb.append("[sexpfunccode]").append(" = ").append(sexpfunccode).append(sep);
        sb.append("[sexpfuncname]").append(" = ").append(sexpfuncname).append(sep);
        sb.append("[sexpecocode]").append(" = ").append(sexpecocode).append(sep);
        sb.append("[sexpeconame]").append(" = ").append(sexpeconame).append(sep);
        sb.append("[sdepprocode]").append(" = ").append(sdepprocode).append(sep);
        sb.append("[sdepproname]").append(" = ").append(sdepproname).append(sep);
        sb.append("[spayeeacctno]").append(" = ").append(spayeeacctno).append(sep);
        sb.append("[spayeeacctname]").append(" = ").append(spayeeacctname).append(sep);
        sb.append("[spayeeacctbankname]").append(" = ").append(spayeeacctbankname).append(sep);
        sb.append("[spayeeacctbankno]").append(" = ").append(spayeeacctbankno).append(sep);
        sb.append("[npayamt]").append(" = ").append(npayamt).append(sep);
        sb.append("[sxpaydate]").append(" = ").append(sxpaydate).append(sep);
        sb.append("[sxagentbusinessno]").append(" = ").append(sxagentbusinessno).append(sep);
        sb.append("[sxcheckno]").append(" = ").append(sxcheckno).append(sep);
        sb.append("[nxpayamt]").append(" = ").append(nxpayamt).append(sep);
        sb.append("[sxpayeeacctbankname]").append(" = ").append(sxpayeeacctbankname).append(sep);
        sb.append("[sxpayeeacctno]").append(" = ").append(sxpayeeacctno).append(sep);
        sb.append("[sxpayeeacctname]").append(" = ").append(sxpayeeacctname).append(sep);
        sb.append("[sremark]").append(" = ").append(sremark).append(sep);
        sb.append("[shold1]").append(" = ").append(shold1).append(sep);
        sb.append("[shold2]").append(" = ").append(shold2).append(sep);
        sb.append("[shold3]").append(" = ").append(shold3).append(sep);
        sb.append("[shold4]").append(" = ").append(shold4).append(sep);
        sb.append("[sext1]").append(" = ").append(sext1).append(sep);
        sb.append("[sext2]").append(" = ").append(sext2).append(sep);
        sb.append("[sext3]").append(" = ").append(sext3).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field I_VOUSRLNO
      if (this.getIvousrlno()==null)
             sb.append("I_VOUSRLNO主键流水号不能为空; ");
      
    //check field I_SEQNO
      if (this.getIseqno()==null)
             sb.append("I_SEQNO主键流水号不能为空; ");
      
    //check field S_ID
      if (this.getSid()==null)
             sb.append("S_ID支付明细Id不能为空; ");
      if (this.getSid()!=null)
             if (this.getSid().getBytes().length > 38)
                sb.append("S_ID支付明细Id宽度不能超过 "+38+"个字符; ");
    
    //check field S_VOUCHERBILLID
      if (this.getSvoucherbillid()==null)
             sb.append("S_VOUCHERBILLID财政授权支付凭证Id不能为空; ");
      if (this.getSvoucherbillid()!=null)
             if (this.getSvoucherbillid().getBytes().length > 38)
                sb.append("S_VOUCHERBILLID财政授权支付凭证Id宽度不能超过 "+38+"个字符; ");
    
    //check field S_VOUCHERBILLNO
      if (this.getSvoucherbillno()==null)
             sb.append("S_VOUCHERBILLNO财政授权支付凭证单号不能为空; ");
      if (this.getSvoucherbillno()!=null)
             if (this.getSvoucherbillno().getBytes().length > 42)
                sb.append("S_VOUCHERBILLNO财政授权支付凭证单号宽度不能超过 "+42+"个字符; ");
    
    //check field S_VOUCHERNO
      if (this.getSvoucherno()==null)
             sb.append("S_VOUCHERNO支付申请序号不能为空; ");
      if (this.getSvoucherno()!=null)
             if (this.getSvoucherno().getBytes().length > 42)
                sb.append("S_VOUCHERNO支付申请序号宽度不能超过 "+42+"个字符; ");
    
    //check field S_FUNDTYPECODE
      if (this.getSfundtypecode()==null)
             sb.append("S_FUNDTYPECODE资金性质编码不能为空; ");
      if (this.getSfundtypecode()!=null)
             if (this.getSfundtypecode().getBytes().length > 42)
                sb.append("S_FUNDTYPECODE资金性质编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_FUNDTYPENAME
      if (this.getSfundtypename()==null)
             sb.append("S_FUNDTYPENAME资金性质名称不能为空; ");
      if (this.getSfundtypename()!=null)
             if (this.getSfundtypename().getBytes().length > 60)
                sb.append("S_FUNDTYPENAME资金性质名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_BGTTYPECODE
      if (this.getSbgttypecode()!=null)
             if (this.getSbgttypecode().getBytes().length > 60)
                sb.append("S_BGTTYPECODE预算类型编码宽度不能超过 "+60+"个字符; ");
    
    //check field S_BGTTYPENAME
      if (this.getSbgttypename()!=null)
             if (this.getSbgttypename().getBytes().length > 60)
                sb.append("S_BGTTYPENAME预算类型名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_PROCATCODE
      if (this.getSprocatcode()!=null)
             if (this.getSprocatcode().getBytes().length > 42)
                sb.append("S_PROCATCODE收支管理编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_PROCATNAME
      if (this.getSprocatname()!=null)
             if (this.getSprocatname().getBytes().length > 60)
                sb.append("S_PROCATNAME收支管理名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_PAYKINDCODE
      if (this.getSpaykindcode()!=null)
             if (this.getSpaykindcode().getBytes().length > 42)
                sb.append("S_PAYKINDCODE支出类型编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_PAYKINDNAME
      if (this.getSpaykindname()!=null)
             if (this.getSpaykindname().getBytes().length > 60)
                sb.append("S_PAYKINDNAME支出类型名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_FILENOCODE
      if (this.getSfilenocode()!=null)
             if (this.getSfilenocode().getBytes().length > 42)
                sb.append("S_FILENOCODE指标文号编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_FILENONAME
      if (this.getSfilenoname()!=null)
             if (this.getSfilenoname().getBytes().length > 100)
                sb.append("S_FILENONAME指标文号名称宽度不能超过 "+100+"个字符; ");
    
    //check field S_SUPDEPCODE
      if (this.getSsupdepcode()!=null)
             if (this.getSsupdepcode().getBytes().length > 42)
                sb.append("S_SUPDEPCODE一级预算单位编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_SUPDEPNAME
      if (this.getSsupdepname()!=null)
             if (this.getSsupdepname().getBytes().length > 60)
                sb.append("S_SUPDEPNAME一级预算单位名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_AGENCYCODE
      if (this.getSagencycode()==null)
             sb.append("S_AGENCYCODE基层预算单位编码不能为空; ");
      if (this.getSagencycode()!=null)
             if (this.getSagencycode().getBytes().length > 42)
                sb.append("S_AGENCYCODE基层预算单位编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_AGENCYNAME
      if (this.getSagencyname()==null)
             sb.append("S_AGENCYNAME基层预算单位名称不能为空; ");
      if (this.getSagencyname()!=null)
             if (this.getSagencyname().getBytes().length > 60)
                sb.append("S_AGENCYNAME基层预算单位名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPFUNCCODE
      if (this.getSexpfunccode()==null)
             sb.append("S_EXPFUNCCODE功能分类科目编码不能为空; ");
      if (this.getSexpfunccode()!=null)
             if (this.getSexpfunccode().getBytes().length > 42)
                sb.append("S_EXPFUNCCODE功能分类科目编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPFUNCNAME
      if (this.getSexpfuncname()==null)
             sb.append("S_EXPFUNCNAME功能分类科目名称不能为空; ");
      if (this.getSexpfuncname()!=null)
             if (this.getSexpfuncname().getBytes().length > 60)
                sb.append("S_EXPFUNCNAME功能分类科目名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPECOCODE
      if (this.getSexpecocode()!=null)
             if (this.getSexpecocode().getBytes().length > 42)
                sb.append("S_EXPECOCODE经济分类科目编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPECONAME
      if (this.getSexpeconame()!=null)
             if (this.getSexpeconame().getBytes().length > 60)
                sb.append("S_EXPECONAME经济分类科目名称宽度不能超过 "+60+"个字符; ");
    
    //check field S_DEPPROCODE
      if (this.getSdepprocode()!=null)
             if (this.getSdepprocode().getBytes().length > 42)
                sb.append("S_DEPPROCODE预算项目编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_DEPPRONAME
      if (this.getSdepproname()!=null)
             if (this.getSdepproname().getBytes().length > 200)
                sb.append("S_DEPPRONAME预算项目名称宽度不能超过 "+200+"个字符; ");
    
    //check field S_PAYEEACCTNO
      if (this.getSpayeeacctno()==null)
             sb.append("S_PAYEEACCTNO收款人账号不能为空; ");
      if (this.getSpayeeacctno()!=null)
             if (this.getSpayeeacctno().getBytes().length > 42)
                sb.append("S_PAYEEACCTNO收款人账号宽度不能超过 "+42+"个字符; ");
    
    //check field S_PAYEEACCTNAME
      if (this.getSpayeeacctname()==null)
             sb.append("S_PAYEEACCTNAME收款人名称不能为空; ");
      if (this.getSpayeeacctname()!=null)
             if (this.getSpayeeacctname().getBytes().length > 120)
                sb.append("S_PAYEEACCTNAME收款人名称宽度不能超过 "+120+"个字符; ");
    
    //check field S_PAYEEACCTBANKNAME
      if (this.getSpayeeacctbankname()==null)
             sb.append("S_PAYEEACCTBANKNAME收款人银行不能为空; ");
      if (this.getSpayeeacctbankname()!=null)
             if (this.getSpayeeacctbankname().getBytes().length > 60)
                sb.append("S_PAYEEACCTBANKNAME收款人银行宽度不能超过 "+60+"个字符; ");
    
    //check field S_PAYEEACCTBANKNO
      if (this.getSpayeeacctbankno()!=null)
             if (this.getSpayeeacctbankno().getBytes().length > 42)
                sb.append("S_PAYEEACCTBANKNO收款人银行行号宽度不能超过 "+42+"个字符; ");
    
    //check field N_PAYAMT
      if (this.getNpayamt()==null)
             sb.append("N_PAYAMT支付金额不能为空; ");
      
    //check field S_XPAYDATE
      if (this.getSxpaydate()!=null)
             if (this.getSxpaydate().getBytes().length > 20)
                sb.append("S_XPAYDATE实际支付日期宽度不能超过 "+20+"个字符; ");
    
    //check field S_XAGENTBUSINESSNO
      if (this.getSxagentbusinessno()!=null)
             if (this.getSxagentbusinessno().getBytes().length > 42)
                sb.append("S_XAGENTBUSINESSNO银行交易流水号宽度不能超过 "+42+"个字符; ");
    
    //check field S_XCHECKNO
      if (this.getSxcheckno()!=null)
             if (this.getSxcheckno().getBytes().length > 42)
                sb.append("S_XCHECKNO支票号(结算号)宽度不能超过 "+42+"个字符; ");
    
    //check field N_XPAYAMT
      
    //check field S_XPAYEEACCTBANKNAME
      if (this.getSxpayeeacctbankname()!=null)
             if (this.getSxpayeeacctbankname().getBytes().length > 60)
                sb.append("S_XPAYEEACCTBANKNAME收款人银行宽度不能超过 "+60+"个字符; ");
    
    //check field S_XPAYEEACCTNO
      if (this.getSxpayeeacctno()!=null)
             if (this.getSxpayeeacctno().getBytes().length > 60)
                sb.append("S_XPAYEEACCTNO收款人账号宽度不能超过 "+60+"个字符; ");
    
    //check field S_XPAYEEACCTNAME
      if (this.getSxpayeeacctname()!=null)
             if (this.getSxpayeeacctname().getBytes().length > 120)
                sb.append("S_XPAYEEACCTNAME收款人全称宽度不能超过 "+120+"个字符; ");
    
    //check field S_REMARK
      if (this.getSremark()!=null)
             if (this.getSremark().getBytes().length > 255)
                sb.append("S_REMARK备注宽度不能超过 "+255+"个字符; ");
    
    //check field S_HOLD1
      if (this.getShold1()!=null)
             if (this.getShold1().getBytes().length > 42)
                sb.append("S_HOLD1预留字段1宽度不能超过 "+42+"个字符; ");
    
    //check field S_HOLD2
      if (this.getShold2()!=null)
             if (this.getShold2().getBytes().length > 42)
                sb.append("S_HOLD2预留字段2宽度不能超过 "+42+"个字符; ");
    
    //check field S_HOLD3
      if (this.getShold3()!=null)
             if (this.getShold3().getBytes().length > 42)
                sb.append("S_HOLD3预留字段3宽度不能超过 "+42+"个字符; ");
    
    //check field S_HOLD4
      if (this.getShold4()!=null)
             if (this.getShold4().getBytes().length > 42)
                sb.append("S_HOLD4预留字段4宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXT1
      if (this.getSext1()!=null)
             if (this.getSext1().getBytes().length > 50)
                sb.append("S_EXT1扩展1宽度不能超过 "+50+"个字符; ");
    
    //check field S_EXT2
      if (this.getSext2()!=null)
             if (this.getSext2().getBytes().length > 50)
                sb.append("S_EXT2扩展2宽度不能超过 "+50+"个字符; ");
    
    //check field S_EXT3
      if (this.getSext3()!=null)
             if (this.getSext3().getBytes().length > 50)
                sb.append("S_EXT3扩展3宽度不能超过 "+50+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field I_VOUSRLNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("I_VOUSRLNO")) {
               if (this.getIvousrlno()==null)
                    sb.append("I_VOUSRLNO 主键流水号不能为空; ");
               break;
         }
  }
    
    //check field I_SEQNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("I_SEQNO")) {
               if (this.getIseqno()==null)
                    sb.append("I_SEQNO 主键流水号不能为空; ");
               break;
         }
  }
    
    //check field S_ID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ID")) {
               if (this.getSid()==null)
                    sb.append("S_ID 支付明细Id不能为空; ");
               if (this.getSid()!=null)
                    if (this.getSid().getBytes().length > 38)
                        sb.append("S_ID 支付明细Id宽度不能超过 "+38+"个字符");
             break;
         }
  }
    
    //check field S_VOUCHERBILLID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VOUCHERBILLID")) {
               if (this.getSvoucherbillid()==null)
                    sb.append("S_VOUCHERBILLID 财政授权支付凭证Id不能为空; ");
               if (this.getSvoucherbillid()!=null)
                    if (this.getSvoucherbillid().getBytes().length > 38)
                        sb.append("S_VOUCHERBILLID 财政授权支付凭证Id宽度不能超过 "+38+"个字符");
             break;
         }
  }
    
    //check field S_VOUCHERBILLNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VOUCHERBILLNO")) {
               if (this.getSvoucherbillno()==null)
                    sb.append("S_VOUCHERBILLNO 财政授权支付凭证单号不能为空; ");
               if (this.getSvoucherbillno()!=null)
                    if (this.getSvoucherbillno().getBytes().length > 42)
                        sb.append("S_VOUCHERBILLNO 财政授权支付凭证单号宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_VOUCHERNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VOUCHERNO")) {
               if (this.getSvoucherno()==null)
                    sb.append("S_VOUCHERNO 支付申请序号不能为空; ");
               if (this.getSvoucherno()!=null)
                    if (this.getSvoucherno().getBytes().length > 42)
                        sb.append("S_VOUCHERNO 支付申请序号宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_FUNDTYPECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FUNDTYPECODE")) {
               if (this.getSfundtypecode()==null)
                    sb.append("S_FUNDTYPECODE 资金性质编码不能为空; ");
               if (this.getSfundtypecode()!=null)
                    if (this.getSfundtypecode().getBytes().length > 42)
                        sb.append("S_FUNDTYPECODE 资金性质编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_FUNDTYPENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FUNDTYPENAME")) {
               if (this.getSfundtypename()==null)
                    sb.append("S_FUNDTYPENAME 资金性质名称不能为空; ");
               if (this.getSfundtypename()!=null)
                    if (this.getSfundtypename().getBytes().length > 60)
                        sb.append("S_FUNDTYPENAME 资金性质名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_BGTTYPECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BGTTYPECODE")) {
                 if (this.getSbgttypecode()!=null)
                    if (this.getSbgttypecode().getBytes().length > 60)
                        sb.append("S_BGTTYPECODE 预算类型编码宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_BGTTYPENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BGTTYPENAME")) {
                 if (this.getSbgttypename()!=null)
                    if (this.getSbgttypename().getBytes().length > 60)
                        sb.append("S_BGTTYPENAME 预算类型名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PROCATCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PROCATCODE")) {
                 if (this.getSprocatcode()!=null)
                    if (this.getSprocatcode().getBytes().length > 42)
                        sb.append("S_PROCATCODE 收支管理编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_PROCATNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PROCATNAME")) {
                 if (this.getSprocatname()!=null)
                    if (this.getSprocatname().getBytes().length > 60)
                        sb.append("S_PROCATNAME 收支管理名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PAYKINDCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYKINDCODE")) {
                 if (this.getSpaykindcode()!=null)
                    if (this.getSpaykindcode().getBytes().length > 42)
                        sb.append("S_PAYKINDCODE 支出类型编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_PAYKINDNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYKINDNAME")) {
                 if (this.getSpaykindname()!=null)
                    if (this.getSpaykindname().getBytes().length > 60)
                        sb.append("S_PAYKINDNAME 支出类型名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_FILENOCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENOCODE")) {
                 if (this.getSfilenocode()!=null)
                    if (this.getSfilenocode().getBytes().length > 42)
                        sb.append("S_FILENOCODE 指标文号编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_FILENONAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENONAME")) {
                 if (this.getSfilenoname()!=null)
                    if (this.getSfilenoname().getBytes().length > 100)
                        sb.append("S_FILENONAME 指标文号名称宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_SUPDEPCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SUPDEPCODE")) {
                 if (this.getSsupdepcode()!=null)
                    if (this.getSsupdepcode().getBytes().length > 42)
                        sb.append("S_SUPDEPCODE 一级预算单位编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_SUPDEPNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SUPDEPNAME")) {
                 if (this.getSsupdepname()!=null)
                    if (this.getSsupdepname().getBytes().length > 60)
                        sb.append("S_SUPDEPNAME 一级预算单位名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_AGENCYCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_AGENCYCODE")) {
               if (this.getSagencycode()==null)
                    sb.append("S_AGENCYCODE 基层预算单位编码不能为空; ");
               if (this.getSagencycode()!=null)
                    if (this.getSagencycode().getBytes().length > 42)
                        sb.append("S_AGENCYCODE 基层预算单位编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_AGENCYNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_AGENCYNAME")) {
               if (this.getSagencyname()==null)
                    sb.append("S_AGENCYNAME 基层预算单位名称不能为空; ");
               if (this.getSagencyname()!=null)
                    if (this.getSagencyname().getBytes().length > 60)
                        sb.append("S_AGENCYNAME 基层预算单位名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCCODE")) {
               if (this.getSexpfunccode()==null)
                    sb.append("S_EXPFUNCCODE 功能分类科目编码不能为空; ");
               if (this.getSexpfunccode()!=null)
                    if (this.getSexpfunccode().getBytes().length > 42)
                        sb.append("S_EXPFUNCCODE 功能分类科目编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCNAME")) {
               if (this.getSexpfuncname()==null)
                    sb.append("S_EXPFUNCNAME 功能分类科目名称不能为空; ");
               if (this.getSexpfuncname()!=null)
                    if (this.getSexpfuncname().getBytes().length > 60)
                        sb.append("S_EXPFUNCNAME 功能分类科目名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPECOCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECOCODE")) {
                 if (this.getSexpecocode()!=null)
                    if (this.getSexpecocode().getBytes().length > 42)
                        sb.append("S_EXPECOCODE 经济分类科目编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPECONAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECONAME")) {
                 if (this.getSexpeconame()!=null)
                    if (this.getSexpeconame().getBytes().length > 60)
                        sb.append("S_EXPECONAME 经济分类科目名称宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_DEPPROCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEPPROCODE")) {
                 if (this.getSdepprocode()!=null)
                    if (this.getSdepprocode().getBytes().length > 42)
                        sb.append("S_DEPPROCODE 预算项目编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_DEPPRONAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEPPRONAME")) {
                 if (this.getSdepproname()!=null)
                    if (this.getSdepproname().getBytes().length > 200)
                        sb.append("S_DEPPRONAME 预算项目名称宽度不能超过 "+200+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCTNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCTNO")) {
               if (this.getSpayeeacctno()==null)
                    sb.append("S_PAYEEACCTNO 收款人账号不能为空; ");
               if (this.getSpayeeacctno()!=null)
                    if (this.getSpayeeacctno().getBytes().length > 42)
                        sb.append("S_PAYEEACCTNO 收款人账号宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCTNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCTNAME")) {
               if (this.getSpayeeacctname()==null)
                    sb.append("S_PAYEEACCTNAME 收款人名称不能为空; ");
               if (this.getSpayeeacctname()!=null)
                    if (this.getSpayeeacctname().getBytes().length > 120)
                        sb.append("S_PAYEEACCTNAME 收款人名称宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCTBANKNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCTBANKNAME")) {
               if (this.getSpayeeacctbankname()==null)
                    sb.append("S_PAYEEACCTBANKNAME 收款人银行不能为空; ");
               if (this.getSpayeeacctbankname()!=null)
                    if (this.getSpayeeacctbankname().getBytes().length > 60)
                        sb.append("S_PAYEEACCTBANKNAME 收款人银行宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCTBANKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCTBANKNO")) {
                 if (this.getSpayeeacctbankno()!=null)
                    if (this.getSpayeeacctbankno().getBytes().length > 42)
                        sb.append("S_PAYEEACCTBANKNO 收款人银行行号宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field N_PAYAMT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_PAYAMT")) {
               if (this.getNpayamt()==null)
                    sb.append("N_PAYAMT 支付金额不能为空; ");
               break;
         }
  }
    
    //check field S_XPAYDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XPAYDATE")) {
                 if (this.getSxpaydate()!=null)
                    if (this.getSxpaydate().getBytes().length > 20)
                        sb.append("S_XPAYDATE 实际支付日期宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_XAGENTBUSINESSNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XAGENTBUSINESSNO")) {
                 if (this.getSxagentbusinessno()!=null)
                    if (this.getSxagentbusinessno().getBytes().length > 42)
                        sb.append("S_XAGENTBUSINESSNO 银行交易流水号宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_XCHECKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XCHECKNO")) {
                 if (this.getSxcheckno()!=null)
                    if (this.getSxcheckno().getBytes().length > 42)
                        sb.append("S_XCHECKNO 支票号(结算号)宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field N_XPAYAMT
          
    //check field S_XPAYEEACCTBANKNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XPAYEEACCTBANKNAME")) {
                 if (this.getSxpayeeacctbankname()!=null)
                    if (this.getSxpayeeacctbankname().getBytes().length > 60)
                        sb.append("S_XPAYEEACCTBANKNAME 收款人银行宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_XPAYEEACCTNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XPAYEEACCTNO")) {
                 if (this.getSxpayeeacctno()!=null)
                    if (this.getSxpayeeacctno().getBytes().length > 60)
                        sb.append("S_XPAYEEACCTNO 收款人账号宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_XPAYEEACCTNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XPAYEEACCTNAME")) {
                 if (this.getSxpayeeacctname()!=null)
                    if (this.getSxpayeeacctname().getBytes().length > 120)
                        sb.append("S_XPAYEEACCTNAME 收款人全称宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_REMARK
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_REMARK")) {
                 if (this.getSremark()!=null)
                    if (this.getSremark().getBytes().length > 255)
                        sb.append("S_REMARK 备注宽度不能超过 "+255+"个字符");
             break;
         }
  }
    
    //check field S_HOLD1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD1")) {
                 if (this.getShold1()!=null)
                    if (this.getShold1().getBytes().length > 42)
                        sb.append("S_HOLD1 预留字段1宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_HOLD2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD2")) {
                 if (this.getShold2()!=null)
                    if (this.getShold2().getBytes().length > 42)
                        sb.append("S_HOLD2 预留字段2宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_HOLD3
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD3")) {
                 if (this.getShold3()!=null)
                    if (this.getShold3().getBytes().length > 42)
                        sb.append("S_HOLD3 预留字段3宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_HOLD4
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD4")) {
                 if (this.getShold4()!=null)
                    if (this.getShold4().getBytes().length > 42)
                        sb.append("S_HOLD4 预留字段4宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXT1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXT1")) {
                 if (this.getSext1()!=null)
                    if (this.getSext1().getBytes().length > 50)
                        sb.append("S_EXT1 扩展1宽度不能超过 "+50+"个字符");
             break;
         }
  }
    
    //check field S_EXT2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXT2")) {
                 if (this.getSext2()!=null)
                    if (this.getSext2().getBytes().length > 50)
                        sb.append("S_EXT2 扩展2宽度不能超过 "+50+"个字符");
             break;
         }
  }
    
    //check field S_EXT3
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXT3")) {
                 if (this.getSext3()!=null)
                    if (this.getSext3().getBytes().length > 50)
                        sb.append("S_EXT3 扩展3宽度不能超过 "+50+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TfGrantpaymsgsubPK pk = new TfGrantpaymsgsubPK();
      pk.setIvousrlno(getIvousrlno());
      pk.setIseqno(getIseqno());
      return pk;
    };
}
