    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TsCheckdeloptlogPK;
/**
 * <p>Title: DTO of table: TS_CHECKDELOPTLOG</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:59 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TsCheckdeloptlogDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_ORGCODE CHARACTER   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_BIZTYPE CHARACTER   , NOT NULL       */
    protected String sbiztype;
    /**
    *  S_USERCODE CHARACTER   , NOT NULL       */
    protected String susercode;
    /**
    *  S_USERNAME CHARACTER   , NOT NULL       */
    protected String susername;
    /**
    *  S_FILENAME CHARACTER   , NOT NULL       */
    protected String sfilename;
    /**
    *  S_VOUNO CHARACTER         */
    protected String svouno;
    /**
    *  T_OPETIME TIMESTAMP         */
    protected Timestamp topetime;
    /**
    *  S_REMAEK1 CHARACTER         */
    protected String sremaek1;
    /**
    *  S_REMAEK2 CHARACTER         */
    protected String sremaek2;
    /**
    *  S_REMAEK3 CHARACTER         */
    protected String sremaek3;
    /**
    *  F_AMT DECIMAL         */
    protected BigDecimal famt;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getSbiztype()
    {
        return sbiztype;
    }
     /**
     *   Setter S_BIZTYPE , NOT NULL        * */
    public void setSbiztype(String _sbiztype) {
        this.sbiztype = _sbiztype;
    }


    public String getSusercode()
    {
        return susercode;
    }
     /**
     *   Setter S_USERCODE , NOT NULL        * */
    public void setSusercode(String _susercode) {
        this.susercode = _susercode;
    }


    public String getSusername()
    {
        return susername;
    }
     /**
     *   Setter S_USERNAME , NOT NULL        * */
    public void setSusername(String _susername) {
        this.susername = _susername;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME , NOT NULL        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getSvouno()
    {
        return svouno;
    }
     /**
     *   Setter S_VOUNO        * */
    public void setSvouno(String _svouno) {
        this.svouno = _svouno;
    }


    public Timestamp getTopetime()
    {
        return topetime;
    }
     /**
     *   Setter T_OPETIME        * */
    public void setTopetime(Timestamp _topetime) {
        this.topetime = _topetime;
    }


    public String getSremaek1()
    {
        return sremaek1;
    }
     /**
     *   Setter S_REMAEK1        * */
    public void setSremaek1(String _sremaek1) {
        this.sremaek1 = _sremaek1;
    }


    public String getSremaek2()
    {
        return sremaek2;
    }
     /**
     *   Setter S_REMAEK2        * */
    public void setSremaek2(String _sremaek2) {
        this.sremaek2 = _sremaek2;
    }


    public String getSremaek3()
    {
        return sremaek3;
    }
     /**
     *   Setter S_REMAEK3        * */
    public void setSremaek3(String _sremaek3) {
        this.sremaek3 = _sremaek3;
    }


    public BigDecimal getFamt()
    {
        return famt;
    }
     /**
     *   Setter F_AMT        * */
    public void setFamt(BigDecimal _famt) {
        this.famt = _famt;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_ORGCODE , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_BIZTYPE , NOT NULL       * */
    public static String  columnSbiztype()
    {
        return "S_BIZTYPE";
    }
   
    /**
    *   Getter S_USERCODE , NOT NULL       * */
    public static String  columnSusercode()
    {
        return "S_USERCODE";
    }
   
    /**
    *   Getter S_USERNAME , NOT NULL       * */
    public static String  columnSusername()
    {
        return "S_USERNAME";
    }
   
    /**
    *   Getter S_FILENAME , NOT NULL       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_VOUNO       * */
    public static String  columnSvouno()
    {
        return "S_VOUNO";
    }
   
    /**
    *   Getter T_OPETIME       * */
    public static String  columnTopetime()
    {
        return "T_OPETIME";
    }
   
    /**
    *   Getter S_REMAEK1       * */
    public static String  columnSremaek1()
    {
        return "S_REMAEK1";
    }
   
    /**
    *   Getter S_REMAEK2       * */
    public static String  columnSremaek2()
    {
        return "S_REMAEK2";
    }
   
    /**
    *   Getter S_REMAEK3       * */
    public static String  columnSremaek3()
    {
        return "S_REMAEK3";
    }
   
    /**
    *   Getter F_AMT       * */
    public static String  columnFamt()
    {
        return "F_AMT";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TS_CHECKDELOPTLOG";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[11];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_BIZTYPE";
        columnNames[2]="S_USERCODE";
        columnNames[3]="S_USERNAME";
        columnNames[4]="S_FILENAME";
        columnNames[5]="S_VOUNO";
        columnNames[6]="T_OPETIME";
        columnNames[7]="S_REMAEK1";
        columnNames[8]="S_REMAEK2";
        columnNames[9]="S_REMAEK3";
        columnNames[10]="F_AMT";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TsCheckdeloptlogDto))
            return false;

        TsCheckdeloptlogDto bean = (TsCheckdeloptlogDto) obj;


      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field sbiztype
      if((this.sbiztype==null && bean.sbiztype!=null) || (this.sbiztype!=null && bean.sbiztype==null))
          return false;
        else if(this.sbiztype==null && bean.sbiztype==null){
        }
        else{
          if(!bean.sbiztype.equals(this.sbiztype))
               return false;
     }
      //compare field susercode
      if((this.susercode==null && bean.susercode!=null) || (this.susercode!=null && bean.susercode==null))
          return false;
        else if(this.susercode==null && bean.susercode==null){
        }
        else{
          if(!bean.susercode.equals(this.susercode))
               return false;
     }
      //compare field susername
      if((this.susername==null && bean.susername!=null) || (this.susername!=null && bean.susername==null))
          return false;
        else if(this.susername==null && bean.susername==null){
        }
        else{
          if(!bean.susername.equals(this.susername))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field svouno
      if((this.svouno==null && bean.svouno!=null) || (this.svouno!=null && bean.svouno==null))
          return false;
        else if(this.svouno==null && bean.svouno==null){
        }
        else{
          if(!bean.svouno.equals(this.svouno))
               return false;
     }
      //compare field topetime
      if((this.topetime==null && bean.topetime!=null) || (this.topetime!=null && bean.topetime==null))
          return false;
        else if(this.topetime==null && bean.topetime==null){
        }
        else{
          if(!bean.topetime.equals(this.topetime))
               return false;
     }
      //compare field sremaek1
      if((this.sremaek1==null && bean.sremaek1!=null) || (this.sremaek1!=null && bean.sremaek1==null))
          return false;
        else if(this.sremaek1==null && bean.sremaek1==null){
        }
        else{
          if(!bean.sremaek1.equals(this.sremaek1))
               return false;
     }
      //compare field sremaek2
      if((this.sremaek2==null && bean.sremaek2!=null) || (this.sremaek2!=null && bean.sremaek2==null))
          return false;
        else if(this.sremaek2==null && bean.sremaek2==null){
        }
        else{
          if(!bean.sremaek2.equals(this.sremaek2))
               return false;
     }
      //compare field sremaek3
      if((this.sremaek3==null && bean.sremaek3!=null) || (this.sremaek3!=null && bean.sremaek3==null))
          return false;
        else if(this.sremaek3==null && bean.sremaek3==null){
        }
        else{
          if(!bean.sremaek3.equals(this.sremaek3))
               return false;
     }
      //compare field famt
      if((this.famt==null && bean.famt!=null) || (this.famt!=null && bean.famt==null))
          return false;
        else if(this.famt==null && bean.famt==null){
        }
        else{
          if(!bean.famt.equals(this.famt))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.sbiztype!=null)
          _hash_ = _hash_ * 31+ this.sbiztype.hashCode() ;
        if(this.susercode!=null)
          _hash_ = _hash_ * 31+ this.susercode.hashCode() ;
        if(this.susername!=null)
          _hash_ = _hash_ * 31+ this.susername.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.svouno!=null)
          _hash_ = _hash_ * 31+ this.svouno.hashCode() ;
        if(this.topetime!=null)
          _hash_ = _hash_ * 31+ this.topetime.hashCode() ;
        if(this.sremaek1!=null)
          _hash_ = _hash_ * 31+ this.sremaek1.hashCode() ;
        if(this.sremaek2!=null)
          _hash_ = _hash_ * 31+ this.sremaek2.hashCode() ;
        if(this.sremaek3!=null)
          _hash_ = _hash_ * 31+ this.sremaek3.hashCode() ;
        if(this.famt!=null)
          _hash_ = _hash_ * 31+ this.famt.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TsCheckdeloptlogDto bean = new TsCheckdeloptlogDto();

          if (this.sorgcode != null)
            bean.sorgcode = new String(this.sorgcode);
          if (this.sbiztype != null)
            bean.sbiztype = new String(this.sbiztype);
          if (this.susercode != null)
            bean.susercode = new String(this.susercode);
          if (this.susername != null)
            bean.susername = new String(this.susername);
          if (this.sfilename != null)
            bean.sfilename = new String(this.sfilename);
          if (this.svouno != null)
            bean.svouno = new String(this.svouno);
          if (this.topetime != null)
            bean.topetime = (Timestamp) this.topetime.clone();
          if (this.sremaek1 != null)
            bean.sremaek1 = new String(this.sremaek1);
          if (this.sremaek2 != null)
            bean.sremaek2 = new String(this.sremaek2);
          if (this.sremaek3 != null)
            bean.sremaek3 = new String(this.sremaek3);
          if (this.famt != null)
            bean.famt = new BigDecimal(this.famt.toString());
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TsCheckdeloptlogDto").append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[sbiztype]").append(" = ").append(sbiztype).append(sep);
        sb.append("[susercode]").append(" = ").append(susercode).append(sep);
        sb.append("[susername]").append(" = ").append(susername).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[svouno]").append(" = ").append(svouno).append(sep);
        sb.append("[topetime]").append(" = ").append(topetime).append(sep);
        sb.append("[sremaek1]").append(" = ").append(sremaek1).append(sep);
        sb.append("[sremaek2]").append(" = ").append(sremaek2).append(sep);
        sb.append("[sremaek3]").append(" = ").append(sremaek3).append(sep);
        sb.append("[famt]").append(" = ").append(famt).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_BIZTYPE
      if (this.getSbiztype()==null)
             sb.append("S_BIZTYPE不能为空; ");
      if (this.getSbiztype()!=null)
             if (this.getSbiztype().getBytes().length > 10)
                sb.append("S_BIZTYPE宽度不能超过 "+10+"个字符; ");
    
    //check field S_USERCODE
      if (this.getSusercode()==null)
             sb.append("S_USERCODE不能为空; ");
      if (this.getSusercode()!=null)
             if (this.getSusercode().getBytes().length > 30)
                sb.append("S_USERCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_USERNAME
      if (this.getSusername()==null)
             sb.append("S_USERNAME不能为空; ");
      if (this.getSusername()!=null)
             if (this.getSusername().getBytes().length > 100)
                sb.append("S_USERNAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()==null)
             sb.append("S_FILENAME不能为空; ");
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_VOUNO
      if (this.getSvouno()!=null)
             if (this.getSvouno().getBytes().length > 100)
                sb.append("S_VOUNO宽度不能超过 "+100+"个字符; ");
    
    //check field T_OPETIME
      
    //check field S_REMAEK1
      if (this.getSremaek1()!=null)
             if (this.getSremaek1().getBytes().length > 20)
                sb.append("S_REMAEK1宽度不能超过 "+20+"个字符; ");
    
    //check field S_REMAEK2
      if (this.getSremaek2()!=null)
             if (this.getSremaek2().getBytes().length > 50)
                sb.append("S_REMAEK2宽度不能超过 "+50+"个字符; ");
    
    //check field S_REMAEK3
      if (this.getSremaek3()!=null)
             if (this.getSremaek3().getBytes().length > 100)
                sb.append("S_REMAEK3宽度不能超过 "+100+"个字符; ");
    
    //check field F_AMT
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_BIZTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BIZTYPE")) {
               if (this.getSbiztype()==null)
                    sb.append("S_BIZTYPE 不能为空; ");
               if (this.getSbiztype()!=null)
                    if (this.getSbiztype().getBytes().length > 10)
                        sb.append("S_BIZTYPE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_USERCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_USERCODE")) {
               if (this.getSusercode()==null)
                    sb.append("S_USERCODE 不能为空; ");
               if (this.getSusercode()!=null)
                    if (this.getSusercode().getBytes().length > 30)
                        sb.append("S_USERCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_USERNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_USERNAME")) {
               if (this.getSusername()==null)
                    sb.append("S_USERNAME 不能为空; ");
               if (this.getSusername()!=null)
                    if (this.getSusername().getBytes().length > 100)
                        sb.append("S_USERNAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
               if (this.getSfilename()==null)
                    sb.append("S_FILENAME 不能为空; ");
               if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_VOUNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VOUNO")) {
                 if (this.getSvouno()!=null)
                    if (this.getSvouno().getBytes().length > 100)
                        sb.append("S_VOUNO 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field T_OPETIME
          
    //check field S_REMAEK1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_REMAEK1")) {
                 if (this.getSremaek1()!=null)
                    if (this.getSremaek1().getBytes().length > 20)
                        sb.append("S_REMAEK1 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_REMAEK2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_REMAEK2")) {
                 if (this.getSremaek2()!=null)
                    if (this.getSremaek2().getBytes().length > 50)
                        sb.append("S_REMAEK2 宽度不能超过 "+50+"个字符");
             break;
         }
  }
    
    //check field S_REMAEK3
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_REMAEK3")) {
                 if (this.getSremaek3()!=null)
                    if (this.getSremaek3().getBytes().length > 100)
                        sb.append("S_REMAEK3 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field F_AMT
          
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      throw new RuntimeException("此dto没有PK，不能进行此操作");
    };
}
