    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TsCoderegtypePK;
/**
 * <p>Title: DTO of table: TS_CODEREGTYPE</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:59 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TsCoderegtypeDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_ORGCODE VARCHAR , PK   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_REGCODE CHARACTER , PK   , NOT NULL       */
    protected String sregcode;
    /**
    *  S_REGNAME VARCHAR   , NOT NULL       */
    protected String sregname;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE, PK , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getSregcode()
    {
        return sregcode;
    }
     /**
     *   Setter S_REGCODE, PK , NOT NULL        * */
    public void setSregcode(String _sregcode) {
        this.sregcode = _sregcode;
    }


    public String getSregname()
    {
        return sregname;
    }
     /**
     *   Setter S_REGNAME , NOT NULL        * */
    public void setSregname(String _sregname) {
        this.sregname = _sregname;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_ORGCODE, PK , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_REGCODE, PK , NOT NULL       * */
    public static String  columnSregcode()
    {
        return "S_REGCODE";
    }
   
    /**
    *   Getter S_REGNAME , NOT NULL       * */
    public static String  columnSregname()
    {
        return "S_REGNAME";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TS_CODEREGTYPE";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[3];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_REGCODE";
        columnNames[2]="S_REGNAME";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TsCoderegtypeDto))
            return false;

        TsCoderegtypeDto bean = (TsCoderegtypeDto) obj;


      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field sregcode
      if((this.sregcode==null && bean.sregcode!=null) || (this.sregcode!=null && bean.sregcode==null))
          return false;
        else if(this.sregcode==null && bean.sregcode==null){
        }
        else{
          if(!bean.sregcode.equals(this.sregcode))
               return false;
     }
      //compare field sregname
      if((this.sregname==null && bean.sregname!=null) || (this.sregname!=null && bean.sregname==null))
          return false;
        else if(this.sregname==null && bean.sregname==null){
        }
        else{
          if(!bean.sregname.equals(this.sregname))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.sregcode!=null)
          _hash_ = _hash_ * 31+ this.sregcode.hashCode() ;
        if(this.sregname!=null)
          _hash_ = _hash_ * 31+ this.sregname.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TsCoderegtypeDto bean = new TsCoderegtypeDto();

          bean.sorgcode = this.sorgcode;

          bean.sregcode = this.sregcode;

          if (this.sregname != null)
            bean.sregname = new String(this.sregname);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TsCoderegtypeDto").append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[sregcode]").append(" = ").append(sregcode).append(sep);
        sb.append("[sregname]").append(" = ").append(sregname).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_REGCODE
      if (this.getSregcode()==null)
             sb.append("S_REGCODE不能为空; ");
      if (this.getSregcode()!=null)
             if (this.getSregcode().getBytes().length > 3)
                sb.append("S_REGCODE宽度不能超过 "+3+"个字符; ");
    
    //check field S_REGNAME
      if (this.getSregname()==null)
             sb.append("S_REGNAME不能为空; ");
      if (this.getSregname()!=null)
             if (this.getSregname().getBytes().length > 60)
                sb.append("S_REGNAME宽度不能超过 "+60+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_REGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_REGCODE")) {
               if (this.getSregcode()==null)
                    sb.append("S_REGCODE 不能为空; ");
               if (this.getSregcode()!=null)
                    if (this.getSregcode().getBytes().length > 3)
                        sb.append("S_REGCODE 宽度不能超过 "+3+"个字符");
             break;
         }
  }
    
    //check field S_REGNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_REGNAME")) {
               if (this.getSregname()==null)
                    sb.append("S_REGNAME 不能为空; ");
               if (this.getSregname()!=null)
                    if (this.getSregname().getBytes().length > 60)
                        sb.append("S_REGNAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TsCoderegtypePK pk = new TsCoderegtypePK();
      pk.setSorgcode(getSorgcode());
      pk.setSregcode(getSregcode());
      return pk;
    };
}
