    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TsConvertaxPK;
/**
 * <p>Title: DTO of table: TS_CONVERTAX</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:00 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TsConvertaxDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_ORGCODE VARCHAR , PK   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_TAXCODE VARCHAR , PK   , NOT NULL       */
    protected String staxcode;
    /**
    *  S_TCBSTAX VARCHAR   , NOT NULL       */
    protected String stcbstax;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE, PK , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getStaxcode()
    {
        return staxcode;
    }
     /**
     *   Setter S_TAXCODE, PK , NOT NULL        * */
    public void setStaxcode(String _staxcode) {
        this.staxcode = _staxcode;
    }


    public String getStcbstax()
    {
        return stcbstax;
    }
     /**
     *   Setter S_TCBSTAX , NOT NULL        * */
    public void setStcbstax(String _stcbstax) {
        this.stcbstax = _stcbstax;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_ORGCODE, PK , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_TAXCODE, PK , NOT NULL       * */
    public static String  columnStaxcode()
    {
        return "S_TAXCODE";
    }
   
    /**
    *   Getter S_TCBSTAX , NOT NULL       * */
    public static String  columnStcbstax()
    {
        return "S_TCBSTAX";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TS_CONVERTAX";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[3];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_TAXCODE";
        columnNames[2]="S_TCBSTAX";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TsConvertaxDto))
            return false;

        TsConvertaxDto bean = (TsConvertaxDto) obj;


      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field staxcode
      if((this.staxcode==null && bean.staxcode!=null) || (this.staxcode!=null && bean.staxcode==null))
          return false;
        else if(this.staxcode==null && bean.staxcode==null){
        }
        else{
          if(!bean.staxcode.equals(this.staxcode))
               return false;
     }
      //compare field stcbstax
      if((this.stcbstax==null && bean.stcbstax!=null) || (this.stcbstax!=null && bean.stcbstax==null))
          return false;
        else if(this.stcbstax==null && bean.stcbstax==null){
        }
        else{
          if(!bean.stcbstax.equals(this.stcbstax))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.staxcode!=null)
          _hash_ = _hash_ * 31+ this.staxcode.hashCode() ;
        if(this.stcbstax!=null)
          _hash_ = _hash_ * 31+ this.stcbstax.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TsConvertaxDto bean = new TsConvertaxDto();

          bean.sorgcode = this.sorgcode;

          bean.staxcode = this.staxcode;

          if (this.stcbstax != null)
            bean.stcbstax = new String(this.stcbstax);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TsConvertaxDto").append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[staxcode]").append(" = ").append(staxcode).append(sep);
        sb.append("[stcbstax]").append(" = ").append(stcbstax).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_TAXCODE
      if (this.getStaxcode()==null)
             sb.append("S_TAXCODE不能为空; ");
      if (this.getStaxcode()!=null)
             if (this.getStaxcode().getBytes().length > 12)
                sb.append("S_TAXCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_TCBSTAX
      if (this.getStcbstax()==null)
             sb.append("S_TCBSTAX不能为空; ");
      if (this.getStcbstax()!=null)
             if (this.getStcbstax().getBytes().length > 12)
                sb.append("S_TCBSTAX宽度不能超过 "+12+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_TAXCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXCODE")) {
               if (this.getStaxcode()==null)
                    sb.append("S_TAXCODE 不能为空; ");
               if (this.getStaxcode()!=null)
                    if (this.getStaxcode().getBytes().length > 12)
                        sb.append("S_TAXCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_TCBSTAX
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TCBSTAX")) {
               if (this.getStcbstax()==null)
                    sb.append("S_TCBSTAX 不能为空; ");
               if (this.getStcbstax()!=null)
                    if (this.getStcbstax().getBytes().length > 12)
                        sb.append("S_TCBSTAX 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TsConvertaxPK pk = new TsConvertaxPK();
      pk.setSorgcode(getSorgcode());
      pk.setStaxcode(getStaxcode());
      return pk;
    };
}
