    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TsInfotaxorgPK;
/**
 * <p>Title: DTO of table: TS_INFOTAXORG</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:00 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TsInfotaxorgDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_ORGCODE VARCHAR , PK   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_TRECODE CHARACTER , PK   , NOT NULL       */
    protected String strecode;
    /**
    *  S_TAXORG VARCHAR , PK   , NOT NULL       */
    protected String staxorg;
    /**
    *  S_PAYERNAME VARCHAR         */
    protected String spayername;
    /**
    *  S_PAYERBANK VARCHAR         */
    protected String spayerbank;
    /**
    *  S_ACCOUNT VARCHAR         */
    protected String saccount;
    /**
    *  I_MODICOUNT INTEGER         */
    protected Integer imodicount;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE, PK , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getStrecode()
    {
        return strecode;
    }
     /**
     *   Setter S_TRECODE, PK , NOT NULL        * */
    public void setStrecode(String _strecode) {
        this.strecode = _strecode;
    }


    public String getStaxorg()
    {
        return staxorg;
    }
     /**
     *   Setter S_TAXORG, PK , NOT NULL        * */
    public void setStaxorg(String _staxorg) {
        this.staxorg = _staxorg;
    }


    public String getSpayername()
    {
        return spayername;
    }
     /**
     *   Setter S_PAYERNAME        * */
    public void setSpayername(String _spayername) {
        this.spayername = _spayername;
    }


    public String getSpayerbank()
    {
        return spayerbank;
    }
     /**
     *   Setter S_PAYERBANK        * */
    public void setSpayerbank(String _spayerbank) {
        this.spayerbank = _spayerbank;
    }


    public String getSaccount()
    {
        return saccount;
    }
     /**
     *   Setter S_ACCOUNT        * */
    public void setSaccount(String _saccount) {
        this.saccount = _saccount;
    }


    public Integer getImodicount()
    {
        return imodicount;
    }
     /**
     *   Setter I_MODICOUNT        * */
    public void setImodicount(Integer _imodicount) {
        this.imodicount = _imodicount;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_ORGCODE, PK , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_TRECODE, PK , NOT NULL       * */
    public static String  columnStrecode()
    {
        return "S_TRECODE";
    }
   
    /**
    *   Getter S_TAXORG, PK , NOT NULL       * */
    public static String  columnStaxorg()
    {
        return "S_TAXORG";
    }
   
    /**
    *   Getter S_PAYERNAME       * */
    public static String  columnSpayername()
    {
        return "S_PAYERNAME";
    }
   
    /**
    *   Getter S_PAYERBANK       * */
    public static String  columnSpayerbank()
    {
        return "S_PAYERBANK";
    }
   
    /**
    *   Getter S_ACCOUNT       * */
    public static String  columnSaccount()
    {
        return "S_ACCOUNT";
    }
   
    /**
    *   Getter I_MODICOUNT       * */
    public static String  columnImodicount()
    {
        return "I_MODICOUNT";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TS_INFOTAXORG";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[7];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_TRECODE";
        columnNames[2]="S_TAXORG";
        columnNames[3]="S_PAYERNAME";
        columnNames[4]="S_PAYERBANK";
        columnNames[5]="S_ACCOUNT";
        columnNames[6]="I_MODICOUNT";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TsInfotaxorgDto))
            return false;

        TsInfotaxorgDto bean = (TsInfotaxorgDto) obj;


      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field strecode
      if((this.strecode==null && bean.strecode!=null) || (this.strecode!=null && bean.strecode==null))
          return false;
        else if(this.strecode==null && bean.strecode==null){
        }
        else{
          if(!bean.strecode.equals(this.strecode))
               return false;
     }
      //compare field staxorg
      if((this.staxorg==null && bean.staxorg!=null) || (this.staxorg!=null && bean.staxorg==null))
          return false;
        else if(this.staxorg==null && bean.staxorg==null){
        }
        else{
          if(!bean.staxorg.equals(this.staxorg))
               return false;
     }
      //compare field spayername
      if((this.spayername==null && bean.spayername!=null) || (this.spayername!=null && bean.spayername==null))
          return false;
        else if(this.spayername==null && bean.spayername==null){
        }
        else{
          if(!bean.spayername.equals(this.spayername))
               return false;
     }
      //compare field spayerbank
      if((this.spayerbank==null && bean.spayerbank!=null) || (this.spayerbank!=null && bean.spayerbank==null))
          return false;
        else if(this.spayerbank==null && bean.spayerbank==null){
        }
        else{
          if(!bean.spayerbank.equals(this.spayerbank))
               return false;
     }
      //compare field saccount
      if((this.saccount==null && bean.saccount!=null) || (this.saccount!=null && bean.saccount==null))
          return false;
        else if(this.saccount==null && bean.saccount==null){
        }
        else{
          if(!bean.saccount.equals(this.saccount))
               return false;
     }
      //compare field imodicount
      if((this.imodicount==null && bean.imodicount!=null) || (this.imodicount!=null && bean.imodicount==null))
          return false;
        else if(this.imodicount==null && bean.imodicount==null){
        }
        else{
          if(!bean.imodicount.equals(this.imodicount))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.strecode!=null)
          _hash_ = _hash_ * 31+ this.strecode.hashCode() ;
        if(this.staxorg!=null)
          _hash_ = _hash_ * 31+ this.staxorg.hashCode() ;
        if(this.spayername!=null)
          _hash_ = _hash_ * 31+ this.spayername.hashCode() ;
        if(this.spayerbank!=null)
          _hash_ = _hash_ * 31+ this.spayerbank.hashCode() ;
        if(this.saccount!=null)
          _hash_ = _hash_ * 31+ this.saccount.hashCode() ;
        if(this.imodicount!=null)
          _hash_ = _hash_ * 31+ this.imodicount.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TsInfotaxorgDto bean = new TsInfotaxorgDto();

          bean.sorgcode = this.sorgcode;

          bean.strecode = this.strecode;

          bean.staxorg = this.staxorg;

          if (this.spayername != null)
            bean.spayername = new String(this.spayername);
          if (this.spayerbank != null)
            bean.spayerbank = new String(this.spayerbank);
          if (this.saccount != null)
            bean.saccount = new String(this.saccount);
          if (this.imodicount != null)
            bean.imodicount = new Integer(this.imodicount.toString());
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TsInfotaxorgDto").append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[strecode]").append(" = ").append(strecode).append(sep);
        sb.append("[staxorg]").append(" = ").append(staxorg).append(sep);
        sb.append("[spayername]").append(" = ").append(spayername).append(sep);
        sb.append("[spayerbank]").append(" = ").append(spayerbank).append(sep);
        sb.append("[saccount]").append(" = ").append(saccount).append(sep);
        sb.append("[imodicount]").append(" = ").append(imodicount).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_TRECODE
      if (this.getStrecode()==null)
             sb.append("S_TRECODE不能为空; ");
      if (this.getStrecode()!=null)
             if (this.getStrecode().getBytes().length > 10)
                sb.append("S_TRECODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_TAXORG
      if (this.getStaxorg()==null)
             sb.append("S_TAXORG不能为空; ");
      if (this.getStaxorg()!=null)
             if (this.getStaxorg().getBytes().length > 30)
                sb.append("S_TAXORG宽度不能超过 "+30+"个字符; ");
    
    //check field S_PAYERNAME
      if (this.getSpayername()!=null)
             if (this.getSpayername().getBytes().length > 60)
                sb.append("S_PAYERNAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_PAYERBANK
      if (this.getSpayerbank()!=null)
             if (this.getSpayerbank().getBytes().length > 60)
                sb.append("S_PAYERBANK宽度不能超过 "+60+"个字符; ");
    
    //check field S_ACCOUNT
      if (this.getSaccount()!=null)
             if (this.getSaccount().getBytes().length > 50)
                sb.append("S_ACCOUNT宽度不能超过 "+50+"个字符; ");
    
    //check field I_MODICOUNT
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_TRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRECODE")) {
               if (this.getStrecode()==null)
                    sb.append("S_TRECODE 不能为空; ");
               if (this.getStrecode()!=null)
                    if (this.getStrecode().getBytes().length > 10)
                        sb.append("S_TRECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_TAXORG
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXORG")) {
               if (this.getStaxorg()==null)
                    sb.append("S_TAXORG 不能为空; ");
               if (this.getStaxorg()!=null)
                    if (this.getStaxorg().getBytes().length > 30)
                        sb.append("S_TAXORG 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_PAYERNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYERNAME")) {
                 if (this.getSpayername()!=null)
                    if (this.getSpayername().getBytes().length > 60)
                        sb.append("S_PAYERNAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PAYERBANK
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYERBANK")) {
                 if (this.getSpayerbank()!=null)
                    if (this.getSpayerbank().getBytes().length > 60)
                        sb.append("S_PAYERBANK 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_ACCOUNT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ACCOUNT")) {
                 if (this.getSaccount()!=null)
                    if (this.getSaccount().getBytes().length > 50)
                        sb.append("S_ACCOUNT 宽度不能超过 "+50+"个字符");
             break;
         }
  }
    
    //check field I_MODICOUNT
          
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TsInfotaxorgPK pk = new TsInfotaxorgPK();
      pk.setSorgcode(getSorgcode());
      pk.setStrecode(getStrecode());
      pk.setStaxorg(getStaxorg());
      return pk;
    };
}
