    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TsOperationformPK;
/**
 * <p>Title: DTO of table: TS_OPERATIONFORM</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:00 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TsOperationformDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_MODELID VARCHAR , PK   , NOT NULL       */
    protected String smodelid;
    /**
    *  S_FORMID VARCHAR , PK   , NOT NULL       */
    protected String sformid;
    /**
    *  S_FORMTYPE CHARACTER         */
    protected String sformtype;
    /**
    *  I_MODICOUNT INTEGER         */
    protected Integer imodicount;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSmodelid()
    {
        return smodelid;
    }
     /**
     *   Setter S_MODELID, PK , NOT NULL        * */
    public void setSmodelid(String _smodelid) {
        this.smodelid = _smodelid;
    }


    public String getSformid()
    {
        return sformid;
    }
     /**
     *   Setter S_FORMID, PK , NOT NULL        * */
    public void setSformid(String _sformid) {
        this.sformid = _sformid;
    }


    public String getSformtype()
    {
        return sformtype;
    }
     /**
     *   Setter S_FORMTYPE        * */
    public void setSformtype(String _sformtype) {
        this.sformtype = _sformtype;
    }


    public Integer getImodicount()
    {
        return imodicount;
    }
     /**
     *   Setter I_MODICOUNT        * */
    public void setImodicount(Integer _imodicount) {
        this.imodicount = _imodicount;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_MODELID, PK , NOT NULL       * */
    public static String  columnSmodelid()
    {
        return "S_MODELID";
    }
   
    /**
    *   Getter S_FORMID, PK , NOT NULL       * */
    public static String  columnSformid()
    {
        return "S_FORMID";
    }
   
    /**
    *   Getter S_FORMTYPE       * */
    public static String  columnSformtype()
    {
        return "S_FORMTYPE";
    }
   
    /**
    *   Getter I_MODICOUNT       * */
    public static String  columnImodicount()
    {
        return "I_MODICOUNT";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TS_OPERATIONFORM";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[4];        
        columnNames[0]="S_MODELID";
        columnNames[1]="S_FORMID";
        columnNames[2]="S_FORMTYPE";
        columnNames[3]="I_MODICOUNT";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TsOperationformDto))
            return false;

        TsOperationformDto bean = (TsOperationformDto) obj;


      //compare field smodelid
      if((this.smodelid==null && bean.smodelid!=null) || (this.smodelid!=null && bean.smodelid==null))
          return false;
        else if(this.smodelid==null && bean.smodelid==null){
        }
        else{
          if(!bean.smodelid.equals(this.smodelid))
               return false;
     }
      //compare field sformid
      if((this.sformid==null && bean.sformid!=null) || (this.sformid!=null && bean.sformid==null))
          return false;
        else if(this.sformid==null && bean.sformid==null){
        }
        else{
          if(!bean.sformid.equals(this.sformid))
               return false;
     }
      //compare field sformtype
      if((this.sformtype==null && bean.sformtype!=null) || (this.sformtype!=null && bean.sformtype==null))
          return false;
        else if(this.sformtype==null && bean.sformtype==null){
        }
        else{
          if(!bean.sformtype.equals(this.sformtype))
               return false;
     }
      //compare field imodicount
      if((this.imodicount==null && bean.imodicount!=null) || (this.imodicount!=null && bean.imodicount==null))
          return false;
        else if(this.imodicount==null && bean.imodicount==null){
        }
        else{
          if(!bean.imodicount.equals(this.imodicount))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.smodelid!=null)
          _hash_ = _hash_ * 31+ this.smodelid.hashCode() ;
        if(this.sformid!=null)
          _hash_ = _hash_ * 31+ this.sformid.hashCode() ;
        if(this.sformtype!=null)
          _hash_ = _hash_ * 31+ this.sformtype.hashCode() ;
        if(this.imodicount!=null)
          _hash_ = _hash_ * 31+ this.imodicount.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TsOperationformDto bean = new TsOperationformDto();

          bean.smodelid = this.smodelid;

          bean.sformid = this.sformid;

          if (this.sformtype != null)
            bean.sformtype = new String(this.sformtype);
          if (this.imodicount != null)
            bean.imodicount = new Integer(this.imodicount.toString());
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TsOperationformDto").append(sep);
        sb.append("[smodelid]").append(" = ").append(smodelid).append(sep);
        sb.append("[sformid]").append(" = ").append(sformid).append(sep);
        sb.append("[sformtype]").append(" = ").append(sformtype).append(sep);
        sb.append("[imodicount]").append(" = ").append(imodicount).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_MODELID
      if (this.getSmodelid()==null)
             sb.append("S_MODELID不能为空; ");
      if (this.getSmodelid()!=null)
             if (this.getSmodelid().getBytes().length > 10)
                sb.append("S_MODELID宽度不能超过 "+10+"个字符; ");
    
    //check field S_FORMID
      if (this.getSformid()==null)
             sb.append("S_FORMID不能为空; ");
      if (this.getSformid()!=null)
             if (this.getSformid().getBytes().length > 30)
                sb.append("S_FORMID宽度不能超过 "+30+"个字符; ");
    
    //check field S_FORMTYPE
      if (this.getSformtype()!=null)
             if (this.getSformtype().getBytes().length > 1)
                sb.append("S_FORMTYPE宽度不能超过 "+1+"个字符; ");
    
    //check field I_MODICOUNT
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_MODELID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_MODELID")) {
               if (this.getSmodelid()==null)
                    sb.append("S_MODELID 不能为空; ");
               if (this.getSmodelid()!=null)
                    if (this.getSmodelid().getBytes().length > 10)
                        sb.append("S_MODELID 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_FORMID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FORMID")) {
               if (this.getSformid()==null)
                    sb.append("S_FORMID 不能为空; ");
               if (this.getSformid()!=null)
                    if (this.getSformid().getBytes().length > 30)
                        sb.append("S_FORMID 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_FORMTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FORMTYPE")) {
                 if (this.getSformtype()!=null)
                    if (this.getSformtype().getBytes().length > 1)
                        sb.append("S_FORMTYPE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field I_MODICOUNT
          
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TsOperationformPK pk = new TsOperationformPK();
      pk.setSmodelid(getSmodelid());
      pk.setSformid(getSformid());
      return pk;
    };
}
