    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TsOrganPK;
/**
 * <p>Title: DTO of table: TS_ORGAN</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:00 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TsOrganDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_ORGCODE VARCHAR , PK   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_ORGNAME VARCHAR   , NOT NULL       */
    protected String sorgname;
    /**
    *  S_ORGLEVEL CHARACTER         */
    protected String sorglevel;
    /**
    *  S_OFPROVORGCODE VARCHAR         */
    protected String sofprovorgcode;
    /**
    *  S_OFCITYORGCODE VARCHAR         */
    protected String sofcityorgcode;
    /**
    *  S_OFCOUNTRYORGCODE VARCHAR         */
    protected String sofcountryorgcode;
    /**
    *  S_GOVERNORGCODE VARCHAR         */
    protected String sgovernorgcode;
    /**
    *  S_PAYBANKNO VARCHAR         */
    protected String spaybankno;
    /**
    *  S_ORGSTATUS CHARACTER         */
    protected String sorgstatus;
    /**
    *  S_ISCOLLECT CHARACTER         */
    protected String siscollect;
    /**
    *  I_PARTNO INTEGER         */
    protected Integer ipartno;
    /**
    *  I_MODICOUNT INTEGER         */
    protected Integer imodicount;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE, PK , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getSorgname()
    {
        return sorgname;
    }
     /**
     *   Setter S_ORGNAME , NOT NULL        * */
    public void setSorgname(String _sorgname) {
        this.sorgname = _sorgname;
    }


    public String getSorglevel()
    {
        return sorglevel;
    }
     /**
     *   Setter S_ORGLEVEL        * */
    public void setSorglevel(String _sorglevel) {
        this.sorglevel = _sorglevel;
    }


    public String getSofprovorgcode()
    {
        return sofprovorgcode;
    }
     /**
     *   Setter S_OFPROVORGCODE        * */
    public void setSofprovorgcode(String _sofprovorgcode) {
        this.sofprovorgcode = _sofprovorgcode;
    }


    public String getSofcityorgcode()
    {
        return sofcityorgcode;
    }
     /**
     *   Setter S_OFCITYORGCODE        * */
    public void setSofcityorgcode(String _sofcityorgcode) {
        this.sofcityorgcode = _sofcityorgcode;
    }


    public String getSofcountryorgcode()
    {
        return sofcountryorgcode;
    }
     /**
     *   Setter S_OFCOUNTRYORGCODE        * */
    public void setSofcountryorgcode(String _sofcountryorgcode) {
        this.sofcountryorgcode = _sofcountryorgcode;
    }


    public String getSgovernorgcode()
    {
        return sgovernorgcode;
    }
     /**
     *   Setter S_GOVERNORGCODE        * */
    public void setSgovernorgcode(String _sgovernorgcode) {
        this.sgovernorgcode = _sgovernorgcode;
    }


    public String getSpaybankno()
    {
        return spaybankno;
    }
     /**
     *   Setter S_PAYBANKNO        * */
    public void setSpaybankno(String _spaybankno) {
        this.spaybankno = _spaybankno;
    }


    public String getSorgstatus()
    {
        return sorgstatus;
    }
     /**
     *   Setter S_ORGSTATUS        * */
    public void setSorgstatus(String _sorgstatus) {
        this.sorgstatus = _sorgstatus;
    }


    public String getSiscollect()
    {
        return siscollect;
    }
     /**
     *   Setter S_ISCOLLECT        * */
    public void setSiscollect(String _siscollect) {
        this.siscollect = _siscollect;
    }


    public Integer getIpartno()
    {
        return ipartno;
    }
     /**
     *   Setter I_PARTNO        * */
    public void setIpartno(Integer _ipartno) {
        this.ipartno = _ipartno;
    }


    public Integer getImodicount()
    {
        return imodicount;
    }
     /**
     *   Setter I_MODICOUNT        * */
    public void setImodicount(Integer _imodicount) {
        this.imodicount = _imodicount;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_ORGCODE, PK , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_ORGNAME , NOT NULL       * */
    public static String  columnSorgname()
    {
        return "S_ORGNAME";
    }
   
    /**
    *   Getter S_ORGLEVEL       * */
    public static String  columnSorglevel()
    {
        return "S_ORGLEVEL";
    }
   
    /**
    *   Getter S_OFPROVORGCODE       * */
    public static String  columnSofprovorgcode()
    {
        return "S_OFPROVORGCODE";
    }
   
    /**
    *   Getter S_OFCITYORGCODE       * */
    public static String  columnSofcityorgcode()
    {
        return "S_OFCITYORGCODE";
    }
   
    /**
    *   Getter S_OFCOUNTRYORGCODE       * */
    public static String  columnSofcountryorgcode()
    {
        return "S_OFCOUNTRYORGCODE";
    }
   
    /**
    *   Getter S_GOVERNORGCODE       * */
    public static String  columnSgovernorgcode()
    {
        return "S_GOVERNORGCODE";
    }
   
    /**
    *   Getter S_PAYBANKNO       * */
    public static String  columnSpaybankno()
    {
        return "S_PAYBANKNO";
    }
   
    /**
    *   Getter S_ORGSTATUS       * */
    public static String  columnSorgstatus()
    {
        return "S_ORGSTATUS";
    }
   
    /**
    *   Getter S_ISCOLLECT       * */
    public static String  columnSiscollect()
    {
        return "S_ISCOLLECT";
    }
   
    /**
    *   Getter I_PARTNO       * */
    public static String  columnIpartno()
    {
        return "I_PARTNO";
    }
   
    /**
    *   Getter I_MODICOUNT       * */
    public static String  columnImodicount()
    {
        return "I_MODICOUNT";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TS_ORGAN";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[12];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_ORGNAME";
        columnNames[2]="S_ORGLEVEL";
        columnNames[3]="S_OFPROVORGCODE";
        columnNames[4]="S_OFCITYORGCODE";
        columnNames[5]="S_OFCOUNTRYORGCODE";
        columnNames[6]="S_GOVERNORGCODE";
        columnNames[7]="S_PAYBANKNO";
        columnNames[8]="S_ORGSTATUS";
        columnNames[9]="S_ISCOLLECT";
        columnNames[10]="I_PARTNO";
        columnNames[11]="I_MODICOUNT";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TsOrganDto))
            return false;

        TsOrganDto bean = (TsOrganDto) obj;


      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field sorgname
      if((this.sorgname==null && bean.sorgname!=null) || (this.sorgname!=null && bean.sorgname==null))
          return false;
        else if(this.sorgname==null && bean.sorgname==null){
        }
        else{
          if(!bean.sorgname.equals(this.sorgname))
               return false;
     }
      //compare field sorglevel
      if((this.sorglevel==null && bean.sorglevel!=null) || (this.sorglevel!=null && bean.sorglevel==null))
          return false;
        else if(this.sorglevel==null && bean.sorglevel==null){
        }
        else{
          if(!bean.sorglevel.equals(this.sorglevel))
               return false;
     }
      //compare field sofprovorgcode
      if((this.sofprovorgcode==null && bean.sofprovorgcode!=null) || (this.sofprovorgcode!=null && bean.sofprovorgcode==null))
          return false;
        else if(this.sofprovorgcode==null && bean.sofprovorgcode==null){
        }
        else{
          if(!bean.sofprovorgcode.equals(this.sofprovorgcode))
               return false;
     }
      //compare field sofcityorgcode
      if((this.sofcityorgcode==null && bean.sofcityorgcode!=null) || (this.sofcityorgcode!=null && bean.sofcityorgcode==null))
          return false;
        else if(this.sofcityorgcode==null && bean.sofcityorgcode==null){
        }
        else{
          if(!bean.sofcityorgcode.equals(this.sofcityorgcode))
               return false;
     }
      //compare field sofcountryorgcode
      if((this.sofcountryorgcode==null && bean.sofcountryorgcode!=null) || (this.sofcountryorgcode!=null && bean.sofcountryorgcode==null))
          return false;
        else if(this.sofcountryorgcode==null && bean.sofcountryorgcode==null){
        }
        else{
          if(!bean.sofcountryorgcode.equals(this.sofcountryorgcode))
               return false;
     }
      //compare field sgovernorgcode
      if((this.sgovernorgcode==null && bean.sgovernorgcode!=null) || (this.sgovernorgcode!=null && bean.sgovernorgcode==null))
          return false;
        else if(this.sgovernorgcode==null && bean.sgovernorgcode==null){
        }
        else{
          if(!bean.sgovernorgcode.equals(this.sgovernorgcode))
               return false;
     }
      //compare field spaybankno
      if((this.spaybankno==null && bean.spaybankno!=null) || (this.spaybankno!=null && bean.spaybankno==null))
          return false;
        else if(this.spaybankno==null && bean.spaybankno==null){
        }
        else{
          if(!bean.spaybankno.equals(this.spaybankno))
               return false;
     }
      //compare field sorgstatus
      if((this.sorgstatus==null && bean.sorgstatus!=null) || (this.sorgstatus!=null && bean.sorgstatus==null))
          return false;
        else if(this.sorgstatus==null && bean.sorgstatus==null){
        }
        else{
          if(!bean.sorgstatus.equals(this.sorgstatus))
               return false;
     }
      //compare field siscollect
      if((this.siscollect==null && bean.siscollect!=null) || (this.siscollect!=null && bean.siscollect==null))
          return false;
        else if(this.siscollect==null && bean.siscollect==null){
        }
        else{
          if(!bean.siscollect.equals(this.siscollect))
               return false;
     }
      //compare field ipartno
      if((this.ipartno==null && bean.ipartno!=null) || (this.ipartno!=null && bean.ipartno==null))
          return false;
        else if(this.ipartno==null && bean.ipartno==null){
        }
        else{
          if(!bean.ipartno.equals(this.ipartno))
               return false;
     }
      //compare field imodicount
      if((this.imodicount==null && bean.imodicount!=null) || (this.imodicount!=null && bean.imodicount==null))
          return false;
        else if(this.imodicount==null && bean.imodicount==null){
        }
        else{
          if(!bean.imodicount.equals(this.imodicount))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.sorgname!=null)
          _hash_ = _hash_ * 31+ this.sorgname.hashCode() ;
        if(this.sorglevel!=null)
          _hash_ = _hash_ * 31+ this.sorglevel.hashCode() ;
        if(this.sofprovorgcode!=null)
          _hash_ = _hash_ * 31+ this.sofprovorgcode.hashCode() ;
        if(this.sofcityorgcode!=null)
          _hash_ = _hash_ * 31+ this.sofcityorgcode.hashCode() ;
        if(this.sofcountryorgcode!=null)
          _hash_ = _hash_ * 31+ this.sofcountryorgcode.hashCode() ;
        if(this.sgovernorgcode!=null)
          _hash_ = _hash_ * 31+ this.sgovernorgcode.hashCode() ;
        if(this.spaybankno!=null)
          _hash_ = _hash_ * 31+ this.spaybankno.hashCode() ;
        if(this.sorgstatus!=null)
          _hash_ = _hash_ * 31+ this.sorgstatus.hashCode() ;
        if(this.siscollect!=null)
          _hash_ = _hash_ * 31+ this.siscollect.hashCode() ;
        if(this.ipartno!=null)
          _hash_ = _hash_ * 31+ this.ipartno.hashCode() ;
        if(this.imodicount!=null)
          _hash_ = _hash_ * 31+ this.imodicount.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TsOrganDto bean = new TsOrganDto();

          bean.sorgcode = this.sorgcode;

          if (this.sorgname != null)
            bean.sorgname = new String(this.sorgname);
          if (this.sorglevel != null)
            bean.sorglevel = new String(this.sorglevel);
          if (this.sofprovorgcode != null)
            bean.sofprovorgcode = new String(this.sofprovorgcode);
          if (this.sofcityorgcode != null)
            bean.sofcityorgcode = new String(this.sofcityorgcode);
          if (this.sofcountryorgcode != null)
            bean.sofcountryorgcode = new String(this.sofcountryorgcode);
          if (this.sgovernorgcode != null)
            bean.sgovernorgcode = new String(this.sgovernorgcode);
          if (this.spaybankno != null)
            bean.spaybankno = new String(this.spaybankno);
          if (this.sorgstatus != null)
            bean.sorgstatus = new String(this.sorgstatus);
          if (this.siscollect != null)
            bean.siscollect = new String(this.siscollect);
          if (this.ipartno != null)
            bean.ipartno = new Integer(this.ipartno.toString());
          if (this.imodicount != null)
            bean.imodicount = new Integer(this.imodicount.toString());
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TsOrganDto").append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[sorgname]").append(" = ").append(sorgname).append(sep);
        sb.append("[sorglevel]").append(" = ").append(sorglevel).append(sep);
        sb.append("[sofprovorgcode]").append(" = ").append(sofprovorgcode).append(sep);
        sb.append("[sofcityorgcode]").append(" = ").append(sofcityorgcode).append(sep);
        sb.append("[sofcountryorgcode]").append(" = ").append(sofcountryorgcode).append(sep);
        sb.append("[sgovernorgcode]").append(" = ").append(sgovernorgcode).append(sep);
        sb.append("[spaybankno]").append(" = ").append(spaybankno).append(sep);
        sb.append("[sorgstatus]").append(" = ").append(sorgstatus).append(sep);
        sb.append("[siscollect]").append(" = ").append(siscollect).append(sep);
        sb.append("[ipartno]").append(" = ").append(ipartno).append(sep);
        sb.append("[imodicount]").append(" = ").append(imodicount).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_ORGNAME
      if (this.getSorgname()==null)
             sb.append("S_ORGNAME不能为空; ");
      if (this.getSorgname()!=null)
             if (this.getSorgname().getBytes().length > 100)
                sb.append("S_ORGNAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_ORGLEVEL
      if (this.getSorglevel()!=null)
             if (this.getSorglevel().getBytes().length > 1)
                sb.append("S_ORGLEVEL宽度不能超过 "+1+"个字符; ");
    
    //check field S_OFPROVORGCODE
      if (this.getSofprovorgcode()!=null)
             if (this.getSofprovorgcode().getBytes().length > 12)
                sb.append("S_OFPROVORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_OFCITYORGCODE
      if (this.getSofcityorgcode()!=null)
             if (this.getSofcityorgcode().getBytes().length > 12)
                sb.append("S_OFCITYORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_OFCOUNTRYORGCODE
      if (this.getSofcountryorgcode()!=null)
             if (this.getSofcountryorgcode().getBytes().length > 12)
                sb.append("S_OFCOUNTRYORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_GOVERNORGCODE
      if (this.getSgovernorgcode()!=null)
             if (this.getSgovernorgcode().getBytes().length > 12)
                sb.append("S_GOVERNORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_PAYBANKNO
      if (this.getSpaybankno()!=null)
             if (this.getSpaybankno().getBytes().length > 12)
                sb.append("S_PAYBANKNO宽度不能超过 "+12+"个字符; ");
    
    //check field S_ORGSTATUS
      if (this.getSorgstatus()!=null)
             if (this.getSorgstatus().getBytes().length > 1)
                sb.append("S_ORGSTATUS宽度不能超过 "+1+"个字符; ");
    
    //check field S_ISCOLLECT
      if (this.getSiscollect()!=null)
             if (this.getSiscollect().getBytes().length > 1)
                sb.append("S_ISCOLLECT宽度不能超过 "+1+"个字符; ");
    
    //check field I_PARTNO
      
    //check field I_MODICOUNT
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_ORGNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGNAME")) {
               if (this.getSorgname()==null)
                    sb.append("S_ORGNAME 不能为空; ");
               if (this.getSorgname()!=null)
                    if (this.getSorgname().getBytes().length > 100)
                        sb.append("S_ORGNAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_ORGLEVEL
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGLEVEL")) {
                 if (this.getSorglevel()!=null)
                    if (this.getSorglevel().getBytes().length > 1)
                        sb.append("S_ORGLEVEL 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_OFPROVORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OFPROVORGCODE")) {
                 if (this.getSofprovorgcode()!=null)
                    if (this.getSofprovorgcode().getBytes().length > 12)
                        sb.append("S_OFPROVORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_OFCITYORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OFCITYORGCODE")) {
                 if (this.getSofcityorgcode()!=null)
                    if (this.getSofcityorgcode().getBytes().length > 12)
                        sb.append("S_OFCITYORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_OFCOUNTRYORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OFCOUNTRYORGCODE")) {
                 if (this.getSofcountryorgcode()!=null)
                    if (this.getSofcountryorgcode().getBytes().length > 12)
                        sb.append("S_OFCOUNTRYORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_GOVERNORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_GOVERNORGCODE")) {
                 if (this.getSgovernorgcode()!=null)
                    if (this.getSgovernorgcode().getBytes().length > 12)
                        sb.append("S_GOVERNORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_PAYBANKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBANKNO")) {
                 if (this.getSpaybankno()!=null)
                    if (this.getSpaybankno().getBytes().length > 12)
                        sb.append("S_PAYBANKNO 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_ORGSTATUS
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGSTATUS")) {
                 if (this.getSorgstatus()!=null)
                    if (this.getSorgstatus().getBytes().length > 1)
                        sb.append("S_ORGSTATUS 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_ISCOLLECT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ISCOLLECT")) {
                 if (this.getSiscollect()!=null)
                    if (this.getSiscollect().getBytes().length > 1)
                        sb.append("S_ISCOLLECT 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field I_PARTNO
          
    //check field I_MODICOUNT
          
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TsOrganPK pk = new TsOrganPK();
      pk.setSorgcode(getSorgcode());
      return pk;
    };
}
