    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvAmtControlInfoPK;
/**
 * <p>Title: DTO of table: TV_AMT_CONTROL_INFO</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:01 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvAmtControlInfoDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_TRECODE VARCHAR , PK   , NOT NULL       */
    protected String strecode;
    /**
    *  S_BANKCODE VARCHAR , PK   , NOT NULL       */
    protected String sbankcode;
    /**
    *  S_BUDGETUNITCODE VARCHAR , PK   , NOT NULL       */
    protected String sbudgetunitcode;
    /**
    *  S_FUNCBDGSBTCODE VARCHAR , PK   , NOT NULL       */
    protected String sfuncbdgsbtcode;
    /**
    *  S_YEAR CHARACTER , PK   , NOT NULL       */
    protected String syear;
    /**
    *  N_AMT DECIMAL   , NOT NULL       */
    protected BigDecimal namt;
    /**
    *  S_PAYTYPECODE VARCHAR , PK   , NOT NULL       */
    protected String spaytypecode;
    /**
    *  S_BUDGETTYPE CHARACTER , PK   , NOT NULL       */
    protected String sbudgettype;
    /**
    *  S_REMARK VARCHAR         */
    protected String sremark;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getStrecode()
    {
        return strecode;
    }
     /**
     *   Setter S_TRECODE, PK , NOT NULL        * */
    public void setStrecode(String _strecode) {
        this.strecode = _strecode;
    }


    public String getSbankcode()
    {
        return sbankcode;
    }
     /**
     *   Setter S_BANKCODE, PK , NOT NULL        * */
    public void setSbankcode(String _sbankcode) {
        this.sbankcode = _sbankcode;
    }


    public String getSbudgetunitcode()
    {
        return sbudgetunitcode;
    }
     /**
     *   Setter S_BUDGETUNITCODE, PK , NOT NULL        * */
    public void setSbudgetunitcode(String _sbudgetunitcode) {
        this.sbudgetunitcode = _sbudgetunitcode;
    }


    public String getSfuncbdgsbtcode()
    {
        return sfuncbdgsbtcode;
    }
     /**
     *   Setter S_FUNCBDGSBTCODE, PK , NOT NULL        * */
    public void setSfuncbdgsbtcode(String _sfuncbdgsbtcode) {
        this.sfuncbdgsbtcode = _sfuncbdgsbtcode;
    }


    public String getSyear()
    {
        return syear;
    }
     /**
     *   Setter S_YEAR, PK , NOT NULL        * */
    public void setSyear(String _syear) {
        this.syear = _syear;
    }


    public BigDecimal getNamt()
    {
        return namt;
    }
     /**
     *   Setter N_AMT , NOT NULL        * */
    public void setNamt(BigDecimal _namt) {
        this.namt = _namt;
    }


    public String getSpaytypecode()
    {
        return spaytypecode;
    }
     /**
     *   Setter S_PAYTYPECODE, PK , NOT NULL        * */
    public void setSpaytypecode(String _spaytypecode) {
        this.spaytypecode = _spaytypecode;
    }


    public String getSbudgettype()
    {
        return sbudgettype;
    }
     /**
     *   Setter S_BUDGETTYPE, PK , NOT NULL        * */
    public void setSbudgettype(String _sbudgettype) {
        this.sbudgettype = _sbudgettype;
    }


    public String getSremark()
    {
        return sremark;
    }
     /**
     *   Setter S_REMARK        * */
    public void setSremark(String _sremark) {
        this.sremark = _sremark;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_TRECODE, PK , NOT NULL       * */
    public static String  columnStrecode()
    {
        return "S_TRECODE";
    }
   
    /**
    *   Getter S_BANKCODE, PK , NOT NULL       * */
    public static String  columnSbankcode()
    {
        return "S_BANKCODE";
    }
   
    /**
    *   Getter S_BUDGETUNITCODE, PK , NOT NULL       * */
    public static String  columnSbudgetunitcode()
    {
        return "S_BUDGETUNITCODE";
    }
   
    /**
    *   Getter S_FUNCBDGSBTCODE, PK , NOT NULL       * */
    public static String  columnSfuncbdgsbtcode()
    {
        return "S_FUNCBDGSBTCODE";
    }
   
    /**
    *   Getter S_YEAR, PK , NOT NULL       * */
    public static String  columnSyear()
    {
        return "S_YEAR";
    }
   
    /**
    *   Getter N_AMT , NOT NULL       * */
    public static String  columnNamt()
    {
        return "N_AMT";
    }
   
    /**
    *   Getter S_PAYTYPECODE, PK , NOT NULL       * */
    public static String  columnSpaytypecode()
    {
        return "S_PAYTYPECODE";
    }
   
    /**
    *   Getter S_BUDGETTYPE, PK , NOT NULL       * */
    public static String  columnSbudgettype()
    {
        return "S_BUDGETTYPE";
    }
   
    /**
    *   Getter S_REMARK       * */
    public static String  columnSremark()
    {
        return "S_REMARK";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_AMT_CONTROL_INFO";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[9];        
        columnNames[0]="S_TRECODE";
        columnNames[1]="S_BANKCODE";
        columnNames[2]="S_BUDGETUNITCODE";
        columnNames[3]="S_FUNCBDGSBTCODE";
        columnNames[4]="S_YEAR";
        columnNames[5]="N_AMT";
        columnNames[6]="S_PAYTYPECODE";
        columnNames[7]="S_BUDGETTYPE";
        columnNames[8]="S_REMARK";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvAmtControlInfoDto))
            return false;

        TvAmtControlInfoDto bean = (TvAmtControlInfoDto) obj;


      //compare field strecode
      if((this.strecode==null && bean.strecode!=null) || (this.strecode!=null && bean.strecode==null))
          return false;
        else if(this.strecode==null && bean.strecode==null){
        }
        else{
          if(!bean.strecode.equals(this.strecode))
               return false;
     }
      //compare field sbankcode
      if((this.sbankcode==null && bean.sbankcode!=null) || (this.sbankcode!=null && bean.sbankcode==null))
          return false;
        else if(this.sbankcode==null && bean.sbankcode==null){
        }
        else{
          if(!bean.sbankcode.equals(this.sbankcode))
               return false;
     }
      //compare field sbudgetunitcode
      if((this.sbudgetunitcode==null && bean.sbudgetunitcode!=null) || (this.sbudgetunitcode!=null && bean.sbudgetunitcode==null))
          return false;
        else if(this.sbudgetunitcode==null && bean.sbudgetunitcode==null){
        }
        else{
          if(!bean.sbudgetunitcode.equals(this.sbudgetunitcode))
               return false;
     }
      //compare field sfuncbdgsbtcode
      if((this.sfuncbdgsbtcode==null && bean.sfuncbdgsbtcode!=null) || (this.sfuncbdgsbtcode!=null && bean.sfuncbdgsbtcode==null))
          return false;
        else if(this.sfuncbdgsbtcode==null && bean.sfuncbdgsbtcode==null){
        }
        else{
          if(!bean.sfuncbdgsbtcode.equals(this.sfuncbdgsbtcode))
               return false;
     }
      //compare field syear
      if((this.syear==null && bean.syear!=null) || (this.syear!=null && bean.syear==null))
          return false;
        else if(this.syear==null && bean.syear==null){
        }
        else{
          if(!bean.syear.equals(this.syear))
               return false;
     }
      //compare field namt
      if((this.namt==null && bean.namt!=null) || (this.namt!=null && bean.namt==null))
          return false;
        else if(this.namt==null && bean.namt==null){
        }
        else{
          if(!bean.namt.equals(this.namt))
               return false;
     }
      //compare field spaytypecode
      if((this.spaytypecode==null && bean.spaytypecode!=null) || (this.spaytypecode!=null && bean.spaytypecode==null))
          return false;
        else if(this.spaytypecode==null && bean.spaytypecode==null){
        }
        else{
          if(!bean.spaytypecode.equals(this.spaytypecode))
               return false;
     }
      //compare field sbudgettype
      if((this.sbudgettype==null && bean.sbudgettype!=null) || (this.sbudgettype!=null && bean.sbudgettype==null))
          return false;
        else if(this.sbudgettype==null && bean.sbudgettype==null){
        }
        else{
          if(!bean.sbudgettype.equals(this.sbudgettype))
               return false;
     }
      //compare field sremark
      if((this.sremark==null && bean.sremark!=null) || (this.sremark!=null && bean.sremark==null))
          return false;
        else if(this.sremark==null && bean.sremark==null){
        }
        else{
          if(!bean.sremark.equals(this.sremark))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.strecode!=null)
          _hash_ = _hash_ * 31+ this.strecode.hashCode() ;
        if(this.sbankcode!=null)
          _hash_ = _hash_ * 31+ this.sbankcode.hashCode() ;
        if(this.sbudgetunitcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetunitcode.hashCode() ;
        if(this.sfuncbdgsbtcode!=null)
          _hash_ = _hash_ * 31+ this.sfuncbdgsbtcode.hashCode() ;
        if(this.syear!=null)
          _hash_ = _hash_ * 31+ this.syear.hashCode() ;
        if(this.namt!=null)
          _hash_ = _hash_ * 31+ this.namt.hashCode() ;
        if(this.spaytypecode!=null)
          _hash_ = _hash_ * 31+ this.spaytypecode.hashCode() ;
        if(this.sbudgettype!=null)
          _hash_ = _hash_ * 31+ this.sbudgettype.hashCode() ;
        if(this.sremark!=null)
          _hash_ = _hash_ * 31+ this.sremark.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvAmtControlInfoDto bean = new TvAmtControlInfoDto();

          bean.strecode = this.strecode;

          bean.sbankcode = this.sbankcode;

          bean.sbudgetunitcode = this.sbudgetunitcode;

          bean.sfuncbdgsbtcode = this.sfuncbdgsbtcode;

          bean.syear = this.syear;

          if (this.namt != null)
            bean.namt = new BigDecimal(this.namt.toString());
          bean.spaytypecode = this.spaytypecode;

          bean.sbudgettype = this.sbudgettype;

          if (this.sremark != null)
            bean.sremark = new String(this.sremark);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvAmtControlInfoDto").append(sep);
        sb.append("[strecode]").append(" = ").append(strecode).append(sep);
        sb.append("[sbankcode]").append(" = ").append(sbankcode).append(sep);
        sb.append("[sbudgetunitcode]").append(" = ").append(sbudgetunitcode).append(sep);
        sb.append("[sfuncbdgsbtcode]").append(" = ").append(sfuncbdgsbtcode).append(sep);
        sb.append("[syear]").append(" = ").append(syear).append(sep);
        sb.append("[namt]").append(" = ").append(namt).append(sep);
        sb.append("[spaytypecode]").append(" = ").append(spaytypecode).append(sep);
        sb.append("[sbudgettype]").append(" = ").append(sbudgettype).append(sep);
        sb.append("[sremark]").append(" = ").append(sremark).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_TRECODE
      if (this.getStrecode()==null)
             sb.append("S_TRECODE不能为空; ");
      if (this.getStrecode()!=null)
             if (this.getStrecode().getBytes().length > 10)
                sb.append("S_TRECODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_BANKCODE
      if (this.getSbankcode()==null)
             sb.append("S_BANKCODE不能为空; ");
      if (this.getSbankcode()!=null)
             if (this.getSbankcode().getBytes().length > 12)
                sb.append("S_BANKCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_BUDGETUNITCODE
      if (this.getSbudgetunitcode()==null)
             sb.append("S_BUDGETUNITCODE不能为空; ");
      if (this.getSbudgetunitcode()!=null)
             if (this.getSbudgetunitcode().getBytes().length > 15)
                sb.append("S_BUDGETUNITCODE宽度不能超过 "+15+"个字符; ");
    
    //check field S_FUNCBDGSBTCODE
      if (this.getSfuncbdgsbtcode()==null)
             sb.append("S_FUNCBDGSBTCODE不能为空; ");
      if (this.getSfuncbdgsbtcode()!=null)
             if (this.getSfuncbdgsbtcode().getBytes().length > 30)
                sb.append("S_FUNCBDGSBTCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_YEAR
      if (this.getSyear()==null)
             sb.append("S_YEAR不能为空; ");
      if (this.getSyear()!=null)
             if (this.getSyear().getBytes().length > 4)
                sb.append("S_YEAR宽度不能超过 "+4+"个字符; ");
    
    //check field N_AMT
      if (this.getNamt()==null)
             sb.append("N_AMT不能为空; ");
      
    //check field S_PAYTYPECODE
      if (this.getSpaytypecode()==null)
             sb.append("S_PAYTYPECODE不能为空; ");
      if (this.getSpaytypecode()!=null)
             if (this.getSpaytypecode().getBytes().length > 2)
                sb.append("S_PAYTYPECODE宽度不能超过 "+2+"个字符; ");
    
    //check field S_BUDGETTYPE
      if (this.getSbudgettype()==null)
             sb.append("S_BUDGETTYPE不能为空; ");
      if (this.getSbudgettype()!=null)
             if (this.getSbudgettype().getBytes().length > 1)
                sb.append("S_BUDGETTYPE宽度不能超过 "+1+"个字符; ");
    
    //check field S_REMARK
      if (this.getSremark()!=null)
             if (this.getSremark().getBytes().length > 200)
                sb.append("S_REMARK宽度不能超过 "+200+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_TRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRECODE")) {
               if (this.getStrecode()==null)
                    sb.append("S_TRECODE 不能为空; ");
               if (this.getStrecode()!=null)
                    if (this.getStrecode().getBytes().length > 10)
                        sb.append("S_TRECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_BANKCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BANKCODE")) {
               if (this.getSbankcode()==null)
                    sb.append("S_BANKCODE 不能为空; ");
               if (this.getSbankcode()!=null)
                    if (this.getSbankcode().getBytes().length > 12)
                        sb.append("S_BANKCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETUNITCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETUNITCODE")) {
               if (this.getSbudgetunitcode()==null)
                    sb.append("S_BUDGETUNITCODE 不能为空; ");
               if (this.getSbudgetunitcode()!=null)
                    if (this.getSbudgetunitcode().getBytes().length > 15)
                        sb.append("S_BUDGETUNITCODE 宽度不能超过 "+15+"个字符");
             break;
         }
  }
    
    //check field S_FUNCBDGSBTCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FUNCBDGSBTCODE")) {
               if (this.getSfuncbdgsbtcode()==null)
                    sb.append("S_FUNCBDGSBTCODE 不能为空; ");
               if (this.getSfuncbdgsbtcode()!=null)
                    if (this.getSfuncbdgsbtcode().getBytes().length > 30)
                        sb.append("S_FUNCBDGSBTCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_YEAR
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_YEAR")) {
               if (this.getSyear()==null)
                    sb.append("S_YEAR 不能为空; ");
               if (this.getSyear()!=null)
                    if (this.getSyear().getBytes().length > 4)
                        sb.append("S_YEAR 宽度不能超过 "+4+"个字符");
             break;
         }
  }
    
    //check field N_AMT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_AMT")) {
               if (this.getNamt()==null)
                    sb.append("N_AMT 不能为空; ");
               break;
         }
  }
    
    //check field S_PAYTYPECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYTYPECODE")) {
               if (this.getSpaytypecode()==null)
                    sb.append("S_PAYTYPECODE 不能为空; ");
               if (this.getSpaytypecode()!=null)
                    if (this.getSpaytypecode().getBytes().length > 2)
                        sb.append("S_PAYTYPECODE 宽度不能超过 "+2+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETTYPE")) {
               if (this.getSbudgettype()==null)
                    sb.append("S_BUDGETTYPE 不能为空; ");
               if (this.getSbudgettype()!=null)
                    if (this.getSbudgettype().getBytes().length > 1)
                        sb.append("S_BUDGETTYPE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_REMARK
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_REMARK")) {
                 if (this.getSremark()!=null)
                    if (this.getSremark().getBytes().length > 200)
                        sb.append("S_REMARK 宽度不能超过 "+200+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TvAmtControlInfoPK pk = new TvAmtControlInfoPK();
      pk.setStrecode(getStrecode());
      pk.setSbankcode(getSbankcode());
      pk.setSbudgetunitcode(getSbudgetunitcode());
      pk.setSfuncbdgsbtcode(getSfuncbdgsbtcode());
      pk.setSyear(getSyear());
      pk.setSpaytypecode(getSpaytypecode());
      pk.setSbudgettype(getSbudgettype());
      return pk;
    };
}
