    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvDirectpayfilemainTmpPK;
/**
 * <p>Title: DTO of table: TV_DIRECTPAYFILEMAIN_TMP</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:01 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvDirectpayfilemainTmpDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_OFYEAR CHARACTER   , NOT NULL       */
    protected String sofyear;
    /**
    *  S_TAXTICKETNO VARCHAR   , NOT NULL       */
    protected String staxticketno;
    /**
    *  S_GENTICKETDATE CHARACTER   , NOT NULL       */
    protected String sgenticketdate;
    /**
    *  S_BUDGETUNITCODE VARCHAR   , NOT NULL       */
    protected String sbudgetunitcode;
    /**
    *  S_UNITCODENAME VARCHAR         */
    protected String sunitcodename;
    /**
    *  S_SETTLETYPE CHARACTER         */
    protected String ssettletype;
    /**
    *  S_SETTLENO VARCHAR         */
    protected String ssettleno;
    /**
    *  N_MONEY DECIMAL   , NOT NULL       */
    protected BigDecimal nmoney;
    /**
    *  S_PURPOSE VARCHAR         */
    protected String spurpose;
    /**
    *  S_PAYBANKCODE VARCHAR         */
    protected String spaybankcode;
    /**
    *  S_PAYBANKNAME VARCHAR         */
    protected String spaybankname;
    /**
    *  S_PAYBANKNO VARCHAR         */
    protected String spaybankno;
    /**
    *  S_RECNAME VARCHAR         */
    protected String srecname;
    /**
    *  S_RECBANKNAME VARCHAR         */
    protected String srecbankname;
    /**
    *  S_RECBANKNO VARCHAR         */
    protected String srecbankno;
    /**
    *  S_OBILLNO VARCHAR         */
    protected String sobillno;
    /**
    *  S_FILENAME VARCHAR   , NOT NULL       */
    protected String sfilename;
    /**
    *  S_ORGCODE VARCHAR   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_DEALNO VARCHAR   , NOT NULL       */
    protected String sdealno;
    /**
    *  S_PACKAGENO VARCHAR   , NOT NULL       */
    protected String spackageno;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSofyear()
    {
        return sofyear;
    }
     /**
     *   Setter S_OFYEAR , NOT NULL        * */
    public void setSofyear(String _sofyear) {
        this.sofyear = _sofyear;
    }


    public String getStaxticketno()
    {
        return staxticketno;
    }
     /**
     *   Setter S_TAXTICKETNO , NOT NULL        * */
    public void setStaxticketno(String _staxticketno) {
        this.staxticketno = _staxticketno;
    }


    public String getSgenticketdate()
    {
        return sgenticketdate;
    }
     /**
     *   Setter S_GENTICKETDATE , NOT NULL        * */
    public void setSgenticketdate(String _sgenticketdate) {
        this.sgenticketdate = _sgenticketdate;
    }


    public String getSbudgetunitcode()
    {
        return sbudgetunitcode;
    }
     /**
     *   Setter S_BUDGETUNITCODE , NOT NULL        * */
    public void setSbudgetunitcode(String _sbudgetunitcode) {
        this.sbudgetunitcode = _sbudgetunitcode;
    }


    public String getSunitcodename()
    {
        return sunitcodename;
    }
     /**
     *   Setter S_UNITCODENAME        * */
    public void setSunitcodename(String _sunitcodename) {
        this.sunitcodename = _sunitcodename;
    }


    public String getSsettletype()
    {
        return ssettletype;
    }
     /**
     *   Setter S_SETTLETYPE        * */
    public void setSsettletype(String _ssettletype) {
        this.ssettletype = _ssettletype;
    }


    public String getSsettleno()
    {
        return ssettleno;
    }
     /**
     *   Setter S_SETTLENO        * */
    public void setSsettleno(String _ssettleno) {
        this.ssettleno = _ssettleno;
    }


    public BigDecimal getNmoney()
    {
        return nmoney;
    }
     /**
     *   Setter N_MONEY , NOT NULL        * */
    public void setNmoney(BigDecimal _nmoney) {
        this.nmoney = _nmoney;
    }


    public String getSpurpose()
    {
        return spurpose;
    }
     /**
     *   Setter S_PURPOSE        * */
    public void setSpurpose(String _spurpose) {
        this.spurpose = _spurpose;
    }


    public String getSpaybankcode()
    {
        return spaybankcode;
    }
     /**
     *   Setter S_PAYBANKCODE        * */
    public void setSpaybankcode(String _spaybankcode) {
        this.spaybankcode = _spaybankcode;
    }


    public String getSpaybankname()
    {
        return spaybankname;
    }
     /**
     *   Setter S_PAYBANKNAME        * */
    public void setSpaybankname(String _spaybankname) {
        this.spaybankname = _spaybankname;
    }


    public String getSpaybankno()
    {
        return spaybankno;
    }
     /**
     *   Setter S_PAYBANKNO        * */
    public void setSpaybankno(String _spaybankno) {
        this.spaybankno = _spaybankno;
    }


    public String getSrecname()
    {
        return srecname;
    }
     /**
     *   Setter S_RECNAME        * */
    public void setSrecname(String _srecname) {
        this.srecname = _srecname;
    }


    public String getSrecbankname()
    {
        return srecbankname;
    }
     /**
     *   Setter S_RECBANKNAME        * */
    public void setSrecbankname(String _srecbankname) {
        this.srecbankname = _srecbankname;
    }


    public String getSrecbankno()
    {
        return srecbankno;
    }
     /**
     *   Setter S_RECBANKNO        * */
    public void setSrecbankno(String _srecbankno) {
        this.srecbankno = _srecbankno;
    }


    public String getSobillno()
    {
        return sobillno;
    }
     /**
     *   Setter S_OBILLNO        * */
    public void setSobillno(String _sobillno) {
        this.sobillno = _sobillno;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME , NOT NULL        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getSdealno()
    {
        return sdealno;
    }
     /**
     *   Setter S_DEALNO , NOT NULL        * */
    public void setSdealno(String _sdealno) {
        this.sdealno = _sdealno;
    }


    public String getSpackageno()
    {
        return spackageno;
    }
     /**
     *   Setter S_PACKAGENO , NOT NULL        * */
    public void setSpackageno(String _spackageno) {
        this.spackageno = _spackageno;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_OFYEAR , NOT NULL       * */
    public static String  columnSofyear()
    {
        return "S_OFYEAR";
    }
   
    /**
    *   Getter S_TAXTICKETNO , NOT NULL       * */
    public static String  columnStaxticketno()
    {
        return "S_TAXTICKETNO";
    }
   
    /**
    *   Getter S_GENTICKETDATE , NOT NULL       * */
    public static String  columnSgenticketdate()
    {
        return "S_GENTICKETDATE";
    }
   
    /**
    *   Getter S_BUDGETUNITCODE , NOT NULL       * */
    public static String  columnSbudgetunitcode()
    {
        return "S_BUDGETUNITCODE";
    }
   
    /**
    *   Getter S_UNITCODENAME       * */
    public static String  columnSunitcodename()
    {
        return "S_UNITCODENAME";
    }
   
    /**
    *   Getter S_SETTLETYPE       * */
    public static String  columnSsettletype()
    {
        return "S_SETTLETYPE";
    }
   
    /**
    *   Getter S_SETTLENO       * */
    public static String  columnSsettleno()
    {
        return "S_SETTLENO";
    }
   
    /**
    *   Getter N_MONEY , NOT NULL       * */
    public static String  columnNmoney()
    {
        return "N_MONEY";
    }
   
    /**
    *   Getter S_PURPOSE       * */
    public static String  columnSpurpose()
    {
        return "S_PURPOSE";
    }
   
    /**
    *   Getter S_PAYBANKCODE       * */
    public static String  columnSpaybankcode()
    {
        return "S_PAYBANKCODE";
    }
   
    /**
    *   Getter S_PAYBANKNAME       * */
    public static String  columnSpaybankname()
    {
        return "S_PAYBANKNAME";
    }
   
    /**
    *   Getter S_PAYBANKNO       * */
    public static String  columnSpaybankno()
    {
        return "S_PAYBANKNO";
    }
   
    /**
    *   Getter S_RECNAME       * */
    public static String  columnSrecname()
    {
        return "S_RECNAME";
    }
   
    /**
    *   Getter S_RECBANKNAME       * */
    public static String  columnSrecbankname()
    {
        return "S_RECBANKNAME";
    }
   
    /**
    *   Getter S_RECBANKNO       * */
    public static String  columnSrecbankno()
    {
        return "S_RECBANKNO";
    }
   
    /**
    *   Getter S_OBILLNO       * */
    public static String  columnSobillno()
    {
        return "S_OBILLNO";
    }
   
    /**
    *   Getter S_FILENAME , NOT NULL       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_ORGCODE , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_DEALNO , NOT NULL       * */
    public static String  columnSdealno()
    {
        return "S_DEALNO";
    }
   
    /**
    *   Getter S_PACKAGENO , NOT NULL       * */
    public static String  columnSpackageno()
    {
        return "S_PACKAGENO";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_DIRECTPAYFILEMAIN_TMP";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[20];        
        columnNames[0]="S_OFYEAR";
        columnNames[1]="S_TAXTICKETNO";
        columnNames[2]="S_GENTICKETDATE";
        columnNames[3]="S_BUDGETUNITCODE";
        columnNames[4]="S_UNITCODENAME";
        columnNames[5]="S_SETTLETYPE";
        columnNames[6]="S_SETTLENO";
        columnNames[7]="N_MONEY";
        columnNames[8]="S_PURPOSE";
        columnNames[9]="S_PAYBANKCODE";
        columnNames[10]="S_PAYBANKNAME";
        columnNames[11]="S_PAYBANKNO";
        columnNames[12]="S_RECNAME";
        columnNames[13]="S_RECBANKNAME";
        columnNames[14]="S_RECBANKNO";
        columnNames[15]="S_OBILLNO";
        columnNames[16]="S_FILENAME";
        columnNames[17]="S_ORGCODE";
        columnNames[18]="S_DEALNO";
        columnNames[19]="S_PACKAGENO";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvDirectpayfilemainTmpDto))
            return false;

        TvDirectpayfilemainTmpDto bean = (TvDirectpayfilemainTmpDto) obj;


      //compare field sofyear
      if((this.sofyear==null && bean.sofyear!=null) || (this.sofyear!=null && bean.sofyear==null))
          return false;
        else if(this.sofyear==null && bean.sofyear==null){
        }
        else{
          if(!bean.sofyear.equals(this.sofyear))
               return false;
     }
      //compare field staxticketno
      if((this.staxticketno==null && bean.staxticketno!=null) || (this.staxticketno!=null && bean.staxticketno==null))
          return false;
        else if(this.staxticketno==null && bean.staxticketno==null){
        }
        else{
          if(!bean.staxticketno.equals(this.staxticketno))
               return false;
     }
      //compare field sgenticketdate
      if((this.sgenticketdate==null && bean.sgenticketdate!=null) || (this.sgenticketdate!=null && bean.sgenticketdate==null))
          return false;
        else if(this.sgenticketdate==null && bean.sgenticketdate==null){
        }
        else{
          if(!bean.sgenticketdate.equals(this.sgenticketdate))
               return false;
     }
      //compare field sbudgetunitcode
      if((this.sbudgetunitcode==null && bean.sbudgetunitcode!=null) || (this.sbudgetunitcode!=null && bean.sbudgetunitcode==null))
          return false;
        else if(this.sbudgetunitcode==null && bean.sbudgetunitcode==null){
        }
        else{
          if(!bean.sbudgetunitcode.equals(this.sbudgetunitcode))
               return false;
     }
      //compare field sunitcodename
      if((this.sunitcodename==null && bean.sunitcodename!=null) || (this.sunitcodename!=null && bean.sunitcodename==null))
          return false;
        else if(this.sunitcodename==null && bean.sunitcodename==null){
        }
        else{
          if(!bean.sunitcodename.equals(this.sunitcodename))
               return false;
     }
      //compare field ssettletype
      if((this.ssettletype==null && bean.ssettletype!=null) || (this.ssettletype!=null && bean.ssettletype==null))
          return false;
        else if(this.ssettletype==null && bean.ssettletype==null){
        }
        else{
          if(!bean.ssettletype.equals(this.ssettletype))
               return false;
     }
      //compare field ssettleno
      if((this.ssettleno==null && bean.ssettleno!=null) || (this.ssettleno!=null && bean.ssettleno==null))
          return false;
        else if(this.ssettleno==null && bean.ssettleno==null){
        }
        else{
          if(!bean.ssettleno.equals(this.ssettleno))
               return false;
     }
      //compare field nmoney
      if((this.nmoney==null && bean.nmoney!=null) || (this.nmoney!=null && bean.nmoney==null))
          return false;
        else if(this.nmoney==null && bean.nmoney==null){
        }
        else{
          if(!bean.nmoney.equals(this.nmoney))
               return false;
     }
      //compare field spurpose
      if((this.spurpose==null && bean.spurpose!=null) || (this.spurpose!=null && bean.spurpose==null))
          return false;
        else if(this.spurpose==null && bean.spurpose==null){
        }
        else{
          if(!bean.spurpose.equals(this.spurpose))
               return false;
     }
      //compare field spaybankcode
      if((this.spaybankcode==null && bean.spaybankcode!=null) || (this.spaybankcode!=null && bean.spaybankcode==null))
          return false;
        else if(this.spaybankcode==null && bean.spaybankcode==null){
        }
        else{
          if(!bean.spaybankcode.equals(this.spaybankcode))
               return false;
     }
      //compare field spaybankname
      if((this.spaybankname==null && bean.spaybankname!=null) || (this.spaybankname!=null && bean.spaybankname==null))
          return false;
        else if(this.spaybankname==null && bean.spaybankname==null){
        }
        else{
          if(!bean.spaybankname.equals(this.spaybankname))
               return false;
     }
      //compare field spaybankno
      if((this.spaybankno==null && bean.spaybankno!=null) || (this.spaybankno!=null && bean.spaybankno==null))
          return false;
        else if(this.spaybankno==null && bean.spaybankno==null){
        }
        else{
          if(!bean.spaybankno.equals(this.spaybankno))
               return false;
     }
      //compare field srecname
      if((this.srecname==null && bean.srecname!=null) || (this.srecname!=null && bean.srecname==null))
          return false;
        else if(this.srecname==null && bean.srecname==null){
        }
        else{
          if(!bean.srecname.equals(this.srecname))
               return false;
     }
      //compare field srecbankname
      if((this.srecbankname==null && bean.srecbankname!=null) || (this.srecbankname!=null && bean.srecbankname==null))
          return false;
        else if(this.srecbankname==null && bean.srecbankname==null){
        }
        else{
          if(!bean.srecbankname.equals(this.srecbankname))
               return false;
     }
      //compare field srecbankno
      if((this.srecbankno==null && bean.srecbankno!=null) || (this.srecbankno!=null && bean.srecbankno==null))
          return false;
        else if(this.srecbankno==null && bean.srecbankno==null){
        }
        else{
          if(!bean.srecbankno.equals(this.srecbankno))
               return false;
     }
      //compare field sobillno
      if((this.sobillno==null && bean.sobillno!=null) || (this.sobillno!=null && bean.sobillno==null))
          return false;
        else if(this.sobillno==null && bean.sobillno==null){
        }
        else{
          if(!bean.sobillno.equals(this.sobillno))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field sdealno
      if((this.sdealno==null && bean.sdealno!=null) || (this.sdealno!=null && bean.sdealno==null))
          return false;
        else if(this.sdealno==null && bean.sdealno==null){
        }
        else{
          if(!bean.sdealno.equals(this.sdealno))
               return false;
     }
      //compare field spackageno
      if((this.spackageno==null && bean.spackageno!=null) || (this.spackageno!=null && bean.spackageno==null))
          return false;
        else if(this.spackageno==null && bean.spackageno==null){
        }
        else{
          if(!bean.spackageno.equals(this.spackageno))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sofyear!=null)
          _hash_ = _hash_ * 31+ this.sofyear.hashCode() ;
        if(this.staxticketno!=null)
          _hash_ = _hash_ * 31+ this.staxticketno.hashCode() ;
        if(this.sgenticketdate!=null)
          _hash_ = _hash_ * 31+ this.sgenticketdate.hashCode() ;
        if(this.sbudgetunitcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetunitcode.hashCode() ;
        if(this.sunitcodename!=null)
          _hash_ = _hash_ * 31+ this.sunitcodename.hashCode() ;
        if(this.ssettletype!=null)
          _hash_ = _hash_ * 31+ this.ssettletype.hashCode() ;
        if(this.ssettleno!=null)
          _hash_ = _hash_ * 31+ this.ssettleno.hashCode() ;
        if(this.nmoney!=null)
          _hash_ = _hash_ * 31+ this.nmoney.hashCode() ;
        if(this.spurpose!=null)
          _hash_ = _hash_ * 31+ this.spurpose.hashCode() ;
        if(this.spaybankcode!=null)
          _hash_ = _hash_ * 31+ this.spaybankcode.hashCode() ;
        if(this.spaybankname!=null)
          _hash_ = _hash_ * 31+ this.spaybankname.hashCode() ;
        if(this.spaybankno!=null)
          _hash_ = _hash_ * 31+ this.spaybankno.hashCode() ;
        if(this.srecname!=null)
          _hash_ = _hash_ * 31+ this.srecname.hashCode() ;
        if(this.srecbankname!=null)
          _hash_ = _hash_ * 31+ this.srecbankname.hashCode() ;
        if(this.srecbankno!=null)
          _hash_ = _hash_ * 31+ this.srecbankno.hashCode() ;
        if(this.sobillno!=null)
          _hash_ = _hash_ * 31+ this.sobillno.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.sdealno!=null)
          _hash_ = _hash_ * 31+ this.sdealno.hashCode() ;
        if(this.spackageno!=null)
          _hash_ = _hash_ * 31+ this.spackageno.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvDirectpayfilemainTmpDto bean = new TvDirectpayfilemainTmpDto();

          if (this.sofyear != null)
            bean.sofyear = new String(this.sofyear);
          if (this.staxticketno != null)
            bean.staxticketno = new String(this.staxticketno);
          if (this.sgenticketdate != null)
            bean.sgenticketdate = new String(this.sgenticketdate);
          if (this.sbudgetunitcode != null)
            bean.sbudgetunitcode = new String(this.sbudgetunitcode);
          if (this.sunitcodename != null)
            bean.sunitcodename = new String(this.sunitcodename);
          if (this.ssettletype != null)
            bean.ssettletype = new String(this.ssettletype);
          if (this.ssettleno != null)
            bean.ssettleno = new String(this.ssettleno);
          if (this.nmoney != null)
            bean.nmoney = new BigDecimal(this.nmoney.toString());
          if (this.spurpose != null)
            bean.spurpose = new String(this.spurpose);
          if (this.spaybankcode != null)
            bean.spaybankcode = new String(this.spaybankcode);
          if (this.spaybankname != null)
            bean.spaybankname = new String(this.spaybankname);
          if (this.spaybankno != null)
            bean.spaybankno = new String(this.spaybankno);
          if (this.srecname != null)
            bean.srecname = new String(this.srecname);
          if (this.srecbankname != null)
            bean.srecbankname = new String(this.srecbankname);
          if (this.srecbankno != null)
            bean.srecbankno = new String(this.srecbankno);
          if (this.sobillno != null)
            bean.sobillno = new String(this.sobillno);
          if (this.sfilename != null)
            bean.sfilename = new String(this.sfilename);
          if (this.sorgcode != null)
            bean.sorgcode = new String(this.sorgcode);
          if (this.sdealno != null)
            bean.sdealno = new String(this.sdealno);
          if (this.spackageno != null)
            bean.spackageno = new String(this.spackageno);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvDirectpayfilemainTmpDto").append(sep);
        sb.append("[sofyear]").append(" = ").append(sofyear).append(sep);
        sb.append("[staxticketno]").append(" = ").append(staxticketno).append(sep);
        sb.append("[sgenticketdate]").append(" = ").append(sgenticketdate).append(sep);
        sb.append("[sbudgetunitcode]").append(" = ").append(sbudgetunitcode).append(sep);
        sb.append("[sunitcodename]").append(" = ").append(sunitcodename).append(sep);
        sb.append("[ssettletype]").append(" = ").append(ssettletype).append(sep);
        sb.append("[ssettleno]").append(" = ").append(ssettleno).append(sep);
        sb.append("[nmoney]").append(" = ").append(nmoney).append(sep);
        sb.append("[spurpose]").append(" = ").append(spurpose).append(sep);
        sb.append("[spaybankcode]").append(" = ").append(spaybankcode).append(sep);
        sb.append("[spaybankname]").append(" = ").append(spaybankname).append(sep);
        sb.append("[spaybankno]").append(" = ").append(spaybankno).append(sep);
        sb.append("[srecname]").append(" = ").append(srecname).append(sep);
        sb.append("[srecbankname]").append(" = ").append(srecbankname).append(sep);
        sb.append("[srecbankno]").append(" = ").append(srecbankno).append(sep);
        sb.append("[sobillno]").append(" = ").append(sobillno).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[sdealno]").append(" = ").append(sdealno).append(sep);
        sb.append("[spackageno]").append(" = ").append(spackageno).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_OFYEAR
      if (this.getSofyear()==null)
             sb.append("S_OFYEAR不能为空; ");
      if (this.getSofyear()!=null)
             if (this.getSofyear().getBytes().length > 4)
                sb.append("S_OFYEAR宽度不能超过 "+4+"个字符; ");
    
    //check field S_TAXTICKETNO
      if (this.getStaxticketno()==null)
             sb.append("S_TAXTICKETNO不能为空; ");
      if (this.getStaxticketno()!=null)
             if (this.getStaxticketno().getBytes().length > 30)
                sb.append("S_TAXTICKETNO宽度不能超过 "+30+"个字符; ");
    
    //check field S_GENTICKETDATE
      if (this.getSgenticketdate()==null)
             sb.append("S_GENTICKETDATE不能为空; ");
      if (this.getSgenticketdate()!=null)
             if (this.getSgenticketdate().getBytes().length > 8)
                sb.append("S_GENTICKETDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_BUDGETUNITCODE
      if (this.getSbudgetunitcode()==null)
             sb.append("S_BUDGETUNITCODE不能为空; ");
      if (this.getSbudgetunitcode()!=null)
             if (this.getSbudgetunitcode().getBytes().length > 30)
                sb.append("S_BUDGETUNITCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_UNITCODENAME
      if (this.getSunitcodename()!=null)
             if (this.getSunitcodename().getBytes().length > 120)
                sb.append("S_UNITCODENAME宽度不能超过 "+120+"个字符; ");
    
    //check field S_SETTLETYPE
      if (this.getSsettletype()!=null)
             if (this.getSsettletype().getBytes().length > 1)
                sb.append("S_SETTLETYPE宽度不能超过 "+1+"个字符; ");
    
    //check field S_SETTLENO
      if (this.getSsettleno()!=null)
             if (this.getSsettleno().getBytes().length > 60)
                sb.append("S_SETTLENO宽度不能超过 "+60+"个字符; ");
    
    //check field N_MONEY
      if (this.getNmoney()==null)
             sb.append("N_MONEY不能为空; ");
      
    //check field S_PURPOSE
      if (this.getSpurpose()!=null)
             if (this.getSpurpose().getBytes().length > 200)
                sb.append("S_PURPOSE宽度不能超过 "+200+"个字符; ");
    
    //check field S_PAYBANKCODE
      if (this.getSpaybankcode()!=null)
             if (this.getSpaybankcode().getBytes().length > 60)
                sb.append("S_PAYBANKCODE宽度不能超过 "+60+"个字符; ");
    
    //check field S_PAYBANKNAME
      if (this.getSpaybankname()!=null)
             if (this.getSpaybankname().getBytes().length > 120)
                sb.append("S_PAYBANKNAME宽度不能超过 "+120+"个字符; ");
    
    //check field S_PAYBANKNO
      if (this.getSpaybankno()!=null)
             if (this.getSpaybankno().getBytes().length > 60)
                sb.append("S_PAYBANKNO宽度不能超过 "+60+"个字符; ");
    
    //check field S_RECNAME
      if (this.getSrecname()!=null)
             if (this.getSrecname().getBytes().length > 120)
                sb.append("S_RECNAME宽度不能超过 "+120+"个字符; ");
    
    //check field S_RECBANKNAME
      if (this.getSrecbankname()!=null)
             if (this.getSrecbankname().getBytes().length > 120)
                sb.append("S_RECBANKNAME宽度不能超过 "+120+"个字符; ");
    
    //check field S_RECBANKNO
      if (this.getSrecbankno()!=null)
             if (this.getSrecbankno().getBytes().length > 60)
                sb.append("S_RECBANKNO宽度不能超过 "+60+"个字符; ");
    
    //check field S_OBILLNO
      if (this.getSobillno()!=null)
             if (this.getSobillno().getBytes().length > 6)
                sb.append("S_OBILLNO宽度不能超过 "+6+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()==null)
             sb.append("S_FILENAME不能为空; ");
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_DEALNO
      if (this.getSdealno()==null)
             sb.append("S_DEALNO不能为空; ");
      if (this.getSdealno()!=null)
             if (this.getSdealno().getBytes().length > 8)
                sb.append("S_DEALNO宽度不能超过 "+8+"个字符; ");
    
    //check field S_PACKAGENO
      if (this.getSpackageno()==null)
             sb.append("S_PACKAGENO不能为空; ");
      if (this.getSpackageno()!=null)
             if (this.getSpackageno().getBytes().length > 8)
                sb.append("S_PACKAGENO宽度不能超过 "+8+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_OFYEAR
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OFYEAR")) {
               if (this.getSofyear()==null)
                    sb.append("S_OFYEAR 不能为空; ");
               if (this.getSofyear()!=null)
                    if (this.getSofyear().getBytes().length > 4)
                        sb.append("S_OFYEAR 宽度不能超过 "+4+"个字符");
             break;
         }
  }
    
    //check field S_TAXTICKETNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTICKETNO")) {
               if (this.getStaxticketno()==null)
                    sb.append("S_TAXTICKETNO 不能为空; ");
               if (this.getStaxticketno()!=null)
                    if (this.getStaxticketno().getBytes().length > 30)
                        sb.append("S_TAXTICKETNO 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_GENTICKETDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_GENTICKETDATE")) {
               if (this.getSgenticketdate()==null)
                    sb.append("S_GENTICKETDATE 不能为空; ");
               if (this.getSgenticketdate()!=null)
                    if (this.getSgenticketdate().getBytes().length > 8)
                        sb.append("S_GENTICKETDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETUNITCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETUNITCODE")) {
               if (this.getSbudgetunitcode()==null)
                    sb.append("S_BUDGETUNITCODE 不能为空; ");
               if (this.getSbudgetunitcode()!=null)
                    if (this.getSbudgetunitcode().getBytes().length > 30)
                        sb.append("S_BUDGETUNITCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_UNITCODENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_UNITCODENAME")) {
                 if (this.getSunitcodename()!=null)
                    if (this.getSunitcodename().getBytes().length > 120)
                        sb.append("S_UNITCODENAME 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_SETTLETYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SETTLETYPE")) {
                 if (this.getSsettletype()!=null)
                    if (this.getSsettletype().getBytes().length > 1)
                        sb.append("S_SETTLETYPE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_SETTLENO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SETTLENO")) {
                 if (this.getSsettleno()!=null)
                    if (this.getSsettleno().getBytes().length > 60)
                        sb.append("S_SETTLENO 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field N_MONEY
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_MONEY")) {
               if (this.getNmoney()==null)
                    sb.append("N_MONEY 不能为空; ");
               break;
         }
  }
    
    //check field S_PURPOSE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PURPOSE")) {
                 if (this.getSpurpose()!=null)
                    if (this.getSpurpose().getBytes().length > 200)
                        sb.append("S_PURPOSE 宽度不能超过 "+200+"个字符");
             break;
         }
  }
    
    //check field S_PAYBANKCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBANKCODE")) {
                 if (this.getSpaybankcode()!=null)
                    if (this.getSpaybankcode().getBytes().length > 60)
                        sb.append("S_PAYBANKCODE 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PAYBANKNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBANKNAME")) {
                 if (this.getSpaybankname()!=null)
                    if (this.getSpaybankname().getBytes().length > 120)
                        sb.append("S_PAYBANKNAME 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_PAYBANKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBANKNO")) {
                 if (this.getSpaybankno()!=null)
                    if (this.getSpaybankno().getBytes().length > 60)
                        sb.append("S_PAYBANKNO 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_RECNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RECNAME")) {
                 if (this.getSrecname()!=null)
                    if (this.getSrecname().getBytes().length > 120)
                        sb.append("S_RECNAME 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_RECBANKNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RECBANKNAME")) {
                 if (this.getSrecbankname()!=null)
                    if (this.getSrecbankname().getBytes().length > 120)
                        sb.append("S_RECBANKNAME 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_RECBANKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RECBANKNO")) {
                 if (this.getSrecbankno()!=null)
                    if (this.getSrecbankno().getBytes().length > 60)
                        sb.append("S_RECBANKNO 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_OBILLNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OBILLNO")) {
                 if (this.getSobillno()!=null)
                    if (this.getSobillno().getBytes().length > 6)
                        sb.append("S_OBILLNO 宽度不能超过 "+6+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
               if (this.getSfilename()==null)
                    sb.append("S_FILENAME 不能为空; ");
               if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_DEALNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEALNO")) {
               if (this.getSdealno()==null)
                    sb.append("S_DEALNO 不能为空; ");
               if (this.getSdealno()!=null)
                    if (this.getSdealno().getBytes().length > 8)
                        sb.append("S_DEALNO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_PACKAGENO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PACKAGENO")) {
               if (this.getSpackageno()==null)
                    sb.append("S_PACKAGENO 不能为空; ");
               if (this.getSpackageno()!=null)
                    if (this.getSpackageno().getBytes().length > 8)
                        sb.append("S_PACKAGENO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      throw new RuntimeException("此dto没有PK，不能进行此操作");
    };
}
