    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvExceptionmanPK;
/**
 * <p>Title: DTO of table: TV_EXCEPTIONMAN</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvExceptionmanDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  I_EXCEPTIONNO BIGINT , PK   , NOT NULL  , Identity  , Generated     */
    protected Long iexceptionno;
    /**
    *  D_WORKDATE CHARACTER         */
    protected String dworkdate;
    /**
    *  C_SYSID CHARACTER         */
    protected String csysid;
    /**
    *  S_USERID VARCHAR         */
    protected String suserid;
    /**
    *  S_EXCEPTIONINFO VARCHAR         */
    protected String sexceptioninfo;
    /**
    *  S_OFBIZKIND VARCHAR         */
    protected String sofbizkind;
    /**
    *  TS_UPDATE TIMESTAMP         */
    protected Timestamp tsupdate;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public Long getIexceptionno()
    {
        return iexceptionno;
    }
     /**
     *   Setter I_EXCEPTIONNO, PK , NOT NULL  , Identity  , Generated      * */
    public void setIexceptionno(Long _iexceptionno) {
        this.iexceptionno = _iexceptionno;
    }


    public String getDworkdate()
    {
        return dworkdate;
    }
     /**
     *   Setter D_WORKDATE        * */
    public void setDworkdate(String _dworkdate) {
        this.dworkdate = _dworkdate;
    }


    public String getCsysid()
    {
        return csysid;
    }
     /**
     *   Setter C_SYSID        * */
    public void setCsysid(String _csysid) {
        this.csysid = _csysid;
    }


    public String getSuserid()
    {
        return suserid;
    }
     /**
     *   Setter S_USERID        * */
    public void setSuserid(String _suserid) {
        this.suserid = _suserid;
    }


    public String getSexceptioninfo()
    {
        return sexceptioninfo;
    }
     /**
     *   Setter S_EXCEPTIONINFO        * */
    public void setSexceptioninfo(String _sexceptioninfo) {
        this.sexceptioninfo = _sexceptioninfo;
    }


    public String getSofbizkind()
    {
        return sofbizkind;
    }
     /**
     *   Setter S_OFBIZKIND        * */
    public void setSofbizkind(String _sofbizkind) {
        this.sofbizkind = _sofbizkind;
    }


    public Timestamp getTsupdate()
    {
        return tsupdate;
    }
     /**
     *   Setter TS_UPDATE        * */
    public void setTsupdate(Timestamp _tsupdate) {
        this.tsupdate = _tsupdate;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter I_EXCEPTIONNO, PK , NOT NULL  , Identity  , Generated     * */
    public static String  columnIexceptionno()
    {
        return "I_EXCEPTIONNO";
    }
   
    /**
    *   Getter D_WORKDATE       * */
    public static String  columnDworkdate()
    {
        return "D_WORKDATE";
    }
   
    /**
    *   Getter C_SYSID       * */
    public static String  columnCsysid()
    {
        return "C_SYSID";
    }
   
    /**
    *   Getter S_USERID       * */
    public static String  columnSuserid()
    {
        return "S_USERID";
    }
   
    /**
    *   Getter S_EXCEPTIONINFO       * */
    public static String  columnSexceptioninfo()
    {
        return "S_EXCEPTIONINFO";
    }
   
    /**
    *   Getter S_OFBIZKIND       * */
    public static String  columnSofbizkind()
    {
        return "S_OFBIZKIND";
    }
   
    /**
    *   Getter TS_UPDATE       * */
    public static String  columnTsupdate()
    {
        return "TS_UPDATE";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_EXCEPTIONMAN";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[7];        
        columnNames[0]="I_EXCEPTIONNO";
        columnNames[1]="D_WORKDATE";
        columnNames[2]="C_SYSID";
        columnNames[3]="S_USERID";
        columnNames[4]="S_EXCEPTIONINFO";
        columnNames[5]="S_OFBIZKIND";
        columnNames[6]="TS_UPDATE";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvExceptionmanDto))
            return false;

        TvExceptionmanDto bean = (TvExceptionmanDto) obj;


      //compare field iexceptionno
      if((this.iexceptionno==null && bean.iexceptionno!=null) || (this.iexceptionno!=null && bean.iexceptionno==null))
          return false;
        else if(this.iexceptionno==null && bean.iexceptionno==null){
        }
        else{
          if(!bean.iexceptionno.equals(this.iexceptionno))
               return false;
     }
      //compare field dworkdate
      if((this.dworkdate==null && bean.dworkdate!=null) || (this.dworkdate!=null && bean.dworkdate==null))
          return false;
        else if(this.dworkdate==null && bean.dworkdate==null){
        }
        else{
          if(!bean.dworkdate.equals(this.dworkdate))
               return false;
     }
      //compare field csysid
      if((this.csysid==null && bean.csysid!=null) || (this.csysid!=null && bean.csysid==null))
          return false;
        else if(this.csysid==null && bean.csysid==null){
        }
        else{
          if(!bean.csysid.equals(this.csysid))
               return false;
     }
      //compare field suserid
      if((this.suserid==null && bean.suserid!=null) || (this.suserid!=null && bean.suserid==null))
          return false;
        else if(this.suserid==null && bean.suserid==null){
        }
        else{
          if(!bean.suserid.equals(this.suserid))
               return false;
     }
      //compare field sexceptioninfo
      if((this.sexceptioninfo==null && bean.sexceptioninfo!=null) || (this.sexceptioninfo!=null && bean.sexceptioninfo==null))
          return false;
        else if(this.sexceptioninfo==null && bean.sexceptioninfo==null){
        }
        else{
          if(!bean.sexceptioninfo.equals(this.sexceptioninfo))
               return false;
     }
      //compare field sofbizkind
      if((this.sofbizkind==null && bean.sofbizkind!=null) || (this.sofbizkind!=null && bean.sofbizkind==null))
          return false;
        else if(this.sofbizkind==null && bean.sofbizkind==null){
        }
        else{
          if(!bean.sofbizkind.equals(this.sofbizkind))
               return false;
     }
      //compare field tsupdate
      if((this.tsupdate==null && bean.tsupdate!=null) || (this.tsupdate!=null && bean.tsupdate==null))
          return false;
        else if(this.tsupdate==null && bean.tsupdate==null){
        }
        else{
          if(!bean.tsupdate.equals(this.tsupdate))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.iexceptionno!=null)
          _hash_ = _hash_ * 31+ this.iexceptionno.hashCode() ;
        if(this.dworkdate!=null)
          _hash_ = _hash_ * 31+ this.dworkdate.hashCode() ;
        if(this.csysid!=null)
          _hash_ = _hash_ * 31+ this.csysid.hashCode() ;
        if(this.suserid!=null)
          _hash_ = _hash_ * 31+ this.suserid.hashCode() ;
        if(this.sexceptioninfo!=null)
          _hash_ = _hash_ * 31+ this.sexceptioninfo.hashCode() ;
        if(this.sofbizkind!=null)
          _hash_ = _hash_ * 31+ this.sofbizkind.hashCode() ;
        if(this.tsupdate!=null)
          _hash_ = _hash_ * 31+ this.tsupdate.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvExceptionmanDto bean = new TvExceptionmanDto();

          bean.iexceptionno = this.iexceptionno;

          if (this.dworkdate != null)
            bean.dworkdate = new String(this.dworkdate);
          if (this.csysid != null)
            bean.csysid = new String(this.csysid);
          if (this.suserid != null)
            bean.suserid = new String(this.suserid);
          if (this.sexceptioninfo != null)
            bean.sexceptioninfo = new String(this.sexceptioninfo);
          if (this.sofbizkind != null)
            bean.sofbizkind = new String(this.sofbizkind);
          if (this.tsupdate != null)
            bean.tsupdate = (Timestamp) this.tsupdate.clone();
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvExceptionmanDto").append(sep);
        sb.append("[iexceptionno]").append(" = ").append(iexceptionno).append(sep);
        sb.append("[dworkdate]").append(" = ").append(dworkdate).append(sep);
        sb.append("[csysid]").append(" = ").append(csysid).append(sep);
        sb.append("[suserid]").append(" = ").append(suserid).append(sep);
        sb.append("[sexceptioninfo]").append(" = ").append(sexceptioninfo).append(sep);
        sb.append("[sofbizkind]").append(" = ").append(sofbizkind).append(sep);
        sb.append("[tsupdate]").append(" = ").append(tsupdate).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //don't need check field I_EXCEPTIONNO,it is generated column
  
    //check field D_WORKDATE
      if (this.getDworkdate()!=null)
             if (this.getDworkdate().getBytes().length > 8)
                sb.append("D_WORKDATE宽度不能超过 "+8+"个字符; ");
    
    //check field C_SYSID
      if (this.getCsysid()!=null)
             if (this.getCsysid().getBytes().length > 1)
                sb.append("C_SYSID宽度不能超过 "+1+"个字符; ");
    
    //check field S_USERID
      if (this.getSuserid()!=null)
             if (this.getSuserid().getBytes().length > 20)
                sb.append("S_USERID宽度不能超过 "+20+"个字符; ");
    
    //check field S_EXCEPTIONINFO
      if (this.getSexceptioninfo()!=null)
             if (this.getSexceptioninfo().getBytes().length > 1024)
                sb.append("S_EXCEPTIONINFO宽度不能超过 "+1024+"个字符; ");
    
    //check field S_OFBIZKIND
      if (this.getSofbizkind()!=null)
             if (this.getSofbizkind().getBytes().length > 200)
                sb.append("S_OFBIZKIND宽度不能超过 "+200+"个字符; ");
    
    //check field TS_UPDATE
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //don't need check field I_EXCEPTIONNO,it is generated column
  
    //check field D_WORKDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("D_WORKDATE")) {
                 if (this.getDworkdate()!=null)
                    if (this.getDworkdate().getBytes().length > 8)
                        sb.append("D_WORKDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field C_SYSID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_SYSID")) {
                 if (this.getCsysid()!=null)
                    if (this.getCsysid().getBytes().length > 1)
                        sb.append("C_SYSID 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_USERID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_USERID")) {
                 if (this.getSuserid()!=null)
                    if (this.getSuserid().getBytes().length > 20)
                        sb.append("S_USERID 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_EXCEPTIONINFO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXCEPTIONINFO")) {
                 if (this.getSexceptioninfo()!=null)
                    if (this.getSexceptioninfo().getBytes().length > 1024)
                        sb.append("S_EXCEPTIONINFO 宽度不能超过 "+1024+"个字符");
             break;
         }
  }
    
    //check field S_OFBIZKIND
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OFBIZKIND")) {
                 if (this.getSofbizkind()!=null)
                    if (this.getSofbizkind().getBytes().length > 200)
                        sb.append("S_OFBIZKIND 宽度不能超过 "+200+"个字符");
             break;
         }
  }
    
    //check field TS_UPDATE
          
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TvExceptionmanPK pk = new TvExceptionmanPK();
      pk.setIexceptionno(getIexceptionno());
      return pk;
    };
}
