    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvFilepackagerefPK;
/**
 * <p>Title: DTO of table: TV_FILEPACKAGEREF</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvFilepackagerefDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_ORGCODE VARCHAR , PK   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_TRECODE CHARACTER , PK   , NOT NULL       */
    protected String strecode;
    /**
    *  S_FILENAME VARCHAR , PK   , NOT NULL       */
    protected String sfilename;
    /**
    *  S_TAXORGCODE VARCHAR   , NOT NULL       */
    protected String staxorgcode;
    /**
    *  S_COMMITDATE CHARACTER   , NOT NULL       */
    protected String scommitdate;
    /**
    *  S_ACCDATE CHARACTER   , NOT NULL       */
    protected String saccdate;
    /**
    *  S_PACKAGENO VARCHAR , PK   , NOT NULL       */
    protected String spackageno;
    /**
    *  S_OPERATIONTYPECODE VARCHAR   , NOT NULL       */
    protected String soperationtypecode;
    /**
    *  I_COUNT INTEGER   , NOT NULL       */
    protected Integer icount;
    /**
    *  N_MONEY DECIMAL   , NOT NULL       */
    protected BigDecimal nmoney;
    /**
    *  S_RETCODE CHARACTER   , NOT NULL       */
    protected String sretcode;
    /**
    *  S_USERCODE VARCHAR   , NOT NULL       */
    protected String susercode;
    /**
    *  I_MODICOUNT INTEGER   , NOT NULL       */
    protected Integer imodicount;
    /**
    *  S_DEMO VARCHAR         */
    protected String sdemo;
    /**
    *  S_CHKSTATE CHARACTER         */
    protected String schkstate;
    /**
    *  S_MSGID VARCHAR         */
    protected String smsgid;
    /**
    *  T_SENDTIME TIMESTAMP         */
    protected Timestamp tsendtime;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE, PK , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getStrecode()
    {
        return strecode;
    }
     /**
     *   Setter S_TRECODE, PK , NOT NULL        * */
    public void setStrecode(String _strecode) {
        this.strecode = _strecode;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME, PK , NOT NULL        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getStaxorgcode()
    {
        return staxorgcode;
    }
     /**
     *   Setter S_TAXORGCODE , NOT NULL        * */
    public void setStaxorgcode(String _staxorgcode) {
        this.staxorgcode = _staxorgcode;
    }


    public String getScommitdate()
    {
        return scommitdate;
    }
     /**
     *   Setter S_COMMITDATE , NOT NULL        * */
    public void setScommitdate(String _scommitdate) {
        this.scommitdate = _scommitdate;
    }


    public String getSaccdate()
    {
        return saccdate;
    }
     /**
     *   Setter S_ACCDATE , NOT NULL        * */
    public void setSaccdate(String _saccdate) {
        this.saccdate = _saccdate;
    }


    public String getSpackageno()
    {
        return spackageno;
    }
     /**
     *   Setter S_PACKAGENO, PK , NOT NULL        * */
    public void setSpackageno(String _spackageno) {
        this.spackageno = _spackageno;
    }


    public String getSoperationtypecode()
    {
        return soperationtypecode;
    }
     /**
     *   Setter S_OPERATIONTYPECODE , NOT NULL        * */
    public void setSoperationtypecode(String _soperationtypecode) {
        this.soperationtypecode = _soperationtypecode;
    }


    public Integer getIcount()
    {
        return icount;
    }
     /**
     *   Setter I_COUNT , NOT NULL        * */
    public void setIcount(Integer _icount) {
        this.icount = _icount;
    }


    public BigDecimal getNmoney()
    {
        return nmoney;
    }
     /**
     *   Setter N_MONEY , NOT NULL        * */
    public void setNmoney(BigDecimal _nmoney) {
        this.nmoney = _nmoney;
    }


    public String getSretcode()
    {
        return sretcode;
    }
     /**
     *   Setter S_RETCODE , NOT NULL        * */
    public void setSretcode(String _sretcode) {
        this.sretcode = _sretcode;
    }


    public String getSusercode()
    {
        return susercode;
    }
     /**
     *   Setter S_USERCODE , NOT NULL        * */
    public void setSusercode(String _susercode) {
        this.susercode = _susercode;
    }


    public Integer getImodicount()
    {
        return imodicount;
    }
     /**
     *   Setter I_MODICOUNT , NOT NULL        * */
    public void setImodicount(Integer _imodicount) {
        this.imodicount = _imodicount;
    }


    public String getSdemo()
    {
        return sdemo;
    }
     /**
     *   Setter S_DEMO        * */
    public void setSdemo(String _sdemo) {
        this.sdemo = _sdemo;
    }


    public String getSchkstate()
    {
        return schkstate;
    }
     /**
     *   Setter S_CHKSTATE        * */
    public void setSchkstate(String _schkstate) {
        this.schkstate = _schkstate;
    }


    public String getSmsgid()
    {
        return smsgid;
    }
     /**
     *   Setter S_MSGID        * */
    public void setSmsgid(String _smsgid) {
        this.smsgid = _smsgid;
    }


    public Timestamp getTsendtime()
    {
        return tsendtime;
    }
     /**
     *   Setter T_SENDTIME        * */
    public void setTsendtime(Timestamp _tsendtime) {
        this.tsendtime = _tsendtime;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_ORGCODE, PK , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_TRECODE, PK , NOT NULL       * */
    public static String  columnStrecode()
    {
        return "S_TRECODE";
    }
   
    /**
    *   Getter S_FILENAME, PK , NOT NULL       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_TAXORGCODE , NOT NULL       * */
    public static String  columnStaxorgcode()
    {
        return "S_TAXORGCODE";
    }
   
    /**
    *   Getter S_COMMITDATE , NOT NULL       * */
    public static String  columnScommitdate()
    {
        return "S_COMMITDATE";
    }
   
    /**
    *   Getter S_ACCDATE , NOT NULL       * */
    public static String  columnSaccdate()
    {
        return "S_ACCDATE";
    }
   
    /**
    *   Getter S_PACKAGENO, PK , NOT NULL       * */
    public static String  columnSpackageno()
    {
        return "S_PACKAGENO";
    }
   
    /**
    *   Getter S_OPERATIONTYPECODE , NOT NULL       * */
    public static String  columnSoperationtypecode()
    {
        return "S_OPERATIONTYPECODE";
    }
   
    /**
    *   Getter I_COUNT , NOT NULL       * */
    public static String  columnIcount()
    {
        return "I_COUNT";
    }
   
    /**
    *   Getter N_MONEY , NOT NULL       * */
    public static String  columnNmoney()
    {
        return "N_MONEY";
    }
   
    /**
    *   Getter S_RETCODE , NOT NULL       * */
    public static String  columnSretcode()
    {
        return "S_RETCODE";
    }
   
    /**
    *   Getter S_USERCODE , NOT NULL       * */
    public static String  columnSusercode()
    {
        return "S_USERCODE";
    }
   
    /**
    *   Getter I_MODICOUNT , NOT NULL       * */
    public static String  columnImodicount()
    {
        return "I_MODICOUNT";
    }
   
    /**
    *   Getter S_DEMO       * */
    public static String  columnSdemo()
    {
        return "S_DEMO";
    }
   
    /**
    *   Getter S_CHKSTATE       * */
    public static String  columnSchkstate()
    {
        return "S_CHKSTATE";
    }
   
    /**
    *   Getter S_MSGID       * */
    public static String  columnSmsgid()
    {
        return "S_MSGID";
    }
   
    /**
    *   Getter T_SENDTIME       * */
    public static String  columnTsendtime()
    {
        return "T_SENDTIME";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_FILEPACKAGEREF";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[17];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_TRECODE";
        columnNames[2]="S_FILENAME";
        columnNames[3]="S_TAXORGCODE";
        columnNames[4]="S_COMMITDATE";
        columnNames[5]="S_ACCDATE";
        columnNames[6]="S_PACKAGENO";
        columnNames[7]="S_OPERATIONTYPECODE";
        columnNames[8]="I_COUNT";
        columnNames[9]="N_MONEY";
        columnNames[10]="S_RETCODE";
        columnNames[11]="S_USERCODE";
        columnNames[12]="I_MODICOUNT";
        columnNames[13]="S_DEMO";
        columnNames[14]="S_CHKSTATE";
        columnNames[15]="S_MSGID";
        columnNames[16]="T_SENDTIME";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvFilepackagerefDto))
            return false;

        TvFilepackagerefDto bean = (TvFilepackagerefDto) obj;


      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field strecode
      if((this.strecode==null && bean.strecode!=null) || (this.strecode!=null && bean.strecode==null))
          return false;
        else if(this.strecode==null && bean.strecode==null){
        }
        else{
          if(!bean.strecode.equals(this.strecode))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field staxorgcode
      if((this.staxorgcode==null && bean.staxorgcode!=null) || (this.staxorgcode!=null && bean.staxorgcode==null))
          return false;
        else if(this.staxorgcode==null && bean.staxorgcode==null){
        }
        else{
          if(!bean.staxorgcode.equals(this.staxorgcode))
               return false;
     }
      //compare field scommitdate
      if((this.scommitdate==null && bean.scommitdate!=null) || (this.scommitdate!=null && bean.scommitdate==null))
          return false;
        else if(this.scommitdate==null && bean.scommitdate==null){
        }
        else{
          if(!bean.scommitdate.equals(this.scommitdate))
               return false;
     }
      //compare field saccdate
      if((this.saccdate==null && bean.saccdate!=null) || (this.saccdate!=null && bean.saccdate==null))
          return false;
        else if(this.saccdate==null && bean.saccdate==null){
        }
        else{
          if(!bean.saccdate.equals(this.saccdate))
               return false;
     }
      //compare field spackageno
      if((this.spackageno==null && bean.spackageno!=null) || (this.spackageno!=null && bean.spackageno==null))
          return false;
        else if(this.spackageno==null && bean.spackageno==null){
        }
        else{
          if(!bean.spackageno.equals(this.spackageno))
               return false;
     }
      //compare field soperationtypecode
      if((this.soperationtypecode==null && bean.soperationtypecode!=null) || (this.soperationtypecode!=null && bean.soperationtypecode==null))
          return false;
        else if(this.soperationtypecode==null && bean.soperationtypecode==null){
        }
        else{
          if(!bean.soperationtypecode.equals(this.soperationtypecode))
               return false;
     }
      //compare field icount
      if((this.icount==null && bean.icount!=null) || (this.icount!=null && bean.icount==null))
          return false;
        else if(this.icount==null && bean.icount==null){
        }
        else{
          if(!bean.icount.equals(this.icount))
               return false;
     }
      //compare field nmoney
      if((this.nmoney==null && bean.nmoney!=null) || (this.nmoney!=null && bean.nmoney==null))
          return false;
        else if(this.nmoney==null && bean.nmoney==null){
        }
        else{
          if(!bean.nmoney.equals(this.nmoney))
               return false;
     }
      //compare field sretcode
      if((this.sretcode==null && bean.sretcode!=null) || (this.sretcode!=null && bean.sretcode==null))
          return false;
        else if(this.sretcode==null && bean.sretcode==null){
        }
        else{
          if(!bean.sretcode.equals(this.sretcode))
               return false;
     }
      //compare field susercode
      if((this.susercode==null && bean.susercode!=null) || (this.susercode!=null && bean.susercode==null))
          return false;
        else if(this.susercode==null && bean.susercode==null){
        }
        else{
          if(!bean.susercode.equals(this.susercode))
               return false;
     }
      //compare field imodicount
      if((this.imodicount==null && bean.imodicount!=null) || (this.imodicount!=null && bean.imodicount==null))
          return false;
        else if(this.imodicount==null && bean.imodicount==null){
        }
        else{
          if(!bean.imodicount.equals(this.imodicount))
               return false;
     }
      //compare field sdemo
      if((this.sdemo==null && bean.sdemo!=null) || (this.sdemo!=null && bean.sdemo==null))
          return false;
        else if(this.sdemo==null && bean.sdemo==null){
        }
        else{
          if(!bean.sdemo.equals(this.sdemo))
               return false;
     }
      //compare field schkstate
      if((this.schkstate==null && bean.schkstate!=null) || (this.schkstate!=null && bean.schkstate==null))
          return false;
        else if(this.schkstate==null && bean.schkstate==null){
        }
        else{
          if(!bean.schkstate.equals(this.schkstate))
               return false;
     }
      //compare field smsgid
      if((this.smsgid==null && bean.smsgid!=null) || (this.smsgid!=null && bean.smsgid==null))
          return false;
        else if(this.smsgid==null && bean.smsgid==null){
        }
        else{
          if(!bean.smsgid.equals(this.smsgid))
               return false;
     }
      //compare field tsendtime
      if((this.tsendtime==null && bean.tsendtime!=null) || (this.tsendtime!=null && bean.tsendtime==null))
          return false;
        else if(this.tsendtime==null && bean.tsendtime==null){
        }
        else{
          if(!bean.tsendtime.equals(this.tsendtime))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.strecode!=null)
          _hash_ = _hash_ * 31+ this.strecode.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.staxorgcode!=null)
          _hash_ = _hash_ * 31+ this.staxorgcode.hashCode() ;
        if(this.scommitdate!=null)
          _hash_ = _hash_ * 31+ this.scommitdate.hashCode() ;
        if(this.saccdate!=null)
          _hash_ = _hash_ * 31+ this.saccdate.hashCode() ;
        if(this.spackageno!=null)
          _hash_ = _hash_ * 31+ this.spackageno.hashCode() ;
        if(this.soperationtypecode!=null)
          _hash_ = _hash_ * 31+ this.soperationtypecode.hashCode() ;
        if(this.icount!=null)
          _hash_ = _hash_ * 31+ this.icount.hashCode() ;
        if(this.nmoney!=null)
          _hash_ = _hash_ * 31+ this.nmoney.hashCode() ;
        if(this.sretcode!=null)
          _hash_ = _hash_ * 31+ this.sretcode.hashCode() ;
        if(this.susercode!=null)
          _hash_ = _hash_ * 31+ this.susercode.hashCode() ;
        if(this.imodicount!=null)
          _hash_ = _hash_ * 31+ this.imodicount.hashCode() ;
        if(this.sdemo!=null)
          _hash_ = _hash_ * 31+ this.sdemo.hashCode() ;
        if(this.schkstate!=null)
          _hash_ = _hash_ * 31+ this.schkstate.hashCode() ;
        if(this.smsgid!=null)
          _hash_ = _hash_ * 31+ this.smsgid.hashCode() ;
        if(this.tsendtime!=null)
          _hash_ = _hash_ * 31+ this.tsendtime.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvFilepackagerefDto bean = new TvFilepackagerefDto();

          bean.sorgcode = this.sorgcode;

          bean.strecode = this.strecode;

          bean.sfilename = this.sfilename;

          if (this.staxorgcode != null)
            bean.staxorgcode = new String(this.staxorgcode);
          if (this.scommitdate != null)
            bean.scommitdate = new String(this.scommitdate);
          if (this.saccdate != null)
            bean.saccdate = new String(this.saccdate);
          bean.spackageno = this.spackageno;

          if (this.soperationtypecode != null)
            bean.soperationtypecode = new String(this.soperationtypecode);
          if (this.icount != null)
            bean.icount = new Integer(this.icount.toString());
          if (this.nmoney != null)
            bean.nmoney = new BigDecimal(this.nmoney.toString());
          if (this.sretcode != null)
            bean.sretcode = new String(this.sretcode);
          if (this.susercode != null)
            bean.susercode = new String(this.susercode);
          if (this.imodicount != null)
            bean.imodicount = new Integer(this.imodicount.toString());
          if (this.sdemo != null)
            bean.sdemo = new String(this.sdemo);
          if (this.schkstate != null)
            bean.schkstate = new String(this.schkstate);
          if (this.smsgid != null)
            bean.smsgid = new String(this.smsgid);
          if (this.tsendtime != null)
            bean.tsendtime = (Timestamp) this.tsendtime.clone();
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvFilepackagerefDto").append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[strecode]").append(" = ").append(strecode).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[staxorgcode]").append(" = ").append(staxorgcode).append(sep);
        sb.append("[scommitdate]").append(" = ").append(scommitdate).append(sep);
        sb.append("[saccdate]").append(" = ").append(saccdate).append(sep);
        sb.append("[spackageno]").append(" = ").append(spackageno).append(sep);
        sb.append("[soperationtypecode]").append(" = ").append(soperationtypecode).append(sep);
        sb.append("[icount]").append(" = ").append(icount).append(sep);
        sb.append("[nmoney]").append(" = ").append(nmoney).append(sep);
        sb.append("[sretcode]").append(" = ").append(sretcode).append(sep);
        sb.append("[susercode]").append(" = ").append(susercode).append(sep);
        sb.append("[imodicount]").append(" = ").append(imodicount).append(sep);
        sb.append("[sdemo]").append(" = ").append(sdemo).append(sep);
        sb.append("[schkstate]").append(" = ").append(schkstate).append(sep);
        sb.append("[smsgid]").append(" = ").append(smsgid).append(sep);
        sb.append("[tsendtime]").append(" = ").append(tsendtime).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_TRECODE
      if (this.getStrecode()==null)
             sb.append("S_TRECODE不能为空; ");
      if (this.getStrecode()!=null)
             if (this.getStrecode().getBytes().length > 10)
                sb.append("S_TRECODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()==null)
             sb.append("S_FILENAME不能为空; ");
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_TAXORGCODE
      if (this.getStaxorgcode()==null)
             sb.append("S_TAXORGCODE不能为空; ");
      if (this.getStaxorgcode()!=null)
             if (this.getStaxorgcode().getBytes().length > 30)
                sb.append("S_TAXORGCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_COMMITDATE
      if (this.getScommitdate()==null)
             sb.append("S_COMMITDATE不能为空; ");
      if (this.getScommitdate()!=null)
             if (this.getScommitdate().getBytes().length > 8)
                sb.append("S_COMMITDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_ACCDATE
      if (this.getSaccdate()==null)
             sb.append("S_ACCDATE不能为空; ");
      if (this.getSaccdate()!=null)
             if (this.getSaccdate().getBytes().length > 8)
                sb.append("S_ACCDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_PACKAGENO
      if (this.getSpackageno()==null)
             sb.append("S_PACKAGENO不能为空; ");
      if (this.getSpackageno()!=null)
             if (this.getSpackageno().getBytes().length > 8)
                sb.append("S_PACKAGENO宽度不能超过 "+8+"个字符; ");
    
    //check field S_OPERATIONTYPECODE
      if (this.getSoperationtypecode()==null)
             sb.append("S_OPERATIONTYPECODE不能为空; ");
      if (this.getSoperationtypecode()!=null)
             if (this.getSoperationtypecode().getBytes().length > 10)
                sb.append("S_OPERATIONTYPECODE宽度不能超过 "+10+"个字符; ");
    
    //check field I_COUNT
      if (this.getIcount()==null)
             sb.append("I_COUNT不能为空; ");
      
    //check field N_MONEY
      if (this.getNmoney()==null)
             sb.append("N_MONEY不能为空; ");
      
    //check field S_RETCODE
      if (this.getSretcode()==null)
             sb.append("S_RETCODE不能为空; ");
      if (this.getSretcode()!=null)
             if (this.getSretcode().getBytes().length > 5)
                sb.append("S_RETCODE宽度不能超过 "+5+"个字符; ");
    
    //check field S_USERCODE
      if (this.getSusercode()==null)
             sb.append("S_USERCODE不能为空; ");
      if (this.getSusercode()!=null)
             if (this.getSusercode().getBytes().length > 30)
                sb.append("S_USERCODE宽度不能超过 "+30+"个字符; ");
    
    //check field I_MODICOUNT
      if (this.getImodicount()==null)
             sb.append("I_MODICOUNT不能为空; ");
      
    //check field S_DEMO
      if (this.getSdemo()!=null)
             if (this.getSdemo().getBytes().length > 100)
                sb.append("S_DEMO宽度不能超过 "+100+"个字符; ");
    
    //check field S_CHKSTATE
      if (this.getSchkstate()!=null)
             if (this.getSchkstate().getBytes().length > 1)
                sb.append("S_CHKSTATE宽度不能超过 "+1+"个字符; ");
    
    //check field S_MSGID
      if (this.getSmsgid()!=null)
             if (this.getSmsgid().getBytes().length > 20)
                sb.append("S_MSGID宽度不能超过 "+20+"个字符; ");
    
    //check field T_SENDTIME
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_TRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRECODE")) {
               if (this.getStrecode()==null)
                    sb.append("S_TRECODE 不能为空; ");
               if (this.getStrecode()!=null)
                    if (this.getStrecode().getBytes().length > 10)
                        sb.append("S_TRECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
               if (this.getSfilename()==null)
                    sb.append("S_FILENAME 不能为空; ");
               if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_TAXORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXORGCODE")) {
               if (this.getStaxorgcode()==null)
                    sb.append("S_TAXORGCODE 不能为空; ");
               if (this.getStaxorgcode()!=null)
                    if (this.getStaxorgcode().getBytes().length > 30)
                        sb.append("S_TAXORGCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_COMMITDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_COMMITDATE")) {
               if (this.getScommitdate()==null)
                    sb.append("S_COMMITDATE 不能为空; ");
               if (this.getScommitdate()!=null)
                    if (this.getScommitdate().getBytes().length > 8)
                        sb.append("S_COMMITDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_ACCDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ACCDATE")) {
               if (this.getSaccdate()==null)
                    sb.append("S_ACCDATE 不能为空; ");
               if (this.getSaccdate()!=null)
                    if (this.getSaccdate().getBytes().length > 8)
                        sb.append("S_ACCDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_PACKAGENO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PACKAGENO")) {
               if (this.getSpackageno()==null)
                    sb.append("S_PACKAGENO 不能为空; ");
               if (this.getSpackageno()!=null)
                    if (this.getSpackageno().getBytes().length > 8)
                        sb.append("S_PACKAGENO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_OPERATIONTYPECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OPERATIONTYPECODE")) {
               if (this.getSoperationtypecode()==null)
                    sb.append("S_OPERATIONTYPECODE 不能为空; ");
               if (this.getSoperationtypecode()!=null)
                    if (this.getSoperationtypecode().getBytes().length > 10)
                        sb.append("S_OPERATIONTYPECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field I_COUNT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("I_COUNT")) {
               if (this.getIcount()==null)
                    sb.append("I_COUNT 不能为空; ");
               break;
         }
  }
    
    //check field N_MONEY
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_MONEY")) {
               if (this.getNmoney()==null)
                    sb.append("N_MONEY 不能为空; ");
               break;
         }
  }
    
    //check field S_RETCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RETCODE")) {
               if (this.getSretcode()==null)
                    sb.append("S_RETCODE 不能为空; ");
               if (this.getSretcode()!=null)
                    if (this.getSretcode().getBytes().length > 5)
                        sb.append("S_RETCODE 宽度不能超过 "+5+"个字符");
             break;
         }
  }
    
    //check field S_USERCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_USERCODE")) {
               if (this.getSusercode()==null)
                    sb.append("S_USERCODE 不能为空; ");
               if (this.getSusercode()!=null)
                    if (this.getSusercode().getBytes().length > 30)
                        sb.append("S_USERCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field I_MODICOUNT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("I_MODICOUNT")) {
               if (this.getImodicount()==null)
                    sb.append("I_MODICOUNT 不能为空; ");
               break;
         }
  }
    
    //check field S_DEMO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEMO")) {
                 if (this.getSdemo()!=null)
                    if (this.getSdemo().getBytes().length > 100)
                        sb.append("S_DEMO 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_CHKSTATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CHKSTATE")) {
                 if (this.getSchkstate()!=null)
                    if (this.getSchkstate().getBytes().length > 1)
                        sb.append("S_CHKSTATE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_MSGID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_MSGID")) {
                 if (this.getSmsgid()!=null)
                    if (this.getSmsgid().getBytes().length > 20)
                        sb.append("S_MSGID 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field T_SENDTIME
          
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TvFilepackagerefPK pk = new TvFilepackagerefPK();
      pk.setSorgcode(getSorgcode());
      pk.setStrecode(getStrecode());
      pk.setSfilename(getSfilename());
      pk.setSpackageno(getSpackageno());
      return pk;
    };
}
