    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvGrantpayfilemainTmpPK;
/**
 * <p>Title: DTO of table: TV_GRANTPAYFILEMAIN_TMP</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvGrantpayfilemainTmpDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_LIMITID VARCHAR   , NOT NULL       */
    protected String slimitid;
    /**
    *  S_OFYEAR CHARACTER   , NOT NULL       */
    protected String sofyear;
    /**
    *  S_GENTICKETDATE CHARACTER   , NOT NULL       */
    protected String sgenticketdate;
    /**
    *  S_OFMONTH CHARACTER   , NOT NULL       */
    protected String sofmonth;
    /**
    *  N_MONEY DECIMAL   , NOT NULL       */
    protected BigDecimal nmoney;
    /**
    *  S_RECBANKNAME VARCHAR         */
    protected String srecbankname;
    /**
    *  S_FILENAME VARCHAR         */
    protected String sfilename;
    /**
    *  S_ORGCODE VARCHAR   , NOT NULL       */
    protected String sorgcode;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSlimitid()
    {
        return slimitid;
    }
     /**
     *   Setter S_LIMITID , NOT NULL        * */
    public void setSlimitid(String _slimitid) {
        this.slimitid = _slimitid;
    }


    public String getSofyear()
    {
        return sofyear;
    }
     /**
     *   Setter S_OFYEAR , NOT NULL        * */
    public void setSofyear(String _sofyear) {
        this.sofyear = _sofyear;
    }


    public String getSgenticketdate()
    {
        return sgenticketdate;
    }
     /**
     *   Setter S_GENTICKETDATE , NOT NULL        * */
    public void setSgenticketdate(String _sgenticketdate) {
        this.sgenticketdate = _sgenticketdate;
    }


    public String getSofmonth()
    {
        return sofmonth;
    }
     /**
     *   Setter S_OFMONTH , NOT NULL        * */
    public void setSofmonth(String _sofmonth) {
        this.sofmonth = _sofmonth;
    }


    public BigDecimal getNmoney()
    {
        return nmoney;
    }
     /**
     *   Setter N_MONEY , NOT NULL        * */
    public void setNmoney(BigDecimal _nmoney) {
        this.nmoney = _nmoney;
    }


    public String getSrecbankname()
    {
        return srecbankname;
    }
     /**
     *   Setter S_RECBANKNAME        * */
    public void setSrecbankname(String _srecbankname) {
        this.srecbankname = _srecbankname;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_LIMITID , NOT NULL       * */
    public static String  columnSlimitid()
    {
        return "S_LIMITID";
    }
   
    /**
    *   Getter S_OFYEAR , NOT NULL       * */
    public static String  columnSofyear()
    {
        return "S_OFYEAR";
    }
   
    /**
    *   Getter S_GENTICKETDATE , NOT NULL       * */
    public static String  columnSgenticketdate()
    {
        return "S_GENTICKETDATE";
    }
   
    /**
    *   Getter S_OFMONTH , NOT NULL       * */
    public static String  columnSofmonth()
    {
        return "S_OFMONTH";
    }
   
    /**
    *   Getter N_MONEY , NOT NULL       * */
    public static String  columnNmoney()
    {
        return "N_MONEY";
    }
   
    /**
    *   Getter S_RECBANKNAME       * */
    public static String  columnSrecbankname()
    {
        return "S_RECBANKNAME";
    }
   
    /**
    *   Getter S_FILENAME       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_ORGCODE , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_GRANTPAYFILEMAIN_TMP";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[8];        
        columnNames[0]="S_LIMITID";
        columnNames[1]="S_OFYEAR";
        columnNames[2]="S_GENTICKETDATE";
        columnNames[3]="S_OFMONTH";
        columnNames[4]="N_MONEY";
        columnNames[5]="S_RECBANKNAME";
        columnNames[6]="S_FILENAME";
        columnNames[7]="S_ORGCODE";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvGrantpayfilemainTmpDto))
            return false;

        TvGrantpayfilemainTmpDto bean = (TvGrantpayfilemainTmpDto) obj;


      //compare field slimitid
      if((this.slimitid==null && bean.slimitid!=null) || (this.slimitid!=null && bean.slimitid==null))
          return false;
        else if(this.slimitid==null && bean.slimitid==null){
        }
        else{
          if(!bean.slimitid.equals(this.slimitid))
               return false;
     }
      //compare field sofyear
      if((this.sofyear==null && bean.sofyear!=null) || (this.sofyear!=null && bean.sofyear==null))
          return false;
        else if(this.sofyear==null && bean.sofyear==null){
        }
        else{
          if(!bean.sofyear.equals(this.sofyear))
               return false;
     }
      //compare field sgenticketdate
      if((this.sgenticketdate==null && bean.sgenticketdate!=null) || (this.sgenticketdate!=null && bean.sgenticketdate==null))
          return false;
        else if(this.sgenticketdate==null && bean.sgenticketdate==null){
        }
        else{
          if(!bean.sgenticketdate.equals(this.sgenticketdate))
               return false;
     }
      //compare field sofmonth
      if((this.sofmonth==null && bean.sofmonth!=null) || (this.sofmonth!=null && bean.sofmonth==null))
          return false;
        else if(this.sofmonth==null && bean.sofmonth==null){
        }
        else{
          if(!bean.sofmonth.equals(this.sofmonth))
               return false;
     }
      //compare field nmoney
      if((this.nmoney==null && bean.nmoney!=null) || (this.nmoney!=null && bean.nmoney==null))
          return false;
        else if(this.nmoney==null && bean.nmoney==null){
        }
        else{
          if(!bean.nmoney.equals(this.nmoney))
               return false;
     }
      //compare field srecbankname
      if((this.srecbankname==null && bean.srecbankname!=null) || (this.srecbankname!=null && bean.srecbankname==null))
          return false;
        else if(this.srecbankname==null && bean.srecbankname==null){
        }
        else{
          if(!bean.srecbankname.equals(this.srecbankname))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.slimitid!=null)
          _hash_ = _hash_ * 31+ this.slimitid.hashCode() ;
        if(this.sofyear!=null)
          _hash_ = _hash_ * 31+ this.sofyear.hashCode() ;
        if(this.sgenticketdate!=null)
          _hash_ = _hash_ * 31+ this.sgenticketdate.hashCode() ;
        if(this.sofmonth!=null)
          _hash_ = _hash_ * 31+ this.sofmonth.hashCode() ;
        if(this.nmoney!=null)
          _hash_ = _hash_ * 31+ this.nmoney.hashCode() ;
        if(this.srecbankname!=null)
          _hash_ = _hash_ * 31+ this.srecbankname.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvGrantpayfilemainTmpDto bean = new TvGrantpayfilemainTmpDto();

          if (this.slimitid != null)
            bean.slimitid = new String(this.slimitid);
          if (this.sofyear != null)
            bean.sofyear = new String(this.sofyear);
          if (this.sgenticketdate != null)
            bean.sgenticketdate = new String(this.sgenticketdate);
          if (this.sofmonth != null)
            bean.sofmonth = new String(this.sofmonth);
          if (this.nmoney != null)
            bean.nmoney = new BigDecimal(this.nmoney.toString());
          if (this.srecbankname != null)
            bean.srecbankname = new String(this.srecbankname);
          if (this.sfilename != null)
            bean.sfilename = new String(this.sfilename);
          if (this.sorgcode != null)
            bean.sorgcode = new String(this.sorgcode);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvGrantpayfilemainTmpDto").append(sep);
        sb.append("[slimitid]").append(" = ").append(slimitid).append(sep);
        sb.append("[sofyear]").append(" = ").append(sofyear).append(sep);
        sb.append("[sgenticketdate]").append(" = ").append(sgenticketdate).append(sep);
        sb.append("[sofmonth]").append(" = ").append(sofmonth).append(sep);
        sb.append("[nmoney]").append(" = ").append(nmoney).append(sep);
        sb.append("[srecbankname]").append(" = ").append(srecbankname).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_LIMITID
      if (this.getSlimitid()==null)
             sb.append("S_LIMITID不能为空; ");
      if (this.getSlimitid()!=null)
             if (this.getSlimitid().getBytes().length > 8)
                sb.append("S_LIMITID宽度不能超过 "+8+"个字符; ");
    
    //check field S_OFYEAR
      if (this.getSofyear()==null)
             sb.append("S_OFYEAR不能为空; ");
      if (this.getSofyear()!=null)
             if (this.getSofyear().getBytes().length > 4)
                sb.append("S_OFYEAR宽度不能超过 "+4+"个字符; ");
    
    //check field S_GENTICKETDATE
      if (this.getSgenticketdate()==null)
             sb.append("S_GENTICKETDATE不能为空; ");
      if (this.getSgenticketdate()!=null)
             if (this.getSgenticketdate().getBytes().length > 8)
                sb.append("S_GENTICKETDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_OFMONTH
      if (this.getSofmonth()==null)
             sb.append("S_OFMONTH不能为空; ");
      if (this.getSofmonth()!=null)
             if (this.getSofmonth().getBytes().length > 2)
                sb.append("S_OFMONTH宽度不能超过 "+2+"个字符; ");
    
    //check field N_MONEY
      if (this.getNmoney()==null)
             sb.append("N_MONEY不能为空; ");
      
    //check field S_RECBANKNAME
      if (this.getSrecbankname()!=null)
             if (this.getSrecbankname().getBytes().length > 120)
                sb.append("S_RECBANKNAME宽度不能超过 "+120+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_LIMITID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_LIMITID")) {
               if (this.getSlimitid()==null)
                    sb.append("S_LIMITID 不能为空; ");
               if (this.getSlimitid()!=null)
                    if (this.getSlimitid().getBytes().length > 8)
                        sb.append("S_LIMITID 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_OFYEAR
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OFYEAR")) {
               if (this.getSofyear()==null)
                    sb.append("S_OFYEAR 不能为空; ");
               if (this.getSofyear()!=null)
                    if (this.getSofyear().getBytes().length > 4)
                        sb.append("S_OFYEAR 宽度不能超过 "+4+"个字符");
             break;
         }
  }
    
    //check field S_GENTICKETDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_GENTICKETDATE")) {
               if (this.getSgenticketdate()==null)
                    sb.append("S_GENTICKETDATE 不能为空; ");
               if (this.getSgenticketdate()!=null)
                    if (this.getSgenticketdate().getBytes().length > 8)
                        sb.append("S_GENTICKETDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_OFMONTH
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OFMONTH")) {
               if (this.getSofmonth()==null)
                    sb.append("S_OFMONTH 不能为空; ");
               if (this.getSofmonth()!=null)
                    if (this.getSofmonth().getBytes().length > 2)
                        sb.append("S_OFMONTH 宽度不能超过 "+2+"个字符");
             break;
         }
  }
    
    //check field N_MONEY
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_MONEY")) {
               if (this.getNmoney()==null)
                    sb.append("N_MONEY 不能为空; ");
               break;
         }
  }
    
    //check field S_RECBANKNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RECBANKNAME")) {
                 if (this.getSrecbankname()!=null)
                    if (this.getSrecbankname().getBytes().length > 120)
                        sb.append("S_RECBANKNAME 宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
                 if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      throw new RuntimeException("此dto没有PK，不能进行此操作");
    };
}
