    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvInfileTmpCountryPK;
/**
 * <p>Title: DTO of table: TV_INFILE_TMP_COUNTRY</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvInfileTmpCountryDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_TAXTICKETNO VARCHAR   , NOT NULL       */
    protected String staxticketno;
    /**
    *  S_CORPTYPENAME VARCHAR         */
    protected String scorptypename;
    /**
    *  S_BILLDATE CHARACTER         */
    protected String sbilldate;
    /**
    *  S_TAXORGCODE VARCHAR         */
    protected String staxorgcode;
    /**
    *  S_CORPCODE VARCHAR         */
    protected String scorpcode;
    /**
    *  S_CORPNAME VARCHAR         */
    protected String scorpname;
    /**
    *  S_PAYBNKNO VARCHAR         */
    protected String spaybnkno;
    /**
    *  S_PAYACCT VARCHAR         */
    protected String spayacct;
    /**
    *  S_BUDGETSUBCODE VARCHAR         */
    protected String sbudgetsubcode;
    /**
    *  S_BUDGETLEVELCODE CHARACTER         */
    protected String sbudgetlevelcode;
    /**
    *  S_PAYEETRECODE VARCHAR         */
    protected String spayeetrecode;
    /**
    *  S_TAXSTARTDATE CHARACTER         */
    protected String staxstartdate;
    /**
    *  S_TAXENDDATE CHARACTER         */
    protected String staxenddate;
    /**
    *  S_LIMITDATE CHARACTER         */
    protected String slimitdate;
    /**
    *  S_TAXTYPENAME VARCHAR         */
    protected String staxtypename;
    /**
    *  N_FACTTAXAMT DECIMAL         */
    protected BigDecimal nfacttaxamt;
    /**
    *  S_ORGCODE VARCHAR   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_FILENAME VARCHAR   , NOT NULL       */
    protected String sfilename;
    /**
    *  S_OPENACCBANKCODE VARCHAR         */
    protected String sopenaccbankcode;
    /**
    *  S_TCBSTAXORGCODE VARCHAR         */
    protected String stcbstaxorgcode;
    /**
    *  S_TCBSTRECODE VARCHAR         */
    protected String stcbstrecode;
    /**
    *  S_ASSITSIGN VARCHAR         */
    protected String sassitsign;
    /**
    *  S_CORPTYPE VARCHAR         */
    protected String scorptype;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getStaxticketno()
    {
        return staxticketno;
    }
     /**
     *   Setter S_TAXTICKETNO , NOT NULL        * */
    public void setStaxticketno(String _staxticketno) {
        this.staxticketno = _staxticketno;
    }


    public String getScorptypename()
    {
        return scorptypename;
    }
     /**
     *   Setter S_CORPTYPENAME        * */
    public void setScorptypename(String _scorptypename) {
        this.scorptypename = _scorptypename;
    }


    public String getSbilldate()
    {
        return sbilldate;
    }
     /**
     *   Setter S_BILLDATE        * */
    public void setSbilldate(String _sbilldate) {
        this.sbilldate = _sbilldate;
    }


    public String getStaxorgcode()
    {
        return staxorgcode;
    }
     /**
     *   Setter S_TAXORGCODE        * */
    public void setStaxorgcode(String _staxorgcode) {
        this.staxorgcode = _staxorgcode;
    }


    public String getScorpcode()
    {
        return scorpcode;
    }
     /**
     *   Setter S_CORPCODE        * */
    public void setScorpcode(String _scorpcode) {
        this.scorpcode = _scorpcode;
    }


    public String getScorpname()
    {
        return scorpname;
    }
     /**
     *   Setter S_CORPNAME        * */
    public void setScorpname(String _scorpname) {
        this.scorpname = _scorpname;
    }


    public String getSpaybnkno()
    {
        return spaybnkno;
    }
     /**
     *   Setter S_PAYBNKNO        * */
    public void setSpaybnkno(String _spaybnkno) {
        this.spaybnkno = _spaybnkno;
    }


    public String getSpayacct()
    {
        return spayacct;
    }
     /**
     *   Setter S_PAYACCT        * */
    public void setSpayacct(String _spayacct) {
        this.spayacct = _spayacct;
    }


    public String getSbudgetsubcode()
    {
        return sbudgetsubcode;
    }
     /**
     *   Setter S_BUDGETSUBCODE        * */
    public void setSbudgetsubcode(String _sbudgetsubcode) {
        this.sbudgetsubcode = _sbudgetsubcode;
    }


    public String getSbudgetlevelcode()
    {
        return sbudgetlevelcode;
    }
     /**
     *   Setter S_BUDGETLEVELCODE        * */
    public void setSbudgetlevelcode(String _sbudgetlevelcode) {
        this.sbudgetlevelcode = _sbudgetlevelcode;
    }


    public String getSpayeetrecode()
    {
        return spayeetrecode;
    }
     /**
     *   Setter S_PAYEETRECODE        * */
    public void setSpayeetrecode(String _spayeetrecode) {
        this.spayeetrecode = _spayeetrecode;
    }


    public String getStaxstartdate()
    {
        return staxstartdate;
    }
     /**
     *   Setter S_TAXSTARTDATE        * */
    public void setStaxstartdate(String _staxstartdate) {
        this.staxstartdate = _staxstartdate;
    }


    public String getStaxenddate()
    {
        return staxenddate;
    }
     /**
     *   Setter S_TAXENDDATE        * */
    public void setStaxenddate(String _staxenddate) {
        this.staxenddate = _staxenddate;
    }


    public String getSlimitdate()
    {
        return slimitdate;
    }
     /**
     *   Setter S_LIMITDATE        * */
    public void setSlimitdate(String _slimitdate) {
        this.slimitdate = _slimitdate;
    }


    public String getStaxtypename()
    {
        return staxtypename;
    }
     /**
     *   Setter S_TAXTYPENAME        * */
    public void setStaxtypename(String _staxtypename) {
        this.staxtypename = _staxtypename;
    }


    public BigDecimal getNfacttaxamt()
    {
        return nfacttaxamt;
    }
     /**
     *   Setter N_FACTTAXAMT        * */
    public void setNfacttaxamt(BigDecimal _nfacttaxamt) {
        this.nfacttaxamt = _nfacttaxamt;
    }


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME , NOT NULL        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getSopenaccbankcode()
    {
        return sopenaccbankcode;
    }
     /**
     *   Setter S_OPENACCBANKCODE        * */
    public void setSopenaccbankcode(String _sopenaccbankcode) {
        this.sopenaccbankcode = _sopenaccbankcode;
    }


    public String getStcbstaxorgcode()
    {
        return stcbstaxorgcode;
    }
     /**
     *   Setter S_TCBSTAXORGCODE        * */
    public void setStcbstaxorgcode(String _stcbstaxorgcode) {
        this.stcbstaxorgcode = _stcbstaxorgcode;
    }


    public String getStcbstrecode()
    {
        return stcbstrecode;
    }
     /**
     *   Setter S_TCBSTRECODE        * */
    public void setStcbstrecode(String _stcbstrecode) {
        this.stcbstrecode = _stcbstrecode;
    }


    public String getSassitsign()
    {
        return sassitsign;
    }
     /**
     *   Setter S_ASSITSIGN        * */
    public void setSassitsign(String _sassitsign) {
        this.sassitsign = _sassitsign;
    }


    public String getScorptype()
    {
        return scorptype;
    }
     /**
     *   Setter S_CORPTYPE        * */
    public void setScorptype(String _scorptype) {
        this.scorptype = _scorptype;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_TAXTICKETNO , NOT NULL       * */
    public static String  columnStaxticketno()
    {
        return "S_TAXTICKETNO";
    }
   
    /**
    *   Getter S_CORPTYPENAME       * */
    public static String  columnScorptypename()
    {
        return "S_CORPTYPENAME";
    }
   
    /**
    *   Getter S_BILLDATE       * */
    public static String  columnSbilldate()
    {
        return "S_BILLDATE";
    }
   
    /**
    *   Getter S_TAXORGCODE       * */
    public static String  columnStaxorgcode()
    {
        return "S_TAXORGCODE";
    }
   
    /**
    *   Getter S_CORPCODE       * */
    public static String  columnScorpcode()
    {
        return "S_CORPCODE";
    }
   
    /**
    *   Getter S_CORPNAME       * */
    public static String  columnScorpname()
    {
        return "S_CORPNAME";
    }
   
    /**
    *   Getter S_PAYBNKNO       * */
    public static String  columnSpaybnkno()
    {
        return "S_PAYBNKNO";
    }
   
    /**
    *   Getter S_PAYACCT       * */
    public static String  columnSpayacct()
    {
        return "S_PAYACCT";
    }
   
    /**
    *   Getter S_BUDGETSUBCODE       * */
    public static String  columnSbudgetsubcode()
    {
        return "S_BUDGETSUBCODE";
    }
   
    /**
    *   Getter S_BUDGETLEVELCODE       * */
    public static String  columnSbudgetlevelcode()
    {
        return "S_BUDGETLEVELCODE";
    }
   
    /**
    *   Getter S_PAYEETRECODE       * */
    public static String  columnSpayeetrecode()
    {
        return "S_PAYEETRECODE";
    }
   
    /**
    *   Getter S_TAXSTARTDATE       * */
    public static String  columnStaxstartdate()
    {
        return "S_TAXSTARTDATE";
    }
   
    /**
    *   Getter S_TAXENDDATE       * */
    public static String  columnStaxenddate()
    {
        return "S_TAXENDDATE";
    }
   
    /**
    *   Getter S_LIMITDATE       * */
    public static String  columnSlimitdate()
    {
        return "S_LIMITDATE";
    }
   
    /**
    *   Getter S_TAXTYPENAME       * */
    public static String  columnStaxtypename()
    {
        return "S_TAXTYPENAME";
    }
   
    /**
    *   Getter N_FACTTAXAMT       * */
    public static String  columnNfacttaxamt()
    {
        return "N_FACTTAXAMT";
    }
   
    /**
    *   Getter S_ORGCODE , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_FILENAME , NOT NULL       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_OPENACCBANKCODE       * */
    public static String  columnSopenaccbankcode()
    {
        return "S_OPENACCBANKCODE";
    }
   
    /**
    *   Getter S_TCBSTAXORGCODE       * */
    public static String  columnStcbstaxorgcode()
    {
        return "S_TCBSTAXORGCODE";
    }
   
    /**
    *   Getter S_TCBSTRECODE       * */
    public static String  columnStcbstrecode()
    {
        return "S_TCBSTRECODE";
    }
   
    /**
    *   Getter S_ASSITSIGN       * */
    public static String  columnSassitsign()
    {
        return "S_ASSITSIGN";
    }
   
    /**
    *   Getter S_CORPTYPE       * */
    public static String  columnScorptype()
    {
        return "S_CORPTYPE";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_INFILE_TMP_COUNTRY";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[23];        
        columnNames[0]="S_TAXTICKETNO";
        columnNames[1]="S_CORPTYPENAME";
        columnNames[2]="S_BILLDATE";
        columnNames[3]="S_TAXORGCODE";
        columnNames[4]="S_CORPCODE";
        columnNames[5]="S_CORPNAME";
        columnNames[6]="S_PAYBNKNO";
        columnNames[7]="S_PAYACCT";
        columnNames[8]="S_BUDGETSUBCODE";
        columnNames[9]="S_BUDGETLEVELCODE";
        columnNames[10]="S_PAYEETRECODE";
        columnNames[11]="S_TAXSTARTDATE";
        columnNames[12]="S_TAXENDDATE";
        columnNames[13]="S_LIMITDATE";
        columnNames[14]="S_TAXTYPENAME";
        columnNames[15]="N_FACTTAXAMT";
        columnNames[16]="S_ORGCODE";
        columnNames[17]="S_FILENAME";
        columnNames[18]="S_OPENACCBANKCODE";
        columnNames[19]="S_TCBSTAXORGCODE";
        columnNames[20]="S_TCBSTRECODE";
        columnNames[21]="S_ASSITSIGN";
        columnNames[22]="S_CORPTYPE";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvInfileTmpCountryDto))
            return false;

        TvInfileTmpCountryDto bean = (TvInfileTmpCountryDto) obj;


      //compare field staxticketno
      if((this.staxticketno==null && bean.staxticketno!=null) || (this.staxticketno!=null && bean.staxticketno==null))
          return false;
        else if(this.staxticketno==null && bean.staxticketno==null){
        }
        else{
          if(!bean.staxticketno.equals(this.staxticketno))
               return false;
     }
      //compare field scorptypename
      if((this.scorptypename==null && bean.scorptypename!=null) || (this.scorptypename!=null && bean.scorptypename==null))
          return false;
        else if(this.scorptypename==null && bean.scorptypename==null){
        }
        else{
          if(!bean.scorptypename.equals(this.scorptypename))
               return false;
     }
      //compare field sbilldate
      if((this.sbilldate==null && bean.sbilldate!=null) || (this.sbilldate!=null && bean.sbilldate==null))
          return false;
        else if(this.sbilldate==null && bean.sbilldate==null){
        }
        else{
          if(!bean.sbilldate.equals(this.sbilldate))
               return false;
     }
      //compare field staxorgcode
      if((this.staxorgcode==null && bean.staxorgcode!=null) || (this.staxorgcode!=null && bean.staxorgcode==null))
          return false;
        else if(this.staxorgcode==null && bean.staxorgcode==null){
        }
        else{
          if(!bean.staxorgcode.equals(this.staxorgcode))
               return false;
     }
      //compare field scorpcode
      if((this.scorpcode==null && bean.scorpcode!=null) || (this.scorpcode!=null && bean.scorpcode==null))
          return false;
        else if(this.scorpcode==null && bean.scorpcode==null){
        }
        else{
          if(!bean.scorpcode.equals(this.scorpcode))
               return false;
     }
      //compare field scorpname
      if((this.scorpname==null && bean.scorpname!=null) || (this.scorpname!=null && bean.scorpname==null))
          return false;
        else if(this.scorpname==null && bean.scorpname==null){
        }
        else{
          if(!bean.scorpname.equals(this.scorpname))
               return false;
     }
      //compare field spaybnkno
      if((this.spaybnkno==null && bean.spaybnkno!=null) || (this.spaybnkno!=null && bean.spaybnkno==null))
          return false;
        else if(this.spaybnkno==null && bean.spaybnkno==null){
        }
        else{
          if(!bean.spaybnkno.equals(this.spaybnkno))
               return false;
     }
      //compare field spayacct
      if((this.spayacct==null && bean.spayacct!=null) || (this.spayacct!=null && bean.spayacct==null))
          return false;
        else if(this.spayacct==null && bean.spayacct==null){
        }
        else{
          if(!bean.spayacct.equals(this.spayacct))
               return false;
     }
      //compare field sbudgetsubcode
      if((this.sbudgetsubcode==null && bean.sbudgetsubcode!=null) || (this.sbudgetsubcode!=null && bean.sbudgetsubcode==null))
          return false;
        else if(this.sbudgetsubcode==null && bean.sbudgetsubcode==null){
        }
        else{
          if(!bean.sbudgetsubcode.equals(this.sbudgetsubcode))
               return false;
     }
      //compare field sbudgetlevelcode
      if((this.sbudgetlevelcode==null && bean.sbudgetlevelcode!=null) || (this.sbudgetlevelcode!=null && bean.sbudgetlevelcode==null))
          return false;
        else if(this.sbudgetlevelcode==null && bean.sbudgetlevelcode==null){
        }
        else{
          if(!bean.sbudgetlevelcode.equals(this.sbudgetlevelcode))
               return false;
     }
      //compare field spayeetrecode
      if((this.spayeetrecode==null && bean.spayeetrecode!=null) || (this.spayeetrecode!=null && bean.spayeetrecode==null))
          return false;
        else if(this.spayeetrecode==null && bean.spayeetrecode==null){
        }
        else{
          if(!bean.spayeetrecode.equals(this.spayeetrecode))
               return false;
     }
      //compare field staxstartdate
      if((this.staxstartdate==null && bean.staxstartdate!=null) || (this.staxstartdate!=null && bean.staxstartdate==null))
          return false;
        else if(this.staxstartdate==null && bean.staxstartdate==null){
        }
        else{
          if(!bean.staxstartdate.equals(this.staxstartdate))
               return false;
     }
      //compare field staxenddate
      if((this.staxenddate==null && bean.staxenddate!=null) || (this.staxenddate!=null && bean.staxenddate==null))
          return false;
        else if(this.staxenddate==null && bean.staxenddate==null){
        }
        else{
          if(!bean.staxenddate.equals(this.staxenddate))
               return false;
     }
      //compare field slimitdate
      if((this.slimitdate==null && bean.slimitdate!=null) || (this.slimitdate!=null && bean.slimitdate==null))
          return false;
        else if(this.slimitdate==null && bean.slimitdate==null){
        }
        else{
          if(!bean.slimitdate.equals(this.slimitdate))
               return false;
     }
      //compare field staxtypename
      if((this.staxtypename==null && bean.staxtypename!=null) || (this.staxtypename!=null && bean.staxtypename==null))
          return false;
        else if(this.staxtypename==null && bean.staxtypename==null){
        }
        else{
          if(!bean.staxtypename.equals(this.staxtypename))
               return false;
     }
      //compare field nfacttaxamt
      if((this.nfacttaxamt==null && bean.nfacttaxamt!=null) || (this.nfacttaxamt!=null && bean.nfacttaxamt==null))
          return false;
        else if(this.nfacttaxamt==null && bean.nfacttaxamt==null){
        }
        else{
          if(!bean.nfacttaxamt.equals(this.nfacttaxamt))
               return false;
     }
      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field sopenaccbankcode
      if((this.sopenaccbankcode==null && bean.sopenaccbankcode!=null) || (this.sopenaccbankcode!=null && bean.sopenaccbankcode==null))
          return false;
        else if(this.sopenaccbankcode==null && bean.sopenaccbankcode==null){
        }
        else{
          if(!bean.sopenaccbankcode.equals(this.sopenaccbankcode))
               return false;
     }
      //compare field stcbstaxorgcode
      if((this.stcbstaxorgcode==null && bean.stcbstaxorgcode!=null) || (this.stcbstaxorgcode!=null && bean.stcbstaxorgcode==null))
          return false;
        else if(this.stcbstaxorgcode==null && bean.stcbstaxorgcode==null){
        }
        else{
          if(!bean.stcbstaxorgcode.equals(this.stcbstaxorgcode))
               return false;
     }
      //compare field stcbstrecode
      if((this.stcbstrecode==null && bean.stcbstrecode!=null) || (this.stcbstrecode!=null && bean.stcbstrecode==null))
          return false;
        else if(this.stcbstrecode==null && bean.stcbstrecode==null){
        }
        else{
          if(!bean.stcbstrecode.equals(this.stcbstrecode))
               return false;
     }
      //compare field sassitsign
      if((this.sassitsign==null && bean.sassitsign!=null) || (this.sassitsign!=null && bean.sassitsign==null))
          return false;
        else if(this.sassitsign==null && bean.sassitsign==null){
        }
        else{
          if(!bean.sassitsign.equals(this.sassitsign))
               return false;
     }
      //compare field scorptype
      if((this.scorptype==null && bean.scorptype!=null) || (this.scorptype!=null && bean.scorptype==null))
          return false;
        else if(this.scorptype==null && bean.scorptype==null){
        }
        else{
          if(!bean.scorptype.equals(this.scorptype))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.staxticketno!=null)
          _hash_ = _hash_ * 31+ this.staxticketno.hashCode() ;
        if(this.scorptypename!=null)
          _hash_ = _hash_ * 31+ this.scorptypename.hashCode() ;
        if(this.sbilldate!=null)
          _hash_ = _hash_ * 31+ this.sbilldate.hashCode() ;
        if(this.staxorgcode!=null)
          _hash_ = _hash_ * 31+ this.staxorgcode.hashCode() ;
        if(this.scorpcode!=null)
          _hash_ = _hash_ * 31+ this.scorpcode.hashCode() ;
        if(this.scorpname!=null)
          _hash_ = _hash_ * 31+ this.scorpname.hashCode() ;
        if(this.spaybnkno!=null)
          _hash_ = _hash_ * 31+ this.spaybnkno.hashCode() ;
        if(this.spayacct!=null)
          _hash_ = _hash_ * 31+ this.spayacct.hashCode() ;
        if(this.sbudgetsubcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetsubcode.hashCode() ;
        if(this.sbudgetlevelcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetlevelcode.hashCode() ;
        if(this.spayeetrecode!=null)
          _hash_ = _hash_ * 31+ this.spayeetrecode.hashCode() ;
        if(this.staxstartdate!=null)
          _hash_ = _hash_ * 31+ this.staxstartdate.hashCode() ;
        if(this.staxenddate!=null)
          _hash_ = _hash_ * 31+ this.staxenddate.hashCode() ;
        if(this.slimitdate!=null)
          _hash_ = _hash_ * 31+ this.slimitdate.hashCode() ;
        if(this.staxtypename!=null)
          _hash_ = _hash_ * 31+ this.staxtypename.hashCode() ;
        if(this.nfacttaxamt!=null)
          _hash_ = _hash_ * 31+ this.nfacttaxamt.hashCode() ;
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.sopenaccbankcode!=null)
          _hash_ = _hash_ * 31+ this.sopenaccbankcode.hashCode() ;
        if(this.stcbstaxorgcode!=null)
          _hash_ = _hash_ * 31+ this.stcbstaxorgcode.hashCode() ;
        if(this.stcbstrecode!=null)
          _hash_ = _hash_ * 31+ this.stcbstrecode.hashCode() ;
        if(this.sassitsign!=null)
          _hash_ = _hash_ * 31+ this.sassitsign.hashCode() ;
        if(this.scorptype!=null)
          _hash_ = _hash_ * 31+ this.scorptype.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvInfileTmpCountryDto bean = new TvInfileTmpCountryDto();

          if (this.staxticketno != null)
            bean.staxticketno = new String(this.staxticketno);
          if (this.scorptypename != null)
            bean.scorptypename = new String(this.scorptypename);
          if (this.sbilldate != null)
            bean.sbilldate = new String(this.sbilldate);
          if (this.staxorgcode != null)
            bean.staxorgcode = new String(this.staxorgcode);
          if (this.scorpcode != null)
            bean.scorpcode = new String(this.scorpcode);
          if (this.scorpname != null)
            bean.scorpname = new String(this.scorpname);
          if (this.spaybnkno != null)
            bean.spaybnkno = new String(this.spaybnkno);
          if (this.spayacct != null)
            bean.spayacct = new String(this.spayacct);
          if (this.sbudgetsubcode != null)
            bean.sbudgetsubcode = new String(this.sbudgetsubcode);
          if (this.sbudgetlevelcode != null)
            bean.sbudgetlevelcode = new String(this.sbudgetlevelcode);
          if (this.spayeetrecode != null)
            bean.spayeetrecode = new String(this.spayeetrecode);
          if (this.staxstartdate != null)
            bean.staxstartdate = new String(this.staxstartdate);
          if (this.staxenddate != null)
            bean.staxenddate = new String(this.staxenddate);
          if (this.slimitdate != null)
            bean.slimitdate = new String(this.slimitdate);
          if (this.staxtypename != null)
            bean.staxtypename = new String(this.staxtypename);
          if (this.nfacttaxamt != null)
            bean.nfacttaxamt = new BigDecimal(this.nfacttaxamt.toString());
          if (this.sorgcode != null)
            bean.sorgcode = new String(this.sorgcode);
          if (this.sfilename != null)
            bean.sfilename = new String(this.sfilename);
          if (this.sopenaccbankcode != null)
            bean.sopenaccbankcode = new String(this.sopenaccbankcode);
          if (this.stcbstaxorgcode != null)
            bean.stcbstaxorgcode = new String(this.stcbstaxorgcode);
          if (this.stcbstrecode != null)
            bean.stcbstrecode = new String(this.stcbstrecode);
          if (this.sassitsign != null)
            bean.sassitsign = new String(this.sassitsign);
          if (this.scorptype != null)
            bean.scorptype = new String(this.scorptype);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvInfileTmpCountryDto").append(sep);
        sb.append("[staxticketno]").append(" = ").append(staxticketno).append(sep);
        sb.append("[scorptypename]").append(" = ").append(scorptypename).append(sep);
        sb.append("[sbilldate]").append(" = ").append(sbilldate).append(sep);
        sb.append("[staxorgcode]").append(" = ").append(staxorgcode).append(sep);
        sb.append("[scorpcode]").append(" = ").append(scorpcode).append(sep);
        sb.append("[scorpname]").append(" = ").append(scorpname).append(sep);
        sb.append("[spaybnkno]").append(" = ").append(spaybnkno).append(sep);
        sb.append("[spayacct]").append(" = ").append(spayacct).append(sep);
        sb.append("[sbudgetsubcode]").append(" = ").append(sbudgetsubcode).append(sep);
        sb.append("[sbudgetlevelcode]").append(" = ").append(sbudgetlevelcode).append(sep);
        sb.append("[spayeetrecode]").append(" = ").append(spayeetrecode).append(sep);
        sb.append("[staxstartdate]").append(" = ").append(staxstartdate).append(sep);
        sb.append("[staxenddate]").append(" = ").append(staxenddate).append(sep);
        sb.append("[slimitdate]").append(" = ").append(slimitdate).append(sep);
        sb.append("[staxtypename]").append(" = ").append(staxtypename).append(sep);
        sb.append("[nfacttaxamt]").append(" = ").append(nfacttaxamt).append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[sopenaccbankcode]").append(" = ").append(sopenaccbankcode).append(sep);
        sb.append("[stcbstaxorgcode]").append(" = ").append(stcbstaxorgcode).append(sep);
        sb.append("[stcbstrecode]").append(" = ").append(stcbstrecode).append(sep);
        sb.append("[sassitsign]").append(" = ").append(sassitsign).append(sep);
        sb.append("[scorptype]").append(" = ").append(scorptype).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_TAXTICKETNO
      if (this.getStaxticketno()==null)
             sb.append("S_TAXTICKETNO不能为空; ");
      if (this.getStaxticketno()!=null)
             if (this.getStaxticketno().getBytes().length > 20)
                sb.append("S_TAXTICKETNO宽度不能超过 "+20+"个字符; ");
    
    //check field S_CORPTYPENAME
      if (this.getScorptypename()!=null)
             if (this.getScorptypename().getBytes().length > 100)
                sb.append("S_CORPTYPENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_BILLDATE
      if (this.getSbilldate()!=null)
             if (this.getSbilldate().getBytes().length > 8)
                sb.append("S_BILLDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_TAXORGCODE
      if (this.getStaxorgcode()!=null)
             if (this.getStaxorgcode().getBytes().length > 12)
                sb.append("S_TAXORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_CORPCODE
      if (this.getScorpcode()!=null)
             if (this.getScorpcode().getBytes().length > 20)
                sb.append("S_CORPCODE宽度不能超过 "+20+"个字符; ");
    
    //check field S_CORPNAME
      if (this.getScorpname()!=null)
             if (this.getScorpname().getBytes().length > 200)
                sb.append("S_CORPNAME宽度不能超过 "+200+"个字符; ");
    
    //check field S_PAYBNKNO
      if (this.getSpaybnkno()!=null)
             if (this.getSpaybnkno().getBytes().length > 12)
                sb.append("S_PAYBNKNO宽度不能超过 "+12+"个字符; ");
    
    //check field S_PAYACCT
      if (this.getSpayacct()!=null)
             if (this.getSpayacct().getBytes().length > 32)
                sb.append("S_PAYACCT宽度不能超过 "+32+"个字符; ");
    
    //check field S_BUDGETSUBCODE
      if (this.getSbudgetsubcode()!=null)
             if (this.getSbudgetsubcode().getBytes().length > 30)
                sb.append("S_BUDGETSUBCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_BUDGETLEVELCODE
      if (this.getSbudgetlevelcode()!=null)
             if (this.getSbudgetlevelcode().getBytes().length > 1)
                sb.append("S_BUDGETLEVELCODE宽度不能超过 "+1+"个字符; ");
    
    //check field S_PAYEETRECODE
      if (this.getSpayeetrecode()!=null)
             if (this.getSpayeetrecode().getBytes().length > 12)
                sb.append("S_PAYEETRECODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_TAXSTARTDATE
      if (this.getStaxstartdate()!=null)
             if (this.getStaxstartdate().getBytes().length > 8)
                sb.append("S_TAXSTARTDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_TAXENDDATE
      if (this.getStaxenddate()!=null)
             if (this.getStaxenddate().getBytes().length > 8)
                sb.append("S_TAXENDDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_LIMITDATE
      if (this.getSlimitdate()!=null)
             if (this.getSlimitdate().getBytes().length > 8)
                sb.append("S_LIMITDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_TAXTYPENAME
      if (this.getStaxtypename()!=null)
             if (this.getStaxtypename().getBytes().length > 60)
                sb.append("S_TAXTYPENAME宽度不能超过 "+60+"个字符; ");
    
    //check field N_FACTTAXAMT
      
    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()==null)
             sb.append("S_FILENAME不能为空; ");
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_OPENACCBANKCODE
      if (this.getSopenaccbankcode()!=null)
             if (this.getSopenaccbankcode().getBytes().length > 12)
                sb.append("S_OPENACCBANKCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_TCBSTAXORGCODE
      if (this.getStcbstaxorgcode()!=null)
             if (this.getStcbstaxorgcode().getBytes().length > 30)
                sb.append("S_TCBSTAXORGCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_TCBSTRECODE
      if (this.getStcbstrecode()!=null)
             if (this.getStcbstrecode().getBytes().length > 10)
                sb.append("S_TCBSTRECODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_ASSITSIGN
      if (this.getSassitsign()!=null)
             if (this.getSassitsign().getBytes().length > 35)
                sb.append("S_ASSITSIGN宽度不能超过 "+35+"个字符; ");
    
    //check field S_CORPTYPE
      if (this.getScorptype()!=null)
             if (this.getScorptype().getBytes().length > 12)
                sb.append("S_CORPTYPE宽度不能超过 "+12+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_TAXTICKETNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTICKETNO")) {
               if (this.getStaxticketno()==null)
                    sb.append("S_TAXTICKETNO 不能为空; ");
               if (this.getStaxticketno()!=null)
                    if (this.getStaxticketno().getBytes().length > 20)
                        sb.append("S_TAXTICKETNO 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_CORPTYPENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CORPTYPENAME")) {
                 if (this.getScorptypename()!=null)
                    if (this.getScorptypename().getBytes().length > 100)
                        sb.append("S_CORPTYPENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_BILLDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BILLDATE")) {
                 if (this.getSbilldate()!=null)
                    if (this.getSbilldate().getBytes().length > 8)
                        sb.append("S_BILLDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TAXORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXORGCODE")) {
                 if (this.getStaxorgcode()!=null)
                    if (this.getStaxorgcode().getBytes().length > 12)
                        sb.append("S_TAXORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_CORPCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CORPCODE")) {
                 if (this.getScorpcode()!=null)
                    if (this.getScorpcode().getBytes().length > 20)
                        sb.append("S_CORPCODE 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_CORPNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CORPNAME")) {
                 if (this.getScorpname()!=null)
                    if (this.getScorpname().getBytes().length > 200)
                        sb.append("S_CORPNAME 宽度不能超过 "+200+"个字符");
             break;
         }
  }
    
    //check field S_PAYBNKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBNKNO")) {
                 if (this.getSpaybnkno()!=null)
                    if (this.getSpaybnkno().getBytes().length > 12)
                        sb.append("S_PAYBNKNO 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_PAYACCT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYACCT")) {
                 if (this.getSpayacct()!=null)
                    if (this.getSpayacct().getBytes().length > 32)
                        sb.append("S_PAYACCT 宽度不能超过 "+32+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETSUBCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETSUBCODE")) {
                 if (this.getSbudgetsubcode()!=null)
                    if (this.getSbudgetsubcode().getBytes().length > 30)
                        sb.append("S_BUDGETSUBCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETLEVELCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETLEVELCODE")) {
                 if (this.getSbudgetlevelcode()!=null)
                    if (this.getSbudgetlevelcode().getBytes().length > 1)
                        sb.append("S_BUDGETLEVELCODE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_PAYEETRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEETRECODE")) {
                 if (this.getSpayeetrecode()!=null)
                    if (this.getSpayeetrecode().getBytes().length > 12)
                        sb.append("S_PAYEETRECODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_TAXSTARTDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXSTARTDATE")) {
                 if (this.getStaxstartdate()!=null)
                    if (this.getStaxstartdate().getBytes().length > 8)
                        sb.append("S_TAXSTARTDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TAXENDDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXENDDATE")) {
                 if (this.getStaxenddate()!=null)
                    if (this.getStaxenddate().getBytes().length > 8)
                        sb.append("S_TAXENDDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_LIMITDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_LIMITDATE")) {
                 if (this.getSlimitdate()!=null)
                    if (this.getSlimitdate().getBytes().length > 8)
                        sb.append("S_LIMITDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TAXTYPENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTYPENAME")) {
                 if (this.getStaxtypename()!=null)
                    if (this.getStaxtypename().getBytes().length > 60)
                        sb.append("S_TAXTYPENAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field N_FACTTAXAMT
          
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
               if (this.getSfilename()==null)
                    sb.append("S_FILENAME 不能为空; ");
               if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_OPENACCBANKCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OPENACCBANKCODE")) {
                 if (this.getSopenaccbankcode()!=null)
                    if (this.getSopenaccbankcode().getBytes().length > 12)
                        sb.append("S_OPENACCBANKCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_TCBSTAXORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TCBSTAXORGCODE")) {
                 if (this.getStcbstaxorgcode()!=null)
                    if (this.getStcbstaxorgcode().getBytes().length > 30)
                        sb.append("S_TCBSTAXORGCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_TCBSTRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TCBSTRECODE")) {
                 if (this.getStcbstrecode()!=null)
                    if (this.getStcbstrecode().getBytes().length > 10)
                        sb.append("S_TCBSTRECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_ASSITSIGN
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ASSITSIGN")) {
                 if (this.getSassitsign()!=null)
                    if (this.getSassitsign().getBytes().length > 35)
                        sb.append("S_ASSITSIGN 宽度不能超过 "+35+"个字符");
             break;
         }
  }
    
    //check field S_CORPTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CORPTYPE")) {
                 if (this.getScorptype()!=null)
                    if (this.getScorptype().getBytes().length > 12)
                        sb.append("S_CORPTYPE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      throw new RuntimeException("此dto没有PK，不能进行此操作");
    };
}
