    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvInfilePK;
/**
 * <p>Title: DTO of table: TV_INFILE</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvInfileDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_ORGCODE VARCHAR , PK   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_COMMITDATE CHARACTER , PK   , NOT NULL       */
    protected String scommitdate;
    /**
    *  S_ACCDATE CHARACTER   , NOT NULL       */
    protected String saccdate;
    /**
    *  S_PACKAGENO VARCHAR   , NOT NULL       */
    protected String spackageno;
    /**
    *  S_TAXORGCODE VARCHAR   , NOT NULL       */
    protected String staxorgcode;
    /**
    *  S_TBS_TAXORGCODE VARCHAR         */
    protected String stbstaxorgcode;
    /**
    *  S_FILENAME VARCHAR   , NOT NULL       */
    protected String sfilename;
    /**
    *  S_RECVTRECODE CHARACTER   , NOT NULL       */
    protected String srecvtrecode;
    /**
    *  S_RECVTRENAME VARCHAR         */
    protected String srecvtrename;
    /**
    *  S_DEALNO VARCHAR , PK   , NOT NULL       */
    protected String sdealno;
    /**
    *  S_TRASRLNO VARCHAR   , NOT NULL       */
    protected String strasrlno;
    /**
    *  N_MONEY DECIMAL   , NOT NULL       */
    protected BigDecimal nmoney;
    /**
    *  S_TAXTICKETNO VARCHAR   , NOT NULL       */
    protected String staxticketno;
    /**
    *  S_GENTICKETDATE CHARACTER   , NOT NULL       */
    protected String sgenticketdate;
    /**
    *  S_BUDGETTYPE CHARACTER   , NOT NULL       */
    protected String sbudgettype;
    /**
    *  S_TRIMFLAG CHARACTER   , NOT NULL       */
    protected String strimflag;
    /**
    *  S_BUDGETSUBCODE VARCHAR   , NOT NULL       */
    protected String sbudgetsubcode;
    /**
    *  S_BUDGETLEVELCODE CHARACTER   , NOT NULL       */
    protected String sbudgetlevelcode;
    /**
    *  S_ASSITSIGN VARCHAR         */
    protected String sassitsign;
    /**
    *  S_TBS_ASSITSIGN VARCHAR         */
    protected String stbsassitsign;
    /**
    *  S_UNITCODE VARCHAR         */
    protected String sunitcode;
    /**
    *  S_PAYBOOKKIND VARCHAR         */
    protected String spaybookkind;
    /**
    *  S_OPENACCBANKCODE VARCHAR         */
    protected String sopenaccbankcode;
    /**
    *  S_STATUS CHARACTER   , NOT NULL       */
    protected String sstatus;
    /**
    *  S_USERCODE VARCHAR   , NOT NULL       */
    protected String susercode;
    /**
    *  S_DEMO VARCHAR         */
    protected String sdemo;
    /**
    *  S_TAXPAYCODE VARCHAR         */
    protected String staxpaycode;
    /**
    *  S_TAXPAYNAME VARCHAR         */
    protected String staxpayname;
    /**
    *  S_CORPTYPE VARCHAR         */
    protected String scorptype;
    /**
    *  S_LIMITDATE CHARACTER         */
    protected String slimitdate;
    /**
    *  S_TAXTYPECODE VARCHAR         */
    protected String staxtypecode;
    /**
    *  S_TAXTYPENAME VARCHAR         */
    protected String staxtypename;
    /**
    *  S_TAXSUBJECTNAME VARCHAR         */
    protected String staxsubjectname;
    /**
    *  S_PAYBNKNO VARCHAR         */
    protected String spaybnkno;
    /**
    *  S_PAYACCT VARCHAR         */
    protected String spayacct;
    /**
    *  S_TAXSTARTDATE CHARACTER         */
    protected String staxstartdate;
    /**
    *  S_TAXENDDATE CHARACTER         */
    protected String staxenddate;
    /**
    *  S_TAXNUMBER VARCHAR         */
    protected String staxnumber;
    /**
    *  N_TAXAMT DECIMAL         */
    protected BigDecimal ntaxamt;
    /**
    *  N_TAXRATE DECIMAL         */
    protected BigDecimal ntaxrate;
    /**
    *  N_DISCOUNTTAXAMT DECIMAL         */
    protected BigDecimal ndiscounttaxamt;
    /**
    *  N_FACTTAXAMT DECIMAL         */
    protected BigDecimal nfacttaxamt;
    /**
    *  S_SOURCEFLAG CHARACTER         */
    protected String ssourceflag;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE, PK , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getScommitdate()
    {
        return scommitdate;
    }
     /**
     *   Setter S_COMMITDATE, PK , NOT NULL        * */
    public void setScommitdate(String _scommitdate) {
        this.scommitdate = _scommitdate;
    }


    public String getSaccdate()
    {
        return saccdate;
    }
     /**
     *   Setter S_ACCDATE , NOT NULL        * */
    public void setSaccdate(String _saccdate) {
        this.saccdate = _saccdate;
    }


    public String getSpackageno()
    {
        return spackageno;
    }
     /**
     *   Setter S_PACKAGENO , NOT NULL        * */
    public void setSpackageno(String _spackageno) {
        this.spackageno = _spackageno;
    }


    public String getStaxorgcode()
    {
        return staxorgcode;
    }
     /**
     *   Setter S_TAXORGCODE , NOT NULL        * */
    public void setStaxorgcode(String _staxorgcode) {
        this.staxorgcode = _staxorgcode;
    }


    public String getStbstaxorgcode()
    {
        return stbstaxorgcode;
    }
     /**
     *   Setter S_TBS_TAXORGCODE        * */
    public void setStbstaxorgcode(String _stbstaxorgcode) {
        this.stbstaxorgcode = _stbstaxorgcode;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME , NOT NULL        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getSrecvtrecode()
    {
        return srecvtrecode;
    }
     /**
     *   Setter S_RECVTRECODE , NOT NULL        * */
    public void setSrecvtrecode(String _srecvtrecode) {
        this.srecvtrecode = _srecvtrecode;
    }


    public String getSrecvtrename()
    {
        return srecvtrename;
    }
     /**
     *   Setter S_RECVTRENAME        * */
    public void setSrecvtrename(String _srecvtrename) {
        this.srecvtrename = _srecvtrename;
    }


    public String getSdealno()
    {
        return sdealno;
    }
     /**
     *   Setter S_DEALNO, PK , NOT NULL        * */
    public void setSdealno(String _sdealno) {
        this.sdealno = _sdealno;
    }


    public String getStrasrlno()
    {
        return strasrlno;
    }
     /**
     *   Setter S_TRASRLNO , NOT NULL        * */
    public void setStrasrlno(String _strasrlno) {
        this.strasrlno = _strasrlno;
    }


    public BigDecimal getNmoney()
    {
        return nmoney;
    }
     /**
     *   Setter N_MONEY , NOT NULL        * */
    public void setNmoney(BigDecimal _nmoney) {
        this.nmoney = _nmoney;
    }


    public String getStaxticketno()
    {
        return staxticketno;
    }
     /**
     *   Setter S_TAXTICKETNO , NOT NULL        * */
    public void setStaxticketno(String _staxticketno) {
        this.staxticketno = _staxticketno;
    }


    public String getSgenticketdate()
    {
        return sgenticketdate;
    }
     /**
     *   Setter S_GENTICKETDATE , NOT NULL        * */
    public void setSgenticketdate(String _sgenticketdate) {
        this.sgenticketdate = _sgenticketdate;
    }


    public String getSbudgettype()
    {
        return sbudgettype;
    }
     /**
     *   Setter S_BUDGETTYPE , NOT NULL        * */
    public void setSbudgettype(String _sbudgettype) {
        this.sbudgettype = _sbudgettype;
    }


    public String getStrimflag()
    {
        return strimflag;
    }
     /**
     *   Setter S_TRIMFLAG , NOT NULL        * */
    public void setStrimflag(String _strimflag) {
        this.strimflag = _strimflag;
    }


    public String getSbudgetsubcode()
    {
        return sbudgetsubcode;
    }
     /**
     *   Setter S_BUDGETSUBCODE , NOT NULL        * */
    public void setSbudgetsubcode(String _sbudgetsubcode) {
        this.sbudgetsubcode = _sbudgetsubcode;
    }


    public String getSbudgetlevelcode()
    {
        return sbudgetlevelcode;
    }
     /**
     *   Setter S_BUDGETLEVELCODE , NOT NULL        * */
    public void setSbudgetlevelcode(String _sbudgetlevelcode) {
        this.sbudgetlevelcode = _sbudgetlevelcode;
    }


    public String getSassitsign()
    {
        return sassitsign;
    }
     /**
     *   Setter S_ASSITSIGN        * */
    public void setSassitsign(String _sassitsign) {
        this.sassitsign = _sassitsign;
    }


    public String getStbsassitsign()
    {
        return stbsassitsign;
    }
     /**
     *   Setter S_TBS_ASSITSIGN        * */
    public void setStbsassitsign(String _stbsassitsign) {
        this.stbsassitsign = _stbsassitsign;
    }


    public String getSunitcode()
    {
        return sunitcode;
    }
     /**
     *   Setter S_UNITCODE        * */
    public void setSunitcode(String _sunitcode) {
        this.sunitcode = _sunitcode;
    }


    public String getSpaybookkind()
    {
        return spaybookkind;
    }
     /**
     *   Setter S_PAYBOOKKIND        * */
    public void setSpaybookkind(String _spaybookkind) {
        this.spaybookkind = _spaybookkind;
    }


    public String getSopenaccbankcode()
    {
        return sopenaccbankcode;
    }
     /**
     *   Setter S_OPENACCBANKCODE        * */
    public void setSopenaccbankcode(String _sopenaccbankcode) {
        this.sopenaccbankcode = _sopenaccbankcode;
    }


    public String getSstatus()
    {
        return sstatus;
    }
     /**
     *   Setter S_STATUS , NOT NULL        * */
    public void setSstatus(String _sstatus) {
        this.sstatus = _sstatus;
    }


    public String getSusercode()
    {
        return susercode;
    }
     /**
     *   Setter S_USERCODE , NOT NULL        * */
    public void setSusercode(String _susercode) {
        this.susercode = _susercode;
    }


    public String getSdemo()
    {
        return sdemo;
    }
     /**
     *   Setter S_DEMO        * */
    public void setSdemo(String _sdemo) {
        this.sdemo = _sdemo;
    }


    public String getStaxpaycode()
    {
        return staxpaycode;
    }
     /**
     *   Setter S_TAXPAYCODE        * */
    public void setStaxpaycode(String _staxpaycode) {
        this.staxpaycode = _staxpaycode;
    }


    public String getStaxpayname()
    {
        return staxpayname;
    }
     /**
     *   Setter S_TAXPAYNAME        * */
    public void setStaxpayname(String _staxpayname) {
        this.staxpayname = _staxpayname;
    }


    public String getScorptype()
    {
        return scorptype;
    }
     /**
     *   Setter S_CORPTYPE        * */
    public void setScorptype(String _scorptype) {
        this.scorptype = _scorptype;
    }


    public String getSlimitdate()
    {
        return slimitdate;
    }
     /**
     *   Setter S_LIMITDATE        * */
    public void setSlimitdate(String _slimitdate) {
        this.slimitdate = _slimitdate;
    }


    public String getStaxtypecode()
    {
        return staxtypecode;
    }
     /**
     *   Setter S_TAXTYPECODE        * */
    public void setStaxtypecode(String _staxtypecode) {
        this.staxtypecode = _staxtypecode;
    }


    public String getStaxtypename()
    {
        return staxtypename;
    }
     /**
     *   Setter S_TAXTYPENAME        * */
    public void setStaxtypename(String _staxtypename) {
        this.staxtypename = _staxtypename;
    }


    public String getStaxsubjectname()
    {
        return staxsubjectname;
    }
     /**
     *   Setter S_TAXSUBJECTNAME        * */
    public void setStaxsubjectname(String _staxsubjectname) {
        this.staxsubjectname = _staxsubjectname;
    }


    public String getSpaybnkno()
    {
        return spaybnkno;
    }
     /**
     *   Setter S_PAYBNKNO        * */
    public void setSpaybnkno(String _spaybnkno) {
        this.spaybnkno = _spaybnkno;
    }


    public String getSpayacct()
    {
        return spayacct;
    }
     /**
     *   Setter S_PAYACCT        * */
    public void setSpayacct(String _spayacct) {
        this.spayacct = _spayacct;
    }


    public String getStaxstartdate()
    {
        return staxstartdate;
    }
     /**
     *   Setter S_TAXSTARTDATE        * */
    public void setStaxstartdate(String _staxstartdate) {
        this.staxstartdate = _staxstartdate;
    }


    public String getStaxenddate()
    {
        return staxenddate;
    }
     /**
     *   Setter S_TAXENDDATE        * */
    public void setStaxenddate(String _staxenddate) {
        this.staxenddate = _staxenddate;
    }


    public String getStaxnumber()
    {
        return staxnumber;
    }
     /**
     *   Setter S_TAXNUMBER        * */
    public void setStaxnumber(String _staxnumber) {
        this.staxnumber = _staxnumber;
    }


    public BigDecimal getNtaxamt()
    {
        return ntaxamt;
    }
     /**
     *   Setter N_TAXAMT        * */
    public void setNtaxamt(BigDecimal _ntaxamt) {
        this.ntaxamt = _ntaxamt;
    }


    public BigDecimal getNtaxrate()
    {
        return ntaxrate;
    }
     /**
     *   Setter N_TAXRATE        * */
    public void setNtaxrate(BigDecimal _ntaxrate) {
        this.ntaxrate = _ntaxrate;
    }


    public BigDecimal getNdiscounttaxamt()
    {
        return ndiscounttaxamt;
    }
     /**
     *   Setter N_DISCOUNTTAXAMT        * */
    public void setNdiscounttaxamt(BigDecimal _ndiscounttaxamt) {
        this.ndiscounttaxamt = _ndiscounttaxamt;
    }


    public BigDecimal getNfacttaxamt()
    {
        return nfacttaxamt;
    }
     /**
     *   Setter N_FACTTAXAMT        * */
    public void setNfacttaxamt(BigDecimal _nfacttaxamt) {
        this.nfacttaxamt = _nfacttaxamt;
    }


    public String getSsourceflag()
    {
        return ssourceflag;
    }
     /**
     *   Setter S_SOURCEFLAG        * */
    public void setSsourceflag(String _ssourceflag) {
        this.ssourceflag = _ssourceflag;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_ORGCODE, PK , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_COMMITDATE, PK , NOT NULL       * */
    public static String  columnScommitdate()
    {
        return "S_COMMITDATE";
    }
   
    /**
    *   Getter S_ACCDATE , NOT NULL       * */
    public static String  columnSaccdate()
    {
        return "S_ACCDATE";
    }
   
    /**
    *   Getter S_PACKAGENO , NOT NULL       * */
    public static String  columnSpackageno()
    {
        return "S_PACKAGENO";
    }
   
    /**
    *   Getter S_TAXORGCODE , NOT NULL       * */
    public static String  columnStaxorgcode()
    {
        return "S_TAXORGCODE";
    }
   
    /**
    *   Getter S_TBS_TAXORGCODE       * */
    public static String  columnStbstaxorgcode()
    {
        return "S_TBS_TAXORGCODE";
    }
   
    /**
    *   Getter S_FILENAME , NOT NULL       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_RECVTRECODE , NOT NULL       * */
    public static String  columnSrecvtrecode()
    {
        return "S_RECVTRECODE";
    }
   
    /**
    *   Getter S_RECVTRENAME       * */
    public static String  columnSrecvtrename()
    {
        return "S_RECVTRENAME";
    }
   
    /**
    *   Getter S_DEALNO, PK , NOT NULL       * */
    public static String  columnSdealno()
    {
        return "S_DEALNO";
    }
   
    /**
    *   Getter S_TRASRLNO , NOT NULL       * */
    public static String  columnStrasrlno()
    {
        return "S_TRASRLNO";
    }
   
    /**
    *   Getter N_MONEY , NOT NULL       * */
    public static String  columnNmoney()
    {
        return "N_MONEY";
    }
   
    /**
    *   Getter S_TAXTICKETNO , NOT NULL       * */
    public static String  columnStaxticketno()
    {
        return "S_TAXTICKETNO";
    }
   
    /**
    *   Getter S_GENTICKETDATE , NOT NULL       * */
    public static String  columnSgenticketdate()
    {
        return "S_GENTICKETDATE";
    }
   
    /**
    *   Getter S_BUDGETTYPE , NOT NULL       * */
    public static String  columnSbudgettype()
    {
        return "S_BUDGETTYPE";
    }
   
    /**
    *   Getter S_TRIMFLAG , NOT NULL       * */
    public static String  columnStrimflag()
    {
        return "S_TRIMFLAG";
    }
   
    /**
    *   Getter S_BUDGETSUBCODE , NOT NULL       * */
    public static String  columnSbudgetsubcode()
    {
        return "S_BUDGETSUBCODE";
    }
   
    /**
    *   Getter S_BUDGETLEVELCODE , NOT NULL       * */
    public static String  columnSbudgetlevelcode()
    {
        return "S_BUDGETLEVELCODE";
    }
   
    /**
    *   Getter S_ASSITSIGN       * */
    public static String  columnSassitsign()
    {
        return "S_ASSITSIGN";
    }
   
    /**
    *   Getter S_TBS_ASSITSIGN       * */
    public static String  columnStbsassitsign()
    {
        return "S_TBS_ASSITSIGN";
    }
   
    /**
    *   Getter S_UNITCODE       * */
    public static String  columnSunitcode()
    {
        return "S_UNITCODE";
    }
   
    /**
    *   Getter S_PAYBOOKKIND       * */
    public static String  columnSpaybookkind()
    {
        return "S_PAYBOOKKIND";
    }
   
    /**
    *   Getter S_OPENACCBANKCODE       * */
    public static String  columnSopenaccbankcode()
    {
        return "S_OPENACCBANKCODE";
    }
   
    /**
    *   Getter S_STATUS , NOT NULL       * */
    public static String  columnSstatus()
    {
        return "S_STATUS";
    }
   
    /**
    *   Getter S_USERCODE , NOT NULL       * */
    public static String  columnSusercode()
    {
        return "S_USERCODE";
    }
   
    /**
    *   Getter S_DEMO       * */
    public static String  columnSdemo()
    {
        return "S_DEMO";
    }
   
    /**
    *   Getter S_TAXPAYCODE       * */
    public static String  columnStaxpaycode()
    {
        return "S_TAXPAYCODE";
    }
   
    /**
    *   Getter S_TAXPAYNAME       * */
    public static String  columnStaxpayname()
    {
        return "S_TAXPAYNAME";
    }
   
    /**
    *   Getter S_CORPTYPE       * */
    public static String  columnScorptype()
    {
        return "S_CORPTYPE";
    }
   
    /**
    *   Getter S_LIMITDATE       * */
    public static String  columnSlimitdate()
    {
        return "S_LIMITDATE";
    }
   
    /**
    *   Getter S_TAXTYPECODE       * */
    public static String  columnStaxtypecode()
    {
        return "S_TAXTYPECODE";
    }
   
    /**
    *   Getter S_TAXTYPENAME       * */
    public static String  columnStaxtypename()
    {
        return "S_TAXTYPENAME";
    }
   
    /**
    *   Getter S_TAXSUBJECTNAME       * */
    public static String  columnStaxsubjectname()
    {
        return "S_TAXSUBJECTNAME";
    }
   
    /**
    *   Getter S_PAYBNKNO       * */
    public static String  columnSpaybnkno()
    {
        return "S_PAYBNKNO";
    }
   
    /**
    *   Getter S_PAYACCT       * */
    public static String  columnSpayacct()
    {
        return "S_PAYACCT";
    }
   
    /**
    *   Getter S_TAXSTARTDATE       * */
    public static String  columnStaxstartdate()
    {
        return "S_TAXSTARTDATE";
    }
   
    /**
    *   Getter S_TAXENDDATE       * */
    public static String  columnStaxenddate()
    {
        return "S_TAXENDDATE";
    }
   
    /**
    *   Getter S_TAXNUMBER       * */
    public static String  columnStaxnumber()
    {
        return "S_TAXNUMBER";
    }
   
    /**
    *   Getter N_TAXAMT       * */
    public static String  columnNtaxamt()
    {
        return "N_TAXAMT";
    }
   
    /**
    *   Getter N_TAXRATE       * */
    public static String  columnNtaxrate()
    {
        return "N_TAXRATE";
    }
   
    /**
    *   Getter N_DISCOUNTTAXAMT       * */
    public static String  columnNdiscounttaxamt()
    {
        return "N_DISCOUNTTAXAMT";
    }
   
    /**
    *   Getter N_FACTTAXAMT       * */
    public static String  columnNfacttaxamt()
    {
        return "N_FACTTAXAMT";
    }
   
    /**
    *   Getter S_SOURCEFLAG       * */
    public static String  columnSsourceflag()
    {
        return "S_SOURCEFLAG";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_INFILE";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[43];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_COMMITDATE";
        columnNames[2]="S_ACCDATE";
        columnNames[3]="S_PACKAGENO";
        columnNames[4]="S_TAXORGCODE";
        columnNames[5]="S_TBS_TAXORGCODE";
        columnNames[6]="S_FILENAME";
        columnNames[7]="S_RECVTRECODE";
        columnNames[8]="S_RECVTRENAME";
        columnNames[9]="S_DEALNO";
        columnNames[10]="S_TRASRLNO";
        columnNames[11]="N_MONEY";
        columnNames[12]="S_TAXTICKETNO";
        columnNames[13]="S_GENTICKETDATE";
        columnNames[14]="S_BUDGETTYPE";
        columnNames[15]="S_TRIMFLAG";
        columnNames[16]="S_BUDGETSUBCODE";
        columnNames[17]="S_BUDGETLEVELCODE";
        columnNames[18]="S_ASSITSIGN";
        columnNames[19]="S_TBS_ASSITSIGN";
        columnNames[20]="S_UNITCODE";
        columnNames[21]="S_PAYBOOKKIND";
        columnNames[22]="S_OPENACCBANKCODE";
        columnNames[23]="S_STATUS";
        columnNames[24]="S_USERCODE";
        columnNames[25]="S_DEMO";
        columnNames[26]="S_TAXPAYCODE";
        columnNames[27]="S_TAXPAYNAME";
        columnNames[28]="S_CORPTYPE";
        columnNames[29]="S_LIMITDATE";
        columnNames[30]="S_TAXTYPECODE";
        columnNames[31]="S_TAXTYPENAME";
        columnNames[32]="S_TAXSUBJECTNAME";
        columnNames[33]="S_PAYBNKNO";
        columnNames[34]="S_PAYACCT";
        columnNames[35]="S_TAXSTARTDATE";
        columnNames[36]="S_TAXENDDATE";
        columnNames[37]="S_TAXNUMBER";
        columnNames[38]="N_TAXAMT";
        columnNames[39]="N_TAXRATE";
        columnNames[40]="N_DISCOUNTTAXAMT";
        columnNames[41]="N_FACTTAXAMT";
        columnNames[42]="S_SOURCEFLAG";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvInfileDto))
            return false;

        TvInfileDto bean = (TvInfileDto) obj;


      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field scommitdate
      if((this.scommitdate==null && bean.scommitdate!=null) || (this.scommitdate!=null && bean.scommitdate==null))
          return false;
        else if(this.scommitdate==null && bean.scommitdate==null){
        }
        else{
          if(!bean.scommitdate.equals(this.scommitdate))
               return false;
     }
      //compare field saccdate
      if((this.saccdate==null && bean.saccdate!=null) || (this.saccdate!=null && bean.saccdate==null))
          return false;
        else if(this.saccdate==null && bean.saccdate==null){
        }
        else{
          if(!bean.saccdate.equals(this.saccdate))
               return false;
     }
      //compare field spackageno
      if((this.spackageno==null && bean.spackageno!=null) || (this.spackageno!=null && bean.spackageno==null))
          return false;
        else if(this.spackageno==null && bean.spackageno==null){
        }
        else{
          if(!bean.spackageno.equals(this.spackageno))
               return false;
     }
      //compare field staxorgcode
      if((this.staxorgcode==null && bean.staxorgcode!=null) || (this.staxorgcode!=null && bean.staxorgcode==null))
          return false;
        else if(this.staxorgcode==null && bean.staxorgcode==null){
        }
        else{
          if(!bean.staxorgcode.equals(this.staxorgcode))
               return false;
     }
      //compare field stbstaxorgcode
      if((this.stbstaxorgcode==null && bean.stbstaxorgcode!=null) || (this.stbstaxorgcode!=null && bean.stbstaxorgcode==null))
          return false;
        else if(this.stbstaxorgcode==null && bean.stbstaxorgcode==null){
        }
        else{
          if(!bean.stbstaxorgcode.equals(this.stbstaxorgcode))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field srecvtrecode
      if((this.srecvtrecode==null && bean.srecvtrecode!=null) || (this.srecvtrecode!=null && bean.srecvtrecode==null))
          return false;
        else if(this.srecvtrecode==null && bean.srecvtrecode==null){
        }
        else{
          if(!bean.srecvtrecode.equals(this.srecvtrecode))
               return false;
     }
      //compare field srecvtrename
      if((this.srecvtrename==null && bean.srecvtrename!=null) || (this.srecvtrename!=null && bean.srecvtrename==null))
          return false;
        else if(this.srecvtrename==null && bean.srecvtrename==null){
        }
        else{
          if(!bean.srecvtrename.equals(this.srecvtrename))
               return false;
     }
      //compare field sdealno
      if((this.sdealno==null && bean.sdealno!=null) || (this.sdealno!=null && bean.sdealno==null))
          return false;
        else if(this.sdealno==null && bean.sdealno==null){
        }
        else{
          if(!bean.sdealno.equals(this.sdealno))
               return false;
     }
      //compare field strasrlno
      if((this.strasrlno==null && bean.strasrlno!=null) || (this.strasrlno!=null && bean.strasrlno==null))
          return false;
        else if(this.strasrlno==null && bean.strasrlno==null){
        }
        else{
          if(!bean.strasrlno.equals(this.strasrlno))
               return false;
     }
      //compare field nmoney
      if((this.nmoney==null && bean.nmoney!=null) || (this.nmoney!=null && bean.nmoney==null))
          return false;
        else if(this.nmoney==null && bean.nmoney==null){
        }
        else{
          if(!bean.nmoney.equals(this.nmoney))
               return false;
     }
      //compare field staxticketno
      if((this.staxticketno==null && bean.staxticketno!=null) || (this.staxticketno!=null && bean.staxticketno==null))
          return false;
        else if(this.staxticketno==null && bean.staxticketno==null){
        }
        else{
          if(!bean.staxticketno.equals(this.staxticketno))
               return false;
     }
      //compare field sgenticketdate
      if((this.sgenticketdate==null && bean.sgenticketdate!=null) || (this.sgenticketdate!=null && bean.sgenticketdate==null))
          return false;
        else if(this.sgenticketdate==null && bean.sgenticketdate==null){
        }
        else{
          if(!bean.sgenticketdate.equals(this.sgenticketdate))
               return false;
     }
      //compare field sbudgettype
      if((this.sbudgettype==null && bean.sbudgettype!=null) || (this.sbudgettype!=null && bean.sbudgettype==null))
          return false;
        else if(this.sbudgettype==null && bean.sbudgettype==null){
        }
        else{
          if(!bean.sbudgettype.equals(this.sbudgettype))
               return false;
     }
      //compare field strimflag
      if((this.strimflag==null && bean.strimflag!=null) || (this.strimflag!=null && bean.strimflag==null))
          return false;
        else if(this.strimflag==null && bean.strimflag==null){
        }
        else{
          if(!bean.strimflag.equals(this.strimflag))
               return false;
     }
      //compare field sbudgetsubcode
      if((this.sbudgetsubcode==null && bean.sbudgetsubcode!=null) || (this.sbudgetsubcode!=null && bean.sbudgetsubcode==null))
          return false;
        else if(this.sbudgetsubcode==null && bean.sbudgetsubcode==null){
        }
        else{
          if(!bean.sbudgetsubcode.equals(this.sbudgetsubcode))
               return false;
     }
      //compare field sbudgetlevelcode
      if((this.sbudgetlevelcode==null && bean.sbudgetlevelcode!=null) || (this.sbudgetlevelcode!=null && bean.sbudgetlevelcode==null))
          return false;
        else if(this.sbudgetlevelcode==null && bean.sbudgetlevelcode==null){
        }
        else{
          if(!bean.sbudgetlevelcode.equals(this.sbudgetlevelcode))
               return false;
     }
      //compare field sassitsign
      if((this.sassitsign==null && bean.sassitsign!=null) || (this.sassitsign!=null && bean.sassitsign==null))
          return false;
        else if(this.sassitsign==null && bean.sassitsign==null){
        }
        else{
          if(!bean.sassitsign.equals(this.sassitsign))
               return false;
     }
      //compare field stbsassitsign
      if((this.stbsassitsign==null && bean.stbsassitsign!=null) || (this.stbsassitsign!=null && bean.stbsassitsign==null))
          return false;
        else if(this.stbsassitsign==null && bean.stbsassitsign==null){
        }
        else{
          if(!bean.stbsassitsign.equals(this.stbsassitsign))
               return false;
     }
      //compare field sunitcode
      if((this.sunitcode==null && bean.sunitcode!=null) || (this.sunitcode!=null && bean.sunitcode==null))
          return false;
        else if(this.sunitcode==null && bean.sunitcode==null){
        }
        else{
          if(!bean.sunitcode.equals(this.sunitcode))
               return false;
     }
      //compare field spaybookkind
      if((this.spaybookkind==null && bean.spaybookkind!=null) || (this.spaybookkind!=null && bean.spaybookkind==null))
          return false;
        else if(this.spaybookkind==null && bean.spaybookkind==null){
        }
        else{
          if(!bean.spaybookkind.equals(this.spaybookkind))
               return false;
     }
      //compare field sopenaccbankcode
      if((this.sopenaccbankcode==null && bean.sopenaccbankcode!=null) || (this.sopenaccbankcode!=null && bean.sopenaccbankcode==null))
          return false;
        else if(this.sopenaccbankcode==null && bean.sopenaccbankcode==null){
        }
        else{
          if(!bean.sopenaccbankcode.equals(this.sopenaccbankcode))
               return false;
     }
      //compare field sstatus
      if((this.sstatus==null && bean.sstatus!=null) || (this.sstatus!=null && bean.sstatus==null))
          return false;
        else if(this.sstatus==null && bean.sstatus==null){
        }
        else{
          if(!bean.sstatus.equals(this.sstatus))
               return false;
     }
      //compare field susercode
      if((this.susercode==null && bean.susercode!=null) || (this.susercode!=null && bean.susercode==null))
          return false;
        else if(this.susercode==null && bean.susercode==null){
        }
        else{
          if(!bean.susercode.equals(this.susercode))
               return false;
     }
      //compare field sdemo
      if((this.sdemo==null && bean.sdemo!=null) || (this.sdemo!=null && bean.sdemo==null))
          return false;
        else if(this.sdemo==null && bean.sdemo==null){
        }
        else{
          if(!bean.sdemo.equals(this.sdemo))
               return false;
     }
      //compare field staxpaycode
      if((this.staxpaycode==null && bean.staxpaycode!=null) || (this.staxpaycode!=null && bean.staxpaycode==null))
          return false;
        else if(this.staxpaycode==null && bean.staxpaycode==null){
        }
        else{
          if(!bean.staxpaycode.equals(this.staxpaycode))
               return false;
     }
      //compare field staxpayname
      if((this.staxpayname==null && bean.staxpayname!=null) || (this.staxpayname!=null && bean.staxpayname==null))
          return false;
        else if(this.staxpayname==null && bean.staxpayname==null){
        }
        else{
          if(!bean.staxpayname.equals(this.staxpayname))
               return false;
     }
      //compare field scorptype
      if((this.scorptype==null && bean.scorptype!=null) || (this.scorptype!=null && bean.scorptype==null))
          return false;
        else if(this.scorptype==null && bean.scorptype==null){
        }
        else{
          if(!bean.scorptype.equals(this.scorptype))
               return false;
     }
      //compare field slimitdate
      if((this.slimitdate==null && bean.slimitdate!=null) || (this.slimitdate!=null && bean.slimitdate==null))
          return false;
        else if(this.slimitdate==null && bean.slimitdate==null){
        }
        else{
          if(!bean.slimitdate.equals(this.slimitdate))
               return false;
     }
      //compare field staxtypecode
      if((this.staxtypecode==null && bean.staxtypecode!=null) || (this.staxtypecode!=null && bean.staxtypecode==null))
          return false;
        else if(this.staxtypecode==null && bean.staxtypecode==null){
        }
        else{
          if(!bean.staxtypecode.equals(this.staxtypecode))
               return false;
     }
      //compare field staxtypename
      if((this.staxtypename==null && bean.staxtypename!=null) || (this.staxtypename!=null && bean.staxtypename==null))
          return false;
        else if(this.staxtypename==null && bean.staxtypename==null){
        }
        else{
          if(!bean.staxtypename.equals(this.staxtypename))
               return false;
     }
      //compare field staxsubjectname
      if((this.staxsubjectname==null && bean.staxsubjectname!=null) || (this.staxsubjectname!=null && bean.staxsubjectname==null))
          return false;
        else if(this.staxsubjectname==null && bean.staxsubjectname==null){
        }
        else{
          if(!bean.staxsubjectname.equals(this.staxsubjectname))
               return false;
     }
      //compare field spaybnkno
      if((this.spaybnkno==null && bean.spaybnkno!=null) || (this.spaybnkno!=null && bean.spaybnkno==null))
          return false;
        else if(this.spaybnkno==null && bean.spaybnkno==null){
        }
        else{
          if(!bean.spaybnkno.equals(this.spaybnkno))
               return false;
     }
      //compare field spayacct
      if((this.spayacct==null && bean.spayacct!=null) || (this.spayacct!=null && bean.spayacct==null))
          return false;
        else if(this.spayacct==null && bean.spayacct==null){
        }
        else{
          if(!bean.spayacct.equals(this.spayacct))
               return false;
     }
      //compare field staxstartdate
      if((this.staxstartdate==null && bean.staxstartdate!=null) || (this.staxstartdate!=null && bean.staxstartdate==null))
          return false;
        else if(this.staxstartdate==null && bean.staxstartdate==null){
        }
        else{
          if(!bean.staxstartdate.equals(this.staxstartdate))
               return false;
     }
      //compare field staxenddate
      if((this.staxenddate==null && bean.staxenddate!=null) || (this.staxenddate!=null && bean.staxenddate==null))
          return false;
        else if(this.staxenddate==null && bean.staxenddate==null){
        }
        else{
          if(!bean.staxenddate.equals(this.staxenddate))
               return false;
     }
      //compare field staxnumber
      if((this.staxnumber==null && bean.staxnumber!=null) || (this.staxnumber!=null && bean.staxnumber==null))
          return false;
        else if(this.staxnumber==null && bean.staxnumber==null){
        }
        else{
          if(!bean.staxnumber.equals(this.staxnumber))
               return false;
     }
      //compare field ntaxamt
      if((this.ntaxamt==null && bean.ntaxamt!=null) || (this.ntaxamt!=null && bean.ntaxamt==null))
          return false;
        else if(this.ntaxamt==null && bean.ntaxamt==null){
        }
        else{
          if(!bean.ntaxamt.equals(this.ntaxamt))
               return false;
     }
      //compare field ntaxrate
      if((this.ntaxrate==null && bean.ntaxrate!=null) || (this.ntaxrate!=null && bean.ntaxrate==null))
          return false;
        else if(this.ntaxrate==null && bean.ntaxrate==null){
        }
        else{
          if(!bean.ntaxrate.equals(this.ntaxrate))
               return false;
     }
      //compare field ndiscounttaxamt
      if((this.ndiscounttaxamt==null && bean.ndiscounttaxamt!=null) || (this.ndiscounttaxamt!=null && bean.ndiscounttaxamt==null))
          return false;
        else if(this.ndiscounttaxamt==null && bean.ndiscounttaxamt==null){
        }
        else{
          if(!bean.ndiscounttaxamt.equals(this.ndiscounttaxamt))
               return false;
     }
      //compare field nfacttaxamt
      if((this.nfacttaxamt==null && bean.nfacttaxamt!=null) || (this.nfacttaxamt!=null && bean.nfacttaxamt==null))
          return false;
        else if(this.nfacttaxamt==null && bean.nfacttaxamt==null){
        }
        else{
          if(!bean.nfacttaxamt.equals(this.nfacttaxamt))
               return false;
     }
      //compare field ssourceflag
      if((this.ssourceflag==null && bean.ssourceflag!=null) || (this.ssourceflag!=null && bean.ssourceflag==null))
          return false;
        else if(this.ssourceflag==null && bean.ssourceflag==null){
        }
        else{
          if(!bean.ssourceflag.equals(this.ssourceflag))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.scommitdate!=null)
          _hash_ = _hash_ * 31+ this.scommitdate.hashCode() ;
        if(this.saccdate!=null)
          _hash_ = _hash_ * 31+ this.saccdate.hashCode() ;
        if(this.spackageno!=null)
          _hash_ = _hash_ * 31+ this.spackageno.hashCode() ;
        if(this.staxorgcode!=null)
          _hash_ = _hash_ * 31+ this.staxorgcode.hashCode() ;
        if(this.stbstaxorgcode!=null)
          _hash_ = _hash_ * 31+ this.stbstaxorgcode.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.srecvtrecode!=null)
          _hash_ = _hash_ * 31+ this.srecvtrecode.hashCode() ;
        if(this.srecvtrename!=null)
          _hash_ = _hash_ * 31+ this.srecvtrename.hashCode() ;
        if(this.sdealno!=null)
          _hash_ = _hash_ * 31+ this.sdealno.hashCode() ;
        if(this.strasrlno!=null)
          _hash_ = _hash_ * 31+ this.strasrlno.hashCode() ;
        if(this.nmoney!=null)
          _hash_ = _hash_ * 31+ this.nmoney.hashCode() ;
        if(this.staxticketno!=null)
          _hash_ = _hash_ * 31+ this.staxticketno.hashCode() ;
        if(this.sgenticketdate!=null)
          _hash_ = _hash_ * 31+ this.sgenticketdate.hashCode() ;
        if(this.sbudgettype!=null)
          _hash_ = _hash_ * 31+ this.sbudgettype.hashCode() ;
        if(this.strimflag!=null)
          _hash_ = _hash_ * 31+ this.strimflag.hashCode() ;
        if(this.sbudgetsubcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetsubcode.hashCode() ;
        if(this.sbudgetlevelcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetlevelcode.hashCode() ;
        if(this.sassitsign!=null)
          _hash_ = _hash_ * 31+ this.sassitsign.hashCode() ;
        if(this.stbsassitsign!=null)
          _hash_ = _hash_ * 31+ this.stbsassitsign.hashCode() ;
        if(this.sunitcode!=null)
          _hash_ = _hash_ * 31+ this.sunitcode.hashCode() ;
        if(this.spaybookkind!=null)
          _hash_ = _hash_ * 31+ this.spaybookkind.hashCode() ;
        if(this.sopenaccbankcode!=null)
          _hash_ = _hash_ * 31+ this.sopenaccbankcode.hashCode() ;
        if(this.sstatus!=null)
          _hash_ = _hash_ * 31+ this.sstatus.hashCode() ;
        if(this.susercode!=null)
          _hash_ = _hash_ * 31+ this.susercode.hashCode() ;
        if(this.sdemo!=null)
          _hash_ = _hash_ * 31+ this.sdemo.hashCode() ;
        if(this.staxpaycode!=null)
          _hash_ = _hash_ * 31+ this.staxpaycode.hashCode() ;
        if(this.staxpayname!=null)
          _hash_ = _hash_ * 31+ this.staxpayname.hashCode() ;
        if(this.scorptype!=null)
          _hash_ = _hash_ * 31+ this.scorptype.hashCode() ;
        if(this.slimitdate!=null)
          _hash_ = _hash_ * 31+ this.slimitdate.hashCode() ;
        if(this.staxtypecode!=null)
          _hash_ = _hash_ * 31+ this.staxtypecode.hashCode() ;
        if(this.staxtypename!=null)
          _hash_ = _hash_ * 31+ this.staxtypename.hashCode() ;
        if(this.staxsubjectname!=null)
          _hash_ = _hash_ * 31+ this.staxsubjectname.hashCode() ;
        if(this.spaybnkno!=null)
          _hash_ = _hash_ * 31+ this.spaybnkno.hashCode() ;
        if(this.spayacct!=null)
          _hash_ = _hash_ * 31+ this.spayacct.hashCode() ;
        if(this.staxstartdate!=null)
          _hash_ = _hash_ * 31+ this.staxstartdate.hashCode() ;
        if(this.staxenddate!=null)
          _hash_ = _hash_ * 31+ this.staxenddate.hashCode() ;
        if(this.staxnumber!=null)
          _hash_ = _hash_ * 31+ this.staxnumber.hashCode() ;
        if(this.ntaxamt!=null)
          _hash_ = _hash_ * 31+ this.ntaxamt.hashCode() ;
        if(this.ntaxrate!=null)
          _hash_ = _hash_ * 31+ this.ntaxrate.hashCode() ;
        if(this.ndiscounttaxamt!=null)
          _hash_ = _hash_ * 31+ this.ndiscounttaxamt.hashCode() ;
        if(this.nfacttaxamt!=null)
          _hash_ = _hash_ * 31+ this.nfacttaxamt.hashCode() ;
        if(this.ssourceflag!=null)
          _hash_ = _hash_ * 31+ this.ssourceflag.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvInfileDto bean = new TvInfileDto();

          bean.sorgcode = this.sorgcode;

          bean.scommitdate = this.scommitdate;

          if (this.saccdate != null)
            bean.saccdate = new String(this.saccdate);
          if (this.spackageno != null)
            bean.spackageno = new String(this.spackageno);
          if (this.staxorgcode != null)
            bean.staxorgcode = new String(this.staxorgcode);
          if (this.stbstaxorgcode != null)
            bean.stbstaxorgcode = new String(this.stbstaxorgcode);
          if (this.sfilename != null)
            bean.sfilename = new String(this.sfilename);
          if (this.srecvtrecode != null)
            bean.srecvtrecode = new String(this.srecvtrecode);
          if (this.srecvtrename != null)
            bean.srecvtrename = new String(this.srecvtrename);
          bean.sdealno = this.sdealno;

          if (this.strasrlno != null)
            bean.strasrlno = new String(this.strasrlno);
          if (this.nmoney != null)
            bean.nmoney = new BigDecimal(this.nmoney.toString());
          if (this.staxticketno != null)
            bean.staxticketno = new String(this.staxticketno);
          if (this.sgenticketdate != null)
            bean.sgenticketdate = new String(this.sgenticketdate);
          if (this.sbudgettype != null)
            bean.sbudgettype = new String(this.sbudgettype);
          if (this.strimflag != null)
            bean.strimflag = new String(this.strimflag);
          if (this.sbudgetsubcode != null)
            bean.sbudgetsubcode = new String(this.sbudgetsubcode);
          if (this.sbudgetlevelcode != null)
            bean.sbudgetlevelcode = new String(this.sbudgetlevelcode);
          if (this.sassitsign != null)
            bean.sassitsign = new String(this.sassitsign);
          if (this.stbsassitsign != null)
            bean.stbsassitsign = new String(this.stbsassitsign);
          if (this.sunitcode != null)
            bean.sunitcode = new String(this.sunitcode);
          if (this.spaybookkind != null)
            bean.spaybookkind = new String(this.spaybookkind);
          if (this.sopenaccbankcode != null)
            bean.sopenaccbankcode = new String(this.sopenaccbankcode);
          if (this.sstatus != null)
            bean.sstatus = new String(this.sstatus);
          if (this.susercode != null)
            bean.susercode = new String(this.susercode);
          if (this.sdemo != null)
            bean.sdemo = new String(this.sdemo);
          if (this.staxpaycode != null)
            bean.staxpaycode = new String(this.staxpaycode);
          if (this.staxpayname != null)
            bean.staxpayname = new String(this.staxpayname);
          if (this.scorptype != null)
            bean.scorptype = new String(this.scorptype);
          if (this.slimitdate != null)
            bean.slimitdate = new String(this.slimitdate);
          if (this.staxtypecode != null)
            bean.staxtypecode = new String(this.staxtypecode);
          if (this.staxtypename != null)
            bean.staxtypename = new String(this.staxtypename);
          if (this.staxsubjectname != null)
            bean.staxsubjectname = new String(this.staxsubjectname);
          if (this.spaybnkno != null)
            bean.spaybnkno = new String(this.spaybnkno);
          if (this.spayacct != null)
            bean.spayacct = new String(this.spayacct);
          if (this.staxstartdate != null)
            bean.staxstartdate = new String(this.staxstartdate);
          if (this.staxenddate != null)
            bean.staxenddate = new String(this.staxenddate);
          if (this.staxnumber != null)
            bean.staxnumber = new String(this.staxnumber);
          if (this.ntaxamt != null)
            bean.ntaxamt = new BigDecimal(this.ntaxamt.toString());
          if (this.ntaxrate != null)
            bean.ntaxrate = new BigDecimal(this.ntaxrate.toString());
          if (this.ndiscounttaxamt != null)
            bean.ndiscounttaxamt = new BigDecimal(this.ndiscounttaxamt.toString());
          if (this.nfacttaxamt != null)
            bean.nfacttaxamt = new BigDecimal(this.nfacttaxamt.toString());
          if (this.ssourceflag != null)
            bean.ssourceflag = new String(this.ssourceflag);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvInfileDto").append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[scommitdate]").append(" = ").append(scommitdate).append(sep);
        sb.append("[saccdate]").append(" = ").append(saccdate).append(sep);
        sb.append("[spackageno]").append(" = ").append(spackageno).append(sep);
        sb.append("[staxorgcode]").append(" = ").append(staxorgcode).append(sep);
        sb.append("[stbstaxorgcode]").append(" = ").append(stbstaxorgcode).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[srecvtrecode]").append(" = ").append(srecvtrecode).append(sep);
        sb.append("[srecvtrename]").append(" = ").append(srecvtrename).append(sep);
        sb.append("[sdealno]").append(" = ").append(sdealno).append(sep);
        sb.append("[strasrlno]").append(" = ").append(strasrlno).append(sep);
        sb.append("[nmoney]").append(" = ").append(nmoney).append(sep);
        sb.append("[staxticketno]").append(" = ").append(staxticketno).append(sep);
        sb.append("[sgenticketdate]").append(" = ").append(sgenticketdate).append(sep);
        sb.append("[sbudgettype]").append(" = ").append(sbudgettype).append(sep);
        sb.append("[strimflag]").append(" = ").append(strimflag).append(sep);
        sb.append("[sbudgetsubcode]").append(" = ").append(sbudgetsubcode).append(sep);
        sb.append("[sbudgetlevelcode]").append(" = ").append(sbudgetlevelcode).append(sep);
        sb.append("[sassitsign]").append(" = ").append(sassitsign).append(sep);
        sb.append("[stbsassitsign]").append(" = ").append(stbsassitsign).append(sep);
        sb.append("[sunitcode]").append(" = ").append(sunitcode).append(sep);
        sb.append("[spaybookkind]").append(" = ").append(spaybookkind).append(sep);
        sb.append("[sopenaccbankcode]").append(" = ").append(sopenaccbankcode).append(sep);
        sb.append("[sstatus]").append(" = ").append(sstatus).append(sep);
        sb.append("[susercode]").append(" = ").append(susercode).append(sep);
        sb.append("[sdemo]").append(" = ").append(sdemo).append(sep);
        sb.append("[staxpaycode]").append(" = ").append(staxpaycode).append(sep);
        sb.append("[staxpayname]").append(" = ").append(staxpayname).append(sep);
        sb.append("[scorptype]").append(" = ").append(scorptype).append(sep);
        sb.append("[slimitdate]").append(" = ").append(slimitdate).append(sep);
        sb.append("[staxtypecode]").append(" = ").append(staxtypecode).append(sep);
        sb.append("[staxtypename]").append(" = ").append(staxtypename).append(sep);
        sb.append("[staxsubjectname]").append(" = ").append(staxsubjectname).append(sep);
        sb.append("[spaybnkno]").append(" = ").append(spaybnkno).append(sep);
        sb.append("[spayacct]").append(" = ").append(spayacct).append(sep);
        sb.append("[staxstartdate]").append(" = ").append(staxstartdate).append(sep);
        sb.append("[staxenddate]").append(" = ").append(staxenddate).append(sep);
        sb.append("[staxnumber]").append(" = ").append(staxnumber).append(sep);
        sb.append("[ntaxamt]").append(" = ").append(ntaxamt).append(sep);
        sb.append("[ntaxrate]").append(" = ").append(ntaxrate).append(sep);
        sb.append("[ndiscounttaxamt]").append(" = ").append(ndiscounttaxamt).append(sep);
        sb.append("[nfacttaxamt]").append(" = ").append(nfacttaxamt).append(sep);
        sb.append("[ssourceflag]").append(" = ").append(ssourceflag).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_COMMITDATE
      if (this.getScommitdate()==null)
             sb.append("S_COMMITDATE不能为空; ");
      if (this.getScommitdate()!=null)
             if (this.getScommitdate().getBytes().length > 8)
                sb.append("S_COMMITDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_ACCDATE
      if (this.getSaccdate()==null)
             sb.append("S_ACCDATE不能为空; ");
      if (this.getSaccdate()!=null)
             if (this.getSaccdate().getBytes().length > 8)
                sb.append("S_ACCDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_PACKAGENO
      if (this.getSpackageno()==null)
             sb.append("S_PACKAGENO不能为空; ");
      if (this.getSpackageno()!=null)
             if (this.getSpackageno().getBytes().length > 8)
                sb.append("S_PACKAGENO宽度不能超过 "+8+"个字符; ");
    
    //check field S_TAXORGCODE
      if (this.getStaxorgcode()==null)
             sb.append("S_TAXORGCODE不能为空; ");
      if (this.getStaxorgcode()!=null)
             if (this.getStaxorgcode().getBytes().length > 30)
                sb.append("S_TAXORGCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_TBS_TAXORGCODE
      if (this.getStbstaxorgcode()!=null)
             if (this.getStbstaxorgcode().getBytes().length > 30)
                sb.append("S_TBS_TAXORGCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()==null)
             sb.append("S_FILENAME不能为空; ");
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_RECVTRECODE
      if (this.getSrecvtrecode()==null)
             sb.append("S_RECVTRECODE不能为空; ");
      if (this.getSrecvtrecode()!=null)
             if (this.getSrecvtrecode().getBytes().length > 10)
                sb.append("S_RECVTRECODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_RECVTRENAME
      if (this.getSrecvtrename()!=null)
             if (this.getSrecvtrename().getBytes().length > 100)
                sb.append("S_RECVTRENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_DEALNO
      if (this.getSdealno()==null)
             sb.append("S_DEALNO不能为空; ");
      if (this.getSdealno()!=null)
             if (this.getSdealno().getBytes().length > 8)
                sb.append("S_DEALNO宽度不能超过 "+8+"个字符; ");
    
    //check field S_TRASRLNO
      if (this.getStrasrlno()==null)
             sb.append("S_TRASRLNO不能为空; ");
      if (this.getStrasrlno()!=null)
             if (this.getStrasrlno().getBytes().length > 18)
                sb.append("S_TRASRLNO宽度不能超过 "+18+"个字符; ");
    
    //check field N_MONEY
      if (this.getNmoney()==null)
             sb.append("N_MONEY不能为空; ");
      
    //check field S_TAXTICKETNO
      if (this.getStaxticketno()==null)
             sb.append("S_TAXTICKETNO不能为空; ");
      if (this.getStaxticketno()!=null)
             if (this.getStaxticketno().getBytes().length > 30)
                sb.append("S_TAXTICKETNO宽度不能超过 "+30+"个字符; ");
    
    //check field S_GENTICKETDATE
      if (this.getSgenticketdate()==null)
             sb.append("S_GENTICKETDATE不能为空; ");
      if (this.getSgenticketdate()!=null)
             if (this.getSgenticketdate().getBytes().length > 8)
                sb.append("S_GENTICKETDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_BUDGETTYPE
      if (this.getSbudgettype()==null)
             sb.append("S_BUDGETTYPE不能为空; ");
      if (this.getSbudgettype()!=null)
             if (this.getSbudgettype().getBytes().length > 1)
                sb.append("S_BUDGETTYPE宽度不能超过 "+1+"个字符; ");
    
    //check field S_TRIMFLAG
      if (this.getStrimflag()==null)
             sb.append("S_TRIMFLAG不能为空; ");
      if (this.getStrimflag()!=null)
             if (this.getStrimflag().getBytes().length > 1)
                sb.append("S_TRIMFLAG宽度不能超过 "+1+"个字符; ");
    
    //check field S_BUDGETSUBCODE
      if (this.getSbudgetsubcode()==null)
             sb.append("S_BUDGETSUBCODE不能为空; ");
      if (this.getSbudgetsubcode()!=null)
             if (this.getSbudgetsubcode().getBytes().length > 30)
                sb.append("S_BUDGETSUBCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_BUDGETLEVELCODE
      if (this.getSbudgetlevelcode()==null)
             sb.append("S_BUDGETLEVELCODE不能为空; ");
      if (this.getSbudgetlevelcode()!=null)
             if (this.getSbudgetlevelcode().getBytes().length > 1)
                sb.append("S_BUDGETLEVELCODE宽度不能超过 "+1+"个字符; ");
    
    //check field S_ASSITSIGN
      if (this.getSassitsign()!=null)
             if (this.getSassitsign().getBytes().length > 35)
                sb.append("S_ASSITSIGN宽度不能超过 "+35+"个字符; ");
    
    //check field S_TBS_ASSITSIGN
      if (this.getStbsassitsign()!=null)
             if (this.getStbsassitsign().getBytes().length > 35)
                sb.append("S_TBS_ASSITSIGN宽度不能超过 "+35+"个字符; ");
    
    //check field S_UNITCODE
      if (this.getSunitcode()!=null)
             if (this.getSunitcode().getBytes().length > 15)
                sb.append("S_UNITCODE宽度不能超过 "+15+"个字符; ");
    
    //check field S_PAYBOOKKIND
      if (this.getSpaybookkind()!=null)
             if (this.getSpaybookkind().getBytes().length > 2)
                sb.append("S_PAYBOOKKIND宽度不能超过 "+2+"个字符; ");
    
    //check field S_OPENACCBANKCODE
      if (this.getSopenaccbankcode()!=null)
             if (this.getSopenaccbankcode().getBytes().length > 12)
                sb.append("S_OPENACCBANKCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_STATUS
      if (this.getSstatus()==null)
             sb.append("S_STATUS不能为空; ");
      if (this.getSstatus()!=null)
             if (this.getSstatus().getBytes().length > 5)
                sb.append("S_STATUS宽度不能超过 "+5+"个字符; ");
    
    //check field S_USERCODE
      if (this.getSusercode()==null)
             sb.append("S_USERCODE不能为空; ");
      if (this.getSusercode()!=null)
             if (this.getSusercode().getBytes().length > 30)
                sb.append("S_USERCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_DEMO
      if (this.getSdemo()!=null)
             if (this.getSdemo().getBytes().length > 100)
                sb.append("S_DEMO宽度不能超过 "+100+"个字符; ");
    
    //check field S_TAXPAYCODE
      if (this.getStaxpaycode()!=null)
             if (this.getStaxpaycode().getBytes().length > 20)
                sb.append("S_TAXPAYCODE宽度不能超过 "+20+"个字符; ");
    
    //check field S_TAXPAYNAME
      if (this.getStaxpayname()!=null)
             if (this.getStaxpayname().getBytes().length > 200)
                sb.append("S_TAXPAYNAME宽度不能超过 "+200+"个字符; ");
    
    //check field S_CORPTYPE
      if (this.getScorptype()!=null)
             if (this.getScorptype().getBytes().length > 12)
                sb.append("S_CORPTYPE宽度不能超过 "+12+"个字符; ");
    
    //check field S_LIMITDATE
      if (this.getSlimitdate()!=null)
             if (this.getSlimitdate().getBytes().length > 8)
                sb.append("S_LIMITDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_TAXTYPECODE
      if (this.getStaxtypecode()!=null)
             if (this.getStaxtypecode().getBytes().length > 10)
                sb.append("S_TAXTYPECODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_TAXTYPENAME
      if (this.getStaxtypename()!=null)
             if (this.getStaxtypename().getBytes().length > 60)
                sb.append("S_TAXTYPENAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_TAXSUBJECTNAME
      if (this.getStaxsubjectname()!=null)
             if (this.getStaxsubjectname().getBytes().length > 60)
                sb.append("S_TAXSUBJECTNAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_PAYBNKNO
      if (this.getSpaybnkno()!=null)
             if (this.getSpaybnkno().getBytes().length > 12)
                sb.append("S_PAYBNKNO宽度不能超过 "+12+"个字符; ");
    
    //check field S_PAYACCT
      if (this.getSpayacct()!=null)
             if (this.getSpayacct().getBytes().length > 32)
                sb.append("S_PAYACCT宽度不能超过 "+32+"个字符; ");
    
    //check field S_TAXSTARTDATE
      if (this.getStaxstartdate()!=null)
             if (this.getStaxstartdate().getBytes().length > 8)
                sb.append("S_TAXSTARTDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_TAXENDDATE
      if (this.getStaxenddate()!=null)
             if (this.getStaxenddate().getBytes().length > 8)
                sb.append("S_TAXENDDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_TAXNUMBER
      if (this.getStaxnumber()!=null)
             if (this.getStaxnumber().getBytes().length > 5)
                sb.append("S_TAXNUMBER宽度不能超过 "+5+"个字符; ");
    
    //check field N_TAXAMT
      
    //check field N_TAXRATE
      
    //check field N_DISCOUNTTAXAMT
      
    //check field N_FACTTAXAMT
      
    //check field S_SOURCEFLAG
      if (this.getSsourceflag()!=null)
             if (this.getSsourceflag().getBytes().length > 1)
                sb.append("S_SOURCEFLAG宽度不能超过 "+1+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_COMMITDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_COMMITDATE")) {
               if (this.getScommitdate()==null)
                    sb.append("S_COMMITDATE 不能为空; ");
               if (this.getScommitdate()!=null)
                    if (this.getScommitdate().getBytes().length > 8)
                        sb.append("S_COMMITDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_ACCDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ACCDATE")) {
               if (this.getSaccdate()==null)
                    sb.append("S_ACCDATE 不能为空; ");
               if (this.getSaccdate()!=null)
                    if (this.getSaccdate().getBytes().length > 8)
                        sb.append("S_ACCDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_PACKAGENO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PACKAGENO")) {
               if (this.getSpackageno()==null)
                    sb.append("S_PACKAGENO 不能为空; ");
               if (this.getSpackageno()!=null)
                    if (this.getSpackageno().getBytes().length > 8)
                        sb.append("S_PACKAGENO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TAXORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXORGCODE")) {
               if (this.getStaxorgcode()==null)
                    sb.append("S_TAXORGCODE 不能为空; ");
               if (this.getStaxorgcode()!=null)
                    if (this.getStaxorgcode().getBytes().length > 30)
                        sb.append("S_TAXORGCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_TBS_TAXORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TBS_TAXORGCODE")) {
                 if (this.getStbstaxorgcode()!=null)
                    if (this.getStbstaxorgcode().getBytes().length > 30)
                        sb.append("S_TBS_TAXORGCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
               if (this.getSfilename()==null)
                    sb.append("S_FILENAME 不能为空; ");
               if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_RECVTRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RECVTRECODE")) {
               if (this.getSrecvtrecode()==null)
                    sb.append("S_RECVTRECODE 不能为空; ");
               if (this.getSrecvtrecode()!=null)
                    if (this.getSrecvtrecode().getBytes().length > 10)
                        sb.append("S_RECVTRECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_RECVTRENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RECVTRENAME")) {
                 if (this.getSrecvtrename()!=null)
                    if (this.getSrecvtrename().getBytes().length > 100)
                        sb.append("S_RECVTRENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_DEALNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEALNO")) {
               if (this.getSdealno()==null)
                    sb.append("S_DEALNO 不能为空; ");
               if (this.getSdealno()!=null)
                    if (this.getSdealno().getBytes().length > 8)
                        sb.append("S_DEALNO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TRASRLNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRASRLNO")) {
               if (this.getStrasrlno()==null)
                    sb.append("S_TRASRLNO 不能为空; ");
               if (this.getStrasrlno()!=null)
                    if (this.getStrasrlno().getBytes().length > 18)
                        sb.append("S_TRASRLNO 宽度不能超过 "+18+"个字符");
             break;
         }
  }
    
    //check field N_MONEY
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_MONEY")) {
               if (this.getNmoney()==null)
                    sb.append("N_MONEY 不能为空; ");
               break;
         }
  }
    
    //check field S_TAXTICKETNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTICKETNO")) {
               if (this.getStaxticketno()==null)
                    sb.append("S_TAXTICKETNO 不能为空; ");
               if (this.getStaxticketno()!=null)
                    if (this.getStaxticketno().getBytes().length > 30)
                        sb.append("S_TAXTICKETNO 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_GENTICKETDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_GENTICKETDATE")) {
               if (this.getSgenticketdate()==null)
                    sb.append("S_GENTICKETDATE 不能为空; ");
               if (this.getSgenticketdate()!=null)
                    if (this.getSgenticketdate().getBytes().length > 8)
                        sb.append("S_GENTICKETDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETTYPE")) {
               if (this.getSbudgettype()==null)
                    sb.append("S_BUDGETTYPE 不能为空; ");
               if (this.getSbudgettype()!=null)
                    if (this.getSbudgettype().getBytes().length > 1)
                        sb.append("S_BUDGETTYPE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_TRIMFLAG
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRIMFLAG")) {
               if (this.getStrimflag()==null)
                    sb.append("S_TRIMFLAG 不能为空; ");
               if (this.getStrimflag()!=null)
                    if (this.getStrimflag().getBytes().length > 1)
                        sb.append("S_TRIMFLAG 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETSUBCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETSUBCODE")) {
               if (this.getSbudgetsubcode()==null)
                    sb.append("S_BUDGETSUBCODE 不能为空; ");
               if (this.getSbudgetsubcode()!=null)
                    if (this.getSbudgetsubcode().getBytes().length > 30)
                        sb.append("S_BUDGETSUBCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETLEVELCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETLEVELCODE")) {
               if (this.getSbudgetlevelcode()==null)
                    sb.append("S_BUDGETLEVELCODE 不能为空; ");
               if (this.getSbudgetlevelcode()!=null)
                    if (this.getSbudgetlevelcode().getBytes().length > 1)
                        sb.append("S_BUDGETLEVELCODE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_ASSITSIGN
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ASSITSIGN")) {
                 if (this.getSassitsign()!=null)
                    if (this.getSassitsign().getBytes().length > 35)
                        sb.append("S_ASSITSIGN 宽度不能超过 "+35+"个字符");
             break;
         }
  }
    
    //check field S_TBS_ASSITSIGN
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TBS_ASSITSIGN")) {
                 if (this.getStbsassitsign()!=null)
                    if (this.getStbsassitsign().getBytes().length > 35)
                        sb.append("S_TBS_ASSITSIGN 宽度不能超过 "+35+"个字符");
             break;
         }
  }
    
    //check field S_UNITCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_UNITCODE")) {
                 if (this.getSunitcode()!=null)
                    if (this.getSunitcode().getBytes().length > 15)
                        sb.append("S_UNITCODE 宽度不能超过 "+15+"个字符");
             break;
         }
  }
    
    //check field S_PAYBOOKKIND
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBOOKKIND")) {
                 if (this.getSpaybookkind()!=null)
                    if (this.getSpaybookkind().getBytes().length > 2)
                        sb.append("S_PAYBOOKKIND 宽度不能超过 "+2+"个字符");
             break;
         }
  }
    
    //check field S_OPENACCBANKCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_OPENACCBANKCODE")) {
                 if (this.getSopenaccbankcode()!=null)
                    if (this.getSopenaccbankcode().getBytes().length > 12)
                        sb.append("S_OPENACCBANKCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_STATUS
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_STATUS")) {
               if (this.getSstatus()==null)
                    sb.append("S_STATUS 不能为空; ");
               if (this.getSstatus()!=null)
                    if (this.getSstatus().getBytes().length > 5)
                        sb.append("S_STATUS 宽度不能超过 "+5+"个字符");
             break;
         }
  }
    
    //check field S_USERCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_USERCODE")) {
               if (this.getSusercode()==null)
                    sb.append("S_USERCODE 不能为空; ");
               if (this.getSusercode()!=null)
                    if (this.getSusercode().getBytes().length > 30)
                        sb.append("S_USERCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_DEMO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEMO")) {
                 if (this.getSdemo()!=null)
                    if (this.getSdemo().getBytes().length > 100)
                        sb.append("S_DEMO 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_TAXPAYCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXPAYCODE")) {
                 if (this.getStaxpaycode()!=null)
                    if (this.getStaxpaycode().getBytes().length > 20)
                        sb.append("S_TAXPAYCODE 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_TAXPAYNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXPAYNAME")) {
                 if (this.getStaxpayname()!=null)
                    if (this.getStaxpayname().getBytes().length > 200)
                        sb.append("S_TAXPAYNAME 宽度不能超过 "+200+"个字符");
             break;
         }
  }
    
    //check field S_CORPTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CORPTYPE")) {
                 if (this.getScorptype()!=null)
                    if (this.getScorptype().getBytes().length > 12)
                        sb.append("S_CORPTYPE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_LIMITDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_LIMITDATE")) {
                 if (this.getSlimitdate()!=null)
                    if (this.getSlimitdate().getBytes().length > 8)
                        sb.append("S_LIMITDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TAXTYPECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTYPECODE")) {
                 if (this.getStaxtypecode()!=null)
                    if (this.getStaxtypecode().getBytes().length > 10)
                        sb.append("S_TAXTYPECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_TAXTYPENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTYPENAME")) {
                 if (this.getStaxtypename()!=null)
                    if (this.getStaxtypename().getBytes().length > 60)
                        sb.append("S_TAXTYPENAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_TAXSUBJECTNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXSUBJECTNAME")) {
                 if (this.getStaxsubjectname()!=null)
                    if (this.getStaxsubjectname().getBytes().length > 60)
                        sb.append("S_TAXSUBJECTNAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PAYBNKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBNKNO")) {
                 if (this.getSpaybnkno()!=null)
                    if (this.getSpaybnkno().getBytes().length > 12)
                        sb.append("S_PAYBNKNO 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_PAYACCT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYACCT")) {
                 if (this.getSpayacct()!=null)
                    if (this.getSpayacct().getBytes().length > 32)
                        sb.append("S_PAYACCT 宽度不能超过 "+32+"个字符");
             break;
         }
  }
    
    //check field S_TAXSTARTDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXSTARTDATE")) {
                 if (this.getStaxstartdate()!=null)
                    if (this.getStaxstartdate().getBytes().length > 8)
                        sb.append("S_TAXSTARTDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TAXENDDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXENDDATE")) {
                 if (this.getStaxenddate()!=null)
                    if (this.getStaxenddate().getBytes().length > 8)
                        sb.append("S_TAXENDDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_TAXNUMBER
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXNUMBER")) {
                 if (this.getStaxnumber()!=null)
                    if (this.getStaxnumber().getBytes().length > 5)
                        sb.append("S_TAXNUMBER 宽度不能超过 "+5+"个字符");
             break;
         }
  }
    
    //check field N_TAXAMT
          
    //check field N_TAXRATE
          
    //check field N_DISCOUNTTAXAMT
          
    //check field N_FACTTAXAMT
          
    //check field S_SOURCEFLAG
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SOURCEFLAG")) {
                 if (this.getSsourceflag()!=null)
                    if (this.getSsourceflag().getBytes().length > 1)
                        sb.append("S_SOURCEFLAG 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TvInfilePK pk = new TvInfilePK();
      pk.setSorgcode(getSorgcode());
      pk.setScommitdate(getScommitdate());
      pk.setSdealno(getSdealno());
      return pk;
    };
}
