    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvPayoutmsgsubPK;
/**
 * <p>Title: DTO of table: TV_PAYOUTMSGSUB</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:03 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvPayoutmsgsubDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_BIZNO VARCHAR , PK   , NOT NULL       */
    protected String sbizno;
    /**
    *  S_SEQNO INTEGER , PK   , NOT NULL       */
    protected Integer sseqno;
    /**
    *  S_ACCDATE CHARACTER   , NOT NULL       */
    protected String saccdate;
    /**
    *  S_ECNOMICSUBJECTCODE VARCHAR         */
    protected String secnomicsubjectcode;
    /**
    *  S_BUDGETPRJCODE VARCHAR         */
    protected String sbudgetprjcode;
    /**
    *  N_MONEY DECIMAL   , NOT NULL       */
    protected BigDecimal nmoney;
    /**
    *  S_FUNSUBJECTCODE VARCHAR   , NOT NULL       */
    protected String sfunsubjectcode;
    /**
    *  TS_SYSUPDATE TIMESTAMP   , NOT NULL       */
    protected Timestamp tssysupdate;
    /**
    *  S_TAXTICKETNO VARCHAR         */
    protected String staxticketno;
    /**
    *  S_BGTTYPECODE VARCHAR         */
    protected String sbgttypecode;
    /**
    *  S_BGTTYPENAME VARCHAR         */
    protected String sbgttypename;
    /**
    *  S_PROCATCODE VARCHAR         */
    protected String sprocatcode;
    /**
    *  S_PROCATNAME VARCHAR         */
    protected String sprocatname;
    /**
    *  S_AGENCYCODE VARCHAR         */
    protected String sagencycode;
    /**
    *  S_AGENCYNAME VARCHAR         */
    protected String sagencyname;
    /**
    *  S_EXPFUNCNAME VARCHAR         */
    protected String sexpfuncname;
    /**
    *  S_EXPFUNCCODE1 VARCHAR         */
    protected String sexpfunccode1;
    /**
    *  S_EXPFUNCNAME1 VARCHAR         */
    protected String sexpfuncname1;
    /**
    *  S_EXPFUNCCODE2 VARCHAR         */
    protected String sexpfunccode2;
    /**
    *  S_EXPFUNCNAME2 VARCHAR         */
    protected String sexpfuncname2;
    /**
    *  S_EXPFUNCCODE3 VARCHAR         */
    protected String sexpfunccode3;
    /**
    *  S_EXPFUNCNAME3 VARCHAR         */
    protected String sexpfuncname3;
    /**
    *  S_EXPECOCODE VARCHAR         */
    protected String sexpecocode;
    /**
    *  S_EXPECONAME VARCHAR         */
    protected String sexpeconame;
    /**
    *  S_EXPECOCODE1 VARCHAR         */
    protected String sexpecocode1;
    /**
    *  S_EXPECONAME1 VARCHAR         */
    protected String sexpeconame1;
    /**
    *  S_EXPECOCODE2 VARCHAR         */
    protected String sexpecocode2;
    /**
    *  S_EXPECONAME2 VARCHAR         */
    protected String sexpeconame2;
    /**
    *  S_HOLD1 VARCHAR         */
    protected String shold1;
    /**
    *  S_HOLD2 VARCHAR         */
    protected String shold2;
    /**
    *  S_HOLD3 VARCHAR         */
    protected String shold3;
    /**
    *  S_HOLD4 VARCHAR         */
    protected String shold4;
    /**
    * 收款人账号 S_PAYEEACCTNO VARCHAR         */
    protected String spayeeacctno;
    /**
    * 收款人名称 S_PAYEEACCTNAME VARCHAR         */
    protected String spayeeacctname;
    /**
    * 收款人银行 S_PAYEEACCTBANKNAME VARCHAR         */
    protected String spayeeacctbankname;
    /**
    * 用途编码 S_PAYSUMMARYCODE VARCHAR         */
    protected String spaysummarycode;
    /**
    * 用途名称 S_PAYSUMMARYNAME VARCHAR         */
    protected String spaysummaryname;
    /**
    * 实际支付金额,人民银行在回单中补录 S_XPAYAMT DECIMAL         */
    protected BigDecimal sxpayamt;
    /**
    * 人民银行处理日期，人民银行在回单中补录 S_XPAYDATE VARCHAR         */
    protected String sxpaydate;
    /**
    * 银行交易流水号,人民银行在回单中补录 S_XAGENTBUSINESSNO VARCHAR         */
    protected String sxagentbusinessno;
    /**
    * 拨款凭证明细ID S_ID VARCHAR         */
    protected String sid;
    /**
    * 失败原因 S_XADDWORD VARCHAR         */
    protected String sxaddword;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSbizno()
    {
        return sbizno;
    }
     /**
     *   Setter S_BIZNO, PK , NOT NULL        * */
    public void setSbizno(String _sbizno) {
        this.sbizno = _sbizno;
    }


    public Integer getSseqno()
    {
        return sseqno;
    }
     /**
     *   Setter S_SEQNO, PK , NOT NULL        * */
    public void setSseqno(Integer _sseqno) {
        this.sseqno = _sseqno;
    }


    public String getSaccdate()
    {
        return saccdate;
    }
     /**
     *   Setter S_ACCDATE , NOT NULL        * */
    public void setSaccdate(String _saccdate) {
        this.saccdate = _saccdate;
    }


    public String getSecnomicsubjectcode()
    {
        return secnomicsubjectcode;
    }
     /**
     *   Setter S_ECNOMICSUBJECTCODE        * */
    public void setSecnomicsubjectcode(String _secnomicsubjectcode) {
        this.secnomicsubjectcode = _secnomicsubjectcode;
    }


    public String getSbudgetprjcode()
    {
        return sbudgetprjcode;
    }
     /**
     *   Setter S_BUDGETPRJCODE        * */
    public void setSbudgetprjcode(String _sbudgetprjcode) {
        this.sbudgetprjcode = _sbudgetprjcode;
    }


    public BigDecimal getNmoney()
    {
        return nmoney;
    }
     /**
     *   Setter N_MONEY , NOT NULL        * */
    public void setNmoney(BigDecimal _nmoney) {
        this.nmoney = _nmoney;
    }


    public String getSfunsubjectcode()
    {
        return sfunsubjectcode;
    }
     /**
     *   Setter S_FUNSUBJECTCODE , NOT NULL        * */
    public void setSfunsubjectcode(String _sfunsubjectcode) {
        this.sfunsubjectcode = _sfunsubjectcode;
    }


    public Timestamp getTssysupdate()
    {
        return tssysupdate;
    }
     /**
     *   Setter TS_SYSUPDATE , NOT NULL        * */
    public void setTssysupdate(Timestamp _tssysupdate) {
        this.tssysupdate = _tssysupdate;
    }


    public String getStaxticketno()
    {
        return staxticketno;
    }
     /**
     *   Setter S_TAXTICKETNO        * */
    public void setStaxticketno(String _staxticketno) {
        this.staxticketno = _staxticketno;
    }


    public String getSbgttypecode()
    {
        return sbgttypecode;
    }
     /**
     *   Setter S_BGTTYPECODE        * */
    public void setSbgttypecode(String _sbgttypecode) {
        this.sbgttypecode = _sbgttypecode;
    }


    public String getSbgttypename()
    {
        return sbgttypename;
    }
     /**
     *   Setter S_BGTTYPENAME        * */
    public void setSbgttypename(String _sbgttypename) {
        this.sbgttypename = _sbgttypename;
    }


    public String getSprocatcode()
    {
        return sprocatcode;
    }
     /**
     *   Setter S_PROCATCODE        * */
    public void setSprocatcode(String _sprocatcode) {
        this.sprocatcode = _sprocatcode;
    }


    public String getSprocatname()
    {
        return sprocatname;
    }
     /**
     *   Setter S_PROCATNAME        * */
    public void setSprocatname(String _sprocatname) {
        this.sprocatname = _sprocatname;
    }


    public String getSagencycode()
    {
        return sagencycode;
    }
     /**
     *   Setter S_AGENCYCODE        * */
    public void setSagencycode(String _sagencycode) {
        this.sagencycode = _sagencycode;
    }


    public String getSagencyname()
    {
        return sagencyname;
    }
     /**
     *   Setter S_AGENCYNAME        * */
    public void setSagencyname(String _sagencyname) {
        this.sagencyname = _sagencyname;
    }


    public String getSexpfuncname()
    {
        return sexpfuncname;
    }
     /**
     *   Setter S_EXPFUNCNAME        * */
    public void setSexpfuncname(String _sexpfuncname) {
        this.sexpfuncname = _sexpfuncname;
    }


    public String getSexpfunccode1()
    {
        return sexpfunccode1;
    }
     /**
     *   Setter S_EXPFUNCCODE1        * */
    public void setSexpfunccode1(String _sexpfunccode1) {
        this.sexpfunccode1 = _sexpfunccode1;
    }


    public String getSexpfuncname1()
    {
        return sexpfuncname1;
    }
     /**
     *   Setter S_EXPFUNCNAME1        * */
    public void setSexpfuncname1(String _sexpfuncname1) {
        this.sexpfuncname1 = _sexpfuncname1;
    }


    public String getSexpfunccode2()
    {
        return sexpfunccode2;
    }
     /**
     *   Setter S_EXPFUNCCODE2        * */
    public void setSexpfunccode2(String _sexpfunccode2) {
        this.sexpfunccode2 = _sexpfunccode2;
    }


    public String getSexpfuncname2()
    {
        return sexpfuncname2;
    }
     /**
     *   Setter S_EXPFUNCNAME2        * */
    public void setSexpfuncname2(String _sexpfuncname2) {
        this.sexpfuncname2 = _sexpfuncname2;
    }


    public String getSexpfunccode3()
    {
        return sexpfunccode3;
    }
     /**
     *   Setter S_EXPFUNCCODE3        * */
    public void setSexpfunccode3(String _sexpfunccode3) {
        this.sexpfunccode3 = _sexpfunccode3;
    }


    public String getSexpfuncname3()
    {
        return sexpfuncname3;
    }
     /**
     *   Setter S_EXPFUNCNAME3        * */
    public void setSexpfuncname3(String _sexpfuncname3) {
        this.sexpfuncname3 = _sexpfuncname3;
    }


    public String getSexpecocode()
    {
        return sexpecocode;
    }
     /**
     *   Setter S_EXPECOCODE        * */
    public void setSexpecocode(String _sexpecocode) {
        this.sexpecocode = _sexpecocode;
    }


    public String getSexpeconame()
    {
        return sexpeconame;
    }
     /**
     *   Setter S_EXPECONAME        * */
    public void setSexpeconame(String _sexpeconame) {
        this.sexpeconame = _sexpeconame;
    }


    public String getSexpecocode1()
    {
        return sexpecocode1;
    }
     /**
     *   Setter S_EXPECOCODE1        * */
    public void setSexpecocode1(String _sexpecocode1) {
        this.sexpecocode1 = _sexpecocode1;
    }


    public String getSexpeconame1()
    {
        return sexpeconame1;
    }
     /**
     *   Setter S_EXPECONAME1        * */
    public void setSexpeconame1(String _sexpeconame1) {
        this.sexpeconame1 = _sexpeconame1;
    }


    public String getSexpecocode2()
    {
        return sexpecocode2;
    }
     /**
     *   Setter S_EXPECOCODE2        * */
    public void setSexpecocode2(String _sexpecocode2) {
        this.sexpecocode2 = _sexpecocode2;
    }


    public String getSexpeconame2()
    {
        return sexpeconame2;
    }
     /**
     *   Setter S_EXPECONAME2        * */
    public void setSexpeconame2(String _sexpeconame2) {
        this.sexpeconame2 = _sexpeconame2;
    }


    public String getShold1()
    {
        return shold1;
    }
     /**
     *   Setter S_HOLD1        * */
    public void setShold1(String _shold1) {
        this.shold1 = _shold1;
    }


    public String getShold2()
    {
        return shold2;
    }
     /**
     *   Setter S_HOLD2        * */
    public void setShold2(String _shold2) {
        this.shold2 = _shold2;
    }


    public String getShold3()
    {
        return shold3;
    }
     /**
     *   Setter S_HOLD3        * */
    public void setShold3(String _shold3) {
        this.shold3 = _shold3;
    }


    public String getShold4()
    {
        return shold4;
    }
     /**
     *   Setter S_HOLD4        * */
    public void setShold4(String _shold4) {
        this.shold4 = _shold4;
    }


    public String getSpayeeacctno()
    {
        return spayeeacctno;
    }
     /**
     *  收款人账号 Setter S_PAYEEACCTNO        * */
    public void setSpayeeacctno(String _spayeeacctno) {
        this.spayeeacctno = _spayeeacctno;
    }


    public String getSpayeeacctname()
    {
        return spayeeacctname;
    }
     /**
     *  收款人名称 Setter S_PAYEEACCTNAME        * */
    public void setSpayeeacctname(String _spayeeacctname) {
        this.spayeeacctname = _spayeeacctname;
    }


    public String getSpayeeacctbankname()
    {
        return spayeeacctbankname;
    }
     /**
     *  收款人银行 Setter S_PAYEEACCTBANKNAME        * */
    public void setSpayeeacctbankname(String _spayeeacctbankname) {
        this.spayeeacctbankname = _spayeeacctbankname;
    }


    public String getSpaysummarycode()
    {
        return spaysummarycode;
    }
     /**
     *  用途编码 Setter S_PAYSUMMARYCODE        * */
    public void setSpaysummarycode(String _spaysummarycode) {
        this.spaysummarycode = _spaysummarycode;
    }


    public String getSpaysummaryname()
    {
        return spaysummaryname;
    }
     /**
     *  用途名称 Setter S_PAYSUMMARYNAME        * */
    public void setSpaysummaryname(String _spaysummaryname) {
        this.spaysummaryname = _spaysummaryname;
    }


    public BigDecimal getSxpayamt()
    {
        return sxpayamt;
    }
     /**
     *  实际支付金额,人民银行在回单中补录 Setter S_XPAYAMT        * */
    public void setSxpayamt(BigDecimal _sxpayamt) {
        this.sxpayamt = _sxpayamt;
    }


    public String getSxpaydate()
    {
        return sxpaydate;
    }
     /**
     *  人民银行处理日期，人民银行在回单中补录 Setter S_XPAYDATE        * */
    public void setSxpaydate(String _sxpaydate) {
        this.sxpaydate = _sxpaydate;
    }


    public String getSxagentbusinessno()
    {
        return sxagentbusinessno;
    }
     /**
     *  银行交易流水号,人民银行在回单中补录 Setter S_XAGENTBUSINESSNO        * */
    public void setSxagentbusinessno(String _sxagentbusinessno) {
        this.sxagentbusinessno = _sxagentbusinessno;
    }


    public String getSid()
    {
        return sid;
    }
     /**
     *  拨款凭证明细ID Setter S_ID        * */
    public void setSid(String _sid) {
        this.sid = _sid;
    }


    public String getSxaddword()
    {
        return sxaddword;
    }
     /**
     *  失败原因 Setter S_XADDWORD        * */
    public void setSxaddword(String _sxaddword) {
        this.sxaddword = _sxaddword;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_BIZNO, PK , NOT NULL       * */
    public static String  columnSbizno()
    {
        return "S_BIZNO";
    }
   
    /**
    *   Getter S_SEQNO, PK , NOT NULL       * */
    public static String  columnSseqno()
    {
        return "S_SEQNO";
    }
   
    /**
    *   Getter S_ACCDATE , NOT NULL       * */
    public static String  columnSaccdate()
    {
        return "S_ACCDATE";
    }
   
    /**
    *   Getter S_ECNOMICSUBJECTCODE       * */
    public static String  columnSecnomicsubjectcode()
    {
        return "S_ECNOMICSUBJECTCODE";
    }
   
    /**
    *   Getter S_BUDGETPRJCODE       * */
    public static String  columnSbudgetprjcode()
    {
        return "S_BUDGETPRJCODE";
    }
   
    /**
    *   Getter N_MONEY , NOT NULL       * */
    public static String  columnNmoney()
    {
        return "N_MONEY";
    }
   
    /**
    *   Getter S_FUNSUBJECTCODE , NOT NULL       * */
    public static String  columnSfunsubjectcode()
    {
        return "S_FUNSUBJECTCODE";
    }
   
    /**
    *   Getter TS_SYSUPDATE , NOT NULL       * */
    public static String  columnTssysupdate()
    {
        return "TS_SYSUPDATE";
    }
   
    /**
    *   Getter S_TAXTICKETNO       * */
    public static String  columnStaxticketno()
    {
        return "S_TAXTICKETNO";
    }
   
    /**
    *   Getter S_BGTTYPECODE       * */
    public static String  columnSbgttypecode()
    {
        return "S_BGTTYPECODE";
    }
   
    /**
    *   Getter S_BGTTYPENAME       * */
    public static String  columnSbgttypename()
    {
        return "S_BGTTYPENAME";
    }
   
    /**
    *   Getter S_PROCATCODE       * */
    public static String  columnSprocatcode()
    {
        return "S_PROCATCODE";
    }
   
    /**
    *   Getter S_PROCATNAME       * */
    public static String  columnSprocatname()
    {
        return "S_PROCATNAME";
    }
   
    /**
    *   Getter S_AGENCYCODE       * */
    public static String  columnSagencycode()
    {
        return "S_AGENCYCODE";
    }
   
    /**
    *   Getter S_AGENCYNAME       * */
    public static String  columnSagencyname()
    {
        return "S_AGENCYNAME";
    }
   
    /**
    *   Getter S_EXPFUNCNAME       * */
    public static String  columnSexpfuncname()
    {
        return "S_EXPFUNCNAME";
    }
   
    /**
    *   Getter S_EXPFUNCCODE1       * */
    public static String  columnSexpfunccode1()
    {
        return "S_EXPFUNCCODE1";
    }
   
    /**
    *   Getter S_EXPFUNCNAME1       * */
    public static String  columnSexpfuncname1()
    {
        return "S_EXPFUNCNAME1";
    }
   
    /**
    *   Getter S_EXPFUNCCODE2       * */
    public static String  columnSexpfunccode2()
    {
        return "S_EXPFUNCCODE2";
    }
   
    /**
    *   Getter S_EXPFUNCNAME2       * */
    public static String  columnSexpfuncname2()
    {
        return "S_EXPFUNCNAME2";
    }
   
    /**
    *   Getter S_EXPFUNCCODE3       * */
    public static String  columnSexpfunccode3()
    {
        return "S_EXPFUNCCODE3";
    }
   
    /**
    *   Getter S_EXPFUNCNAME3       * */
    public static String  columnSexpfuncname3()
    {
        return "S_EXPFUNCNAME3";
    }
   
    /**
    *   Getter S_EXPECOCODE       * */
    public static String  columnSexpecocode()
    {
        return "S_EXPECOCODE";
    }
   
    /**
    *   Getter S_EXPECONAME       * */
    public static String  columnSexpeconame()
    {
        return "S_EXPECONAME";
    }
   
    /**
    *   Getter S_EXPECOCODE1       * */
    public static String  columnSexpecocode1()
    {
        return "S_EXPECOCODE1";
    }
   
    /**
    *   Getter S_EXPECONAME1       * */
    public static String  columnSexpeconame1()
    {
        return "S_EXPECONAME1";
    }
   
    /**
    *   Getter S_EXPECOCODE2       * */
    public static String  columnSexpecocode2()
    {
        return "S_EXPECOCODE2";
    }
   
    /**
    *   Getter S_EXPECONAME2       * */
    public static String  columnSexpeconame2()
    {
        return "S_EXPECONAME2";
    }
   
    /**
    *   Getter S_HOLD1       * */
    public static String  columnShold1()
    {
        return "S_HOLD1";
    }
   
    /**
    *   Getter S_HOLD2       * */
    public static String  columnShold2()
    {
        return "S_HOLD2";
    }
   
    /**
    *   Getter S_HOLD3       * */
    public static String  columnShold3()
    {
        return "S_HOLD3";
    }
   
    /**
    *   Getter S_HOLD4       * */
    public static String  columnShold4()
    {
        return "S_HOLD4";
    }
   
    /**
    *  收款人账号 Getter S_PAYEEACCTNO       * */
    public static String  columnSpayeeacctno()
    {
        return "S_PAYEEACCTNO";
    }
   
    /**
    *  收款人名称 Getter S_PAYEEACCTNAME       * */
    public static String  columnSpayeeacctname()
    {
        return "S_PAYEEACCTNAME";
    }
   
    /**
    *  收款人银行 Getter S_PAYEEACCTBANKNAME       * */
    public static String  columnSpayeeacctbankname()
    {
        return "S_PAYEEACCTBANKNAME";
    }
   
    /**
    *  用途编码 Getter S_PAYSUMMARYCODE       * */
    public static String  columnSpaysummarycode()
    {
        return "S_PAYSUMMARYCODE";
    }
   
    /**
    *  用途名称 Getter S_PAYSUMMARYNAME       * */
    public static String  columnSpaysummaryname()
    {
        return "S_PAYSUMMARYNAME";
    }
   
    /**
    *  实际支付金额,人民银行在回单中补录 Getter S_XPAYAMT       * */
    public static String  columnSxpayamt()
    {
        return "S_XPAYAMT";
    }
   
    /**
    *  人民银行处理日期，人民银行在回单中补录 Getter S_XPAYDATE       * */
    public static String  columnSxpaydate()
    {
        return "S_XPAYDATE";
    }
   
    /**
    *  银行交易流水号,人民银行在回单中补录 Getter S_XAGENTBUSINESSNO       * */
    public static String  columnSxagentbusinessno()
    {
        return "S_XAGENTBUSINESSNO";
    }
   
    /**
    *  拨款凭证明细ID Getter S_ID       * */
    public static String  columnSid()
    {
        return "S_ID";
    }
   
    /**
    *  失败原因 Getter S_XADDWORD       * */
    public static String  columnSxaddword()
    {
        return "S_XADDWORD";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_PAYOUTMSGSUB";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[42];        
        columnNames[0]="S_BIZNO";
        columnNames[1]="S_SEQNO";
        columnNames[2]="S_ACCDATE";
        columnNames[3]="S_ECNOMICSUBJECTCODE";
        columnNames[4]="S_BUDGETPRJCODE";
        columnNames[5]="N_MONEY";
        columnNames[6]="S_FUNSUBJECTCODE";
        columnNames[7]="TS_SYSUPDATE";
        columnNames[8]="S_TAXTICKETNO";
        columnNames[9]="S_BGTTYPECODE";
        columnNames[10]="S_BGTTYPENAME";
        columnNames[11]="S_PROCATCODE";
        columnNames[12]="S_PROCATNAME";
        columnNames[13]="S_AGENCYCODE";
        columnNames[14]="S_AGENCYNAME";
        columnNames[15]="S_EXPFUNCNAME";
        columnNames[16]="S_EXPFUNCCODE1";
        columnNames[17]="S_EXPFUNCNAME1";
        columnNames[18]="S_EXPFUNCCODE2";
        columnNames[19]="S_EXPFUNCNAME2";
        columnNames[20]="S_EXPFUNCCODE3";
        columnNames[21]="S_EXPFUNCNAME3";
        columnNames[22]="S_EXPECOCODE";
        columnNames[23]="S_EXPECONAME";
        columnNames[24]="S_EXPECOCODE1";
        columnNames[25]="S_EXPECONAME1";
        columnNames[26]="S_EXPECOCODE2";
        columnNames[27]="S_EXPECONAME2";
        columnNames[28]="S_HOLD1";
        columnNames[29]="S_HOLD2";
        columnNames[30]="S_HOLD3";
        columnNames[31]="S_HOLD4";
        columnNames[32]="S_PAYEEACCTNO";
        columnNames[33]="S_PAYEEACCTNAME";
        columnNames[34]="S_PAYEEACCTBANKNAME";
        columnNames[35]="S_PAYSUMMARYCODE";
        columnNames[36]="S_PAYSUMMARYNAME";
        columnNames[37]="S_XPAYAMT";
        columnNames[38]="S_XPAYDATE";
        columnNames[39]="S_XAGENTBUSINESSNO";
        columnNames[40]="S_ID";
        columnNames[41]="S_XADDWORD";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvPayoutmsgsubDto))
            return false;

        TvPayoutmsgsubDto bean = (TvPayoutmsgsubDto) obj;


      //compare field sbizno
      if((this.sbizno==null && bean.sbizno!=null) || (this.sbizno!=null && bean.sbizno==null))
          return false;
        else if(this.sbizno==null && bean.sbizno==null){
        }
        else{
          if(!bean.sbizno.equals(this.sbizno))
               return false;
     }
      //compare field sseqno
      if((this.sseqno==null && bean.sseqno!=null) || (this.sseqno!=null && bean.sseqno==null))
          return false;
        else if(this.sseqno==null && bean.sseqno==null){
        }
        else{
          if(!bean.sseqno.equals(this.sseqno))
               return false;
     }
      //compare field saccdate
      if((this.saccdate==null && bean.saccdate!=null) || (this.saccdate!=null && bean.saccdate==null))
          return false;
        else if(this.saccdate==null && bean.saccdate==null){
        }
        else{
          if(!bean.saccdate.equals(this.saccdate))
               return false;
     }
      //compare field secnomicsubjectcode
      if((this.secnomicsubjectcode==null && bean.secnomicsubjectcode!=null) || (this.secnomicsubjectcode!=null && bean.secnomicsubjectcode==null))
          return false;
        else if(this.secnomicsubjectcode==null && bean.secnomicsubjectcode==null){
        }
        else{
          if(!bean.secnomicsubjectcode.equals(this.secnomicsubjectcode))
               return false;
     }
      //compare field sbudgetprjcode
      if((this.sbudgetprjcode==null && bean.sbudgetprjcode!=null) || (this.sbudgetprjcode!=null && bean.sbudgetprjcode==null))
          return false;
        else if(this.sbudgetprjcode==null && bean.sbudgetprjcode==null){
        }
        else{
          if(!bean.sbudgetprjcode.equals(this.sbudgetprjcode))
               return false;
     }
      //compare field nmoney
      if((this.nmoney==null && bean.nmoney!=null) || (this.nmoney!=null && bean.nmoney==null))
          return false;
        else if(this.nmoney==null && bean.nmoney==null){
        }
        else{
          if(!bean.nmoney.equals(this.nmoney))
               return false;
     }
      //compare field sfunsubjectcode
      if((this.sfunsubjectcode==null && bean.sfunsubjectcode!=null) || (this.sfunsubjectcode!=null && bean.sfunsubjectcode==null))
          return false;
        else if(this.sfunsubjectcode==null && bean.sfunsubjectcode==null){
        }
        else{
          if(!bean.sfunsubjectcode.equals(this.sfunsubjectcode))
               return false;
     }
      //compare field tssysupdate
      if((this.tssysupdate==null && bean.tssysupdate!=null) || (this.tssysupdate!=null && bean.tssysupdate==null))
          return false;
        else if(this.tssysupdate==null && bean.tssysupdate==null){
        }
        else{
          if(!bean.tssysupdate.equals(this.tssysupdate))
               return false;
     }
      //compare field staxticketno
      if((this.staxticketno==null && bean.staxticketno!=null) || (this.staxticketno!=null && bean.staxticketno==null))
          return false;
        else if(this.staxticketno==null && bean.staxticketno==null){
        }
        else{
          if(!bean.staxticketno.equals(this.staxticketno))
               return false;
     }
      //compare field sbgttypecode
      if((this.sbgttypecode==null && bean.sbgttypecode!=null) || (this.sbgttypecode!=null && bean.sbgttypecode==null))
          return false;
        else if(this.sbgttypecode==null && bean.sbgttypecode==null){
        }
        else{
          if(!bean.sbgttypecode.equals(this.sbgttypecode))
               return false;
     }
      //compare field sbgttypename
      if((this.sbgttypename==null && bean.sbgttypename!=null) || (this.sbgttypename!=null && bean.sbgttypename==null))
          return false;
        else if(this.sbgttypename==null && bean.sbgttypename==null){
        }
        else{
          if(!bean.sbgttypename.equals(this.sbgttypename))
               return false;
     }
      //compare field sprocatcode
      if((this.sprocatcode==null && bean.sprocatcode!=null) || (this.sprocatcode!=null && bean.sprocatcode==null))
          return false;
        else if(this.sprocatcode==null && bean.sprocatcode==null){
        }
        else{
          if(!bean.sprocatcode.equals(this.sprocatcode))
               return false;
     }
      //compare field sprocatname
      if((this.sprocatname==null && bean.sprocatname!=null) || (this.sprocatname!=null && bean.sprocatname==null))
          return false;
        else if(this.sprocatname==null && bean.sprocatname==null){
        }
        else{
          if(!bean.sprocatname.equals(this.sprocatname))
               return false;
     }
      //compare field sagencycode
      if((this.sagencycode==null && bean.sagencycode!=null) || (this.sagencycode!=null && bean.sagencycode==null))
          return false;
        else if(this.sagencycode==null && bean.sagencycode==null){
        }
        else{
          if(!bean.sagencycode.equals(this.sagencycode))
               return false;
     }
      //compare field sagencyname
      if((this.sagencyname==null && bean.sagencyname!=null) || (this.sagencyname!=null && bean.sagencyname==null))
          return false;
        else if(this.sagencyname==null && bean.sagencyname==null){
        }
        else{
          if(!bean.sagencyname.equals(this.sagencyname))
               return false;
     }
      //compare field sexpfuncname
      if((this.sexpfuncname==null && bean.sexpfuncname!=null) || (this.sexpfuncname!=null && bean.sexpfuncname==null))
          return false;
        else if(this.sexpfuncname==null && bean.sexpfuncname==null){
        }
        else{
          if(!bean.sexpfuncname.equals(this.sexpfuncname))
               return false;
     }
      //compare field sexpfunccode1
      if((this.sexpfunccode1==null && bean.sexpfunccode1!=null) || (this.sexpfunccode1!=null && bean.sexpfunccode1==null))
          return false;
        else if(this.sexpfunccode1==null && bean.sexpfunccode1==null){
        }
        else{
          if(!bean.sexpfunccode1.equals(this.sexpfunccode1))
               return false;
     }
      //compare field sexpfuncname1
      if((this.sexpfuncname1==null && bean.sexpfuncname1!=null) || (this.sexpfuncname1!=null && bean.sexpfuncname1==null))
          return false;
        else if(this.sexpfuncname1==null && bean.sexpfuncname1==null){
        }
        else{
          if(!bean.sexpfuncname1.equals(this.sexpfuncname1))
               return false;
     }
      //compare field sexpfunccode2
      if((this.sexpfunccode2==null && bean.sexpfunccode2!=null) || (this.sexpfunccode2!=null && bean.sexpfunccode2==null))
          return false;
        else if(this.sexpfunccode2==null && bean.sexpfunccode2==null){
        }
        else{
          if(!bean.sexpfunccode2.equals(this.sexpfunccode2))
               return false;
     }
      //compare field sexpfuncname2
      if((this.sexpfuncname2==null && bean.sexpfuncname2!=null) || (this.sexpfuncname2!=null && bean.sexpfuncname2==null))
          return false;
        else if(this.sexpfuncname2==null && bean.sexpfuncname2==null){
        }
        else{
          if(!bean.sexpfuncname2.equals(this.sexpfuncname2))
               return false;
     }
      //compare field sexpfunccode3
      if((this.sexpfunccode3==null && bean.sexpfunccode3!=null) || (this.sexpfunccode3!=null && bean.sexpfunccode3==null))
          return false;
        else if(this.sexpfunccode3==null && bean.sexpfunccode3==null){
        }
        else{
          if(!bean.sexpfunccode3.equals(this.sexpfunccode3))
               return false;
     }
      //compare field sexpfuncname3
      if((this.sexpfuncname3==null && bean.sexpfuncname3!=null) || (this.sexpfuncname3!=null && bean.sexpfuncname3==null))
          return false;
        else if(this.sexpfuncname3==null && bean.sexpfuncname3==null){
        }
        else{
          if(!bean.sexpfuncname3.equals(this.sexpfuncname3))
               return false;
     }
      //compare field sexpecocode
      if((this.sexpecocode==null && bean.sexpecocode!=null) || (this.sexpecocode!=null && bean.sexpecocode==null))
          return false;
        else if(this.sexpecocode==null && bean.sexpecocode==null){
        }
        else{
          if(!bean.sexpecocode.equals(this.sexpecocode))
               return false;
     }
      //compare field sexpeconame
      if((this.sexpeconame==null && bean.sexpeconame!=null) || (this.sexpeconame!=null && bean.sexpeconame==null))
          return false;
        else if(this.sexpeconame==null && bean.sexpeconame==null){
        }
        else{
          if(!bean.sexpeconame.equals(this.sexpeconame))
               return false;
     }
      //compare field sexpecocode1
      if((this.sexpecocode1==null && bean.sexpecocode1!=null) || (this.sexpecocode1!=null && bean.sexpecocode1==null))
          return false;
        else if(this.sexpecocode1==null && bean.sexpecocode1==null){
        }
        else{
          if(!bean.sexpecocode1.equals(this.sexpecocode1))
               return false;
     }
      //compare field sexpeconame1
      if((this.sexpeconame1==null && bean.sexpeconame1!=null) || (this.sexpeconame1!=null && bean.sexpeconame1==null))
          return false;
        else if(this.sexpeconame1==null && bean.sexpeconame1==null){
        }
        else{
          if(!bean.sexpeconame1.equals(this.sexpeconame1))
               return false;
     }
      //compare field sexpecocode2
      if((this.sexpecocode2==null && bean.sexpecocode2!=null) || (this.sexpecocode2!=null && bean.sexpecocode2==null))
          return false;
        else if(this.sexpecocode2==null && bean.sexpecocode2==null){
        }
        else{
          if(!bean.sexpecocode2.equals(this.sexpecocode2))
               return false;
     }
      //compare field sexpeconame2
      if((this.sexpeconame2==null && bean.sexpeconame2!=null) || (this.sexpeconame2!=null && bean.sexpeconame2==null))
          return false;
        else if(this.sexpeconame2==null && bean.sexpeconame2==null){
        }
        else{
          if(!bean.sexpeconame2.equals(this.sexpeconame2))
               return false;
     }
      //compare field shold1
      if((this.shold1==null && bean.shold1!=null) || (this.shold1!=null && bean.shold1==null))
          return false;
        else if(this.shold1==null && bean.shold1==null){
        }
        else{
          if(!bean.shold1.equals(this.shold1))
               return false;
     }
      //compare field shold2
      if((this.shold2==null && bean.shold2!=null) || (this.shold2!=null && bean.shold2==null))
          return false;
        else if(this.shold2==null && bean.shold2==null){
        }
        else{
          if(!bean.shold2.equals(this.shold2))
               return false;
     }
      //compare field shold3
      if((this.shold3==null && bean.shold3!=null) || (this.shold3!=null && bean.shold3==null))
          return false;
        else if(this.shold3==null && bean.shold3==null){
        }
        else{
          if(!bean.shold3.equals(this.shold3))
               return false;
     }
      //compare field shold4
      if((this.shold4==null && bean.shold4!=null) || (this.shold4!=null && bean.shold4==null))
          return false;
        else if(this.shold4==null && bean.shold4==null){
        }
        else{
          if(!bean.shold4.equals(this.shold4))
               return false;
     }
      //compare field spayeeacctno
      if((this.spayeeacctno==null && bean.spayeeacctno!=null) || (this.spayeeacctno!=null && bean.spayeeacctno==null))
          return false;
        else if(this.spayeeacctno==null && bean.spayeeacctno==null){
        }
        else{
          if(!bean.spayeeacctno.equals(this.spayeeacctno))
               return false;
     }
      //compare field spayeeacctname
      if((this.spayeeacctname==null && bean.spayeeacctname!=null) || (this.spayeeacctname!=null && bean.spayeeacctname==null))
          return false;
        else if(this.spayeeacctname==null && bean.spayeeacctname==null){
        }
        else{
          if(!bean.spayeeacctname.equals(this.spayeeacctname))
               return false;
     }
      //compare field spayeeacctbankname
      if((this.spayeeacctbankname==null && bean.spayeeacctbankname!=null) || (this.spayeeacctbankname!=null && bean.spayeeacctbankname==null))
          return false;
        else if(this.spayeeacctbankname==null && bean.spayeeacctbankname==null){
        }
        else{
          if(!bean.spayeeacctbankname.equals(this.spayeeacctbankname))
               return false;
     }
      //compare field spaysummarycode
      if((this.spaysummarycode==null && bean.spaysummarycode!=null) || (this.spaysummarycode!=null && bean.spaysummarycode==null))
          return false;
        else if(this.spaysummarycode==null && bean.spaysummarycode==null){
        }
        else{
          if(!bean.spaysummarycode.equals(this.spaysummarycode))
               return false;
     }
      //compare field spaysummaryname
      if((this.spaysummaryname==null && bean.spaysummaryname!=null) || (this.spaysummaryname!=null && bean.spaysummaryname==null))
          return false;
        else if(this.spaysummaryname==null && bean.spaysummaryname==null){
        }
        else{
          if(!bean.spaysummaryname.equals(this.spaysummaryname))
               return false;
     }
      //compare field sxpayamt
      if((this.sxpayamt==null && bean.sxpayamt!=null) || (this.sxpayamt!=null && bean.sxpayamt==null))
          return false;
        else if(this.sxpayamt==null && bean.sxpayamt==null){
        }
        else{
          if(!bean.sxpayamt.equals(this.sxpayamt))
               return false;
     }
      //compare field sxpaydate
      if((this.sxpaydate==null && bean.sxpaydate!=null) || (this.sxpaydate!=null && bean.sxpaydate==null))
          return false;
        else if(this.sxpaydate==null && bean.sxpaydate==null){
        }
        else{
          if(!bean.sxpaydate.equals(this.sxpaydate))
               return false;
     }
      //compare field sxagentbusinessno
      if((this.sxagentbusinessno==null && bean.sxagentbusinessno!=null) || (this.sxagentbusinessno!=null && bean.sxagentbusinessno==null))
          return false;
        else if(this.sxagentbusinessno==null && bean.sxagentbusinessno==null){
        }
        else{
          if(!bean.sxagentbusinessno.equals(this.sxagentbusinessno))
               return false;
     }
      //compare field sid
      if((this.sid==null && bean.sid!=null) || (this.sid!=null && bean.sid==null))
          return false;
        else if(this.sid==null && bean.sid==null){
        }
        else{
          if(!bean.sid.equals(this.sid))
               return false;
     }
      //compare field sxaddword
      if((this.sxaddword==null && bean.sxaddword!=null) || (this.sxaddword!=null && bean.sxaddword==null))
          return false;
        else if(this.sxaddword==null && bean.sxaddword==null){
        }
        else{
          if(!bean.sxaddword.equals(this.sxaddword))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sbizno!=null)
          _hash_ = _hash_ * 31+ this.sbizno.hashCode() ;
        if(this.sseqno!=null)
          _hash_ = _hash_ * 31+ this.sseqno.hashCode() ;
        if(this.saccdate!=null)
          _hash_ = _hash_ * 31+ this.saccdate.hashCode() ;
        if(this.secnomicsubjectcode!=null)
          _hash_ = _hash_ * 31+ this.secnomicsubjectcode.hashCode() ;
        if(this.sbudgetprjcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetprjcode.hashCode() ;
        if(this.nmoney!=null)
          _hash_ = _hash_ * 31+ this.nmoney.hashCode() ;
        if(this.sfunsubjectcode!=null)
          _hash_ = _hash_ * 31+ this.sfunsubjectcode.hashCode() ;
        if(this.tssysupdate!=null)
          _hash_ = _hash_ * 31+ this.tssysupdate.hashCode() ;
        if(this.staxticketno!=null)
          _hash_ = _hash_ * 31+ this.staxticketno.hashCode() ;
        if(this.sbgttypecode!=null)
          _hash_ = _hash_ * 31+ this.sbgttypecode.hashCode() ;
        if(this.sbgttypename!=null)
          _hash_ = _hash_ * 31+ this.sbgttypename.hashCode() ;
        if(this.sprocatcode!=null)
          _hash_ = _hash_ * 31+ this.sprocatcode.hashCode() ;
        if(this.sprocatname!=null)
          _hash_ = _hash_ * 31+ this.sprocatname.hashCode() ;
        if(this.sagencycode!=null)
          _hash_ = _hash_ * 31+ this.sagencycode.hashCode() ;
        if(this.sagencyname!=null)
          _hash_ = _hash_ * 31+ this.sagencyname.hashCode() ;
        if(this.sexpfuncname!=null)
          _hash_ = _hash_ * 31+ this.sexpfuncname.hashCode() ;
        if(this.sexpfunccode1!=null)
          _hash_ = _hash_ * 31+ this.sexpfunccode1.hashCode() ;
        if(this.sexpfuncname1!=null)
          _hash_ = _hash_ * 31+ this.sexpfuncname1.hashCode() ;
        if(this.sexpfunccode2!=null)
          _hash_ = _hash_ * 31+ this.sexpfunccode2.hashCode() ;
        if(this.sexpfuncname2!=null)
          _hash_ = _hash_ * 31+ this.sexpfuncname2.hashCode() ;
        if(this.sexpfunccode3!=null)
          _hash_ = _hash_ * 31+ this.sexpfunccode3.hashCode() ;
        if(this.sexpfuncname3!=null)
          _hash_ = _hash_ * 31+ this.sexpfuncname3.hashCode() ;
        if(this.sexpecocode!=null)
          _hash_ = _hash_ * 31+ this.sexpecocode.hashCode() ;
        if(this.sexpeconame!=null)
          _hash_ = _hash_ * 31+ this.sexpeconame.hashCode() ;
        if(this.sexpecocode1!=null)
          _hash_ = _hash_ * 31+ this.sexpecocode1.hashCode() ;
        if(this.sexpeconame1!=null)
          _hash_ = _hash_ * 31+ this.sexpeconame1.hashCode() ;
        if(this.sexpecocode2!=null)
          _hash_ = _hash_ * 31+ this.sexpecocode2.hashCode() ;
        if(this.sexpeconame2!=null)
          _hash_ = _hash_ * 31+ this.sexpeconame2.hashCode() ;
        if(this.shold1!=null)
          _hash_ = _hash_ * 31+ this.shold1.hashCode() ;
        if(this.shold2!=null)
          _hash_ = _hash_ * 31+ this.shold2.hashCode() ;
        if(this.shold3!=null)
          _hash_ = _hash_ * 31+ this.shold3.hashCode() ;
        if(this.shold4!=null)
          _hash_ = _hash_ * 31+ this.shold4.hashCode() ;
        if(this.spayeeacctno!=null)
          _hash_ = _hash_ * 31+ this.spayeeacctno.hashCode() ;
        if(this.spayeeacctname!=null)
          _hash_ = _hash_ * 31+ this.spayeeacctname.hashCode() ;
        if(this.spayeeacctbankname!=null)
          _hash_ = _hash_ * 31+ this.spayeeacctbankname.hashCode() ;
        if(this.spaysummarycode!=null)
          _hash_ = _hash_ * 31+ this.spaysummarycode.hashCode() ;
        if(this.spaysummaryname!=null)
          _hash_ = _hash_ * 31+ this.spaysummaryname.hashCode() ;
        if(this.sxpayamt!=null)
          _hash_ = _hash_ * 31+ this.sxpayamt.hashCode() ;
        if(this.sxpaydate!=null)
          _hash_ = _hash_ * 31+ this.sxpaydate.hashCode() ;
        if(this.sxagentbusinessno!=null)
          _hash_ = _hash_ * 31+ this.sxagentbusinessno.hashCode() ;
        if(this.sid!=null)
          _hash_ = _hash_ * 31+ this.sid.hashCode() ;
        if(this.sxaddword!=null)
          _hash_ = _hash_ * 31+ this.sxaddword.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvPayoutmsgsubDto bean = new TvPayoutmsgsubDto();

          bean.sbizno = this.sbizno;

          bean.sseqno = this.sseqno;

          if (this.saccdate != null)
            bean.saccdate = new String(this.saccdate);
          if (this.secnomicsubjectcode != null)
            bean.secnomicsubjectcode = new String(this.secnomicsubjectcode);
          if (this.sbudgetprjcode != null)
            bean.sbudgetprjcode = new String(this.sbudgetprjcode);
          if (this.nmoney != null)
            bean.nmoney = new BigDecimal(this.nmoney.toString());
          if (this.sfunsubjectcode != null)
            bean.sfunsubjectcode = new String(this.sfunsubjectcode);
          if (this.tssysupdate != null)
            bean.tssysupdate = (Timestamp) this.tssysupdate.clone();
          if (this.staxticketno != null)
            bean.staxticketno = new String(this.staxticketno);
          if (this.sbgttypecode != null)
            bean.sbgttypecode = new String(this.sbgttypecode);
          if (this.sbgttypename != null)
            bean.sbgttypename = new String(this.sbgttypename);
          if (this.sprocatcode != null)
            bean.sprocatcode = new String(this.sprocatcode);
          if (this.sprocatname != null)
            bean.sprocatname = new String(this.sprocatname);
          if (this.sagencycode != null)
            bean.sagencycode = new String(this.sagencycode);
          if (this.sagencyname != null)
            bean.sagencyname = new String(this.sagencyname);
          if (this.sexpfuncname != null)
            bean.sexpfuncname = new String(this.sexpfuncname);
          if (this.sexpfunccode1 != null)
            bean.sexpfunccode1 = new String(this.sexpfunccode1);
          if (this.sexpfuncname1 != null)
            bean.sexpfuncname1 = new String(this.sexpfuncname1);
          if (this.sexpfunccode2 != null)
            bean.sexpfunccode2 = new String(this.sexpfunccode2);
          if (this.sexpfuncname2 != null)
            bean.sexpfuncname2 = new String(this.sexpfuncname2);
          if (this.sexpfunccode3 != null)
            bean.sexpfunccode3 = new String(this.sexpfunccode3);
          if (this.sexpfuncname3 != null)
            bean.sexpfuncname3 = new String(this.sexpfuncname3);
          if (this.sexpecocode != null)
            bean.sexpecocode = new String(this.sexpecocode);
          if (this.sexpeconame != null)
            bean.sexpeconame = new String(this.sexpeconame);
          if (this.sexpecocode1 != null)
            bean.sexpecocode1 = new String(this.sexpecocode1);
          if (this.sexpeconame1 != null)
            bean.sexpeconame1 = new String(this.sexpeconame1);
          if (this.sexpecocode2 != null)
            bean.sexpecocode2 = new String(this.sexpecocode2);
          if (this.sexpeconame2 != null)
            bean.sexpeconame2 = new String(this.sexpeconame2);
          if (this.shold1 != null)
            bean.shold1 = new String(this.shold1);
          if (this.shold2 != null)
            bean.shold2 = new String(this.shold2);
          if (this.shold3 != null)
            bean.shold3 = new String(this.shold3);
          if (this.shold4 != null)
            bean.shold4 = new String(this.shold4);
          if (this.spayeeacctno != null)
            bean.spayeeacctno = new String(this.spayeeacctno);
          if (this.spayeeacctname != null)
            bean.spayeeacctname = new String(this.spayeeacctname);
          if (this.spayeeacctbankname != null)
            bean.spayeeacctbankname = new String(this.spayeeacctbankname);
          if (this.spaysummarycode != null)
            bean.spaysummarycode = new String(this.spaysummarycode);
          if (this.spaysummaryname != null)
            bean.spaysummaryname = new String(this.spaysummaryname);
          if (this.sxpayamt != null)
            bean.sxpayamt = new BigDecimal(this.sxpayamt.toString());
          if (this.sxpaydate != null)
            bean.sxpaydate = new String(this.sxpaydate);
          if (this.sxagentbusinessno != null)
            bean.sxagentbusinessno = new String(this.sxagentbusinessno);
          if (this.sid != null)
            bean.sid = new String(this.sid);
          if (this.sxaddword != null)
            bean.sxaddword = new String(this.sxaddword);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvPayoutmsgsubDto").append(sep);
        sb.append("[sbizno]").append(" = ").append(sbizno).append(sep);
        sb.append("[sseqno]").append(" = ").append(sseqno).append(sep);
        sb.append("[saccdate]").append(" = ").append(saccdate).append(sep);
        sb.append("[secnomicsubjectcode]").append(" = ").append(secnomicsubjectcode).append(sep);
        sb.append("[sbudgetprjcode]").append(" = ").append(sbudgetprjcode).append(sep);
        sb.append("[nmoney]").append(" = ").append(nmoney).append(sep);
        sb.append("[sfunsubjectcode]").append(" = ").append(sfunsubjectcode).append(sep);
        sb.append("[tssysupdate]").append(" = ").append(tssysupdate).append(sep);
        sb.append("[staxticketno]").append(" = ").append(staxticketno).append(sep);
        sb.append("[sbgttypecode]").append(" = ").append(sbgttypecode).append(sep);
        sb.append("[sbgttypename]").append(" = ").append(sbgttypename).append(sep);
        sb.append("[sprocatcode]").append(" = ").append(sprocatcode).append(sep);
        sb.append("[sprocatname]").append(" = ").append(sprocatname).append(sep);
        sb.append("[sagencycode]").append(" = ").append(sagencycode).append(sep);
        sb.append("[sagencyname]").append(" = ").append(sagencyname).append(sep);
        sb.append("[sexpfuncname]").append(" = ").append(sexpfuncname).append(sep);
        sb.append("[sexpfunccode1]").append(" = ").append(sexpfunccode1).append(sep);
        sb.append("[sexpfuncname1]").append(" = ").append(sexpfuncname1).append(sep);
        sb.append("[sexpfunccode2]").append(" = ").append(sexpfunccode2).append(sep);
        sb.append("[sexpfuncname2]").append(" = ").append(sexpfuncname2).append(sep);
        sb.append("[sexpfunccode3]").append(" = ").append(sexpfunccode3).append(sep);
        sb.append("[sexpfuncname3]").append(" = ").append(sexpfuncname3).append(sep);
        sb.append("[sexpecocode]").append(" = ").append(sexpecocode).append(sep);
        sb.append("[sexpeconame]").append(" = ").append(sexpeconame).append(sep);
        sb.append("[sexpecocode1]").append(" = ").append(sexpecocode1).append(sep);
        sb.append("[sexpeconame1]").append(" = ").append(sexpeconame1).append(sep);
        sb.append("[sexpecocode2]").append(" = ").append(sexpecocode2).append(sep);
        sb.append("[sexpeconame2]").append(" = ").append(sexpeconame2).append(sep);
        sb.append("[shold1]").append(" = ").append(shold1).append(sep);
        sb.append("[shold2]").append(" = ").append(shold2).append(sep);
        sb.append("[shold3]").append(" = ").append(shold3).append(sep);
        sb.append("[shold4]").append(" = ").append(shold4).append(sep);
        sb.append("[spayeeacctno]").append(" = ").append(spayeeacctno).append(sep);
        sb.append("[spayeeacctname]").append(" = ").append(spayeeacctname).append(sep);
        sb.append("[spayeeacctbankname]").append(" = ").append(spayeeacctbankname).append(sep);
        sb.append("[spaysummarycode]").append(" = ").append(spaysummarycode).append(sep);
        sb.append("[spaysummaryname]").append(" = ").append(spaysummaryname).append(sep);
        sb.append("[sxpayamt]").append(" = ").append(sxpayamt).append(sep);
        sb.append("[sxpaydate]").append(" = ").append(sxpaydate).append(sep);
        sb.append("[sxagentbusinessno]").append(" = ").append(sxagentbusinessno).append(sep);
        sb.append("[sid]").append(" = ").append(sid).append(sep);
        sb.append("[sxaddword]").append(" = ").append(sxaddword).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_BIZNO
      if (this.getSbizno()==null)
             sb.append("S_BIZNO不能为空; ");
      if (this.getSbizno()!=null)
             if (this.getSbizno().getBytes().length > 20)
                sb.append("S_BIZNO宽度不能超过 "+20+"个字符; ");
    
    //check field S_SEQNO
      if (this.getSseqno()==null)
             sb.append("S_SEQNO不能为空; ");
      
    //check field S_ACCDATE
      if (this.getSaccdate()==null)
             sb.append("S_ACCDATE不能为空; ");
      if (this.getSaccdate()!=null)
             if (this.getSaccdate().getBytes().length > 8)
                sb.append("S_ACCDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_ECNOMICSUBJECTCODE
      if (this.getSecnomicsubjectcode()!=null)
             if (this.getSecnomicsubjectcode().getBytes().length > 30)
                sb.append("S_ECNOMICSUBJECTCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_BUDGETPRJCODE
      if (this.getSbudgetprjcode()!=null)
             if (this.getSbudgetprjcode().getBytes().length > 30)
                sb.append("S_BUDGETPRJCODE宽度不能超过 "+30+"个字符; ");
    
    //check field N_MONEY
      if (this.getNmoney()==null)
             sb.append("N_MONEY不能为空; ");
      
    //check field S_FUNSUBJECTCODE
      if (this.getSfunsubjectcode()==null)
             sb.append("S_FUNSUBJECTCODE不能为空; ");
      if (this.getSfunsubjectcode()!=null)
             if (this.getSfunsubjectcode().getBytes().length > 30)
                sb.append("S_FUNSUBJECTCODE宽度不能超过 "+30+"个字符; ");
    
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  
    //check field S_TAXTICKETNO
      if (this.getStaxticketno()!=null)
             if (this.getStaxticketno().getBytes().length > 30)
                sb.append("S_TAXTICKETNO宽度不能超过 "+30+"个字符; ");
    
    //check field S_BGTTYPECODE
      if (this.getSbgttypecode()!=null)
             if (this.getSbgttypecode().getBytes().length > 42)
                sb.append("S_BGTTYPECODE宽度不能超过 "+42+"个字符; ");
    
    //check field S_BGTTYPENAME
      if (this.getSbgttypename()!=null)
             if (this.getSbgttypename().getBytes().length > 60)
                sb.append("S_BGTTYPENAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_PROCATCODE
      if (this.getSprocatcode()!=null)
             if (this.getSprocatcode().getBytes().length > 42)
                sb.append("S_PROCATCODE宽度不能超过 "+42+"个字符; ");
    
    //check field S_PROCATNAME
      if (this.getSprocatname()!=null)
             if (this.getSprocatname().getBytes().length > 60)
                sb.append("S_PROCATNAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_AGENCYCODE
      if (this.getSagencycode()!=null)
             if (this.getSagencycode().getBytes().length > 42)
                sb.append("S_AGENCYCODE宽度不能超过 "+42+"个字符; ");
    
    //check field S_AGENCYNAME
      if (this.getSagencyname()!=null)
             if (this.getSagencyname().getBytes().length > 60)
                sb.append("S_AGENCYNAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPFUNCNAME
      if (this.getSexpfuncname()!=null)
             if (this.getSexpfuncname().getBytes().length > 60)
                sb.append("S_EXPFUNCNAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPFUNCCODE1
      if (this.getSexpfunccode1()!=null)
             if (this.getSexpfunccode1().getBytes().length > 42)
                sb.append("S_EXPFUNCCODE1宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPFUNCNAME1
      if (this.getSexpfuncname1()!=null)
             if (this.getSexpfuncname1().getBytes().length > 60)
                sb.append("S_EXPFUNCNAME1宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPFUNCCODE2
      if (this.getSexpfunccode2()!=null)
             if (this.getSexpfunccode2().getBytes().length > 42)
                sb.append("S_EXPFUNCCODE2宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPFUNCNAME2
      if (this.getSexpfuncname2()!=null)
             if (this.getSexpfuncname2().getBytes().length > 60)
                sb.append("S_EXPFUNCNAME2宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPFUNCCODE3
      if (this.getSexpfunccode3()!=null)
             if (this.getSexpfunccode3().getBytes().length > 42)
                sb.append("S_EXPFUNCCODE3宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPFUNCNAME3
      if (this.getSexpfuncname3()!=null)
             if (this.getSexpfuncname3().getBytes().length > 60)
                sb.append("S_EXPFUNCNAME3宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPECOCODE
      if (this.getSexpecocode()!=null)
             if (this.getSexpecocode().getBytes().length > 42)
                sb.append("S_EXPECOCODE宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPECONAME
      if (this.getSexpeconame()!=null)
             if (this.getSexpeconame().getBytes().length > 60)
                sb.append("S_EXPECONAME宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPECOCODE1
      if (this.getSexpecocode1()!=null)
             if (this.getSexpecocode1().getBytes().length > 42)
                sb.append("S_EXPECOCODE1宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPECONAME1
      if (this.getSexpeconame1()!=null)
             if (this.getSexpeconame1().getBytes().length > 60)
                sb.append("S_EXPECONAME1宽度不能超过 "+60+"个字符; ");
    
    //check field S_EXPECOCODE2
      if (this.getSexpecocode2()!=null)
             if (this.getSexpecocode2().getBytes().length > 42)
                sb.append("S_EXPECOCODE2宽度不能超过 "+42+"个字符; ");
    
    //check field S_EXPECONAME2
      if (this.getSexpeconame2()!=null)
             if (this.getSexpeconame2().getBytes().length > 60)
                sb.append("S_EXPECONAME2宽度不能超过 "+60+"个字符; ");
    
    //check field S_HOLD1
      if (this.getShold1()!=null)
             if (this.getShold1().getBytes().length > 42)
                sb.append("S_HOLD1宽度不能超过 "+42+"个字符; ");
    
    //check field S_HOLD2
      if (this.getShold2()!=null)
             if (this.getShold2().getBytes().length > 42)
                sb.append("S_HOLD2宽度不能超过 "+42+"个字符; ");
    
    //check field S_HOLD3
      if (this.getShold3()!=null)
             if (this.getShold3().getBytes().length > 42)
                sb.append("S_HOLD3宽度不能超过 "+42+"个字符; ");
    
    //check field S_HOLD4
      if (this.getShold4()!=null)
             if (this.getShold4().getBytes().length > 42)
                sb.append("S_HOLD4宽度不能超过 "+42+"个字符; ");
    
    //check field S_PAYEEACCTNO
      if (this.getSpayeeacctno()!=null)
             if (this.getSpayeeacctno().getBytes().length > 32)
                sb.append("S_PAYEEACCTNO收款人账号宽度不能超过 "+32+"个字符; ");
    
    //check field S_PAYEEACCTNAME
      if (this.getSpayeeacctname()!=null)
             if (this.getSpayeeacctname().getBytes().length > 120)
                sb.append("S_PAYEEACCTNAME收款人名称宽度不能超过 "+120+"个字符; ");
    
    //check field S_PAYEEACCTBANKNAME
      if (this.getSpayeeacctbankname()!=null)
             if (this.getSpayeeacctbankname().getBytes().length > 60)
                sb.append("S_PAYEEACCTBANKNAME收款人银行宽度不能超过 "+60+"个字符; ");
    
    //check field S_PAYSUMMARYCODE
      if (this.getSpaysummarycode()!=null)
             if (this.getSpaysummarycode().getBytes().length > 42)
                sb.append("S_PAYSUMMARYCODE用途编码宽度不能超过 "+42+"个字符; ");
    
    //check field S_PAYSUMMARYNAME
      if (this.getSpaysummaryname()!=null)
             if (this.getSpaysummaryname().getBytes().length > 200)
                sb.append("S_PAYSUMMARYNAME用途名称宽度不能超过 "+200+"个字符; ");
    
    //check field S_XPAYAMT
      
    //check field S_XPAYDATE
      if (this.getSxpaydate()!=null)
             if (this.getSxpaydate().getBytes().length > 10)
                sb.append("S_XPAYDATE人民银行处理日期，人民银行在回单中补录宽度不能超过 "+10+"个字符; ");
    
    //check field S_XAGENTBUSINESSNO
      if (this.getSxagentbusinessno()!=null)
             if (this.getSxagentbusinessno().getBytes().length > 60)
                sb.append("S_XAGENTBUSINESSNO银行交易流水号,人民银行在回单中补录宽度不能超过 "+60+"个字符; ");
    
    //check field S_ID
      if (this.getSid()!=null)
             if (this.getSid().getBytes().length > 38)
                sb.append("S_ID拨款凭证明细ID宽度不能超过 "+38+"个字符; ");
    
    //check field S_XADDWORD
      if (this.getSxaddword()!=null)
             if (this.getSxaddword().getBytes().length > 120)
                sb.append("S_XADDWORD失败原因宽度不能超过 "+120+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_BIZNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BIZNO")) {
               if (this.getSbizno()==null)
                    sb.append("S_BIZNO 不能为空; ");
               if (this.getSbizno()!=null)
                    if (this.getSbizno().getBytes().length > 20)
                        sb.append("S_BIZNO 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field S_SEQNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SEQNO")) {
               if (this.getSseqno()==null)
                    sb.append("S_SEQNO 不能为空; ");
               break;
         }
  }
    
    //check field S_ACCDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ACCDATE")) {
               if (this.getSaccdate()==null)
                    sb.append("S_ACCDATE 不能为空; ");
               if (this.getSaccdate()!=null)
                    if (this.getSaccdate().getBytes().length > 8)
                        sb.append("S_ACCDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_ECNOMICSUBJECTCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ECNOMICSUBJECTCODE")) {
                 if (this.getSecnomicsubjectcode()!=null)
                    if (this.getSecnomicsubjectcode().getBytes().length > 30)
                        sb.append("S_ECNOMICSUBJECTCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETPRJCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETPRJCODE")) {
                 if (this.getSbudgetprjcode()!=null)
                    if (this.getSbudgetprjcode().getBytes().length > 30)
                        sb.append("S_BUDGETPRJCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field N_MONEY
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_MONEY")) {
               if (this.getNmoney()==null)
                    sb.append("N_MONEY 不能为空; ");
               break;
         }
  }
    
    //check field S_FUNSUBJECTCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FUNSUBJECTCODE")) {
               if (this.getSfunsubjectcode()==null)
                    sb.append("S_FUNSUBJECTCODE 不能为空; ");
               if (this.getSfunsubjectcode()!=null)
                    if (this.getSfunsubjectcode().getBytes().length > 30)
                        sb.append("S_FUNSUBJECTCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  
    //check field S_TAXTICKETNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTICKETNO")) {
                 if (this.getStaxticketno()!=null)
                    if (this.getStaxticketno().getBytes().length > 30)
                        sb.append("S_TAXTICKETNO 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_BGTTYPECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BGTTYPECODE")) {
                 if (this.getSbgttypecode()!=null)
                    if (this.getSbgttypecode().getBytes().length > 42)
                        sb.append("S_BGTTYPECODE 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_BGTTYPENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BGTTYPENAME")) {
                 if (this.getSbgttypename()!=null)
                    if (this.getSbgttypename().getBytes().length > 60)
                        sb.append("S_BGTTYPENAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PROCATCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PROCATCODE")) {
                 if (this.getSprocatcode()!=null)
                    if (this.getSprocatcode().getBytes().length > 42)
                        sb.append("S_PROCATCODE 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_PROCATNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PROCATNAME")) {
                 if (this.getSprocatname()!=null)
                    if (this.getSprocatname().getBytes().length > 60)
                        sb.append("S_PROCATNAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_AGENCYCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_AGENCYCODE")) {
                 if (this.getSagencycode()!=null)
                    if (this.getSagencycode().getBytes().length > 42)
                        sb.append("S_AGENCYCODE 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_AGENCYNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_AGENCYNAME")) {
                 if (this.getSagencyname()!=null)
                    if (this.getSagencyname().getBytes().length > 60)
                        sb.append("S_AGENCYNAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCNAME")) {
                 if (this.getSexpfuncname()!=null)
                    if (this.getSexpfuncname().getBytes().length > 60)
                        sb.append("S_EXPFUNCNAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCCODE1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCCODE1")) {
                 if (this.getSexpfunccode1()!=null)
                    if (this.getSexpfunccode1().getBytes().length > 42)
                        sb.append("S_EXPFUNCCODE1 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCNAME1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCNAME1")) {
                 if (this.getSexpfuncname1()!=null)
                    if (this.getSexpfuncname1().getBytes().length > 60)
                        sb.append("S_EXPFUNCNAME1 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCCODE2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCCODE2")) {
                 if (this.getSexpfunccode2()!=null)
                    if (this.getSexpfunccode2().getBytes().length > 42)
                        sb.append("S_EXPFUNCCODE2 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCNAME2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCNAME2")) {
                 if (this.getSexpfuncname2()!=null)
                    if (this.getSexpfuncname2().getBytes().length > 60)
                        sb.append("S_EXPFUNCNAME2 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCCODE3
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCCODE3")) {
                 if (this.getSexpfunccode3()!=null)
                    if (this.getSexpfunccode3().getBytes().length > 42)
                        sb.append("S_EXPFUNCCODE3 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPFUNCNAME3
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPFUNCNAME3")) {
                 if (this.getSexpfuncname3()!=null)
                    if (this.getSexpfuncname3().getBytes().length > 60)
                        sb.append("S_EXPFUNCNAME3 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPECOCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECOCODE")) {
                 if (this.getSexpecocode()!=null)
                    if (this.getSexpecocode().getBytes().length > 42)
                        sb.append("S_EXPECOCODE 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPECONAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECONAME")) {
                 if (this.getSexpeconame()!=null)
                    if (this.getSexpeconame().getBytes().length > 60)
                        sb.append("S_EXPECONAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPECOCODE1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECOCODE1")) {
                 if (this.getSexpecocode1()!=null)
                    if (this.getSexpecocode1().getBytes().length > 42)
                        sb.append("S_EXPECOCODE1 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPECONAME1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECONAME1")) {
                 if (this.getSexpeconame1()!=null)
                    if (this.getSexpeconame1().getBytes().length > 60)
                        sb.append("S_EXPECONAME1 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_EXPECOCODE2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECOCODE2")) {
                 if (this.getSexpecocode2()!=null)
                    if (this.getSexpecocode2().getBytes().length > 42)
                        sb.append("S_EXPECOCODE2 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_EXPECONAME2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_EXPECONAME2")) {
                 if (this.getSexpeconame2()!=null)
                    if (this.getSexpeconame2().getBytes().length > 60)
                        sb.append("S_EXPECONAME2 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_HOLD1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD1")) {
                 if (this.getShold1()!=null)
                    if (this.getShold1().getBytes().length > 42)
                        sb.append("S_HOLD1 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_HOLD2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD2")) {
                 if (this.getShold2()!=null)
                    if (this.getShold2().getBytes().length > 42)
                        sb.append("S_HOLD2 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_HOLD3
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD3")) {
                 if (this.getShold3()!=null)
                    if (this.getShold3().getBytes().length > 42)
                        sb.append("S_HOLD3 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_HOLD4
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD4")) {
                 if (this.getShold4()!=null)
                    if (this.getShold4().getBytes().length > 42)
                        sb.append("S_HOLD4 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCTNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCTNO")) {
                 if (this.getSpayeeacctno()!=null)
                    if (this.getSpayeeacctno().getBytes().length > 32)
                        sb.append("S_PAYEEACCTNO 收款人账号宽度不能超过 "+32+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCTNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCTNAME")) {
                 if (this.getSpayeeacctname()!=null)
                    if (this.getSpayeeacctname().getBytes().length > 120)
                        sb.append("S_PAYEEACCTNAME 收款人名称宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
    //check field S_PAYEEACCTBANKNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYEEACCTBANKNAME")) {
                 if (this.getSpayeeacctbankname()!=null)
                    if (this.getSpayeeacctbankname().getBytes().length > 60)
                        sb.append("S_PAYEEACCTBANKNAME 收款人银行宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_PAYSUMMARYCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYSUMMARYCODE")) {
                 if (this.getSpaysummarycode()!=null)
                    if (this.getSpaysummarycode().getBytes().length > 42)
                        sb.append("S_PAYSUMMARYCODE 用途编码宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_PAYSUMMARYNAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYSUMMARYNAME")) {
                 if (this.getSpaysummaryname()!=null)
                    if (this.getSpaysummaryname().getBytes().length > 200)
                        sb.append("S_PAYSUMMARYNAME 用途名称宽度不能超过 "+200+"个字符");
             break;
         }
  }
    
    //check field S_XPAYAMT
          
    //check field S_XPAYDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XPAYDATE")) {
                 if (this.getSxpaydate()!=null)
                    if (this.getSxpaydate().getBytes().length > 10)
                        sb.append("S_XPAYDATE 人民银行处理日期，人民银行在回单中补录宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_XAGENTBUSINESSNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XAGENTBUSINESSNO")) {
                 if (this.getSxagentbusinessno()!=null)
                    if (this.getSxagentbusinessno().getBytes().length > 60)
                        sb.append("S_XAGENTBUSINESSNO 银行交易流水号,人民银行在回单中补录宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_ID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ID")) {
                 if (this.getSid()!=null)
                    if (this.getSid().getBytes().length > 38)
                        sb.append("S_ID 拨款凭证明细ID宽度不能超过 "+38+"个字符");
             break;
         }
  }
    
    //check field S_XADDWORD
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_XADDWORD")) {
                 if (this.getSxaddword()!=null)
                    if (this.getSxaddword().getBytes().length > 120)
                        sb.append("S_XADDWORD 失败原因宽度不能超过 "+120+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TvPayoutmsgsubPK pk = new TvPayoutmsgsubPK();
      pk.setSbizno(getSbizno());
      pk.setSseqno(getSseqno());
      return pk;
    };
}
