    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvTaxKindPK;
/**
 * <p>Title: DTO of table: TV_TAX_KIND</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:04 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvTaxKindDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_SEQ VARCHAR , PK   , NOT NULL       */
    protected String sseq;
    /**
    *  I_PROJECTID INTEGER , PK   , NOT NULL       */
    protected Integer iprojectid;
    /**
    *  S_LIMITDATE CHARACTER   , NOT NULL       */
    protected String slimitdate;
    /**
    *  S_BUDGETSUBJECTCODE VARCHAR   , NOT NULL       */
    protected String sbudgetsubjectcode;
    /**
    *  S_TAXTYPENAME VARCHAR   , NOT NULL       */
    protected String staxtypename;
    /**
    *  C_BUDGETLEVEL CHARACTER   , NOT NULL       */
    protected String cbudgetlevel;
    /**
    *  S_VICESIGN CHARACTER         */
    protected String svicesign;
    /**
    *  F_SUBJECTAMT DECIMAL   , NOT NULL       */
    protected BigDecimal fsubjectamt;
    /**
    *  C_TAXTYPE CHARACTER   , NOT NULL       */
    protected String ctaxtype;
    /**
    *  S_TAXSTARTDATE CHARACTER   , NOT NULL       */
    protected String staxstartdate;
    /**
    *  I_DETAILNO INTEGER         */
    protected Integer idetailno;
    /**
    *  S_TAXENDDATE CHARACTER   , NOT NULL       */
    protected String staxenddate;
    /**
    *  TS_UPDATE TIMESTAMP   , NOT NULL       */
    protected Timestamp tsupdate;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSseq()
    {
        return sseq;
    }
     /**
     *   Setter S_SEQ, PK , NOT NULL        * */
    public void setSseq(String _sseq) {
        this.sseq = _sseq;
    }


    public Integer getIprojectid()
    {
        return iprojectid;
    }
     /**
     *   Setter I_PROJECTID, PK , NOT NULL        * */
    public void setIprojectid(Integer _iprojectid) {
        this.iprojectid = _iprojectid;
    }


    public String getSlimitdate()
    {
        return slimitdate;
    }
     /**
     *   Setter S_LIMITDATE , NOT NULL        * */
    public void setSlimitdate(String _slimitdate) {
        this.slimitdate = _slimitdate;
    }


    public String getSbudgetsubjectcode()
    {
        return sbudgetsubjectcode;
    }
     /**
     *   Setter S_BUDGETSUBJECTCODE , NOT NULL        * */
    public void setSbudgetsubjectcode(String _sbudgetsubjectcode) {
        this.sbudgetsubjectcode = _sbudgetsubjectcode;
    }


    public String getStaxtypename()
    {
        return staxtypename;
    }
     /**
     *   Setter S_TAXTYPENAME , NOT NULL        * */
    public void setStaxtypename(String _staxtypename) {
        this.staxtypename = _staxtypename;
    }


    public String getCbudgetlevel()
    {
        return cbudgetlevel;
    }
     /**
     *   Setter C_BUDGETLEVEL , NOT NULL        * */
    public void setCbudgetlevel(String _cbudgetlevel) {
        this.cbudgetlevel = _cbudgetlevel;
    }


    public String getSvicesign()
    {
        return svicesign;
    }
     /**
     *   Setter S_VICESIGN        * */
    public void setSvicesign(String _svicesign) {
        this.svicesign = _svicesign;
    }


    public BigDecimal getFsubjectamt()
    {
        return fsubjectamt;
    }
     /**
     *   Setter F_SUBJECTAMT , NOT NULL        * */
    public void setFsubjectamt(BigDecimal _fsubjectamt) {
        this.fsubjectamt = _fsubjectamt;
    }


    public String getCtaxtype()
    {
        return ctaxtype;
    }
     /**
     *   Setter C_TAXTYPE , NOT NULL        * */
    public void setCtaxtype(String _ctaxtype) {
        this.ctaxtype = _ctaxtype;
    }


    public String getStaxstartdate()
    {
        return staxstartdate;
    }
     /**
     *   Setter S_TAXSTARTDATE , NOT NULL        * */
    public void setStaxstartdate(String _staxstartdate) {
        this.staxstartdate = _staxstartdate;
    }


    public Integer getIdetailno()
    {
        return idetailno;
    }
     /**
     *   Setter I_DETAILNO        * */
    public void setIdetailno(Integer _idetailno) {
        this.idetailno = _idetailno;
    }


    public String getStaxenddate()
    {
        return staxenddate;
    }
     /**
     *   Setter S_TAXENDDATE , NOT NULL        * */
    public void setStaxenddate(String _staxenddate) {
        this.staxenddate = _staxenddate;
    }


    public Timestamp getTsupdate()
    {
        return tsupdate;
    }
     /**
     *   Setter TS_UPDATE , NOT NULL        * */
    public void setTsupdate(Timestamp _tsupdate) {
        this.tsupdate = _tsupdate;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_SEQ, PK , NOT NULL       * */
    public static String  columnSseq()
    {
        return "S_SEQ";
    }
   
    /**
    *   Getter I_PROJECTID, PK , NOT NULL       * */
    public static String  columnIprojectid()
    {
        return "I_PROJECTID";
    }
   
    /**
    *   Getter S_LIMITDATE , NOT NULL       * */
    public static String  columnSlimitdate()
    {
        return "S_LIMITDATE";
    }
   
    /**
    *   Getter S_BUDGETSUBJECTCODE , NOT NULL       * */
    public static String  columnSbudgetsubjectcode()
    {
        return "S_BUDGETSUBJECTCODE";
    }
   
    /**
    *   Getter S_TAXTYPENAME , NOT NULL       * */
    public static String  columnStaxtypename()
    {
        return "S_TAXTYPENAME";
    }
   
    /**
    *   Getter C_BUDGETLEVEL , NOT NULL       * */
    public static String  columnCbudgetlevel()
    {
        return "C_BUDGETLEVEL";
    }
   
    /**
    *   Getter S_VICESIGN       * */
    public static String  columnSvicesign()
    {
        return "S_VICESIGN";
    }
   
    /**
    *   Getter F_SUBJECTAMT , NOT NULL       * */
    public static String  columnFsubjectamt()
    {
        return "F_SUBJECTAMT";
    }
   
    /**
    *   Getter C_TAXTYPE , NOT NULL       * */
    public static String  columnCtaxtype()
    {
        return "C_TAXTYPE";
    }
   
    /**
    *   Getter S_TAXSTARTDATE , NOT NULL       * */
    public static String  columnStaxstartdate()
    {
        return "S_TAXSTARTDATE";
    }
   
    /**
    *   Getter I_DETAILNO       * */
    public static String  columnIdetailno()
    {
        return "I_DETAILNO";
    }
   
    /**
    *   Getter S_TAXENDDATE , NOT NULL       * */
    public static String  columnStaxenddate()
    {
        return "S_TAXENDDATE";
    }
   
    /**
    *   Getter TS_UPDATE , NOT NULL       * */
    public static String  columnTsupdate()
    {
        return "TS_UPDATE";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_TAX_KIND";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[13];        
        columnNames[0]="S_SEQ";
        columnNames[1]="I_PROJECTID";
        columnNames[2]="S_LIMITDATE";
        columnNames[3]="S_BUDGETSUBJECTCODE";
        columnNames[4]="S_TAXTYPENAME";
        columnNames[5]="C_BUDGETLEVEL";
        columnNames[6]="S_VICESIGN";
        columnNames[7]="F_SUBJECTAMT";
        columnNames[8]="C_TAXTYPE";
        columnNames[9]="S_TAXSTARTDATE";
        columnNames[10]="I_DETAILNO";
        columnNames[11]="S_TAXENDDATE";
        columnNames[12]="TS_UPDATE";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvTaxKindDto))
            return false;

        TvTaxKindDto bean = (TvTaxKindDto) obj;


      //compare field sseq
      if((this.sseq==null && bean.sseq!=null) || (this.sseq!=null && bean.sseq==null))
          return false;
        else if(this.sseq==null && bean.sseq==null){
        }
        else{
          if(!bean.sseq.equals(this.sseq))
               return false;
     }
      //compare field iprojectid
      if((this.iprojectid==null && bean.iprojectid!=null) || (this.iprojectid!=null && bean.iprojectid==null))
          return false;
        else if(this.iprojectid==null && bean.iprojectid==null){
        }
        else{
          if(!bean.iprojectid.equals(this.iprojectid))
               return false;
     }
      //compare field slimitdate
      if((this.slimitdate==null && bean.slimitdate!=null) || (this.slimitdate!=null && bean.slimitdate==null))
          return false;
        else if(this.slimitdate==null && bean.slimitdate==null){
        }
        else{
          if(!bean.slimitdate.equals(this.slimitdate))
               return false;
     }
      //compare field sbudgetsubjectcode
      if((this.sbudgetsubjectcode==null && bean.sbudgetsubjectcode!=null) || (this.sbudgetsubjectcode!=null && bean.sbudgetsubjectcode==null))
          return false;
        else if(this.sbudgetsubjectcode==null && bean.sbudgetsubjectcode==null){
        }
        else{
          if(!bean.sbudgetsubjectcode.equals(this.sbudgetsubjectcode))
               return false;
     }
      //compare field staxtypename
      if((this.staxtypename==null && bean.staxtypename!=null) || (this.staxtypename!=null && bean.staxtypename==null))
          return false;
        else if(this.staxtypename==null && bean.staxtypename==null){
        }
        else{
          if(!bean.staxtypename.equals(this.staxtypename))
               return false;
     }
      //compare field cbudgetlevel
      if((this.cbudgetlevel==null && bean.cbudgetlevel!=null) || (this.cbudgetlevel!=null && bean.cbudgetlevel==null))
          return false;
        else if(this.cbudgetlevel==null && bean.cbudgetlevel==null){
        }
        else{
          if(!bean.cbudgetlevel.equals(this.cbudgetlevel))
               return false;
     }
      //compare field svicesign
      if((this.svicesign==null && bean.svicesign!=null) || (this.svicesign!=null && bean.svicesign==null))
          return false;
        else if(this.svicesign==null && bean.svicesign==null){
        }
        else{
          if(!bean.svicesign.equals(this.svicesign))
               return false;
     }
      //compare field fsubjectamt
      if((this.fsubjectamt==null && bean.fsubjectamt!=null) || (this.fsubjectamt!=null && bean.fsubjectamt==null))
          return false;
        else if(this.fsubjectamt==null && bean.fsubjectamt==null){
        }
        else{
          if(!bean.fsubjectamt.equals(this.fsubjectamt))
               return false;
     }
      //compare field ctaxtype
      if((this.ctaxtype==null && bean.ctaxtype!=null) || (this.ctaxtype!=null && bean.ctaxtype==null))
          return false;
        else if(this.ctaxtype==null && bean.ctaxtype==null){
        }
        else{
          if(!bean.ctaxtype.equals(this.ctaxtype))
               return false;
     }
      //compare field staxstartdate
      if((this.staxstartdate==null && bean.staxstartdate!=null) || (this.staxstartdate!=null && bean.staxstartdate==null))
          return false;
        else if(this.staxstartdate==null && bean.staxstartdate==null){
        }
        else{
          if(!bean.staxstartdate.equals(this.staxstartdate))
               return false;
     }
      //compare field idetailno
      if((this.idetailno==null && bean.idetailno!=null) || (this.idetailno!=null && bean.idetailno==null))
          return false;
        else if(this.idetailno==null && bean.idetailno==null){
        }
        else{
          if(!bean.idetailno.equals(this.idetailno))
               return false;
     }
      //compare field staxenddate
      if((this.staxenddate==null && bean.staxenddate!=null) || (this.staxenddate!=null && bean.staxenddate==null))
          return false;
        else if(this.staxenddate==null && bean.staxenddate==null){
        }
        else{
          if(!bean.staxenddate.equals(this.staxenddate))
               return false;
     }
      //compare field tsupdate
      if((this.tsupdate==null && bean.tsupdate!=null) || (this.tsupdate!=null && bean.tsupdate==null))
          return false;
        else if(this.tsupdate==null && bean.tsupdate==null){
        }
        else{
          if(!bean.tsupdate.equals(this.tsupdate))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sseq!=null)
          _hash_ = _hash_ * 31+ this.sseq.hashCode() ;
        if(this.iprojectid!=null)
          _hash_ = _hash_ * 31+ this.iprojectid.hashCode() ;
        if(this.slimitdate!=null)
          _hash_ = _hash_ * 31+ this.slimitdate.hashCode() ;
        if(this.sbudgetsubjectcode!=null)
          _hash_ = _hash_ * 31+ this.sbudgetsubjectcode.hashCode() ;
        if(this.staxtypename!=null)
          _hash_ = _hash_ * 31+ this.staxtypename.hashCode() ;
        if(this.cbudgetlevel!=null)
          _hash_ = _hash_ * 31+ this.cbudgetlevel.hashCode() ;
        if(this.svicesign!=null)
          _hash_ = _hash_ * 31+ this.svicesign.hashCode() ;
        if(this.fsubjectamt!=null)
          _hash_ = _hash_ * 31+ this.fsubjectamt.hashCode() ;
        if(this.ctaxtype!=null)
          _hash_ = _hash_ * 31+ this.ctaxtype.hashCode() ;
        if(this.staxstartdate!=null)
          _hash_ = _hash_ * 31+ this.staxstartdate.hashCode() ;
        if(this.idetailno!=null)
          _hash_ = _hash_ * 31+ this.idetailno.hashCode() ;
        if(this.staxenddate!=null)
          _hash_ = _hash_ * 31+ this.staxenddate.hashCode() ;
        if(this.tsupdate!=null)
          _hash_ = _hash_ * 31+ this.tsupdate.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvTaxKindDto bean = new TvTaxKindDto();

          bean.sseq = this.sseq;

          bean.iprojectid = this.iprojectid;

          if (this.slimitdate != null)
            bean.slimitdate = new String(this.slimitdate);
          if (this.sbudgetsubjectcode != null)
            bean.sbudgetsubjectcode = new String(this.sbudgetsubjectcode);
          if (this.staxtypename != null)
            bean.staxtypename = new String(this.staxtypename);
          if (this.cbudgetlevel != null)
            bean.cbudgetlevel = new String(this.cbudgetlevel);
          if (this.svicesign != null)
            bean.svicesign = new String(this.svicesign);
          if (this.fsubjectamt != null)
            bean.fsubjectamt = new BigDecimal(this.fsubjectamt.toString());
          if (this.ctaxtype != null)
            bean.ctaxtype = new String(this.ctaxtype);
          if (this.staxstartdate != null)
            bean.staxstartdate = new String(this.staxstartdate);
          if (this.idetailno != null)
            bean.idetailno = new Integer(this.idetailno.toString());
          if (this.staxenddate != null)
            bean.staxenddate = new String(this.staxenddate);
          if (this.tsupdate != null)
            bean.tsupdate = (Timestamp) this.tsupdate.clone();
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvTaxKindDto").append(sep);
        sb.append("[sseq]").append(" = ").append(sseq).append(sep);
        sb.append("[iprojectid]").append(" = ").append(iprojectid).append(sep);
        sb.append("[slimitdate]").append(" = ").append(slimitdate).append(sep);
        sb.append("[sbudgetsubjectcode]").append(" = ").append(sbudgetsubjectcode).append(sep);
        sb.append("[staxtypename]").append(" = ").append(staxtypename).append(sep);
        sb.append("[cbudgetlevel]").append(" = ").append(cbudgetlevel).append(sep);
        sb.append("[svicesign]").append(" = ").append(svicesign).append(sep);
        sb.append("[fsubjectamt]").append(" = ").append(fsubjectamt).append(sep);
        sb.append("[ctaxtype]").append(" = ").append(ctaxtype).append(sep);
        sb.append("[staxstartdate]").append(" = ").append(staxstartdate).append(sep);
        sb.append("[idetailno]").append(" = ").append(idetailno).append(sep);
        sb.append("[staxenddate]").append(" = ").append(staxenddate).append(sep);
        sb.append("[tsupdate]").append(" = ").append(tsupdate).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_SEQ
      if (this.getSseq()==null)
             sb.append("S_SEQ不能为空; ");
      if (this.getSseq()!=null)
             if (this.getSseq().getBytes().length > 20)
                sb.append("S_SEQ宽度不能超过 "+20+"个字符; ");
    
    //check field I_PROJECTID
      if (this.getIprojectid()==null)
             sb.append("I_PROJECTID不能为空; ");
      
    //check field S_LIMITDATE
      if (this.getSlimitdate()==null)
             sb.append("S_LIMITDATE不能为空; ");
      if (this.getSlimitdate()!=null)
             if (this.getSlimitdate().getBytes().length > 8)
                sb.append("S_LIMITDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_BUDGETSUBJECTCODE
      if (this.getSbudgetsubjectcode()==null)
             sb.append("S_BUDGETSUBJECTCODE不能为空; ");
      if (this.getSbudgetsubjectcode()!=null)
             if (this.getSbudgetsubjectcode().getBytes().length > 30)
                sb.append("S_BUDGETSUBJECTCODE宽度不能超过 "+30+"个字符; ");
    
    //check field S_TAXTYPENAME
      if (this.getStaxtypename()==null)
             sb.append("S_TAXTYPENAME不能为空; ");
      if (this.getStaxtypename()!=null)
             if (this.getStaxtypename().getBytes().length > 60)
                sb.append("S_TAXTYPENAME宽度不能超过 "+60+"个字符; ");
    
    //check field C_BUDGETLEVEL
      if (this.getCbudgetlevel()==null)
             sb.append("C_BUDGETLEVEL不能为空; ");
      if (this.getCbudgetlevel()!=null)
             if (this.getCbudgetlevel().getBytes().length > 1)
                sb.append("C_BUDGETLEVEL宽度不能超过 "+1+"个字符; ");
    
    //check field S_VICESIGN
      if (this.getSvicesign()!=null)
             if (this.getSvicesign().getBytes().length > 35)
                sb.append("S_VICESIGN宽度不能超过 "+35+"个字符; ");
    
    //check field F_SUBJECTAMT
      if (this.getFsubjectamt()==null)
             sb.append("F_SUBJECTAMT不能为空; ");
      
    //check field C_TAXTYPE
      if (this.getCtaxtype()==null)
             sb.append("C_TAXTYPE不能为空; ");
      if (this.getCtaxtype()!=null)
             if (this.getCtaxtype().getBytes().length > 1)
                sb.append("C_TAXTYPE宽度不能超过 "+1+"个字符; ");
    
    //check field S_TAXSTARTDATE
      if (this.getStaxstartdate()==null)
             sb.append("S_TAXSTARTDATE不能为空; ");
      if (this.getStaxstartdate()!=null)
             if (this.getStaxstartdate().getBytes().length > 8)
                sb.append("S_TAXSTARTDATE宽度不能超过 "+8+"个字符; ");
    
    //check field I_DETAILNO
      
    //check field S_TAXENDDATE
      if (this.getStaxenddate()==null)
             sb.append("S_TAXENDDATE不能为空; ");
      if (this.getStaxenddate()!=null)
             if (this.getStaxenddate().getBytes().length > 8)
                sb.append("S_TAXENDDATE宽度不能超过 "+8+"个字符; ");
    
    //check field TS_UPDATE
      if (this.getTsupdate()==null)
             sb.append("TS_UPDATE不能为空; ");
      

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_SEQ
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_SEQ")) {
               if (this.getSseq()==null)
                    sb.append("S_SEQ 不能为空; ");
               if (this.getSseq()!=null)
                    if (this.getSseq().getBytes().length > 20)
                        sb.append("S_SEQ 宽度不能超过 "+20+"个字符");
             break;
         }
  }
    
    //check field I_PROJECTID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("I_PROJECTID")) {
               if (this.getIprojectid()==null)
                    sb.append("I_PROJECTID 不能为空; ");
               break;
         }
  }
    
    //check field S_LIMITDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_LIMITDATE")) {
               if (this.getSlimitdate()==null)
                    sb.append("S_LIMITDATE 不能为空; ");
               if (this.getSlimitdate()!=null)
                    if (this.getSlimitdate().getBytes().length > 8)
                        sb.append("S_LIMITDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_BUDGETSUBJECTCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_BUDGETSUBJECTCODE")) {
               if (this.getSbudgetsubjectcode()==null)
                    sb.append("S_BUDGETSUBJECTCODE 不能为空; ");
               if (this.getSbudgetsubjectcode()!=null)
                    if (this.getSbudgetsubjectcode().getBytes().length > 30)
                        sb.append("S_BUDGETSUBJECTCODE 宽度不能超过 "+30+"个字符");
             break;
         }
  }
    
    //check field S_TAXTYPENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXTYPENAME")) {
               if (this.getStaxtypename()==null)
                    sb.append("S_TAXTYPENAME 不能为空; ");
               if (this.getStaxtypename()!=null)
                    if (this.getStaxtypename().getBytes().length > 60)
                        sb.append("S_TAXTYPENAME 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field C_BUDGETLEVEL
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_BUDGETLEVEL")) {
               if (this.getCbudgetlevel()==null)
                    sb.append("C_BUDGETLEVEL 不能为空; ");
               if (this.getCbudgetlevel()!=null)
                    if (this.getCbudgetlevel().getBytes().length > 1)
                        sb.append("C_BUDGETLEVEL 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_VICESIGN
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VICESIGN")) {
                 if (this.getSvicesign()!=null)
                    if (this.getSvicesign().getBytes().length > 35)
                        sb.append("S_VICESIGN 宽度不能超过 "+35+"个字符");
             break;
         }
  }
    
    //check field F_SUBJECTAMT
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("F_SUBJECTAMT")) {
               if (this.getFsubjectamt()==null)
                    sb.append("F_SUBJECTAMT 不能为空; ");
               break;
         }
  }
    
    //check field C_TAXTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("C_TAXTYPE")) {
               if (this.getCtaxtype()==null)
                    sb.append("C_TAXTYPE 不能为空; ");
               if (this.getCtaxtype()!=null)
                    if (this.getCtaxtype().getBytes().length > 1)
                        sb.append("C_TAXTYPE 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_TAXSTARTDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXSTARTDATE")) {
               if (this.getStaxstartdate()==null)
                    sb.append("S_TAXSTARTDATE 不能为空; ");
               if (this.getStaxstartdate()!=null)
                    if (this.getStaxstartdate().getBytes().length > 8)
                        sb.append("S_TAXSTARTDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field I_DETAILNO
          
    //check field S_TAXENDDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TAXENDDATE")) {
               if (this.getStaxenddate()==null)
                    sb.append("S_TAXENDDATE 不能为空; ");
               if (this.getStaxenddate()!=null)
                    if (this.getStaxenddate().getBytes().length > 8)
                        sb.append("S_TAXENDDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field TS_UPDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("TS_UPDATE")) {
               if (this.getTsupdate()==null)
                    sb.append("TS_UPDATE 不能为空; ");
               break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TvTaxKindPK pk = new TvTaxKindPK();
      pk.setSseq(getSseq());
      pk.setIprojectid(getIprojectid());
      return pk;
    };
}
