    
package com.cfcc.itfe.persistence.dto;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp ;

import java.lang.reflect.Array;

import com.cfcc.jaf.persistence.jaform.parent.IDto ;
import com.cfcc.jaf.persistence.jaform.parent.IPK;
import com.cfcc.itfe.persistence.pk.TvVoucherinfoSxPK;
/**
 * <p>Title: DTO of table: TV_VOUCHERINFO_SX</p>
 * <p>Description:  Data Transfer Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:04 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  dto.vm version timestamp: 2008-01-08 16:30:00 
 *
 * @author win7
 */

public class TvVoucherinfoSxDto   
                              implements IDto  {
/********************************************************
 *   fields
 ********************************************************/

    /**
    *  S_DEALNO VARCHAR , PK   , NOT NULL       */
    protected String sdealno;
    /**
    *  S_ORGCODE VARCHAR   , NOT NULL       */
    protected String sorgcode;
    /**
    *  S_TRECODE VARCHAR   , NOT NULL       */
    protected String strecode;
    /**
    *  S_FILENAME VARCHAR   , NOT NULL       */
    protected String sfilename;
    /**
    *  S_ADMDIVCODE VARCHAR   , NOT NULL       */
    protected String sadmdivcode;
    /**
    *  S_STYEAR VARCHAR   , NOT NULL       */
    protected String sstyear;
    /**
    *  S_VTCODE VARCHAR   , NOT NULL       */
    protected String svtcode;
    /**
    *  S_VOUCHERNO VARCHAR   , NOT NULL       */
    protected String svoucherno;
    /**
    *  S_VOUCHERFLAG VARCHAR   , NOT NULL       */
    protected String svoucherflag;
    /**
    *  S_ATTACH VARCHAR         */
    protected String sattach;
    /**
    *  S_RETURNERRMSG VARCHAR         */
    protected String sreturnerrmsg;
    /**
    *  S_CREATDATE CHARACTER   , NOT NULL       */
    protected String screatdate;
    /**
    *  N_MONEY DECIMAL   , NOT NULL       */
    protected BigDecimal nmoney;
    /**
    *  S_STATUS VARCHAR   , NOT NULL       */
    protected String sstatus;
    /**
    *  S_CONFIRUSERCODE VARCHAR         */
    protected String sconfirusercode;
    /**
    *  S_VERIFYUSERCODE VARCHAR         */
    protected String sverifyusercode;
    /**
    *  S_DEMO VARCHAR         */
    protected String sdemo;
    /**
    *  S_STAMPID VARCHAR         */
    protected String sstampid;
    /**
    *  S_PACKNO VARCHAR         */
    protected String spackno;
    /**
    *  I_COUNT INTEGER         */
    protected Integer icount;
    /**
    *  N_CHECKMONEY DECIMAL         */
    protected BigDecimal ncheckmoney;
    /**
    *  I_CHECKCOUNT INTEGER         */
    protected Integer icheckcount;
    /**
    *  TS_SYSUPDATE TIMESTAMP         */
    protected Timestamp tssysupdate;
    /**
    *  S_STAMPUSER VARCHAR         */
    protected String sstampuser;
    /**
    *  S_CHECKDATE VARCHAR         */
    protected String scheckdate;
    /**
    *  S_CHECKVOUCHERTYPE VARCHAR         */
    protected String scheckvouchertype;
    /**
    *  S_PAYBANKCODE VARCHAR         */
    protected String spaybankcode;
    /**
    *  S_RECVTIME TIMESTAMP         */
    protected Timestamp srecvtime;
    /**
    *  S_HOLD1 VARCHAR         */
    protected String shold1;
    /**
    *  S_HOLD2 VARCHAR         */
    protected String shold2;
    /**
    *  S_HOLD3 VARCHAR         */
    protected String shold3;
    /**
    *  S_HOLD4 VARCHAR         */
    protected String shold4;


/******************************************************
*
*  getter and setter
*
*******************************************************/


    public String getSdealno()
    {
        return sdealno;
    }
     /**
     *   Setter S_DEALNO, PK , NOT NULL        * */
    public void setSdealno(String _sdealno) {
        this.sdealno = _sdealno;
    }


    public String getSorgcode()
    {
        return sorgcode;
    }
     /**
     *   Setter S_ORGCODE , NOT NULL        * */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }


    public String getStrecode()
    {
        return strecode;
    }
     /**
     *   Setter S_TRECODE , NOT NULL        * */
    public void setStrecode(String _strecode) {
        this.strecode = _strecode;
    }


    public String getSfilename()
    {
        return sfilename;
    }
     /**
     *   Setter S_FILENAME , NOT NULL        * */
    public void setSfilename(String _sfilename) {
        this.sfilename = _sfilename;
    }


    public String getSadmdivcode()
    {
        return sadmdivcode;
    }
     /**
     *   Setter S_ADMDIVCODE , NOT NULL        * */
    public void setSadmdivcode(String _sadmdivcode) {
        this.sadmdivcode = _sadmdivcode;
    }


    public String getSstyear()
    {
        return sstyear;
    }
     /**
     *   Setter S_STYEAR , NOT NULL        * */
    public void setSstyear(String _sstyear) {
        this.sstyear = _sstyear;
    }


    public String getSvtcode()
    {
        return svtcode;
    }
     /**
     *   Setter S_VTCODE , NOT NULL        * */
    public void setSvtcode(String _svtcode) {
        this.svtcode = _svtcode;
    }


    public String getSvoucherno()
    {
        return svoucherno;
    }
     /**
     *   Setter S_VOUCHERNO , NOT NULL        * */
    public void setSvoucherno(String _svoucherno) {
        this.svoucherno = _svoucherno;
    }


    public String getSvoucherflag()
    {
        return svoucherflag;
    }
     /**
     *   Setter S_VOUCHERFLAG , NOT NULL        * */
    public void setSvoucherflag(String _svoucherflag) {
        this.svoucherflag = _svoucherflag;
    }


    public String getSattach()
    {
        return sattach;
    }
     /**
     *   Setter S_ATTACH        * */
    public void setSattach(String _sattach) {
        this.sattach = _sattach;
    }


    public String getSreturnerrmsg()
    {
        return sreturnerrmsg;
    }
     /**
     *   Setter S_RETURNERRMSG        * */
    public void setSreturnerrmsg(String _sreturnerrmsg) {
        this.sreturnerrmsg = _sreturnerrmsg;
    }


    public String getScreatdate()
    {
        return screatdate;
    }
     /**
     *   Setter S_CREATDATE , NOT NULL        * */
    public void setScreatdate(String _screatdate) {
        this.screatdate = _screatdate;
    }


    public BigDecimal getNmoney()
    {
        return nmoney;
    }
     /**
     *   Setter N_MONEY , NOT NULL        * */
    public void setNmoney(BigDecimal _nmoney) {
        this.nmoney = _nmoney;
    }


    public String getSstatus()
    {
        return sstatus;
    }
     /**
     *   Setter S_STATUS , NOT NULL        * */
    public void setSstatus(String _sstatus) {
        this.sstatus = _sstatus;
    }


    public String getSconfirusercode()
    {
        return sconfirusercode;
    }
     /**
     *   Setter S_CONFIRUSERCODE        * */
    public void setSconfirusercode(String _sconfirusercode) {
        this.sconfirusercode = _sconfirusercode;
    }


    public String getSverifyusercode()
    {
        return sverifyusercode;
    }
     /**
     *   Setter S_VERIFYUSERCODE        * */
    public void setSverifyusercode(String _sverifyusercode) {
        this.sverifyusercode = _sverifyusercode;
    }


    public String getSdemo()
    {
        return sdemo;
    }
     /**
     *   Setter S_DEMO        * */
    public void setSdemo(String _sdemo) {
        this.sdemo = _sdemo;
    }


    public String getSstampid()
    {
        return sstampid;
    }
     /**
     *   Setter S_STAMPID        * */
    public void setSstampid(String _sstampid) {
        this.sstampid = _sstampid;
    }


    public String getSpackno()
    {
        return spackno;
    }
     /**
     *   Setter S_PACKNO        * */
    public void setSpackno(String _spackno) {
        this.spackno = _spackno;
    }


    public Integer getIcount()
    {
        return icount;
    }
     /**
     *   Setter I_COUNT        * */
    public void setIcount(Integer _icount) {
        this.icount = _icount;
    }


    public BigDecimal getNcheckmoney()
    {
        return ncheckmoney;
    }
     /**
     *   Setter N_CHECKMONEY        * */
    public void setNcheckmoney(BigDecimal _ncheckmoney) {
        this.ncheckmoney = _ncheckmoney;
    }


    public Integer getIcheckcount()
    {
        return icheckcount;
    }
     /**
     *   Setter I_CHECKCOUNT        * */
    public void setIcheckcount(Integer _icheckcount) {
        this.icheckcount = _icheckcount;
    }


    public Timestamp getTssysupdate()
    {
        return tssysupdate;
    }
     /**
     *   Setter TS_SYSUPDATE        * */
    public void setTssysupdate(Timestamp _tssysupdate) {
        this.tssysupdate = _tssysupdate;
    }


    public String getSstampuser()
    {
        return sstampuser;
    }
     /**
     *   Setter S_STAMPUSER        * */
    public void setSstampuser(String _sstampuser) {
        this.sstampuser = _sstampuser;
    }


    public String getScheckdate()
    {
        return scheckdate;
    }
     /**
     *   Setter S_CHECKDATE        * */
    public void setScheckdate(String _scheckdate) {
        this.scheckdate = _scheckdate;
    }


    public String getScheckvouchertype()
    {
        return scheckvouchertype;
    }
     /**
     *   Setter S_CHECKVOUCHERTYPE        * */
    public void setScheckvouchertype(String _scheckvouchertype) {
        this.scheckvouchertype = _scheckvouchertype;
    }


    public String getSpaybankcode()
    {
        return spaybankcode;
    }
     /**
     *   Setter S_PAYBANKCODE        * */
    public void setSpaybankcode(String _spaybankcode) {
        this.spaybankcode = _spaybankcode;
    }


    public Timestamp getSrecvtime()
    {
        return srecvtime;
    }
     /**
     *   Setter S_RECVTIME        * */
    public void setSrecvtime(Timestamp _srecvtime) {
        this.srecvtime = _srecvtime;
    }


    public String getShold1()
    {
        return shold1;
    }
     /**
     *   Setter S_HOLD1        * */
    public void setShold1(String _shold1) {
        this.shold1 = _shold1;
    }


    public String getShold2()
    {
        return shold2;
    }
     /**
     *   Setter S_HOLD2        * */
    public void setShold2(String _shold2) {
        this.shold2 = _shold2;
    }


    public String getShold3()
    {
        return shold3;
    }
     /**
     *   Setter S_HOLD3        * */
    public void setShold3(String _shold3) {
        this.shold3 = _shold3;
    }


    public String getShold4()
    {
        return shold4;
    }
     /**
     *   Setter S_HOLD4        * */
    public void setShold4(String _shold4) {
        this.shold4 = _shold4;
    }




/******************************************************
*
*  Get Column Name
*
*******************************************************/
    /**
    *   Getter S_DEALNO, PK , NOT NULL       * */
    public static String  columnSdealno()
    {
        return "S_DEALNO";
    }
   
    /**
    *   Getter S_ORGCODE , NOT NULL       * */
    public static String  columnSorgcode()
    {
        return "S_ORGCODE";
    }
   
    /**
    *   Getter S_TRECODE , NOT NULL       * */
    public static String  columnStrecode()
    {
        return "S_TRECODE";
    }
   
    /**
    *   Getter S_FILENAME , NOT NULL       * */
    public static String  columnSfilename()
    {
        return "S_FILENAME";
    }
   
    /**
    *   Getter S_ADMDIVCODE , NOT NULL       * */
    public static String  columnSadmdivcode()
    {
        return "S_ADMDIVCODE";
    }
   
    /**
    *   Getter S_STYEAR , NOT NULL       * */
    public static String  columnSstyear()
    {
        return "S_STYEAR";
    }
   
    /**
    *   Getter S_VTCODE , NOT NULL       * */
    public static String  columnSvtcode()
    {
        return "S_VTCODE";
    }
   
    /**
    *   Getter S_VOUCHERNO , NOT NULL       * */
    public static String  columnSvoucherno()
    {
        return "S_VOUCHERNO";
    }
   
    /**
    *   Getter S_VOUCHERFLAG , NOT NULL       * */
    public static String  columnSvoucherflag()
    {
        return "S_VOUCHERFLAG";
    }
   
    /**
    *   Getter S_ATTACH       * */
    public static String  columnSattach()
    {
        return "S_ATTACH";
    }
   
    /**
    *   Getter S_RETURNERRMSG       * */
    public static String  columnSreturnerrmsg()
    {
        return "S_RETURNERRMSG";
    }
   
    /**
    *   Getter S_CREATDATE , NOT NULL       * */
    public static String  columnScreatdate()
    {
        return "S_CREATDATE";
    }
   
    /**
    *   Getter N_MONEY , NOT NULL       * */
    public static String  columnNmoney()
    {
        return "N_MONEY";
    }
   
    /**
    *   Getter S_STATUS , NOT NULL       * */
    public static String  columnSstatus()
    {
        return "S_STATUS";
    }
   
    /**
    *   Getter S_CONFIRUSERCODE       * */
    public static String  columnSconfirusercode()
    {
        return "S_CONFIRUSERCODE";
    }
   
    /**
    *   Getter S_VERIFYUSERCODE       * */
    public static String  columnSverifyusercode()
    {
        return "S_VERIFYUSERCODE";
    }
   
    /**
    *   Getter S_DEMO       * */
    public static String  columnSdemo()
    {
        return "S_DEMO";
    }
   
    /**
    *   Getter S_STAMPID       * */
    public static String  columnSstampid()
    {
        return "S_STAMPID";
    }
   
    /**
    *   Getter S_PACKNO       * */
    public static String  columnSpackno()
    {
        return "S_PACKNO";
    }
   
    /**
    *   Getter I_COUNT       * */
    public static String  columnIcount()
    {
        return "I_COUNT";
    }
   
    /**
    *   Getter N_CHECKMONEY       * */
    public static String  columnNcheckmoney()
    {
        return "N_CHECKMONEY";
    }
   
    /**
    *   Getter I_CHECKCOUNT       * */
    public static String  columnIcheckcount()
    {
        return "I_CHECKCOUNT";
    }
   
    /**
    *   Getter TS_SYSUPDATE       * */
    public static String  columnTssysupdate()
    {
        return "TS_SYSUPDATE";
    }
   
    /**
    *   Getter S_STAMPUSER       * */
    public static String  columnSstampuser()
    {
        return "S_STAMPUSER";
    }
   
    /**
    *   Getter S_CHECKDATE       * */
    public static String  columnScheckdate()
    {
        return "S_CHECKDATE";
    }
   
    /**
    *   Getter S_CHECKVOUCHERTYPE       * */
    public static String  columnScheckvouchertype()
    {
        return "S_CHECKVOUCHERTYPE";
    }
   
    /**
    *   Getter S_PAYBANKCODE       * */
    public static String  columnSpaybankcode()
    {
        return "S_PAYBANKCODE";
    }
   
    /**
    *   Getter S_RECVTIME       * */
    public static String  columnSrecvtime()
    {
        return "S_RECVTIME";
    }
   
    /**
    *   Getter S_HOLD1       * */
    public static String  columnShold1()
    {
        return "S_HOLD1";
    }
   
    /**
    *   Getter S_HOLD2       * */
    public static String  columnShold2()
    {
        return "S_HOLD2";
    }
   
    /**
    *   Getter S_HOLD3       * */
    public static String  columnShold3()
    {
        return "S_HOLD3";
    }
   
    /**
    *   Getter S_HOLD4       * */
    public static String  columnShold4()
    {
        return "S_HOLD4";
    }
   


    /**
    *  Table Name
    */
    public static String tableName(){
        return "TV_VOUCHERINFO_SX";
    }
    
    /**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[32];        
        columnNames[0]="S_DEALNO";
        columnNames[1]="S_ORGCODE";
        columnNames[2]="S_TRECODE";
        columnNames[3]="S_FILENAME";
        columnNames[4]="S_ADMDIVCODE";
        columnNames[5]="S_STYEAR";
        columnNames[6]="S_VTCODE";
        columnNames[7]="S_VOUCHERNO";
        columnNames[8]="S_VOUCHERFLAG";
        columnNames[9]="S_ATTACH";
        columnNames[10]="S_RETURNERRMSG";
        columnNames[11]="S_CREATDATE";
        columnNames[12]="N_MONEY";
        columnNames[13]="S_STATUS";
        columnNames[14]="S_CONFIRUSERCODE";
        columnNames[15]="S_VERIFYUSERCODE";
        columnNames[16]="S_DEMO";
        columnNames[17]="S_STAMPID";
        columnNames[18]="S_PACKNO";
        columnNames[19]="I_COUNT";
        columnNames[20]="N_CHECKMONEY";
        columnNames[21]="I_CHECKCOUNT";
        columnNames[22]="TS_SYSUPDATE";
        columnNames[23]="S_STAMPUSER";
        columnNames[24]="S_CHECKDATE";
        columnNames[25]="S_CHECKVOUCHERTYPE";
        columnNames[26]="S_PAYBANKCODE";
        columnNames[27]="S_RECVTIME";
        columnNames[28]="S_HOLD1";
        columnNames[29]="S_HOLD2";
        columnNames[30]="S_HOLD3";
        columnNames[31]="S_HOLD4";
        return columnNames;     
    }
/*******************************************************
*
*  supplementary methods
*
*****************************************************/


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvVoucherinfoSxDto))
            return false;

        TvVoucherinfoSxDto bean = (TvVoucherinfoSxDto) obj;


      //compare field sdealno
      if((this.sdealno==null && bean.sdealno!=null) || (this.sdealno!=null && bean.sdealno==null))
          return false;
        else if(this.sdealno==null && bean.sdealno==null){
        }
        else{
          if(!bean.sdealno.equals(this.sdealno))
               return false;
     }
      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
      //compare field strecode
      if((this.strecode==null && bean.strecode!=null) || (this.strecode!=null && bean.strecode==null))
          return false;
        else if(this.strecode==null && bean.strecode==null){
        }
        else{
          if(!bean.strecode.equals(this.strecode))
               return false;
     }
      //compare field sfilename
      if((this.sfilename==null && bean.sfilename!=null) || (this.sfilename!=null && bean.sfilename==null))
          return false;
        else if(this.sfilename==null && bean.sfilename==null){
        }
        else{
          if(!bean.sfilename.equals(this.sfilename))
               return false;
     }
      //compare field sadmdivcode
      if((this.sadmdivcode==null && bean.sadmdivcode!=null) || (this.sadmdivcode!=null && bean.sadmdivcode==null))
          return false;
        else if(this.sadmdivcode==null && bean.sadmdivcode==null){
        }
        else{
          if(!bean.sadmdivcode.equals(this.sadmdivcode))
               return false;
     }
      //compare field sstyear
      if((this.sstyear==null && bean.sstyear!=null) || (this.sstyear!=null && bean.sstyear==null))
          return false;
        else if(this.sstyear==null && bean.sstyear==null){
        }
        else{
          if(!bean.sstyear.equals(this.sstyear))
               return false;
     }
      //compare field svtcode
      if((this.svtcode==null && bean.svtcode!=null) || (this.svtcode!=null && bean.svtcode==null))
          return false;
        else if(this.svtcode==null && bean.svtcode==null){
        }
        else{
          if(!bean.svtcode.equals(this.svtcode))
               return false;
     }
      //compare field svoucherno
      if((this.svoucherno==null && bean.svoucherno!=null) || (this.svoucherno!=null && bean.svoucherno==null))
          return false;
        else if(this.svoucherno==null && bean.svoucherno==null){
        }
        else{
          if(!bean.svoucherno.equals(this.svoucherno))
               return false;
     }
      //compare field svoucherflag
      if((this.svoucherflag==null && bean.svoucherflag!=null) || (this.svoucherflag!=null && bean.svoucherflag==null))
          return false;
        else if(this.svoucherflag==null && bean.svoucherflag==null){
        }
        else{
          if(!bean.svoucherflag.equals(this.svoucherflag))
               return false;
     }
      //compare field sattach
      if((this.sattach==null && bean.sattach!=null) || (this.sattach!=null && bean.sattach==null))
          return false;
        else if(this.sattach==null && bean.sattach==null){
        }
        else{
          if(!bean.sattach.equals(this.sattach))
               return false;
     }
      //compare field sreturnerrmsg
      if((this.sreturnerrmsg==null && bean.sreturnerrmsg!=null) || (this.sreturnerrmsg!=null && bean.sreturnerrmsg==null))
          return false;
        else if(this.sreturnerrmsg==null && bean.sreturnerrmsg==null){
        }
        else{
          if(!bean.sreturnerrmsg.equals(this.sreturnerrmsg))
               return false;
     }
      //compare field screatdate
      if((this.screatdate==null && bean.screatdate!=null) || (this.screatdate!=null && bean.screatdate==null))
          return false;
        else if(this.screatdate==null && bean.screatdate==null){
        }
        else{
          if(!bean.screatdate.equals(this.screatdate))
               return false;
     }
      //compare field nmoney
      if((this.nmoney==null && bean.nmoney!=null) || (this.nmoney!=null && bean.nmoney==null))
          return false;
        else if(this.nmoney==null && bean.nmoney==null){
        }
        else{
          if(!bean.nmoney.equals(this.nmoney))
               return false;
     }
      //compare field sstatus
      if((this.sstatus==null && bean.sstatus!=null) || (this.sstatus!=null && bean.sstatus==null))
          return false;
        else if(this.sstatus==null && bean.sstatus==null){
        }
        else{
          if(!bean.sstatus.equals(this.sstatus))
               return false;
     }
      //compare field sconfirusercode
      if((this.sconfirusercode==null && bean.sconfirusercode!=null) || (this.sconfirusercode!=null && bean.sconfirusercode==null))
          return false;
        else if(this.sconfirusercode==null && bean.sconfirusercode==null){
        }
        else{
          if(!bean.sconfirusercode.equals(this.sconfirusercode))
               return false;
     }
      //compare field sverifyusercode
      if((this.sverifyusercode==null && bean.sverifyusercode!=null) || (this.sverifyusercode!=null && bean.sverifyusercode==null))
          return false;
        else if(this.sverifyusercode==null && bean.sverifyusercode==null){
        }
        else{
          if(!bean.sverifyusercode.equals(this.sverifyusercode))
               return false;
     }
      //compare field sdemo
      if((this.sdemo==null && bean.sdemo!=null) || (this.sdemo!=null && bean.sdemo==null))
          return false;
        else if(this.sdemo==null && bean.sdemo==null){
        }
        else{
          if(!bean.sdemo.equals(this.sdemo))
               return false;
     }
      //compare field sstampid
      if((this.sstampid==null && bean.sstampid!=null) || (this.sstampid!=null && bean.sstampid==null))
          return false;
        else if(this.sstampid==null && bean.sstampid==null){
        }
        else{
          if(!bean.sstampid.equals(this.sstampid))
               return false;
     }
      //compare field spackno
      if((this.spackno==null && bean.spackno!=null) || (this.spackno!=null && bean.spackno==null))
          return false;
        else if(this.spackno==null && bean.spackno==null){
        }
        else{
          if(!bean.spackno.equals(this.spackno))
               return false;
     }
      //compare field icount
      if((this.icount==null && bean.icount!=null) || (this.icount!=null && bean.icount==null))
          return false;
        else if(this.icount==null && bean.icount==null){
        }
        else{
          if(!bean.icount.equals(this.icount))
               return false;
     }
      //compare field ncheckmoney
      if((this.ncheckmoney==null && bean.ncheckmoney!=null) || (this.ncheckmoney!=null && bean.ncheckmoney==null))
          return false;
        else if(this.ncheckmoney==null && bean.ncheckmoney==null){
        }
        else{
          if(!bean.ncheckmoney.equals(this.ncheckmoney))
               return false;
     }
      //compare field icheckcount
      if((this.icheckcount==null && bean.icheckcount!=null) || (this.icheckcount!=null && bean.icheckcount==null))
          return false;
        else if(this.icheckcount==null && bean.icheckcount==null){
        }
        else{
          if(!bean.icheckcount.equals(this.icheckcount))
               return false;
     }
      //compare field tssysupdate
      if((this.tssysupdate==null && bean.tssysupdate!=null) || (this.tssysupdate!=null && bean.tssysupdate==null))
          return false;
        else if(this.tssysupdate==null && bean.tssysupdate==null){
        }
        else{
          if(!bean.tssysupdate.equals(this.tssysupdate))
               return false;
     }
      //compare field sstampuser
      if((this.sstampuser==null && bean.sstampuser!=null) || (this.sstampuser!=null && bean.sstampuser==null))
          return false;
        else if(this.sstampuser==null && bean.sstampuser==null){
        }
        else{
          if(!bean.sstampuser.equals(this.sstampuser))
               return false;
     }
      //compare field scheckdate
      if((this.scheckdate==null && bean.scheckdate!=null) || (this.scheckdate!=null && bean.scheckdate==null))
          return false;
        else if(this.scheckdate==null && bean.scheckdate==null){
        }
        else{
          if(!bean.scheckdate.equals(this.scheckdate))
               return false;
     }
      //compare field scheckvouchertype
      if((this.scheckvouchertype==null && bean.scheckvouchertype!=null) || (this.scheckvouchertype!=null && bean.scheckvouchertype==null))
          return false;
        else if(this.scheckvouchertype==null && bean.scheckvouchertype==null){
        }
        else{
          if(!bean.scheckvouchertype.equals(this.scheckvouchertype))
               return false;
     }
      //compare field spaybankcode
      if((this.spaybankcode==null && bean.spaybankcode!=null) || (this.spaybankcode!=null && bean.spaybankcode==null))
          return false;
        else if(this.spaybankcode==null && bean.spaybankcode==null){
        }
        else{
          if(!bean.spaybankcode.equals(this.spaybankcode))
               return false;
     }
      //compare field srecvtime
      if((this.srecvtime==null && bean.srecvtime!=null) || (this.srecvtime!=null && bean.srecvtime==null))
          return false;
        else if(this.srecvtime==null && bean.srecvtime==null){
        }
        else{
          if(!bean.srecvtime.equals(this.srecvtime))
               return false;
     }
      //compare field shold1
      if((this.shold1==null && bean.shold1!=null) || (this.shold1!=null && bean.shold1==null))
          return false;
        else if(this.shold1==null && bean.shold1==null){
        }
        else{
          if(!bean.shold1.equals(this.shold1))
               return false;
     }
      //compare field shold2
      if((this.shold2==null && bean.shold2!=null) || (this.shold2!=null && bean.shold2==null))
          return false;
        else if(this.shold2==null && bean.shold2==null){
        }
        else{
          if(!bean.shold2.equals(this.shold2))
               return false;
     }
      //compare field shold3
      if((this.shold3==null && bean.shold3!=null) || (this.shold3!=null && bean.shold3==null))
          return false;
        else if(this.shold3==null && bean.shold3==null){
        }
        else{
          if(!bean.shold3.equals(this.shold3))
               return false;
     }
      //compare field shold4
      if((this.shold4==null && bean.shold4!=null) || (this.shold4!=null && bean.shold4==null))
          return false;
        else if(this.shold4==null && bean.shold4==null){
        }
        else{
          if(!bean.shold4.equals(this.shold4))
               return false;
     }



        return true;
    }

    /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
  
		int _hash_ = 1;
		
        if(this.sdealno!=null)
          _hash_ = _hash_ * 31+ this.sdealno.hashCode() ;
        if(this.sorgcode!=null)
          _hash_ = _hash_ * 31+ this.sorgcode.hashCode() ;
        if(this.strecode!=null)
          _hash_ = _hash_ * 31+ this.strecode.hashCode() ;
        if(this.sfilename!=null)
          _hash_ = _hash_ * 31+ this.sfilename.hashCode() ;
        if(this.sadmdivcode!=null)
          _hash_ = _hash_ * 31+ this.sadmdivcode.hashCode() ;
        if(this.sstyear!=null)
          _hash_ = _hash_ * 31+ this.sstyear.hashCode() ;
        if(this.svtcode!=null)
          _hash_ = _hash_ * 31+ this.svtcode.hashCode() ;
        if(this.svoucherno!=null)
          _hash_ = _hash_ * 31+ this.svoucherno.hashCode() ;
        if(this.svoucherflag!=null)
          _hash_ = _hash_ * 31+ this.svoucherflag.hashCode() ;
        if(this.sattach!=null)
          _hash_ = _hash_ * 31+ this.sattach.hashCode() ;
        if(this.sreturnerrmsg!=null)
          _hash_ = _hash_ * 31+ this.sreturnerrmsg.hashCode() ;
        if(this.screatdate!=null)
          _hash_ = _hash_ * 31+ this.screatdate.hashCode() ;
        if(this.nmoney!=null)
          _hash_ = _hash_ * 31+ this.nmoney.hashCode() ;
        if(this.sstatus!=null)
          _hash_ = _hash_ * 31+ this.sstatus.hashCode() ;
        if(this.sconfirusercode!=null)
          _hash_ = _hash_ * 31+ this.sconfirusercode.hashCode() ;
        if(this.sverifyusercode!=null)
          _hash_ = _hash_ * 31+ this.sverifyusercode.hashCode() ;
        if(this.sdemo!=null)
          _hash_ = _hash_ * 31+ this.sdemo.hashCode() ;
        if(this.sstampid!=null)
          _hash_ = _hash_ * 31+ this.sstampid.hashCode() ;
        if(this.spackno!=null)
          _hash_ = _hash_ * 31+ this.spackno.hashCode() ;
        if(this.icount!=null)
          _hash_ = _hash_ * 31+ this.icount.hashCode() ;
        if(this.ncheckmoney!=null)
          _hash_ = _hash_ * 31+ this.ncheckmoney.hashCode() ;
        if(this.icheckcount!=null)
          _hash_ = _hash_ * 31+ this.icheckcount.hashCode() ;
        if(this.tssysupdate!=null)
          _hash_ = _hash_ * 31+ this.tssysupdate.hashCode() ;
        if(this.sstampuser!=null)
          _hash_ = _hash_ * 31+ this.sstampuser.hashCode() ;
        if(this.scheckdate!=null)
          _hash_ = _hash_ * 31+ this.scheckdate.hashCode() ;
        if(this.scheckvouchertype!=null)
          _hash_ = _hash_ * 31+ this.scheckvouchertype.hashCode() ;
        if(this.spaybankcode!=null)
          _hash_ = _hash_ * 31+ this.spaybankcode.hashCode() ;
        if(this.srecvtime!=null)
          _hash_ = _hash_ * 31+ this.srecvtime.hashCode() ;
        if(this.shold1!=null)
          _hash_ = _hash_ * 31+ this.shold1.hashCode() ;
        if(this.shold2!=null)
          _hash_ = _hash_ * 31+ this.shold2.hashCode() ;
        if(this.shold3!=null)
          _hash_ = _hash_ * 31+ this.shold3.hashCode() ;
        if(this.shold4!=null)
          _hash_ = _hash_ * 31+ this.shold4.hashCode() ;

		return _hash_;
	
	}

     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvVoucherinfoSxDto bean = new TvVoucherinfoSxDto();

          bean.sdealno = this.sdealno;

          if (this.sorgcode != null)
            bean.sorgcode = new String(this.sorgcode);
          if (this.strecode != null)
            bean.strecode = new String(this.strecode);
          if (this.sfilename != null)
            bean.sfilename = new String(this.sfilename);
          if (this.sadmdivcode != null)
            bean.sadmdivcode = new String(this.sadmdivcode);
          if (this.sstyear != null)
            bean.sstyear = new String(this.sstyear);
          if (this.svtcode != null)
            bean.svtcode = new String(this.svtcode);
          if (this.svoucherno != null)
            bean.svoucherno = new String(this.svoucherno);
          if (this.svoucherflag != null)
            bean.svoucherflag = new String(this.svoucherflag);
          if (this.sattach != null)
            bean.sattach = new String(this.sattach);
          if (this.sreturnerrmsg != null)
            bean.sreturnerrmsg = new String(this.sreturnerrmsg);
          if (this.screatdate != null)
            bean.screatdate = new String(this.screatdate);
          if (this.nmoney != null)
            bean.nmoney = new BigDecimal(this.nmoney.toString());
          if (this.sstatus != null)
            bean.sstatus = new String(this.sstatus);
          if (this.sconfirusercode != null)
            bean.sconfirusercode = new String(this.sconfirusercode);
          if (this.sverifyusercode != null)
            bean.sverifyusercode = new String(this.sverifyusercode);
          if (this.sdemo != null)
            bean.sdemo = new String(this.sdemo);
          if (this.sstampid != null)
            bean.sstampid = new String(this.sstampid);
          if (this.spackno != null)
            bean.spackno = new String(this.spackno);
          if (this.icount != null)
            bean.icount = new Integer(this.icount.toString());
          if (this.ncheckmoney != null)
            bean.ncheckmoney = new BigDecimal(this.ncheckmoney.toString());
          if (this.icheckcount != null)
            bean.icheckcount = new Integer(this.icheckcount.toString());
          if (this.tssysupdate != null)
            bean.tssysupdate = (Timestamp) this.tssysupdate.clone();
          if (this.sstampuser != null)
            bean.sstampuser = new String(this.sstampuser);
          if (this.scheckdate != null)
            bean.scheckdate = new String(this.scheckdate);
          if (this.scheckvouchertype != null)
            bean.scheckvouchertype = new String(this.scheckvouchertype);
          if (this.spaybankcode != null)
            bean.spaybankcode = new String(this.spaybankcode);
          if (this.srecvtime != null)
            bean.srecvtime = (Timestamp) this.srecvtime.clone();
          if (this.shold1 != null)
            bean.shold1 = new String(this.shold1);
          if (this.shold2 != null)
            bean.shold2 = new String(this.shold2);
          if (this.shold3 != null)
            bean.shold3 = new String(this.shold3);
          if (this.shold4 != null)
            bean.shold4 = new String(this.shold4);
  
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = "; ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvVoucherinfoSxDto").append(sep);
        sb.append("[sdealno]").append(" = ").append(sdealno).append(sep);
        sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
        sb.append("[strecode]").append(" = ").append(strecode).append(sep);
        sb.append("[sfilename]").append(" = ").append(sfilename).append(sep);
        sb.append("[sadmdivcode]").append(" = ").append(sadmdivcode).append(sep);
        sb.append("[sstyear]").append(" = ").append(sstyear).append(sep);
        sb.append("[svtcode]").append(" = ").append(svtcode).append(sep);
        sb.append("[svoucherno]").append(" = ").append(svoucherno).append(sep);
        sb.append("[svoucherflag]").append(" = ").append(svoucherflag).append(sep);
        sb.append("[sattach]").append(" = ").append(sattach).append(sep);
        sb.append("[sreturnerrmsg]").append(" = ").append(sreturnerrmsg).append(sep);
        sb.append("[screatdate]").append(" = ").append(screatdate).append(sep);
        sb.append("[nmoney]").append(" = ").append(nmoney).append(sep);
        sb.append("[sstatus]").append(" = ").append(sstatus).append(sep);
        sb.append("[sconfirusercode]").append(" = ").append(sconfirusercode).append(sep);
        sb.append("[sverifyusercode]").append(" = ").append(sverifyusercode).append(sep);
        sb.append("[sdemo]").append(" = ").append(sdemo).append(sep);
        sb.append("[sstampid]").append(" = ").append(sstampid).append(sep);
        sb.append("[spackno]").append(" = ").append(spackno).append(sep);
        sb.append("[icount]").append(" = ").append(icount).append(sep);
        sb.append("[ncheckmoney]").append(" = ").append(ncheckmoney).append(sep);
        sb.append("[icheckcount]").append(" = ").append(icheckcount).append(sep);
        sb.append("[tssysupdate]").append(" = ").append(tssysupdate).append(sep);
        sb.append("[sstampuser]").append(" = ").append(sstampuser).append(sep);
        sb.append("[scheckdate]").append(" = ").append(scheckdate).append(sep);
        sb.append("[scheckvouchertype]").append(" = ").append(scheckvouchertype).append(sep);
        sb.append("[spaybankcode]").append(" = ").append(spaybankcode).append(sep);
        sb.append("[srecvtime]").append(" = ").append(srecvtime).append(sep);
        sb.append("[shold1]").append(" = ").append(shold1).append(sep);
        sb.append("[shold2]").append(" = ").append(shold2).append(sep);
        sb.append("[shold3]").append(" = ").append(shold3).append(sep);
        sb.append("[shold4]").append(" = ").append(shold4).append(sep);
            return sb.toString();
    }

  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

    //check field S_DEALNO
      if (this.getSdealno()==null)
             sb.append("S_DEALNO不能为空; ");
      if (this.getSdealno()!=null)
             if (this.getSdealno().getBytes().length > 16)
                sb.append("S_DEALNO宽度不能超过 "+16+"个字符; ");
    
    //check field S_ORGCODE
      if (this.getSorgcode()==null)
             sb.append("S_ORGCODE不能为空; ");
      if (this.getSorgcode()!=null)
             if (this.getSorgcode().getBytes().length > 12)
                sb.append("S_ORGCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_TRECODE
      if (this.getStrecode()==null)
             sb.append("S_TRECODE不能为空; ");
      if (this.getStrecode()!=null)
             if (this.getStrecode().getBytes().length > 10)
                sb.append("S_TRECODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_FILENAME
      if (this.getSfilename()==null)
             sb.append("S_FILENAME不能为空; ");
      if (this.getSfilename()!=null)
             if (this.getSfilename().getBytes().length > 100)
                sb.append("S_FILENAME宽度不能超过 "+100+"个字符; ");
    
    //check field S_ADMDIVCODE
      if (this.getSadmdivcode()==null)
             sb.append("S_ADMDIVCODE不能为空; ");
      if (this.getSadmdivcode()!=null)
             if (this.getSadmdivcode().getBytes().length > 10)
                sb.append("S_ADMDIVCODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_STYEAR
      if (this.getSstyear()==null)
             sb.append("S_STYEAR不能为空; ");
      if (this.getSstyear()!=null)
             if (this.getSstyear().getBytes().length > 4)
                sb.append("S_STYEAR宽度不能超过 "+4+"个字符; ");
    
    //check field S_VTCODE
      if (this.getSvtcode()==null)
             sb.append("S_VTCODE不能为空; ");
      if (this.getSvtcode()!=null)
             if (this.getSvtcode().getBytes().length > 10)
                sb.append("S_VTCODE宽度不能超过 "+10+"个字符; ");
    
    //check field S_VOUCHERNO
      if (this.getSvoucherno()==null)
             sb.append("S_VOUCHERNO不能为空; ");
      if (this.getSvoucherno()!=null)
             if (this.getSvoucherno().getBytes().length > 42)
                sb.append("S_VOUCHERNO宽度不能超过 "+42+"个字符; ");
    
    //check field S_VOUCHERFLAG
      if (this.getSvoucherflag()==null)
             sb.append("S_VOUCHERFLAG不能为空; ");
      if (this.getSvoucherflag()!=null)
             if (this.getSvoucherflag().getBytes().length > 1)
                sb.append("S_VOUCHERFLAG宽度不能超过 "+1+"个字符; ");
    
    //check field S_ATTACH
      if (this.getSattach()!=null)
             if (this.getSattach().getBytes().length > 32)
                sb.append("S_ATTACH宽度不能超过 "+32+"个字符; ");
    
    //check field S_RETURNERRMSG
      if (this.getSreturnerrmsg()!=null)
             if (this.getSreturnerrmsg().getBytes().length > 1024)
                sb.append("S_RETURNERRMSG宽度不能超过 "+1024+"个字符; ");
    
    //check field S_CREATDATE
      if (this.getScreatdate()==null)
             sb.append("S_CREATDATE不能为空; ");
      if (this.getScreatdate()!=null)
             if (this.getScreatdate().getBytes().length > 8)
                sb.append("S_CREATDATE宽度不能超过 "+8+"个字符; ");
    
    //check field N_MONEY
      if (this.getNmoney()==null)
             sb.append("N_MONEY不能为空; ");
      
    //check field S_STATUS
      if (this.getSstatus()==null)
             sb.append("S_STATUS不能为空; ");
      if (this.getSstatus()!=null)
             if (this.getSstatus().getBytes().length > 4)
                sb.append("S_STATUS宽度不能超过 "+4+"个字符; ");
    
    //check field S_CONFIRUSERCODE
      if (this.getSconfirusercode()!=null)
             if (this.getSconfirusercode().getBytes().length > 12)
                sb.append("S_CONFIRUSERCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_VERIFYUSERCODE
      if (this.getSverifyusercode()!=null)
             if (this.getSverifyusercode().getBytes().length > 12)
                sb.append("S_VERIFYUSERCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_DEMO
      if (this.getSdemo()!=null)
             if (this.getSdemo().getBytes().length > 1024)
                sb.append("S_DEMO宽度不能超过 "+1024+"个字符; ");
    
    //check field S_STAMPID
      if (this.getSstampid()!=null)
             if (this.getSstampid().getBytes().length > 100)
                sb.append("S_STAMPID宽度不能超过 "+100+"个字符; ");
    
    //check field S_PACKNO
      if (this.getSpackno()!=null)
             if (this.getSpackno().getBytes().length > 8)
                sb.append("S_PACKNO宽度不能超过 "+8+"个字符; ");
    
    //check field I_COUNT
      
    //check field N_CHECKMONEY
      
    //check field I_CHECKCOUNT
      
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  
    //check field S_STAMPUSER
      if (this.getSstampuser()!=null)
             if (this.getSstampuser().getBytes().length > 100)
                sb.append("S_STAMPUSER宽度不能超过 "+100+"个字符; ");
    
    //check field S_CHECKDATE
      if (this.getScheckdate()!=null)
             if (this.getScheckdate().getBytes().length > 8)
                sb.append("S_CHECKDATE宽度不能超过 "+8+"个字符; ");
    
    //check field S_CHECKVOUCHERTYPE
      if (this.getScheckvouchertype()!=null)
             if (this.getScheckvouchertype().getBytes().length > 4)
                sb.append("S_CHECKVOUCHERTYPE宽度不能超过 "+4+"个字符; ");
    
    //check field S_PAYBANKCODE
      if (this.getSpaybankcode()!=null)
             if (this.getSpaybankcode().getBytes().length > 12)
                sb.append("S_PAYBANKCODE宽度不能超过 "+12+"个字符; ");
    
    //check field S_RECVTIME
      
    //check field S_HOLD1
      if (this.getShold1()!=null)
             if (this.getShold1().getBytes().length > 60)
                sb.append("S_HOLD1宽度不能超过 "+60+"个字符; ");
    
    //check field S_HOLD2
      if (this.getShold2()!=null)
             if (this.getShold2().getBytes().length > 60)
                sb.append("S_HOLD2宽度不能超过 "+60+"个字符; ");
    
    //check field S_HOLD3
      if (this.getShold3()!=null)
             if (this.getShold3().getBytes().length > 60)
                sb.append("S_HOLD3宽度不能超过 "+60+"个字符; ");
    
    //check field S_HOLD4
      if (this.getShold4()!=null)
             if (this.getShold4().getBytes().length > 60)
                sb.append("S_HOLD4宽度不能超过 "+60+"个字符; ");
    

 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid(String[] _columnNames)
  {
  	StringBuffer sb = new StringBuffer() ;
    // check columnNames
    String checkNameMsg = checkColumnNamesValid(_columnNames);
    if (checkNameMsg != null) {
         return checkNameMsg;
    }
    //check field S_DEALNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEALNO")) {
               if (this.getSdealno()==null)
                    sb.append("S_DEALNO 不能为空; ");
               if (this.getSdealno()!=null)
                    if (this.getSdealno().getBytes().length > 16)
                        sb.append("S_DEALNO 宽度不能超过 "+16+"个字符");
             break;
         }
  }
    
    //check field S_ORGCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ORGCODE")) {
               if (this.getSorgcode()==null)
                    sb.append("S_ORGCODE 不能为空; ");
               if (this.getSorgcode()!=null)
                    if (this.getSorgcode().getBytes().length > 12)
                        sb.append("S_ORGCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_TRECODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_TRECODE")) {
               if (this.getStrecode()==null)
                    sb.append("S_TRECODE 不能为空; ");
               if (this.getStrecode()!=null)
                    if (this.getStrecode().getBytes().length > 10)
                        sb.append("S_TRECODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_FILENAME
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_FILENAME")) {
               if (this.getSfilename()==null)
                    sb.append("S_FILENAME 不能为空; ");
               if (this.getSfilename()!=null)
                    if (this.getSfilename().getBytes().length > 100)
                        sb.append("S_FILENAME 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_ADMDIVCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ADMDIVCODE")) {
               if (this.getSadmdivcode()==null)
                    sb.append("S_ADMDIVCODE 不能为空; ");
               if (this.getSadmdivcode()!=null)
                    if (this.getSadmdivcode().getBytes().length > 10)
                        sb.append("S_ADMDIVCODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_STYEAR
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_STYEAR")) {
               if (this.getSstyear()==null)
                    sb.append("S_STYEAR 不能为空; ");
               if (this.getSstyear()!=null)
                    if (this.getSstyear().getBytes().length > 4)
                        sb.append("S_STYEAR 宽度不能超过 "+4+"个字符");
             break;
         }
  }
    
    //check field S_VTCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VTCODE")) {
               if (this.getSvtcode()==null)
                    sb.append("S_VTCODE 不能为空; ");
               if (this.getSvtcode()!=null)
                    if (this.getSvtcode().getBytes().length > 10)
                        sb.append("S_VTCODE 宽度不能超过 "+10+"个字符");
             break;
         }
  }
    
    //check field S_VOUCHERNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VOUCHERNO")) {
               if (this.getSvoucherno()==null)
                    sb.append("S_VOUCHERNO 不能为空; ");
               if (this.getSvoucherno()!=null)
                    if (this.getSvoucherno().getBytes().length > 42)
                        sb.append("S_VOUCHERNO 宽度不能超过 "+42+"个字符");
             break;
         }
  }
    
    //check field S_VOUCHERFLAG
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VOUCHERFLAG")) {
               if (this.getSvoucherflag()==null)
                    sb.append("S_VOUCHERFLAG 不能为空; ");
               if (this.getSvoucherflag()!=null)
                    if (this.getSvoucherflag().getBytes().length > 1)
                        sb.append("S_VOUCHERFLAG 宽度不能超过 "+1+"个字符");
             break;
         }
  }
    
    //check field S_ATTACH
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_ATTACH")) {
                 if (this.getSattach()!=null)
                    if (this.getSattach().getBytes().length > 32)
                        sb.append("S_ATTACH 宽度不能超过 "+32+"个字符");
             break;
         }
  }
    
    //check field S_RETURNERRMSG
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_RETURNERRMSG")) {
                 if (this.getSreturnerrmsg()!=null)
                    if (this.getSreturnerrmsg().getBytes().length > 1024)
                        sb.append("S_RETURNERRMSG 宽度不能超过 "+1024+"个字符");
             break;
         }
  }
    
    //check field S_CREATDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CREATDATE")) {
               if (this.getScreatdate()==null)
                    sb.append("S_CREATDATE 不能为空; ");
               if (this.getScreatdate()!=null)
                    if (this.getScreatdate().getBytes().length > 8)
                        sb.append("S_CREATDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field N_MONEY
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("N_MONEY")) {
               if (this.getNmoney()==null)
                    sb.append("N_MONEY 不能为空; ");
               break;
         }
  }
    
    //check field S_STATUS
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_STATUS")) {
               if (this.getSstatus()==null)
                    sb.append("S_STATUS 不能为空; ");
               if (this.getSstatus()!=null)
                    if (this.getSstatus().getBytes().length > 4)
                        sb.append("S_STATUS 宽度不能超过 "+4+"个字符");
             break;
         }
  }
    
    //check field S_CONFIRUSERCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CONFIRUSERCODE")) {
                 if (this.getSconfirusercode()!=null)
                    if (this.getSconfirusercode().getBytes().length > 12)
                        sb.append("S_CONFIRUSERCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_VERIFYUSERCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_VERIFYUSERCODE")) {
                 if (this.getSverifyusercode()!=null)
                    if (this.getSverifyusercode().getBytes().length > 12)
                        sb.append("S_VERIFYUSERCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_DEMO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_DEMO")) {
                 if (this.getSdemo()!=null)
                    if (this.getSdemo().getBytes().length > 1024)
                        sb.append("S_DEMO 宽度不能超过 "+1024+"个字符");
             break;
         }
  }
    
    //check field S_STAMPID
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_STAMPID")) {
                 if (this.getSstampid()!=null)
                    if (this.getSstampid().getBytes().length > 100)
                        sb.append("S_STAMPID 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_PACKNO
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PACKNO")) {
                 if (this.getSpackno()!=null)
                    if (this.getSpackno().getBytes().length > 8)
                        sb.append("S_PACKNO 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field I_COUNT
          
    //check field N_CHECKMONEY
          
    //check field I_CHECKCOUNT
          
    //don't need check field TS_SYSUPDATE,it is UpdateTimeStamp column
  
    //check field S_STAMPUSER
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_STAMPUSER")) {
                 if (this.getSstampuser()!=null)
                    if (this.getSstampuser().getBytes().length > 100)
                        sb.append("S_STAMPUSER 宽度不能超过 "+100+"个字符");
             break;
         }
  }
    
    //check field S_CHECKDATE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CHECKDATE")) {
                 if (this.getScheckdate()!=null)
                    if (this.getScheckdate().getBytes().length > 8)
                        sb.append("S_CHECKDATE 宽度不能超过 "+8+"个字符");
             break;
         }
  }
    
    //check field S_CHECKVOUCHERTYPE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_CHECKVOUCHERTYPE")) {
                 if (this.getScheckvouchertype()!=null)
                    if (this.getScheckvouchertype().getBytes().length > 4)
                        sb.append("S_CHECKVOUCHERTYPE 宽度不能超过 "+4+"个字符");
             break;
         }
  }
    
    //check field S_PAYBANKCODE
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_PAYBANKCODE")) {
                 if (this.getSpaybankcode()!=null)
                    if (this.getSpaybankcode().getBytes().length > 12)
                        sb.append("S_PAYBANKCODE 宽度不能超过 "+12+"个字符");
             break;
         }
  }
    
    //check field S_RECVTIME
          
    //check field S_HOLD1
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD1")) {
                 if (this.getShold1()!=null)
                    if (this.getShold1().getBytes().length > 60)
                        sb.append("S_HOLD1 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_HOLD2
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD2")) {
                 if (this.getShold2()!=null)
                    if (this.getShold2().getBytes().length > 60)
                        sb.append("S_HOLD2 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_HOLD3
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD3")) {
                 if (this.getShold3()!=null)
                    if (this.getShold3().getBytes().length > 60)
                        sb.append("S_HOLD3 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
    //check field S_HOLD4
     for (int i = 0; i < _columnNames.length; i++) {
        if (((String) _columnNames[i]).equals("S_HOLD4")) {
                 if (this.getShold4()!=null)
                    if (this.getShold4().getBytes().length > 60)
                        sb.append("S_HOLD4 宽度不能超过 "+60+"个字符");
             break;
         }
  }
    
 	String msg = sb.toString() ;
	if (msg.length() == 0)
		  return null ;

  return  msg;
  }
  /* Returns value valid checking String , NULL is Valid*/
	public String checkValidExcept(String[] _columnNames) {
		String msg = checkColumnNamesValid(_columnNames);
		if (msg != null) {
			return msg;
		}
		String[] columnCheckNames = new String[columnNames().length
				- _columnNames.length];
		int k = 0;
		for (int i = 0; i < columnNames().length; i++) {
			boolean checkNameInColumn = true;
			for (int j = 0; j < _columnNames.length; j++) {
				if (_columnNames[i].equals(columnNames()[j])) {
					checkNameInColumn = false;
					break;
				}
			}
			if (checkNameInColumn) {
				columnCheckNames[k] = columnNames()[i];
				k++;
			}
		}
		return checkValid(columnCheckNames);
	}
	/* Returns value valid checking String , NULL is Valid */
	public String checkColumnNamesValid(String[] _columnNames) {
		StringBuffer sb = new StringBuffer();
		if (_columnNames.length > columnNames().length) {
			return "输入字段个数多于表中字段个数; ";
		}
		// check columnNames
		for (int i = 0; i < _columnNames.length; i++) {
			boolean checkNameValid = false;
			for (int j = 0; j < columnNames().length; j++) {
				if (_columnNames[i] != null
						&& _columnNames[i].equals(columnNames()[j])) {
					checkNameValid = true;
					break;
				}
			}
			if (!checkNameValid)
				sb.append("输入字段 " + _columnNames[i] + " 不在该表字段中; ");
		}
		String msg = sb.toString();
		if (msg.length() == 0)
			return null;

		return msg;
	}
/*******************************************************
*
*  implement IDto
*
*****************************************************/

  /* if this Dto has children Dtos*/
  public boolean  isParent() {
     return false;
  };

  /* get the children Dtos if this has children*/
  public IDto[]  getChildren() {
     return null;
  };

  /* set the children Dtos if this has children*/
  public void  setChildren(IDto[] _dtos) 
  {
     throw new RuntimeException("此dto没有相关联的子dto，不能进行此操作");
  };
  
  /* return the IPK class  */
    public IPK      getPK(){
      TvVoucherinfoSxPK pk = new TvVoucherinfoSxPK();
      pk.setSdealno(getSdealno());
      return pk;
    };
}
