<?xml version="1.0" encoding="GBK"?>
<CFX>
	<HEAD>
		<VER>${cfx.HEAD.VER}</VER>
		<SRC>${cfx.HEAD.SRC}</SRC>
		<DES>${cfx.HEAD.DES}</DES>
		<APP>${cfx.HEAD.APP}</APP>
		<MsgNo>${cfx.HEAD.MsgNo}</MsgNo>
		<MsgID>${cfx.HEAD.MsgID}</MsgID>
		<MsgRef>${cfx.HEAD.MsgRef}</MsgRef>
		<WorkDate>${cfx.HEAD.WorkDate}</WorkDate>
	</HEAD>
	<MSG>
		<GetMsg9111>
			<SendOrgCode>${cfx.MSG.GetMsg9111.SendOrgCode}</SendOrgCode>
			<EntrustDate>${cfx.MSG.GetMsg9111.EntrustDate}</EntrustDate>
			<OriPackMsgNo>${cfx.MSG.GetMsg9111.OriPackMsgNo}</OriPackMsgNo>
			<OriSendOrgCode>${cfx.MSG.GetMsg9111.OriSendOrgCode}</OriSendOrgCode>
			<OriEntrustDate>${cfx.MSG.GetMsg9111.OriEntrustDate}</OriEntrustDate>
			<OriPackNo>${cfx.MSG.GetMsg9111.OriPackNo}</OriPackNo>
			<OrgType>${cfx.MSG.GetMsg9111.OrgType}</OrgType>
		</GetMsg9111>
	</MSG>
</CFX>