<?xml version="1.0" encoding="GBK"?>
<CFX>
	<HEAD>
		<VER>${cfx.HEAD.VER}</VER>
		<SRC>${cfx.HEAD.SRC}</SRC>
		<DES>${cfx.HEAD.DES}</DES>
		<APP>${cfx.HEAD.APP}</APP>
		<MsgNo>${cfx.HEAD.MsgNo}</MsgNo>
		<MsgID>${cfx.HEAD.MsgID}</MsgID>
		<MsgRef>${cfx.HEAD.MsgRef}</MsgRef>
		<WorkDate>${cfx.HEAD.WorkDate}</WorkDate>
	</HEAD>
	<MSG>
		<RequestHead5001>
			<SendOrgCode>${cfx.MSG.RequestHead5001.SendOrgCode}</SendOrgCode>
			<ReportDate>${cfx.MSG.RequestHead5001.ReportDate}</ReportDate>
		</RequestHead5001>
		<RequestReport5001>
			<NrBudget>${cfx.MSG.RequestReport5001.NrBudget}</NrBudget>
			<NrDrawBack>${cfx.MSG.RequestReport5001.NrDrawBack}</NrDrawBack>
			<NrRemove>${cfx.MSG.RequestReport5001.NrRemove}</NrRemove>
			<Amount>${cfx.MSG.RequestReport5001.Amount}</Amount>
			<NrShare>${cfx.MSG.RequestReport5001.NrShare}</NrShare>
			<TrBudget>${cfx.MSG.RequestReport5001.TrBudget}</TrBudget>
			<TrDrawBack>${cfx.MSG.RequestReport5001.TrDrawBack}</TrDrawBack>
			<TrRemove>${cfx.MSG.RequestReport5001.TrRemove}</TrRemove>
			<TrShare>${cfx.MSG.RequestReport5001.TrShare}</TrShare>
			<Stock>${cfx.MSG.RequestReport5001.Stock}</Stock>
		</RequestReport5001>
	</MSG>
</CFX>