<?xml version="1.0" encoding="GBK"?>
<CFX>
	<HEAD>
		<VER>${cfx.HEAD.VER}</VER>
		<SRC>${cfx.HEAD.SRC}</SRC>
		<DES>${cfx.HEAD.DES}</DES>
		<APP>${cfx.HEAD.APP}</APP>
		<MsgNo>${cfx.HEAD.MsgNo}</MsgNo>
		<MsgID>${cfx.HEAD.MsgID}</MsgID>
		<MsgRef>${cfx.HEAD.MsgRef}</MsgRef>
		<WorkDate>${cfx.HEAD.WorkDate}</WorkDate>
	</HEAD>
     <MSG>
        <MsgReturn3001>
            <OriMsgNo>${cfx.MSG.MsgReturn3001.OriMsgNo}</OriMsgNo>
            <Result>${cfx.MSG.MsgReturn3001.Result}</Result>
            <AddWord>${cfx.MSG.MsgReturn3001.AddWord}</AddWord>
            <Information>${cfx.MSG.MsgReturn3001.Information}</Information>
        </MsgReturn3001>
    </MSG>
</CFX>
