<?xml version="1.0" encoding="GBK"?>
<CFX>
	<HEAD>
		<VER>${cfx.HEAD.VER}</VER>
		<SRC>${cfx.HEAD.SRC}</SRC>
		<DES>${cfx.HEAD.DES}</DES>
		<APP>${cfx.HEAD.APP}</APP>
		<MsgNo>${cfx.HEAD.MsgNo}</MsgNo>
		<MsgID>${cfx.HEAD.MsgID}</MsgID>
		<MsgRef>${cfx.HEAD.MsgRef}</MsgRef>
		<WorkDate>${cfx.HEAD.WorkDate}</WorkDate>
	</HEAD>
	<MSG>
		<RushReturn2021>
			<TaxOrgCode>${cfx.MSG.RushReturn2021.TaxOrgCode}</TaxOrgCode>
			<OriCancelNo>${cfx.MSG.RushReturn2021.OriCancelNo}</OriCancelNo>
			<OriCancelDate>${cfx.MSG.RushReturn2021.OriCancelDate}</OriCancelDate>
			<OriTraNo>${cfx.MSG.RushReturn2021.OriTraNo}</OriTraNo>
			<OriEntrustDate>${cfx.MSG.RushReturn2021.OriEntrustDate}</OriEntrustDate>
			<CancelAnswer>${cfx.MSG.RushReturn2021.CancelAnswer}</CancelAnswer>
			<AddWord>${cfx.MSG.RushReturn2021.AddWord}</AddWord>
		</RushReturn2021>
	</MSG>
</CFX>