<?xml version="1.0" encoding="GBK"?>
<Voucher>
	<AdmDivCode>${Voucher.AdmDivCode}</AdmDivCode>
	<StYear>${Voucher.StYear}</StYear>
	<VtCode>${Voucher.VtCode}</VtCode>
	<VouDate>${Voucher.VouDate}</VouDate>
	<VoucherNo>${Voucher.VoucherNo}</VoucherNo>
	<DataEle>${Voucher.DataEle}</DataEle>
	<DataEleName>${Voucher.DataEleName}</DataEleName>
	<SupDepName>${Voucher.SupDepName}</SupDepName>
	<SupDepCode>${Voucher.SupDepCode}</SupDepCode>
	<UnitChangeStatus>${Voucher.UnitChangeStatus}</UnitChangeStatus>
	<IssuedDate>${Voucher.IssuedDate}</IssuedDate>
	<EffectiveDate>${Voucher.EffectiveDate}</EffectiveDate>
	<Subjectcode>${Voucher.Subjectcode}</Subjectcode>
	<Subjectname>${Voucher.Subjectname}</Subjectname>
	<Subjecttype>${Voucher.Subjecttype}</Subjecttype>
	<Subjectclassification>${Voucher.Subjectclassification}</Subjectclassification>
	<IEsign>${Voucher.IEsign}</IEsign>
	<Entrymark>${Voucher.Entrymark}</Entrymark>
	<Subjectattribute>${Voucher.Subjectattribute}</Subjectattribute>
	<Allocationmark>${Voucher.Allocationmark}</Allocationmark>
	<SubjectcodeSimplify>${Voucher.SubjectcodeSimplify}</SubjectcodeSimplify>
	
	<FiscalCode>${Voucher.FiscalCode}</FiscalCode>
	<TaxCode>${Voucher.TaxCode}</TaxCode>
	<SuperiorsCode>${Voucher.SuperiorsCode}</SuperiorsCode>
	<UniformCode>${Voucher.UniformCode}</UniformCode>
	<Statisticalcode>${Voucher.Statisticalcode}</Statisticalcode>
	<Paylinenumber>${Voucher.Paylinenumber}</Paylinenumber>
	<Status>${Voucher.Status}</Status>
	<Liquidationlinenumber>${Voucher.Liquidationlinenumber}</Liquidationlinenumber>
	<City>${Voucher.City}</City>
	<Participantsfullname>${Voucher.Participantsfullname}</Participantsfullname>
	<effectivedate>${Voucher.effectivedate}</effectivedate>
	<Expirationdate>${Voucher.Expirationdate}</Expirationdate>
	<Remark>${Voucher.Remark}</Remark>
	<ZeroAccount>${Voucher.ZeroAccount}</ZeroAccount>
	<ZBAsstate>${Voucher.ZBAsstate}</ZBAsstate>
	<Zerotime>${Voucher.Zerotime}</Zerotime>
	<ZeroBanknumber>${Voucher.ZeroBanknumber}</ZeroBanknumber>
	<ZeroBankname>${Voucher.ZeroBankname}</ZeroBankname>
	<Zerocodingunit>${Voucher.Zerocodingunit}</Zerocodingunit>
	<ZeroAccountName>${Voucher.ZeroAccountName}</ZeroAccountName>
	<Hold1>${Voucher.Hold1}</Hold1>
	<Hold2>${Voucher.Hold2}</Hold2>
	<Hold3>${Voucher.Hold3}</Hold3>
	<Hold4>${Voucher.Hold4}</Hold4>
</Voucher>