<?xml version="1.0" encoding="GBK"?>
<Voucher>
	<AdmDivCode>${Voucher.AdmDivCode}</AdmDivCode>
	<StYear>${Voucher.StYear}</StYear>
	<VtCode>${Voucher.VtCode}</VtCode>
	<VouDate>${Voucher.VouDate}</VouDate>
	<VoucherNo>${Voucher.VoucherNo}</VoucherNo>
	<VoucherCheckNo>${Voucher.VoucherCheckNo}</VoucherCheckNo>
	<TreCode>${Voucher.TreCode}</TreCode>
	<TreName>${Voucher.TreName}</TreName>
	<AcctNo>${Voucher.AcctNo}</AcctNo>
	<AcctName>${Voucher.AcctName}</AcctName>
	<BeginDate>${Voucher.BeginDate}</BeginDate>
	<EndDate>${Voucher.EndDate}</EndDate>
	<AllNum>${Voucher.AllNum}</AllNum>
	<LastAmt>${Voucher.LastAmt}</LastAmt>
	<AcctAmt>${Voucher.AcctAmt}</AcctAmt>
	<XCheckResult></XCheckResult>
	<XDiffNum></XDiffNum>
	<XCheckReason></XCheckReason>
	<Hold1>${Voucher.Hold1}</Hold1>
	<Hold2>${Voucher.Hold2}</Hold2>
	<DetailList>
	  <#list Voucher.DetailList.Detail as var>
	  <Detail>
		<Id>${var.Id}</Id>
		<AcctDate>${var.AcctDate}</AcctDate>
		<IncomeAmt>${var.IncomeAmt}</IncomeAmt>
		<PayAmt>${var.PayAmt}</PayAmt>
		<XIncomeAmt></XIncomeAmt>
		<XPayAmt></XPayAmt>
		<XCheckResult></XCheckResult>
		<XCheckReason></XCheckReason>
		<Hold1>${var.Hold1}</Hold1>
		<Hold2>${var.Hold2}</Hold2>
		<Hold3>${var.Hold3}</Hold3>
		<Hold4>${var.Hold4}</Hold4>	  
	 </Detail>
	</#list> 
	</DetailList>  
</Voucher>