package com.cfcc.itfe.persistence.pk;

import java.sql.Date;
import java.math.BigDecimal;
import java.sql.Time;
import java.sql.Timestamp ;
import com.cfcc.jaf.persistence.jaform.parent.IPK ;

/**
 * <p>Title: PK of table: TD_TAXORG_MERGER</p>
 * <p>Description:  PK Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:57 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *
 *  pk.vm version timestamp: 2007-04-06 08:30:00
 * 
 * @author win7
 */

public class TdTaxorgMergerPK implements IPK
{
    /**
    *   S_BOOKORGCODE CHARACTER  , PK   , NOT NULL        */
    protected String sbookorgcode;
    /**
    *   S_PRETAXORGCODE VARCHAR  , PK   , NOT NULL        */
    protected String spretaxorgcode;
    /**
    *   S_AFTERTAXORGCODE VARCHAR  , PK   , NOT NULL        */
    protected String saftertaxorgcode;



    /*  Getter S_BOOKORGCODE, PK , NOT NULL   */
    public String getSbookorgcode()
    {
        return sbookorgcode;
    }

     /*   Setter S_BOOKORGCODE, PK , NOT NULL   */
    public void setSbookorgcode(String _sbookorgcode) {
        this.sbookorgcode = _sbookorgcode;
    }
    /*  Getter S_PRETAXORGCODE, PK , NOT NULL   */
    public String getSpretaxorgcode()
    {
        return spretaxorgcode;
    }

     /*   Setter S_PRETAXORGCODE, PK , NOT NULL   */
    public void setSpretaxorgcode(String _spretaxorgcode) {
        this.spretaxorgcode = _spretaxorgcode;
    }
    /*  Getter S_AFTERTAXORGCODE, PK , NOT NULL   */
    public String getSaftertaxorgcode()
    {
        return saftertaxorgcode;
    }

     /*   Setter S_AFTERTAXORGCODE, PK , NOT NULL   */
    public void setSaftertaxorgcode(String _saftertaxorgcode) {
        this.saftertaxorgcode = _saftertaxorgcode;
    }


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TdTaxorgMergerPK))
            return false;

        TdTaxorgMergerPK bean = (TdTaxorgMergerPK) obj;

	      //compare field sbookorgcode
      if((this.sbookorgcode==null && bean.sbookorgcode!=null) || (this.sbookorgcode!=null && bean.sbookorgcode==null))
          return false;
        else if(this.sbookorgcode==null && bean.sbookorgcode==null){
        }
        else{
          if(!bean.sbookorgcode.equals(this.sbookorgcode))
               return false;
     }
  	      //compare field spretaxorgcode
      if((this.spretaxorgcode==null && bean.spretaxorgcode!=null) || (this.spretaxorgcode!=null && bean.spretaxorgcode==null))
          return false;
        else if(this.spretaxorgcode==null && bean.spretaxorgcode==null){
        }
        else{
          if(!bean.spretaxorgcode.equals(this.spretaxorgcode))
               return false;
     }
  	      //compare field saftertaxorgcode
      if((this.saftertaxorgcode==null && bean.saftertaxorgcode!=null) || (this.saftertaxorgcode!=null && bean.saftertaxorgcode==null))
          return false;
        else if(this.saftertaxorgcode==null && bean.saftertaxorgcode==null){
        }
        else{
          if(!bean.saftertaxorgcode.equals(this.saftertaxorgcode))
               return false;
     }
          return true;
    }


   /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
		int __hash__ = 1;
		

        if(this.sbookorgcode!=null)
          __hash__ = __hash__ * 31+ this.sbookorgcode.hashCode() ;

        if(this.spretaxorgcode!=null)
          __hash__ = __hash__ * 31+ this.spretaxorgcode.hashCode() ;

        if(this.saftertaxorgcode!=null)
          __hash__ = __hash__ * 31+ this.saftertaxorgcode.hashCode() ;

		return __hash__;
	
	}



     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TdTaxorgMergerPK bean = new TdTaxorgMergerPK();
          if(this.sbookorgcode!=null){
                  bean.sbookorgcode = new String(this.sbookorgcode);
            }
             if(this.spretaxorgcode!=null){
                  bean.spretaxorgcode = new String(this.spretaxorgcode);
            }
             if(this.saftertaxorgcode!=null){
                  bean.saftertaxorgcode = new String(this.saftertaxorgcode);
            }
   
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = ", ";
        StringBuffer sb = new StringBuffer();
        sb.append("TdTaxorgMergerPK").append(":");
            sb.append("[sbookorgcode]").append(" = ").append(sbookorgcode).append(sep);
            sb.append("[spretaxorgcode]").append(" = ").append(spretaxorgcode).append(sep);
            sb.append("[saftertaxorgcode]").append(" = ").append(saftertaxorgcode).append(sep);
            return sb.toString();
    }


     /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

          
        if (this.getSbookorgcode()==null)
              sb.append("数据库表：TD_TAXORG_MERGER 字段：S_BOOKORGCODE 不能为空; ");
                
       if (this.getSbookorgcode()!=null)
          if (this.getSbookorgcode().getBytes().length > 12)
             sb.append("数据库表：TD_TAXORG_MERGER 字段：S_BOOKORGCODE 宽度不能超过 "+12);
                
        if (this.getSpretaxorgcode()==null)
              sb.append("数据库表：TD_TAXORG_MERGER 字段：S_PRETAXORGCODE 不能为空; ");
                
       if (this.getSpretaxorgcode()!=null)
          if (this.getSpretaxorgcode().getBytes().length > 20)
             sb.append("数据库表：TD_TAXORG_MERGER 字段：S_PRETAXORGCODE 宽度不能超过 "+20);
                
        if (this.getSaftertaxorgcode()==null)
              sb.append("数据库表：TD_TAXORG_MERGER 字段：S_AFTERTAXORGCODE 不能为空; ");
                
       if (this.getSaftertaxorgcode()!=null)
          if (this.getSaftertaxorgcode().getBytes().length > 20)
             sb.append("数据库表：TD_TAXORG_MERGER 字段：S_AFTERTAXORGCODE 宽度不能超过 "+20);
        	String msg = sb.toString() ;
	if (msg.length() == 0)
		return null ;
  	return  msg;
   }

}
