package com.cfcc.itfe.persistence.pk;

import java.sql.Date;
import java.math.BigDecimal;
import java.sql.Time;
import java.sql.Timestamp ;
import com.cfcc.jaf.persistence.jaform.parent.IPK ;

/**
 * <p>Title: PK of table: TS_ASSITFLAGTRANS</p>
 * <p>Description:  PK Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:59 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *
 *  pk.vm version timestamp: 2007-04-06 08:30:00
 * 
 * @author win7
 */

public class TsAssitflagtransPK implements IPK
{
    /**
    *   S_ORGCODE VARCHAR  , PK   , NOT NULL        */
    protected String sorgcode;
    /**
    *   S_BUDGETSUBJECT VARCHAR  , PK   , NOT NULL        */
    protected String sbudgetsubject;
    /**
    *   S_BUDGETLEVEL CHARACTER  , PK   , NOT NULL        */
    protected String sbudgetlevel;
    /**
    *   S_TRECODE CHARACTER  , PK   , NOT NULL        */
    protected String strecode;



    /*  Getter S_ORGCODE, PK , NOT NULL   */
    public String getSorgcode()
    {
        return sorgcode;
    }

     /*   Setter S_ORGCODE, PK , NOT NULL   */
    public void setSorgcode(String _sorgcode) {
        this.sorgcode = _sorgcode;
    }
    /*  Getter S_BUDGETSUBJECT, PK , NOT NULL   */
    public String getSbudgetsubject()
    {
        return sbudgetsubject;
    }

     /*   Setter S_BUDGETSUBJECT, PK , NOT NULL   */
    public void setSbudgetsubject(String _sbudgetsubject) {
        this.sbudgetsubject = _sbudgetsubject;
    }
    /*  Getter S_BUDGETLEVEL, PK , NOT NULL   */
    public String getSbudgetlevel()
    {
        return sbudgetlevel;
    }

     /*   Setter S_BUDGETLEVEL, PK , NOT NULL   */
    public void setSbudgetlevel(String _sbudgetlevel) {
        this.sbudgetlevel = _sbudgetlevel;
    }
    /*  Getter S_TRECODE, PK , NOT NULL   */
    public String getStrecode()
    {
        return strecode;
    }

     /*   Setter S_TRECODE, PK , NOT NULL   */
    public void setStrecode(String _strecode) {
        this.strecode = _strecode;
    }


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TsAssitflagtransPK))
            return false;

        TsAssitflagtransPK bean = (TsAssitflagtransPK) obj;

	      //compare field sorgcode
      if((this.sorgcode==null && bean.sorgcode!=null) || (this.sorgcode!=null && bean.sorgcode==null))
          return false;
        else if(this.sorgcode==null && bean.sorgcode==null){
        }
        else{
          if(!bean.sorgcode.equals(this.sorgcode))
               return false;
     }
  	      //compare field sbudgetsubject
      if((this.sbudgetsubject==null && bean.sbudgetsubject!=null) || (this.sbudgetsubject!=null && bean.sbudgetsubject==null))
          return false;
        else if(this.sbudgetsubject==null && bean.sbudgetsubject==null){
        }
        else{
          if(!bean.sbudgetsubject.equals(this.sbudgetsubject))
               return false;
     }
  	      //compare field sbudgetlevel
      if((this.sbudgetlevel==null && bean.sbudgetlevel!=null) || (this.sbudgetlevel!=null && bean.sbudgetlevel==null))
          return false;
        else if(this.sbudgetlevel==null && bean.sbudgetlevel==null){
        }
        else{
          if(!bean.sbudgetlevel.equals(this.sbudgetlevel))
               return false;
     }
  	      //compare field strecode
      if((this.strecode==null && bean.strecode!=null) || (this.strecode!=null && bean.strecode==null))
          return false;
        else if(this.strecode==null && bean.strecode==null){
        }
        else{
          if(!bean.strecode.equals(this.strecode))
               return false;
     }
          return true;
    }


   /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
		int __hash__ = 1;
		

        if(this.sorgcode!=null)
          __hash__ = __hash__ * 31+ this.sorgcode.hashCode() ;

        if(this.sbudgetsubject!=null)
          __hash__ = __hash__ * 31+ this.sbudgetsubject.hashCode() ;

        if(this.sbudgetlevel!=null)
          __hash__ = __hash__ * 31+ this.sbudgetlevel.hashCode() ;

        if(this.strecode!=null)
          __hash__ = __hash__ * 31+ this.strecode.hashCode() ;

		return __hash__;
	
	}



     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TsAssitflagtransPK bean = new TsAssitflagtransPK();
          if(this.sorgcode!=null){
                  bean.sorgcode = new String(this.sorgcode);
            }
             if(this.sbudgetsubject!=null){
                  bean.sbudgetsubject = new String(this.sbudgetsubject);
            }
             if(this.sbudgetlevel!=null){
                  bean.sbudgetlevel = new String(this.sbudgetlevel);
            }
             if(this.strecode!=null){
                  bean.strecode = new String(this.strecode);
            }
   
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = ", ";
        StringBuffer sb = new StringBuffer();
        sb.append("TsAssitflagtransPK").append(":");
            sb.append("[sorgcode]").append(" = ").append(sorgcode).append(sep);
            sb.append("[sbudgetsubject]").append(" = ").append(sbudgetsubject).append(sep);
            sb.append("[sbudgetlevel]").append(" = ").append(sbudgetlevel).append(sep);
            sb.append("[strecode]").append(" = ").append(strecode).append(sep);
            return sb.toString();
    }


     /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

          
        if (this.getSorgcode()==null)
              sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_ORGCODE 不能为空; ");
                
       if (this.getSorgcode()!=null)
          if (this.getSorgcode().getBytes().length > 12)
             sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_ORGCODE 宽度不能超过 "+12);
                
        if (this.getSbudgetsubject()==null)
              sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_BUDGETSUBJECT 不能为空; ");
                
       if (this.getSbudgetsubject()!=null)
          if (this.getSbudgetsubject().getBytes().length > 32)
             sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_BUDGETSUBJECT 宽度不能超过 "+32);
                
        if (this.getSbudgetlevel()==null)
              sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_BUDGETLEVEL 不能为空; ");
                
       if (this.getSbudgetlevel()!=null)
          if (this.getSbudgetlevel().getBytes().length > 1)
             sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_BUDGETLEVEL 宽度不能超过 "+1);
                
        if (this.getStrecode()==null)
              sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_TRECODE 不能为空; ");
                
       if (this.getStrecode()!=null)
          if (this.getStrecode().getBytes().length > 10)
             sb.append("数据库表：TS_ASSITFLAGTRANS 字段：S_TRECODE 宽度不能超过 "+10);
        	String msg = sb.toString() ;
	if (msg.length() == 0)
		return null ;
  	return  msg;
   }

}
