package com.cfcc.itfe.persistence.pk;

import java.sql.Date;
import java.math.BigDecimal;
import java.sql.Time;
import java.sql.Timestamp ;
import com.cfcc.jaf.persistence.jaform.parent.IPK ;

/**
 * <p>Title: PK of table: TV_AMT_CONTROL_INFO</p>
 * <p>Description:  PK Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:01 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *
 *  pk.vm version timestamp: 2007-04-06 08:30:00
 * 
 * @author win7
 */

public class TvAmtControlInfoPK implements IPK
{
    /**
    *   S_TRECODE VARCHAR  , PK   , NOT NULL        */
    protected String strecode;
    /**
    *   S_BANKCODE VARCHAR  , PK   , NOT NULL        */
    protected String sbankcode;
    /**
    *   S_BUDGETUNITCODE VARCHAR  , PK   , NOT NULL        */
    protected String sbudgetunitcode;
    /**
    *   S_FUNCBDGSBTCODE VARCHAR  , PK   , NOT NULL        */
    protected String sfuncbdgsbtcode;
    /**
    *   S_YEAR CHARACTER  , PK   , NOT NULL        */
    protected String syear;
    /**
    *   S_PAYTYPECODE VARCHAR  , PK   , NOT NULL        */
    protected String spaytypecode;
    /**
    *   S_BUDGETTYPE CHARACTER  , PK   , NOT NULL        */
    protected String sbudgettype;



    /*  Getter S_TRECODE, PK , NOT NULL   */
    public String getStrecode()
    {
        return strecode;
    }

     /*   Setter S_TRECODE, PK , NOT NULL   */
    public void setStrecode(String _strecode) {
        this.strecode = _strecode;
    }
    /*  Getter S_BANKCODE, PK , NOT NULL   */
    public String getSbankcode()
    {
        return sbankcode;
    }

     /*   Setter S_BANKCODE, PK , NOT NULL   */
    public void setSbankcode(String _sbankcode) {
        this.sbankcode = _sbankcode;
    }
    /*  Getter S_BUDGETUNITCODE, PK , NOT NULL   */
    public String getSbudgetunitcode()
    {
        return sbudgetunitcode;
    }

     /*   Setter S_BUDGETUNITCODE, PK , NOT NULL   */
    public void setSbudgetunitcode(String _sbudgetunitcode) {
        this.sbudgetunitcode = _sbudgetunitcode;
    }
    /*  Getter S_FUNCBDGSBTCODE, PK , NOT NULL   */
    public String getSfuncbdgsbtcode()
    {
        return sfuncbdgsbtcode;
    }

     /*   Setter S_FUNCBDGSBTCODE, PK , NOT NULL   */
    public void setSfuncbdgsbtcode(String _sfuncbdgsbtcode) {
        this.sfuncbdgsbtcode = _sfuncbdgsbtcode;
    }
    /*  Getter S_YEAR, PK , NOT NULL   */
    public String getSyear()
    {
        return syear;
    }

     /*   Setter S_YEAR, PK , NOT NULL   */
    public void setSyear(String _syear) {
        this.syear = _syear;
    }
    /*  Getter S_PAYTYPECODE, PK , NOT NULL   */
    public String getSpaytypecode()
    {
        return spaytypecode;
    }

     /*   Setter S_PAYTYPECODE, PK , NOT NULL   */
    public void setSpaytypecode(String _spaytypecode) {
        this.spaytypecode = _spaytypecode;
    }
    /*  Getter S_BUDGETTYPE, PK , NOT NULL   */
    public String getSbudgettype()
    {
        return sbudgettype;
    }

     /*   Setter S_BUDGETTYPE, PK , NOT NULL   */
    public void setSbudgettype(String _sbudgettype) {
        this.sbudgettype = _sbudgettype;
    }


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvAmtControlInfoPK))
            return false;

        TvAmtControlInfoPK bean = (TvAmtControlInfoPK) obj;

	      //compare field strecode
      if((this.strecode==null && bean.strecode!=null) || (this.strecode!=null && bean.strecode==null))
          return false;
        else if(this.strecode==null && bean.strecode==null){
        }
        else{
          if(!bean.strecode.equals(this.strecode))
               return false;
     }
  	      //compare field sbankcode
      if((this.sbankcode==null && bean.sbankcode!=null) || (this.sbankcode!=null && bean.sbankcode==null))
          return false;
        else if(this.sbankcode==null && bean.sbankcode==null){
        }
        else{
          if(!bean.sbankcode.equals(this.sbankcode))
               return false;
     }
  	      //compare field sbudgetunitcode
      if((this.sbudgetunitcode==null && bean.sbudgetunitcode!=null) || (this.sbudgetunitcode!=null && bean.sbudgetunitcode==null))
          return false;
        else if(this.sbudgetunitcode==null && bean.sbudgetunitcode==null){
        }
        else{
          if(!bean.sbudgetunitcode.equals(this.sbudgetunitcode))
               return false;
     }
  	      //compare field sfuncbdgsbtcode
      if((this.sfuncbdgsbtcode==null && bean.sfuncbdgsbtcode!=null) || (this.sfuncbdgsbtcode!=null && bean.sfuncbdgsbtcode==null))
          return false;
        else if(this.sfuncbdgsbtcode==null && bean.sfuncbdgsbtcode==null){
        }
        else{
          if(!bean.sfuncbdgsbtcode.equals(this.sfuncbdgsbtcode))
               return false;
     }
  	      //compare field syear
      if((this.syear==null && bean.syear!=null) || (this.syear!=null && bean.syear==null))
          return false;
        else if(this.syear==null && bean.syear==null){
        }
        else{
          if(!bean.syear.equals(this.syear))
               return false;
     }
  	      //compare field spaytypecode
      if((this.spaytypecode==null && bean.spaytypecode!=null) || (this.spaytypecode!=null && bean.spaytypecode==null))
          return false;
        else if(this.spaytypecode==null && bean.spaytypecode==null){
        }
        else{
          if(!bean.spaytypecode.equals(this.spaytypecode))
               return false;
     }
  	      //compare field sbudgettype
      if((this.sbudgettype==null && bean.sbudgettype!=null) || (this.sbudgettype!=null && bean.sbudgettype==null))
          return false;
        else if(this.sbudgettype==null && bean.sbudgettype==null){
        }
        else{
          if(!bean.sbudgettype.equals(this.sbudgettype))
               return false;
     }
          return true;
    }


   /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
		int __hash__ = 1;
		

        if(this.strecode!=null)
          __hash__ = __hash__ * 31+ this.strecode.hashCode() ;

        if(this.sbankcode!=null)
          __hash__ = __hash__ * 31+ this.sbankcode.hashCode() ;

        if(this.sbudgetunitcode!=null)
          __hash__ = __hash__ * 31+ this.sbudgetunitcode.hashCode() ;

        if(this.sfuncbdgsbtcode!=null)
          __hash__ = __hash__ * 31+ this.sfuncbdgsbtcode.hashCode() ;

        if(this.syear!=null)
          __hash__ = __hash__ * 31+ this.syear.hashCode() ;

        if(this.spaytypecode!=null)
          __hash__ = __hash__ * 31+ this.spaytypecode.hashCode() ;

        if(this.sbudgettype!=null)
          __hash__ = __hash__ * 31+ this.sbudgettype.hashCode() ;

		return __hash__;
	
	}



     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvAmtControlInfoPK bean = new TvAmtControlInfoPK();
          if(this.strecode!=null){
                  bean.strecode = new String(this.strecode);
            }
             if(this.sbankcode!=null){
                  bean.sbankcode = new String(this.sbankcode);
            }
             if(this.sbudgetunitcode!=null){
                  bean.sbudgetunitcode = new String(this.sbudgetunitcode);
            }
             if(this.sfuncbdgsbtcode!=null){
                  bean.sfuncbdgsbtcode = new String(this.sfuncbdgsbtcode);
            }
             if(this.syear!=null){
                  bean.syear = new String(this.syear);
            }
             if(this.spaytypecode!=null){
                  bean.spaytypecode = new String(this.spaytypecode);
            }
             if(this.sbudgettype!=null){
                  bean.sbudgettype = new String(this.sbudgettype);
            }
   
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = ", ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvAmtControlInfoPK").append(":");
            sb.append("[strecode]").append(" = ").append(strecode).append(sep);
            sb.append("[sbankcode]").append(" = ").append(sbankcode).append(sep);
            sb.append("[sbudgetunitcode]").append(" = ").append(sbudgetunitcode).append(sep);
            sb.append("[sfuncbdgsbtcode]").append(" = ").append(sfuncbdgsbtcode).append(sep);
            sb.append("[syear]").append(" = ").append(syear).append(sep);
            sb.append("[spaytypecode]").append(" = ").append(spaytypecode).append(sep);
            sb.append("[sbudgettype]").append(" = ").append(sbudgettype).append(sep);
            return sb.toString();
    }


     /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

          
        if (this.getStrecode()==null)
              sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_TRECODE 不能为空; ");
                
       if (this.getStrecode()!=null)
          if (this.getStrecode().getBytes().length > 10)
             sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_TRECODE 宽度不能超过 "+10);
                
        if (this.getSbankcode()==null)
              sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_BANKCODE 不能为空; ");
                
       if (this.getSbankcode()!=null)
          if (this.getSbankcode().getBytes().length > 12)
             sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_BANKCODE 宽度不能超过 "+12);
                
        if (this.getSbudgetunitcode()==null)
              sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_BUDGETUNITCODE 不能为空; ");
                
       if (this.getSbudgetunitcode()!=null)
          if (this.getSbudgetunitcode().getBytes().length > 15)
             sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_BUDGETUNITCODE 宽度不能超过 "+15);
                
        if (this.getSfuncbdgsbtcode()==null)
              sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_FUNCBDGSBTCODE 不能为空; ");
                
       if (this.getSfuncbdgsbtcode()!=null)
          if (this.getSfuncbdgsbtcode().getBytes().length > 30)
             sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_FUNCBDGSBTCODE 宽度不能超过 "+30);
                
        if (this.getSyear()==null)
              sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_YEAR 不能为空; ");
                
       if (this.getSyear()!=null)
          if (this.getSyear().getBytes().length > 4)
             sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_YEAR 宽度不能超过 "+4);
                
        if (this.getSpaytypecode()==null)
              sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_PAYTYPECODE 不能为空; ");
                
       if (this.getSpaytypecode()!=null)
          if (this.getSpaytypecode().getBytes().length > 2)
             sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_PAYTYPECODE 宽度不能超过 "+2);
                
        if (this.getSbudgettype()==null)
              sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_BUDGETTYPE 不能为空; ");
                
       if (this.getSbudgettype()!=null)
          if (this.getSbudgettype().getBytes().length > 1)
             sb.append("数据库表：TV_AMT_CONTROL_INFO 字段：S_BUDGETTYPE 宽度不能超过 "+1);
        	String msg = sb.toString() ;
	if (msg.length() == 0)
		return null ;
  	return  msg;
   }

}
