package com.cfcc.itfe.persistence.pk;

import java.sql.Date;
import java.math.BigDecimal;
import java.sql.Time;
import java.sql.Timestamp ;
import com.cfcc.jaf.persistence.jaform.parent.IPK ;

/**
 * <p>Title: PK of table: TV_EXCEPTIONMAN</p>
 * <p>Description:  PK Object  </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *
 *  pk.vm version timestamp: 2007-04-06 08:30:00
 * 
 * @author win7
 */

public class TvExceptionmanPK implements IPK
{
    /**
    *   I_EXCEPTIONNO BIGINT  , PK   , NOT NULL   , Identity  , Generated     */
    protected Long iexceptionno;



    /*  Getter I_EXCEPTIONNO, PK , NOT NULL  , Identity  , Generated */
    public Long getIexceptionno()
    {
        return iexceptionno;
    }

     /*   Setter I_EXCEPTIONNO, PK , NOT NULL  , Identity  , Generated */
    public void setIexceptionno(Long _iexceptionno) {
        this.iexceptionno = _iexceptionno;
    }


    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TvExceptionmanPK))
            return false;

        TvExceptionmanPK bean = (TvExceptionmanPK) obj;

	      //compare field iexceptionno
      if((this.iexceptionno==null && bean.iexceptionno!=null) || (this.iexceptionno!=null && bean.iexceptionno==null))
          return false;
        else if(this.iexceptionno==null && bean.iexceptionno==null){
        }
        else{
          if(!bean.iexceptionno.equals(this.iexceptionno))
               return false;
     }
          return true;
    }


   /* return hashCode ,if A.equals(B) that A.hashCode()==B.hashCode() */
	public int hashCode()
	{
		int __hash__ = 1;
		

        if(this.iexceptionno!=null)
          __hash__ = __hash__ * 31+ this.iexceptionno.hashCode() ;

		return __hash__;
	
	}



     /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TvExceptionmanPK bean = new TvExceptionmanPK();
          if(this.iexceptionno!=null){
                  bean.iexceptionno = new Long(this.iexceptionno.toString());
            }
   
        return bean;
    }


   /* Returns a string representation of the object. */
    public String toString()
    {
        String sep = ", ";
        StringBuffer sb = new StringBuffer();
        sb.append("TvExceptionmanPK").append(":");
            sb.append("[iexceptionno]").append(" = ").append(iexceptionno).append(sep);
            return sb.toString();
    }


     /* Returns value valid checking String , NULL is Valid*/
   public String  checkValid()
  {
  	StringBuffer sb = new StringBuffer() ;

          
        if (this.getIexceptionno()==null)
              sb.append("数据库表：TV_EXCEPTIONMAN 字段：I_EXCEPTIONNO 不能为空; ");
                	String msg = sb.toString() ;
	if (msg.length() == 0)
		return null ;
  	return  msg;
   }

}
