      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: HTF_DIRECTPAYMSGSUB</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:54 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class HtfDirectpaymsgsubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "HTF_DIRECTPAYMSGSUB";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column I_SEQNO
	 */
	public static String I_SEQNO ="I_SEQNO";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * column S_VOUCHERBILLID
	 */
	public static String S_VOUCHERBILLID ="S_VOUCHERBILLID";
	/**
	 * column S_VOUCHERBILLNO
	 */
	public static String S_VOUCHERBILLNO ="S_VOUCHERBILLNO";
	/**
	 * column S_VOUCHERNO
	 */
	public static String S_VOUCHERNO ="S_VOUCHERNO";
	/**
	 * column S_FUNDTYPECODE
	 */
	public static String S_FUNDTYPECODE ="S_FUNDTYPECODE";
	/**
	 * column S_FUNDTYPENAME
	 */
	public static String S_FUNDTYPENAME ="S_FUNDTYPENAME";
	/**
	 * column S_BGTTYPECODE
	 */
	public static String S_BGTTYPECODE ="S_BGTTYPECODE";
	/**
	 * column S_BGTTYPENAME
	 */
	public static String S_BGTTYPENAME ="S_BGTTYPENAME";
	/**
	 * column S_PROCATCODE
	 */
	public static String S_PROCATCODE ="S_PROCATCODE";
	/**
	 * column S_PROCATNAME
	 */
	public static String S_PROCATNAME ="S_PROCATNAME";
	/**
	 * column S_PAYKINDCODE
	 */
	public static String S_PAYKINDCODE ="S_PAYKINDCODE";
	/**
	 * column S_PAYKINDNAME
	 */
	public static String S_PAYKINDNAME ="S_PAYKINDNAME";
	/**
	 * column S_MOFDEPCODE
	 */
	public static String S_MOFDEPCODE ="S_MOFDEPCODE";
	/**
	 * column S_MOFDEPNAME
	 */
	public static String S_MOFDEPNAME ="S_MOFDEPNAME";
	/**
	 * column S_FILENOCODE
	 */
	public static String S_FILENOCODE ="S_FILENOCODE";
	/**
	 * column S_FILENONAME
	 */
	public static String S_FILENONAME ="S_FILENONAME";
	/**
	 * column S_SUPDEPCODE
	 */
	public static String S_SUPDEPCODE ="S_SUPDEPCODE";
	/**
	 * column S_SUPDEPNAME
	 */
	public static String S_SUPDEPNAME ="S_SUPDEPNAME";
	/**
	 * column S_AGENCYCODE
	 */
	public static String S_AGENCYCODE ="S_AGENCYCODE";
	/**
	 * column S_AGENCYNAME
	 */
	public static String S_AGENCYNAME ="S_AGENCYNAME";
	/**
	 * column S_EXPFUNCCODE
	 */
	public static String S_EXPFUNCCODE ="S_EXPFUNCCODE";
	/**
	 * column S_EXPFUNCNAME
	 */
	public static String S_EXPFUNCNAME ="S_EXPFUNCNAME";
	/**
	 * column S_EXPECOCODE
	 */
	public static String S_EXPECOCODE ="S_EXPECOCODE";
	/**
	 * column S_EXPECONAME
	 */
	public static String S_EXPECONAME ="S_EXPECONAME";
	/**
	 * column S_DEPPROCODE
	 */
	public static String S_DEPPROCODE ="S_DEPPROCODE";
	/**
	 * column S_DEPPRONAME
	 */
	public static String S_DEPPRONAME ="S_DEPPRONAME";
	/**
	 * column S_PAYEEACCTNO
	 */
	public static String S_PAYEEACCTNO ="S_PAYEEACCTNO";
	/**
	 * column S_PAYEEACCTNAME
	 */
	public static String S_PAYEEACCTNAME ="S_PAYEEACCTNAME";
	/**
	 * column S_PAYEEACCTBANKNAME
	 */
	public static String S_PAYEEACCTBANKNAME ="S_PAYEEACCTBANKNAME";
	/**
	 * column S_PAYEEACCTBANKNO
	 */
	public static String S_PAYEEACCTBANKNO ="S_PAYEEACCTBANKNO";
	/**
	 * column N_PAYAMT
	 */
	public static String N_PAYAMT ="N_PAYAMT";
	/**
	 * column S_REMARK
	 */
	public static String S_REMARK ="S_REMARK";
	/**
	 * column S_XPAYDATE
	 */
	public static String S_XPAYDATE ="S_XPAYDATE";
	/**
	 * column S_XAGENTBUSINESSNO
	 */
	public static String S_XAGENTBUSINESSNO ="S_XAGENTBUSINESSNO";
	/**
	 * column S_XCHECKNO
	 */
	public static String S_XCHECKNO ="S_XCHECKNO";
	/**
	 * column N_XPAYAMT
	 */
	public static String N_XPAYAMT ="N_XPAYAMT";
	/**
	 * column S_XPAYEEACCTBANKNAME
	 */
	public static String S_XPAYEEACCTBANKNAME ="S_XPAYEEACCTBANKNAME";
	/**
	 * column S_XPAYEEACCTNO
	 */
	public static String S_XPAYEEACCTNO ="S_XPAYEEACCTNO";
	/**
	 * column S_XPAYEEACCTNAME
	 */
	public static String S_XPAYEEACCTNAME ="S_XPAYEEACCTNAME";
	/**
	 * column S_XADDWORD
	 */
	public static String S_XADDWORD ="S_XADDWORD";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_HOLD3
	 */
	public static String S_HOLD3 ="S_HOLD3";
	/**
	 * column S_HOLD4
	 */
	public static String S_HOLD4 ="S_HOLD4";
	/**
	 * column S_EXT1
	 */
	public static String S_EXT1 ="S_EXT1";
	/**
	 * column S_EXT2
	 */
	public static String S_EXT2 ="S_EXT2";
	/**
	 * column S_EXT3
	 */
	public static String S_EXT3 ="S_EXT3";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[49];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="I_SEQNO";
        columnNames[2]="S_ID";
        columnNames[3]="S_VOUCHERBILLID";
        columnNames[4]="S_VOUCHERBILLNO";
        columnNames[5]="S_VOUCHERNO";
        columnNames[6]="S_FUNDTYPECODE";
        columnNames[7]="S_FUNDTYPENAME";
        columnNames[8]="S_BGTTYPECODE";
        columnNames[9]="S_BGTTYPENAME";
        columnNames[10]="S_PROCATCODE";
        columnNames[11]="S_PROCATNAME";
        columnNames[12]="S_PAYKINDCODE";
        columnNames[13]="S_PAYKINDNAME";
        columnNames[14]="S_MOFDEPCODE";
        columnNames[15]="S_MOFDEPNAME";
        columnNames[16]="S_FILENOCODE";
        columnNames[17]="S_FILENONAME";
        columnNames[18]="S_SUPDEPCODE";
        columnNames[19]="S_SUPDEPNAME";
        columnNames[20]="S_AGENCYCODE";
        columnNames[21]="S_AGENCYNAME";
        columnNames[22]="S_EXPFUNCCODE";
        columnNames[23]="S_EXPFUNCNAME";
        columnNames[24]="S_EXPECOCODE";
        columnNames[25]="S_EXPECONAME";
        columnNames[26]="S_DEPPROCODE";
        columnNames[27]="S_DEPPRONAME";
        columnNames[28]="S_PAYEEACCTNO";
        columnNames[29]="S_PAYEEACCTNAME";
        columnNames[30]="S_PAYEEACCTBANKNAME";
        columnNames[31]="S_PAYEEACCTBANKNO";
        columnNames[32]="N_PAYAMT";
        columnNames[33]="S_REMARK";
        columnNames[34]="S_XPAYDATE";
        columnNames[35]="S_XAGENTBUSINESSNO";
        columnNames[36]="S_XCHECKNO";
        columnNames[37]="N_XPAYAMT";
        columnNames[38]="S_XPAYEEACCTBANKNAME";
        columnNames[39]="S_XPAYEEACCTNO";
        columnNames[40]="S_XPAYEEACCTNAME";
        columnNames[41]="S_XADDWORD";
        columnNames[42]="S_HOLD1";
        columnNames[43]="S_HOLD2";
        columnNames[44]="S_HOLD3";
        columnNames[45]="S_HOLD4";
        columnNames[46]="S_EXT1";
        columnNames[47]="S_EXT2";
        columnNames[48]="S_EXT3";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnIseqno(){
		 return I_SEQNO;
	}
	/**
	 * Getter S_ID , NOT NULL   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/**
	 * Getter S_VOUCHERBILLID , NOT NULL   	 
	 */
	public static String columnSvoucherbillid(){
		 return S_VOUCHERBILLID;
	}
	/**
	 * Getter S_VOUCHERBILLNO , NOT NULL   	 
	 */
	public static String columnSvoucherbillno(){
		 return S_VOUCHERBILLNO;
	}
	/**
	 * Getter S_VOUCHERNO , NOT NULL   	 
	 */
	public static String columnSvoucherno(){
		 return S_VOUCHERNO;
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 */
	public static String columnSfundtypecode(){
		 return S_FUNDTYPECODE;
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 */
	public static String columnSfundtypename(){
		 return S_FUNDTYPENAME;
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static String columnSbgttypecode(){
		 return S_BGTTYPECODE;
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static String columnSbgttypename(){
		 return S_BGTTYPENAME;
	}
	/**
	 * Getter S_PROCATCODE   	 
	 */
	public static String columnSprocatcode(){
		 return S_PROCATCODE;
	}
	/**
	 * Getter S_PROCATNAME   	 
	 */
	public static String columnSprocatname(){
		 return S_PROCATNAME;
	}
	/**
	 * Getter S_PAYKINDCODE   	 
	 */
	public static String columnSpaykindcode(){
		 return S_PAYKINDCODE;
	}
	/**
	 * Getter S_PAYKINDNAME   	 
	 */
	public static String columnSpaykindname(){
		 return S_PAYKINDNAME;
	}
	/**
	 * Getter S_MOFDEPCODE   	 
	 */
	public static String columnSmofdepcode(){
		 return S_MOFDEPCODE;
	}
	/**
	 * Getter S_MOFDEPNAME   	 
	 */
	public static String columnSmofdepname(){
		 return S_MOFDEPNAME;
	}
	/**
	 * Getter S_FILENOCODE   	 
	 */
	public static String columnSfilenocode(){
		 return S_FILENOCODE;
	}
	/**
	 * Getter S_FILENONAME   	 
	 */
	public static String columnSfilenoname(){
		 return S_FILENONAME;
	}
	/**
	 * Getter S_SUPDEPCODE   	 
	 */
	public static String columnSsupdepcode(){
		 return S_SUPDEPCODE;
	}
	/**
	 * Getter S_SUPDEPNAME   	 
	 */
	public static String columnSsupdepname(){
		 return S_SUPDEPNAME;
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 */
	public static String columnSagencycode(){
		 return S_AGENCYCODE;
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 */
	public static String columnSagencyname(){
		 return S_AGENCYNAME;
	}
	/**
	 * Getter S_EXPFUNCCODE , NOT NULL   	 
	 */
	public static String columnSexpfunccode(){
		 return S_EXPFUNCCODE;
	}
	/**
	 * Getter S_EXPFUNCNAME , NOT NULL   	 
	 */
	public static String columnSexpfuncname(){
		 return S_EXPFUNCNAME;
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 */
	public static String columnSexpecocode(){
		 return S_EXPECOCODE;
	}
	/**
	 * Getter S_EXPECONAME   	 
	 */
	public static String columnSexpeconame(){
		 return S_EXPECONAME;
	}
	/**
	 * Getter S_DEPPROCODE   	 
	 */
	public static String columnSdepprocode(){
		 return S_DEPPROCODE;
	}
	/**
	 * Getter S_DEPPRONAME   	 
	 */
	public static String columnSdepproname(){
		 return S_DEPPRONAME;
	}
	/**
	 * Getter S_PAYEEACCTNO , NOT NULL   	 
	 */
	public static String columnSpayeeacctno(){
		 return S_PAYEEACCTNO;
	}
	/**
	 * Getter S_PAYEEACCTNAME , NOT NULL   	 
	 */
	public static String columnSpayeeacctname(){
		 return S_PAYEEACCTNAME;
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME , NOT NULL   	 
	 */
	public static String columnSpayeeacctbankname(){
		 return S_PAYEEACCTBANKNAME;
	}
	/**
	 * Getter S_PAYEEACCTBANKNO   	 
	 */
	public static String columnSpayeeacctbankno(){
		 return S_PAYEEACCTBANKNO;
	}
	/**
	 * Getter N_PAYAMT , NOT NULL   	 
	 */
	public static String columnNpayamt(){
		 return N_PAYAMT;
	}
	/**
	 * Getter S_REMARK   	 
	 */
	public static String columnSremark(){
		 return S_REMARK;
	}
	/**
	 * Getter S_XPAYDATE   	 
	 */
	public static String columnSxpaydate(){
		 return S_XPAYDATE;
	}
	/**
	 * Getter S_XAGENTBUSINESSNO   	 
	 */
	public static String columnSxagentbusinessno(){
		 return S_XAGENTBUSINESSNO;
	}
	/**
	 * Getter S_XCHECKNO   	 
	 */
	public static String columnSxcheckno(){
		 return S_XCHECKNO;
	}
	/**
	 * Getter N_XPAYAMT   	 
	 */
	public static String columnNxpayamt(){
		 return N_XPAYAMT;
	}
	/**
	 * Getter S_XPAYEEACCTBANKNAME   	 
	 */
	public static String columnSxpayeeacctbankname(){
		 return S_XPAYEEACCTBANKNAME;
	}
	/**
	 * Getter S_XPAYEEACCTNO   	 
	 */
	public static String columnSxpayeeacctno(){
		 return S_XPAYEEACCTNO;
	}
	/**
	 * Getter S_XPAYEEACCTNAME   	 
	 */
	public static String columnSxpayeeacctname(){
		 return S_XPAYEEACCTNAME;
	}
	/**
	 * Getter S_XADDWORD   	 
	 */
	public static String columnSxaddword(){
		 return S_XADDWORD;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnShold3(){
		 return S_HOLD3;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnShold4(){
		 return S_HOLD4;
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static String columnSext1(){
		 return S_EXT1;
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static String columnSext2(){
		 return S_EXT2;
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static String columnSext3(){
		 return S_EXT3;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIseqno(){
		 return "Long";
	}
	/**
	 * Getter S_ID , NOT NULL   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/**
	 * Getter S_VOUCHERBILLID , NOT NULL   	 
	 */
	public static String columnJavaTypeSvoucherbillid(){
		 return "String";
	}
	/**
	 * Getter S_VOUCHERBILLNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSvoucherbillno(){
		 return "String";
	}
	/**
	 * Getter S_VOUCHERNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSvoucherno(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfundtypecode(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSfundtypename(){
		 return "String";
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static String columnJavaTypeSbgttypecode(){
		 return "String";
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static String columnJavaTypeSbgttypename(){
		 return "String";
	}
	/**
	 * Getter S_PROCATCODE   	 
	 */
	public static String columnJavaTypeSprocatcode(){
		 return "String";
	}
	/**
	 * Getter S_PROCATNAME   	 
	 */
	public static String columnJavaTypeSprocatname(){
		 return "String";
	}
	/**
	 * Getter S_PAYKINDCODE   	 
	 */
	public static String columnJavaTypeSpaykindcode(){
		 return "String";
	}
	/**
	 * Getter S_PAYKINDNAME   	 
	 */
	public static String columnJavaTypeSpaykindname(){
		 return "String";
	}
	/**
	 * Getter S_MOFDEPCODE   	 
	 */
	public static String columnJavaTypeSmofdepcode(){
		 return "String";
	}
	/**
	 * Getter S_MOFDEPNAME   	 
	 */
	public static String columnJavaTypeSmofdepname(){
		 return "String";
	}
	/**
	 * Getter S_FILENOCODE   	 
	 */
	public static String columnJavaTypeSfilenocode(){
		 return "String";
	}
	/**
	 * Getter S_FILENONAME   	 
	 */
	public static String columnJavaTypeSfilenoname(){
		 return "String";
	}
	/**
	 * Getter S_SUPDEPCODE   	 
	 */
	public static String columnJavaTypeSsupdepcode(){
		 return "String";
	}
	/**
	 * Getter S_SUPDEPNAME   	 
	 */
	public static String columnJavaTypeSsupdepname(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSagencycode(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSagencyname(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSexpfunccode(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSexpfuncname(){
		 return "String";
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 */
	public static String columnJavaTypeSexpecocode(){
		 return "String";
	}
	/**
	 * Getter S_EXPECONAME   	 
	 */
	public static String columnJavaTypeSexpeconame(){
		 return "String";
	}
	/**
	 * Getter S_DEPPROCODE   	 
	 */
	public static String columnJavaTypeSdepprocode(){
		 return "String";
	}
	/**
	 * Getter S_DEPPRONAME   	 
	 */
	public static String columnJavaTypeSdepproname(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeeacctno(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeeacctname(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeeacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTBANKNO   	 
	 */
	public static String columnJavaTypeSpayeeacctbankno(){
		 return "String";
	}
	/**
	 * Getter N_PAYAMT , NOT NULL   	 
	 */
	public static String columnJavaTypeNpayamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_REMARK   	 
	 */
	public static String columnJavaTypeSremark(){
		 return "String";
	}
	/**
	 * Getter S_XPAYDATE   	 
	 */
	public static String columnJavaTypeSxpaydate(){
		 return "String";
	}
	/**
	 * Getter S_XAGENTBUSINESSNO   	 
	 */
	public static String columnJavaTypeSxagentbusinessno(){
		 return "String";
	}
	/**
	 * Getter S_XCHECKNO   	 
	 */
	public static String columnJavaTypeSxcheckno(){
		 return "String";
	}
	/**
	 * Getter N_XPAYAMT   	 
	 */
	public static String columnJavaTypeNxpayamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_XPAYEEACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSxpayeeacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_XPAYEEACCTNO   	 
	 */
	public static String columnJavaTypeSxpayeeacctno(){
		 return "String";
	}
	/**
	 * Getter S_XPAYEEACCTNAME   	 
	 */
	public static String columnJavaTypeSxpayeeacctname(){
		 return "String";
	}
	/**
	 * Getter S_XADDWORD   	 
	 */
	public static String columnJavaTypeSxaddword(){
		 return "String";
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnJavaTypeShold3(){
		 return "String";
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnJavaTypeShold4(){
		 return "String";
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static String columnJavaTypeSext1(){
		 return "String";
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static String columnJavaTypeSext2(){
		 return "String";
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static String columnJavaTypeSext3(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIseqno(){
		 return "BIGINT";
	}
	/**
	 * Getter S_ID , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_VOUCHERBILLID , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvoucherbillid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_VOUCHERBILLNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvoucherbillno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_VOUCHERNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvoucherno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PROCATCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSprocatcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PROCATNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSprocatname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYKINDCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaykindcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYKINDNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaykindname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_MOFDEPCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSmofdepcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_MOFDEPNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSmofdepname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FILENOCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilenocode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FILENONAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilenoname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_SUPDEPCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSsupdepcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_SUPDEPNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSsupdepname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencycode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencyname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfunccode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfuncname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpecocode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECONAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpeconame(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_DEPPROCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSdepprocode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_DEPPRONAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSdepproname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTBANKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctbankno(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_PAYAMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNpayamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_REMARK   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XPAYDATE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxpaydate(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XAGENTBUSINESSNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxagentbusinessno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XCHECKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxcheckno(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_XPAYAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNxpayamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_XPAYEEACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxpayeeacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XPAYEEACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxpayeeacctno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XPAYEEACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxpayeeacctname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XADDWORD   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxaddword(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold4(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext3(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_ID , NOT NULL   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
	/**
	 * Getter S_VOUCHERBILLID , NOT NULL   	 
	 */
	public static int columnWidthSvoucherbillid(){
		 return 38;
	}
	/**
	 * Getter S_VOUCHERBILLNO , NOT NULL   	 
	 */
	public static int columnWidthSvoucherbillno(){
		 return 42;
	}
	/**
	 * Getter S_VOUCHERNO , NOT NULL   	 
	 */
	public static int columnWidthSvoucherno(){
		 return 42;
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 */
	public static int columnWidthSfundtypecode(){
		 return 42;
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 */
	public static int columnWidthSfundtypename(){
		 return 60;
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static int columnWidthSbgttypecode(){
		 return 60;
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static int columnWidthSbgttypename(){
		 return 60;
	}
	/**
	 * Getter S_PROCATCODE   	 
	 */
	public static int columnWidthSprocatcode(){
		 return 42;
	}
	/**
	 * Getter S_PROCATNAME   	 
	 */
	public static int columnWidthSprocatname(){
		 return 60;
	}
	/**
	 * Getter S_PAYKINDCODE   	 
	 */
	public static int columnWidthSpaykindcode(){
		 return 42;
	}
	/**
	 * Getter S_PAYKINDNAME   	 
	 */
	public static int columnWidthSpaykindname(){
		 return 60;
	}
	/**
	 * Getter S_MOFDEPCODE   	 
	 */
	public static int columnWidthSmofdepcode(){
		 return 42;
	}
	/**
	 * Getter S_MOFDEPNAME   	 
	 */
	public static int columnWidthSmofdepname(){
		 return 60;
	}
	/**
	 * Getter S_FILENOCODE   	 
	 */
	public static int columnWidthSfilenocode(){
		 return 42;
	}
	/**
	 * Getter S_FILENONAME   	 
	 */
	public static int columnWidthSfilenoname(){
		 return 100;
	}
	/**
	 * Getter S_SUPDEPCODE   	 
	 */
	public static int columnWidthSsupdepcode(){
		 return 42;
	}
	/**
	 * Getter S_SUPDEPNAME   	 
	 */
	public static int columnWidthSsupdepname(){
		 return 60;
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 */
	public static int columnWidthSagencycode(){
		 return 42;
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 */
	public static int columnWidthSagencyname(){
		 return 60;
	}
	/**
	 * Getter S_EXPFUNCCODE , NOT NULL   	 
	 */
	public static int columnWidthSexpfunccode(){
		 return 42;
	}
	/**
	 * Getter S_EXPFUNCNAME , NOT NULL   	 
	 */
	public static int columnWidthSexpfuncname(){
		 return 60;
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 */
	public static int columnWidthSexpecocode(){
		 return 42;
	}
	/**
	 * Getter S_EXPECONAME   	 
	 */
	public static int columnWidthSexpeconame(){
		 return 60;
	}
	/**
	 * Getter S_DEPPROCODE   	 
	 */
	public static int columnWidthSdepprocode(){
		 return 42;
	}
	/**
	 * Getter S_DEPPRONAME   	 
	 */
	public static int columnWidthSdepproname(){
		 return 200;
	}
	/**
	 * Getter S_PAYEEACCTNO , NOT NULL   	 
	 */
	public static int columnWidthSpayeeacctno(){
		 return 42;
	}
	/**
	 * Getter S_PAYEEACCTNAME , NOT NULL   	 
	 */
	public static int columnWidthSpayeeacctname(){
		 return 120;
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME , NOT NULL   	 
	 */
	public static int columnWidthSpayeeacctbankname(){
		 return 60;
	}
	/**
	 * Getter S_PAYEEACCTBANKNO   	 
	 */
	public static int columnWidthSpayeeacctbankno(){
		 return 42;
	}
	/**
	 * Getter S_REMARK   	 
	 */
	public static int columnWidthSremark(){
		 return 255;
	}
	/**
	 * Getter S_XPAYDATE   	 
	 */
	public static int columnWidthSxpaydate(){
		 return 20;
	}
	/**
	 * Getter S_XAGENTBUSINESSNO   	 
	 */
	public static int columnWidthSxagentbusinessno(){
		 return 42;
	}
	/**
	 * Getter S_XCHECKNO   	 
	 */
	public static int columnWidthSxcheckno(){
		 return 42;
	}
	/**
	 * Getter S_XPAYEEACCTBANKNAME   	 
	 */
	public static int columnWidthSxpayeeacctbankname(){
		 return 60;
	}
	/**
	 * Getter S_XPAYEEACCTNO   	 
	 */
	public static int columnWidthSxpayeeacctno(){
		 return 60;
	}
	/**
	 * Getter S_XPAYEEACCTNAME   	 
	 */
	public static int columnWidthSxpayeeacctname(){
		 return 120;
	}
	/**
	 * Getter S_XADDWORD   	 
	 */
	public static int columnWidthSxaddword(){
		 return 42;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static int columnWidthShold3(){
		 return 42;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static int columnWidthShold4(){
		 return 42;
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static int columnWidthSext1(){
		 return 50;
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static int columnWidthSext2(){
		 return 50;
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static int columnWidthSext3(){
		 return 50;
	}
}