      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: HTF_RECONCILE_REFUND_SUB</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:55 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class HtfReconcileRefundSubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "HTF_RECONCILE_REFUND_SUB";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column I_SEQNO
	 */
	public static String I_SEQNO ="I_SEQNO";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * column S_PAYDETAILID
	 */
	public static String S_PAYDETAILID ="S_PAYDETAILID";
	/**
	 * column S_FUNDTYPECODE
	 */
	public static String S_FUNDTYPECODE ="S_FUNDTYPECODE";
	/**
	 * column S_FUNDTYPENAME
	 */
	public static String S_FUNDTYPENAME ="S_FUNDTYPENAME";
	/**
	 * column S_PAYEEACCTNO
	 */
	public static String S_PAYEEACCTNO ="S_PAYEEACCTNO";
	/**
	 * column S_PAYEEACCTNAME
	 */
	public static String S_PAYEEACCTNAME ="S_PAYEEACCTNAME";
	/**
	 * column S_PAYEEACCTBANKNAME
	 */
	public static String S_PAYEEACCTBANKNAME ="S_PAYEEACCTBANKNAME";
	/**
	 * column S_PAYACCTNO
	 */
	public static String S_PAYACCTNO ="S_PAYACCTNO";
	/**
	 * column S_PAYACCTNAME
	 */
	public static String S_PAYACCTNAME ="S_PAYACCTNAME";
	/**
	 * column S_PAYACCTBANKNAME
	 */
	public static String S_PAYACCTBANKNAME ="S_PAYACCTBANKNAME";
	/**
	 * column S_AGENCYCODE
	 */
	public static String S_AGENCYCODE ="S_AGENCYCODE";
	/**
	 * column S_AGENCYNAME
	 */
	public static String S_AGENCYNAME ="S_AGENCYNAME";
	/**
	 * column S_INCOMESORTCODE
	 */
	public static String S_INCOMESORTCODE ="S_INCOMESORTCODE";
	/**
	 * column S_INCOMESORTNAME
	 */
	public static String S_INCOMESORTNAME ="S_INCOMESORTNAME";
	/**
	 * column N_PAYAMT
	 */
	public static String N_PAYAMT ="N_PAYAMT";
	/**
	 * column S_XCHECKRESULT
	 */
	public static String S_XCHECKRESULT ="S_XCHECKRESULT";
	/**
	 * column S_XCHECKREASON
	 */
	public static String S_XCHECKREASON ="S_XCHECKREASON";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_HOLD3
	 */
	public static String S_HOLD3 ="S_HOLD3";
	/**
	 * column S_HOLD4
	 */
	public static String S_HOLD4 ="S_HOLD4";
	/**
	 * column S_EXT1
	 */
	public static String S_EXT1 ="S_EXT1";
	/**
	 * column S_EXT2
	 */
	public static String S_EXT2 ="S_EXT2";
	/**
	 * column S_EXT3
	 */
	public static String S_EXT3 ="S_EXT3";
	/**
	 * column S_EXT4
	 */
	public static String S_EXT4 ="S_EXT4";
	/**
	 * column S_EXT5
	 */
	public static String S_EXT5 ="S_EXT5";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[28];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="I_SEQNO";
        columnNames[2]="S_ID";
        columnNames[3]="S_PAYDETAILID";
        columnNames[4]="S_FUNDTYPECODE";
        columnNames[5]="S_FUNDTYPENAME";
        columnNames[6]="S_PAYEEACCTNO";
        columnNames[7]="S_PAYEEACCTNAME";
        columnNames[8]="S_PAYEEACCTBANKNAME";
        columnNames[9]="S_PAYACCTNO";
        columnNames[10]="S_PAYACCTNAME";
        columnNames[11]="S_PAYACCTBANKNAME";
        columnNames[12]="S_AGENCYCODE";
        columnNames[13]="S_AGENCYNAME";
        columnNames[14]="S_INCOMESORTCODE";
        columnNames[15]="S_INCOMESORTNAME";
        columnNames[16]="N_PAYAMT";
        columnNames[17]="S_XCHECKRESULT";
        columnNames[18]="S_XCHECKREASON";
        columnNames[19]="S_HOLD1";
        columnNames[20]="S_HOLD2";
        columnNames[21]="S_HOLD3";
        columnNames[22]="S_HOLD4";
        columnNames[23]="S_EXT1";
        columnNames[24]="S_EXT2";
        columnNames[25]="S_EXT3";
        columnNames[26]="S_EXT4";
        columnNames[27]="S_EXT5";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnIseqno(){
		 return I_SEQNO;
	}
	/**
	 * Getter S_ID   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/**
	 * Getter S_PAYDETAILID   	 
	 */
	public static String columnSpaydetailid(){
		 return S_PAYDETAILID;
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static String columnSfundtypecode(){
		 return S_FUNDTYPECODE;
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static String columnSfundtypename(){
		 return S_FUNDTYPENAME;
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 */
	public static String columnSpayeeacctno(){
		 return S_PAYEEACCTNO;
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnSpayeeacctname(){
		 return S_PAYEEACCTNAME;
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnSpayeeacctbankname(){
		 return S_PAYEEACCTBANKNAME;
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 */
	public static String columnSpayacctno(){
		 return S_PAYACCTNO;
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 */
	public static String columnSpayacctname(){
		 return S_PAYACCTNAME;
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 */
	public static String columnSpayacctbankname(){
		 return S_PAYACCTBANKNAME;
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 */
	public static String columnSagencycode(){
		 return S_AGENCYCODE;
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 */
	public static String columnSagencyname(){
		 return S_AGENCYNAME;
	}
	/**
	 * Getter S_INCOMESORTCODE   	 
	 */
	public static String columnSincomesortcode(){
		 return S_INCOMESORTCODE;
	}
	/**
	 * Getter S_INCOMESORTNAME   	 
	 */
	public static String columnSincomesortname(){
		 return S_INCOMESORTNAME;
	}
	/**
	 * Getter N_PAYAMT   	 
	 */
	public static String columnNpayamt(){
		 return N_PAYAMT;
	}
	/**
	 * Getter S_XCHECKRESULT   	 
	 */
	public static String columnSxcheckresult(){
		 return S_XCHECKRESULT;
	}
	/**
	 * Getter S_XCHECKREASON   	 
	 */
	public static String columnSxcheckreason(){
		 return S_XCHECKREASON;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnShold3(){
		 return S_HOLD3;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnShold4(){
		 return S_HOLD4;
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static String columnSext1(){
		 return S_EXT1;
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static String columnSext2(){
		 return S_EXT2;
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static String columnSext3(){
		 return S_EXT3;
	}
	/**
	 * Getter S_EXT4   	 
	 */
	public static String columnSext4(){
		 return S_EXT4;
	}
	/**
	 * Getter S_EXT5   	 
	 */
	public static String columnSext5(){
		 return S_EXT5;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIseqno(){
		 return "Long";
	}
	/**
	 * Getter S_ID   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/**
	 * Getter S_PAYDETAILID   	 
	 */
	public static String columnJavaTypeSpaydetailid(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static String columnJavaTypeSfundtypecode(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static String columnJavaTypeSfundtypename(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 */
	public static String columnJavaTypeSpayeeacctno(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctname(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 */
	public static String columnJavaTypeSpayacctno(){
		 return "String";
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 */
	public static String columnJavaTypeSpayacctname(){
		 return "String";
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSpayacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 */
	public static String columnJavaTypeSagencycode(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 */
	public static String columnJavaTypeSagencyname(){
		 return "String";
	}
	/**
	 * Getter S_INCOMESORTCODE   	 
	 */
	public static String columnJavaTypeSincomesortcode(){
		 return "String";
	}
	/**
	 * Getter S_INCOMESORTNAME   	 
	 */
	public static String columnJavaTypeSincomesortname(){
		 return "String";
	}
	/**
	 * Getter N_PAYAMT   	 
	 */
	public static String columnJavaTypeNpayamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_XCHECKRESULT   	 
	 */
	public static String columnJavaTypeSxcheckresult(){
		 return "String";
	}
	/**
	 * Getter S_XCHECKREASON   	 
	 */
	public static String columnJavaTypeSxcheckreason(){
		 return "String";
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnJavaTypeShold3(){
		 return "String";
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnJavaTypeShold4(){
		 return "String";
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static String columnJavaTypeSext1(){
		 return "String";
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static String columnJavaTypeSext2(){
		 return "String";
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static String columnJavaTypeSext3(){
		 return "String";
	}
	/**
	 * Getter S_EXT4   	 
	 */
	public static String columnJavaTypeSext4(){
		 return "String";
	}
	/**
	 * Getter S_EXT5   	 
	 */
	public static String columnJavaTypeSext5(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIseqno(){
		 return "BIGINT";
	}
	/**
	 * Getter S_ID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYDETAILID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaydetailid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencycode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencyname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_INCOMESORTCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSincomesortcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_INCOMESORTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSincomesortname(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_PAYAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNpayamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_XCHECKRESULT   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxcheckresult(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XCHECKREASON   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxcheckreason(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold4(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext4(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT5   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext5(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_ID   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
	/**
	 * Getter S_PAYDETAILID   	 
	 */
	public static int columnWidthSpaydetailid(){
		 return 38;
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static int columnWidthSfundtypecode(){
		 return 42;
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static int columnWidthSfundtypename(){
		 return 60;
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 */
	public static int columnWidthSpayeeacctno(){
		 return 42;
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 */
	public static int columnWidthSpayeeacctname(){
		 return 120;
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static int columnWidthSpayeeacctbankname(){
		 return 60;
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 */
	public static int columnWidthSpayacctno(){
		 return 60;
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 */
	public static int columnWidthSpayacctname(){
		 return 120;
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 */
	public static int columnWidthSpayacctbankname(){
		 return 60;
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 */
	public static int columnWidthSagencycode(){
		 return 42;
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 */
	public static int columnWidthSagencyname(){
		 return 60;
	}
	/**
	 * Getter S_INCOMESORTCODE   	 
	 */
	public static int columnWidthSincomesortcode(){
		 return 42;
	}
	/**
	 * Getter S_INCOMESORTNAME   	 
	 */
	public static int columnWidthSincomesortname(){
		 return 60;
	}
	/**
	 * Getter S_XCHECKRESULT   	 
	 */
	public static int columnWidthSxcheckresult(){
		 return 5;
	}
	/**
	 * Getter S_XCHECKREASON   	 
	 */
	public static int columnWidthSxcheckreason(){
		 return 200;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static int columnWidthShold3(){
		 return 42;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static int columnWidthShold4(){
		 return 42;
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static int columnWidthSext1(){
		 return 50;
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static int columnWidthSext2(){
		 return 50;
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static int columnWidthSext3(){
		 return 50;
	}
	/**
	 * Getter S_EXT4   	 
	 */
	public static int columnWidthSext4(){
		 return 50;
	}
	/**
	 * Getter S_EXT5   	 
	 */
	public static int columnWidthSext5(){
		 return 50;
	}
}