      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: HTF_UNITRECORDSUB</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:55 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class HtfUnitrecordsubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "HTF_UNITRECORDSUB";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column I_SEQNO
	 */
	public static String I_SEQNO ="I_SEQNO";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * column S_AGENCYCODE
	 */
	public static String S_AGENCYCODE ="S_AGENCYCODE";
	/**
	 * column S_AGENCYNAME
	 */
	public static String S_AGENCYNAME ="S_AGENCYNAME";
	/**
	 * column S_FUNDTYPECODE
	 */
	public static String S_FUNDTYPECODE ="S_FUNDTYPECODE";
	/**
	 * column S_FUNDTYPENAME
	 */
	public static String S_FUNDTYPENAME ="S_FUNDTYPENAME";
	/**
	 * column S_AGENCYACCONO
	 */
	public static String S_AGENCYACCONO ="S_AGENCYACCONO";
	/**
	 * column S_AGENCYACCONAME
	 */
	public static String S_AGENCYACCONAME ="S_AGENCYACCONAME";
	/**
	 * column S_AGENCYBANKNAME
	 */
	public static String S_AGENCYBANKNAME ="S_AGENCYBANKNAME";
	/**
	 * column S_ACCSTATUS
	 */
	public static String S_ACCSTATUS ="S_ACCSTATUS";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_HOLD3
	 */
	public static String S_HOLD3 ="S_HOLD3";
	/**
	 * column S_HOLD4
	 */
	public static String S_HOLD4 ="S_HOLD4";
	/**
	 * column S_EXT1
	 */
	public static String S_EXT1 ="S_EXT1";
	/**
	 * column S_EXT2
	 */
	public static String S_EXT2 ="S_EXT2";
	/**
	 * column S_EXT3
	 */
	public static String S_EXT3 ="S_EXT3";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[18];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="I_SEQNO";
        columnNames[2]="S_ID";
        columnNames[3]="S_AGENCYCODE";
        columnNames[4]="S_AGENCYNAME";
        columnNames[5]="S_FUNDTYPECODE";
        columnNames[6]="S_FUNDTYPENAME";
        columnNames[7]="S_AGENCYACCONO";
        columnNames[8]="S_AGENCYACCONAME";
        columnNames[9]="S_AGENCYBANKNAME";
        columnNames[10]="S_ACCSTATUS";
        columnNames[11]="S_HOLD1";
        columnNames[12]="S_HOLD2";
        columnNames[13]="S_HOLD3";
        columnNames[14]="S_HOLD4";
        columnNames[15]="S_EXT1";
        columnNames[16]="S_EXT2";
        columnNames[17]="S_EXT3";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnIseqno(){
		 return I_SEQNO;
	}
	/**
	 * Getter S_ID , NOT NULL   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 */
	public static String columnSagencycode(){
		 return S_AGENCYCODE;
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 */
	public static String columnSagencyname(){
		 return S_AGENCYNAME;
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 */
	public static String columnSfundtypecode(){
		 return S_FUNDTYPECODE;
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 */
	public static String columnSfundtypename(){
		 return S_FUNDTYPENAME;
	}
	/**
	 * Getter S_AGENCYACCONO , NOT NULL   	 
	 */
	public static String columnSagencyaccono(){
		 return S_AGENCYACCONO;
	}
	/**
	 * Getter S_AGENCYACCONAME , NOT NULL   	 
	 */
	public static String columnSagencyacconame(){
		 return S_AGENCYACCONAME;
	}
	/**
	 * Getter S_AGENCYBANKNAME , NOT NULL   	 
	 */
	public static String columnSagencybankname(){
		 return S_AGENCYBANKNAME;
	}
	/**
	 * Getter S_ACCSTATUS , NOT NULL   	 
	 */
	public static String columnSaccstatus(){
		 return S_ACCSTATUS;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnShold3(){
		 return S_HOLD3;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnShold4(){
		 return S_HOLD4;
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static String columnSext1(){
		 return S_EXT1;
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static String columnSext2(){
		 return S_EXT2;
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static String columnSext3(){
		 return S_EXT3;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIseqno(){
		 return "Long";
	}
	/**
	 * Getter S_ID , NOT NULL   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSagencycode(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSagencyname(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfundtypecode(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSfundtypename(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYACCONO , NOT NULL   	 
	 */
	public static String columnJavaTypeSagencyaccono(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYACCONAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSagencyacconame(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYBANKNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSagencybankname(){
		 return "String";
	}
	/**
	 * Getter S_ACCSTATUS , NOT NULL   	 
	 */
	public static String columnJavaTypeSaccstatus(){
		 return "String";
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnJavaTypeShold3(){
		 return "String";
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnJavaTypeShold4(){
		 return "String";
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static String columnJavaTypeSext1(){
		 return "String";
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static String columnJavaTypeSext2(){
		 return "String";
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static String columnJavaTypeSext3(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter I_SEQNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIseqno(){
		 return "BIGINT";
	}
	/**
	 * Getter S_ID , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencycode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencyname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYACCONO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencyaccono(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYACCONAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencyacconame(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYBANKNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencybankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ACCSTATUS , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSaccstatus(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold4(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXT3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext3(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_ID , NOT NULL   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
	/**
	 * Getter S_AGENCYCODE , NOT NULL   	 
	 */
	public static int columnWidthSagencycode(){
		 return 42;
	}
	/**
	 * Getter S_AGENCYNAME , NOT NULL   	 
	 */
	public static int columnWidthSagencyname(){
		 return 60;
	}
	/**
	 * Getter S_FUNDTYPECODE , NOT NULL   	 
	 */
	public static int columnWidthSfundtypecode(){
		 return 42;
	}
	/**
	 * Getter S_FUNDTYPENAME , NOT NULL   	 
	 */
	public static int columnWidthSfundtypename(){
		 return 60;
	}
	/**
	 * Getter S_AGENCYACCONO , NOT NULL   	 
	 */
	public static int columnWidthSagencyaccono(){
		 return 60;
	}
	/**
	 * Getter S_AGENCYACCONAME , NOT NULL   	 
	 */
	public static int columnWidthSagencyacconame(){
		 return 200;
	}
	/**
	 * Getter S_AGENCYBANKNAME , NOT NULL   	 
	 */
	public static int columnWidthSagencybankname(){
		 return 200;
	}
	/**
	 * Getter S_ACCSTATUS , NOT NULL   	 
	 */
	public static int columnWidthSaccstatus(){
		 return 5;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static int columnWidthShold3(){
		 return 42;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static int columnWidthShold4(){
		 return 42;
	}
	/**
	 * Getter S_EXT1   	 
	 */
	public static int columnWidthSext1(){
		 return 50;
	}
	/**
	 * Getter S_EXT2   	 
	 */
	public static int columnWidthSext2(){
		 return 50;
	}
	/**
	 * Getter S_EXT3   	 
	 */
	public static int columnWidthSext3(){
		 return 50;
	}
}