      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: HTV_PAYOUTFINANCE_MAIN</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:56 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class HtvPayoutfinanceMainInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "HTV_PAYOUTFINANCE_MAIN";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column S_TRECODE
	 */
	public static String S_TRECODE ="S_TRECODE";
	/**
	 * column S_BILLORG
	 */
	public static String S_BILLORG ="S_BILLORG";
	/**
	 * column S_PAYEEBANKNO
	 */
	public static String S_PAYEEBANKNO ="S_PAYEEBANKNO";
	/**
	 * column S_PAYERACCT
	 */
	public static String S_PAYERACCT ="S_PAYERACCT";
	/**
	 * column S_PAYERNAME
	 */
	public static String S_PAYERNAME ="S_PAYERNAME";
	/**
	 * column S_PAYERADDR
	 */
	public static String S_PAYERADDR ="S_PAYERADDR";
	/**
	 * column S_ENTRUSTDATE
	 */
	public static String S_ENTRUSTDATE ="S_ENTRUSTDATE";
	/**
	 * column S_PACKAGENO
	 */
	public static String S_PACKAGENO ="S_PACKAGENO";
	/**
	 * column S_PAYOUTVOUTYPE
	 */
	public static String S_PAYOUTVOUTYPE ="S_PAYOUTVOUTYPE";
	/**
	 * column S_VOUNO
	 */
	public static String S_VOUNO ="S_VOUNO";
	/**
	 * column S_VOUDATE
	 */
	public static String S_VOUDATE ="S_VOUDATE";
	/**
	 * column S_ADDWORD
	 */
	public static String S_ADDWORD ="S_ADDWORD";
	/**
	 * column S_BUDGETTYPE
	 */
	public static String S_BUDGETTYPE ="S_BUDGETTYPE";
	/**
	 * column S_BDGORGCODE
	 */
	public static String S_BDGORGCODE ="S_BDGORGCODE";
	/**
	 * column S_FUNCSBTCODE
	 */
	public static String S_FUNCSBTCODE ="S_FUNCSBTCODE";
	/**
	 * column S_ECNOMICSUBJECTCODE
	 */
	public static String S_ECNOMICSUBJECTCODE ="S_ECNOMICSUBJECTCODE";
	/**
	 * column N_AMT
	 */
	public static String N_AMT ="N_AMT";
	/**
	 * column S_FILENAME
	 */
	public static String S_FILENAME ="S_FILENAME";
	/**
	 * column S_RESULT
	 */
	public static String S_RESULT ="S_RESULT";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * column S_BOOKORGCODE
	 */
	public static String S_BOOKORGCODE ="S_BOOKORGCODE";
	/**
	 * column S_STATUS
	 */
	public static String S_STATUS ="S_STATUS";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[23];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="S_TRECODE";
        columnNames[2]="S_BILLORG";
        columnNames[3]="S_PAYEEBANKNO";
        columnNames[4]="S_PAYERACCT";
        columnNames[5]="S_PAYERNAME";
        columnNames[6]="S_PAYERADDR";
        columnNames[7]="S_ENTRUSTDATE";
        columnNames[8]="S_PACKAGENO";
        columnNames[9]="S_PAYOUTVOUTYPE";
        columnNames[10]="S_VOUNO";
        columnNames[11]="S_VOUDATE";
        columnNames[12]="S_ADDWORD";
        columnNames[13]="S_BUDGETTYPE";
        columnNames[14]="S_BDGORGCODE";
        columnNames[15]="S_FUNCSBTCODE";
        columnNames[16]="S_ECNOMICSUBJECTCODE";
        columnNames[17]="N_AMT";
        columnNames[18]="S_FILENAME";
        columnNames[19]="S_RESULT";
        columnNames[20]="TS_SYSUPDATE";
        columnNames[21]="S_BOOKORGCODE";
        columnNames[22]="S_STATUS";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnStrecode(){
		 return S_TRECODE;
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 */
	public static String columnSbillorg(){
		 return S_BILLORG;
	}
	/**
	 * Getter S_PAYEEBANKNO , NOT NULL   	 
	 */
	public static String columnSpayeebankno(){
		 return S_PAYEEBANKNO;
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static String columnSpayeracct(){
		 return S_PAYERACCT;
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 */
	public static String columnSpayername(){
		 return S_PAYERNAME;
	}
	/**
	 * Getter S_PAYERADDR   	 
	 */
	public static String columnSpayeraddr(){
		 return S_PAYERADDR;
	}
	/**
	 * Getter S_ENTRUSTDATE , NOT NULL   	 
	 */
	public static String columnSentrustdate(){
		 return S_ENTRUSTDATE;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnSpackageno(){
		 return S_PACKAGENO;
	}
	/**
	 * Getter S_PAYOUTVOUTYPE , NOT NULL   	 
	 */
	public static String columnSpayoutvoutype(){
		 return S_PAYOUTVOUTYPE;
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static String columnSvouno(){
		 return S_VOUNO;
	}
	/**
	 * Getter S_VOUDATE , NOT NULL   	 
	 */
	public static String columnSvoudate(){
		 return S_VOUDATE;
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static String columnSaddword(){
		 return S_ADDWORD;
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnSbudgettype(){
		 return S_BUDGETTYPE;
	}
	/**
	 * Getter S_BDGORGCODE , NOT NULL   	 
	 */
	public static String columnSbdgorgcode(){
		 return S_BDGORGCODE;
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 */
	public static String columnSfuncsbtcode(){
		 return S_FUNCSBTCODE;
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static String columnSecnomicsubjectcode(){
		 return S_ECNOMICSUBJECTCODE;
	}
	/**
	 * Getter N_AMT , NOT NULL   	 
	 */
	public static String columnNamt(){
		 return N_AMT;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnSfilename(){
		 return S_FILENAME;
	}
	/**
	 * Getter S_RESULT   	 
	 */
	public static String columnSresult(){
		 return S_RESULT;
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/**
	 * Getter S_BOOKORGCODE   	 
	 */
	public static String columnSbookorgcode(){
		 return S_BOOKORGCODE;
	}
	/**
	 * Getter S_STATUS   	 
	 */
	public static String columnSstatus(){
		 return S_STATUS;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStrecode(){
		 return "String";
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 */
	public static String columnJavaTypeSbillorg(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEBANKNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeebankno(){
		 return "String";
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeracct(){
		 return "String";
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayername(){
		 return "String";
	}
	/**
	 * Getter S_PAYERADDR   	 
	 */
	public static String columnJavaTypeSpayeraddr(){
		 return "String";
	}
	/**
	 * Getter S_ENTRUSTDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSentrustdate(){
		 return "String";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackageno(){
		 return "String";
	}
	/**
	 * Getter S_PAYOUTVOUTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayoutvoutype(){
		 return "String";
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSvouno(){
		 return "String";
	}
	/**
	 * Getter S_VOUDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSvoudate(){
		 return "String";
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static String columnJavaTypeSaddword(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbudgettype(){
		 return "String";
	}
	/**
	 * Getter S_BDGORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbdgorgcode(){
		 return "String";
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfuncsbtcode(){
		 return "String";
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static String columnJavaTypeSecnomicsubjectcode(){
		 return "String";
	}
	/**
	 * Getter N_AMT , NOT NULL   	 
	 */
	public static String columnJavaTypeNamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSfilename(){
		 return "String";
	}
	/**
	 * Getter S_RESULT   	 
	 */
	public static String columnJavaTypeSresult(){
		 return "String";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/**
	 * Getter S_BOOKORGCODE   	 
	 */
	public static String columnJavaTypeSbookorgcode(){
		 return "String";
	}
	/**
	 * Getter S_STATUS   	 
	 */
	public static String columnJavaTypeSstatus(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrecode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbillorg(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEBANKNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeebankno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeracct(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayername(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERADDR   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeraddr(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ENTRUSTDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSentrustdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpackageno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYOUTVOUTYPE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpayoutvoutype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvouno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_VOUDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSvoudate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ADDWORD   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSaddword(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbudgettype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BDGORGCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdgorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfuncsbtcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSecnomicsubjectcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_AMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_RESULT   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSresult(){
		 return "VARCHAR";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/**
	 * Getter S_BOOKORGCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbookorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_STATUS   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSstatus(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static int columnWidthStrecode(){
		 return 10;
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 */
	public static int columnWidthSbillorg(){
		 return 30;
	}
	/**
	 * Getter S_PAYEEBANKNO , NOT NULL   	 
	 */
	public static int columnWidthSpayeebankno(){
		 return 12;
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static int columnWidthSpayeracct(){
		 return 32;
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 */
	public static int columnWidthSpayername(){
		 return 120;
	}
	/**
	 * Getter S_PAYERADDR   	 
	 */
	public static int columnWidthSpayeraddr(){
		 return 120;
	}
	/**
	 * Getter S_ENTRUSTDATE , NOT NULL   	 
	 */
	public static int columnWidthSentrustdate(){
		 return 8;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static int columnWidthSpackageno(){
		 return 8;
	}
	/**
	 * Getter S_PAYOUTVOUTYPE , NOT NULL   	 
	 */
	public static int columnWidthSpayoutvoutype(){
		 return 1;
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static int columnWidthSvouno(){
		 return 20;
	}
	/**
	 * Getter S_VOUDATE , NOT NULL   	 
	 */
	public static int columnWidthSvoudate(){
		 return 8;
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static int columnWidthSaddword(){
		 return 120;
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static int columnWidthSbudgettype(){
		 return 1;
	}
	/**
	 * Getter S_BDGORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSbdgorgcode(){
		 return 30;
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 */
	public static int columnWidthSfuncsbtcode(){
		 return 30;
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static int columnWidthSecnomicsubjectcode(){
		 return 30;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static int columnWidthSfilename(){
		 return 100;
	}
	/**
	 * Getter S_RESULT   	 
	 */
	public static int columnWidthSresult(){
		 return 180;
	}
	/**
	 * Getter S_BOOKORGCODE   	 
	 */
	public static int columnWidthSbookorgcode(){
		 return 12;
	}
	/**
	 * Getter S_STATUS   	 
	 */
	public static int columnWidthSstatus(){
		 return 5;
	}
}