      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: HTV_PAYOUTMSGSUB</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:56 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class HtvPayoutmsgsubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "HTV_PAYOUTMSGSUB";
	
	/**
	 * column S_BIZNO
	 */
	public static String S_BIZNO ="S_BIZNO";
	/**
	 * column S_SEQNO
	 */
	public static String S_SEQNO ="S_SEQNO";
	/**
	 * column S_ACCDATE
	 */
	public static String S_ACCDATE ="S_ACCDATE";
	/**
	 * column S_ECNOMICSUBJECTCODE
	 */
	public static String S_ECNOMICSUBJECTCODE ="S_ECNOMICSUBJECTCODE";
	/**
	 * column S_BUDGETPRJCODE
	 */
	public static String S_BUDGETPRJCODE ="S_BUDGETPRJCODE";
	/**
	 * column N_MONEY
	 */
	public static String N_MONEY ="N_MONEY";
	/**
	 * column S_FUNSUBJECTCODE
	 */
	public static String S_FUNSUBJECTCODE ="S_FUNSUBJECTCODE";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * column S_TAXTICKETNO
	 */
	public static String S_TAXTICKETNO ="S_TAXTICKETNO";
	/**
	 * column S_BGTTYPECODE
	 */
	public static String S_BGTTYPECODE ="S_BGTTYPECODE";
	/**
	 * column S_BGTTYPENAME
	 */
	public static String S_BGTTYPENAME ="S_BGTTYPENAME";
	/**
	 * column S_PROCATCODE
	 */
	public static String S_PROCATCODE ="S_PROCATCODE";
	/**
	 * column S_PROCATNAME
	 */
	public static String S_PROCATNAME ="S_PROCATNAME";
	/**
	 * column S_AGENCYCODE
	 */
	public static String S_AGENCYCODE ="S_AGENCYCODE";
	/**
	 * column S_AGENCYNAME
	 */
	public static String S_AGENCYNAME ="S_AGENCYNAME";
	/**
	 * column S_EXPFUNCNAME
	 */
	public static String S_EXPFUNCNAME ="S_EXPFUNCNAME";
	/**
	 * column S_EXPFUNCCODE1
	 */
	public static String S_EXPFUNCCODE1 ="S_EXPFUNCCODE1";
	/**
	 * column S_EXPFUNCNAME1
	 */
	public static String S_EXPFUNCNAME1 ="S_EXPFUNCNAME1";
	/**
	 * column S_EXPFUNCCODE2
	 */
	public static String S_EXPFUNCCODE2 ="S_EXPFUNCCODE2";
	/**
	 * column S_EXPFUNCNAME2
	 */
	public static String S_EXPFUNCNAME2 ="S_EXPFUNCNAME2";
	/**
	 * column S_EXPFUNCCODE3
	 */
	public static String S_EXPFUNCCODE3 ="S_EXPFUNCCODE3";
	/**
	 * column S_EXPFUNCNAME3
	 */
	public static String S_EXPFUNCNAME3 ="S_EXPFUNCNAME3";
	/**
	 * column S_EXPECOCODE
	 */
	public static String S_EXPECOCODE ="S_EXPECOCODE";
	/**
	 * column S_EXPECONAME
	 */
	public static String S_EXPECONAME ="S_EXPECONAME";
	/**
	 * column S_EXPECOCODE1
	 */
	public static String S_EXPECOCODE1 ="S_EXPECOCODE1";
	/**
	 * column S_EXPECONAME1
	 */
	public static String S_EXPECONAME1 ="S_EXPECONAME1";
	/**
	 * column S_EXPECOCODE2
	 */
	public static String S_EXPECOCODE2 ="S_EXPECOCODE2";
	/**
	 * column S_EXPECONAME2
	 */
	public static String S_EXPECONAME2 ="S_EXPECONAME2";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_HOLD3
	 */
	public static String S_HOLD3 ="S_HOLD3";
	/**
	 * column S_HOLD4
	 */
	public static String S_HOLD4 ="S_HOLD4";
	/**
	 * column S_PAYEEACCTNO
	 */
	public static String S_PAYEEACCTNO ="S_PAYEEACCTNO";
	/**
	 * column S_PAYEEACCTNAME
	 */
	public static String S_PAYEEACCTNAME ="S_PAYEEACCTNAME";
	/**
	 * column S_PAYEEACCTBANKNAME
	 */
	public static String S_PAYEEACCTBANKNAME ="S_PAYEEACCTBANKNAME";
	/**
	 * column S_PAYSUMMARYCODE
	 */
	public static String S_PAYSUMMARYCODE ="S_PAYSUMMARYCODE";
	/**
	 * column S_PAYSUMMARYNAME
	 */
	public static String S_PAYSUMMARYNAME ="S_PAYSUMMARYNAME";
	/**
	 * column S_XPAYAMT
	 */
	public static String S_XPAYAMT ="S_XPAYAMT";
	/**
	 * column S_XPAYDATE
	 */
	public static String S_XPAYDATE ="S_XPAYDATE";
	/**
	 * column S_XAGENTBUSINESSNO
	 */
	public static String S_XAGENTBUSINESSNO ="S_XAGENTBUSINESSNO";
	/**
	 * column S_XADDWORD
	 */
	public static String S_XADDWORD ="S_XADDWORD";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[42];        
        columnNames[0]="S_BIZNO";
        columnNames[1]="S_SEQNO";
        columnNames[2]="S_ACCDATE";
        columnNames[3]="S_ECNOMICSUBJECTCODE";
        columnNames[4]="S_BUDGETPRJCODE";
        columnNames[5]="N_MONEY";
        columnNames[6]="S_FUNSUBJECTCODE";
        columnNames[7]="TS_SYSUPDATE";
        columnNames[8]="S_TAXTICKETNO";
        columnNames[9]="S_BGTTYPECODE";
        columnNames[10]="S_BGTTYPENAME";
        columnNames[11]="S_PROCATCODE";
        columnNames[12]="S_PROCATNAME";
        columnNames[13]="S_AGENCYCODE";
        columnNames[14]="S_AGENCYNAME";
        columnNames[15]="S_EXPFUNCNAME";
        columnNames[16]="S_EXPFUNCCODE1";
        columnNames[17]="S_EXPFUNCNAME1";
        columnNames[18]="S_EXPFUNCCODE2";
        columnNames[19]="S_EXPFUNCNAME2";
        columnNames[20]="S_EXPFUNCCODE3";
        columnNames[21]="S_EXPFUNCNAME3";
        columnNames[22]="S_EXPECOCODE";
        columnNames[23]="S_EXPECONAME";
        columnNames[24]="S_EXPECOCODE1";
        columnNames[25]="S_EXPECONAME1";
        columnNames[26]="S_EXPECOCODE2";
        columnNames[27]="S_EXPECONAME2";
        columnNames[28]="S_HOLD1";
        columnNames[29]="S_HOLD2";
        columnNames[30]="S_HOLD3";
        columnNames[31]="S_HOLD4";
        columnNames[32]="S_PAYEEACCTNO";
        columnNames[33]="S_PAYEEACCTNAME";
        columnNames[34]="S_PAYEEACCTBANKNAME";
        columnNames[35]="S_PAYSUMMARYCODE";
        columnNames[36]="S_PAYSUMMARYNAME";
        columnNames[37]="S_XPAYAMT";
        columnNames[38]="S_XPAYDATE";
        columnNames[39]="S_XAGENTBUSINESSNO";
        columnNames[40]="S_XADDWORD";
        columnNames[41]="S_ID";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 */
	public static String columnSbizno(){
		 return S_BIZNO;
	}
	/**
	 * Getter S_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnSseqno(){
		 return S_SEQNO;
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 */
	public static String columnSaccdate(){
		 return S_ACCDATE;
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static String columnSecnomicsubjectcode(){
		 return S_ECNOMICSUBJECTCODE;
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 */
	public static String columnSbudgetprjcode(){
		 return S_BUDGETPRJCODE;
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnNmoney(){
		 return N_MONEY;
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnSfunsubjectcode(){
		 return S_FUNSUBJECTCODE;
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/**
	 * Getter S_TAXTICKETNO   	 
	 */
	public static String columnStaxticketno(){
		 return S_TAXTICKETNO;
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static String columnSbgttypecode(){
		 return S_BGTTYPECODE;
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static String columnSbgttypename(){
		 return S_BGTTYPENAME;
	}
	/**
	 * Getter S_PROCATCODE   	 
	 */
	public static String columnSprocatcode(){
		 return S_PROCATCODE;
	}
	/**
	 * Getter S_PROCATNAME   	 
	 */
	public static String columnSprocatname(){
		 return S_PROCATNAME;
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 */
	public static String columnSagencycode(){
		 return S_AGENCYCODE;
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 */
	public static String columnSagencyname(){
		 return S_AGENCYNAME;
	}
	/**
	 * Getter S_EXPFUNCNAME   	 
	 */
	public static String columnSexpfuncname(){
		 return S_EXPFUNCNAME;
	}
	/**
	 * Getter S_EXPFUNCCODE1   	 
	 */
	public static String columnSexpfunccode1(){
		 return S_EXPFUNCCODE1;
	}
	/**
	 * Getter S_EXPFUNCNAME1   	 
	 */
	public static String columnSexpfuncname1(){
		 return S_EXPFUNCNAME1;
	}
	/**
	 * Getter S_EXPFUNCCODE2   	 
	 */
	public static String columnSexpfunccode2(){
		 return S_EXPFUNCCODE2;
	}
	/**
	 * Getter S_EXPFUNCNAME2   	 
	 */
	public static String columnSexpfuncname2(){
		 return S_EXPFUNCNAME2;
	}
	/**
	 * Getter S_EXPFUNCCODE3   	 
	 */
	public static String columnSexpfunccode3(){
		 return S_EXPFUNCCODE3;
	}
	/**
	 * Getter S_EXPFUNCNAME3   	 
	 */
	public static String columnSexpfuncname3(){
		 return S_EXPFUNCNAME3;
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 */
	public static String columnSexpecocode(){
		 return S_EXPECOCODE;
	}
	/**
	 * Getter S_EXPECONAME   	 
	 */
	public static String columnSexpeconame(){
		 return S_EXPECONAME;
	}
	/**
	 * Getter S_EXPECOCODE1   	 
	 */
	public static String columnSexpecocode1(){
		 return S_EXPECOCODE1;
	}
	/**
	 * Getter S_EXPECONAME1   	 
	 */
	public static String columnSexpeconame1(){
		 return S_EXPECONAME1;
	}
	/**
	 * Getter S_EXPECOCODE2   	 
	 */
	public static String columnSexpecocode2(){
		 return S_EXPECOCODE2;
	}
	/**
	 * Getter S_EXPECONAME2   	 
	 */
	public static String columnSexpeconame2(){
		 return S_EXPECONAME2;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnShold3(){
		 return S_HOLD3;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnShold4(){
		 return S_HOLD4;
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 */
	public static String columnSpayeeacctno(){
		 return S_PAYEEACCTNO;
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnSpayeeacctname(){
		 return S_PAYEEACCTNAME;
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnSpayeeacctbankname(){
		 return S_PAYEEACCTBANKNAME;
	}
	/**
	 *用途编码 Getter S_PAYSUMMARYCODE   	 
	 */
	public static String columnSpaysummarycode(){
		 return S_PAYSUMMARYCODE;
	}
	/**
	 *用途名称 Getter S_PAYSUMMARYNAME   	 
	 */
	public static String columnSpaysummaryname(){
		 return S_PAYSUMMARYNAME;
	}
	/**
	 *实际支付金额,人民银行在回单中补录 Getter S_XPAYAMT   	 
	 */
	public static String columnSxpayamt(){
		 return S_XPAYAMT;
	}
	/**
	 *人民银行处理日期，人民银行在回单中补录 Getter S_XPAYDATE   	 
	 */
	public static String columnSxpaydate(){
		 return S_XPAYDATE;
	}
	/**
	 *银行交易流水号,人民银行在回单中补录 Getter S_XAGENTBUSINESSNO   	 
	 */
	public static String columnSxagentbusinessno(){
		 return S_XAGENTBUSINESSNO;
	}
	/**
	 *失败原因 Getter S_XADDWORD   	 
	 */
	public static String columnSxaddword(){
		 return S_XADDWORD;
	}
	/**
	 *拨款凭证明细ID Getter S_ID   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSbizno(){
		 return "String";
	}
	/**
	 * Getter S_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSseqno(){
		 return "Integer";
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSaccdate(){
		 return "String";
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static String columnJavaTypeSecnomicsubjectcode(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 */
	public static String columnJavaTypeSbudgetprjcode(){
		 return "String";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnJavaTypeNmoney(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfunsubjectcode(){
		 return "String";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/**
	 * Getter S_TAXTICKETNO   	 
	 */
	public static String columnJavaTypeStaxticketno(){
		 return "String";
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static String columnJavaTypeSbgttypecode(){
		 return "String";
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static String columnJavaTypeSbgttypename(){
		 return "String";
	}
	/**
	 * Getter S_PROCATCODE   	 
	 */
	public static String columnJavaTypeSprocatcode(){
		 return "String";
	}
	/**
	 * Getter S_PROCATNAME   	 
	 */
	public static String columnJavaTypeSprocatname(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 */
	public static String columnJavaTypeSagencycode(){
		 return "String";
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 */
	public static String columnJavaTypeSagencyname(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCNAME   	 
	 */
	public static String columnJavaTypeSexpfuncname(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCCODE1   	 
	 */
	public static String columnJavaTypeSexpfunccode1(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCNAME1   	 
	 */
	public static String columnJavaTypeSexpfuncname1(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCCODE2   	 
	 */
	public static String columnJavaTypeSexpfunccode2(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCNAME2   	 
	 */
	public static String columnJavaTypeSexpfuncname2(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCCODE3   	 
	 */
	public static String columnJavaTypeSexpfunccode3(){
		 return "String";
	}
	/**
	 * Getter S_EXPFUNCNAME3   	 
	 */
	public static String columnJavaTypeSexpfuncname3(){
		 return "String";
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 */
	public static String columnJavaTypeSexpecocode(){
		 return "String";
	}
	/**
	 * Getter S_EXPECONAME   	 
	 */
	public static String columnJavaTypeSexpeconame(){
		 return "String";
	}
	/**
	 * Getter S_EXPECOCODE1   	 
	 */
	public static String columnJavaTypeSexpecocode1(){
		 return "String";
	}
	/**
	 * Getter S_EXPECONAME1   	 
	 */
	public static String columnJavaTypeSexpeconame1(){
		 return "String";
	}
	/**
	 * Getter S_EXPECOCODE2   	 
	 */
	public static String columnJavaTypeSexpecocode2(){
		 return "String";
	}
	/**
	 * Getter S_EXPECONAME2   	 
	 */
	public static String columnJavaTypeSexpeconame2(){
		 return "String";
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnJavaTypeShold3(){
		 return "String";
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnJavaTypeShold4(){
		 return "String";
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 */
	public static String columnJavaTypeSpayeeacctno(){
		 return "String";
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctname(){
		 return "String";
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctbankname(){
		 return "String";
	}
	/**
	 *用途编码 Getter S_PAYSUMMARYCODE   	 
	 */
	public static String columnJavaTypeSpaysummarycode(){
		 return "String";
	}
	/**
	 *用途名称 Getter S_PAYSUMMARYNAME   	 
	 */
	public static String columnJavaTypeSpaysummaryname(){
		 return "String";
	}
	/**
	 *实际支付金额,人民银行在回单中补录 Getter S_XPAYAMT   	 
	 */
	public static String columnJavaTypeSxpayamt(){
		 return "BigDecimal";
	}
	/**
	 *人民银行处理日期，人民银行在回单中补录 Getter S_XPAYDATE   	 
	 */
	public static String columnJavaTypeSxpaydate(){
		 return "String";
	}
	/**
	 *银行交易流水号,人民银行在回单中补录 Getter S_XAGENTBUSINESSNO   	 
	 */
	public static String columnJavaTypeSxagentbusinessno(){
		 return "String";
	}
	/**
	 *失败原因 Getter S_XADDWORD   	 
	 */
	public static String columnJavaTypeSxaddword(){
		 return "String";
	}
	/**
	 *拨款凭证明细ID Getter S_ID   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbizno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_SEQNO, PK , NOT NULL   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeSseqno(){
		 return "INTEGER";
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSaccdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSecnomicsubjectcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbudgetprjcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNmoney(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfunsubjectcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/**
	 * Getter S_TAXTICKETNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxticketno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PROCATCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSprocatcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PROCATNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSprocatname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencycode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencyname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfuncname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCCODE1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfunccode1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCNAME1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfuncname1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCCODE2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfunccode2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCNAME2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfuncname2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCCODE3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfunccode3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPFUNCNAME3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfuncname3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpecocode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECONAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpeconame(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECOCODE1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpecocode1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECONAME1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpeconame1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECOCODE2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpecocode2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_EXPECONAME2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpeconame2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold4(){
		 return "VARCHAR";
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctno(){
		 return "VARCHAR";
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctname(){
		 return "VARCHAR";
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctbankname(){
		 return "VARCHAR";
	}
	/**
	 *用途编码 Getter S_PAYSUMMARYCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaysummarycode(){
		 return "VARCHAR";
	}
	/**
	 *用途名称 Getter S_PAYSUMMARYNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaysummaryname(){
		 return "VARCHAR";
	}
	/**
	 *实际支付金额,人民银行在回单中补录 Getter S_XPAYAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeSxpayamt(){
		 return "DECIMAL";
	}
	/**
	 *人民银行处理日期，人民银行在回单中补录 Getter S_XPAYDATE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxpaydate(){
		 return "VARCHAR";
	}
	/**
	 *银行交易流水号,人民银行在回单中补录 Getter S_XAGENTBUSINESSNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxagentbusinessno(){
		 return "VARCHAR";
	}
	/**
	 *失败原因 Getter S_XADDWORD   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxaddword(){
		 return "VARCHAR";
	}
	/**
	 *拨款凭证明细ID Getter S_ID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 */
	public static int columnWidthSbizno(){
		 return 20;
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 */
	public static int columnWidthSaccdate(){
		 return 8;
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static int columnWidthSecnomicsubjectcode(){
		 return 30;
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 */
	public static int columnWidthSbudgetprjcode(){
		 return 30;
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static int columnWidthSfunsubjectcode(){
		 return 30;
	}
	/**
	 * Getter S_TAXTICKETNO   	 
	 */
	public static int columnWidthStaxticketno(){
		 return 30;
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static int columnWidthSbgttypecode(){
		 return 42;
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static int columnWidthSbgttypename(){
		 return 60;
	}
	/**
	 * Getter S_PROCATCODE   	 
	 */
	public static int columnWidthSprocatcode(){
		 return 42;
	}
	/**
	 * Getter S_PROCATNAME   	 
	 */
	public static int columnWidthSprocatname(){
		 return 60;
	}
	/**
	 * Getter S_AGENCYCODE   	 
	 */
	public static int columnWidthSagencycode(){
		 return 42;
	}
	/**
	 * Getter S_AGENCYNAME   	 
	 */
	public static int columnWidthSagencyname(){
		 return 60;
	}
	/**
	 * Getter S_EXPFUNCNAME   	 
	 */
	public static int columnWidthSexpfuncname(){
		 return 60;
	}
	/**
	 * Getter S_EXPFUNCCODE1   	 
	 */
	public static int columnWidthSexpfunccode1(){
		 return 42;
	}
	/**
	 * Getter S_EXPFUNCNAME1   	 
	 */
	public static int columnWidthSexpfuncname1(){
		 return 60;
	}
	/**
	 * Getter S_EXPFUNCCODE2   	 
	 */
	public static int columnWidthSexpfunccode2(){
		 return 42;
	}
	/**
	 * Getter S_EXPFUNCNAME2   	 
	 */
	public static int columnWidthSexpfuncname2(){
		 return 60;
	}
	/**
	 * Getter S_EXPFUNCCODE3   	 
	 */
	public static int columnWidthSexpfunccode3(){
		 return 42;
	}
	/**
	 * Getter S_EXPFUNCNAME3   	 
	 */
	public static int columnWidthSexpfuncname3(){
		 return 60;
	}
	/**
	 * Getter S_EXPECOCODE   	 
	 */
	public static int columnWidthSexpecocode(){
		 return 42;
	}
	/**
	 * Getter S_EXPECONAME   	 
	 */
	public static int columnWidthSexpeconame(){
		 return 60;
	}
	/**
	 * Getter S_EXPECOCODE1   	 
	 */
	public static int columnWidthSexpecocode1(){
		 return 42;
	}
	/**
	 * Getter S_EXPECONAME1   	 
	 */
	public static int columnWidthSexpeconame1(){
		 return 60;
	}
	/**
	 * Getter S_EXPECOCODE2   	 
	 */
	public static int columnWidthSexpecocode2(){
		 return 42;
	}
	/**
	 * Getter S_EXPECONAME2   	 
	 */
	public static int columnWidthSexpeconame2(){
		 return 60;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static int columnWidthShold3(){
		 return 42;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static int columnWidthShold4(){
		 return 42;
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 */
	public static int columnWidthSpayeeacctno(){
		 return 32;
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 */
	public static int columnWidthSpayeeacctname(){
		 return 120;
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static int columnWidthSpayeeacctbankname(){
		 return 60;
	}
	/**
	 *用途编码 Getter S_PAYSUMMARYCODE   	 
	 */
	public static int columnWidthSpaysummarycode(){
		 return 42;
	}
	/**
	 *用途名称 Getter S_PAYSUMMARYNAME   	 
	 */
	public static int columnWidthSpaysummaryname(){
		 return 200;
	}
	/**
	 *人民银行处理日期，人民银行在回单中补录 Getter S_XPAYDATE   	 
	 */
	public static int columnWidthSxpaydate(){
		 return 10;
	}
	/**
	 *银行交易流水号,人民银行在回单中补录 Getter S_XAGENTBUSINESSNO   	 
	 */
	public static int columnWidthSxagentbusinessno(){
		 return 60;
	}
	/**
	 *失败原因 Getter S_XADDWORD   	 
	 */
	public static int columnWidthSxaddword(){
		 return 120;
	}
	/**
	 *拨款凭证明细ID Getter S_ID   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
}