      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: HTV_TAX_KIND</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:56 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class HtvTaxKindInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "HTV_TAX_KIND";
	
	/**
	 * column S_SEQ
	 */
	public static String S_SEQ ="S_SEQ";
	/**
	 * column I_PROJECTID
	 */
	public static String I_PROJECTID ="I_PROJECTID";
	/**
	 * column S_LIMITDATE
	 */
	public static String S_LIMITDATE ="S_LIMITDATE";
	/**
	 * column S_BUDGETSUBJECTCODE
	 */
	public static String S_BUDGETSUBJECTCODE ="S_BUDGETSUBJECTCODE";
	/**
	 * column S_TAXTYPENAME
	 */
	public static String S_TAXTYPENAME ="S_TAXTYPENAME";
	/**
	 * column C_BUDGETLEVEL
	 */
	public static String C_BUDGETLEVEL ="C_BUDGETLEVEL";
	/**
	 * column S_VICESIGN
	 */
	public static String S_VICESIGN ="S_VICESIGN";
	/**
	 * column F_SUBJECTAMT
	 */
	public static String F_SUBJECTAMT ="F_SUBJECTAMT";
	/**
	 * column C_TAXTYPE
	 */
	public static String C_TAXTYPE ="C_TAXTYPE";
	/**
	 * column S_TAXSTARTDATE
	 */
	public static String S_TAXSTARTDATE ="S_TAXSTARTDATE";
	/**
	 * column I_DETAILNO
	 */
	public static String I_DETAILNO ="I_DETAILNO";
	/**
	 * column S_TAXENDDATE
	 */
	public static String S_TAXENDDATE ="S_TAXENDDATE";
	/**
	 * column TS_UPDATE
	 */
	public static String TS_UPDATE ="TS_UPDATE";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[13];        
        columnNames[0]="S_SEQ";
        columnNames[1]="I_PROJECTID";
        columnNames[2]="S_LIMITDATE";
        columnNames[3]="S_BUDGETSUBJECTCODE";
        columnNames[4]="S_TAXTYPENAME";
        columnNames[5]="C_BUDGETLEVEL";
        columnNames[6]="S_VICESIGN";
        columnNames[7]="F_SUBJECTAMT";
        columnNames[8]="C_TAXTYPE";
        columnNames[9]="S_TAXSTARTDATE";
        columnNames[10]="I_DETAILNO";
        columnNames[11]="S_TAXENDDATE";
        columnNames[12]="TS_UPDATE";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_SEQ, PK , NOT NULL   	 
	 */
	public static String columnSseq(){
		 return S_SEQ;
	}
	/**
	 * Getter I_PROJECTID, PK , NOT NULL   	 
	 */
	public static String columnIprojectid(){
		 return I_PROJECTID;
	}
	/**
	 * Getter S_LIMITDATE , NOT NULL   	 
	 */
	public static String columnSlimitdate(){
		 return S_LIMITDATE;
	}
	/**
	 * Getter S_BUDGETSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnSbudgetsubjectcode(){
		 return S_BUDGETSUBJECTCODE;
	}
	/**
	 * Getter S_TAXTYPENAME , NOT NULL   	 
	 */
	public static String columnStaxtypename(){
		 return S_TAXTYPENAME;
	}
	/**
	 * Getter C_BUDGETLEVEL , NOT NULL   	 
	 */
	public static String columnCbudgetlevel(){
		 return C_BUDGETLEVEL;
	}
	/**
	 * Getter S_VICESIGN   	 
	 */
	public static String columnSvicesign(){
		 return S_VICESIGN;
	}
	/**
	 * Getter F_SUBJECTAMT , NOT NULL   	 
	 */
	public static String columnFsubjectamt(){
		 return F_SUBJECTAMT;
	}
	/**
	 * Getter C_TAXTYPE , NOT NULL   	 
	 */
	public static String columnCtaxtype(){
		 return C_TAXTYPE;
	}
	/**
	 * Getter S_TAXSTARTDATE , NOT NULL   	 
	 */
	public static String columnStaxstartdate(){
		 return S_TAXSTARTDATE;
	}
	/**
	 * Getter I_DETAILNO   	 
	 */
	public static String columnIdetailno(){
		 return I_DETAILNO;
	}
	/**
	 * Getter S_TAXENDDATE , NOT NULL   	 
	 */
	public static String columnStaxenddate(){
		 return S_TAXENDDATE;
	}
	/**
	 * Getter TS_UPDATE , NOT NULL   	 
	 */
	public static String columnTsupdate(){
		 return TS_UPDATE;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_SEQ, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSseq(){
		 return "String";
	}
	/**
	 * Getter I_PROJECTID, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIprojectid(){
		 return "Integer";
	}
	/**
	 * Getter S_LIMITDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSlimitdate(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbudgetsubjectcode(){
		 return "String";
	}
	/**
	 * Getter S_TAXTYPENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxtypename(){
		 return "String";
	}
	/**
	 * Getter C_BUDGETLEVEL , NOT NULL   	 
	 */
	public static String columnJavaTypeCbudgetlevel(){
		 return "String";
	}
	/**
	 * Getter S_VICESIGN   	 
	 */
	public static String columnJavaTypeSvicesign(){
		 return "String";
	}
	/**
	 * Getter F_SUBJECTAMT , NOT NULL   	 
	 */
	public static String columnJavaTypeFsubjectamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter C_TAXTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeCtaxtype(){
		 return "String";
	}
	/**
	 * Getter S_TAXSTARTDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxstartdate(){
		 return "String";
	}
	/**
	 * Getter I_DETAILNO   	 
	 */
	public static String columnJavaTypeIdetailno(){
		 return "Integer";
	}
	/**
	 * Getter S_TAXENDDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxenddate(){
		 return "String";
	}
	/**
	 * Getter TS_UPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTsupdate(){
		 return "Timestamp";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_SEQ, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSseq(){
		 return "VARCHAR";
	}
	/**
	 * Getter I_PROJECTID, PK , NOT NULL   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeIprojectid(){
		 return "INTEGER";
	}
	/**
	 * Getter S_LIMITDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSlimitdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BUDGETSUBJECTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbudgetsubjectcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_TAXTYPENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxtypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter C_BUDGETLEVEL , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeCbudgetlevel(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_VICESIGN   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSvicesign(){
		 return "CHARACTER";
	}
	/**
	 * Getter F_SUBJECTAMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFsubjectamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter C_TAXTYPE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeCtaxtype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TAXSTARTDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStaxstartdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter I_DETAILNO   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeIdetailno(){
		 return "INTEGER";
	}
	/**
	 * Getter S_TAXENDDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStaxenddate(){
		 return "CHARACTER";
	}
	/**
	 * Getter TS_UPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTsupdate(){
		 return "TIMESTAMP";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_SEQ, PK , NOT NULL   	 
	 */
	public static int columnWidthSseq(){
		 return 20;
	}
	/**
	 * Getter S_LIMITDATE , NOT NULL   	 
	 */
	public static int columnWidthSlimitdate(){
		 return 8;
	}
	/**
	 * Getter S_BUDGETSUBJECTCODE , NOT NULL   	 
	 */
	public static int columnWidthSbudgetsubjectcode(){
		 return 30;
	}
	/**
	 * Getter S_TAXTYPENAME , NOT NULL   	 
	 */
	public static int columnWidthStaxtypename(){
		 return 60;
	}
	/**
	 * Getter C_BUDGETLEVEL , NOT NULL   	 
	 */
	public static int columnWidthCbudgetlevel(){
		 return 1;
	}
	/**
	 * Getter S_VICESIGN   	 
	 */
	public static int columnWidthSvicesign(){
		 return 35;
	}
	/**
	 * Getter C_TAXTYPE , NOT NULL   	 
	 */
	public static int columnWidthCtaxtype(){
		 return 1;
	}
	/**
	 * Getter S_TAXSTARTDATE , NOT NULL   	 
	 */
	public static int columnWidthStaxstartdate(){
		 return 8;
	}
	/**
	 * Getter S_TAXENDDATE , NOT NULL   	 
	 */
	public static int columnWidthStaxenddate(){
		 return 8;
	}
}