      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TBS_TV_DIRECTPAYPLAN_SUB</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:57 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TbsTvDirectpayplanSubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TBS_TV_DIRECTPAYPLAN_SUB";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column I_DETAILSEQNO
	 */
	public static String I_DETAILSEQNO ="I_DETAILSEQNO";
	/**
	 * column S_BDGORGCODE
	 */
	public static String S_BDGORGCODE ="S_BDGORGCODE";
	/**
	 * column S_FUNCSBTCODE
	 */
	public static String S_FUNCSBTCODE ="S_FUNCSBTCODE";
	/**
	 * column S_ECOSBTCODE
	 */
	public static String S_ECOSBTCODE ="S_ECOSBTCODE";
	/**
	 * column F_AMT
	 */
	public static String F_AMT ="F_AMT";
	/**
	 * column S_BOOKORGCODE
	 */
	public static String S_BOOKORGCODE ="S_BOOKORGCODE";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[8];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="I_DETAILSEQNO";
        columnNames[2]="S_BDGORGCODE";
        columnNames[3]="S_FUNCSBTCODE";
        columnNames[4]="S_ECOSBTCODE";
        columnNames[5]="F_AMT";
        columnNames[6]="S_BOOKORGCODE";
        columnNames[7]="TS_SYSUPDATE";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter I_DETAILSEQNO, PK , NOT NULL   	 
	 */
	public static String columnIdetailseqno(){
		 return I_DETAILSEQNO;
	}
	/**
	 * Getter S_BDGORGCODE   	 
	 */
	public static String columnSbdgorgcode(){
		 return S_BDGORGCODE;
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 */
	public static String columnSfuncsbtcode(){
		 return S_FUNCSBTCODE;
	}
	/**
	 * Getter S_ECOSBTCODE , NOT NULL   	 
	 */
	public static String columnSecosbtcode(){
		 return S_ECOSBTCODE;
	}
	/**
	 * Getter F_AMT , NOT NULL   	 
	 */
	public static String columnFamt(){
		 return F_AMT;
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static String columnSbookorgcode(){
		 return S_BOOKORGCODE;
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter I_DETAILSEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIdetailseqno(){
		 return "Integer";
	}
	/**
	 * Getter S_BDGORGCODE   	 
	 */
	public static String columnJavaTypeSbdgorgcode(){
		 return "String";
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfuncsbtcode(){
		 return "String";
	}
	/**
	 * Getter S_ECOSBTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSecosbtcode(){
		 return "String";
	}
	/**
	 * Getter F_AMT , NOT NULL   	 
	 */
	public static String columnJavaTypeFamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbookorgcode(){
		 return "String";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter I_DETAILSEQNO, PK , NOT NULL   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeIdetailseqno(){
		 return "INTEGER";
	}
	/**
	 * Getter S_BDGORGCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdgorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfuncsbtcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ECOSBTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSecosbtcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter F_AMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbookorgcode(){
		 return "CHARACTER";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_BDGORGCODE   	 
	 */
	public static int columnWidthSbdgorgcode(){
		 return 15;
	}
	/**
	 * Getter S_FUNCSBTCODE , NOT NULL   	 
	 */
	public static int columnWidthSfuncsbtcode(){
		 return 30;
	}
	/**
	 * Getter S_ECOSBTCODE , NOT NULL   	 
	 */
	public static int columnWidthSecosbtcode(){
		 return 30;
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSbookorgcode(){
		 return 12;
	}
}