      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TBS_TV_BNKPAY_MAIN</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:57 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TbsTvBnkpayMainInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TBS_TV_BNKPAY_MAIN";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column S_BOOKORGCODE
	 */
	public static String S_BOOKORGCODE ="S_BOOKORGCODE";
	/**
	 * column S_TRECODE
	 */
	public static String S_TRECODE ="S_TRECODE";
	/**
	 * column S_PACKNO
	 */
	public static String S_PACKNO ="S_PACKNO";
	/**
	 * column S_VOUNO
	 */
	public static String S_VOUNO ="S_VOUNO";
	/**
	 * column S_BIZTYPE
	 */
	public static String S_BIZTYPE ="S_BIZTYPE";
	/**
	 * column F_ZEROSUMAMT
	 */
	public static String F_ZEROSUMAMT ="F_ZEROSUMAMT";
	/**
	 * column F_SMALLSUMAMT
	 */
	public static String F_SMALLSUMAMT ="F_SMALLSUMAMT";
	/**
	 * column S_SNDBNKNO
	 */
	public static String S_SNDBNKNO ="S_SNDBNKNO";
	/**
	 * column S_PAYEROPNBNKNO
	 */
	public static String S_PAYEROPNBNKNO ="S_PAYEROPNBNKNO";
	/**
	 * column S_PAYERACCT
	 */
	public static String S_PAYERACCT ="S_PAYERACCT";
	/**
	 * column S_PAYERNAME
	 */
	public static String S_PAYERNAME ="S_PAYERNAME";
	/**
	 * column S_PAYERADDR
	 */
	public static String S_PAYERADDR ="S_PAYERADDR";
	/**
	 * column S_PAYEEACCT
	 */
	public static String S_PAYEEACCT ="S_PAYEEACCT";
	/**
	 * column S_PAYEENAME
	 */
	public static String S_PAYEENAME ="S_PAYEENAME";
	/**
	 * column S_PAYEEADDR
	 */
	public static String S_PAYEEADDR ="S_PAYEEADDR";
	/**
	 * column S_AGENTBNKCODE
	 */
	public static String S_AGENTBNKCODE ="S_AGENTBNKCODE";
	/**
	 * column S_RCVBNKNO
	 */
	public static String S_RCVBNKNO ="S_RCVBNKNO";
	/**
	 * column S_PAYEEOPNBNKNO
	 */
	public static String S_PAYEEOPNBNKNO ="S_PAYEEOPNBNKNO";
	/**
	 * column S_SRLACCTBRIEFCODE
	 */
	public static String S_SRLACCTBRIEFCODE ="S_SRLACCTBRIEFCODE";
	/**
	 * column S_ADDWORD
	 */
	public static String S_ADDWORD ="S_ADDWORD";
	/**
	 * column S_PAYDICTATENO
	 */
	public static String S_PAYDICTATENO ="S_PAYDICTATENO";
	/**
	 * column S_PAYMSGNO
	 */
	public static String S_PAYMSGNO ="S_PAYMSGNO";
	/**
	 * column D_PAYENTRUSTDATE
	 */
	public static String D_PAYENTRUSTDATE ="D_PAYENTRUSTDATE";
	/**
	 * column S_PAYSNDBNKNO
	 */
	public static String S_PAYSNDBNKNO ="S_PAYSNDBNKNO";
	/**
	 * column D_VOUCHER
	 */
	public static String D_VOUCHER ="D_VOUCHER";
	/**
	 * column C_BDGKIND
	 */
	public static String C_BDGKIND ="C_BDGKIND";
	/**
	 * column I_OFYEAR
	 */
	public static String I_OFYEAR ="I_OFYEAR";
	/**
	 * column D_ACCEPT
	 */
	public static String D_ACCEPT ="D_ACCEPT";
	/**
	 * column D_ACCT
	 */
	public static String D_ACCT ="D_ACCT";
	/**
	 * column S_ORIVOUNO
	 */
	public static String S_ORIVOUNO ="S_ORIVOUNO";
	/**
	 * column D_ORIVOUDATE
	 */
	public static String D_ORIVOUDATE ="D_ORIVOUDATE";
	/**
	 * column S_FILENAME
	 */
	public static String S_FILENAME ="S_FILENAME";
	/**
	 * column S_STATE
	 */
	public static String S_STATE ="S_STATE";
	/**
	 * column C_TRIMFLAG
	 */
	public static String C_TRIMFLAG ="C_TRIMFLAG";
	/**
	 * column I_CHGNUM
	 */
	public static String I_CHGNUM ="I_CHGNUM";
	/**
	 * column S_INPUTERID
	 */
	public static String S_INPUTERID ="S_INPUTERID";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * column S_IFMATCH
	 */
	public static String S_IFMATCH ="S_IFMATCH";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[39];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="S_BOOKORGCODE";
        columnNames[2]="S_TRECODE";
        columnNames[3]="S_PACKNO";
        columnNames[4]="S_VOUNO";
        columnNames[5]="S_BIZTYPE";
        columnNames[6]="F_ZEROSUMAMT";
        columnNames[7]="F_SMALLSUMAMT";
        columnNames[8]="S_SNDBNKNO";
        columnNames[9]="S_PAYEROPNBNKNO";
        columnNames[10]="S_PAYERACCT";
        columnNames[11]="S_PAYERNAME";
        columnNames[12]="S_PAYERADDR";
        columnNames[13]="S_PAYEEACCT";
        columnNames[14]="S_PAYEENAME";
        columnNames[15]="S_PAYEEADDR";
        columnNames[16]="S_AGENTBNKCODE";
        columnNames[17]="S_RCVBNKNO";
        columnNames[18]="S_PAYEEOPNBNKNO";
        columnNames[19]="S_SRLACCTBRIEFCODE";
        columnNames[20]="S_ADDWORD";
        columnNames[21]="S_PAYDICTATENO";
        columnNames[22]="S_PAYMSGNO";
        columnNames[23]="D_PAYENTRUSTDATE";
        columnNames[24]="S_PAYSNDBNKNO";
        columnNames[25]="D_VOUCHER";
        columnNames[26]="C_BDGKIND";
        columnNames[27]="I_OFYEAR";
        columnNames[28]="D_ACCEPT";
        columnNames[29]="D_ACCT";
        columnNames[30]="S_ORIVOUNO";
        columnNames[31]="D_ORIVOUDATE";
        columnNames[32]="S_FILENAME";
        columnNames[33]="S_STATE";
        columnNames[34]="C_TRIMFLAG";
        columnNames[35]="I_CHGNUM";
        columnNames[36]="S_INPUTERID";
        columnNames[37]="TS_SYSUPDATE";
        columnNames[38]="S_IFMATCH";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static String columnSbookorgcode(){
		 return S_BOOKORGCODE;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnStrecode(){
		 return S_TRECODE;
	}
	/**
	 * Getter S_PACKNO , NOT NULL   	 
	 */
	public static String columnSpackno(){
		 return S_PACKNO;
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static String columnSvouno(){
		 return S_VOUNO;
	}
	/**
	 * Getter S_BIZTYPE , NOT NULL   	 
	 */
	public static String columnSbiztype(){
		 return S_BIZTYPE;
	}
	/**
	 * Getter F_ZEROSUMAMT   	 
	 */
	public static String columnFzerosumamt(){
		 return F_ZEROSUMAMT;
	}
	/**
	 * Getter F_SMALLSUMAMT   	 
	 */
	public static String columnFsmallsumamt(){
		 return F_SMALLSUMAMT;
	}
	/**
	 * Getter S_SNDBNKNO   	 
	 */
	public static String columnSsndbnkno(){
		 return S_SNDBNKNO;
	}
	/**
	 * Getter S_PAYEROPNBNKNO , NOT NULL   	 
	 */
	public static String columnSpayeropnbnkno(){
		 return S_PAYEROPNBNKNO;
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static String columnSpayeracct(){
		 return S_PAYERACCT;
	}
	/**
	 * Getter S_PAYERNAME   	 
	 */
	public static String columnSpayername(){
		 return S_PAYERNAME;
	}
	/**
	 * Getter S_PAYERADDR   	 
	 */
	public static String columnSpayeraddr(){
		 return S_PAYERADDR;
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 */
	public static String columnSpayeeacct(){
		 return S_PAYEEACCT;
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 */
	public static String columnSpayeename(){
		 return S_PAYEENAME;
	}
	/**
	 * Getter S_PAYEEADDR   	 
	 */
	public static String columnSpayeeaddr(){
		 return S_PAYEEADDR;
	}
	/**
	 * Getter S_AGENTBNKCODE , NOT NULL   	 
	 */
	public static String columnSagentbnkcode(){
		 return S_AGENTBNKCODE;
	}
	/**
	 * Getter S_RCVBNKNO   	 
	 */
	public static String columnSrcvbnkno(){
		 return S_RCVBNKNO;
	}
	/**
	 * Getter S_PAYEEOPNBNKNO   	 
	 */
	public static String columnSpayeeopnbnkno(){
		 return S_PAYEEOPNBNKNO;
	}
	/**
	 * Getter S_SRLACCTBRIEFCODE   	 
	 */
	public static String columnSsrlacctbriefcode(){
		 return S_SRLACCTBRIEFCODE;
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static String columnSaddword(){
		 return S_ADDWORD;
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 */
	public static String columnSpaydictateno(){
		 return S_PAYDICTATENO;
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 */
	public static String columnSpaymsgno(){
		 return S_PAYMSGNO;
	}
	/**
	 * Getter D_PAYENTRUSTDATE   	 
	 */
	public static String columnDpayentrustdate(){
		 return D_PAYENTRUSTDATE;
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 */
	public static String columnSpaysndbnkno(){
		 return S_PAYSNDBNKNO;
	}
	/**
	 * Getter D_VOUCHER , NOT NULL   	 
	 */
	public static String columnDvoucher(){
		 return D_VOUCHER;
	}
	/**
	 * Getter C_BDGKIND , NOT NULL   	 
	 */
	public static String columnCbdgkind(){
		 return C_BDGKIND;
	}
	/**
	 * Getter I_OFYEAR   	 
	 */
	public static String columnIofyear(){
		 return I_OFYEAR;
	}
	/**
	 * Getter D_ACCEPT , NOT NULL   	 
	 */
	public static String columnDaccept(){
		 return D_ACCEPT;
	}
	/**
	 * Getter D_ACCT   	 
	 */
	public static String columnDacct(){
		 return D_ACCT;
	}
	/**
	 * Getter S_ORIVOUNO   	 
	 */
	public static String columnSorivouno(){
		 return S_ORIVOUNO;
	}
	/**
	 * Getter D_ORIVOUDATE   	 
	 */
	public static String columnDorivoudate(){
		 return D_ORIVOUDATE;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnSfilename(){
		 return S_FILENAME;
	}
	/**
	 * Getter S_STATE   	 
	 */
	public static String columnSstate(){
		 return S_STATE;
	}
	/**
	 * Getter C_TRIMFLAG   	 
	 */
	public static String columnCtrimflag(){
		 return C_TRIMFLAG;
	}
	/**
	 * Getter I_CHGNUM   	 
	 */
	public static String columnIchgnum(){
		 return I_CHGNUM;
	}
	/**
	 * Getter S_INPUTERID   	 
	 */
	public static String columnSinputerid(){
		 return S_INPUTERID;
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/**
	 * Getter S_IFMATCH   	 
	 */
	public static String columnSifmatch(){
		 return S_IFMATCH;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbookorgcode(){
		 return "String";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStrecode(){
		 return "String";
	}
	/**
	 * Getter S_PACKNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackno(){
		 return "String";
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSvouno(){
		 return "String";
	}
	/**
	 * Getter S_BIZTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbiztype(){
		 return "String";
	}
	/**
	 * Getter F_ZEROSUMAMT   	 
	 */
	public static String columnJavaTypeFzerosumamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter F_SMALLSUMAMT   	 
	 */
	public static String columnJavaTypeFsmallsumamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_SNDBNKNO   	 
	 */
	public static String columnJavaTypeSsndbnkno(){
		 return "String";
	}
	/**
	 * Getter S_PAYEROPNBNKNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeropnbnkno(){
		 return "String";
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeracct(){
		 return "String";
	}
	/**
	 * Getter S_PAYERNAME   	 
	 */
	public static String columnJavaTypeSpayername(){
		 return "String";
	}
	/**
	 * Getter S_PAYERADDR   	 
	 */
	public static String columnJavaTypeSpayeraddr(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeeacct(){
		 return "String";
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeename(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEADDR   	 
	 */
	public static String columnJavaTypeSpayeeaddr(){
		 return "String";
	}
	/**
	 * Getter S_AGENTBNKCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSagentbnkcode(){
		 return "String";
	}
	/**
	 * Getter S_RCVBNKNO   	 
	 */
	public static String columnJavaTypeSrcvbnkno(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEOPNBNKNO   	 
	 */
	public static String columnJavaTypeSpayeeopnbnkno(){
		 return "String";
	}
	/**
	 * Getter S_SRLACCTBRIEFCODE   	 
	 */
	public static String columnJavaTypeSsrlacctbriefcode(){
		 return "String";
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static String columnJavaTypeSaddword(){
		 return "String";
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 */
	public static String columnJavaTypeSpaydictateno(){
		 return "String";
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 */
	public static String columnJavaTypeSpaymsgno(){
		 return "String";
	}
	/**
	 * Getter D_PAYENTRUSTDATE   	 
	 */
	public static String columnJavaTypeDpayentrustdate(){
		 return "Date";
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 */
	public static String columnJavaTypeSpaysndbnkno(){
		 return "String";
	}
	/**
	 * Getter D_VOUCHER , NOT NULL   	 
	 */
	public static String columnJavaTypeDvoucher(){
		 return "Date";
	}
	/**
	 * Getter C_BDGKIND , NOT NULL   	 
	 */
	public static String columnJavaTypeCbdgkind(){
		 return "String";
	}
	/**
	 * Getter I_OFYEAR   	 
	 */
	public static String columnJavaTypeIofyear(){
		 return "Integer";
	}
	/**
	 * Getter D_ACCEPT , NOT NULL   	 
	 */
	public static String columnJavaTypeDaccept(){
		 return "Date";
	}
	/**
	 * Getter D_ACCT   	 
	 */
	public static String columnJavaTypeDacct(){
		 return "Date";
	}
	/**
	 * Getter S_ORIVOUNO   	 
	 */
	public static String columnJavaTypeSorivouno(){
		 return "String";
	}
	/**
	 * Getter D_ORIVOUDATE   	 
	 */
	public static String columnJavaTypeDorivoudate(){
		 return "Date";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSfilename(){
		 return "String";
	}
	/**
	 * Getter S_STATE   	 
	 */
	public static String columnJavaTypeSstate(){
		 return "String";
	}
	/**
	 * Getter C_TRIMFLAG   	 
	 */
	public static String columnJavaTypeCtrimflag(){
		 return "String";
	}
	/**
	 * Getter I_CHGNUM   	 
	 */
	public static String columnJavaTypeIchgnum(){
		 return "Integer";
	}
	/**
	 * Getter S_INPUTERID   	 
	 */
	public static String columnJavaTypeSinputerid(){
		 return "String";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/**
	 * Getter S_IFMATCH   	 
	 */
	public static String columnJavaTypeSifmatch(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbookorgcode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrecode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_PACKNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpackno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvouno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BIZTYPE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbiztype(){
		 return "VARCHAR";
	}
	/**
	 * Getter F_ZEROSUMAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFzerosumamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter F_SMALLSUMAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFsmallsumamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_SNDBNKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSsndbnkno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEROPNBNKNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeropnbnkno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeracct(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayername(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERADDR   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeraddr(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacct(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEADDR   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeaddr(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AGENTBNKCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagentbnkcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_RCVBNKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSrcvbnkno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEOPNBNKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeopnbnkno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_SRLACCTBRIEFCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSsrlacctbriefcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ADDWORD   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSaddword(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpaydictateno(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaymsgno(){
		 return "VARCHAR";
	}
	/**
	 * Getter D_PAYENTRUSTDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDpayentrustdate(){
		 return "DATE";
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpaysndbnkno(){
		 return "CHARACTER";
	}
	/**
	 * Getter D_VOUCHER , NOT NULL   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDvoucher(){
		 return "DATE";
	}
	/**
	 * Getter C_BDGKIND , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeCbdgkind(){
		 return "CHARACTER";
	}
	/**
	 * Getter I_OFYEAR   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeIofyear(){
		 return "INTEGER";
	}
	/**
	 * Getter D_ACCEPT , NOT NULL   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDaccept(){
		 return "DATE";
	}
	/**
	 * Getter D_ACCT   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDacct(){
		 return "DATE";
	}
	/**
	 * Getter S_ORIVOUNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorivouno(){
		 return "VARCHAR";
	}
	/**
	 * Getter D_ORIVOUDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDorivoudate(){
		 return "DATE";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_STATE   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSstate(){
		 return "CHARACTER";
	}
	/**
	 * Getter C_TRIMFLAG   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeCtrimflag(){
		 return "CHARACTER";
	}
	/**
	 * Getter I_CHGNUM   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeIchgnum(){
		 return "INTEGER";
	}
	/**
	 * Getter S_INPUTERID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSinputerid(){
		 return "VARCHAR";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/**
	 * Getter S_IFMATCH   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSifmatch(){
		 return "CHARACTER";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSbookorgcode(){
		 return 12;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static int columnWidthStrecode(){
		 return 10;
	}
	/**
	 * Getter S_PACKNO , NOT NULL   	 
	 */
	public static int columnWidthSpackno(){
		 return 8;
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static int columnWidthSvouno(){
		 return 22;
	}
	/**
	 * Getter S_BIZTYPE , NOT NULL   	 
	 */
	public static int columnWidthSbiztype(){
		 return 6;
	}
	/**
	 * Getter S_SNDBNKNO   	 
	 */
	public static int columnWidthSsndbnkno(){
		 return 12;
	}
	/**
	 * Getter S_PAYEROPNBNKNO , NOT NULL   	 
	 */
	public static int columnWidthSpayeropnbnkno(){
		 return 12;
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static int columnWidthSpayeracct(){
		 return 32;
	}
	/**
	 * Getter S_PAYERNAME   	 
	 */
	public static int columnWidthSpayername(){
		 return 60;
	}
	/**
	 * Getter S_PAYERADDR   	 
	 */
	public static int columnWidthSpayeraddr(){
		 return 60;
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 */
	public static int columnWidthSpayeeacct(){
		 return 32;
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 */
	public static int columnWidthSpayeename(){
		 return 60;
	}
	/**
	 * Getter S_PAYEEADDR   	 
	 */
	public static int columnWidthSpayeeaddr(){
		 return 100;
	}
	/**
	 * Getter S_AGENTBNKCODE , NOT NULL   	 
	 */
	public static int columnWidthSagentbnkcode(){
		 return 12;
	}
	/**
	 * Getter S_RCVBNKNO   	 
	 */
	public static int columnWidthSrcvbnkno(){
		 return 12;
	}
	/**
	 * Getter S_PAYEEOPNBNKNO   	 
	 */
	public static int columnWidthSpayeeopnbnkno(){
		 return 12;
	}
	/**
	 * Getter S_SRLACCTBRIEFCODE   	 
	 */
	public static int columnWidthSsrlacctbriefcode(){
		 return 9;
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static int columnWidthSaddword(){
		 return 60;
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 */
	public static int columnWidthSpaydictateno(){
		 return 8;
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 */
	public static int columnWidthSpaymsgno(){
		 return 10;
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 */
	public static int columnWidthSpaysndbnkno(){
		 return 12;
	}
	/**
	 * Getter C_BDGKIND , NOT NULL   	 
	 */
	public static int columnWidthCbdgkind(){
		 return 1;
	}
	/**
	 * Getter S_ORIVOUNO   	 
	 */
	public static int columnWidthSorivouno(){
		 return 22;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static int columnWidthSfilename(){
		 return 100;
	}
	/**
	 * Getter S_STATE   	 
	 */
	public static int columnWidthSstate(){
		 return 1;
	}
	/**
	 * Getter C_TRIMFLAG   	 
	 */
	public static int columnWidthCtrimflag(){
		 return 1;
	}
	/**
	 * Getter S_INPUTERID   	 
	 */
	public static int columnWidthSinputerid(){
		 return 18;
	}
	/**
	 * Getter S_IFMATCH   	 
	 */
	public static int columnWidthSifmatch(){
		 return 1;
	}
}