      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TF_RECONCILE_PAYQUOTA_SUB</p>
 * <p>Description: 清算额度对帐子表3510 Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:58 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TfReconcilePayquotaSubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TF_RECONCILE_PAYQUOTA_SUB";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column I_SEQNO
	 */
	public static String I_SEQNO ="I_SEQNO";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * column S_SUPDEPCODE
	 */
	public static String S_SUPDEPCODE ="S_SUPDEPCODE";
	/**
	 * column S_SUPDEPNAME
	 */
	public static String S_SUPDEPNAME ="S_SUPDEPNAME";
	/**
	 * column S_FUNDTYPECODE
	 */
	public static String S_FUNDTYPECODE ="S_FUNDTYPECODE";
	/**
	 * column S_FUNDTYPENAME
	 */
	public static String S_FUNDTYPENAME ="S_FUNDTYPENAME";
	/**
	 * column S_PAYBANKCODE
	 */
	public static String S_PAYBANKCODE ="S_PAYBANKCODE";
	/**
	 * column S_PAYBANKNAME
	 */
	public static String S_PAYBANKNAME ="S_PAYBANKNAME";
	/**
	 * column S_PAYBANKNO
	 */
	public static String S_PAYBANKNO ="S_PAYBANKNO";
	/**
	 * column S_EXPFUNCCODE
	 */
	public static String S_EXPFUNCCODE ="S_EXPFUNCCODE";
	/**
	 * column S_EXPFUNCNAME
	 */
	public static String S_EXPFUNCNAME ="S_EXPFUNCNAME";
	/**
	 * column S_PROCATCODE
	 */
	public static String S_PROCATCODE ="S_PROCATCODE";
	/**
	 * column S_PROCATNAME
	 */
	public static String S_PROCATNAME ="S_PROCATNAME";
	/**
	 * column S_PAYTYPECODE
	 */
	public static String S_PAYTYPECODE ="S_PAYTYPECODE";
	/**
	 * column S_PAYTYPENAME
	 */
	public static String S_PAYTYPENAME ="S_PAYTYPENAME";
	/**
	 * column N_PREDATEMONEY
	 */
	public static String N_PREDATEMONEY ="N_PREDATEMONEY";
	/**
	 * column N_CLEARAMT
	 */
	public static String N_CLEARAMT ="N_CLEARAMT";
	/**
	 * column N_CURRECKMONEY
	 */
	public static String N_CURRECKMONEY ="N_CURRECKMONEY";
	/**
	 * column N_CURDATEMONEY
	 */
	public static String N_CURDATEMONEY ="N_CURDATEMONEY";
	/**
	 * column S_XCHECKRESULT
	 */
	public static String S_XCHECKRESULT ="S_XCHECKRESULT";
	/**
	 * column S_XCHECKREASON
	 */
	public static String S_XCHECKREASON ="S_XCHECKREASON";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_HOLD3
	 */
	public static String S_HOLD3 ="S_HOLD3";
	/**
	 * column S_HOLD4
	 */
	public static String S_HOLD4 ="S_HOLD4";
	/**
	 * column S_EXT1
	 */
	public static String S_EXT1 ="S_EXT1";
	/**
	 * column S_EXT2
	 */
	public static String S_EXT2 ="S_EXT2";
	/**
	 * column S_EXT3
	 */
	public static String S_EXT3 ="S_EXT3";
	/**
	 * column S_EXT4
	 */
	public static String S_EXT4 ="S_EXT4";
	/**
	 * column S_EXT5
	 */
	public static String S_EXT5 ="S_EXT5";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[31];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="I_SEQNO";
        columnNames[2]="S_ID";
        columnNames[3]="S_SUPDEPCODE";
        columnNames[4]="S_SUPDEPNAME";
        columnNames[5]="S_FUNDTYPECODE";
        columnNames[6]="S_FUNDTYPENAME";
        columnNames[7]="S_PAYBANKCODE";
        columnNames[8]="S_PAYBANKNAME";
        columnNames[9]="S_PAYBANKNO";
        columnNames[10]="S_EXPFUNCCODE";
        columnNames[11]="S_EXPFUNCNAME";
        columnNames[12]="S_PROCATCODE";
        columnNames[13]="S_PROCATNAME";
        columnNames[14]="S_PAYTYPECODE";
        columnNames[15]="S_PAYTYPENAME";
        columnNames[16]="N_PREDATEMONEY";
        columnNames[17]="N_CLEARAMT";
        columnNames[18]="N_CURRECKMONEY";
        columnNames[19]="N_CURDATEMONEY";
        columnNames[20]="S_XCHECKRESULT";
        columnNames[21]="S_XCHECKREASON";
        columnNames[22]="S_HOLD1";
        columnNames[23]="S_HOLD2";
        columnNames[24]="S_HOLD3";
        columnNames[25]="S_HOLD4";
        columnNames[26]="S_EXT1";
        columnNames[27]="S_EXT2";
        columnNames[28]="S_EXT3";
        columnNames[29]="S_EXT4";
        columnNames[30]="S_EXT5";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 *外键联合主键 Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 *联合主键 Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnIseqno(){
		 return I_SEQNO;
	}
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/**
	 *一级预算单位编码 Getter S_SUPDEPCODE , NOT NULL   	 
	 */
	public static String columnSsupdepcode(){
		 return S_SUPDEPCODE;
	}
	/**
	 *一级预算单位名称 Getter S_SUPDEPNAME , NOT NULL   	 
	 */
	public static String columnSsupdepname(){
		 return S_SUPDEPNAME;
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 */
	public static String columnSfundtypecode(){
		 return S_FUNDTYPECODE;
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 */
	public static String columnSfundtypename(){
		 return S_FUNDTYPENAME;
	}
	/**
	 *代理银行编码 Getter S_PAYBANKCODE   	 
	 */
	public static String columnSpaybankcode(){
		 return S_PAYBANKCODE;
	}
	/**
	 *代理银行名称 Getter S_PAYBANKNAME   	 
	 */
	public static String columnSpaybankname(){
		 return S_PAYBANKNAME;
	}
	/**
	 *代理银行行号 Getter S_PAYBANKNO , NOT NULL   	 
	 */
	public static String columnSpaybankno(){
		 return S_PAYBANKNO;
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE , NOT NULL   	 
	 */
	public static String columnSexpfunccode(){
		 return S_EXPFUNCCODE;
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME , NOT NULL   	 
	 */
	public static String columnSexpfuncname(){
		 return S_EXPFUNCNAME;
	}
	/**
	 *收支管理编码 Getter S_PROCATCODE   	 
	 */
	public static String columnSprocatcode(){
		 return S_PROCATCODE;
	}
	/**
	 *收支管理名称 Getter S_PROCATNAME   	 
	 */
	public static String columnSprocatname(){
		 return S_PROCATNAME;
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE , NOT NULL   	 
	 */
	public static String columnSpaytypecode(){
		 return S_PAYTYPECODE;
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME , NOT NULL   	 
	 */
	public static String columnSpaytypename(){
		 return S_PAYTYPENAME;
	}
	/**
	 *上期额度余额 Getter N_PREDATEMONEY   	 
	 */
	public static String columnNpredatemoney(){
		 return N_PREDATEMONEY;
	}
	/**
	 *本期新增清算额度 Getter N_CLEARAMT , NOT NULL   	 
	 */
	public static String columnNclearamt(){
		 return N_CLEARAMT;
	}
	/**
	 *本期已清算额度 Getter N_CURRECKMONEY   	 
	 */
	public static String columnNcurreckmoney(){
		 return N_CURRECKMONEY;
	}
	/**
	 *本期额度余额 Getter N_CURDATEMONEY   	 
	 */
	public static String columnNcurdatemoney(){
		 return N_CURDATEMONEY;
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 */
	public static String columnSxcheckresult(){
		 return S_XCHECKRESULT;
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 */
	public static String columnSxcheckreason(){
		 return S_XCHECKREASON;
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 */
	public static String columnShold3(){
		 return S_HOLD3;
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 */
	public static String columnShold4(){
		 return S_HOLD4;
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 */
	public static String columnSext1(){
		 return S_EXT1;
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 */
	public static String columnSext2(){
		 return S_EXT2;
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 */
	public static String columnSext3(){
		 return S_EXT3;
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 */
	public static String columnSext4(){
		 return S_EXT4;
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 */
	public static String columnSext5(){
		 return S_EXT5;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 *外键联合主键 Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 *联合主键 Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIseqno(){
		 return "Long";
	}
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/**
	 *一级预算单位编码 Getter S_SUPDEPCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSsupdepcode(){
		 return "String";
	}
	/**
	 *一级预算单位名称 Getter S_SUPDEPNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSsupdepname(){
		 return "String";
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 */
	public static String columnJavaTypeSfundtypecode(){
		 return "String";
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 */
	public static String columnJavaTypeSfundtypename(){
		 return "String";
	}
	/**
	 *代理银行编码 Getter S_PAYBANKCODE   	 
	 */
	public static String columnJavaTypeSpaybankcode(){
		 return "String";
	}
	/**
	 *代理银行名称 Getter S_PAYBANKNAME   	 
	 */
	public static String columnJavaTypeSpaybankname(){
		 return "String";
	}
	/**
	 *代理银行行号 Getter S_PAYBANKNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpaybankno(){
		 return "String";
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSexpfunccode(){
		 return "String";
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSexpfuncname(){
		 return "String";
	}
	/**
	 *收支管理编码 Getter S_PROCATCODE   	 
	 */
	public static String columnJavaTypeSprocatcode(){
		 return "String";
	}
	/**
	 *收支管理名称 Getter S_PROCATNAME   	 
	 */
	public static String columnJavaTypeSprocatname(){
		 return "String";
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSpaytypecode(){
		 return "String";
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSpaytypename(){
		 return "String";
	}
	/**
	 *上期额度余额 Getter N_PREDATEMONEY   	 
	 */
	public static String columnJavaTypeNpredatemoney(){
		 return "BigDecimal";
	}
	/**
	 *本期新增清算额度 Getter N_CLEARAMT , NOT NULL   	 
	 */
	public static String columnJavaTypeNclearamt(){
		 return "BigDecimal";
	}
	/**
	 *本期已清算额度 Getter N_CURRECKMONEY   	 
	 */
	public static String columnJavaTypeNcurreckmoney(){
		 return "BigDecimal";
	}
	/**
	 *本期额度余额 Getter N_CURDATEMONEY   	 
	 */
	public static String columnJavaTypeNcurdatemoney(){
		 return "BigDecimal";
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 */
	public static String columnJavaTypeSxcheckresult(){
		 return "String";
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 */
	public static String columnJavaTypeSxcheckreason(){
		 return "String";
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 */
	public static String columnJavaTypeShold3(){
		 return "String";
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 */
	public static String columnJavaTypeShold4(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 */
	public static String columnJavaTypeSext1(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 */
	public static String columnJavaTypeSext2(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 */
	public static String columnJavaTypeSext3(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 */
	public static String columnJavaTypeSext4(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 */
	public static String columnJavaTypeSext5(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 *外键联合主键 Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 *联合主键 Getter I_SEQNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIseqno(){
		 return "BIGINT";
	}
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/**
	 *一级预算单位编码 Getter S_SUPDEPCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSsupdepcode(){
		 return "VARCHAR";
	}
	/**
	 *一级预算单位名称 Getter S_SUPDEPNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSsupdepname(){
		 return "VARCHAR";
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypecode(){
		 return "VARCHAR";
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypename(){
		 return "VARCHAR";
	}
	/**
	 *代理银行编码 Getter S_PAYBANKCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankcode(){
		 return "VARCHAR";
	}
	/**
	 *代理银行名称 Getter S_PAYBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankname(){
		 return "VARCHAR";
	}
	/**
	 *代理银行行号 Getter S_PAYBANKNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankno(){
		 return "VARCHAR";
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfunccode(){
		 return "VARCHAR";
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfuncname(){
		 return "VARCHAR";
	}
	/**
	 *收支管理编码 Getter S_PROCATCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSprocatcode(){
		 return "VARCHAR";
	}
	/**
	 *收支管理名称 Getter S_PROCATNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSprocatname(){
		 return "VARCHAR";
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaytypecode(){
		 return "VARCHAR";
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaytypename(){
		 return "VARCHAR";
	}
	/**
	 *上期额度余额 Getter N_PREDATEMONEY   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNpredatemoney(){
		 return "DECIMAL";
	}
	/**
	 *本期新增清算额度 Getter N_CLEARAMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNclearamt(){
		 return "DECIMAL";
	}
	/**
	 *本期已清算额度 Getter N_CURRECKMONEY   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNcurreckmoney(){
		 return "DECIMAL";
	}
	/**
	 *本期额度余额 Getter N_CURDATEMONEY   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNcurdatemoney(){
		 return "DECIMAL";
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxcheckresult(){
		 return "VARCHAR";
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxcheckreason(){
		 return "VARCHAR";
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold3(){
		 return "VARCHAR";
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold4(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext1(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext2(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext3(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext4(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext5(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
	/**
	 *一级预算单位编码 Getter S_SUPDEPCODE , NOT NULL   	 
	 */
	public static int columnWidthSsupdepcode(){
		 return 15;
	}
	/**
	 *一级预算单位名称 Getter S_SUPDEPNAME , NOT NULL   	 
	 */
	public static int columnWidthSsupdepname(){
		 return 60;
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 */
	public static int columnWidthSfundtypecode(){
		 return 42;
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 */
	public static int columnWidthSfundtypename(){
		 return 60;
	}
	/**
	 *代理银行编码 Getter S_PAYBANKCODE   	 
	 */
	public static int columnWidthSpaybankcode(){
		 return 42;
	}
	/**
	 *代理银行名称 Getter S_PAYBANKNAME   	 
	 */
	public static int columnWidthSpaybankname(){
		 return 60;
	}
	/**
	 *代理银行行号 Getter S_PAYBANKNO , NOT NULL   	 
	 */
	public static int columnWidthSpaybankno(){
		 return 12;
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE , NOT NULL   	 
	 */
	public static int columnWidthSexpfunccode(){
		 return 42;
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME , NOT NULL   	 
	 */
	public static int columnWidthSexpfuncname(){
		 return 60;
	}
	/**
	 *收支管理编码 Getter S_PROCATCODE   	 
	 */
	public static int columnWidthSprocatcode(){
		 return 42;
	}
	/**
	 *收支管理名称 Getter S_PROCATNAME   	 
	 */
	public static int columnWidthSprocatname(){
		 return 60;
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE , NOT NULL   	 
	 */
	public static int columnWidthSpaytypecode(){
		 return 42;
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME , NOT NULL   	 
	 */
	public static int columnWidthSpaytypename(){
		 return 60;
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 */
	public static int columnWidthSxcheckresult(){
		 return 5;
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 */
	public static int columnWidthSxcheckreason(){
		 return 200;
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 */
	public static int columnWidthShold3(){
		 return 42;
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 */
	public static int columnWidthShold4(){
		 return 42;
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 */
	public static int columnWidthSext1(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 */
	public static int columnWidthSext2(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 */
	public static int columnWidthSext3(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 */
	public static int columnWidthSext4(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 */
	public static int columnWidthSext5(){
		 return 50;
	}
}