      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TF_RECONCILE_REALDIAL_SUB</p>
 * <p>Description: 实拨信息对帐子表3508 Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:58 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TfReconcileRealdialSubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TF_RECONCILE_REALDIAL_SUB";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column I_SEQNO
	 */
	public static String I_SEQNO ="I_SEQNO";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * column S_PAYDETAILID
	 */
	public static String S_PAYDETAILID ="S_PAYDETAILID";
	/**
	 * column S_BGTTYPECODE
	 */
	public static String S_BGTTYPECODE ="S_BGTTYPECODE";
	/**
	 * column S_BGTTYPENAME
	 */
	public static String S_BGTTYPENAME ="S_BGTTYPENAME";
	/**
	 * column S_FUNDTYPECODE
	 */
	public static String S_FUNDTYPECODE ="S_FUNDTYPECODE";
	/**
	 * column S_FUNDTYPENAME
	 */
	public static String S_FUNDTYPENAME ="S_FUNDTYPENAME";
	/**
	 * column S_PAYTYPECODE
	 */
	public static String S_PAYTYPECODE ="S_PAYTYPECODE";
	/**
	 * column S_PAYTYPENAME
	 */
	public static String S_PAYTYPENAME ="S_PAYTYPENAME";
	/**
	 * column S_PAYEEACCTNO
	 */
	public static String S_PAYEEACCTNO ="S_PAYEEACCTNO";
	/**
	 * column S_PAYEEACCTNAME
	 */
	public static String S_PAYEEACCTNAME ="S_PAYEEACCTNAME";
	/**
	 * column S_PAYEEACCTBANKNAME
	 */
	public static String S_PAYEEACCTBANKNAME ="S_PAYEEACCTBANKNAME";
	/**
	 * column S_PAYACCTNO
	 */
	public static String S_PAYACCTNO ="S_PAYACCTNO";
	/**
	 * column S_PAYACCTNAME
	 */
	public static String S_PAYACCTNAME ="S_PAYACCTNAME";
	/**
	 * column S_PAYACCTBANKNAME
	 */
	public static String S_PAYACCTBANKNAME ="S_PAYACCTBANKNAME";
	/**
	 * column S_AGENCYCODE
	 */
	public static String S_AGENCYCODE ="S_AGENCYCODE";
	/**
	 * column S_AGENCYNAME
	 */
	public static String S_AGENCYNAME ="S_AGENCYNAME";
	/**
	 * column S_EXPFUNCCODE
	 */
	public static String S_EXPFUNCCODE ="S_EXPFUNCCODE";
	/**
	 * column S_EXPFUNCNAME
	 */
	public static String S_EXPFUNCNAME ="S_EXPFUNCNAME";
	/**
	 * column S_EXPECOCODE
	 */
	public static String S_EXPECOCODE ="S_EXPECOCODE";
	/**
	 * column S_EXPECONAME
	 */
	public static String S_EXPECONAME ="S_EXPECONAME";
	/**
	 * column N_PAYAMT
	 */
	public static String N_PAYAMT ="N_PAYAMT";
	/**
	 * column S_XCHECKRESULT
	 */
	public static String S_XCHECKRESULT ="S_XCHECKRESULT";
	/**
	 * column S_XCHECKREASON
	 */
	public static String S_XCHECKREASON ="S_XCHECKREASON";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_HOLD3
	 */
	public static String S_HOLD3 ="S_HOLD3";
	/**
	 * column S_HOLD4
	 */
	public static String S_HOLD4 ="S_HOLD4";
	/**
	 * column S_EXT1
	 */
	public static String S_EXT1 ="S_EXT1";
	/**
	 * column S_EXT2
	 */
	public static String S_EXT2 ="S_EXT2";
	/**
	 * column S_EXT3
	 */
	public static String S_EXT3 ="S_EXT3";
	/**
	 * column S_EXT4
	 */
	public static String S_EXT4 ="S_EXT4";
	/**
	 * column S_EXT5
	 */
	public static String S_EXT5 ="S_EXT5";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[34];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="I_SEQNO";
        columnNames[2]="S_ID";
        columnNames[3]="S_PAYDETAILID";
        columnNames[4]="S_BGTTYPECODE";
        columnNames[5]="S_BGTTYPENAME";
        columnNames[6]="S_FUNDTYPECODE";
        columnNames[7]="S_FUNDTYPENAME";
        columnNames[8]="S_PAYTYPECODE";
        columnNames[9]="S_PAYTYPENAME";
        columnNames[10]="S_PAYEEACCTNO";
        columnNames[11]="S_PAYEEACCTNAME";
        columnNames[12]="S_PAYEEACCTBANKNAME";
        columnNames[13]="S_PAYACCTNO";
        columnNames[14]="S_PAYACCTNAME";
        columnNames[15]="S_PAYACCTBANKNAME";
        columnNames[16]="S_AGENCYCODE";
        columnNames[17]="S_AGENCYNAME";
        columnNames[18]="S_EXPFUNCCODE";
        columnNames[19]="S_EXPFUNCNAME";
        columnNames[20]="S_EXPECOCODE";
        columnNames[21]="S_EXPECONAME";
        columnNames[22]="N_PAYAMT";
        columnNames[23]="S_XCHECKRESULT";
        columnNames[24]="S_XCHECKREASON";
        columnNames[25]="S_HOLD1";
        columnNames[26]="S_HOLD2";
        columnNames[27]="S_HOLD3";
        columnNames[28]="S_HOLD4";
        columnNames[29]="S_EXT1";
        columnNames[30]="S_EXT2";
        columnNames[31]="S_EXT3";
        columnNames[32]="S_EXT4";
        columnNames[33]="S_EXT5";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 *外键联合主键 Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 *联合主键 Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnIseqno(){
		 return I_SEQNO;
	}
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/**
	 *拨款明细ID Getter S_PAYDETAILID   	 
	 */
	public static String columnSpaydetailid(){
		 return S_PAYDETAILID;
	}
	/**
	 *预算类型编码 Getter S_BGTTYPECODE   	 
	 */
	public static String columnSbgttypecode(){
		 return S_BGTTYPECODE;
	}
	/**
	 *预算类型名称 Getter S_BGTTYPENAME   	 
	 */
	public static String columnSbgttypename(){
		 return S_BGTTYPENAME;
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 */
	public static String columnSfundtypecode(){
		 return S_FUNDTYPECODE;
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 */
	public static String columnSfundtypename(){
		 return S_FUNDTYPENAME;
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE   	 
	 */
	public static String columnSpaytypecode(){
		 return S_PAYTYPECODE;
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME   	 
	 */
	public static String columnSpaytypename(){
		 return S_PAYTYPENAME;
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 */
	public static String columnSpayeeacctno(){
		 return S_PAYEEACCTNO;
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnSpayeeacctname(){
		 return S_PAYEEACCTNAME;
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnSpayeeacctbankname(){
		 return S_PAYEEACCTBANKNAME;
	}
	/**
	 *付款账户账号 Getter S_PAYACCTNO   	 
	 */
	public static String columnSpayacctno(){
		 return S_PAYACCTNO;
	}
	/**
	 *付款账户名称 Getter S_PAYACCTNAME   	 
	 */
	public static String columnSpayacctname(){
		 return S_PAYACCTNAME;
	}
	/**
	 *付款账户银行 Getter S_PAYACCTBANKNAME   	 
	 */
	public static String columnSpayacctbankname(){
		 return S_PAYACCTBANKNAME;
	}
	/**
	 *预算单位编码 Getter S_AGENCYCODE   	 
	 */
	public static String columnSagencycode(){
		 return S_AGENCYCODE;
	}
	/**
	 *预算单位名称 Getter S_AGENCYNAME   	 
	 */
	public static String columnSagencyname(){
		 return S_AGENCYNAME;
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE   	 
	 */
	public static String columnSexpfunccode(){
		 return S_EXPFUNCCODE;
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME   	 
	 */
	public static String columnSexpfuncname(){
		 return S_EXPFUNCNAME;
	}
	/**
	 *经济分类科目编码 Getter S_EXPECOCODE   	 
	 */
	public static String columnSexpecocode(){
		 return S_EXPECOCODE;
	}
	/**
	 *经济分类科目名称 Getter S_EXPECONAME   	 
	 */
	public static String columnSexpeconame(){
		 return S_EXPECONAME;
	}
	/**
	 *拨款金额 Getter N_PAYAMT , NOT NULL   	 
	 */
	public static String columnNpayamt(){
		 return N_PAYAMT;
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 */
	public static String columnSxcheckresult(){
		 return S_XCHECKRESULT;
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 */
	public static String columnSxcheckreason(){
		 return S_XCHECKREASON;
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 */
	public static String columnShold3(){
		 return S_HOLD3;
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 */
	public static String columnShold4(){
		 return S_HOLD4;
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 */
	public static String columnSext1(){
		 return S_EXT1;
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 */
	public static String columnSext2(){
		 return S_EXT2;
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 */
	public static String columnSext3(){
		 return S_EXT3;
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 */
	public static String columnSext4(){
		 return S_EXT4;
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 */
	public static String columnSext5(){
		 return S_EXT5;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 *外键联合主键 Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 *联合主键 Getter I_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIseqno(){
		 return "Long";
	}
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/**
	 *拨款明细ID Getter S_PAYDETAILID   	 
	 */
	public static String columnJavaTypeSpaydetailid(){
		 return "String";
	}
	/**
	 *预算类型编码 Getter S_BGTTYPECODE   	 
	 */
	public static String columnJavaTypeSbgttypecode(){
		 return "String";
	}
	/**
	 *预算类型名称 Getter S_BGTTYPENAME   	 
	 */
	public static String columnJavaTypeSbgttypename(){
		 return "String";
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 */
	public static String columnJavaTypeSfundtypecode(){
		 return "String";
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 */
	public static String columnJavaTypeSfundtypename(){
		 return "String";
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE   	 
	 */
	public static String columnJavaTypeSpaytypecode(){
		 return "String";
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME   	 
	 */
	public static String columnJavaTypeSpaytypename(){
		 return "String";
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 */
	public static String columnJavaTypeSpayeeacctno(){
		 return "String";
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctname(){
		 return "String";
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctbankname(){
		 return "String";
	}
	/**
	 *付款账户账号 Getter S_PAYACCTNO   	 
	 */
	public static String columnJavaTypeSpayacctno(){
		 return "String";
	}
	/**
	 *付款账户名称 Getter S_PAYACCTNAME   	 
	 */
	public static String columnJavaTypeSpayacctname(){
		 return "String";
	}
	/**
	 *付款账户银行 Getter S_PAYACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSpayacctbankname(){
		 return "String";
	}
	/**
	 *预算单位编码 Getter S_AGENCYCODE   	 
	 */
	public static String columnJavaTypeSagencycode(){
		 return "String";
	}
	/**
	 *预算单位名称 Getter S_AGENCYNAME   	 
	 */
	public static String columnJavaTypeSagencyname(){
		 return "String";
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE   	 
	 */
	public static String columnJavaTypeSexpfunccode(){
		 return "String";
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME   	 
	 */
	public static String columnJavaTypeSexpfuncname(){
		 return "String";
	}
	/**
	 *经济分类科目编码 Getter S_EXPECOCODE   	 
	 */
	public static String columnJavaTypeSexpecocode(){
		 return "String";
	}
	/**
	 *经济分类科目名称 Getter S_EXPECONAME   	 
	 */
	public static String columnJavaTypeSexpeconame(){
		 return "String";
	}
	/**
	 *拨款金额 Getter N_PAYAMT , NOT NULL   	 
	 */
	public static String columnJavaTypeNpayamt(){
		 return "BigDecimal";
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 */
	public static String columnJavaTypeSxcheckresult(){
		 return "String";
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 */
	public static String columnJavaTypeSxcheckreason(){
		 return "String";
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 */
	public static String columnJavaTypeShold3(){
		 return "String";
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 */
	public static String columnJavaTypeShold4(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 */
	public static String columnJavaTypeSext1(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 */
	public static String columnJavaTypeSext2(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 */
	public static String columnJavaTypeSext3(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 */
	public static String columnJavaTypeSext4(){
		 return "String";
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 */
	public static String columnJavaTypeSext5(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 *外键联合主键 Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 *联合主键 Getter I_SEQNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIseqno(){
		 return "BIGINT";
	}
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/**
	 *拨款明细ID Getter S_PAYDETAILID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaydetailid(){
		 return "VARCHAR";
	}
	/**
	 *预算类型编码 Getter S_BGTTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypecode(){
		 return "VARCHAR";
	}
	/**
	 *预算类型名称 Getter S_BGTTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypename(){
		 return "VARCHAR";
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypecode(){
		 return "VARCHAR";
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypename(){
		 return "VARCHAR";
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaytypecode(){
		 return "VARCHAR";
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaytypename(){
		 return "VARCHAR";
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctno(){
		 return "VARCHAR";
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctname(){
		 return "VARCHAR";
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctbankname(){
		 return "VARCHAR";
	}
	/**
	 *付款账户账号 Getter S_PAYACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctno(){
		 return "VARCHAR";
	}
	/**
	 *付款账户名称 Getter S_PAYACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctname(){
		 return "VARCHAR";
	}
	/**
	 *付款账户银行 Getter S_PAYACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctbankname(){
		 return "VARCHAR";
	}
	/**
	 *预算单位编码 Getter S_AGENCYCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencycode(){
		 return "VARCHAR";
	}
	/**
	 *预算单位名称 Getter S_AGENCYNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagencyname(){
		 return "VARCHAR";
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfunccode(){
		 return "VARCHAR";
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpfuncname(){
		 return "VARCHAR";
	}
	/**
	 *经济分类科目编码 Getter S_EXPECOCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpecocode(){
		 return "VARCHAR";
	}
	/**
	 *经济分类科目名称 Getter S_EXPECONAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSexpeconame(){
		 return "VARCHAR";
	}
	/**
	 *拨款金额 Getter N_PAYAMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNpayamt(){
		 return "DECIMAL";
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxcheckresult(){
		 return "VARCHAR";
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxcheckreason(){
		 return "VARCHAR";
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold3(){
		 return "VARCHAR";
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold4(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext1(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext2(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext3(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext4(){
		 return "VARCHAR";
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSext5(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 *序号 Getter S_ID , NOT NULL   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
	/**
	 *拨款明细ID Getter S_PAYDETAILID   	 
	 */
	public static int columnWidthSpaydetailid(){
		 return 38;
	}
	/**
	 *预算类型编码 Getter S_BGTTYPECODE   	 
	 */
	public static int columnWidthSbgttypecode(){
		 return 42;
	}
	/**
	 *预算类型名称 Getter S_BGTTYPENAME   	 
	 */
	public static int columnWidthSbgttypename(){
		 return 60;
	}
	/**
	 *资金性质编码 Getter S_FUNDTYPECODE   	 
	 */
	public static int columnWidthSfundtypecode(){
		 return 42;
	}
	/**
	 *资金性质名称 Getter S_FUNDTYPENAME   	 
	 */
	public static int columnWidthSfundtypename(){
		 return 60;
	}
	/**
	 *支付方式编码 Getter S_PAYTYPECODE   	 
	 */
	public static int columnWidthSpaytypecode(){
		 return 42;
	}
	/**
	 *支付方式名称 Getter S_PAYTYPENAME   	 
	 */
	public static int columnWidthSpaytypename(){
		 return 60;
	}
	/**
	 *收款人账号 Getter S_PAYEEACCTNO   	 
	 */
	public static int columnWidthSpayeeacctno(){
		 return 42;
	}
	/**
	 *收款人名称 Getter S_PAYEEACCTNAME   	 
	 */
	public static int columnWidthSpayeeacctname(){
		 return 120;
	}
	/**
	 *收款人银行 Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static int columnWidthSpayeeacctbankname(){
		 return 60;
	}
	/**
	 *付款账户账号 Getter S_PAYACCTNO   	 
	 */
	public static int columnWidthSpayacctno(){
		 return 60;
	}
	/**
	 *付款账户名称 Getter S_PAYACCTNAME   	 
	 */
	public static int columnWidthSpayacctname(){
		 return 120;
	}
	/**
	 *付款账户银行 Getter S_PAYACCTBANKNAME   	 
	 */
	public static int columnWidthSpayacctbankname(){
		 return 60;
	}
	/**
	 *预算单位编码 Getter S_AGENCYCODE   	 
	 */
	public static int columnWidthSagencycode(){
		 return 42;
	}
	/**
	 *预算单位名称 Getter S_AGENCYNAME   	 
	 */
	public static int columnWidthSagencyname(){
		 return 60;
	}
	/**
	 *支出功能分类科目编码 Getter S_EXPFUNCCODE   	 
	 */
	public static int columnWidthSexpfunccode(){
		 return 42;
	}
	/**
	 *支出功能分类科目名称 Getter S_EXPFUNCNAME   	 
	 */
	public static int columnWidthSexpfuncname(){
		 return 60;
	}
	/**
	 *经济分类科目编码 Getter S_EXPECOCODE   	 
	 */
	public static int columnWidthSexpecocode(){
		 return 42;
	}
	/**
	 *经济分类科目名称 Getter S_EXPECONAME   	 
	 */
	public static int columnWidthSexpeconame(){
		 return 60;
	}
	/**
	 *对帐结果 Getter S_XCHECKRESULT   	 
	 */
	public static int columnWidthSxcheckresult(){
		 return 5;
	}
	/**
	 *不符原因 Getter S_XCHECKREASON   	 
	 */
	public static int columnWidthSxcheckreason(){
		 return 200;
	}
	/**
	 *预留字段1 Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 *预留字段2 Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 *预留字段3 Getter S_HOLD3   	 
	 */
	public static int columnWidthShold3(){
		 return 42;
	}
	/**
	 *预留字段4 Getter S_HOLD4   	 
	 */
	public static int columnWidthShold4(){
		 return 42;
	}
	/**
	 *扩展 Getter S_EXT1   	 
	 */
	public static int columnWidthSext1(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT2   	 
	 */
	public static int columnWidthSext2(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT3   	 
	 */
	public static int columnWidthSext3(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT4   	 
	 */
	public static int columnWidthSext4(){
		 return 50;
	}
	/**
	 *扩展 Getter S_EXT5   	 
	 */
	public static int columnWidthSext5(){
		 return 50;
	}
}