      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TN_CONPAYCHECKBILL</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:59 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TnConpaycheckbillInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TN_CONPAYCHECKBILL";
	
	/**
	 * column I_ENROLSRLNO
	 */
	public static String I_ENROLSRLNO ="I_ENROLSRLNO";
	/**
	 * column D_ENDDATE
	 */
	public static String D_ENDDATE ="D_ENDDATE";
	/**
	 * column D_STARTDATE
	 */
	public static String D_STARTDATE ="D_STARTDATE";
	/**
	 * column S_BOOKORGCODE
	 */
	public static String S_BOOKORGCODE ="S_BOOKORGCODE";
	/**
	 * column S_TRECODE
	 */
	public static String S_TRECODE ="S_TRECODE";
	/**
	 * column S_BDGORGCODE
	 */
	public static String S_BDGORGCODE ="S_BDGORGCODE";
	/**
	 * column S_BDGORGNAME
	 */
	public static String S_BDGORGNAME ="S_BDGORGNAME";
	/**
	 * column S_BNKNO
	 */
	public static String S_BNKNO ="S_BNKNO";
	/**
	 * column S_FUNCSBTCODE
	 */
	public static String S_FUNCSBTCODE ="S_FUNCSBTCODE";
	/**
	 * column S_ECOSBTCODE
	 */
	public static String S_ECOSBTCODE ="S_ECOSBTCODE";
	/**
	 * column C_AMTKIND
	 */
	public static String C_AMTKIND ="C_AMTKIND";
	/**
	 * column F_LASTMONTHZEROAMT
	 */
	public static String F_LASTMONTHZEROAMT ="F_LASTMONTHZEROAMT";
	/**
	 * column F_CURZEROAMT
	 */
	public static String F_CURZEROAMT ="F_CURZEROAMT";
	/**
	 * column F_CURRECKZEROAMT
	 */
	public static String F_CURRECKZEROAMT ="F_CURRECKZEROAMT";
	/**
	 * column F_LASTMONTHSMALLAMT
	 */
	public static String F_LASTMONTHSMALLAMT ="F_LASTMONTHSMALLAMT";
	/**
	 * column F_CURSMALLAMT
	 */
	public static String F_CURSMALLAMT ="F_CURSMALLAMT";
	/**
	 * column F_CURRECKSMALLAMT
	 */
	public static String F_CURRECKSMALLAMT ="F_CURRECKSMALLAMT";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[18];        
        columnNames[0]="I_ENROLSRLNO";
        columnNames[1]="D_ENDDATE";
        columnNames[2]="D_STARTDATE";
        columnNames[3]="S_BOOKORGCODE";
        columnNames[4]="S_TRECODE";
        columnNames[5]="S_BDGORGCODE";
        columnNames[6]="S_BDGORGNAME";
        columnNames[7]="S_BNKNO";
        columnNames[8]="S_FUNCSBTCODE";
        columnNames[9]="S_ECOSBTCODE";
        columnNames[10]="C_AMTKIND";
        columnNames[11]="F_LASTMONTHZEROAMT";
        columnNames[12]="F_CURZEROAMT";
        columnNames[13]="F_CURRECKZEROAMT";
        columnNames[14]="F_LASTMONTHSMALLAMT";
        columnNames[15]="F_CURSMALLAMT";
        columnNames[16]="F_CURRECKSMALLAMT";
        columnNames[17]="TS_SYSUPDATE";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_ENROLSRLNO, PK , NOT NULL  , Identity  , Generated 	 
	 */
	public static String columnIenrolsrlno(){
		 return I_ENROLSRLNO;
	}
	/**
	 * Getter D_ENDDATE , NOT NULL   	 
	 */
	public static String columnDenddate(){
		 return D_ENDDATE;
	}
	/**
	 * Getter D_STARTDATE , NOT NULL   	 
	 */
	public static String columnDstartdate(){
		 return D_STARTDATE;
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static String columnSbookorgcode(){
		 return S_BOOKORGCODE;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnStrecode(){
		 return S_TRECODE;
	}
	/**
	 * Getter S_BDGORGCODE   	 
	 */
	public static String columnSbdgorgcode(){
		 return S_BDGORGCODE;
	}
	/**
	 * Getter S_BDGORGNAME , NOT NULL   	 
	 */
	public static String columnSbdgorgname(){
		 return S_BDGORGNAME;
	}
	/**
	 * Getter S_BNKNO   	 
	 */
	public static String columnSbnkno(){
		 return S_BNKNO;
	}
	/**
	 * Getter S_FUNCSBTCODE   	 
	 */
	public static String columnSfuncsbtcode(){
		 return S_FUNCSBTCODE;
	}
	/**
	 * Getter S_ECOSBTCODE   	 
	 */
	public static String columnSecosbtcode(){
		 return S_ECOSBTCODE;
	}
	/**
	 * Getter C_AMTKIND   	 
	 */
	public static String columnCamtkind(){
		 return C_AMTKIND;
	}
	/**
	 * Getter F_LASTMONTHZEROAMT   	 
	 */
	public static String columnFlastmonthzeroamt(){
		 return F_LASTMONTHZEROAMT;
	}
	/**
	 * Getter F_CURZEROAMT   	 
	 */
	public static String columnFcurzeroamt(){
		 return F_CURZEROAMT;
	}
	/**
	 * Getter F_CURRECKZEROAMT   	 
	 */
	public static String columnFcurreckzeroamt(){
		 return F_CURRECKZEROAMT;
	}
	/**
	 * Getter F_LASTMONTHSMALLAMT   	 
	 */
	public static String columnFlastmonthsmallamt(){
		 return F_LASTMONTHSMALLAMT;
	}
	/**
	 * Getter F_CURSMALLAMT   	 
	 */
	public static String columnFcursmallamt(){
		 return F_CURSMALLAMT;
	}
	/**
	 * Getter F_CURRECKSMALLAMT   	 
	 */
	public static String columnFcurrecksmallamt(){
		 return F_CURRECKSMALLAMT;
	}
	/**
	 * Getter TS_SYSUPDATE   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_ENROLSRLNO, PK , NOT NULL  , Identity  , Generated 	 
	 */
	public static String columnJavaTypeIenrolsrlno(){
		 return "Long";
	}
	/**
	 * Getter D_ENDDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeDenddate(){
		 return "Date";
	}
	/**
	 * Getter D_STARTDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeDstartdate(){
		 return "Date";
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbookorgcode(){
		 return "String";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStrecode(){
		 return "String";
	}
	/**
	 * Getter S_BDGORGCODE   	 
	 */
	public static String columnJavaTypeSbdgorgcode(){
		 return "String";
	}
	/**
	 * Getter S_BDGORGNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSbdgorgname(){
		 return "String";
	}
	/**
	 * Getter S_BNKNO   	 
	 */
	public static String columnJavaTypeSbnkno(){
		 return "String";
	}
	/**
	 * Getter S_FUNCSBTCODE   	 
	 */
	public static String columnJavaTypeSfuncsbtcode(){
		 return "String";
	}
	/**
	 * Getter S_ECOSBTCODE   	 
	 */
	public static String columnJavaTypeSecosbtcode(){
		 return "String";
	}
	/**
	 * Getter C_AMTKIND   	 
	 */
	public static String columnJavaTypeCamtkind(){
		 return "String";
	}
	/**
	 * Getter F_LASTMONTHZEROAMT   	 
	 */
	public static String columnJavaTypeFlastmonthzeroamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter F_CURZEROAMT   	 
	 */
	public static String columnJavaTypeFcurzeroamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter F_CURRECKZEROAMT   	 
	 */
	public static String columnJavaTypeFcurreckzeroamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter F_LASTMONTHSMALLAMT   	 
	 */
	public static String columnJavaTypeFlastmonthsmallamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter F_CURSMALLAMT   	 
	 */
	public static String columnJavaTypeFcursmallamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter F_CURRECKSMALLAMT   	 
	 */
	public static String columnJavaTypeFcurrecksmallamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter TS_SYSUPDATE   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_ENROLSRLNO, PK , NOT NULL  , Identity  , Generated 	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIenrolsrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter D_ENDDATE , NOT NULL   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDenddate(){
		 return "DATE";
	}
	/**
	 * Getter D_STARTDATE , NOT NULL   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDstartdate(){
		 return "DATE";
	}
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbookorgcode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrecode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BDGORGCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdgorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BDGORGNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdgorgname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BNKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbnkno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNCSBTCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfuncsbtcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ECOSBTCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSecosbtcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter C_AMTKIND   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeCamtkind(){
		 return "CHARACTER";
	}
	/**
	 * Getter F_LASTMONTHZEROAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFlastmonthzeroamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter F_CURZEROAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFcurzeroamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter F_CURRECKZEROAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFcurreckzeroamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter F_LASTMONTHSMALLAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFlastmonthsmallamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter F_CURSMALLAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFcursmallamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter F_CURRECKSMALLAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFcurrecksmallamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter TS_SYSUPDATE   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_BOOKORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSbookorgcode(){
		 return 12;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static int columnWidthStrecode(){
		 return 10;
	}
	/**
	 * Getter S_BDGORGCODE   	 
	 */
	public static int columnWidthSbdgorgcode(){
		 return 15;
	}
	/**
	 * Getter S_BDGORGNAME , NOT NULL   	 
	 */
	public static int columnWidthSbdgorgname(){
		 return 60;
	}
	/**
	 * Getter S_BNKNO   	 
	 */
	public static int columnWidthSbnkno(){
		 return 12;
	}
	/**
	 * Getter S_FUNCSBTCODE   	 
	 */
	public static int columnWidthSfuncsbtcode(){
		 return 30;
	}
	/**
	 * Getter S_ECOSBTCODE   	 
	 */
	public static int columnWidthSecosbtcode(){
		 return 30;
	}
	/**
	 * Getter C_AMTKIND   	 
	 */
	public static int columnWidthCamtkind(){
		 return 1;
	}
}