      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TS_BANKCODE</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:28:59 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TsBankcodeInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TS_BANKCODE";
	
	/**
	 * column S_BNKCODE
	 */
	public static String S_BNKCODE ="S_BNKCODE";
	/**
	 * column S_ACCTSTATUS
	 */
	public static String S_ACCTSTATUS ="S_ACCTSTATUS";
	/**
	 * column S_BNKNAME
	 */
	public static String S_BNKNAME ="S_BNKNAME";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[3];        
        columnNames[0]="S_BNKCODE";
        columnNames[1]="S_ACCTSTATUS";
        columnNames[2]="S_BNKNAME";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_BNKCODE, PK , NOT NULL   	 
	 */
	public static String columnSbnkcode(){
		 return S_BNKCODE;
	}
	/**
	 * Getter S_ACCTSTATUS, PK , NOT NULL   	 
	 */
	public static String columnSacctstatus(){
		 return S_ACCTSTATUS;
	}
	/**
	 * Getter S_BNKNAME , NOT NULL   	 
	 */
	public static String columnSbnkname(){
		 return S_BNKNAME;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_BNKCODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSbnkcode(){
		 return "String";
	}
	/**
	 * Getter S_ACCTSTATUS, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSacctstatus(){
		 return "String";
	}
	/**
	 * Getter S_BNKNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSbnkname(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_BNKCODE, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbnkcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ACCTSTATUS, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSacctstatus(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BNKNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbnkname(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_BNKCODE, PK , NOT NULL   	 
	 */
	public static int columnWidthSbnkcode(){
		 return 12;
	}
	/**
	 * Getter S_ACCTSTATUS, PK , NOT NULL   	 
	 */
	public static int columnWidthSacctstatus(){
		 return 1;
	}
	/**
	 * Getter S_BNKNAME , NOT NULL   	 
	 */
	public static int columnWidthSbnkname(){
		 return 100;
	}
}