      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TS_CONVERTBANKNAME</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:00 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TsConvertbanknameInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TS_CONVERTBANKNAME";
	
	/**
	 * column S_ORGCODE
	 */
	public static String S_ORGCODE ="S_ORGCODE";
	/**
	 * column S_BANKNAME
	 */
	public static String S_BANKNAME ="S_BANKNAME";
	/**
	 * column S_TCBANKNAME
	 */
	public static String S_TCBANKNAME ="S_TCBANKNAME";
	/**
	 * column S_BANKCODE
	 */
	public static String S_BANKCODE ="S_BANKCODE";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[4];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_BANKNAME";
        columnNames[2]="S_TCBANKNAME";
        columnNames[3]="S_BANKCODE";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static String columnSorgcode(){
		 return S_ORGCODE;
	}
	/**
	 * Getter S_BANKNAME, PK , NOT NULL   	 
	 */
	public static String columnSbankname(){
		 return S_BANKNAME;
	}
	/**
	 * Getter S_TCBANKNAME , NOT NULL   	 
	 */
	public static String columnStcbankname(){
		 return S_TCBANKNAME;
	}
	/**
	 * Getter S_BANKCODE , NOT NULL   	 
	 */
	public static String columnSbankcode(){
		 return S_BANKCODE;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSorgcode(){
		 return "String";
	}
	/**
	 * Getter S_BANKNAME, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSbankname(){
		 return "String";
	}
	/**
	 * Getter S_TCBANKNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeStcbankname(){
		 return "String";
	}
	/**
	 * Getter S_BANKCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbankcode(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BANKNAME, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_TCBANKNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStcbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BANKCODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbankcode(){
		 return "CHARACTER";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static int columnWidthSorgcode(){
		 return 12;
	}
	/**
	 * Getter S_BANKNAME, PK , NOT NULL   	 
	 */
	public static int columnWidthSbankname(){
		 return 100;
	}
	/**
	 * Getter S_TCBANKNAME , NOT NULL   	 
	 */
	public static int columnWidthStcbankname(){
		 return 100;
	}
	/**
	 * Getter S_BANKCODE , NOT NULL   	 
	 */
	public static int columnWidthSbankcode(){
		 return 12;
	}
}