      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TS_INFOTAXORG</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:00 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TsInfotaxorgInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TS_INFOTAXORG";
	
	/**
	 * column S_ORGCODE
	 */
	public static String S_ORGCODE ="S_ORGCODE";
	/**
	 * column S_TRECODE
	 */
	public static String S_TRECODE ="S_TRECODE";
	/**
	 * column S_TAXORG
	 */
	public static String S_TAXORG ="S_TAXORG";
	/**
	 * column S_PAYERNAME
	 */
	public static String S_PAYERNAME ="S_PAYERNAME";
	/**
	 * column S_PAYERBANK
	 */
	public static String S_PAYERBANK ="S_PAYERBANK";
	/**
	 * column S_ACCOUNT
	 */
	public static String S_ACCOUNT ="S_ACCOUNT";
	/**
	 * column I_MODICOUNT
	 */
	public static String I_MODICOUNT ="I_MODICOUNT";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[7];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_TRECODE";
        columnNames[2]="S_TAXORG";
        columnNames[3]="S_PAYERNAME";
        columnNames[4]="S_PAYERBANK";
        columnNames[5]="S_ACCOUNT";
        columnNames[6]="I_MODICOUNT";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static String columnSorgcode(){
		 return S_ORGCODE;
	}
	/**
	 * Getter S_TRECODE, PK , NOT NULL   	 
	 */
	public static String columnStrecode(){
		 return S_TRECODE;
	}
	/**
	 * Getter S_TAXORG, PK , NOT NULL   	 
	 */
	public static String columnStaxorg(){
		 return S_TAXORG;
	}
	/**
	 * Getter S_PAYERNAME   	 
	 */
	public static String columnSpayername(){
		 return S_PAYERNAME;
	}
	/**
	 * Getter S_PAYERBANK   	 
	 */
	public static String columnSpayerbank(){
		 return S_PAYERBANK;
	}
	/**
	 * Getter S_ACCOUNT   	 
	 */
	public static String columnSaccount(){
		 return S_ACCOUNT;
	}
	/**
	 * Getter I_MODICOUNT   	 
	 */
	public static String columnImodicount(){
		 return I_MODICOUNT;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSorgcode(){
		 return "String";
	}
	/**
	 * Getter S_TRECODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeStrecode(){
		 return "String";
	}
	/**
	 * Getter S_TAXORG, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxorg(){
		 return "String";
	}
	/**
	 * Getter S_PAYERNAME   	 
	 */
	public static String columnJavaTypeSpayername(){
		 return "String";
	}
	/**
	 * Getter S_PAYERBANK   	 
	 */
	public static String columnJavaTypeSpayerbank(){
		 return "String";
	}
	/**
	 * Getter S_ACCOUNT   	 
	 */
	public static String columnJavaTypeSaccount(){
		 return "String";
	}
	/**
	 * Getter I_MODICOUNT   	 
	 */
	public static String columnJavaTypeImodicount(){
		 return "Integer";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_TRECODE, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrecode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TAXORG, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxorg(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayername(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERBANK   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayerbank(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ACCOUNT   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSaccount(){
		 return "VARCHAR";
	}
	/**
	 * Getter I_MODICOUNT   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeImodicount(){
		 return "INTEGER";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static int columnWidthSorgcode(){
		 return 12;
	}
	/**
	 * Getter S_TRECODE, PK , NOT NULL   	 
	 */
	public static int columnWidthStrecode(){
		 return 10;
	}
	/**
	 * Getter S_TAXORG, PK , NOT NULL   	 
	 */
	public static int columnWidthStaxorg(){
		 return 30;
	}
	/**
	 * Getter S_PAYERNAME   	 
	 */
	public static int columnWidthSpayername(){
		 return 60;
	}
	/**
	 * Getter S_PAYERBANK   	 
	 */
	public static int columnWidthSpayerbank(){
		 return 60;
	}
	/**
	 * Getter S_ACCOUNT   	 
	 */
	public static int columnWidthSaccount(){
		 return 50;
	}
}