      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TS_MANKEYMODE</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:00 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TsMankeymodeInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TS_MANKEYMODE";
	
	/**
	 * column S_KEYMODE
	 */
	public static String S_KEYMODE ="S_KEYMODE";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[1];        
        columnNames[0]="S_KEYMODE";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_KEYMODE, PK , NOT NULL   	 
	 */
	public static String columnSkeymode(){
		 return S_KEYMODE;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_KEYMODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSkeymode(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_KEYMODE, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSkeymode(){
		 return "CHARACTER";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_KEYMODE, PK , NOT NULL   	 
	 */
	public static int columnWidthSkeymode(){
		 return 1;
	}
}