      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TV_DIRECTPAYMSGMAIN</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:01 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TvDirectpaymsgmainInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TV_DIRECTPAYMSGMAIN";
	
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column S_ORGCODE
	 */
	public static String S_ORGCODE ="S_ORGCODE";
	/**
	 * column S_COMMITDATE
	 */
	public static String S_COMMITDATE ="S_COMMITDATE";
	/**
	 * column S_ACCDATE
	 */
	public static String S_ACCDATE ="S_ACCDATE";
	/**
	 * column S_FILENAME
	 */
	public static String S_FILENAME ="S_FILENAME";
	/**
	 * column S_PACKAGENO
	 */
	public static String S_PACKAGENO ="S_PACKAGENO";
	/**
	 * column S_TRECODE
	 */
	public static String S_TRECODE ="S_TRECODE";
	/**
	 * column S_PAYUNIT
	 */
	public static String S_PAYUNIT ="S_PAYUNIT";
	/**
	 * column S_TRANSBANKCODE
	 */
	public static String S_TRANSBANKCODE ="S_TRANSBANKCODE";
	/**
	 * column S_DEALNO
	 */
	public static String S_DEALNO ="S_DEALNO";
	/**
	 * column N_MONEY
	 */
	public static String N_MONEY ="N_MONEY";
	/**
	 * column S_TAXTICKETNO
	 */
	public static String S_TAXTICKETNO ="S_TAXTICKETNO";
	/**
	 * column S_PACKAGETICKETNO
	 */
	public static String S_PACKAGETICKETNO ="S_PACKAGETICKETNO";
	/**
	 * column S_GENTICKETDATE
	 */
	public static String S_GENTICKETDATE ="S_GENTICKETDATE";
	/**
	 * column S_BUDGETTYPE
	 */
	public static String S_BUDGETTYPE ="S_BUDGETTYPE";
	/**
	 * column S_OFYEAR
	 */
	public static String S_OFYEAR ="S_OFYEAR";
	/**
	 * column S_TRANSACTUNIT
	 */
	public static String S_TRANSACTUNIT ="S_TRANSACTUNIT";
	/**
	 * column S_AMTTYPE
	 */
	public static String S_AMTTYPE ="S_AMTTYPE";
	/**
	 * column S_STATUS
	 */
	public static String S_STATUS ="S_STATUS";
	/**
	 * column S_USERCODE
	 */
	public static String S_USERCODE ="S_USERCODE";
	/**
	 * column S_DEMO
	 */
	public static String S_DEMO ="S_DEMO";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * column S_FUNDTYPECODE
	 */
	public static String S_FUNDTYPECODE ="S_FUNDTYPECODE";
	/**
	 * column S_FUNDTYPENAME
	 */
	public static String S_FUNDTYPENAME ="S_FUNDTYPENAME";
	/**
	 * column S_PAYEEACCTNO
	 */
	public static String S_PAYEEACCTNO ="S_PAYEEACCTNO";
	/**
	 * column S_PAYEEACCTNAME
	 */
	public static String S_PAYEEACCTNAME ="S_PAYEEACCTNAME";
	/**
	 * column S_PAYEEACCTBANKNAME
	 */
	public static String S_PAYEEACCTBANKNAME ="S_PAYEEACCTBANKNAME";
	/**
	 * column S_PAYACCTNO
	 */
	public static String S_PAYACCTNO ="S_PAYACCTNO";
	/**
	 * column S_PAYACCTNAME
	 */
	public static String S_PAYACCTNAME ="S_PAYACCTNAME";
	/**
	 * column S_PAYACCTBANKNAME
	 */
	public static String S_PAYACCTBANKNAME ="S_PAYACCTBANKNAME";
	/**
	 * column S_PAYBANKCODE
	 */
	public static String S_PAYBANKCODE ="S_PAYBANKCODE";
	/**
	 * column S_PAYBANKNAME
	 */
	public static String S_PAYBANKNAME ="S_PAYBANKNAME";
	/**
	 * column S_PAYBANKNO
	 */
	public static String S_PAYBANKNO ="S_PAYBANKNO";
	/**
	 * column S_XACCTDATE
	 */
	public static String S_XACCTDATE ="S_XACCTDATE";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_PAYVOUCHERNO
	 */
	public static String S_PAYVOUCHERNO ="S_PAYVOUCHERNO";
	/**
	 * column N_XALLAMT
	 */
	public static String N_XALLAMT ="N_XALLAMT";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[39];        
        columnNames[0]="I_VOUSRLNO";
        columnNames[1]="S_ORGCODE";
        columnNames[2]="S_COMMITDATE";
        columnNames[3]="S_ACCDATE";
        columnNames[4]="S_FILENAME";
        columnNames[5]="S_PACKAGENO";
        columnNames[6]="S_TRECODE";
        columnNames[7]="S_PAYUNIT";
        columnNames[8]="S_TRANSBANKCODE";
        columnNames[9]="S_DEALNO";
        columnNames[10]="N_MONEY";
        columnNames[11]="S_TAXTICKETNO";
        columnNames[12]="S_PACKAGETICKETNO";
        columnNames[13]="S_GENTICKETDATE";
        columnNames[14]="S_BUDGETTYPE";
        columnNames[15]="S_OFYEAR";
        columnNames[16]="S_TRANSACTUNIT";
        columnNames[17]="S_AMTTYPE";
        columnNames[18]="S_STATUS";
        columnNames[19]="S_USERCODE";
        columnNames[20]="S_DEMO";
        columnNames[21]="TS_SYSUPDATE";
        columnNames[22]="S_ID";
        columnNames[23]="S_FUNDTYPECODE";
        columnNames[24]="S_FUNDTYPENAME";
        columnNames[25]="S_PAYEEACCTNO";
        columnNames[26]="S_PAYEEACCTNAME";
        columnNames[27]="S_PAYEEACCTBANKNAME";
        columnNames[28]="S_PAYACCTNO";
        columnNames[29]="S_PAYACCTNAME";
        columnNames[30]="S_PAYACCTBANKNAME";
        columnNames[31]="S_PAYBANKCODE";
        columnNames[32]="S_PAYBANKNAME";
        columnNames[33]="S_PAYBANKNO";
        columnNames[34]="S_XACCTDATE";
        columnNames[35]="S_HOLD1";
        columnNames[36]="S_HOLD2";
        columnNames[37]="S_PAYVOUCHERNO";
        columnNames[38]="N_XALLAMT";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static String columnSorgcode(){
		 return S_ORGCODE;
	}
	/**
	 * Getter S_COMMITDATE , NOT NULL   	 
	 */
	public static String columnScommitdate(){
		 return S_COMMITDATE;
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 */
	public static String columnSaccdate(){
		 return S_ACCDATE;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnSfilename(){
		 return S_FILENAME;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnSpackageno(){
		 return S_PACKAGENO;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnStrecode(){
		 return S_TRECODE;
	}
	/**
	 * Getter S_PAYUNIT   	 
	 */
	public static String columnSpayunit(){
		 return S_PAYUNIT;
	}
	/**
	 * Getter S_TRANSBANKCODE   	 
	 */
	public static String columnStransbankcode(){
		 return S_TRANSBANKCODE;
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static String columnSdealno(){
		 return S_DEALNO;
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnNmoney(){
		 return N_MONEY;
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 */
	public static String columnStaxticketno(){
		 return S_TAXTICKETNO;
	}
	/**
	 * Getter S_PACKAGETICKETNO , NOT NULL   	 
	 */
	public static String columnSpackageticketno(){
		 return S_PACKAGETICKETNO;
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 */
	public static String columnSgenticketdate(){
		 return S_GENTICKETDATE;
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnSbudgettype(){
		 return S_BUDGETTYPE;
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnSofyear(){
		 return S_OFYEAR;
	}
	/**
	 * Getter S_TRANSACTUNIT , NOT NULL   	 
	 */
	public static String columnStransactunit(){
		 return S_TRANSACTUNIT;
	}
	/**
	 * Getter S_AMTTYPE , NOT NULL   	 
	 */
	public static String columnSamttype(){
		 return S_AMTTYPE;
	}
	/**
	 * Getter S_STATUS , NOT NULL   	 
	 */
	public static String columnSstatus(){
		 return S_STATUS;
	}
	/**
	 * Getter S_USERCODE , NOT NULL   	 
	 */
	public static String columnSusercode(){
		 return S_USERCODE;
	}
	/**
	 * Getter S_DEMO   	 
	 */
	public static String columnSdemo(){
		 return S_DEMO;
	}
	/**
	 * Getter TS_SYSUPDATE   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/**
	 * Getter S_ID   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static String columnSfundtypecode(){
		 return S_FUNDTYPECODE;
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static String columnSfundtypename(){
		 return S_FUNDTYPENAME;
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 */
	public static String columnSpayeeacctno(){
		 return S_PAYEEACCTNO;
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnSpayeeacctname(){
		 return S_PAYEEACCTNAME;
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnSpayeeacctbankname(){
		 return S_PAYEEACCTBANKNAME;
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 */
	public static String columnSpayacctno(){
		 return S_PAYACCTNO;
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 */
	public static String columnSpayacctname(){
		 return S_PAYACCTNAME;
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 */
	public static String columnSpayacctbankname(){
		 return S_PAYACCTBANKNAME;
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 */
	public static String columnSpaybankcode(){
		 return S_PAYBANKCODE;
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static String columnSpaybankname(){
		 return S_PAYBANKNAME;
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 */
	public static String columnSpaybankno(){
		 return S_PAYBANKNO;
	}
	/**
	 * Getter S_XACCTDATE   	 
	 */
	public static String columnSxacctdate(){
		 return S_XACCTDATE;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 *支付凭证号(调整凭证号) Getter S_PAYVOUCHERNO   	 
	 */
	public static String columnSpayvoucherno(){
		 return S_PAYVOUCHERNO;
	}
	/**
	 *支付金额 Getter N_XALLAMT   	 
	 */
	public static String columnNxallamt(){
		 return N_XALLAMT;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSorgcode(){
		 return "String";
	}
	/**
	 * Getter S_COMMITDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeScommitdate(){
		 return "String";
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSaccdate(){
		 return "String";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSfilename(){
		 return "String";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackageno(){
		 return "String";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStrecode(){
		 return "String";
	}
	/**
	 * Getter S_PAYUNIT   	 
	 */
	public static String columnJavaTypeSpayunit(){
		 return "String";
	}
	/**
	 * Getter S_TRANSBANKCODE   	 
	 */
	public static String columnJavaTypeStransbankcode(){
		 return "String";
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSdealno(){
		 return "String";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnJavaTypeNmoney(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxticketno(){
		 return "String";
	}
	/**
	 * Getter S_PACKAGETICKETNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackageticketno(){
		 return "String";
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSgenticketdate(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbudgettype(){
		 return "String";
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnJavaTypeSofyear(){
		 return "String";
	}
	/**
	 * Getter S_TRANSACTUNIT , NOT NULL   	 
	 */
	public static String columnJavaTypeStransactunit(){
		 return "String";
	}
	/**
	 * Getter S_AMTTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSamttype(){
		 return "String";
	}
	/**
	 * Getter S_STATUS , NOT NULL   	 
	 */
	public static String columnJavaTypeSstatus(){
		 return "String";
	}
	/**
	 * Getter S_USERCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSusercode(){
		 return "String";
	}
	/**
	 * Getter S_DEMO   	 
	 */
	public static String columnJavaTypeSdemo(){
		 return "String";
	}
	/**
	 * Getter TS_SYSUPDATE   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/**
	 * Getter S_ID   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static String columnJavaTypeSfundtypecode(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static String columnJavaTypeSfundtypename(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 */
	public static String columnJavaTypeSpayeeacctno(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctname(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSpayeeacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 */
	public static String columnJavaTypeSpayacctno(){
		 return "String";
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 */
	public static String columnJavaTypeSpayacctname(){
		 return "String";
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSpayacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 */
	public static String columnJavaTypeSpaybankcode(){
		 return "String";
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static String columnJavaTypeSpaybankname(){
		 return "String";
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 */
	public static String columnJavaTypeSpaybankno(){
		 return "String";
	}
	/**
	 * Getter S_XACCTDATE   	 
	 */
	public static String columnJavaTypeSxacctdate(){
		 return "String";
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 *支付凭证号(调整凭证号) Getter S_PAYVOUCHERNO   	 
	 */
	public static String columnJavaTypeSpayvoucherno(){
		 return "String";
	}
	/**
	 *支付金额 Getter N_XALLAMT   	 
	 */
	public static String columnJavaTypeNxallamt(){
		 return "BigDecimal";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_COMMITDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeScommitdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSaccdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpackageno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrecode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_PAYUNIT   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayunit(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_TRANSBANKCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStransbankcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSdealno(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNmoney(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxticketno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PACKAGETICKETNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpackageticketno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSgenticketdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbudgettype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSofyear(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TRANSACTUNIT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStransactunit(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_AMTTYPE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSamttype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_STATUS , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSstatus(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_USERCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSusercode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_DEMO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSdemo(){
		 return "VARCHAR";
	}
	/**
	 * Getter TS_SYSUPDATE   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/**
	 * Getter S_ID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XACCTDATE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxacctdate(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 *支付凭证号(调整凭证号) Getter S_PAYVOUCHERNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayvoucherno(){
		 return "VARCHAR";
	}
	/**
	 *支付金额 Getter N_XALLAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNxallamt(){
		 return "DECIMAL";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSorgcode(){
		 return 12;
	}
	/**
	 * Getter S_COMMITDATE , NOT NULL   	 
	 */
	public static int columnWidthScommitdate(){
		 return 8;
	}
	/**
	 * Getter S_ACCDATE , NOT NULL   	 
	 */
	public static int columnWidthSaccdate(){
		 return 8;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static int columnWidthSfilename(){
		 return 100;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static int columnWidthSpackageno(){
		 return 8;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static int columnWidthStrecode(){
		 return 10;
	}
	/**
	 * Getter S_PAYUNIT   	 
	 */
	public static int columnWidthSpayunit(){
		 return 30;
	}
	/**
	 * Getter S_TRANSBANKCODE   	 
	 */
	public static int columnWidthStransbankcode(){
		 return 12;
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static int columnWidthSdealno(){
		 return 8;
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 */
	public static int columnWidthStaxticketno(){
		 return 30;
	}
	/**
	 * Getter S_PACKAGETICKETNO , NOT NULL   	 
	 */
	public static int columnWidthSpackageticketno(){
		 return 30;
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 */
	public static int columnWidthSgenticketdate(){
		 return 8;
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static int columnWidthSbudgettype(){
		 return 1;
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static int columnWidthSofyear(){
		 return 4;
	}
	/**
	 * Getter S_TRANSACTUNIT , NOT NULL   	 
	 */
	public static int columnWidthStransactunit(){
		 return 30;
	}
	/**
	 * Getter S_AMTTYPE , NOT NULL   	 
	 */
	public static int columnWidthSamttype(){
		 return 1;
	}
	/**
	 * Getter S_STATUS , NOT NULL   	 
	 */
	public static int columnWidthSstatus(){
		 return 5;
	}
	/**
	 * Getter S_USERCODE , NOT NULL   	 
	 */
	public static int columnWidthSusercode(){
		 return 30;
	}
	/**
	 * Getter S_DEMO   	 
	 */
	public static int columnWidthSdemo(){
		 return 100;
	}
	/**
	 * Getter S_ID   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static int columnWidthSfundtypecode(){
		 return 42;
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static int columnWidthSfundtypename(){
		 return 60;
	}
	/**
	 * Getter S_PAYEEACCTNO   	 
	 */
	public static int columnWidthSpayeeacctno(){
		 return 42;
	}
	/**
	 * Getter S_PAYEEACCTNAME   	 
	 */
	public static int columnWidthSpayeeacctname(){
		 return 120;
	}
	/**
	 * Getter S_PAYEEACCTBANKNAME   	 
	 */
	public static int columnWidthSpayeeacctbankname(){
		 return 120;
	}
	/**
	 * Getter S_PAYACCTNO   	 
	 */
	public static int columnWidthSpayacctno(){
		 return 42;
	}
	/**
	 * Getter S_PAYACCTNAME   	 
	 */
	public static int columnWidthSpayacctname(){
		 return 120;
	}
	/**
	 * Getter S_PAYACCTBANKNAME   	 
	 */
	public static int columnWidthSpayacctbankname(){
		 return 120;
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 */
	public static int columnWidthSpaybankcode(){
		 return 60;
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static int columnWidthSpaybankname(){
		 return 200;
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 */
	public static int columnWidthSpaybankno(){
		 return 12;
	}
	/**
	 * Getter S_XACCTDATE   	 
	 */
	public static int columnWidthSxacctdate(){
		 return 15;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 60;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 60;
	}
	/**
	 *支付凭证号(调整凭证号) Getter S_PAYVOUCHERNO   	 
	 */
	public static int columnWidthSpayvoucherno(){
		 return 42;
	}
}