      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TV_DIRECTPAYFILEMAIN_TMP</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:01 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TvDirectpayfilemainTmpInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TV_DIRECTPAYFILEMAIN_TMP";
	
	/**
	 * column S_OFYEAR
	 */
	public static String S_OFYEAR ="S_OFYEAR";
	/**
	 * column S_TAXTICKETNO
	 */
	public static String S_TAXTICKETNO ="S_TAXTICKETNO";
	/**
	 * column S_GENTICKETDATE
	 */
	public static String S_GENTICKETDATE ="S_GENTICKETDATE";
	/**
	 * column S_BUDGETUNITCODE
	 */
	public static String S_BUDGETUNITCODE ="S_BUDGETUNITCODE";
	/**
	 * column S_UNITCODENAME
	 */
	public static String S_UNITCODENAME ="S_UNITCODENAME";
	/**
	 * column S_SETTLETYPE
	 */
	public static String S_SETTLETYPE ="S_SETTLETYPE";
	/**
	 * column S_SETTLENO
	 */
	public static String S_SETTLENO ="S_SETTLENO";
	/**
	 * column N_MONEY
	 */
	public static String N_MONEY ="N_MONEY";
	/**
	 * column S_PURPOSE
	 */
	public static String S_PURPOSE ="S_PURPOSE";
	/**
	 * column S_PAYBANKCODE
	 */
	public static String S_PAYBANKCODE ="S_PAYBANKCODE";
	/**
	 * column S_PAYBANKNAME
	 */
	public static String S_PAYBANKNAME ="S_PAYBANKNAME";
	/**
	 * column S_PAYBANKNO
	 */
	public static String S_PAYBANKNO ="S_PAYBANKNO";
	/**
	 * column S_RECNAME
	 */
	public static String S_RECNAME ="S_RECNAME";
	/**
	 * column S_RECBANKNAME
	 */
	public static String S_RECBANKNAME ="S_RECBANKNAME";
	/**
	 * column S_RECBANKNO
	 */
	public static String S_RECBANKNO ="S_RECBANKNO";
	/**
	 * column S_OBILLNO
	 */
	public static String S_OBILLNO ="S_OBILLNO";
	/**
	 * column S_FILENAME
	 */
	public static String S_FILENAME ="S_FILENAME";
	/**
	 * column S_ORGCODE
	 */
	public static String S_ORGCODE ="S_ORGCODE";
	/**
	 * column S_DEALNO
	 */
	public static String S_DEALNO ="S_DEALNO";
	/**
	 * column S_PACKAGENO
	 */
	public static String S_PACKAGENO ="S_PACKAGENO";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[20];        
        columnNames[0]="S_OFYEAR";
        columnNames[1]="S_TAXTICKETNO";
        columnNames[2]="S_GENTICKETDATE";
        columnNames[3]="S_BUDGETUNITCODE";
        columnNames[4]="S_UNITCODENAME";
        columnNames[5]="S_SETTLETYPE";
        columnNames[6]="S_SETTLENO";
        columnNames[7]="N_MONEY";
        columnNames[8]="S_PURPOSE";
        columnNames[9]="S_PAYBANKCODE";
        columnNames[10]="S_PAYBANKNAME";
        columnNames[11]="S_PAYBANKNO";
        columnNames[12]="S_RECNAME";
        columnNames[13]="S_RECBANKNAME";
        columnNames[14]="S_RECBANKNO";
        columnNames[15]="S_OBILLNO";
        columnNames[16]="S_FILENAME";
        columnNames[17]="S_ORGCODE";
        columnNames[18]="S_DEALNO";
        columnNames[19]="S_PACKAGENO";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnSofyear(){
		 return S_OFYEAR;
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 */
	public static String columnStaxticketno(){
		 return S_TAXTICKETNO;
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 */
	public static String columnSgenticketdate(){
		 return S_GENTICKETDATE;
	}
	/**
	 * Getter S_BUDGETUNITCODE , NOT NULL   	 
	 */
	public static String columnSbudgetunitcode(){
		 return S_BUDGETUNITCODE;
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 */
	public static String columnSunitcodename(){
		 return S_UNITCODENAME;
	}
	/**
	 * Getter S_SETTLETYPE   	 
	 */
	public static String columnSsettletype(){
		 return S_SETTLETYPE;
	}
	/**
	 * Getter S_SETTLENO   	 
	 */
	public static String columnSsettleno(){
		 return S_SETTLENO;
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnNmoney(){
		 return N_MONEY;
	}
	/**
	 * Getter S_PURPOSE   	 
	 */
	public static String columnSpurpose(){
		 return S_PURPOSE;
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 */
	public static String columnSpaybankcode(){
		 return S_PAYBANKCODE;
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static String columnSpaybankname(){
		 return S_PAYBANKNAME;
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 */
	public static String columnSpaybankno(){
		 return S_PAYBANKNO;
	}
	/**
	 * Getter S_RECNAME   	 
	 */
	public static String columnSrecname(){
		 return S_RECNAME;
	}
	/**
	 * Getter S_RECBANKNAME   	 
	 */
	public static String columnSrecbankname(){
		 return S_RECBANKNAME;
	}
	/**
	 * Getter S_RECBANKNO   	 
	 */
	public static String columnSrecbankno(){
		 return S_RECBANKNO;
	}
	/**
	 * Getter S_OBILLNO   	 
	 */
	public static String columnSobillno(){
		 return S_OBILLNO;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnSfilename(){
		 return S_FILENAME;
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static String columnSorgcode(){
		 return S_ORGCODE;
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static String columnSdealno(){
		 return S_DEALNO;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnSpackageno(){
		 return S_PACKAGENO;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnJavaTypeSofyear(){
		 return "String";
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxticketno(){
		 return "String";
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSgenticketdate(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETUNITCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbudgetunitcode(){
		 return "String";
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 */
	public static String columnJavaTypeSunitcodename(){
		 return "String";
	}
	/**
	 * Getter S_SETTLETYPE   	 
	 */
	public static String columnJavaTypeSsettletype(){
		 return "String";
	}
	/**
	 * Getter S_SETTLENO   	 
	 */
	public static String columnJavaTypeSsettleno(){
		 return "String";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnJavaTypeNmoney(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_PURPOSE   	 
	 */
	public static String columnJavaTypeSpurpose(){
		 return "String";
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 */
	public static String columnJavaTypeSpaybankcode(){
		 return "String";
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static String columnJavaTypeSpaybankname(){
		 return "String";
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 */
	public static String columnJavaTypeSpaybankno(){
		 return "String";
	}
	/**
	 * Getter S_RECNAME   	 
	 */
	public static String columnJavaTypeSrecname(){
		 return "String";
	}
	/**
	 * Getter S_RECBANKNAME   	 
	 */
	public static String columnJavaTypeSrecbankname(){
		 return "String";
	}
	/**
	 * Getter S_RECBANKNO   	 
	 */
	public static String columnJavaTypeSrecbankno(){
		 return "String";
	}
	/**
	 * Getter S_OBILLNO   	 
	 */
	public static String columnJavaTypeSobillno(){
		 return "String";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSfilename(){
		 return "String";
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSorgcode(){
		 return "String";
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSdealno(){
		 return "String";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackageno(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSofyear(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxticketno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSgenticketdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BUDGETUNITCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbudgetunitcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSunitcodename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_SETTLETYPE   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSsettletype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_SETTLENO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSsettleno(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNmoney(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_PURPOSE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpurpose(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_RECNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSrecname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_RECBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSrecbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_RECBANKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSrecbankno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_OBILLNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSobillno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSdealno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpackageno(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static int columnWidthSofyear(){
		 return 4;
	}
	/**
	 * Getter S_TAXTICKETNO , NOT NULL   	 
	 */
	public static int columnWidthStaxticketno(){
		 return 30;
	}
	/**
	 * Getter S_GENTICKETDATE , NOT NULL   	 
	 */
	public static int columnWidthSgenticketdate(){
		 return 8;
	}
	/**
	 * Getter S_BUDGETUNITCODE , NOT NULL   	 
	 */
	public static int columnWidthSbudgetunitcode(){
		 return 30;
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 */
	public static int columnWidthSunitcodename(){
		 return 120;
	}
	/**
	 * Getter S_SETTLETYPE   	 
	 */
	public static int columnWidthSsettletype(){
		 return 1;
	}
	/**
	 * Getter S_SETTLENO   	 
	 */
	public static int columnWidthSsettleno(){
		 return 60;
	}
	/**
	 * Getter S_PURPOSE   	 
	 */
	public static int columnWidthSpurpose(){
		 return 200;
	}
	/**
	 * Getter S_PAYBANKCODE   	 
	 */
	public static int columnWidthSpaybankcode(){
		 return 60;
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static int columnWidthSpaybankname(){
		 return 120;
	}
	/**
	 * Getter S_PAYBANKNO   	 
	 */
	public static int columnWidthSpaybankno(){
		 return 60;
	}
	/**
	 * Getter S_RECNAME   	 
	 */
	public static int columnWidthSrecname(){
		 return 120;
	}
	/**
	 * Getter S_RECBANKNAME   	 
	 */
	public static int columnWidthSrecbankname(){
		 return 120;
	}
	/**
	 * Getter S_RECBANKNO   	 
	 */
	public static int columnWidthSrecbankno(){
		 return 60;
	}
	/**
	 * Getter S_OBILLNO   	 
	 */
	public static int columnWidthSobillno(){
		 return 6;
	}
	/**
	 * Getter S_FILENAME , NOT NULL   	 
	 */
	public static int columnWidthSfilename(){
		 return 100;
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSorgcode(){
		 return 12;
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static int columnWidthSdealno(){
		 return 8;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static int columnWidthSpackageno(){
		 return 8;
	}
}