      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TV_GRANTPAYFILESUB_TMP</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TvGrantpayfilesubTmpInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TV_GRANTPAYFILESUB_TMP";
	
	/**
	 * column S_LIMITID
	 */
	public static String S_LIMITID ="S_LIMITID";
	/**
	 * column S_LINE
	 */
	public static String S_LINE ="S_LINE";
	/**
	 * column S_OFYEAR
	 */
	public static String S_OFYEAR ="S_OFYEAR";
	/**
	 * column S_GPLANID
	 */
	public static String S_GPLANID ="S_GPLANID";
	/**
	 * column S_GPLANDETAILID
	 */
	public static String S_GPLANDETAILID ="S_GPLANDETAILID";
	/**
	 * column S_BUDGETUNITCODE
	 */
	public static String S_BUDGETUNITCODE ="S_BUDGETUNITCODE";
	/**
	 * column S_UNITCODENAME
	 */
	public static String S_UNITCODENAME ="S_UNITCODENAME";
	/**
	 * column S_FUNSUBJECTCODE
	 */
	public static String S_FUNSUBJECTCODE ="S_FUNSUBJECTCODE";
	/**
	 * column S_FUNSUBJECTCODENAME
	 */
	public static String S_FUNSUBJECTCODENAME ="S_FUNSUBJECTCODENAME";
	/**
	 * column S_TZBM
	 */
	public static String S_TZBM ="S_TZBM";
	/**
	 * column S_TZMC
	 */
	public static String S_TZMC ="S_TZMC";
	/**
	 * column N_MONEY
	 */
	public static String N_MONEY ="N_MONEY";
	/**
	 * column S_PACKAGENO
	 */
	public static String S_PACKAGENO ="S_PACKAGENO";
	/**
	 * column S_DEALNO
	 */
	public static String S_DEALNO ="S_DEALNO";
	/**
	 * column S_FILENAME
	 */
	public static String S_FILENAME ="S_FILENAME";
	/**
	 * column S_ORGCODE
	 */
	public static String S_ORGCODE ="S_ORGCODE";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[16];        
        columnNames[0]="S_LIMITID";
        columnNames[1]="S_LINE";
        columnNames[2]="S_OFYEAR";
        columnNames[3]="S_GPLANID";
        columnNames[4]="S_GPLANDETAILID";
        columnNames[5]="S_BUDGETUNITCODE";
        columnNames[6]="S_UNITCODENAME";
        columnNames[7]="S_FUNSUBJECTCODE";
        columnNames[8]="S_FUNSUBJECTCODENAME";
        columnNames[9]="S_TZBM";
        columnNames[10]="S_TZMC";
        columnNames[11]="N_MONEY";
        columnNames[12]="S_PACKAGENO";
        columnNames[13]="S_DEALNO";
        columnNames[14]="S_FILENAME";
        columnNames[15]="S_ORGCODE";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_LIMITID , NOT NULL   	 
	 */
	public static String columnSlimitid(){
		 return S_LIMITID;
	}
	/**
	 * Getter S_LINE , NOT NULL   	 
	 */
	public static String columnSline(){
		 return S_LINE;
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnSofyear(){
		 return S_OFYEAR;
	}
	/**
	 * Getter S_GPLANID   	 
	 */
	public static String columnSgplanid(){
		 return S_GPLANID;
	}
	/**
	 * Getter S_GPLANDETAILID   	 
	 */
	public static String columnSgplandetailid(){
		 return S_GPLANDETAILID;
	}
	/**
	 * Getter S_BUDGETUNITCODE   	 
	 */
	public static String columnSbudgetunitcode(){
		 return S_BUDGETUNITCODE;
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 */
	public static String columnSunitcodename(){
		 return S_UNITCODENAME;
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnSfunsubjectcode(){
		 return S_FUNSUBJECTCODE;
	}
	/**
	 * Getter S_FUNSUBJECTCODENAME   	 
	 */
	public static String columnSfunsubjectcodename(){
		 return S_FUNSUBJECTCODENAME;
	}
	/**
	 * Getter S_TZBM   	 
	 */
	public static String columnStzbm(){
		 return S_TZBM;
	}
	/**
	 * Getter S_TZMC   	 
	 */
	public static String columnStzmc(){
		 return S_TZMC;
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnNmoney(){
		 return N_MONEY;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnSpackageno(){
		 return S_PACKAGENO;
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static String columnSdealno(){
		 return S_DEALNO;
	}
	/**
	 * Getter S_FILENAME   	 
	 */
	public static String columnSfilename(){
		 return S_FILENAME;
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static String columnSorgcode(){
		 return S_ORGCODE;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_LIMITID , NOT NULL   	 
	 */
	public static String columnJavaTypeSlimitid(){
		 return "String";
	}
	/**
	 * Getter S_LINE , NOT NULL   	 
	 */
	public static String columnJavaTypeSline(){
		 return "String";
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnJavaTypeSofyear(){
		 return "String";
	}
	/**
	 * Getter S_GPLANID   	 
	 */
	public static String columnJavaTypeSgplanid(){
		 return "String";
	}
	/**
	 * Getter S_GPLANDETAILID   	 
	 */
	public static String columnJavaTypeSgplandetailid(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETUNITCODE   	 
	 */
	public static String columnJavaTypeSbudgetunitcode(){
		 return "String";
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 */
	public static String columnJavaTypeSunitcodename(){
		 return "String";
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfunsubjectcode(){
		 return "String";
	}
	/**
	 * Getter S_FUNSUBJECTCODENAME   	 
	 */
	public static String columnJavaTypeSfunsubjectcodename(){
		 return "String";
	}
	/**
	 * Getter S_TZBM   	 
	 */
	public static String columnJavaTypeStzbm(){
		 return "String";
	}
	/**
	 * Getter S_TZMC   	 
	 */
	public static String columnJavaTypeStzmc(){
		 return "String";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnJavaTypeNmoney(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackageno(){
		 return "String";
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSdealno(){
		 return "String";
	}
	/**
	 * Getter S_FILENAME   	 
	 */
	public static String columnJavaTypeSfilename(){
		 return "String";
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSorgcode(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_LIMITID , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSlimitid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_LINE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSline(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSofyear(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_GPLANID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSgplanid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_GPLANDETAILID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSgplandetailid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BUDGETUNITCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbudgetunitcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSunitcodename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfunsubjectcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNSUBJECTCODENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfunsubjectcodename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_TZBM   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStzbm(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TZMC   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStzmc(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNmoney(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpackageno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSdealno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FILENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorgcode(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_LIMITID , NOT NULL   	 
	 */
	public static int columnWidthSlimitid(){
		 return 8;
	}
	/**
	 * Getter S_LINE , NOT NULL   	 
	 */
	public static int columnWidthSline(){
		 return 4;
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static int columnWidthSofyear(){
		 return 4;
	}
	/**
	 * Getter S_GPLANID   	 
	 */
	public static int columnWidthSgplanid(){
		 return 6;
	}
	/**
	 * Getter S_GPLANDETAILID   	 
	 */
	public static int columnWidthSgplandetailid(){
		 return 4;
	}
	/**
	 * Getter S_BUDGETUNITCODE   	 
	 */
	public static int columnWidthSbudgetunitcode(){
		 return 30;
	}
	/**
	 * Getter S_UNITCODENAME   	 
	 */
	public static int columnWidthSunitcodename(){
		 return 120;
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static int columnWidthSfunsubjectcode(){
		 return 30;
	}
	/**
	 * Getter S_FUNSUBJECTCODENAME   	 
	 */
	public static int columnWidthSfunsubjectcodename(){
		 return 120;
	}
	/**
	 * Getter S_TZBM   	 
	 */
	public static int columnWidthStzbm(){
		 return 2;
	}
	/**
	 * Getter S_TZMC   	 
	 */
	public static int columnWidthStzmc(){
		 return 120;
	}
	/**
	 * Getter S_PACKAGENO , NOT NULL   	 
	 */
	public static int columnWidthSpackageno(){
		 return 8;
	}
	/**
	 * Getter S_DEALNO , NOT NULL   	 
	 */
	public static int columnWidthSdealno(){
		 return 8;
	}
	/**
	 * Getter S_FILENAME   	 
	 */
	public static int columnWidthSfilename(){
		 return 100;
	}
	/**
	 * Getter S_ORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSorgcode(){
		 return 12;
	}
}