      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TV_INCOMEONLINE_INCOMEONDETAIL_BLEND</p>
 * <p>Description: 电子税票入库流水勾兑表 Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:02 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TvIncomeonlineIncomeondetailBlendInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TV_INCOMEONLINE_INCOMEONDETAIL_BLEND";
	
	/**
	 * column S_SEQ
	 */
	public static String S_SEQ ="S_SEQ";
	/**
	 * column S_FINORGCODE
	 */
	public static String S_FINORGCODE ="S_FINORGCODE";
	/**
	 * column S_APPLYDATE
	 */
	public static String S_APPLYDATE ="S_APPLYDATE";
	/**
	 * column S_INTREDATE
	 */
	public static String S_INTREDATE ="S_INTREDATE";
	/**
	 * column S_BLEND
	 */
	public static String S_BLEND ="S_BLEND";
	/**
	 * column S_PACKNO
	 */
	public static String S_PACKNO ="S_PACKNO";
	/**
	 * column S_TRECODE
	 */
	public static String S_TRECODE ="S_TRECODE";
	/**
	 * column S_TRENAME
	 */
	public static String S_TRENAME ="S_TRENAME";
	/**
	 * column S_TAXORGCODE
	 */
	public static String S_TAXORGCODE ="S_TAXORGCODE";
	/**
	 * column S_PAYBNKNO
	 */
	public static String S_PAYBNKNO ="S_PAYBNKNO";
	/**
	 * column S_TRANO
	 */
	public static String S_TRANO ="S_TRANO";
	/**
	 * column S_ORIMSGNO
	 */
	public static String S_ORIMSGNO ="S_ORIMSGNO";
	/**
	 * column F_TRAAMT
	 */
	public static String F_TRAAMT ="F_TRAAMT";
	/**
	 * column F_AMT
	 */
	public static String F_AMT ="F_AMT";
	/**
	 * column S_PAYEROPNBNKNO
	 */
	public static String S_PAYEROPNBNKNO ="S_PAYEROPNBNKNO";
	/**
	 * column S_PAYEROPBKNAME
	 */
	public static String S_PAYEROPBKNAME ="S_PAYEROPBKNAME";
	/**
	 * column S_HANDORGNAME
	 */
	public static String S_HANDORGNAME ="S_HANDORGNAME";
	/**
	 * column S_PAYACCT
	 */
	public static String S_PAYACCT ="S_PAYACCT";
	/**
	 * column S_TAXVOUNO
	 */
	public static String S_TAXVOUNO ="S_TAXVOUNO";
	/**
	 * column S_BILLDATE
	 */
	public static String S_BILLDATE ="S_BILLDATE";
	/**
	 * column S_TAXPAYCODE
	 */
	public static String S_TAXPAYCODE ="S_TAXPAYCODE";
	/**
	 * column S_TAXPAYNAME
	 */
	public static String S_TAXPAYNAME ="S_TAXPAYNAME";
	/**
	 * column S_BUDGETTYPE
	 */
	public static String S_BUDGETTYPE ="S_BUDGETTYPE";
	/**
	 * column S_TRIMFLAG
	 */
	public static String S_TRIMFLAG ="S_TRIMFLAG";
	/**
	 * column S_ETPCODE
	 */
	public static String S_ETPCODE ="S_ETPCODE";
	/**
	 * column S_ETPNAME
	 */
	public static String S_ETPNAME ="S_ETPNAME";
	/**
	 * column S_ETPTYPE
	 */
	public static String S_ETPTYPE ="S_ETPTYPE";
	/**
	 * column S_BDGSBTCODE
	 */
	public static String S_BDGSBTCODE ="S_BDGSBTCODE";
	/**
	 * column S_BDGSBTNAME
	 */
	public static String S_BDGSBTNAME ="S_BDGSBTNAME";
	/**
	 * column S_LIMIT
	 */
	public static String S_LIMIT ="S_LIMIT";
	/**
	 * column S_TAXTYPECODE
	 */
	public static String S_TAXTYPECODE ="S_TAXTYPECODE";
	/**
	 * column S_TAXKINDNAME
	 */
	public static String S_TAXKINDNAME ="S_TAXKINDNAME";
	/**
	 * column S_BDGLEVEL
	 */
	public static String S_BDGLEVEL ="S_BDGLEVEL";
	/**
	 * column S_BDGLEVELNAME
	 */
	public static String S_BDGLEVELNAME ="S_BDGLEVELNAME";
	/**
	 * column S_TAXSTARTDATE
	 */
	public static String S_TAXSTARTDATE ="S_TAXSTARTDATE";
	/**
	 * column S_TAXENDDATE
	 */
	public static String S_TAXENDDATE ="S_TAXENDDATE";
	/**
	 * column S_ASTFLAG
	 */
	public static String S_ASTFLAG ="S_ASTFLAG";
	/**
	 * column S_TAXTYPE
	 */
	public static String S_TAXTYPE ="S_TAXTYPE";
	/**
	 * column S_ACCT
	 */
	public static String S_ACCT ="S_ACCT";
	/**
	 * column S_TRASTATE
	 */
	public static String S_TRASTATE ="S_TRASTATE";
	/**
	 * column S_INPUTERID
	 */
	public static String S_INPUTERID ="S_INPUTERID";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * column S_VOUCHANNEL
	 */
	public static String S_VOUCHANNEL ="S_VOUCHANNEL";
	/**
	 * column S_STATUS
	 */
	public static String S_STATUS ="S_STATUS";
	/**
	 * column S_REMARK
	 */
	public static String S_REMARK ="S_REMARK";
	/**
	 * column S_REMARK1
	 */
	public static String S_REMARK1 ="S_REMARK1";
	/**
	 * column S_REMARK2
	 */
	public static String S_REMARK2 ="S_REMARK2";
	/**
	 * column S_REMARK3
	 */
	public static String S_REMARK3 ="S_REMARK3";
	/**
	 * column S_REMARK4
	 */
	public static String S_REMARK4 ="S_REMARK4";
	/**
	 * column S_REMARK5
	 */
	public static String S_REMARK5 ="S_REMARK5";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[50];        
        columnNames[0]="S_SEQ";
        columnNames[1]="S_FINORGCODE";
        columnNames[2]="S_APPLYDATE";
        columnNames[3]="S_INTREDATE";
        columnNames[4]="S_BLEND";
        columnNames[5]="S_PACKNO";
        columnNames[6]="S_TRECODE";
        columnNames[7]="S_TRENAME";
        columnNames[8]="S_TAXORGCODE";
        columnNames[9]="S_PAYBNKNO";
        columnNames[10]="S_TRANO";
        columnNames[11]="S_ORIMSGNO";
        columnNames[12]="F_TRAAMT";
        columnNames[13]="F_AMT";
        columnNames[14]="S_PAYEROPNBNKNO";
        columnNames[15]="S_PAYEROPBKNAME";
        columnNames[16]="S_HANDORGNAME";
        columnNames[17]="S_PAYACCT";
        columnNames[18]="S_TAXVOUNO";
        columnNames[19]="S_BILLDATE";
        columnNames[20]="S_TAXPAYCODE";
        columnNames[21]="S_TAXPAYNAME";
        columnNames[22]="S_BUDGETTYPE";
        columnNames[23]="S_TRIMFLAG";
        columnNames[24]="S_ETPCODE";
        columnNames[25]="S_ETPNAME";
        columnNames[26]="S_ETPTYPE";
        columnNames[27]="S_BDGSBTCODE";
        columnNames[28]="S_BDGSBTNAME";
        columnNames[29]="S_LIMIT";
        columnNames[30]="S_TAXTYPECODE";
        columnNames[31]="S_TAXKINDNAME";
        columnNames[32]="S_BDGLEVEL";
        columnNames[33]="S_BDGLEVELNAME";
        columnNames[34]="S_TAXSTARTDATE";
        columnNames[35]="S_TAXENDDATE";
        columnNames[36]="S_ASTFLAG";
        columnNames[37]="S_TAXTYPE";
        columnNames[38]="S_ACCT";
        columnNames[39]="S_TRASTATE";
        columnNames[40]="S_INPUTERID";
        columnNames[41]="TS_SYSUPDATE";
        columnNames[42]="S_VOUCHANNEL";
        columnNames[43]="S_STATUS";
        columnNames[44]="S_REMARK";
        columnNames[45]="S_REMARK1";
        columnNames[46]="S_REMARK2";
        columnNames[47]="S_REMARK3";
        columnNames[48]="S_REMARK4";
        columnNames[49]="S_REMARK5";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 *主键 Getter S_SEQ, PK , NOT NULL   	 
	 */
	public static String columnSseq(){
		 return S_SEQ;
	}
	/**
	 *财政机关代码 Getter S_FINORGCODE , NOT NULL   	 
	 */
	public static String columnSfinorgcode(){
		 return S_FINORGCODE;
	}
	/**
	 *税票日期 Getter S_APPLYDATE , NOT NULL   	 
	 */
	public static String columnSapplydate(){
		 return S_APPLYDATE;
	}
	/**
	 *入库日期 Getter S_INTREDATE   	 
	 */
	public static String columnSintredate(){
		 return S_INTREDATE;
	}
	/**
	 *勾兑日期 Getter S_BLEND , NOT NULL   	 
	 */
	public static String columnSblend(){
		 return S_BLEND;
	}
	/**
	 *包流水号 Getter S_PACKNO , NOT NULL   	 
	 */
	public static String columnSpackno(){
		 return S_PACKNO;
	}
	/**
	 *国库代码 Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnStrecode(){
		 return S_TRECODE;
	}
	/**
	 *国库名称 Getter S_TRENAME   	 
	 */
	public static String columnStrename(){
		 return S_TRENAME;
	}
	/**
	 *征收机关代码 Getter S_TAXORGCODE , NOT NULL   	 
	 */
	public static String columnStaxorgcode(){
		 return S_TAXORGCODE;
	}
	/**
	 *付款行行号 Getter S_PAYBNKNO   	 
	 */
	public static String columnSpaybnkno(){
		 return S_PAYBNKNO;
	}
	/**
	 *交易流水号 Getter S_TRANO , NOT NULL   	 
	 */
	public static String columnStrano(){
		 return S_TRANO;
	}
	/**
	 *原报文编号 Getter S_ORIMSGNO , NOT NULL   	 
	 */
	public static String columnSorimsgno(){
		 return S_ORIMSGNO;
	}
	/**
	 *税票金额 Getter F_TRAAMT , NOT NULL   	 
	 */
	public static String columnFtraamt(){
		 return F_TRAAMT;
	}
	/**
	 *入库金额 Getter F_AMT , NOT NULL   	 
	 */
	public static String columnFamt(){
		 return F_AMT;
	}
	/**
	 *付款人开户行行号 Getter S_PAYEROPNBNKNO   	 
	 */
	public static String columnSpayeropnbnkno(){
		 return S_PAYEROPNBNKNO;
	}
	/**
	 *付款开户行名称 Getter S_PAYEROPBKNAME   	 
	 */
	public static String columnSpayeropbkname(){
		 return S_PAYEROPBKNAME;
	}
	/**
	 *缴款单位名称 Getter S_HANDORGNAME , NOT NULL   	 
	 */
	public static String columnShandorgname(){
		 return S_HANDORGNAME;
	}
	/**
	 *付款人账号 Getter S_PAYACCT   	 
	 */
	public static String columnSpayacct(){
		 return S_PAYACCT;
	}
	/**
	 *税票号码 Getter S_TAXVOUNO , NOT NULL   	 
	 */
	public static String columnStaxvouno(){
		 return S_TAXVOUNO;
	}
	/**
	 *开票日期 Getter S_BILLDATE   	 
	 */
	public static String columnSbilldate(){
		 return S_BILLDATE;
	}
	/**
	 *纳税人编号 Getter S_TAXPAYCODE , NOT NULL   	 
	 */
	public static String columnStaxpaycode(){
		 return S_TAXPAYCODE;
	}
	/**
	 *纳税人名称 Getter S_TAXPAYNAME , NOT NULL   	 
	 */
	public static String columnStaxpayname(){
		 return S_TAXPAYNAME;
	}
	/**
	 *预算种类 Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnSbudgettype(){
		 return S_BUDGETTYPE;
	}
	/**
	 *调整期标志 Getter S_TRIMFLAG , NOT NULL   	 
	 */
	public static String columnStrimflag(){
		 return S_TRIMFLAG;
	}
	/**
	 *企业代码 Getter S_ETPCODE   	 
	 */
	public static String columnSetpcode(){
		 return S_ETPCODE;
	}
	/**
	 *企业名称 Getter S_ETPNAME   	 
	 */
	public static String columnSetpname(){
		 return S_ETPNAME;
	}
	/**
	 *企业类型 Getter S_ETPTYPE   	 
	 */
	public static String columnSetptype(){
		 return S_ETPTYPE;
	}
	/**
	 *预算科目代码 Getter S_BDGSBTCODE , NOT NULL   	 
	 */
	public static String columnSbdgsbtcode(){
		 return S_BDGSBTCODE;
	}
	/**
	 *预算科目代码 Getter S_BDGSBTNAME   	 
	 */
	public static String columnSbdgsbtname(){
		 return S_BDGSBTNAME;
	}
	/**
	 *限缴日期 Getter S_LIMIT , NOT NULL   	 
	 */
	public static String columnSlimit(){
		 return S_LIMIT;
	}
	/**
	 *税种代码 Getter S_TAXTYPECODE   	 
	 */
	public static String columnStaxtypecode(){
		 return S_TAXTYPECODE;
	}
	/**
	 *税种名称 Getter S_TAXKINDNAME   	 
	 */
	public static String columnStaxkindname(){
		 return S_TAXKINDNAME;
	}
	/**
	 *预算级次 Getter S_BDGLEVEL , NOT NULL   	 
	 */
	public static String columnSbdglevel(){
		 return S_BDGLEVEL;
	}
	/**
	 *预算级次名称 Getter S_BDGLEVELNAME   	 
	 */
	public static String columnSbdglevelname(){
		 return S_BDGLEVELNAME;
	}
	/**
	 *税款所属日期起 Getter S_TAXSTARTDATE , NOT NULL   	 
	 */
	public static String columnStaxstartdate(){
		 return S_TAXSTARTDATE;
	}
	/**
	 *税款所属日期止 Getter S_TAXENDDATE , NOT NULL   	 
	 */
	public static String columnStaxenddate(){
		 return S_TAXENDDATE;
	}
	/**
	 *辅助标志 Getter S_ASTFLAG   	 
	 */
	public static String columnSastflag(){
		 return S_ASTFLAG;
	}
	/**
	 *税款类型 Getter S_TAXTYPE , NOT NULL   	 
	 */
	public static String columnStaxtype(){
		 return S_TAXTYPE;
	}
	/**
	 *账务日期 Getter S_ACCT , NOT NULL   	 
	 */
	public static String columnSacct(){
		 return S_ACCT;
	}
	/**
	 *处理状态 Getter S_TRASTATE , NOT NULL   	 
	 */
	public static String columnStrastate(){
		 return S_TRASTATE;
	}
	/**
	 *录入员代码 Getter S_INPUTERID   	 
	 */
	public static String columnSinputerid(){
		 return S_INPUTERID;
	}
	/**
	 *系统更新时间 Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/**
	 *凭证来源 Getter S_VOUCHANNEL   	 
	 */
	public static String columnSvouchannel(){
		 return S_VOUCHANNEL;
	}
	/**
	 *勾兑状态 Getter S_STATUS , NOT NULL   	 
	 */
	public static String columnSstatus(){
		 return S_STATUS;
	}
	/**
	 *备注 Getter S_REMARK   	 
	 */
	public static String columnSremark(){
		 return S_REMARK;
	}
	/**
	 *备注 Getter S_REMARK1   	 
	 */
	public static String columnSremark1(){
		 return S_REMARK1;
	}
	/**
	 *备注 Getter S_REMARK2   	 
	 */
	public static String columnSremark2(){
		 return S_REMARK2;
	}
	/**
	 *备注 Getter S_REMARK3   	 
	 */
	public static String columnSremark3(){
		 return S_REMARK3;
	}
	/**
	 *备注 Getter S_REMARK4   	 
	 */
	public static String columnSremark4(){
		 return S_REMARK4;
	}
	/**
	 *备注 Getter S_REMARK5   	 
	 */
	public static String columnSremark5(){
		 return S_REMARK5;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 *主键 Getter S_SEQ, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSseq(){
		 return "String";
	}
	/**
	 *财政机关代码 Getter S_FINORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfinorgcode(){
		 return "String";
	}
	/**
	 *税票日期 Getter S_APPLYDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSapplydate(){
		 return "String";
	}
	/**
	 *入库日期 Getter S_INTREDATE   	 
	 */
	public static String columnJavaTypeSintredate(){
		 return "String";
	}
	/**
	 *勾兑日期 Getter S_BLEND , NOT NULL   	 
	 */
	public static String columnJavaTypeSblend(){
		 return "String";
	}
	/**
	 *包流水号 Getter S_PACKNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackno(){
		 return "String";
	}
	/**
	 *国库代码 Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStrecode(){
		 return "String";
	}
	/**
	 *国库名称 Getter S_TRENAME   	 
	 */
	public static String columnJavaTypeStrename(){
		 return "String";
	}
	/**
	 *征收机关代码 Getter S_TAXORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxorgcode(){
		 return "String";
	}
	/**
	 *付款行行号 Getter S_PAYBNKNO   	 
	 */
	public static String columnJavaTypeSpaybnkno(){
		 return "String";
	}
	/**
	 *交易流水号 Getter S_TRANO , NOT NULL   	 
	 */
	public static String columnJavaTypeStrano(){
		 return "String";
	}
	/**
	 *原报文编号 Getter S_ORIMSGNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSorimsgno(){
		 return "String";
	}
	/**
	 *税票金额 Getter F_TRAAMT , NOT NULL   	 
	 */
	public static String columnJavaTypeFtraamt(){
		 return "BigDecimal";
	}
	/**
	 *入库金额 Getter F_AMT , NOT NULL   	 
	 */
	public static String columnJavaTypeFamt(){
		 return "BigDecimal";
	}
	/**
	 *付款人开户行行号 Getter S_PAYEROPNBNKNO   	 
	 */
	public static String columnJavaTypeSpayeropnbnkno(){
		 return "String";
	}
	/**
	 *付款开户行名称 Getter S_PAYEROPBKNAME   	 
	 */
	public static String columnJavaTypeSpayeropbkname(){
		 return "String";
	}
	/**
	 *缴款单位名称 Getter S_HANDORGNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeShandorgname(){
		 return "String";
	}
	/**
	 *付款人账号 Getter S_PAYACCT   	 
	 */
	public static String columnJavaTypeSpayacct(){
		 return "String";
	}
	/**
	 *税票号码 Getter S_TAXVOUNO , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxvouno(){
		 return "String";
	}
	/**
	 *开票日期 Getter S_BILLDATE   	 
	 */
	public static String columnJavaTypeSbilldate(){
		 return "String";
	}
	/**
	 *纳税人编号 Getter S_TAXPAYCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxpaycode(){
		 return "String";
	}
	/**
	 *纳税人名称 Getter S_TAXPAYNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxpayname(){
		 return "String";
	}
	/**
	 *预算种类 Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbudgettype(){
		 return "String";
	}
	/**
	 *调整期标志 Getter S_TRIMFLAG , NOT NULL   	 
	 */
	public static String columnJavaTypeStrimflag(){
		 return "String";
	}
	/**
	 *企业代码 Getter S_ETPCODE   	 
	 */
	public static String columnJavaTypeSetpcode(){
		 return "String";
	}
	/**
	 *企业名称 Getter S_ETPNAME   	 
	 */
	public static String columnJavaTypeSetpname(){
		 return "String";
	}
	/**
	 *企业类型 Getter S_ETPTYPE   	 
	 */
	public static String columnJavaTypeSetptype(){
		 return "String";
	}
	/**
	 *预算科目代码 Getter S_BDGSBTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbdgsbtcode(){
		 return "String";
	}
	/**
	 *预算科目代码 Getter S_BDGSBTNAME   	 
	 */
	public static String columnJavaTypeSbdgsbtname(){
		 return "String";
	}
	/**
	 *限缴日期 Getter S_LIMIT , NOT NULL   	 
	 */
	public static String columnJavaTypeSlimit(){
		 return "String";
	}
	/**
	 *税种代码 Getter S_TAXTYPECODE   	 
	 */
	public static String columnJavaTypeStaxtypecode(){
		 return "String";
	}
	/**
	 *税种名称 Getter S_TAXKINDNAME   	 
	 */
	public static String columnJavaTypeStaxkindname(){
		 return "String";
	}
	/**
	 *预算级次 Getter S_BDGLEVEL , NOT NULL   	 
	 */
	public static String columnJavaTypeSbdglevel(){
		 return "String";
	}
	/**
	 *预算级次名称 Getter S_BDGLEVELNAME   	 
	 */
	public static String columnJavaTypeSbdglevelname(){
		 return "String";
	}
	/**
	 *税款所属日期起 Getter S_TAXSTARTDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxstartdate(){
		 return "String";
	}
	/**
	 *税款所属日期止 Getter S_TAXENDDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxenddate(){
		 return "String";
	}
	/**
	 *辅助标志 Getter S_ASTFLAG   	 
	 */
	public static String columnJavaTypeSastflag(){
		 return "String";
	}
	/**
	 *税款类型 Getter S_TAXTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeStaxtype(){
		 return "String";
	}
	/**
	 *账务日期 Getter S_ACCT , NOT NULL   	 
	 */
	public static String columnJavaTypeSacct(){
		 return "String";
	}
	/**
	 *处理状态 Getter S_TRASTATE , NOT NULL   	 
	 */
	public static String columnJavaTypeStrastate(){
		 return "String";
	}
	/**
	 *录入员代码 Getter S_INPUTERID   	 
	 */
	public static String columnJavaTypeSinputerid(){
		 return "String";
	}
	/**
	 *系统更新时间 Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/**
	 *凭证来源 Getter S_VOUCHANNEL   	 
	 */
	public static String columnJavaTypeSvouchannel(){
		 return "String";
	}
	/**
	 *勾兑状态 Getter S_STATUS , NOT NULL   	 
	 */
	public static String columnJavaTypeSstatus(){
		 return "String";
	}
	/**
	 *备注 Getter S_REMARK   	 
	 */
	public static String columnJavaTypeSremark(){
		 return "String";
	}
	/**
	 *备注 Getter S_REMARK1   	 
	 */
	public static String columnJavaTypeSremark1(){
		 return "String";
	}
	/**
	 *备注 Getter S_REMARK2   	 
	 */
	public static String columnJavaTypeSremark2(){
		 return "String";
	}
	/**
	 *备注 Getter S_REMARK3   	 
	 */
	public static String columnJavaTypeSremark3(){
		 return "String";
	}
	/**
	 *备注 Getter S_REMARK4   	 
	 */
	public static String columnJavaTypeSremark4(){
		 return "String";
	}
	/**
	 *备注 Getter S_REMARK5   	 
	 */
	public static String columnJavaTypeSremark5(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 *主键 Getter S_SEQ, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSseq(){
		 return "VARCHAR";
	}
	/**
	 *财政机关代码 Getter S_FINORGCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfinorgcode(){
		 return "VARCHAR";
	}
	/**
	 *税票日期 Getter S_APPLYDATE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSapplydate(){
		 return "VARCHAR";
	}
	/**
	 *入库日期 Getter S_INTREDATE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSintredate(){
		 return "VARCHAR";
	}
	/**
	 *勾兑日期 Getter S_BLEND , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSblend(){
		 return "VARCHAR";
	}
	/**
	 *包流水号 Getter S_PACKNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpackno(){
		 return "VARCHAR";
	}
	/**
	 *国库代码 Getter S_TRECODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStrecode(){
		 return "VARCHAR";
	}
	/**
	 *国库名称 Getter S_TRENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStrename(){
		 return "VARCHAR";
	}
	/**
	 *征收机关代码 Getter S_TAXORGCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxorgcode(){
		 return "VARCHAR";
	}
	/**
	 *付款行行号 Getter S_PAYBNKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybnkno(){
		 return "VARCHAR";
	}
	/**
	 *交易流水号 Getter S_TRANO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStrano(){
		 return "VARCHAR";
	}
	/**
	 *原报文编号 Getter S_ORIMSGNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorimsgno(){
		 return "VARCHAR";
	}
	/**
	 *税票金额 Getter F_TRAAMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFtraamt(){
		 return "DECIMAL";
	}
	/**
	 *入库金额 Getter F_AMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFamt(){
		 return "DECIMAL";
	}
	/**
	 *付款人开户行行号 Getter S_PAYEROPNBNKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeropnbnkno(){
		 return "VARCHAR";
	}
	/**
	 *付款开户行名称 Getter S_PAYEROPBKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeropbkname(){
		 return "VARCHAR";
	}
	/**
	 *缴款单位名称 Getter S_HANDORGNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShandorgname(){
		 return "VARCHAR";
	}
	/**
	 *付款人账号 Getter S_PAYACCT   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayacct(){
		 return "VARCHAR";
	}
	/**
	 *税票号码 Getter S_TAXVOUNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxvouno(){
		 return "VARCHAR";
	}
	/**
	 *开票日期 Getter S_BILLDATE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbilldate(){
		 return "VARCHAR";
	}
	/**
	 *纳税人编号 Getter S_TAXPAYCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxpaycode(){
		 return "VARCHAR";
	}
	/**
	 *纳税人名称 Getter S_TAXPAYNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxpayname(){
		 return "VARCHAR";
	}
	/**
	 *预算种类 Getter S_BUDGETTYPE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbudgettype(){
		 return "VARCHAR";
	}
	/**
	 *调整期标志 Getter S_TRIMFLAG , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStrimflag(){
		 return "VARCHAR";
	}
	/**
	 *企业代码 Getter S_ETPCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSetpcode(){
		 return "VARCHAR";
	}
	/**
	 *企业名称 Getter S_ETPNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSetpname(){
		 return "VARCHAR";
	}
	/**
	 *企业类型 Getter S_ETPTYPE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSetptype(){
		 return "VARCHAR";
	}
	/**
	 *预算科目代码 Getter S_BDGSBTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdgsbtcode(){
		 return "VARCHAR";
	}
	/**
	 *预算科目代码 Getter S_BDGSBTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdgsbtname(){
		 return "VARCHAR";
	}
	/**
	 *限缴日期 Getter S_LIMIT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSlimit(){
		 return "VARCHAR";
	}
	/**
	 *税种代码 Getter S_TAXTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxtypecode(){
		 return "VARCHAR";
	}
	/**
	 *税种名称 Getter S_TAXKINDNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxkindname(){
		 return "VARCHAR";
	}
	/**
	 *预算级次 Getter S_BDGLEVEL , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdglevel(){
		 return "VARCHAR";
	}
	/**
	 *预算级次名称 Getter S_BDGLEVELNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbdglevelname(){
		 return "VARCHAR";
	}
	/**
	 *税款所属日期起 Getter S_TAXSTARTDATE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxstartdate(){
		 return "VARCHAR";
	}
	/**
	 *税款所属日期止 Getter S_TAXENDDATE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxenddate(){
		 return "VARCHAR";
	}
	/**
	 *辅助标志 Getter S_ASTFLAG   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSastflag(){
		 return "VARCHAR";
	}
	/**
	 *税款类型 Getter S_TAXTYPE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStaxtype(){
		 return "VARCHAR";
	}
	/**
	 *账务日期 Getter S_ACCT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSacct(){
		 return "VARCHAR";
	}
	/**
	 *处理状态 Getter S_TRASTATE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStrastate(){
		 return "VARCHAR";
	}
	/**
	 *录入员代码 Getter S_INPUTERID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSinputerid(){
		 return "VARCHAR";
	}
	/**
	 *系统更新时间 Getter TS_SYSUPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/**
	 *凭证来源 Getter S_VOUCHANNEL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvouchannel(){
		 return "VARCHAR";
	}
	/**
	 *勾兑状态 Getter S_STATUS , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSstatus(){
		 return "VARCHAR";
	}
	/**
	 *备注 Getter S_REMARK   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark(){
		 return "VARCHAR";
	}
	/**
	 *备注 Getter S_REMARK1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark1(){
		 return "VARCHAR";
	}
	/**
	 *备注 Getter S_REMARK2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark2(){
		 return "VARCHAR";
	}
	/**
	 *备注 Getter S_REMARK3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark3(){
		 return "VARCHAR";
	}
	/**
	 *备注 Getter S_REMARK4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark4(){
		 return "VARCHAR";
	}
	/**
	 *备注 Getter S_REMARK5   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark5(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 *主键 Getter S_SEQ, PK , NOT NULL   	 
	 */
	public static int columnWidthSseq(){
		 return 20;
	}
	/**
	 *财政机关代码 Getter S_FINORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSfinorgcode(){
		 return 12;
	}
	/**
	 *税票日期 Getter S_APPLYDATE , NOT NULL   	 
	 */
	public static int columnWidthSapplydate(){
		 return 8;
	}
	/**
	 *入库日期 Getter S_INTREDATE   	 
	 */
	public static int columnWidthSintredate(){
		 return 8;
	}
	/**
	 *勾兑日期 Getter S_BLEND , NOT NULL   	 
	 */
	public static int columnWidthSblend(){
		 return 8;
	}
	/**
	 *包流水号 Getter S_PACKNO , NOT NULL   	 
	 */
	public static int columnWidthSpackno(){
		 return 8;
	}
	/**
	 *国库代码 Getter S_TRECODE , NOT NULL   	 
	 */
	public static int columnWidthStrecode(){
		 return 10;
	}
	/**
	 *国库名称 Getter S_TRENAME   	 
	 */
	public static int columnWidthStrename(){
		 return 100;
	}
	/**
	 *征收机关代码 Getter S_TAXORGCODE , NOT NULL   	 
	 */
	public static int columnWidthStaxorgcode(){
		 return 12;
	}
	/**
	 *付款行行号 Getter S_PAYBNKNO   	 
	 */
	public static int columnWidthSpaybnkno(){
		 return 12;
	}
	/**
	 *交易流水号 Getter S_TRANO , NOT NULL   	 
	 */
	public static int columnWidthStrano(){
		 return 8;
	}
	/**
	 *原报文编号 Getter S_ORIMSGNO , NOT NULL   	 
	 */
	public static int columnWidthSorimsgno(){
		 return 4;
	}
	/**
	 *付款人开户行行号 Getter S_PAYEROPNBNKNO   	 
	 */
	public static int columnWidthSpayeropnbnkno(){
		 return 12;
	}
	/**
	 *付款开户行名称 Getter S_PAYEROPBKNAME   	 
	 */
	public static int columnWidthSpayeropbkname(){
		 return 60;
	}
	/**
	 *缴款单位名称 Getter S_HANDORGNAME , NOT NULL   	 
	 */
	public static int columnWidthShandorgname(){
		 return 200;
	}
	/**
	 *付款人账号 Getter S_PAYACCT   	 
	 */
	public static int columnWidthSpayacct(){
		 return 32;
	}
	/**
	 *税票号码 Getter S_TAXVOUNO , NOT NULL   	 
	 */
	public static int columnWidthStaxvouno(){
		 return 20;
	}
	/**
	 *开票日期 Getter S_BILLDATE   	 
	 */
	public static int columnWidthSbilldate(){
		 return 8;
	}
	/**
	 *纳税人编号 Getter S_TAXPAYCODE , NOT NULL   	 
	 */
	public static int columnWidthStaxpaycode(){
		 return 20;
	}
	/**
	 *纳税人名称 Getter S_TAXPAYNAME , NOT NULL   	 
	 */
	public static int columnWidthStaxpayname(){
		 return 200;
	}
	/**
	 *预算种类 Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static int columnWidthSbudgettype(){
		 return 1;
	}
	/**
	 *调整期标志 Getter S_TRIMFLAG , NOT NULL   	 
	 */
	public static int columnWidthStrimflag(){
		 return 1;
	}
	/**
	 *企业代码 Getter S_ETPCODE   	 
	 */
	public static int columnWidthSetpcode(){
		 return 20;
	}
	/**
	 *企业名称 Getter S_ETPNAME   	 
	 */
	public static int columnWidthSetpname(){
		 return 200;
	}
	/**
	 *企业类型 Getter S_ETPTYPE   	 
	 */
	public static int columnWidthSetptype(){
		 return 20;
	}
	/**
	 *预算科目代码 Getter S_BDGSBTCODE , NOT NULL   	 
	 */
	public static int columnWidthSbdgsbtcode(){
		 return 30;
	}
	/**
	 *预算科目代码 Getter S_BDGSBTNAME   	 
	 */
	public static int columnWidthSbdgsbtname(){
		 return 90;
	}
	/**
	 *限缴日期 Getter S_LIMIT , NOT NULL   	 
	 */
	public static int columnWidthSlimit(){
		 return 8;
	}
	/**
	 *税种代码 Getter S_TAXTYPECODE   	 
	 */
	public static int columnWidthStaxtypecode(){
		 return 10;
	}
	/**
	 *税种名称 Getter S_TAXKINDNAME   	 
	 */
	public static int columnWidthStaxkindname(){
		 return 60;
	}
	/**
	 *预算级次 Getter S_BDGLEVEL , NOT NULL   	 
	 */
	public static int columnWidthSbdglevel(){
		 return 1;
	}
	/**
	 *预算级次名称 Getter S_BDGLEVELNAME   	 
	 */
	public static int columnWidthSbdglevelname(){
		 return 60;
	}
	/**
	 *税款所属日期起 Getter S_TAXSTARTDATE , NOT NULL   	 
	 */
	public static int columnWidthStaxstartdate(){
		 return 8;
	}
	/**
	 *税款所属日期止 Getter S_TAXENDDATE , NOT NULL   	 
	 */
	public static int columnWidthStaxenddate(){
		 return 8;
	}
	/**
	 *辅助标志 Getter S_ASTFLAG   	 
	 */
	public static int columnWidthSastflag(){
		 return 35;
	}
	/**
	 *税款类型 Getter S_TAXTYPE , NOT NULL   	 
	 */
	public static int columnWidthStaxtype(){
		 return 1;
	}
	/**
	 *账务日期 Getter S_ACCT , NOT NULL   	 
	 */
	public static int columnWidthSacct(){
		 return 8;
	}
	/**
	 *处理状态 Getter S_TRASTATE , NOT NULL   	 
	 */
	public static int columnWidthStrastate(){
		 return 5;
	}
	/**
	 *录入员代码 Getter S_INPUTERID   	 
	 */
	public static int columnWidthSinputerid(){
		 return 18;
	}
	/**
	 *凭证来源 Getter S_VOUCHANNEL   	 
	 */
	public static int columnWidthSvouchannel(){
		 return 10;
	}
	/**
	 *勾兑状态 Getter S_STATUS , NOT NULL   	 
	 */
	public static int columnWidthSstatus(){
		 return 5;
	}
	/**
	 *备注 Getter S_REMARK   	 
	 */
	public static int columnWidthSremark(){
		 return 60;
	}
	/**
	 *备注 Getter S_REMARK1   	 
	 */
	public static int columnWidthSremark1(){
		 return 60;
	}
	/**
	 *备注 Getter S_REMARK2   	 
	 */
	public static int columnWidthSremark2(){
		 return 60;
	}
	/**
	 *备注 Getter S_REMARK3   	 
	 */
	public static int columnWidthSremark3(){
		 return 60;
	}
	/**
	 *备注 Getter S_REMARK4   	 
	 */
	public static int columnWidthSremark4(){
		 return 60;
	}
	/**
	 *备注 Getter S_REMARK5   	 
	 */
	public static int columnWidthSremark5(){
		 return 60;
	}
}