      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TV_PAYRECKBANKBACK_SX</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:03 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TvPayreckbankbackSxInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TV_PAYRECKBANKBACK_SX";
	
	/**
	 * column S_BOOKORGCODE
	 */
	public static String S_BOOKORGCODE ="S_BOOKORGCODE";
	/**
	 * column D_ENTRUSTDATE
	 */
	public static String D_ENTRUSTDATE ="D_ENTRUSTDATE";
	/**
	 * column S_PACKNO
	 */
	public static String S_PACKNO ="S_PACKNO";
	/**
	 * column S_AGENTBNKCODE
	 */
	public static String S_AGENTBNKCODE ="S_AGENTBNKCODE";
	/**
	 * column S_TRANO
	 */
	public static String S_TRANO ="S_TRANO";
	/**
	 * column I_VOUSRLNO
	 */
	public static String I_VOUSRLNO ="I_VOUSRLNO";
	/**
	 * column S_VOUNO
	 */
	public static String S_VOUNO ="S_VOUNO";
	/**
	 * column D_VOUDATE
	 */
	public static String D_VOUDATE ="D_VOUDATE";
	/**
	 * column S_FINORGCODE
	 */
	public static String S_FINORGCODE ="S_FINORGCODE";
	/**
	 * column S_TRECODE
	 */
	public static String S_TRECODE ="S_TRECODE";
	/**
	 * column S_ORITRANO
	 */
	public static String S_ORITRANO ="S_ORITRANO";
	/**
	 * column D_ORIENTRUSTDATE
	 */
	public static String D_ORIENTRUSTDATE ="D_ORIENTRUSTDATE";
	/**
	 * column S_ORIVOUNO
	 */
	public static String S_ORIVOUNO ="S_ORIVOUNO";
	/**
	 * column D_ORIVOUDATE
	 */
	public static String D_ORIVOUDATE ="D_ORIVOUDATE";
	/**
	 * column S_PAYERACCT
	 */
	public static String S_PAYERACCT ="S_PAYERACCT";
	/**
	 * column S_PAYERNAME
	 */
	public static String S_PAYERNAME ="S_PAYERNAME";
	/**
	 * column S_PAYEEACCT
	 */
	public static String S_PAYEEACCT ="S_PAYEEACCT";
	/**
	 * column S_PAYEENAME
	 */
	public static String S_PAYEENAME ="S_PAYEENAME";
	/**
	 * column S_PAYDICTATENO
	 */
	public static String S_PAYDICTATENO ="S_PAYDICTATENO";
	/**
	 * column S_PAYMSGNO
	 */
	public static String S_PAYMSGNO ="S_PAYMSGNO";
	/**
	 * column D_PAYENTRUSTDATE
	 */
	public static String D_PAYENTRUSTDATE ="D_PAYENTRUSTDATE";
	/**
	 * column S_PAYSNDBNKNO
	 */
	public static String S_PAYSNDBNKNO ="S_PAYSNDBNKNO";
	/**
	 * column S_BUDGETTYPE
	 */
	public static String S_BUDGETTYPE ="S_BUDGETTYPE";
	/**
	 * column S_TRIMSIGN
	 */
	public static String S_TRIMSIGN ="S_TRIMSIGN";
	/**
	 * column S_OFYEAR
	 */
	public static String S_OFYEAR ="S_OFYEAR";
	/**
	 * column F_AMT
	 */
	public static String F_AMT ="F_AMT";
	/**
	 * column I_STATINFNUM
	 */
	public static String I_STATINFNUM ="I_STATINFNUM";
	/**
	 * column S_STATUS
	 */
	public static String S_STATUS ="S_STATUS";
	/**
	 * column S_ADDWORD
	 */
	public static String S_ADDWORD ="S_ADDWORD";
	/**
	 * column D_ACCEPTDATE
	 */
	public static String D_ACCEPTDATE ="D_ACCEPTDATE";
	/**
	 * column TS_UPDATE
	 */
	public static String TS_UPDATE ="TS_UPDATE";
	/**
	 * column S_PAYMODE
	 */
	public static String S_PAYMODE ="S_PAYMODE";
	/**
	 * column S_FILENAME
	 */
	public static String S_FILENAME ="S_FILENAME";
	/**
	 * column S_ID
	 */
	public static String S_ID ="S_ID";
	/**
	 * column S_BGTTYPECODE
	 */
	public static String S_BGTTYPECODE ="S_BGTTYPECODE";
	/**
	 * column S_BGTTYPENAME
	 */
	public static String S_BGTTYPENAME ="S_BGTTYPENAME";
	/**
	 * column S_FUNDTYPECODE
	 */
	public static String S_FUNDTYPECODE ="S_FUNDTYPECODE";
	/**
	 * column S_FUNDTYPENAME
	 */
	public static String S_FUNDTYPENAME ="S_FUNDTYPENAME";
	/**
	 * column S_PAYTYPECODE
	 */
	public static String S_PAYTYPECODE ="S_PAYTYPECODE";
	/**
	 * column S_PAYTYPENAME
	 */
	public static String S_PAYTYPENAME ="S_PAYTYPENAME";
	/**
	 * column S_PAYBANKNAME
	 */
	public static String S_PAYBANKNAME ="S_PAYBANKNAME";
	/**
	 * column S_XPAYSNDBNKNO
	 */
	public static String S_XPAYSNDBNKNO ="S_XPAYSNDBNKNO";
	/**
	 * column S_XPAYAMT
	 */
	public static String S_XPAYAMT ="S_XPAYAMT";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_XCLEARDATE
	 */
	public static String S_XCLEARDATE ="S_XCLEARDATE";
	/**
	 * column S_AGENTACCTBANKNAME
	 */
	public static String S_AGENTACCTBANKNAME ="S_AGENTACCTBANKNAME";
	/**
	 * column S_CLEARACCTBANKNAME
	 */
	public static String S_CLEARACCTBANKNAME ="S_CLEARACCTBANKNAME";
	/**
	 * column S_REMARK
	 */
	public static String S_REMARK ="S_REMARK";
	/**
	 * column S_MONEYCORPCODE
	 */
	public static String S_MONEYCORPCODE ="S_MONEYCORPCODE";
	/**
	 * column S_ADMDIVCODE
	 */
	public static String S_ADMDIVCODE ="S_ADMDIVCODE";
	/**
	 * column S_VTCODE
	 */
	public static String S_VTCODE ="S_VTCODE";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[52];        
        columnNames[0]="S_BOOKORGCODE";
        columnNames[1]="D_ENTRUSTDATE";
        columnNames[2]="S_PACKNO";
        columnNames[3]="S_AGENTBNKCODE";
        columnNames[4]="S_TRANO";
        columnNames[5]="I_VOUSRLNO";
        columnNames[6]="S_VOUNO";
        columnNames[7]="D_VOUDATE";
        columnNames[8]="S_FINORGCODE";
        columnNames[9]="S_TRECODE";
        columnNames[10]="S_ORITRANO";
        columnNames[11]="D_ORIENTRUSTDATE";
        columnNames[12]="S_ORIVOUNO";
        columnNames[13]="D_ORIVOUDATE";
        columnNames[14]="S_PAYERACCT";
        columnNames[15]="S_PAYERNAME";
        columnNames[16]="S_PAYEEACCT";
        columnNames[17]="S_PAYEENAME";
        columnNames[18]="S_PAYDICTATENO";
        columnNames[19]="S_PAYMSGNO";
        columnNames[20]="D_PAYENTRUSTDATE";
        columnNames[21]="S_PAYSNDBNKNO";
        columnNames[22]="S_BUDGETTYPE";
        columnNames[23]="S_TRIMSIGN";
        columnNames[24]="S_OFYEAR";
        columnNames[25]="F_AMT";
        columnNames[26]="I_STATINFNUM";
        columnNames[27]="S_STATUS";
        columnNames[28]="S_ADDWORD";
        columnNames[29]="D_ACCEPTDATE";
        columnNames[30]="TS_UPDATE";
        columnNames[31]="S_PAYMODE";
        columnNames[32]="S_FILENAME";
        columnNames[33]="S_ID";
        columnNames[34]="S_BGTTYPECODE";
        columnNames[35]="S_BGTTYPENAME";
        columnNames[36]="S_FUNDTYPECODE";
        columnNames[37]="S_FUNDTYPENAME";
        columnNames[38]="S_PAYTYPECODE";
        columnNames[39]="S_PAYTYPENAME";
        columnNames[40]="S_PAYBANKNAME";
        columnNames[41]="S_XPAYSNDBNKNO";
        columnNames[42]="S_XPAYAMT";
        columnNames[43]="S_HOLD1";
        columnNames[44]="S_HOLD2";
        columnNames[45]="S_XCLEARDATE";
        columnNames[46]="S_AGENTACCTBANKNAME";
        columnNames[47]="S_CLEARACCTBANKNAME";
        columnNames[48]="S_REMARK";
        columnNames[49]="S_MONEYCORPCODE";
        columnNames[50]="S_ADMDIVCODE";
        columnNames[51]="S_VTCODE";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_BOOKORGCODE, PK , NOT NULL   	 
	 */
	public static String columnSbookorgcode(){
		 return S_BOOKORGCODE;
	}
	/**
	 * Getter D_ENTRUSTDATE, PK , NOT NULL   	 
	 */
	public static String columnDentrustdate(){
		 return D_ENTRUSTDATE;
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 */
	public static String columnSpackno(){
		 return S_PACKNO;
	}
	/**
	 * Getter S_AGENTBNKCODE, PK , NOT NULL   	 
	 */
	public static String columnSagentbnkcode(){
		 return S_AGENTBNKCODE;
	}
	/**
	 * Getter S_TRANO, PK , NOT NULL   	 
	 */
	public static String columnStrano(){
		 return S_TRANO;
	}
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnIvousrlno(){
		 return I_VOUSRLNO;
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static String columnSvouno(){
		 return S_VOUNO;
	}
	/**
	 * Getter D_VOUDATE , NOT NULL   	 
	 */
	public static String columnDvoudate(){
		 return D_VOUDATE;
	}
	/**
	 * Getter S_FINORGCODE , NOT NULL   	 
	 */
	public static String columnSfinorgcode(){
		 return S_FINORGCODE;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnStrecode(){
		 return S_TRECODE;
	}
	/**
	 * Getter S_ORITRANO   	 
	 */
	public static String columnSoritrano(){
		 return S_ORITRANO;
	}
	/**
	 * Getter D_ORIENTRUSTDATE   	 
	 */
	public static String columnDorientrustdate(){
		 return D_ORIENTRUSTDATE;
	}
	/**
	 * Getter S_ORIVOUNO , NOT NULL   	 
	 */
	public static String columnSorivouno(){
		 return S_ORIVOUNO;
	}
	/**
	 * Getter D_ORIVOUDATE , NOT NULL   	 
	 */
	public static String columnDorivoudate(){
		 return D_ORIVOUDATE;
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static String columnSpayeracct(){
		 return S_PAYERACCT;
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 */
	public static String columnSpayername(){
		 return S_PAYERNAME;
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 */
	public static String columnSpayeeacct(){
		 return S_PAYEEACCT;
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 */
	public static String columnSpayeename(){
		 return S_PAYEENAME;
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 */
	public static String columnSpaydictateno(){
		 return S_PAYDICTATENO;
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 */
	public static String columnSpaymsgno(){
		 return S_PAYMSGNO;
	}
	/**
	 * Getter D_PAYENTRUSTDATE   	 
	 */
	public static String columnDpayentrustdate(){
		 return D_PAYENTRUSTDATE;
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 */
	public static String columnSpaysndbnkno(){
		 return S_PAYSNDBNKNO;
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnSbudgettype(){
		 return S_BUDGETTYPE;
	}
	/**
	 * Getter S_TRIMSIGN , NOT NULL   	 
	 */
	public static String columnStrimsign(){
		 return S_TRIMSIGN;
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnSofyear(){
		 return S_OFYEAR;
	}
	/**
	 * Getter F_AMT , NOT NULL   	 
	 */
	public static String columnFamt(){
		 return F_AMT;
	}
	/**
	 * Getter I_STATINFNUM , NOT NULL   	 
	 */
	public static String columnIstatinfnum(){
		 return I_STATINFNUM;
	}
	/**
	 * Getter S_STATUS   	 
	 */
	public static String columnSstatus(){
		 return S_STATUS;
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static String columnSaddword(){
		 return S_ADDWORD;
	}
	/**
	 * Getter D_ACCEPTDATE   	 
	 */
	public static String columnDacceptdate(){
		 return D_ACCEPTDATE;
	}
	/**
	 * Getter TS_UPDATE , NOT NULL   	 
	 */
	public static String columnTsupdate(){
		 return TS_UPDATE;
	}
	/**
	 * Getter S_PAYMODE   	 
	 */
	public static String columnSpaymode(){
		 return S_PAYMODE;
	}
	/**
	 * Getter S_FILENAME   	 
	 */
	public static String columnSfilename(){
		 return S_FILENAME;
	}
	/**
	 * Getter S_ID   	 
	 */
	public static String columnSid(){
		 return S_ID;
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static String columnSbgttypecode(){
		 return S_BGTTYPECODE;
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static String columnSbgttypename(){
		 return S_BGTTYPENAME;
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static String columnSfundtypecode(){
		 return S_FUNDTYPECODE;
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static String columnSfundtypename(){
		 return S_FUNDTYPENAME;
	}
	/**
	 * Getter S_PAYTYPECODE   	 
	 */
	public static String columnSpaytypecode(){
		 return S_PAYTYPECODE;
	}
	/**
	 * Getter S_PAYTYPENAME   	 
	 */
	public static String columnSpaytypename(){
		 return S_PAYTYPENAME;
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static String columnSpaybankname(){
		 return S_PAYBANKNAME;
	}
	/**
	 * Getter S_XPAYSNDBNKNO   	 
	 */
	public static String columnSxpaysndbnkno(){
		 return S_XPAYSNDBNKNO;
	}
	/**
	 * Getter S_XPAYAMT   	 
	 */
	public static String columnSxpayamt(){
		 return S_XPAYAMT;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 * Getter S_XCLEARDATE   	 
	 */
	public static String columnSxcleardate(){
		 return S_XCLEARDATE;
	}
	/**
	 * Getter S_AGENTACCTBANKNAME   	 
	 */
	public static String columnSagentacctbankname(){
		 return S_AGENTACCTBANKNAME;
	}
	/**
	 * Getter S_CLEARACCTBANKNAME   	 
	 */
	public static String columnSclearacctbankname(){
		 return S_CLEARACCTBANKNAME;
	}
	/**
	 * Getter S_REMARK   	 
	 */
	public static String columnSremark(){
		 return S_REMARK;
	}
	/**
	 * Getter S_MONEYCORPCODE   	 
	 */
	public static String columnSmoneycorpcode(){
		 return S_MONEYCORPCODE;
	}
	/**
	 * Getter S_ADMDIVCODE   	 
	 */
	public static String columnSadmdivcode(){
		 return S_ADMDIVCODE;
	}
	/**
	 * Getter S_VTCODE   	 
	 */
	public static String columnSvtcode(){
		 return S_VTCODE;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_BOOKORGCODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSbookorgcode(){
		 return "String";
	}
	/**
	 * Getter D_ENTRUSTDATE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeDentrustdate(){
		 return "Date";
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackno(){
		 return "String";
	}
	/**
	 * Getter S_AGENTBNKCODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSagentbnkcode(){
		 return "String";
	}
	/**
	 * Getter S_TRANO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeStrano(){
		 return "String";
	}
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeIvousrlno(){
		 return "Long";
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSvouno(){
		 return "String";
	}
	/**
	 * Getter D_VOUDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeDvoudate(){
		 return "Date";
	}
	/**
	 * Getter S_FINORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfinorgcode(){
		 return "String";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static String columnJavaTypeStrecode(){
		 return "String";
	}
	/**
	 * Getter S_ORITRANO   	 
	 */
	public static String columnJavaTypeSoritrano(){
		 return "String";
	}
	/**
	 * Getter D_ORIENTRUSTDATE   	 
	 */
	public static String columnJavaTypeDorientrustdate(){
		 return "Date";
	}
	/**
	 * Getter S_ORIVOUNO , NOT NULL   	 
	 */
	public static String columnJavaTypeSorivouno(){
		 return "String";
	}
	/**
	 * Getter D_ORIVOUDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeDorivoudate(){
		 return "Date";
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeracct(){
		 return "String";
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayername(){
		 return "String";
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeeacct(){
		 return "String";
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 */
	public static String columnJavaTypeSpayeename(){
		 return "String";
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 */
	public static String columnJavaTypeSpaydictateno(){
		 return "String";
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 */
	public static String columnJavaTypeSpaymsgno(){
		 return "String";
	}
	/**
	 * Getter D_PAYENTRUSTDATE   	 
	 */
	public static String columnJavaTypeDpayentrustdate(){
		 return "Date";
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 */
	public static String columnJavaTypeSpaysndbnkno(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSbudgettype(){
		 return "String";
	}
	/**
	 * Getter S_TRIMSIGN , NOT NULL   	 
	 */
	public static String columnJavaTypeStrimsign(){
		 return "String";
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static String columnJavaTypeSofyear(){
		 return "String";
	}
	/**
	 * Getter F_AMT , NOT NULL   	 
	 */
	public static String columnJavaTypeFamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter I_STATINFNUM , NOT NULL   	 
	 */
	public static String columnJavaTypeIstatinfnum(){
		 return "Integer";
	}
	/**
	 * Getter S_STATUS   	 
	 */
	public static String columnJavaTypeSstatus(){
		 return "String";
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static String columnJavaTypeSaddword(){
		 return "String";
	}
	/**
	 * Getter D_ACCEPTDATE   	 
	 */
	public static String columnJavaTypeDacceptdate(){
		 return "Date";
	}
	/**
	 * Getter TS_UPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTsupdate(){
		 return "Timestamp";
	}
	/**
	 * Getter S_PAYMODE   	 
	 */
	public static String columnJavaTypeSpaymode(){
		 return "String";
	}
	/**
	 * Getter S_FILENAME   	 
	 */
	public static String columnJavaTypeSfilename(){
		 return "String";
	}
	/**
	 * Getter S_ID   	 
	 */
	public static String columnJavaTypeSid(){
		 return "String";
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static String columnJavaTypeSbgttypecode(){
		 return "String";
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static String columnJavaTypeSbgttypename(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static String columnJavaTypeSfundtypecode(){
		 return "String";
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static String columnJavaTypeSfundtypename(){
		 return "String";
	}
	/**
	 * Getter S_PAYTYPECODE   	 
	 */
	public static String columnJavaTypeSpaytypecode(){
		 return "String";
	}
	/**
	 * Getter S_PAYTYPENAME   	 
	 */
	public static String columnJavaTypeSpaytypename(){
		 return "String";
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static String columnJavaTypeSpaybankname(){
		 return "String";
	}
	/**
	 * Getter S_XPAYSNDBNKNO   	 
	 */
	public static String columnJavaTypeSxpaysndbnkno(){
		 return "String";
	}
	/**
	 * Getter S_XPAYAMT   	 
	 */
	public static String columnJavaTypeSxpayamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 * Getter S_XCLEARDATE   	 
	 */
	public static String columnJavaTypeSxcleardate(){
		 return "Date";
	}
	/**
	 * Getter S_AGENTACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSagentacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_CLEARACCTBANKNAME   	 
	 */
	public static String columnJavaTypeSclearacctbankname(){
		 return "String";
	}
	/**
	 * Getter S_REMARK   	 
	 */
	public static String columnJavaTypeSremark(){
		 return "String";
	}
	/**
	 * Getter S_MONEYCORPCODE   	 
	 */
	public static String columnJavaTypeSmoneycorpcode(){
		 return "String";
	}
	/**
	 * Getter S_ADMDIVCODE   	 
	 */
	public static String columnJavaTypeSadmdivcode(){
		 return "String";
	}
	/**
	 * Getter S_VTCODE   	 
	 */
	public static String columnJavaTypeSvtcode(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_BOOKORGCODE, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbookorgcode(){
		 return "CHARACTER";
	}
	/**
	 * Getter D_ENTRUSTDATE, PK , NOT NULL   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDentrustdate(){
		 return "DATE";
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpackno(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_AGENTBNKCODE, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSagentbnkcode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TRANO, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrano(){
		 return "CHARACTER";
	}
	/**
	 * Getter I_VOUSRLNO, PK , NOT NULL   	 
	 * columnType is BIGINT
	 */
	public static String columnDatabaseTypeIvousrlno(){
		 return "BIGINT";
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvouno(){
		 return "VARCHAR";
	}
	/**
	 * Getter D_VOUDATE , NOT NULL   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDvoudate(){
		 return "DATE";
	}
	/**
	 * Getter S_FINORGCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfinorgcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrecode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ORITRANO   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSoritrano(){
		 return "CHARACTER";
	}
	/**
	 * Getter D_ORIENTRUSTDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDorientrustdate(){
		 return "DATE";
	}
	/**
	 * Getter S_ORIVOUNO , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSorivouno(){
		 return "VARCHAR";
	}
	/**
	 * Getter D_ORIVOUDATE , NOT NULL   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDorivoudate(){
		 return "DATE";
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeracct(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayername(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeeacct(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpayeename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpaydictateno(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaymsgno(){
		 return "VARCHAR";
	}
	/**
	 * Getter D_PAYENTRUSTDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDpayentrustdate(){
		 return "DATE";
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpaysndbnkno(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbudgettype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_TRIMSIGN , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeStrimsign(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSofyear(){
		 return "CHARACTER";
	}
	/**
	 * Getter F_AMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter I_STATINFNUM , NOT NULL   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeIstatinfnum(){
		 return "INTEGER";
	}
	/**
	 * Getter S_STATUS   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSstatus(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ADDWORD   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSaddword(){
		 return "VARCHAR";
	}
	/**
	 * Getter D_ACCEPTDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeDacceptdate(){
		 return "DATE";
	}
	/**
	 * Getter TS_UPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTsupdate(){
		 return "TIMESTAMP";
	}
	/**
	 * Getter S_PAYMODE   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpaymode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_FILENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfilename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ID   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSid(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbgttypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfundtypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYTYPECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaytypecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYTYPENAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaytypename(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSpaybankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XPAYSNDBNKNO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSxpaysndbnkno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XPAYAMT   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeSxpayamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_XCLEARDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeSxcleardate(){
		 return "DATE";
	}
	/**
	 * Getter S_AGENTACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSagentacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_CLEARACCTBANKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSclearacctbankname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_REMARK   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSremark(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_MONEYCORPCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSmoneycorpcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_ADMDIVCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSadmdivcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_VTCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSvtcode(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_BOOKORGCODE, PK , NOT NULL   	 
	 */
	public static int columnWidthSbookorgcode(){
		 return 12;
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 */
	public static int columnWidthSpackno(){
		 return 8;
	}
	/**
	 * Getter S_AGENTBNKCODE, PK , NOT NULL   	 
	 */
	public static int columnWidthSagentbnkcode(){
		 return 12;
	}
	/**
	 * Getter S_TRANO, PK , NOT NULL   	 
	 */
	public static int columnWidthStrano(){
		 return 8;
	}
	/**
	 * Getter S_VOUNO , NOT NULL   	 
	 */
	public static int columnWidthSvouno(){
		 return 20;
	}
	/**
	 * Getter S_FINORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSfinorgcode(){
		 return 12;
	}
	/**
	 * Getter S_TRECODE , NOT NULL   	 
	 */
	public static int columnWidthStrecode(){
		 return 10;
	}
	/**
	 * Getter S_ORITRANO   	 
	 */
	public static int columnWidthSoritrano(){
		 return 8;
	}
	/**
	 * Getter S_ORIVOUNO , NOT NULL   	 
	 */
	public static int columnWidthSorivouno(){
		 return 20;
	}
	/**
	 * Getter S_PAYERACCT , NOT NULL   	 
	 */
	public static int columnWidthSpayeracct(){
		 return 32;
	}
	/**
	 * Getter S_PAYERNAME , NOT NULL   	 
	 */
	public static int columnWidthSpayername(){
		 return 60;
	}
	/**
	 * Getter S_PAYEEACCT , NOT NULL   	 
	 */
	public static int columnWidthSpayeeacct(){
		 return 32;
	}
	/**
	 * Getter S_PAYEENAME , NOT NULL   	 
	 */
	public static int columnWidthSpayeename(){
		 return 60;
	}
	/**
	 * Getter S_PAYDICTATENO   	 
	 */
	public static int columnWidthSpaydictateno(){
		 return 8;
	}
	/**
	 * Getter S_PAYMSGNO   	 
	 */
	public static int columnWidthSpaymsgno(){
		 return 10;
	}
	/**
	 * Getter S_PAYSNDBNKNO   	 
	 */
	public static int columnWidthSpaysndbnkno(){
		 return 12;
	}
	/**
	 * Getter S_BUDGETTYPE , NOT NULL   	 
	 */
	public static int columnWidthSbudgettype(){
		 return 1;
	}
	/**
	 * Getter S_TRIMSIGN , NOT NULL   	 
	 */
	public static int columnWidthStrimsign(){
		 return 1;
	}
	/**
	 * Getter S_OFYEAR , NOT NULL   	 
	 */
	public static int columnWidthSofyear(){
		 return 4;
	}
	/**
	 * Getter S_STATUS   	 
	 */
	public static int columnWidthSstatus(){
		 return 5;
	}
	/**
	 * Getter S_ADDWORD   	 
	 */
	public static int columnWidthSaddword(){
		 return 60;
	}
	/**
	 * Getter S_PAYMODE   	 
	 */
	public static int columnWidthSpaymode(){
		 return 1;
	}
	/**
	 * Getter S_FILENAME   	 
	 */
	public static int columnWidthSfilename(){
		 return 100;
	}
	/**
	 * Getter S_ID   	 
	 */
	public static int columnWidthSid(){
		 return 38;
	}
	/**
	 * Getter S_BGTTYPECODE   	 
	 */
	public static int columnWidthSbgttypecode(){
		 return 42;
	}
	/**
	 * Getter S_BGTTYPENAME   	 
	 */
	public static int columnWidthSbgttypename(){
		 return 60;
	}
	/**
	 * Getter S_FUNDTYPECODE   	 
	 */
	public static int columnWidthSfundtypecode(){
		 return 42;
	}
	/**
	 * Getter S_FUNDTYPENAME   	 
	 */
	public static int columnWidthSfundtypename(){
		 return 60;
	}
	/**
	 * Getter S_PAYTYPECODE   	 
	 */
	public static int columnWidthSpaytypecode(){
		 return 42;
	}
	/**
	 * Getter S_PAYTYPENAME   	 
	 */
	public static int columnWidthSpaytypename(){
		 return 60;
	}
	/**
	 * Getter S_PAYBANKNAME   	 
	 */
	public static int columnWidthSpaybankname(){
		 return 60;
	}
	/**
	 * Getter S_XPAYSNDBNKNO   	 
	 */
	public static int columnWidthSxpaysndbnkno(){
		 return 12;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 * Getter S_AGENTACCTBANKNAME   	 
	 */
	public static int columnWidthSagentacctbankname(){
		 return 60;
	}
	/**
	 * Getter S_CLEARACCTBANKNAME   	 
	 */
	public static int columnWidthSclearacctbankname(){
		 return 60;
	}
	/**
	 * Getter S_REMARK   	 
	 */
	public static int columnWidthSremark(){
		 return 200;
	}
	/**
	 * Getter S_MONEYCORPCODE   	 
	 */
	public static int columnWidthSmoneycorpcode(){
		 return 14;
	}
	/**
	 * Getter S_ADMDIVCODE   	 
	 */
	public static int columnWidthSadmdivcode(){
		 return 9;
	}
	/**
	 * Getter S_VTCODE   	 
	 */
	public static int columnWidthSvtcode(){
		 return 4;
	}
}