      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TV_PAYOUTBACKMSG_SUB</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:03 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TvPayoutbackmsgSubInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TV_PAYOUTBACKMSG_SUB";
	
	/**
	 * column S_BIZNO
	 */
	public static String S_BIZNO ="S_BIZNO";
	/**
	 * column S_SEQNO
	 */
	public static String S_SEQNO ="S_SEQNO";
	/**
	 * column S_ECNOMICSUBJECTCODE
	 */
	public static String S_ECNOMICSUBJECTCODE ="S_ECNOMICSUBJECTCODE";
	/**
	 * column S_FUNSUBJECTCODE
	 */
	public static String S_FUNSUBJECTCODE ="S_FUNSUBJECTCODE";
	/**
	 * column S_FUNSUBJECTNAME
	 */
	public static String S_FUNSUBJECTNAME ="S_FUNSUBJECTNAME";
	/**
	 * column S_BUDGETPRJCODE
	 */
	public static String S_BUDGETPRJCODE ="S_BUDGETPRJCODE";
	/**
	 * column N_MONEY
	 */
	public static String N_MONEY ="N_MONEY";
	/**
	 * column TS_SYSUPDATE
	 */
	public static String TS_SYSUPDATE ="TS_SYSUPDATE";
	/**
	 * column S_HOLD1
	 */
	public static String S_HOLD1 ="S_HOLD1";
	/**
	 * column S_HOLD2
	 */
	public static String S_HOLD2 ="S_HOLD2";
	/**
	 * column S_HOLD3
	 */
	public static String S_HOLD3 ="S_HOLD3";
	/**
	 * column S_HOLD4
	 */
	public static String S_HOLD4 ="S_HOLD4";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[12];        
        columnNames[0]="S_BIZNO";
        columnNames[1]="S_SEQNO";
        columnNames[2]="S_ECNOMICSUBJECTCODE";
        columnNames[3]="S_FUNSUBJECTCODE";
        columnNames[4]="S_FUNSUBJECTNAME";
        columnNames[5]="S_BUDGETPRJCODE";
        columnNames[6]="N_MONEY";
        columnNames[7]="TS_SYSUPDATE";
        columnNames[8]="S_HOLD1";
        columnNames[9]="S_HOLD2";
        columnNames[10]="S_HOLD3";
        columnNames[11]="S_HOLD4";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 */
	public static String columnSbizno(){
		 return S_BIZNO;
	}
	/**
	 * Getter S_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnSseqno(){
		 return S_SEQNO;
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static String columnSecnomicsubjectcode(){
		 return S_ECNOMICSUBJECTCODE;
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnSfunsubjectcode(){
		 return S_FUNSUBJECTCODE;
	}
	/**
	 * Getter S_FUNSUBJECTNAME   	 
	 */
	public static String columnSfunsubjectname(){
		 return S_FUNSUBJECTNAME;
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 */
	public static String columnSbudgetprjcode(){
		 return S_BUDGETPRJCODE;
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnNmoney(){
		 return N_MONEY;
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnTssysupdate(){
		 return TS_SYSUPDATE;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnShold1(){
		 return S_HOLD1;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnShold2(){
		 return S_HOLD2;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnShold3(){
		 return S_HOLD3;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnShold4(){
		 return S_HOLD4;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSbizno(){
		 return "String";
	}
	/**
	 * Getter S_SEQNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSseqno(){
		 return "Integer";
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static String columnJavaTypeSecnomicsubjectcode(){
		 return "String";
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSfunsubjectcode(){
		 return "String";
	}
	/**
	 * Getter S_FUNSUBJECTNAME   	 
	 */
	public static String columnJavaTypeSfunsubjectname(){
		 return "String";
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 */
	public static String columnJavaTypeSbudgetprjcode(){
		 return "String";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 */
	public static String columnJavaTypeNmoney(){
		 return "BigDecimal";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeTssysupdate(){
		 return "Timestamp";
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static String columnJavaTypeShold1(){
		 return "String";
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static String columnJavaTypeShold2(){
		 return "String";
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static String columnJavaTypeShold3(){
		 return "String";
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static String columnJavaTypeShold4(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbizno(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_SEQNO, PK , NOT NULL   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeSseqno(){
		 return "INTEGER";
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSecnomicsubjectcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfunsubjectcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_FUNSUBJECTNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSfunsubjectname(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeSbudgetprjcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter N_MONEY , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeNmoney(){
		 return "DECIMAL";
	}
	/**
	 * Getter TS_SYSUPDATE , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeTssysupdate(){
		 return "TIMESTAMP";
	}
	/**
	 * Getter S_HOLD1   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold1(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD2   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold2(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD3   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold3(){
		 return "VARCHAR";
	}
	/**
	 * Getter S_HOLD4   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeShold4(){
		 return "VARCHAR";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_BIZNO, PK , NOT NULL   	 
	 */
	public static int columnWidthSbizno(){
		 return 20;
	}
	/**
	 * Getter S_ECNOMICSUBJECTCODE   	 
	 */
	public static int columnWidthSecnomicsubjectcode(){
		 return 30;
	}
	/**
	 * Getter S_FUNSUBJECTCODE , NOT NULL   	 
	 */
	public static int columnWidthSfunsubjectcode(){
		 return 30;
	}
	/**
	 * Getter S_FUNSUBJECTNAME   	 
	 */
	public static int columnWidthSfunsubjectname(){
		 return 30;
	}
	/**
	 * Getter S_BUDGETPRJCODE   	 
	 */
	public static int columnWidthSbudgetprjcode(){
		 return 30;
	}
	/**
	 * Getter S_HOLD1   	 
	 */
	public static int columnWidthShold1(){
		 return 42;
	}
	/**
	 * Getter S_HOLD2   	 
	 */
	public static int columnWidthShold2(){
		 return 42;
	}
	/**
	 * Getter S_HOLD3   	 
	 */
	public static int columnWidthShold3(){
		 return 42;
	}
	/**
	 * Getter S_HOLD4   	 
	 */
	public static int columnWidthShold4(){
		 return 42;
	}
}