      

package com.cfcc.itfe.persistence.info;

/**
 * <p>Title: Information of table: TV_TIPS_3201</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2005</p>
 * <p>Company: CFCC </p>
 * <p>Generation Time: 2014-12-25 15:29:04 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2007-05-24 16:30:00 
 *
 * @author win7
 */

public class TvTips3201Info
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "TV_TIPS_3201";
	
	/**
	 * column S_ORGCODE
	 */
	public static String S_ORGCODE ="S_ORGCODE";
	/**
	 * column S_CHKDATE
	 */
	public static String S_CHKDATE ="S_CHKDATE";
	/**
	 * column S_PACKNO
	 */
	public static String S_PACKNO ="S_PACKNO";
	/**
	 * column S_BILLORG
	 */
	public static String S_BILLORG ="S_BILLORG";
	/**
	 * column S_ORGTYPE
	 */
	public static String S_ORGTYPE ="S_ORGTYPE";
	/**
	 * column S_ORIMSGNO
	 */
	public static String S_ORIMSGNO ="S_ORIMSGNO";
	/**
	 * column S_ORISENDORGCODE
	 */
	public static String S_ORISENDORGCODE ="S_ORISENDORGCODE";
	/**
	 * column S_ORIENTRUSTDATE
	 */
	public static String S_ORIENTRUSTDATE ="S_ORIENTRUSTDATE";
	/**
	 * column S_ORIPACKNO
	 */
	public static String S_ORIPACKNO ="S_ORIPACKNO";
	/**
	 * column I_ALLNUM
	 */
	public static String I_ALLNUM ="I_ALLNUM";
	/**
	 * column F_ALLAMT
	 */
	public static String F_ALLAMT ="F_ALLAMT";
	/**
	 * column S_CHECK
	 */
	public static String S_CHECK ="S_CHECK";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[12];        
        columnNames[0]="S_ORGCODE";
        columnNames[1]="S_CHKDATE";
        columnNames[2]="S_PACKNO";
        columnNames[3]="S_BILLORG";
        columnNames[4]="S_ORGTYPE";
        columnNames[5]="S_ORIMSGNO";
        columnNames[6]="S_ORISENDORGCODE";
        columnNames[7]="S_ORIENTRUSTDATE";
        columnNames[8]="S_ORIPACKNO";
        columnNames[9]="I_ALLNUM";
        columnNames[10]="F_ALLAMT";
        columnNames[11]="S_CHECK";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static String columnSorgcode(){
		 return S_ORGCODE;
	}
	/**
	 * Getter S_CHKDATE, PK , NOT NULL   	 
	 */
	public static String columnSchkdate(){
		 return S_CHKDATE;
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 */
	public static String columnSpackno(){
		 return S_PACKNO;
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 */
	public static String columnSbillorg(){
		 return S_BILLORG;
	}
	/**
	 * Getter S_ORGTYPE , NOT NULL   	 
	 */
	public static String columnSorgtype(){
		 return S_ORGTYPE;
	}
	/**
	 * Getter S_ORIMSGNO, PK , NOT NULL   	 
	 */
	public static String columnSorimsgno(){
		 return S_ORIMSGNO;
	}
	/**
	 * Getter S_ORISENDORGCODE , NOT NULL   	 
	 */
	public static String columnSorisendorgcode(){
		 return S_ORISENDORGCODE;
	}
	/**
	 * Getter S_ORIENTRUSTDATE , NOT NULL   	 
	 */
	public static String columnSorientrustdate(){
		 return S_ORIENTRUSTDATE;
	}
	/**
	 * Getter S_ORIPACKNO, PK , NOT NULL   	 
	 */
	public static String columnSoripackno(){
		 return S_ORIPACKNO;
	}
	/**
	 * Getter I_ALLNUM , NOT NULL   	 
	 */
	public static String columnIallnum(){
		 return I_ALLNUM;
	}
	/**
	 * Getter F_ALLAMT , NOT NULL   	 
	 */
	public static String columnFallamt(){
		 return F_ALLAMT;
	}
	/**
	 * Getter S_CHECK   	 
	 */
	public static String columnScheck(){
		 return S_CHECK;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSorgcode(){
		 return "String";
	}
	/**
	 * Getter S_CHKDATE, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSchkdate(){
		 return "String";
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSpackno(){
		 return "String";
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 */
	public static String columnJavaTypeSbillorg(){
		 return "String";
	}
	/**
	 * Getter S_ORGTYPE , NOT NULL   	 
	 */
	public static String columnJavaTypeSorgtype(){
		 return "String";
	}
	/**
	 * Getter S_ORIMSGNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSorimsgno(){
		 return "String";
	}
	/**
	 * Getter S_ORISENDORGCODE , NOT NULL   	 
	 */
	public static String columnJavaTypeSorisendorgcode(){
		 return "String";
	}
	/**
	 * Getter S_ORIENTRUSTDATE , NOT NULL   	 
	 */
	public static String columnJavaTypeSorientrustdate(){
		 return "String";
	}
	/**
	 * Getter S_ORIPACKNO, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeSoripackno(){
		 return "String";
	}
	/**
	 * Getter I_ALLNUM , NOT NULL   	 
	 */
	public static String columnJavaTypeIallnum(){
		 return "Integer";
	}
	/**
	 * Getter F_ALLAMT , NOT NULL   	 
	 */
	public static String columnJavaTypeFallamt(){
		 return "BigDecimal";
	}
	/**
	 * Getter S_CHECK   	 
	 */
	public static String columnJavaTypeScheck(){
		 return "String";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSorgcode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_CHKDATE, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSchkdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSpackno(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSbillorg(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ORGTYPE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSorgtype(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ORIMSGNO, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSorimsgno(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ORISENDORGCODE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSorisendorgcode(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ORIENTRUSTDATE , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSorientrustdate(){
		 return "CHARACTER";
	}
	/**
	 * Getter S_ORIPACKNO, PK , NOT NULL   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeSoripackno(){
		 return "CHARACTER";
	}
	/**
	 * Getter I_ALLNUM , NOT NULL   	 
	 * columnType is INTEGER
	 */
	public static String columnDatabaseTypeIallnum(){
		 return "INTEGER";
	}
	/**
	 * Getter F_ALLAMT , NOT NULL   	 
	 * columnType is DECIMAL
	 */
	public static String columnDatabaseTypeFallamt(){
		 return "DECIMAL";
	}
	/**
	 * Getter S_CHECK   	 
	 * columnType is CHARACTER
	 */
	public static String columnDatabaseTypeScheck(){
		 return "CHARACTER";
	}
	/******************************************************
	*
	*  Get Column With
	*
	*******************************************************/
	/**
	 * Getter S_ORGCODE, PK , NOT NULL   	 
	 */
	public static int columnWidthSorgcode(){
		 return 12;
	}
	/**
	 * Getter S_CHKDATE, PK , NOT NULL   	 
	 */
	public static int columnWidthSchkdate(){
		 return 10;
	}
	/**
	 * Getter S_PACKNO, PK , NOT NULL   	 
	 */
	public static int columnWidthSpackno(){
		 return 8;
	}
	/**
	 * Getter S_BILLORG , NOT NULL   	 
	 */
	public static int columnWidthSbillorg(){
		 return 12;
	}
	/**
	 * Getter S_ORGTYPE , NOT NULL   	 
	 */
	public static int columnWidthSorgtype(){
		 return 1;
	}
	/**
	 * Getter S_ORIMSGNO, PK , NOT NULL   	 
	 */
	public static int columnWidthSorimsgno(){
		 return 4;
	}
	/**
	 * Getter S_ORISENDORGCODE , NOT NULL   	 
	 */
	public static int columnWidthSorisendorgcode(){
		 return 12;
	}
	/**
	 * Getter S_ORIENTRUSTDATE , NOT NULL   	 
	 */
	public static int columnWidthSorientrustdate(){
		 return 10;
	}
	/**
	 * Getter S_ORIPACKNO, PK , NOT NULL   	 
	 */
	public static int columnWidthSoripackno(){
		 return 8;
	}
	/**
	 * Getter S_CHECK   	 
	 */
	public static int columnWidthScheck(){
		 return 1;
	}
}